### ISSUE TITLE
leisure=track ways no longer rendering

### ISSUE THREAD

**Issue by Jez-C** [gravitystorm/openstreetmap-carto#3369] opened 2018-08-30 05:22 UTC
Ways tagged leisure=track recently stopped rendering both their names and green shading. Only ways have been affected (nodes with names remain visible and relations are still shaded green).

**Comment by HolgerJeromin** [comment] 2018-08-30 06:45
duplicate of #2632

**Closed** 2018-08-30 09:55 UTC
Labels: duplicate
