### ISSUE TITLE
Street name missing characters on some tiles

### ISSUE THREAD

**Issue by sbraz** [gravitystorm/openstreetmap-carto#4642] opened 2022-08-12 00:14 UTC
### Expected behavior
Hi,
For some reason, a road named "Rue Ferdinand Mercusot" appears as "Rue Ferdinercusot" on one page. The object is properly named.

### Actual behavior
The street name should always be displayed properly.

### Screenshots with links illustrating the problem
Here is a screenshot from https://www.openstreetmap.org/#map=19/47.30774/4.70841
![image](https://user-images.githubusercontent.com/4833332/184262096-ddeb44f5-942e-455a-9647-269fd6c1fb78.png)

The problem seems to be at the junction of two tiles:
https://tile.openstreetmap.org/19/268999/183746.png
![image](https://user-images.githubusercontent.com/4833332/184262445-922a64dc-1b19-42c7-9230-22baf4eb0aa7.png)
and
https://tile.openstreetmap.org/19/269000/183746.png
![image](https://user-images.githubusercontent.com/4833332/184262472-1390205d-84ac-4734-860e-42bc49e06166.png)

We can see that the bottom of the _n_ from "Ferdinercusot" is actually the bottom of the _M_ from "Mercusot"

**Comment by imagico** [comment] 2022-08-13 18:48
Thanks for reporting.  This is a duplicate of #3820.

**Closed by imagico** 2022-08-13 18:48 UTC
