### ISSUE TITLE
Stop rendering highway=proposed

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1654] opened 2015-07-14 09:10 UTC
As discussed in #1630 it would be a good idea to remove some of features (either by not rendering tag or by rendering different but similar tags in the same way). It is especially important if new features would be added.

Note that this proposal in not caused by fact that rendering highway=proposed roads is completely pointless. Rather, it is about fact that there are other more important features that would benefit from rendering and/or less busy map.

Why highway=proposed is one of the best candidates for removal.

- highway=proposed, unlike other rendered features is completely impossible to verify on the ground. In the best case it is mapping legal situation. In many cases it is not even this - many projects are simply promised for decades. It is drastically different from admin boundaries - boundaries are well defined[1] and there is possibility of verification on the ground.

- highway=proposed are controversial - it is frequently impossible to decide whatever given project is real or is it pie-in-the-sky idea.

- rendering highway=proposed in default style is considered as endorsement to map other planned/proposed features

- there is no consensus that mapping highway=proposed improves OSM. Note that it is extremely rare example of rendered tag not present in JOSM default preset. I think that Default rendering should not promote controversial tagging schemes.

Also to quote @math1985 (source: https://github.com/gravitystorm/openstreetmap-carto/issues/345#issuecomment-35727968 )

>I even wonder if proposed roads should be rendered at all on an online map. For paper maps, printing the proposed roads makes sense: the road might be constructed when the map is still in use. The same holds for cached offline maps, of course. But an online map can be updated easily, and the information of proposed roads is not much more useful than the information about roads that just have been destructed.

> I suspect we might just be rendering proposed roads out of habits, without actually realizing what the reason for this habit is.

I recognize that for some purposes (discussing proposed road construction) such rendering would be useful. I accept that in some limited situation mappers reached consensus that kept real projects and kept away ones that are unlikely to be ever constructed.

But overall I think that it would be better to stop rendering highway=proposed.

See #908 for previous "Stop rendering highway=proposed" from 2014 and https://github.com/gravitystorm/openstreetmap-carto/issues/345#issuecomment-38289437 for "As for highway=proposed, lets keep rendering it for now, but I'm 50/50 on whether it's something that a standard map style would be involved in." by @gravitystorm from May 2014. 

#345 is related

[1] in rare cases of conflict (see Crimea) conflict itself is also well defined. Yes, there are probably cases of lack of well defined admin boundaries but it is an extreme minority compared to highway=proposed where every single case is completely subjective.

**Comment by kocio-pl** [comment] 2015-07-14 09:47
I am not so eager to remove them, but on the other hand all your arguments are completely valid, so this may be just my reluctance.

**Comment by vincentdephily** [comment] 2015-07-14 11:59
To me the strongest argument here is that some highway=proposed are much less likely than others. We don't want to render the unlikely ones, but (I strongly believe) we should render the likely ones (although the changes to render them less prominently were a good thing).

This situation sounds very much like railway=abandoned vs disused. Except that highway=planned (the best candidate for "really likely feature") is barely used compared to highway=proposed (159 vs 38k). If it was more widespread, I'd support rendering "planned" but not "proposed". Maybe if osm-carto rendered both values for a year, it'd give mappers time to migrate relevant cases from one to the other, after which we could stop rendering "proposed" ?

As for an example of something that merits rendering, I present my very own [kilkenny CAS](http://www.openstreetmap.org/?mlat=52.65695&mlon=-7.25252#map=17/52.65695/-7.25252&layers=N) which was fully financed and scheduled when I added it to OSM. Right now the bridge section is under construction, and construction of the other sections are expecte to begin next year. The local controvery against the project included some FUD about its location, so having it rendred somewhere accessible is really usefull. Maybe my jugement is clouded, but I really think that this kind of planned development should be rendered.

**Comment by kocio-pl** [comment] 2015-07-14 12:20
IMO you're right. I think this is a case where we should get in touch with tagging department (namely Tagging list), because it requires kind of coordination between tagging things and rendering them.

**Comment by aceman444** [comment] 2015-07-14 16:15
+1 for the =planned and =proposed distinction and only rendering the planned ones.

**Comment by HolgerJeromin** [comment] 2015-07-14 17:49
The idea is really nice, but needs discussion and a proper documentation on the wiki. 
The wikipage should extremly focus on the livecycle of a street:
proposed -> planned -> construction -> trunk (or whatever)
to have no proposed street tagged as a planned street without a reason.

**Comment by kocio-pl** [comment] 2015-07-14 18:05
[I have just started this discussion](https://lists.openstreetmap.org/pipermail/tagging/2015-July/025630.html), so we can talk about it on Tagging list. However it's been already pointed out, that [planned is a duplicate of proposed on Wiki](http://wiki.openstreetmap.org/wiki/Lifecycle_prefix#Common_lifecycle_prefixes).

**Comment by math1985** [comment] 2015-07-14 18:11
I'd still rather not render planned roads. There is only so much we can render on the main style, and objects without physical presence are a prime candidate to be left out.

**Comment by math1985** [comment] 2015-07-14 18:16
[This way](http://www.openstreetmap.org/way/290450974/history) is really an argument against rendering highway=proposed.

**Comment by matkoniecz** [comment] 2015-07-14 18:24
For reference - somebody decided to draw highway=proposed across Bering Strait and I just deleted it in https://www.openstreetmap.org/changeset/32634578 . 

> For roads that are about to be built, but where any construction work hasn't yet been started.

http://wiki.openstreetmap.org/wiki/Tag:highway%3Dproposed

**Comment by matkoniecz** [comment] 2015-07-14 18:28
> I'd still rather not render planned roads.

Yes, the same arguments why rendering highway=proposed is a poor idea apply also to highway=planned. In addition highway=planned is extremely rarely used.

**Comment by imagico** [comment] 2015-07-14 18:33
I tend to concur that proposed highways are not suited for mapping due to lack of verifiability and therefore should also not be rendered.  Planned might be a different thing when there are clear criteria that are documented and followed by mappers on what stage in the planning is necessary to qualify (most jurisdictions have clear rules on planning stages of construction work).  This is not the case at the moment.

**Comment by daganzdaanda** [comment] 2015-07-15 14:51
I have added proposed streets sometimes, after the official development plans were released by the local authorities. These things usually get built quickly here. But I also know of "proposed" roads that are in legal or financial limbo. 
Since it's not possible to check easily if a "proposed" or "planned" road that's been last touched 5 years ago still is valid, I agree that the cleanest solution is to not render these at all. 
I still would love to have them in some specialist map that's available from the main page, though.

**Comment by lest69** [comment] 2015-07-16 17:42
While I initially didn't like the idea of losing the proposed roads, good cases have been made here for not rendering them, including the lack of verifiability and inconsistency surrounding the likelihood of the road actually being built. If mappers end up using a better system in the future (e.g. more widespread use of proposed/planned distinction), this matter could always be revisited to consider rendering something again.

**Comment by jzvc** [comment] 2015-07-17 15:18
In some countries (cz for me) proposed/planned main (motorway/primary) roads are on every maps - paper included. And, sources are exactly defined - from public government sources.

**Closed** 2015-07-21 22:57 UTC
Labels: roads

**Comment by rudolfmayer** [comment] 2015-08-14 12:15
I agree with potentially too many highway=proposed being around, and indeed a number of them just pure speculation - but I don't agree with highways that are already confirmed but not yet built not being rendered at all, and I would like projects where the route has been confirmed to be displayed.

Highway=planned is maybe semantically too close to "proposed", but a separate distinction would indeed be useful to distinguish proposals from an agreed and approved route, and could be rendered accordingly.

**Comment by dammat** [comment] 2015-09-29 21:32
Hello from Poland

Big roads construction company contacted with OpenStreetMap Community via polish mailing  list with question why they cannot see planned roads:

https://lists.openstreetmap.org/pipermail/talk-pl/2015-September/002003.html

I think its great that OSM Maps are so usefull even for professional use, so we should't make it harder and unpredictable. Its one of many voices requested to restore visibility of this roads.

Would you please consider to restore rendering highway=proposed?

Thanks in advance

Best Regards

**Comment by pnorman** [comment] 2015-09-29 23:27
After reconsidering and looking at the data, I still think dropping rendering of proposed roads is best.

**Comment by emsi** [comment] 2016-08-17 14:10
Could you enable rendering the proposed roads? It was the sole reason I was using OSM rather than google.
At least there should be an option to enable it.

**Comment by kocio-pl** [comment] 2016-08-17 14:35
Unfortunately there's no options in this style, it produces static raster maps and OSM website doesn't have useful dynamic layers (other than data view).

**Comment by emsi** [comment] 2016-08-17 15:57
Straszna kicha. :(
Fortunately I found a way to render it on my own with Maperitive and custom rendering rules. It requires a bit of processing power but is sufficient for my purposes although I preferred original rendering rules.
Do you know where I can find the legacy rendering rules that were used prior to the removal. Are they stored in the git?

**Comment by kocio-pl** [comment] 2016-08-17 16:02
Sure, see here https://github.com/gravitystorm/openstreetmap-carto/pull/1663/files
