### ISSUE TITLE
Render building=greenhouse with different color

### ISSUE THREAD

**Issue by printmaps** [gravitystorm/openstreetmap-carto#4026] opened 2020-02-09 14:07 UTC
Link to data:
https://www.openstreetmap.org/#map=15/52.7042/4.8352

Current rendering:
<img width="800" alt="Bildschirmfoto 2020-02-09 um 15 01 22" src="https://user-images.githubusercontent.com/26689799/74103609-ba657e00-4b4d-11ea-8401-776d9d3fd4ab.png">

Recommended rendering:
<img width="800" alt="Bildschirmfoto 2020-02-09 um 15 01 51" src="https://user-images.githubusercontent.com/26689799/74103610-c2bdb900-4b4d-11ea-8982-036c11a78b3f.png">

**Comment by imagico** [comment] 2020-02-09 14:19
Duplicate of #738 - which had been incorrectly closed so it is understandable you did not find it.

The suggested rendering won't work because it is similar to glacier rendering.

**Closed by imagico** 2020-02-09 14:19 UTC
