### ISSUE TITLE
Some labels for countries, provinces, etc are not at the position one would expect

### ISSUE THREAD

**Issue by K4LCIFER** [gravitystorm/openstreetmap-carto#4494] opened 2021-11-28 01:52 UTC
### Expected behavior
A country's, province's, etc name is expected to be in the center of the mainland.

### Actual behavior
The label is being centered to what I'm guessing is the mercator projection.

### Links and screenshots illustrating the problem
As shown below for Canada, I have labeled where the name of the country currently is in red, and "logically" where it should be in blue. 
![image](https://user-images.githubusercontent.com/7829231/143725841-1b319f3f-df70-4505-b735-2755259fe117.png)
An example of where Google Maps places the name for Canada as an example.
![image](https://user-images.githubusercontent.com/7829231/143725863-4e3208d9-e3de-4dc0-abbc-e53f9fa0e8c9.png)
Same thing for the Northwest Territories, and Nunavut in Canada:
![image](https://user-images.githubusercontent.com/7829231/143725922-5a439c7e-a693-4969-8cd8-350ecffde817.png)

**Comment by imagico** [comment] 2021-11-28 11:07
Duplicate of #4241 (which is slightly more specific but cause and solution of the problem are the same).

N.b.: Google AFAIK uses hand placed label locations at small scales.

**Closed by imagico** 2021-11-28 11:07 UTC
