### ISSUE TITLE
Road in tunnel appears on top of car park

### ISSUE THREAD

**Issue by csmale** [gravitystorm/openstreetmap-carto#1911] opened 2015-10-12 12:30 UTC
I can see a layer/Z-order problem here:

http://www.openstreetmap.org/#map=18/52.09631/5.06956

The motorway is underground, and other roads, buildings and car parks are above the ground. I would expect the car park area to be rendered above the tunnelled motorway.

The problem is also visible with other objects - it seems that the motorway in a tunnel is getting rendered far too high.

Can anything be done to fix this?

**Comment by matkoniecz** [comment] 2015-10-12 12:52
Duplicate of #1609 #623 and others (see https://github.com/gravitystorm/openstreetmap-carto/search?q=road+underground&type=Issues&utf8=%E2%9C%93 for start). This intentional - rendering underground roads under features on the ground would make them invisible.

**Closed by matkoniecz** 2015-10-12 12:52 UTC
Labels: duplicate
