### ISSUE TITLE
trunk_link and other links should be narrowed

### ISSUE THREAD

**Issue by newnumber2** [gravitystorm/openstreetmap-carto#2644] opened 2017-05-25 22:37 UTC
Ways tagged highway=motorway_link are rendered with a narrower line than ways tagged highway=trunk_link, highway=primary_link, highway=secondary_link, and highway=tertiary_link.
This should not be so.  I highly suggest that all "links" be rendered with same width of line as motorway_link.  There are many instances where the width of the line creates a poor cartographic appearance (when the widths of a way tagged highway=trunk and a way tagged highway=trunk_link  are the same).

Also, I would really like to see ANY highway=xxxxxx_link ways rendered below the other ways they intersect, never above (looks terrible).

Two screen shots are attached  (from the same area) showing both motorway links and trunk links as they are presently rendered. In this case, the trunk links don't look too bad because they are rendered underneath the tertiary street (Wooddale Avenue South) that they intersect). However, if motorway links are to be rendered with narrower lines than highway=motorway, other links should follow that example.
![screenshot 2017-05-25 16 27 26](https://cloud.githubusercontent.com/assets/5266966/26473398/576c4d52-4168-11e7-8fa2-b4864d894134.png)
![screenshot 2017-05-25 16 27 52](https://cloud.githubusercontent.com/assets/5266966/26473399/576e9f80-4168-11e7-98e7-09c06cf0aab1.png)

**Comment by math1985** [comment] 2017-05-25 22:54
> Also, I would really like to see ANY highway=xxxxxx_link ways rendered below the other ways they intersect, never above (looks terrible).

That should be the case currently, do you have an example where link roads are rendered above other ways?

**Comment by newnumber2** [comment] 2017-05-25 23:24
I don't have any examples at the moment, but I see them fairly often,so I could send you another reply w/ a screen shot attached when  I do.


Be seeing you,

David J. Wisbey

(720) 282-3626



On Thursday, May 25, 2017, 4:54:35 PM MDT, Matthijs Melissen <notifications@github.com> wrote:

Also, I would really like to see ANY highway=xxxxxx_link ways rendered below the other ways they intersect, never above (looks terrible).


That should be the case currently, do you have an example where link roads are rendered above other ways?

**Comment by kreed** [comment] 2017-05-26 13:48
Duplicate of #1109

**Comment by math1985** [comment] 2017-05-26 14:10
Closing as duplicate.

**Closed by math1985** 2017-05-26 14:10 UTC
Labels: roads

**Comment by newnumber2** [comment] 2017-05-26 20:37
Looks like it has been forgotten, though.I would like to bring attention back to itand actually see something done. Surelyit can't be that hard to do.


Be seeing you,

David J. Wisbey

(720) 282-3626



On Friday, May 26, 2017, 8:10:44 AM MDT, Matthijs Melissen <notifications@github.com> wrote:
Closing as duplicate.

**Comment by nebulon42** [comment] 2017-05-27 09:30
> and actually see something done. Surely it can't be that hard to do.

Please try to be careful with statements like that. It is quite likely interpreted as a kind of attitude that is not helpful in any way. While we have an abundance of issue commenters we don't have many people actually writing code. So I suggest that you try and give it a shot. We're happy to provide help on the way.

**Comment by newnumber2** [comment] 2017-05-27 21:18
It's true that I don't know exactly how these things are done.I just assumed that making the changes I'm recommendingwould be pretty easy to do. I don't have experience writingcode; in fact, I didn't think you would need to do that to makethe changes (I thought you had a program that made it easy).


Be seeing you,

David J. Wisbey

(720) 282-3626



On Saturday, May 27, 2017, 3:30:22 AM MDT, Michael Glanznig <notifications@github.com> wrote:

and actually see something done. Surely it can't be that hard to do.


Please try to be careful with statements like that. It is quite likely interpreted as a kind of attitude that is not helpful in any way. While we have an abundance of issue commenters we don't have many people actually writing code. So I suggest that you try and give it a shot. We're happy to provide help on the way.
