### ISSUE TITLE
national park on a way not rendered

### ISSUE THREAD

**Issue by aceman444** [gravitystorm/openstreetmap-carto#1727] opened 2015-08-06 20:48 UTC
I noticed that the national park "Tatranský národný park" on way 38321675 is not rendered on osm.org (the think green border). Notice the neighbouring park "Tatrzański Park Narodowy" on way 95108528 is rendered. Maybe the difference is that the former has the tags directly on the way and the latter has a relation for the national park?
But the wiki allows boundary=national park on a way and also it is used in that way often: http://taginfo.openstreetmap.org/tags/boundary=national_park . Or is the way just too long (~1500 nodes)?

**Comment by matkoniecz** [comment] 2015-08-06 21:09
Duplicate of The boundary=national_park tag is not rendered when tagged on a closed way (not a relation) #1141 

In other words - tagging is OK, rendering is wrong.

**Closed by matkoniecz** 2015-08-06 21:09 UTC
