### ISSUE TITLE
Polygon icons shown outside polygon

### ISSUE THREAD

**Issue by Skippern** [gravitystorm/openstreetmap-carto#2613] opened 2017-04-17 23:12 UTC
Don't know exactly where to report this, but after adding landcover around a POI mapped as a polygon, I noticed that the icon symbol rendered on the map is shown outside the POI polygon, but in one of the surrounding landcover polygons. See [0]. The polygon shape would not have the center of gravity where the icon is rendered, so I suspect there is something fishy about icon placement.

[0] [Parque Yahoo](https://www.openstreetmap.org/#map=18/-20.20115/-40.21354)

**Comment by pnorman** [comment] 2017-04-18 02:20
Duplicate of #1465

**Closed by pnorman** 2017-04-18 02:20 UTC
Labels: duplicate
