### ISSUE TITLE
Rendering of canal bridges vs canal tunnels

### ISSUE THREAD

**Issue by andischan** [gravitystorm/openstreetmap-carto#2562] opened 2017-02-02 15:56 UTC
Canal tunnels (waterway=canal + tunnel=yes) get rendered beginning with zoomlevel 12.

![p14](https://cloud.githubusercontent.com/assets/24589670/22556547/d3402aba-e967-11e6-9b1c-1a1ba265a794.png)

Canal bridges (waterway=canal + bridge=aqueduct) join them not before zoomlevel 15.

![p15](https://cloud.githubusercontent.com/assets/24589670/22556546/d3395a14-e967-11e6-8b1d-ea3371246e6d.png)

Especially in China we have irrigation canals with many bridges & tunnels and the holes in the bridge parts of them are quite disturbing.

**Comment by imagico** [comment] 2017-02-02 16:06
According to the code:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/water.mss#L103

canals are rendered from z12 independent of bridge/tunnel tags and the bridge casing is rendered from z14.  Your observation probably has a different reason, likely due to the map tiles not being up-to-date.

**Comment by SomeoneElseOSM** [comment] 2017-02-02 17:50
Taginfo doesn't find any "way["tunnel"="aqueduct"]["waterway"="canal"];" so presumably you meant something else; @andischan maybe ask a question on the help site about it, and include an example URL so that people can examine the data there?

**Comment by dieterdreist** [comment] 2017-02-02 17:57
2017-02-02 18:50 GMT+01:00 SomeoneElseOSM <notifications@github.com>:

> Taginfo doesn't find any "way["tunnel"="aqueduct"]["waterway"="canal"];"
> so presumably you meant something else; @andischan
> <https://github.com/andischan> maybe ask a question on the help site
> about it, and include an example URL so that people can examine the data
> there?
>


I guess it was a typo and s/he  meant bridge=aqueduct

Ciao,
Martin

**Comment by imagico** [comment] 2017-02-04 16:15
Closing since the observation described does not seem to be an error in this style.

**Comment by andischan** [comment] 2017-02-08 17:49
@imagico Sorry, I had no internet connection for two days. May you please reopen the thread? Indeed I meant "bridge" and not "tunnel".

**Comment by andischan** [comment] 2017-02-08 17:50
Now there is a ![white signature](https://cloud.githubusercontent.com/assets/24589670/22749941/53b1bb7a-ee2f-11e6-84ec-4df52bbdd0d3.png) for the bridge parts of a canal.

--> [Location](http://www.openstreetmap.org#map=13/37.5068/120.2701)

**Comment by imagico** [comment] 2017-02-08 19:13
Ah, yes, sorry - structure of the code regarding water lines is somewhat confusing.

At a quick glance it seems the cause of this is a too high minzoom for the waterway-bridges layer:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L1127

Have not tested if this is truly the only thing that needs to be changed though.

**Closed** 2017-03-22 22:22 UTC
Labels: bug, water
