### ISSUE TITLE
Missing railways at z12

### ISSUE THREAD

**Issue by Vort** [gravitystorm/openstreetmap-carto#1296] opened 2015-02-08 05:08 UTC
There is no railways at zoom 12 with the latest update 
http://a.tile.openstreetmap.org/11/1229/694.png
http://c.tile.openstreetmap.org/12/2459/1389.png
http://a.tile.openstreetmap.org/13/4919/2779.png

**Comment by pnorman** [comment] 2015-02-08 05:48
barring other evidence, duplicate of #1294

**Comment by math1985** [comment] 2015-02-08 10:22
Confirmed in master.

**Comment by pnorman** [comment] 2015-02-08 10:54
offhand I see nothing in https://github.com/gravitystorm/openstreetmap-carto/compare/v2.27.0...v2.28.0 to casue this.

min/max zoom were added to the roads layers which include railways, but I can't see why that would cause it. If did cause a problem I'd expect it to also impact roads.

@math1985 on your setup if you checkout v2.27.0 does it render?

**Closed** 2015-02-08 20:42 UTC
