### ISSUE TITLE
Labels on top of bridges of elements that are underneath them 

### ISSUE THREAD

**Issue by alfmarcua** [gravitystorm/openstreetmap-carto#4422] opened 2021-06-14 11:41 UTC
### Expected behavior
Elements that are underneath bridges should not display its labels on top of them. They shall be displaced so labels do not collide with the bridge.

### Actual behavior
At certain zoom levels, rivers or roads that are underneath bridges have their labels on top of corresponding bridge.

### Links and screenshots illustrating the problem

Bridge: https://www.openstreetmap.org/way/25752465#map=15/41.9008/12.4656
River: https://www.openstreetmap.org/way/547426106#map=15/41.9039/12.4644

![bridge_river](https://user-images.githubusercontent.com/25908318/121886133-57719180-cd15-11eb-8719-8dab3afe1b03.png)

Bridge: https://www.openstreetmap.org/way/22989460#map=15/41.8679/12.4667
Road: https://www.openstreetmap.org/way/168856392#map=15/41.8705/12.4661
![bridge_road](https://user-images.githubusercontent.com/25908318/121886701-0615d200-cd16-11eb-9665-fcd122b1d9bd.png)

**Comment by alfmarcua** [comment] 2021-06-14 11:51
It is related with #478 and #4401

A partial humble solution to this issue could be to have a phantom label for bridges that displaced the others. In particular, it could be achieved by giving a label style with opacity 0 to the bridges whenever their own label it is not displayed.

**Comment by imagico** [comment] 2021-06-14 15:15
Duplicate of #478 and #4401 - please discuss possible solutions there.  For wider context see also See also #497, #951, #2213.

**Closed by imagico** 2021-06-14 15:15 UTC
