### ISSUE TITLE
Group multiple same road junction labels into one

### ISSUE THREAD

**Issue by donaldrnoble** [gravitystorm/openstreetmap-carto#1992] opened 2015-12-04 10:47 UTC
Would it be possible to group the multiple labels that often appear on road junctions into one. 

Each side of the junction is usually tagged where the slip roads leave the main road, and both of these then get a label. This adds clutter, and can be confusing, especially where there are multiple junctions close to each other, e.g. the Edinburgh bypass 
![screen shot 2015-12-04 at 10 36 50](https://cloud.githubusercontent.com/assets/6844639/11587718/35eb4c16-9a73-11e5-98c5-3ac60c6cc63f.png)
http://www.openstreetmap.org/#map=13/55.9007/-3.1834

The transport layer seems to have a similar feature which groups bus stops with the same name together.

I would imagine that a distance limit (of say 1km) would need to be applied, and only identical labels grouped together, to avoid over-aggregating. This might miss a few edge cases, but should prevent information being lost in the map display.

Removing some of the junction labels will obviously simplify the map, and map allow other useful information to be displayed without the map becoming too cluttered.

**Comment by matkoniecz** [comment] 2015-12-04 13:28
https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md#data-manipulation is relevant

**Comment by sommerluk** [comment] 2015-12-05 17:23
The problem is: The defination of highway=motorway_junction treats each of these nodes as individual object, so that each motorway junction node is independant from all others. This tagging scheme probably works well for some countries where a motorway junction may have a different name, depending of the direction from which you are coming. But it does not work well for other countries like Germany, where all incoming/outgoing junctions at one place usually share the same name.

If the style tries to “guess” which junction labels are duplicate, that requires a lot of magic. It would be a hack that works around missing information in the database. A cleaner solutin would be a tagging scheme that supports such cases (for example a relation that groups existing highway=motorway_junction nodes to stay as compatible as possible and that can have a name=* tag on the relation). However, that’s out of scope of this issue tracker and could be discussed on the tagging mailing list.

**Comment by matkoniecz** [comment] 2015-12-05 17:29
> The transport layer seems to have a similar feature which groups bus stops with the same name together.

Note that this feature sometimes fails, for bus stops in one group separated by distance higher than expected.

**Comment by matkoniecz** [comment] 2016-03-28 19:48
I am not sure whatever data processing is in that case desirable, especially as border between "too close labels not grouped together" and "overaggregation" is fluid.

I think that in this case potential improvement in rendering is not worth obscuring data.

**Closed** 2016-03-29 07:07 UTC
Labels: enhancement, roads
