### ISSUE TITLE
Too many icons at z17?

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1560] opened 2015-05-20 12:46 UTC
z17 might start getting crowded within cities. Example from @SomeoneElseOSM http://www.openstreetmap.org/#map=17/52.95354/-1.14638

I'm not sure if this can be considered a problem, but maybe a discussion is needed if some POIs should get rendered only at higher zoom levels e.g. some shops. For shops we could also switch from a two-tier to a three-tier rendering process.

See also https://github.com/gravitystorm/openstreetmap-carto/issues/1460#issuecomment-103860484, https://github.com/gravitystorm/openstreetmap-carto/issues/1460#issuecomment-103862526, https://github.com/gravitystorm/openstreetmap-carto/issues/1460#issuecomment-103862597.

**Comment by joakimfors** [comment] 2015-05-20 14:08
IMHO that doesn't look like a problem as it pretty accurately describes the street level appearance of areas crowded with shops and cafés. It also helps with navigation as you quickly realise where the busiest areas of a town/city is without obscuring the road network.

**Comment by imagico** [comment] 2015-05-20 16:25
This is a more general problem and not specific to POIs - in fact it is almost the same as #1143.  It comes from the fact that icons and labels of a certain type are generally simply drawn until the map is full - which is always a bad idea since the map needs to show other features as well.

And note the shown example is from 53 degrees latitude where the map already offers more than twice the real estate compared to around the equator.

**Comment by nebulon42** [comment] 2015-05-20 16:41
I thought #1143 results out of a tagging/classification deficiency where we cannot decide to leave out unimportant airports easily whereas we can always decide which POIs to render on a certain zoom level.

**Comment by imagico** [comment] 2015-05-20 17:03
It's the same problem, you want to display features on an early zoom level since in some areas they are rare and if they exist they are important while in areas where they are abundant you only want to display the more important ones.

The rating problem also exists for shops - when they are as dense as in the example which shops are shown and which left out is fairly arbitrary.  If you now decide shop type A is more important than shop type B and is rendered at an earlier zoom level and with higher priority at the later zoom levels this will essentially be an overall importance rating based on shop type which is not really a good importance measure.  Using an objective quantity - like length of a nearby runway in case of airports or area of the building the node is located in for shops - could be much better.

**Comment by nebulon42** [comment] 2015-05-20 17:10
True.

**Comment by SK53** [comment] 2015-05-20 21:14
The example is Nottingham which is quasi-complete for shops. I'm rather pleased that working to completely map a particular feature type also works as a stress test for the cartography. On top of the scaling effects mentioned by @imagico its worth considering that in many places closer to the equator shop density will in practice be much higher than in a western city: many more markets, small kiosks, bazaars etc. The market has been mapped (http://www.openstreetmap.org/#map=18/52.95633/-1.14630), as has the adjacent shopping mall which has shops on multiple levels (handled by offsetting nodes on the upper level from those on lower level). Another aspect is that I dont think that treating shops in isolation will work cleanly: they have to be considered in conjunction with other elements representing retail outlets (e.g., fast_food, pharmacy, post_office etc).

I'm not offering any solutions, but would be happy to work on anything where we could add further information to the data which might help in the future. (I have tagged one or two retail outlets with the sales floor area, but its unlikely that this will be feasible for them all, or practical on a global basis: these have been vacant shops where the figures have been on the TO LET noticeboard).

**Comment by pnorman** [comment] 2015-05-21 07:10
I think the problem is too many different icons, and if we cut back on the distinct icons for some of the less common shop types it might help. This is why we had the generic icon, to avoid having lots of different icons for each shop type, not because it was work to create icons, but because it's undesirable to have too many icons.

I also think the clothing icon is a bit strong compared to the others.

**Comment by AnBuKu** [comment] 2015-05-21 07:30
Indeed, the overall look&feel becomes a little bit "crowded". Does it make sense, to have dozens of variations of e.g. key=shop ? Without provoking a discussion about relevancy/importance of this or that icon, imho it might make more sense to have a generic icon for office (e.g. government offices, business offices, latter potential OSM sponsors), as there is no one at all; but a specific icon for waste bin... but, who knows, waste bins might become sponsors too. :-)

**Comment by kocio-pl** [comment] 2015-05-21 08:15
> Does it make sense, to have dozens of variations of e.g. key=shop ? 

1. If I thought otherwise, I wouldn't try to design them... =} What's the use of generic icon without showing what you can buy (the name alone can be a puzzle)? That would just mean "you can spend some money here" and landuse=retail is not much different. We can (and do) render the same icon for some types if they are close enough, because it's not useful to try to depict everything, but showing at least the type of stock is very important for users IMO and we don't even have the icons for all extremely popular (>10k uses) shops yet!

2. How much places have - and will ever have - this problem? @joakimfors is right: that is not more a problem than complaining, that the desert area is almost empty - this is reality and not that frequent.

3. On z>=19 (and even on z>=18 in this example) this is not a problem, so even if I may be reluctant to repair just one zoom level in a highly specific place, I would support making tiers as @nebulon42 said. But as for me, that is rather solution for the future. Today I would rather try to show real layers in multiple level places like malls or railway stations. Berlin Hauptbahnhof is a good example: it's much less readable at _any_ zoom level than Nottingham on z17 and you can't plan how to get anywhere inside it or even see the building shape.

**Comment by dieterdreist** [comment] 2015-05-21 08:32
> Am 21.05.2015 um 09:10 schrieb Paul Norman <notifications@github.com>:
> 
> This is why we had the generic icon, to avoid having lots of different icons for each shop type, not because it was work to create icons, but because it's undesirable to have too many icons.


I don't agree here, this would make sense if we'd omit certain types completely, but showing a generic icon rather than a specific one is not desirable as a goal and will not help to avoid cluttering

**Comment by dieterdreist** [comment] 2015-05-21 08:39
> Am 21.05.2015 um 10:15 schrieb kocio-pl <notifications@github.com>:
> 
> Berlin Hauptbahnhof is a good example: it's much less readable at any zoom level than Nottingham on z17 and you can't plan how to get anywhere inside it or even see the building shape.


for those that don't know the place, that's like a shopping mall on 5 floors, we'll never ever be able to display this in a simple 2D rendering in a way that it can be understood (actually it's 3 shopping floors in the middle and one train floor in the underground and one on top)

**Comment by dieterdreist** [comment] 2015-05-21 19:47
2015-05-21 10:15 GMT+02:00 kocio-pl <notifications@github.com>:

> Berlin Hauptbahnhof is a good example: it's much less readable at *any*
> zoom level than Nottingham on z17
>


it also isn't mapped in a way that would make it easy to understand from
looking at it. Those connections (footways) that cross diagonally have no
corrispondance to something in the real world, they are actually shortest
ways across more or less rectangular, wide areas (i.e. a graph
representation suitable for routing but not for rendering):
http://www.openstreetmap.org/#map=19/52.52562/13.36917

**Comment by mboeringa** [comment] 2015-05-24 20:38
I think there is one fairly straightforward solution to this problem, but it requires the Standard style using more distinction in building types:

- Don't render any shop icons before Z19
- Render **building = retail** at all other zoomlevels with a distinct color

This is what I do, see the examples below. The muted pink colored buildings are tagged with **building = retail**, a fairly common practice in the Netherlands. You can clearly distinguish the main "Kalverstraat" shopping street in the hart of Amsterdam... It is certainly not a complete picture, but does the job fairly well of telling you where to go for shopping. In the Netherlands, the tagging for this is pretty good in quite a bit of places.

Unfortunately, for the Nottingham example, I noticed that few buildings, *if any*, seem to be tagged like that...

![amsterdam_building_retail](https://cloud.githubusercontent.com/assets/7635726/7789547/76e69f1e-0265-11e5-9c05-eb27c80d1fc9.png)

**Comment by kocio-pl** [comment] 2015-05-24 20:50
Many buildings have only street level for retail and all above for apartments, so it's not clear how to tag them ("building=apartments;retail" uses semicolon and it is avoided by many mappers). 

And z>=19 for all the shop icons is much too far for me.

**Comment by mboeringa** [comment] 2015-05-24 21:16
> Many buildings have only street level for retail and all above for apartments, so it's not clear how to tag them ("building=apartments;retail" uses semicolon and it is avoided by many mappers).

That is an unsolvable issue that can only be dealt with pragmatically (as has been done in the Netherlands by setting a lot of them to simply builing = retail, as that is probably the main function the mappers wished to convey).

In the end, I think many cartographic solutions rely on the willingness to be a bit pragmatic... there is just no way you are going to solve everything.

Looking at the specific Nottingham example, you might be able to get away with Z18 and have a fairly acceptable density of shops, that just leaves the point @imagico raised about the actual density of shops being significantly distorted due to the Web Mercator projection, in favour of high latitudes ---> less dense appearance of shops due to "more cm2's on the map for a given real world square meter" compared to low latitudes equatorial. The effect of this with a projection like Web Mercator is far bigger than we generally realize, the area distortion is pretty dramatic. Good of @imagico to raise the issue, as we tend to forget this all to easily...

**Comment by math1985** [comment] 2015-05-24 22:48
One way to tackle this would be to render purple dots only on z17, and render the specific icons only on z18+ .

**Comment by mboeringa** [comment] 2015-05-24 23:05
That's another pragmatic solution... given the fact that there is already a fair amount of "purple dots" at Z17 in the Nottingham example, that may not be a bad idea.

**Comment by kocio-pl** [comment] 2015-05-25 09:58
I feel like we're trying to fix very specific issue with general tools, so I would first like to know:
- how many places have this problem now,
- how big could it be in the future,
- what may be potential downsides,
- how many less with lesser shop density places would suffer.

It would be less of an issue for me if we have some other style available, where there would be more details, but currently on OSM website only Humanitarian have more icons (and z20, which is useful in such places), but is as pale as MapQuest Open and doesn't use colors for icons, so the POIs are less visible than on default map.

**Comment by math1985** [comment] 2015-05-25 10:04
[Luxembourg](http://www.openstreetmap.org/#map=17/49.61166/6.13061)

**Comment by kocio-pl** [comment] 2015-05-25 10:57
Such examples are just a partial response for only first question. I am fully aware that the problem exist, but let's try to see the scale of it (worldwide if possible) and if the cure is not worse than the disease...

We have no "shop density-meter" (similar to way_area), but I have the other, even simpler idea for points: I guess there is some area around the icon which is supposed to be free. If there's no enough space around, some icons are not rendered. What if:
- we let this space be bigger on z17 (=more aggressive rendering restrictions) and 
- try to render generic dots when the real icon would be not rendered?

This way we would act only locally - and I prefer dynamic solutions over static ones, because the world is very diverse.

It also reminds me of restaurants, theaters and the likes, which can also be [the same kind of problem](http://www.openstreetmap.org/#map=17/51.51064/-0.13092) in touristic places for example. They would need a generic brown icon and it makes sense for me.

We still don't have something like this for lines probably (see the problem with footways, that can be too much in some places like cemeteries or allotments, while being essential in some remote ones), but it would help to have something like this too, so not only areas and points can be adjusted according to size or density.

**Comment by mboeringa** [comment] 2015-05-25 14:48
> Such examples are just a partial response for only first question. I am fully aware that the problem exists, but let's try to see the scale of it (worldwide if possible) **and if the cure is not worse than the disease...**

I think this is a rather personal preference, considering all the discussions that have been going on here on the issue tracker regarding rendering, not just shops... I feel the current rendering of shops is unacceptable at Z17, but I respect others may think otherwise.

Your suggestions of adjustments to labelling and more restrictive rendering restrictions are good, they should be part of the package to solve this, as this is just common cartographic sense to employ such techniques.

**Comment by kocio-pl** [comment] 2015-05-25 15:07
> I think this is a rather personal preference, considering all the discussions that have been going on here on the issue tracker regarding rendering, not just shops... I feel the current rendering of shops is unacceptable at Z17, but I respect others may think otherwise.

Of course, I just want us to try think wider and I was trying to achieve it asking these questions. The end is always "political" (some decisions have to be made), but it's better to say "I'm aware of this, but other things are more important" than simply ignoring some aspects.

**Comment by pnorman** [comment] 2015-05-25 18:33
There's two separate issues - the number of shops rendered, and the number of distinct icons in the style for shops.

**Comment by kocio-pl** [comment] 2015-05-25 19:00
For me the number may be lowered when there's not too much space between them, but I think we have much too few shop icons - even for very common or distinct types. It's one of many problems with scale we have: micromapping shows me a lot of missing things, while at the lowest zoom they should be hidden (like trash cans) or just simplified (highways have no proper shape on the highest zoom levels).

**Comment by Rovastar** [comment] 2015-05-26 02:04
Can someone please explain what the problem with the current rendering is? I cannot see any.

**Comment by mboeringa** [comment] 2015-05-26 19:16
> Can someone please explain what the problem with the current rendering is? I cannot see any.

Have you looked at the Nottingham example the OP pointed out in the first post here?...

**Comment by Rovastar** [comment] 2015-05-27 20:01
Yes and I am still asking the question. That is my point I don't consider this an issue really. There are loads of shops in a dense area and we have mapped them. Sure there are a lot but it is a city centre which has a lot of shops.
I prefer this to the dumbed down Google view where no shops are displayed at all at the same view so I have no idea where the city centre is.

**Comment by kocio-pl** [comment] 2015-05-27 20:26
I also think this way of MapQuest Open: it's pale and has just a few existing POIs, so looks like a perfect for being the background for some independent services. But we have it on the main website - I don't understand it, but OK, cool... Humanitarian is also pale, but it has a lot of POIs and z20 - and I don't have a clue what's that for: it doesn't look like a background, but doesn't highlight anything also. Strange and confusing for me. (other 2 styles are not general, so they don't count).

Now the default map is also more pale (after building rendering change), but at least we have strong POIs on it, so it looks like it's designed with POIs in mind and it makes a lot of sense for standalone map. So I try try to act carefully to not loose that positive feeling.

**Comment by joakimfors** [comment] 2015-05-28 08:48
> […] I don't consider this an issue really. There are loads of shops in a dense area and we have mapped them. Sure there are a lot but it is a city centre which has a lot of shops.
> I prefer this to the dumbed down Google view where no shops are displayed at all at the same view so I have no idea where the city centre is.

++;

**Comment by dieterdreist** [comment] 2015-05-28 09:18
I also won't consider this an issue (but rather a feature), and I want to
point out that you can find very dense situations also for other types of
pois, not just shops, and it might be justified like here:
http://www.openstreetmap.org/#map=16/41.8901/12.4867  (archeological sites
in z16 is ok IMHO; but here it leads to icon clustering)

or not, like here (IMHO mistagging of memorial and monument):
http://www.openstreetmap.org/#map=19/41.90221/12.45628 (look at the
"memorials" and "monuments" that are actually statues part of the
decoration of the square)

**Comment by mboeringa** [comment] 2015-05-28 16:53
I think none of us is really arguing against display of any of these items. Just to consider render them later, or differently on lower zoom (Z17).

Personally, I get a headache looking at the Nottingham example at Z17... Z18 is dense, but OK. All of this doesn't mean I suggest to remove shops from the rendering...

The suggestions for improvement by @math1985 and @kocio-pl are worth considering, and I have given a third possible option... I think it would be good to get some example rendering implementing any of these.

**Comment by Rovastar** [comment] 2015-05-29 00:54
Well it appears we are split in our opinions if this is a "problem" or not. It is probably in fact even in favour of "this is not a problem". I don't think any "pro" people would say it is not busy but it is manageable to most and might even say it saw the detail that OSM can show.

Now if we were to change anything I would suggest (if possible and I do not think it is) to scale the icons slightly smaller on this zoom level.

Other options discussed like rendering some shops and not others in some sort of hierarchy, I don't think will work and will lead to more controversy. And rendering just dots I don't think will help any at all will all the detail we can get get from having icons for the POIs.

We all know we don't have the technology to render a density formula on these - even if it was desirable.

And of all the people to complain about about it I thought @Someonelse (the sort of OP) would be the last one as all changes will have major ramifications for rural areas (where there are less POI displayed - you actually want to see the sole shop and icon if there is nothing else around) which he maps/cares about most.

Personally I think it is probably best to close this issue and keep an eye out for anything worse in the future.

**Comment by pnorman** [comment] 2015-05-29 02:33
Rendering fewer distinct icons won't stop rendering of rural shops. They might rendered with a generic icon, but even then I'd suspect most lone rural shops are of a more common shop tag.

**Comment by kocio-pl** [comment] 2015-05-29 13:41
That's why I proposed more dynamic solution - while I agree that rural shops will be most probably of some generic type, local density tuning keeps more of the icons in the big cities visible than general, static solution.

**Comment by kocio-pl** [comment] 2015-07-05 22:09
BTW: if you think this is "crowded", let's look [at typical rendering of big cities at z10](https://github.com/gravitystorm/openstreetmap-carto/pull/1635#issue-93131881). Nobody complains - and should one?...

**Comment by kocio-pl** [comment] 2017-07-12 12:08
With shops icons being pushed one zoom level up I feel this issue is resolved now - see the area in the original report:

http://www.openstreetmap.org/#map=17/52.95354/-1.14638

**Comment by math1985** [comment] 2017-07-12 13:03
Agree.

**Closed by math1985** 2017-07-12 13:03 UTC
Labels: amenity-points

**Comment by SK53** [comment] 2017-07-12 14:08
I'd agree too, leaving supermarkets & department stores provides enough anchor references & names appear for other large stores. I'd been a bit sceptical in the first instance when that was proposed.
