### ISSUE TITLE
highway in tunnel is rendered above waterway and buildings on surface

### ISSUE THREAD

**Issue by martenjj** [gravitystorm/openstreetmap-carto#3025] opened 2018-01-18 13:06 UTC
See for example https://www.openstreetmap.org/#map=17/46.85628/8.22888

![image](https://user-images.githubusercontent.com/10631760/35099270-425822ea-fc4f-11e7-8b0d-aa51b75eb599.png)

The motorway A8 has highway=trunk, layer=-1, tunnel=yes.

The white roads crossing it (which are rendered correctly) are highway=residential.

The streams crossing it are waterway=stream, but are rendered below the motorway.
The same applies to the buildings at the bottom left.

**Comment by matkoniecz** [comment] 2018-01-18 13:37
Duplicate of #1609 #623 #1911 and others (see https://github.com/gravitystorm/openstreetmap-carto/search?q=road+underground&type=Issues&utf8=%E2%9C%93 for start). This intentional - rendering underground roads under features on the ground would make them invisible.

**Closed by matkoniecz** 2018-01-18 13:37 UTC
Labels: roads
