### ISSUE TITLE
Render public transport platforms and stops (new scheme, relation-free implementation for now)

### ISSUE THREAD

**Issue by stefanct** [gravitystorm/openstreetmap-carto#311] opened 2014-01-12 22:21 UTC
Since supporting the new/alternative tagging scheme of public_transport=\* completely is not trivial due to the heavy use of relations, let's start with some easy bits:
https://github.com/gravitystorm/openstreetmap-carto/issues/134?source=cc#issuecomment-23501892

That is: rendering of public_transport=stop_position (like railway=tram_stop i.e. a small blue square, or like highway=bus_stop (if bus=yes but no other transports are tagged) and public_transport=platform (like railway=platform for areas and ways, and maybe shelters for nodes with shelter=yes?).

**Comment by ximex** [comment] 2016-03-26 00:33
If i see it right, `public_transport=platform` isn't rendered yet!? This should be possible without the database reimport.
Or is this here an other problem: https://www.openstreetmap.org/relation/5988332

**Comment by PolyglotOpenstreetmap** [comment] 2016-03-26 01:33
The problem is the unwillingness to also add bus/tram/metro/train and whatnot to the rendering DB. I don't see this change happen in the nearby future, it hasn't changed for the half decade we're already asking for this, so you'll have to double tag them as railway=platform as well, even though there are no rails on those platforms. You might consider dropping the 'new' scheme public_transport tags, but then JOSM will not add roles properly if you add them to v2 route relations. So double tagging it is and never mind the waste of bits and bytes.
Jo

**Comment by kocio-pl** [comment] 2016-03-26 11:55
> If i see it right, public_transport=platform isn't rendered yet!? This should be possible without the database reimport.

I guess not, since the `public_transport=*` key is currently absent in the rendering database.

**Comment by pnorman** [comment] 2016-03-26 17:39
> I guess not, since the public_transport=* key is currently absent in the rendering database.

`public_transport` is currently in the rendering database.

**Comment by ximex** [comment] 2016-03-26 19:12
so it should be possible to add it to render!?

**Comment by Rondom** [comment] 2016-03-26 19:18
As far as I know (should be further up in this issue) keys such as bus, tram etc. are missing

**Comment by ximex** [comment] 2016-03-26 19:50
as i see the rendering of a platform is rendered the same for bus/train/... so it shouldn't be required

**Comment by PolyglotOpenstreetmap** [comment] 2016-03-26 21:52
Those public_transport=platform can also be used on nodes and there a different icon is used for bus stops and tram stops.

**Comment by ximex** [comment] 2016-03-26 23:56
i thought the icon comes from highway=bus_stop and not from public_transport=platform/bus=yes
and we could only render an area (and way) of public_transport=platform

**Comment by matkoniecz** [comment] 2016-03-27 08:33
Yes, public_transport key is available, but bus key is not. So it is impossible to check whatever element is a bus stop. To replace current style, without losing ability do display bus/tram/etc stops in a different ways database change is necessary.

**Comment by deubeuliou** [comment] 2016-05-25 21:41
Hi,

(please note that I'm new to OSM)

I got here because I recently tried to do some janitorial work on a bus line, including using the PTv2 scheme; after doing that, it was pointed out to me that the bus stops I worked on disappeared from the map... It felt like I was breaking something. I do, however, understand how you, maintaining the rendering style, would see the PTv2 scheme decision as not taking rendering concerns into account.

That being said, the way I understand it, there is no need for an additional column in the database. I looked at mapnik and it seems that this issue could be solved by transforming (in the ".style" file) the public_transport=platform + bus=yes combination into highway=bus_stop.

Am I missing something? Maybe this only works with the Lua style files, which you are not using... Could it be worth using them? It can probably solve other future issues.

**Comment by dieterdreist** [comment] 2016-05-25 22:36
sent from a phone

> Il giorno 25 mag 2016, alle ore 23:41, David Wagner <notifications@github.com> ha scritto:
> 
> I got here because I recently tried to do some janitorial work on a bus line, including using the PTv2 scheme; after doing that, it was pointed out to me that the bus stops I worked on disappeared from the map


Actually you don't have to remove the highway=bus_stop tag to add ptv2 tags. You should be really careful changing tags, especially if you are new, because there isn't- unfortunately- complete documentation about the tags, and the available docu has sometimes bugs, e.g. the wiki.

**Comment by pnorman** [comment] 2016-05-25 22:36
> Am I missing something? Maybe this only works with the Lua style files, which you are not using... Could it be worth using them? It can probably solve other future issues.

A change to use lua (or changing existing lua transforms) would be an osm2pgsql style change, just like adding columns.

**Comment by jojo4u** [comment] 2016-05-27 17:10
After deliberating about the problems of public_transport as a physical feature (platform) and logical feature (waiting area) I came up with a proposal: https://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport_Platform_no_Infrastructure

Before RFCing it I'd like to ask one question to osm2pgsql savvy:

a) Consider a linear way tagged with
* highway=platform
* public_transport=platform
* bus=yes
After database reload, with the possibilities of this style: Could the way rendered like a platform (based on highway=platform) and with a bus symbol in the centre (based on the other two tags)?

b) Consider a closed way tagged with
* highway=platform
* area=yes
* public_transport=platform
* bus=yes
Could the area rendered like a platform (based on highway=platform, area=yes) with a bus symbol in the centre (based on the two remaining tags)?

**Comment by jojo4u** [comment] 2016-11-17 18:31
My question above still remains open and database reload comes closer and closer :)

**Comment by nebulon42** [comment] 2016-11-17 21:48
My answer to your questions would be that both could be rendered as a platform based on `public_transport=platform` and `bus=yes`. The icon could be placed along the linear feature, but you would get repetitions depending on the length of the way. It would be very hard if not impossible to ensure that there is only one icon of any length of line. The icon could be easily placed in the interior of the closed way.

**Comment by xamanu** [comment] 2017-12-28 10:30
Big 👍 for this.

Most people I know (including myself) who map public transport in OpenStreetMap use PTv2 (especially if you want to do something with the data and not exclusively look at OSM-carto) and attach `highway=bus_stop`  to the point where they want it to be rendered in OSM-carto. This has been a practice for years now and unfortunately have lead to two parallel existing data schemes. While it is worth mentioning that most of today's disagreements on how to map public transport in OSM is about PTv1 (like if the stop_position or the platform should be tagged with `highway=bus_stop`, etc..). IMHO PTv1 only makes sense, still, because of this open ticket, all other active initiatives in OSM, which I know, dealing with transport want and rely on PTv2.

**Comment by kocio-pl** [comment] 2017-12-28 10:31
What we lack now is somebody who would make the proper code and test it. Could you try to do this?

**Comment by aceman444** [comment] 2018-12-22 14:08
Yes, this should be done.

**Comment by matkoniecz** [comment] 2018-12-22 20:09
I am not sure whatever it should be done. It's it really desirable to encourage not tagging for example standard highway=bus_stop on bus stops?

**Comment by pnorman** [comment] 2018-12-23 01:00
> It's it really desirable to encourage not tagging for example standard highway=bus_stop on bus stops?

It's not desirable to encourage people not to tag it.

**Comment by PolyglotOpenstreetmap** [comment] 2018-12-23 10:05
I've tried to tag stops with just public_transport=platform/bus=yes (on a
node). Gave up on that.

More recently I tried to tag the bus stop nodes with just highway=bus_stop.
That doesn't work either anymore. JOSM complains if I put a platform role
on them in the route relations and it doesn't add the platform role
automatically when adding them to the route relations.

So I guess we're stuck with tagging the stop nodes as

highway=bus_stop
public_transport=platform
bus=yes
+ all the other tags

or
railway=tram_stop
public_transport=platform
tram=yes


I guess it doesn't really matter.

Polyglot

**Comment by gileri** [comment] 2018-12-26 19:44
>I am planning to close this feature request as declined. If someone thinks that more detailed explanation would be useful - let me know and I will explain in more detail.

I, like multiple people in this thread, support and use PTv2 for reasons explained on this issue and other resources. I would still like to see PTv2 rendered, but understand that there is still work to do for that to happen.

Please do not close this issue. Even if it was not yet implemented/tested/demoed (no blame thrown here), I feel that this change is something doable, positive, and realistic.

**Comment by mkyral** [comment] 2018-12-26 21:12
I's not used because it is not visible. And it is not rendered because it is not used :-(

**Comment by PolyglotOpenstreetmap** [comment] 2018-12-26 23:32
Actually, it IS used, both tagging systems are used in combination. One to
get the stops to render, the other because it's supposedly more expressive.
Unfortunately, it did not solve the problem it was supposed to solve.
Instead it even led to people adding details on more than a single OSM
object for the same stop.

In some places you'll find a stop_position node in combination with a
platform way, in others you'll find platform nodes and in yet other places
even all 3 of them, sometimes with the stop's details replicated among
them. A maintenance nightmare, but alas.

And, of course, there are also sill places where the stops are mapped next
to the highways, with just a highway=bus_stop tag on them. I tried to to
back to that way of tagging. It's not that it doesn't work, it does, but
somehow I got used to tagging public_transport=platform/bus=yes
additionally on those stop nodes.

As far as I'm concerned the most important aspect, is to not have a stop's
details on more than a single object per stop. If we could agree to use a
node for this object, it would be possible to declare that

highway=bus_stop

is equivalent to

public_transport=platform
bus=yes

And thus start rendering that combination the same as highway=bus_stop.

Then you wait 5 years and you check whether people start replacing the use
of highway=bus_stop with that combination.

Of course, it may be that this won't work, because there will also be
mappers who say:

Hey, we use public_transport=stop_position as the main object

That's where we want to put railway=tram_stop and tram=yes.

Oh well,

Polyglot

**Comment by matkoniecz** [comment] 2018-12-27 08:20
Ok, I will write in more detail. But in short: I consider

> highway=bus_stop is equivalent to public_transport=platform bus=yes And thus start rendering that combination the same as highway=bus_stop.

to be undesirable as I consider using multiple tags where one sufficies and is already widely used and supported to be undesirable.

**Comment by kocio-pl** [comment] 2018-12-27 08:46
Rough estimation - currently 72.83% has `highway=bus_stop` (80.77% has `highway=*`) and 6.05% has `railway=*`, which means that ~5% (~60k) is not related to bus, tram or railway, so it is a unique type of objects we don't render yet:

https://taginfo.openstreetmap.org/tags/?key=public_transport&value=platform#combinations

**Comment by PolyglotOpenstreetmap** [comment] 2018-12-27 09:06
You do realise that those numbers are skewed, by the simple fact that stops
without highway=bus_stop / railway=tram_stop won't render? If we were to
stop caring whether our 70k Belgian stops render, those numbers would
already change by about 10%.

The circular logic applied favours the status quo and renders the whole
public_transport scheme moot, at least for the stops.

My reaction to that of a few months ago, was to try and drop the "new"
schema altogether, but we're beyond that point as well. So double tagging
seems to be the only viable option for the foreseeable future.

Polyglot

**Comment by kocio-pl** [comment] 2018-12-27 09:10
Yes, I do realize it. The split in tagging is done and refusing to accept it is just closing eyes. I try to show that it is needed anyway, not rendering does not help anything but hurts some valid cases.

**Comment by dieterdreist** [comment] 2018-12-27 09:15
sent from a phone

> On 27. Dec 2018, at 10:06, Jo <notifications@github.com> wrote:
> 
> The circular logic applied favours the status quo


while this is true, it also seems generally a sane choice, imagine what would happen if it were easier to change things than stick with the established tags

**Comment by PolyglotOpenstreetmap** [comment] 2018-12-27 09:33
Not sure about chaos, but I am convinced you'd see the use of highway=bus_stop / railway=tram_stop wane drastically, if the public_transport combinations were rendered independently.

**Comment by kocio-pl** [comment] 2018-12-27 09:39
We have double tagging for years, so anybody interested had already a lot of time to prepare. And we're not talking about removing rendering old schemes, so there's no hurry. What else would you do to make the change smooth and avoid chaos?

**Comment by daganzdaanda** [comment] 2019-02-01 19:00
It seems we are rendering 
https://www.openstreetmap.org/way/392315371
and not rendering
https://www.openstreetmap.org/way/390222659

It looks as if highway=platform is what makes the platform appear. The [English wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dplatform) seems to tell people it's on its way out, the [German wiki](https://wiki.openstreetmap.org/wiki/DE:Tag:highway=platform?uselang=de) already calls it "replaced" by public_transport=platform.

I think we should be continuing to support highway=platform, but should start treating public_transport=platform just the same.

**Comment by jeisenbe** [comment] 2019-09-07 12:48
I'm in favor of closing this issue. 

1) public_transport=stop_position is not useful for general map users. Generally the railway platform or bus stop location is where passengers want to go, and bus drivers do not need us to record their stop positions for them.

2) public_transport=platform duplicates the much more common highway=bus_stop and more common railway=platform, and it's confusing because it isn't the same as highway=platform which is an actual physical object. 

3) We can't render these properly unless mappers add bus=yes / train=yes etc. to each object. This wasn't part of the original proposal for public_transport, and doing this is twice as much work for mappers compared to just tagging highway=bus_stop. 

This was discussed on Tagging last month, and there's also a proposal open which would suggest stopping using public_transport=stop_position and =platform, and continuing to just use highway=bus_stop, railway=platform, amenity=ferry_terminal, etc. - as is the more common practice: https://wiki.openstreetmap.org/wiki/Proposed_features/Refined_Public_Transport

 I've considered updating the proposal and bringing it to a vote, but the usage statistics show that this is not really necessary. The suggested system in the proposal is already what's actually used by a large majority of mappers, and what we currently use for rendering.

**Comment by kocio-pl** [comment] 2019-09-07 15:02
I don't understand the the claim 3 - what do you mean saying that we can't?

I see public transport platform rendering as very clear in meaning. The important part is not bus/tram, but universal meaning. See the problem we have with public transport terminals/stations rendering, which we started to discuss in #3257 lately. We don't have to review every possible transport existing on earth to know what a platform means and that it's important for people. For example [`seaway=*` proposition](https://wiki.openstreetmap.org/wiki/Proposed_features/Seaway) or [`amenity=ferry_terminal`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dferry_terminal) omits this problem completely. The fact, that the most popular transport types has their own platform defined, does not help all the other types, and I don't think this is good.

**Comment by matkoniecz** [comment] 2019-09-07 19:23
> I don't understand the the claim 3 - what do you mean saying that we can't?

`public_transport=stop_position` may be for either bus or tram or something else

**Comment by kocio-pl** [comment] 2019-09-07 22:55
Still I don't understand what "can't" means here. IMHO rendering generic platform (shape and name) is easy and we can render more elements if more precise data is here. Also it's quite simple to make presets for popular platforms to avoid unneeded typing, if you think this is a problem, or just make bus or tram default value. 

In return we get semantic and flexible solution without discovering new tag for each type of public transport and making style codebase large and consisting of special cases.

**Comment by jeisenbe** [comment] 2019-09-08 01:29
> I see public transport platform rendering as very clear in meaning

It only represents "the place where passengers are waiting for the vehicles," so it doesn't represent a physical `highway=platform` (a flat, elevated area that facilitates boarding a bus), but it's the same as `highway=bus_stop` (a place where passengers wait for a bus). And since it can also be used for aerialways, ferries and trains, the meaning less clear than `highway=bus_stop`. While the proposal said that only real platforms should be mapped as an area, there are over 5000 `highway=bus_stop` + `public_transport=platform` without `highway=platform` which are mapped as closed ways: https://overpass-turbo.eu/s/M8J - so rendering these the same as `highway=platform` would be a mistake.

> > We can't render these properly unless mappers add bus=yes / train=yes etc. to each object 
> Still I don't understand what "can't" means here

I mean we can't use the current rendering with a specific icon for `highway=bus_stop` unless mappers are required to add `bus=yes, `train=yes`, `ferry=yes`, `aerialway=yes` etc - tags which were not required as part of the ["public_transport" proposal](https://wiki.openstreetmap.org/wiki/Special:PermanentLink/625726) (they were suggested with stop_position only), and not used universally.

For example, 76.0% of `public_transport=platform` are tagged with `highway=bus_stop` and 6.3% with `highway=platform` but only 60.7% are tagged with `bus=yes` or `trolleybus=yes` (https://taginfo.openstreetmap.org/tags/public_transport=platform#combinations)

Rendering all `public_transport=platform` like `railway=platform` or `highway=platform` would be incorrect, because as mentioned, most are on `highway=bus_stop` nodes, which normally lack a physical platform. And a small number of `public_transport=platform` are for where passengers wait to board an `aerialway` or `ferry` - quite different features, which also have different renderings currently. 

Encouraging mappers to add `bus=yes` + `public_transport=platform` to every `highway=bus_stop` and `highway=platform` is extra work for mappers which was not envisioned by the public_transport proposal. There are 410,000 `public_transport=platform` which lack any tag like bus=/train=/trolleybus=/subway=/etc.: https://overpass-turbo.eu/s/M8F - but most of these have `highway=bus_stop` or `railway=platform` so they are handled fine. 

> we get semantic and flexible solution without discovering new tag for each type of public transport

Let's discuss the tagging system at https://wiki.openstreetmap.org/wiki/Proposed_features/Refined_Public_Transport or the tagging mailing list.

**Comment by matkoniecz** [comment] 2019-10-22 11:04
According to the PTv2 proposal itself data consumers are supposed to distinguish between bus stop, tram stop, train station or a ferry terminal NOT by using vehicle tags.

PTv2 documents that it should be done using standard tags like `highway=bus_stop`, `railway=tram_stop` etc. PTv2 is not a replacement for simple tagging (sometimes called PTv1), it was at least described as an optional extension that is not deprecating anything.

Later some mappers (or maybe a separate group?) started using vehicle tags also for stop positions, with some voices calling for deprecation of tags like `highway=bus_stop` with `public_transport`=`platform` + `bus=yes` style tagging. But it is not what was disccused and voted on in PTv2 proposal.

It is method that was like original tagging scheme never voted on (AFAIK), is more complex and less popular

> This proposal does not replace, deprecate or obsolete the already existing and well known tags. The usage of the proposed tags is recommended but not mandatory.

in the proposal https://wiki.openstreetmap.org/w/index.php?oldid=625726#What_this_Proposal_does_not_cover

Therefore, by rendering `highway=bus_stop` and similar simple tags we are already following PTv2!

ongoing dominance of standard and simple tagging (see https://github.com/gravitystorm/openstreetmap-carto/issues/435#issuecomment-516016068 ) and lack of documentation why significantly more complex and confusing tagging scheme would be wanted (see https://github.com/gravitystorm/openstreetmap-carto/issues/435#issuecomment-491350865 ).

I am especially confused why this proposal was created and supported in the first place given that stated intention was to duplicate existing tagging without intention of replacing it.

Overall simple tagging (`highway=bus_stop` type) is preferable over more complex that makes everything more complicated (simplest bus stop tagged three times in two different places). Enormous effort went into discussing and using it, without any clear analysis/documentation why additional complexity is worth negative effects.

I am therefore closing this issue as declined. See also comment above.

And please, read at least entire discussion in this issue and in #435 before commenting to avoid repeating things (except pointing out any parts in my comment that were untrue).

**Closed by matkoniecz** 2019-10-22 11:04 UTC
Labels: enhancement, new features, station
