### ISSUE TITLE
Rendering short_name

### ISSUE THREAD

**Issue by Tysseract** [gravitystorm/openstreetmap-carto#4350] opened 2021-03-23 04:28 UTC
### Expected behavior
When there isn't space for the full name of adjacent buildings, the `short_name`s should be rendered.
### Actual behavior
The full `name` is always rendered even when it precludes other surrounding buildings from having their names rendered at all.
### Proposal
Ideally, the renderer could automatically switch from `name` to `short_name` when space becomes an issue.
A much simpler option would be to add a tag such as `render_short_name = yes` or `render_name = short_name` to let the renderer know to use the `short_name`. This not only fixes the render space issues but provides the mapper the ability to correctly tag objects but still display the best version of the name for the situation. I believe my point is best illustrated with an example:
### Example
College campuses generally have short letter codes for buildings which are often described on osm as the `short_name` for that building. In practice, these names are used almost exclusively (in conversation, on class schedules, on official campus maps, etc.) over the use of the full name for the building (which tends to be quite long). In this example, the real `name` for the building is _East Campus Classroom 16_ but it is almost always called by its `short_name`, _ECC16_, which is not only more likely to fit in the map rendering but more useful to the end user. The same logic applies to _Earth and Biological Science_/_EBS_, _Physical Science_/_PS_ (which does not even render on the map), and I'd say most buildings on most college campuses.
https://www.openstreetmap.org/way/920684009#map=19/34.40588/-119.69648&layers=N
![OSM Screenshot](https://user-images.githubusercontent.com/21372677/112077233-490e4200-8b39-11eb-9112-688a3bf47779.png)
https://www.sbcc.edu/map/files/SBCC_CampusMap_4c_1_2018_Master.pdf
### How?
I don't fully understand the syntax for carto but it looks to me like (while it would be a big undertaking) one could replace `text-name: "[name]";` in amenity-points.mss with something like
```
[render_name = null] {text-name: "[name]"}
[render_name = 'short_name'] {text-name: "[short_name]"}
[render_name = 'alt_name'] {text-name: "[alt_name]"}
```

**Comment by HolgerJeromin** [comment] 2021-03-23 10:45
Thanks for your suggestion.
This is a duplicate for #430

**Comment by pnorman** [comment] 2021-03-23 12:49
Duplicate of #430

**Closed by pnorman** 2021-03-23 12:49 UTC
