### ISSUE TITLE
Icons for tourism=wilderness_hut and natural=spring too large in low zoom levels

### ISSUE THREAD

**Issue by johsin18** [gravitystorm/openstreetmap-carto#4558] opened 2022-05-31 19:40 UTC
### Expected behavior

The icons for tourism=wilderness_hut and natural=spring should be relatively small (i.e. not exceed the dimensions of a normal house), and not appear in low zoom levels.

### Actual behavior

The icons for tourism=wilderness_hut and natural=spring appear in low zoom levels, and are relatively large (like 50m to scale).

### Links and screenshots illustrating the problem

![grafik](https://user-images.githubusercontent.com/3518185/171270557-8e154846-5447-4a56-8101-2d8847c2b552.png)
https://www.openstreetmap.org/#map=13/47.5458/7.5219&layers=N

![grafik](https://user-images.githubusercontent.com/3518185/171270582-0f0b0c1c-9d0e-434e-bba4-6ff1c3150aa6.png)
https://www.openstreetmap.org/#map=14/47.6129/7.7068&layers=N

The large spring icon was already complained about in #3274.  It was supposed to be solved by issue #3461, but is open for years now.
How about just fixing the zoom level range / size of the icons?

**Comment by imagico** [comment] 2022-05-31 21:20
In general point symbols and line signatures we use in this style are not supposed to represent ground unit dimensions of the objects they represent.  For example the drawing width of primary roads at z13 is 5 pixel - which is 95m at the equator and half of that at 60 degrees latitude - so way larger than the typical primary road.

Changing the starting zoom level of tourism=wilderness_hut could be reconsidered - or the option to render tourism=wilderness_hut/tourism=alpine_hut at the first zoom level (z13) with a smaller, unified symbol.  But keep in mind that these are features which typically exist in remote regions where showing them early is of significant value for the map user.  See for example here:

https://www.openstreetmap.org/#map=13/54.4676/-2.8007
https://www.openstreetmap.org/#map=13/61.5667/7.8224
https://www.openstreetmap.org/#map=13/0.3205/29.9243
https://www.openstreetmap.org/#map=13/46.5073/8.0826

For springs this is a duplicate of #3461 - so far no one has tried to develop any of the ideas brought up there to a concrete PR that can find consensus.

**Comment by matkoniecz** [comment] 2022-06-03 22:48
> The icons for tourism=wilderness_hut and natural=spring should be relatively small (i.e. not exceed the dimensions of a normal house)

I strictly disagree with this, there is no good idea to do this. What would be reason for such limitation? Why would you apply it only here and not in numerous other cases where object icon is larger than what is being represented?

Such limitation you propose is extremely unusual for maps.

Correctly mapped `tourism=wilderness_hut` and alpine huts are in general well displayed, even if some rare cases are showing badly then pushing to higher level would overall decrease map quality.

**Comment by pnorman** [comment] 2022-06-04 01:10
I agree with the above comments.

**Closed by pnorman** 2022-06-04 01:10 UTC

**Comment by johsin18** [comment] 2022-06-06 15:44
Ok, my argument comparing it too the physical size is not valid, forget about it.

But don't you agree that the icon is excessively large anyway?  Look at
https://www.openstreetmap.org/#map=14/47.5521/7.5543
There is a major city, villages, a major river, and all, everything rendered in small detail.  There are almost no icons on this map at this zoom level (just text signs, and maybe the tram stops), and then the wilderness hut icon is 10 times larger in area than any other visible icon.  Isn't that inconsistent?

And even mountain regions, it's very large and dominant at zoom level 13
https://www.openstreetmap.org/#map=13/46.7262/7.9108
and then disappears completely at zoom level 12.

**Comment by imagico** [comment] 2022-06-06 16:05
We have a standard pictorial symbol size of 14 pixels which is often challengingly small to design a recognizable symbol.  At z13/z14 we don't render many pictorial point symbols, we render peaks and train stations with an abstract shape (and at z14 also railway crossings and power=tower), we render springs with a highly non-ideal abstract shape symbol as well.  And we render airports with a pictorial symbol of the same 14 pixel size (which starts at z10).

It is in the very nature of static pictorial POI symbols that they appear at a certain zoom level abruptly as you zoom in.  Reducing that is possible either with a contextualized symbol (like it has been suggested for springs) or with a smaller symbol with a more simple shape for the first zoom level (which we could - as indicated - consider for tourism=wilderness_hut/tourism=alpine_hut).

If you want to work on a smaller, unified symbol for tourism=wilderness_hut/tourism=alpine_hut for z13 i would welcome that - but we would need to discuss that based on a concrete design proposal.  And there are reasons that speak against that as well (like that map users need to learn to recognize yet another symbol).
