### ISSUE TITLE
Unsuitable way to show names of multipolygons containing several named elements

### ISSUE THREAD

**Issue by rasmusv1** [gravitystorm/openstreetmap-carto#1570] opened 2015-05-21 18:32 UTC
Long description:
I have created the multipolygon 1933205 (*), which covers the municapality of Samsø (Samsø Kommune) in Denmark. It is a island with approximately 16 islets. The multipolygon is given a name tag which shows up on all the elements centred on these. This blocks the view of the standard name tag for the islets and lets users think these are not applied. The name of the multipolygon should preferably apply only to the complete multipolygon and not all of the 17 parts of the multipolygon (#) as it is now. The problem with the existing method of rendering is that you cannot see the names of the islets, but instead they are wrongly called "Samsø Kommune".

Short description:
Subject: Multipolygons naming applied to more than one element is unsuitable.
Actual case: Multipolygons name block elements name.
Expected case: Multipolygons draw only one name of the complete multipolygon, thus not blocking the seperat names of the elements.

(*): http://www.openstreetmap.org/browse/relation/1933205
(#): http://www.openstreetmap.org/?lat=55.8944&lon=10.6519&zoom=14&layers=M

If further clarification is needed, i'll do my best to help.

Rasmus

**Comment by dieterdreist** [comment] 2015-05-21 19:09
I second this, another example: we have a big park which is divided by a big street (and connected by a bridge over that street) and rendering the name twice rather than in the middle looks odd: http://www.openstreetmap.org/relation/2985897
(apparently a local mapper has overwritten the original osm object with an imported one consisting of 4 instead of 2 polygons, but the issue remains the same)

**Comment by 23cpo** [comment] 2015-05-22 10:47
See also https://github.com/gravitystorm/openstreetmap-carto/issues/1496

Btw. it definitely makes sense to display the name on every object. See for example this complicated boundary situation: http://www.openstreetmap.org/relation/3766486

**Comment by matkoniecz** [comment] 2015-08-26 17:50
Duplicate of #59

**Closed by matkoniecz** 2015-08-26 17:50 UTC
Labels: general
