### ISSUE TITLE
Render place=county/neighbourhood/block

### ISSUE THREAD

**Issue by joakimfors** [gravitystorm/openstreetmap-carto#107] opened 2013-08-08 12:37 UTC
It would be nice if more place types were rendered at appropriate zooms. For example county, neighbourhood, block etc. Both on nodes and closed ways/relations.

**Comment by math1985** [comment] 2015-01-20 14:49
* place=neighbourhood is already rendered
* place=county is an administrative region, and the name is already rendered on the admin boundary. I don't think rendering nodes makes much sense, as they are often duplicate with the country capital. I'd propose not to render this.
* We could render place=block. What is it currently used for?

**Comment by math1985** [comment] 2015-01-20 22:23
There is also a place=city_block.

**Comment by lest69** [comment] 2015-01-22 19:24
> We could render place=block. What is it currently used for?

It's unclear, since there's no documentation, but it seems to me to be a duplicate of city_block. Both it and place=city_block appear to be used almost exclusively in Sweden. Oddly, they seem to be used for the same purpose, but are used differently in different cities (ie. city_block in Stockholm, but block in Malmö, Lund, and Landskrona).

Should we be encouraging such ambiguous tagging by rendering both, or only render the documented tag?

**Comment by math1985** [comment] 2015-01-22 19:30
> Should we be encouraging such ambiguous tagging by rendering both, or only render the documented tag?

In cases like bookmaker/betting and fishmonger/seafood we render both the documented and undocumented (but still used) tag. I don't know if that's a good approach.

Maybe someone could reach out to the Swedish community so they can unify their tags?

**Comment by pnorman** [comment] 2015-01-22 19:31
> Should we be encouraging such ambiguous tagging by rendering both, or only render the documented tag?

If they're both only used in Sweden, I'd rather not render either to encourage usage of a widely used tag.

**Comment by math1985** [comment] 2015-02-04 14:13
Rejected per https://github.com/gravitystorm/openstreetmap-carto/pull/1247#issuecomment-72851791.

**Closed by math1985** 2015-02-04 14:13 UTC
Labels: enhancement, features, placenames
