### ISSUE TITLE
national park boundary does not show up for closed ways

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#468] opened 2014-04-09 13:46 UTC
The way 267307539 is the boundary of a national park in Ivory Coast. Basicly, this parc is formed by islands. The boundary passes water. The boundary currently doesn’t render at all. A bug?

**Comment by matkoniecz** [comment] 2015-10-08 10:38
It appears to be duplicate of reported later #1141. I am closing this rather than later as in #1141 it is clear from start what real problem is.

**Closed by matkoniecz** 2015-10-08 10:38 UTC
Labels: admin
