### ISSUE TITLE
man_made=bridge layer issue

### ISSUE THREAD

**Issue by simonpoole** [gravitystorm/openstreetmap-carto#1799] opened 2015-08-30 19:15 UTC
First thanks a lot for supporting the tag in the first place.

There seems to be a minor problem with respect to supporting the layer tag correctly wit http://www.openstreetmap.org/#map=18/47.38605/8.53404

**Comment by matkoniecz** [comment] 2015-08-30 20:14
For now it is like buildings - displayed below all roads.

Partial reason is to show roads, junctions etc below bridges (like at http://www.openstreetmap.org/?mlat=50.04999&mlon=19.93513#map=19/50.04999/19.93513) - but I am not sure is it a good reason to keep it this way, it is probably really rare to see situations where there is something interesting below and it is readable.

Second reason that it was relatively easy to code displaying it like building. To handle layers it would be much more complicated - it would be part of SQL query starting at https://github.com/gravitystorm/openstreetmap-carto/blob/dc6b9fe6a2bb881f5d9b6da4f001a7c4942f914b/project.yaml#L772 and ending 119 lines later.

**Comment by matkoniecz** [comment] 2015-08-30 20:22
@simonpoole In provided example there is a better situation - this steps may be hidden on implementig this suggestion (and somebody would probably change layers to tag it for renderer - and encouraging things like this would be a poor idea)
![91789](https://cloud.githubusercontent.com/assets/899988/9569230/6667adac-4f65-11e5-94a8-bb2ed9664c88.png)

**Comment by matkoniecz** [comment] 2015-09-02 19:54
> show roads, junctions etc below bridges

I think that it is a good enough reason to layer it like buildings. I plan on closing this ticket as IMHO current solution is not perfect - but there is no clear way to improve this.

**Comment by dieterdreist** [comment] 2015-09-03 12:20
sent from a phone

> Am 30.08.2015 um 22:22 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> In provided example there is a better situation - this steps may be hidden on implementig this suggestion (and somebody would probably change layers to tag it for renderer - and encouraging things like this would be a poor idea)


in this example the bridge appears to be below the crossing road, thereby confusing the map reader. I agree with Simon that there is still a flaw in bridge rendering. Maybe there could be an exception for using transparency in conjunction with bridges?

**Comment by Gazer75** [comment] 2015-09-03 17:12
Tbh the entire layering of buildings vs roads can be confusing, but I guess as this render is focused on roads I guess it can't be helped.
Would suggest not even displaying the bridge building at all. Just makes it all more confusing when roads are layered on top.

**Comment by gravitystorm** [comment] 2015-09-04 08:58
> Maybe there could be an exception for using transparency

I've said this before and I'll say it again. No transparency. :-)

https://github.com/gravitystorm/openstreetmap-carto/issues/552#issuecomment-76158611

You don't actually want to blend the road colour and the bridge colour together to get a darker murky brown. What you are actually wanting to do is find the roads that (physically) lie below the bridge, and colour those bits with a different (perhaps lighter? tunnel-like?) colour, while still drawing the bridge polygon first and the roads after. So think `st_intersects()` and `st_split()` and things like that, not translucency.

I'm going to close this as per @matkoniecz since it's not a huge problem and the fix would be quite challenging. Of course, if a PR appears with an alternative approach, that would be of interest.

**Closed by gravitystorm** 2015-09-04 08:58 UTC

**Comment by kocio-pl** [comment] 2015-09-04 09:45
@gravitystorm I'm confused then what is translucency/transparency, what is not, and why it is considered a bad thing. Using examples:

1. "French style" tree canopy uses it or not (opacity=0.3 IIRC)?

2. MapQuest Open uses it or not? [Eiffel Tower](http://www.openstreetmap.org/#map=18/48.85790/2.29411&layers=Q), [Berlin Hauptbahnhof](http://www.openstreetmap.org/#map=18/52.52488/13.37050&layers=Q) or even [Palace of Culture and Science in Warsaw](http://www.openstreetmap.org/#map=18/52.23156/21.00622&layers=Q) all look nice and even better than on osm-carto - or do you think they are flawed maybe?

Closed bridge-related issue may be not the best place to ask such general questions, but we don't have special place for it, so sorry for "hijacking" it...

**Comment by gravitystorm** [comment] 2015-09-04 11:28
opacity/transparency/translucency are all similar things in our conversations (https://en.wikipedia.org/wiki/Transparency_and_translucency has the details.

Yes, the tree canopies use opacity. MapQuest Open uses transparency almost everywhere and that leads to terrible colour mixing - it's a really bad idea, and we knew that when I worked on that style a few years ago. (For your examples, ask why are some buildings darker than others?) But for the best explanation of why it is bad, see my link above regarding footpaths and roofs.

**Comment by dieterdreist** [comment] 2015-11-28 00:40
Here's another example that demonstrates that we should take the layer value for bridge objects into account for the rendering order: 

![layer_ponte_marconi](https://cloud.githubusercontent.com/assets/581288/11449341/00cb1c84-9571-11e5-9213-da91f3ebd77e.png)

http://www.openstreetmap.org/way/44097288#map=19/41.86046/12.47039

**Comment by pnorman** [comment] 2015-11-28 08:42
> Here's another example that demonstrates that we should take the layer value for bridge objects into account for the rendering order:

Could you do a PR with a fix, so we can have a look at how much complexity it adds?

**Comment by sommerluk** [comment] 2018-04-27 19:09
Duplicate of #2509 and #3203
