### ISSUE TITLE
leisure=park overlaps adjacent roads

### ISSUE THREAD

**Issue by ZeLonewolf** [gravitystorm/openstreetmap-carto#4202] opened 2020-09-09 04:00 UTC
When a leisure=park area is immediately adjacent to a road, and the park polygon uses the road as part of its boundary, the park area renders partially on top of the road.

### Expected behavior

Park areas should render in such a way that the road is not obscured.  Other types of area tagging, such as landuse=farmland (shown in an adjacent plot of land) properly render next to the road without obscuring it.

### Actual behavior

Although the road name is visible, the road rendering itself is partially obscured.

### Links and screenshots illustrating the problem

Example: https://www.openstreetmap.org/#map=19/41.51323/-71.76776

In this example, North Road is partially obscured by the adjacent park boundary.

![render_park_road](https://user-images.githubusercontent.com/3254090/92552582-01743880-f22f-11ea-8e9c-ffb7ec3a71d4.png)

**Comment by jeisenbe** [comment] 2020-09-09 05:36
This behavior was intentional.

It is not caused by the `leisure=park` tag but by the `leisure=nature_reserve` or `boundary=protected_area` tag, which is rendered only as an outline. Since it is only an outline, it is rendered above roads so that it is still visible.

We have previously discussed changing this rendering, but in this case the outline would be completely obscured by the road, were it rendered below the road fill. This would de-emphasize protected areas, nature reserves and national parks, which would make it easier to see physical features like waterways and roads and fences, but more difficult to see the protected area boundaries.

(OT: Most likely the `leisure=park` tag is incorrect in this case, and also in the case of the adjacent State Forest areas)

**Comment by jeisenbe** [comment] 2020-09-09 05:38
This issue is mostly a duplicate of #4116 - which was also discussed in PR #4127 (still open)

**Closed** 2020-09-09 05:43 UTC
Labels: duplicate

**Comment by HolgerJeromin** [comment] 2020-09-09 06:38
Does the park starts in the middle of the street? I don't think so. 
But this tagging is disputed (at least in germany)
