### ISSUE TITLE
craft=* on nodes renders addr:housename not name

### ISSUE THREAD

**Issue by eehpcm** [gravitystorm/openstreetmap-carto#3861] opened 2019-09-02 23:41 UTC
### Expected behavior

A node tagged craft=* + name=* should display the name (where space permits, obviously).

### Actual behavior

A node tagged with craft=* + name=* + addr:housename=* renders the housename not the name.  A node tagged with craft=* + name=* (no housename) does not render anything.

### Links and screenshots illustrating the problem

[Winery on node, no housename](https://www.openstreetmap.org/node/4158004085)

[Carpenter on node, with housename](https://www.openstreetmap.org/node/6767621044)

I had the carpenter above tagged on a building and it rendered.  But he just relocated to a new building which he shares with a handicrafts shop (go into the shop and you can watch him work).  Drove me mad trying to figure out why the housename was showing up and not the name.  Looking at overpass-turbo it appear to be a general problem affecting any craft=* applied to a node, not something applicable only to one type of craft or anything specific to my example.

**Comment by eehpcm** [comment] 2019-09-02 23:57
Just did a little more digging and found [this craft=turner on a node](https://www.openstreetmap.org/node/4489000160#map=19/50.65856/6.78084).  No addr:housename but it does have an addr:housenumber.  The house number renders rather than the name.

**Comment by jeisenbe** [comment] 2019-09-03 00:14
This happens because this style does not yet rendering anything under the key `craft=`. If you are seeing the `name` rendered when tagging on a building, this is because we interpret `bulding=*` + `name=` as the name of the building. Ideally the `craft=` business should be mapped separately, if it's name is not the same as the building name, so mapping as nodes is a good idea.

I'm closing this issue because it is a duplicate of issue #1697 where rendering of craft and some icon options is discussed, please add further comments there. Also see the closed PR #3126 which planned to add support for `craft=`, for examples of how it might be done.

**Closed by jeisenbe** 2019-09-03 00:14 UTC
Labels: duplicate
