### ISSUE TITLE
my placemark is not visible

### ISSUE THREAD

**Issue by mominulhasan** [gravitystorm/openstreetmap-carto#4284] opened 2021-01-14 21:56 UTC
### Expected behavior
Coworking icon should be visible 
### Actual behavior
Only house humber is visible
### Links and screenshots illustrating the problem
https://www.openstreetmap.org/node/8319976106#map=17/54.61623/9.82624

**Comment by pnorman** [comment] 2021-01-14 23:01
Duplicate of #4283

**Closed by pnorman** 2021-01-14 23:01 UTC
