### ISSUE TITLE
Add rendering for vending=parking_tickets

### ISSUE THREAD

**Issue by tbertels** [gravitystorm/openstreetmap-carto#2541] opened 2017-01-08 06:34 UTC
[vending=parking_tickets](https://wiki.openstreetmap.org/wiki/Tag:vending%3Dparking_tickets)
About [17 000 uses](https://taginfo.openstreetmap.org/tags/vending=parking_tickets).

**Comment by kocio-pl** [comment] 2017-01-08 07:15
It's partial duplicate of #1561, closing it.

**Comment by tbertels** [comment] 2017-01-08 07:32
This isn't a duplicate, #1561 is about a generic icon for vending_machine, and was closed because of that.

**Comment by imagico** [comment] 2017-01-08 09:52
I would support reopening this and #2544 + #2545 for the possibility to render these specific types of vending machines.  Cigarettes and excrement bags seem too specialized for a general purpose map.

This does not mean i would be definitely in favor of rendering them but i would consider specific suggestions for showing them at the highest zoom level (19).

Would depend on the database reload of course for practical implementation.

**Comment by kocio-pl** [comment] 2017-01-08 22:08
As for me, feel free to reopen, since there's no easy solution. I closed all of them because I felt we should first discuss them it in https://github.com/gravitystorm/openstreetmap-carto/issues/1561 and possibly reopen it, but individual issues also make sense.

I have already designed the icon for shop=tickets, which could be also used here (possibly with amenity brown):
1) ![ticket-14-3](https://cloud.githubusercontent.com/assets/5439713/21753944/0621a028-d5f7-11e6-9028-ac28f66962db.png)

**Comment by dieterdreist** [comment] 2017-01-09 10:29
sent from a phone

> On 8 Jan 2017, at 10:52, Christoph Hormann <notifications@github.com> wrote:
> 
> Cigarettes and excrement bags seem too specialized for a general purpose map.


I partly agree for excrement bags (although I think it would be a distinctive osm map feature and somehow funny to show them), but there are a lot of smokers in the world, so cigarette vending is a general interest feature, while I could imagine people wanting to exclude it for other reasons (moral, educative/not suitable for kids).

**Comment by tbertels** [comment] 2017-01-09 10:46
For parking_tickets and public_transport_tickets, I was wondering if it wouldn't be possible to mix the icon of ticket with the icons of [parking](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/parking.svg) and [bus_stop](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/bus_stop.12.svg), a bit like for [bicycle_parking](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/bicycle_parking.svg) but with the ticket icon in place of the P.

For excrement bags, in case it would be rendered, a mix of [dog_park](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/dog_park.png) and [waste_basket](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/waste_basket.10.svg) could be used.

**Comment by imagico** [comment] 2017-01-09 10:56
I am re-opening this.  But note a suitable solution for this with a chance for being accepted that is not too big and strong even for z19 and that is specific enough to be intuitively understandable is going to be hard.

**Comment by lakedistrictOSM** [comment] 2018-03-12 11:44
Maybe change the top line into a rotated **[** to match amenity=atm and amenity=post_box?

**Comment by kocio-pl** [comment] 2018-03-12 11:47
We might check this too, but current ideas are so distinct, that I see no reason to break the style similar to both ATM and post box.

**Comment by Tomasz-W** [comment] 2018-03-12 12:56
Comparsion:

1)  rotated [ (copied from `amenity=atm` icon)
![vending parking_tickets atm](https://user-images.githubusercontent.com/25656654/37284411-ba06b9fc-25fb-11e8-80a0-a2af3c380fc0.png)
![vending public_transport_tickets atm](https://user-images.githubusercontent.com/25656654/37284409-b9bf2b14-25fb-11e8-8984-0a67010dea11.png)

2) rotated [
![vending parking_tickets2](https://user-images.githubusercontent.com/25656654/37284705-e804d464-25fc-11e8-8b63-f44622323cc0.png)
![vending public_transport_tickets2](https://user-images.githubusercontent.com/25656654/37284706-e824c7f6-25fc-11e8-9155-ad780ccd55af.png)


3) original
![vending parking_tickets](https://user-images.githubusercontent.com/25656654/37284713-efe70a76-25fc-11e8-9c5e-7a1fab6e426a.png)
![vending public_transport_tickets](https://user-images.githubusercontent.com/25656654/37284715-f02fb56e-25fc-11e8-9c06-6fc118a5d18a.png)


Give me feedback, which version should I upload on Gist.

**Comment by kocio-pl** [comment] 2018-03-12 13:31
1 or maybe 2, because this make the style more uniform (it's easier to predict the meaning, because it was used for some other elements). Rendering test is needed to know if 1 has not some visual issues on the real map.

We could also use thinner [ as a special indicator, that it's a vending machine (and use it for many other types), as something distinct from ATMs (even if they are similar) and post boxes.

**Comment by Tomasz-W** [comment] 2018-03-12 16:32
Each icon in versions 1 and 2:

* vending=parking_tickets
https://gist.github.com/Tomasz-W/3a93d9a032725039b3ac24139f5d318c

* vending=public_transport_tickets 
https://gist.github.com/Tomasz-W/e2ada41172ec67de5131e68d44fcb900

**Comment by lakedistrictOSM** [comment] 2018-03-12 19:24
I prefer 2.

**Comment by geozeisig** [comment] 2018-03-22 08:10
Can someone give an example. In the city center, the parking machines are almost every 100 meters and then will be difficult to find a cash machine (atm).

**Comment by Tomasz-W** [comment] 2018-03-22 12:03
If someone is interested, I've proposed also icon for packstations -> https://github.com/gravitystorm/openstreetmap-carto/issues/1561#issuecomment-373943968

**Closed** 2019-01-04 00:11 UTC
Labels: amenity-points, duplicate
