### ISSUE TITLE
Render roads with two-carriage ways in z12 to z15 with a thin line in the middle

### ISSUE THREAD

**Issue by IOOI-SqAR** [gravitystorm/openstreetmap-carto#3934] opened 2019-10-17 01:18 UTC
Roads with two-carriage ways, like motorways, e.g. roads where you can't take a U-turn, should be rendered slighty wider and with a thin line in the middle to better distinguish them from roads with a single carriage way.

While it is easy possible to distinguish the different road types by their color, it is not so easy (at least at z12 to z15) to distinguish roads with two-carriage ways from roads with a single carriage way. There are also secondary and tertiary roads with two-carriage ways and motorways with just one carriage way so there is no simple relation motorways / trunk -> two-carriage ways, other -> single carriage way. The information, whether a road has a single or two carriage ways is somewhat important to drivers on those roads (they can't just take a U-turn and those roads usually have a higher traffic capacity) and also for pedestrians and cyclists (they might not be able to cross the road because of guardrails in the middle).

At z16 to z19 this information is clearly visible due to the small arrows on each lane from z16 on and because of a clear separation of the carriage ways from z18 on, but z16 is already pretty narrow area in terms of what to see on the map. Adding a thin line in the middle of such roads would make this information also available on more of an overview zoom levels. On even lower zoom levels (z6 to z11) this could be done by rendering such roads a bit wider than the normal roads.

Example rendering showing how this could look like:

<img width="620" alt="roads with two-carriage ways with a thin line in the middle example" src="https://user-images.githubusercontent.com/9305009/66970057-5abe0100-f08c-11e9-886e-99d6581f4066.png">

**Comment by jeisenbe** [comment] 2019-10-17 05:56
The style on [openstreetmap.de](https://www.openstreetmap.de/) renders `highway=motorway` and `highway=trunk` in a style similar to this suggestion. This works in Germany, where `highway=trunk` is used almost exclusively for dual-carriage motor-roads (aka expressways). However, in other countries not all `highway=trunk` are dual-carriageway, and sometimes there are dual-carriageway `highway=primary` and `highway=secondary` roads, especially in urban areas.

We could consider rendering `highway=motorway` in this sort of style at mid-zoom levels, since these are almost exclusively dual-carriageway. For `highway=trunk` we would have to look at secondary tags like `motorroad=yes` (in Europe) and `expressway=yes` (in North America), but these may not yet be used widely enough.

When I last considered this issue, I did not find any tag that specifies that an Openstreetmap way is part of a dual-carriageway highway. If there is no a tag that we could use to differentiate rendering, it would be necessary to do some complicated pre-processing or evaluate surrounding geometries (looking for nearly parallel ways with the same highway class and name or ref?) to find dual-carriageway highways. That might be too complex for this style.

**Comment by jeisenbe** [comment] 2019-10-17 06:26
For comparison, here's what this style looks like at the location shown above, at z14:

![z14-gartenstadt-current](https://user-images.githubusercontent.com/42757252/66982120-7a871080-f0f0-11e9-85bd-8f23c472f06a.png)

If you look carefully, it's apparent that the dual-carriageway roads are rendered significantly wider than the single-carriageway roads even at z14, due to the centerlines being separated by several pixels. It's even clearer at z15. But certainly by z13 and z12 it's no longer clear. 

However, I notice that the rendering example in Leaflet above shows some problems where the dual-carriageway splits:

![leaflet-split-dual-carriagway](https://user-images.githubusercontent.com/42757252/66982976-63e1b900-f0f2-11e9-89aa-62bb65ff64e0.png)
Vs
![dual-carriageway-to-separated](https://user-images.githubusercontent.com/42757252/66982913-3d238280-f0f2-11e9-867c-9c9511ff0cf1.png)

It would be difficult to make an idea rendering at such splits.

The openstreetmap.de style doesn't show a difference for the tertiary or primary highways which are dual carriageways, but it does show a special rendering for the trunk and motorway which emphasize that they are (usually) dual carriageways: https://www.openstreetmap.de/karte.html?zoom=14&lat=53.60105&lon=11.41567&layers=B000TT

**Comment by jeisenbe** [comment] 2019-10-17 06:37
German version at z14 (just highway=trunk is different):

https://www.openstreetmap.de/karte.html?zoom=14&lat=53.60105&lon=11.41567&layers=B000TT
![z14-gartenstadt-de-style](https://user-images.githubusercontent.com/42757252/66983247-16b21700-f0f3-11e9-86b4-2fba99244dab.png)

At z11 the trunk and motorway rendering is much wider due to the center line:
z11 openstreetmap.de
![z11-schwerin-de-style](https://user-images.githubusercontent.com/42757252/66983565-c7201b00-f0f3-11e9-810c-20dee37fbfc9.png)

z11 current Openstreetmap-carto
![z11-schwerin-current](https://user-images.githubusercontent.com/42757252/66983590-d737fa80-f0f3-11e9-8e13-d08cead66ae3.png)

**Comment by polarbearing** [comment] 2019-10-17 10:26
I agree with @jeisenbe that combining two parallel carriageways would require complicated pre-processing, as the carriageways are mapped separately in OSM. The grey 'WebAtlas' example in the first post apparently is from one of the governmental German portals, and might have a different vector representation behind. 
So far I was happy enough that in carto the two carriageways 'melt' together in lower zooms and become individually recognisable when zooming in. IIRC the "melting" effect is created by painting the casings first and the road fill later, so that the middle casings are painted over. 
As shown below, the WebAtlas does not separate the carriageways when zooming in:
![webatlas-example](https://user-images.githubusercontent.com/8266355/67001063-3d635400-f0d9-11e9-94f6-4b665dd0c243.png)

**Comment by IOOI-SqAR** [comment] 2019-10-17 11:05
Well, I did not know that the "melting together" of the two carriage ways to one road in lower zoom levels is the result of a clever way to render those roads. I admit that rendering the middle line based only on a clever rule derived from the geometries alone would be very difficult. But we have not just just the geometries to determine whether two lines are the individual carriage ways of the same road. We have also a set of tags on them to determine whether they belong to the same road.

For example:

Linie: Ludwigsluster Chaussee (397790115):

de:strassenschluessel	13004000000000368
highway	tertiary
maxspeed	50
name	Ludwigsluster Chaussee
oneway	yes
surface	asphalt

Linie: Ludwigsluster Chaussee (244139222):

de:strassenschluessel	13004000000000368
highway	tertiary
maxspeed	50
name	Ludwigsluster Chaussee
oneway	yes
surface	asphalt

as we can see here they are both "oneway yes", are both in the same category (here: "highway	tertiary"), most likely share the same name tag, or (this might differ regionally) have even a common key like here "de:strassenschluessel" (translates to "roadID"). Wouldn't that help?

**Comment by jeisenbe** [comment] 2019-10-18 03:11
The similar tags would help determine when two parallel ways are actually parts of a dual-carriageway, rather than a frontage road or service road along a major highway or something similar. The problem is at places like this:

![dual-carriageway-to-separated](https://user-images.githubusercontent.com/42757252/66982913-3d238280-f0f2-11e9-867c-9c9511ff0cf1.png)

Here we have two Openstreetmap ways tagged highway=tertiary and oneway=yes which make up a dual-carriageway road, but then they diverge at the junction. Where should the transition be between the dual-carriageway rendering vs two separate lines?

The openstreetmap.de style deals with this by just rendering a light-colored centerline for highway=trunk and highway=motorway. Note how the grey centerlines diverge as the trunk road approaches the intersection, because that's what the Openstreetmap ways do:

![german-trunk-bright-centerline](https://user-images.githubusercontent.com/42757252/67063017-22a7e280-f1a0-11e9-8114-4338484d7a5b.png)

We could do something like this, perhaps only for highway=motorway and highway=trunk + motorroad=yes / expressway=yes at lower and mid-low zoom levels, since this would not require any fancy pre-processing. 

I've also asked on the Developer talk mailing list if anyone else has already solved this issue. We will see if there is a technically feasible way to put the line right in the center.

**Comment by mboeringa** [comment] 2019-10-18 07:35
> The openstreetmap.de style deals with this by just rendering a light-colored centerline for highway=trunk and highway=motorway. Note how the grey centerlines diverge as the trunk road approaches the intersection, because that's what the Openstreetmap ways do:

From a cartographic point of view, this shows the German fork approach to rendering dual carriageway roads doesn't really work at high-to-mid zoom levels, because such rendering with a centerline actually requires physically merging the roads. 

In addition, e.g. in the Netherlands, many trunk roads with **motorroad=yes** aren't actually dual carriageways, just wider roads where it is often - but not always - forbidden to overtake and with a maxspeed of 100km/h:

![afbeelding](https://user-images.githubusercontent.com/7635726/67074214-ed43ca80-f188-11e9-874d-7b2c7c5d40a3.png)

In my own ArcGIS Renderer, I have chosen to render roads much thinner than carto at mid zoom, which helps in revealing dual carriageways, see this example from Terneuzen in the Netherlands:

![afbeelding](https://user-images.githubusercontent.com/7635726/67073691-ed8f9600-f187-11e9-8214-5c48cf90bbfc.png)

**Comment by kennykb** [comment] 2019-10-18 20:02
On Thu, Oct 17, 2019 at 7:05 AM IOOI-SqAR <notifications@github.com> wrote:

> Well, I did not know that the "melting together" of the two carriage ways
> to one road in lower zoom levels is the result of a clever way to render
> those roads. I admit that rendering the middle line based only on a clever
> rule derived from the geometries alone would be very difficult. But we have
> not just just the geometries to determine whether two lines are the
> individual carriage ways of the same road. We have also a set of tags on
> them to determine whether they belong to the same road.
>
That's not going to work universally, either. While ways
https://www.openstreetmap.org/way/143667240 and
https://www.openstreetmap.org/way/56671814 are the individual carriageways
of the same road, we'd want them rendered separately even at quite a low
zoom level. (I have to zoom out all the way to z9 before it would plausibly
make sense to merge them - at higher zooms you surely don't want to lose
the water.)

**Comment by IOOI-SqAR** [comment] 2019-10-20 00:01
> I've also asked on the Developer talk mailing list if anyone else has already solved this issue. We will see if there is a technically feasible way to put the line right in the center.

I put a link to this discussion here in case somebody wants to follow it or chime in there:

https://lists.openstreetmap.org/pipermail/dev/2019-October/030751.html

**Comment by jeisenbe** [comment] 2019-10-20 06:02
Based on the results of the discussion on the OSM-dev mailing list, it appears that this problem is difficult to solve. Several developers mentioned that it is difficult to get good results even with extensive pre-processing, eg: 
"The algorithms I have tried do the right thing in many cases but totally jumble up some complex junctions"

There are a couple of methods which might work at certain scales, but might not work universally and may not be applicable to this style: 
- https://lists.openstreetmap.org/pipermail/dev/2019-October/030757.html
- https://github.com/johannessen/combiner

I'm closing this issue because the extensive pre-processing involved is probably not feasible for this style. 

However, it would be possible to consider a special rendering for trunks with motorroad=yes or expressway=yes, or for motorways, perhaps similar to the openstreetmap.de style as mentioned above. If this is interesting, a new issue could be opened about that idea.

**Closed by jeisenbe** 2019-10-20 06:02 UTC
Labels: roads
