### ISSUE TITLE
fill walls with area=yes

### ISSUE THREAD

**Issue by tamkto** [gravitystorm/openstreetmap-carto#4239] opened 2020-10-29 17:35 UTC
barriers (most commonly walls) are sometimes mapped as areas:

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dwall
_It is also possible to map a wall as an area. Then draw the basic area of the wall and add area=yes._

but currently only an outline is displayed, regardless of the area tag. it should probably be filled when area=yes, similarly to a building. this is relevant for thicker walls.

also, maybe barrier=city_wall and barrier=wall + wall=castle_wall should be rendered similarly, as they are typically very similar (currently city_wall is thicker on the map than castle_wall).

**Comment by jeisenbe** [comment] 2020-10-29 18:28
@tamko, this is a duplicate of issue #3453, which you might not have seen because it was closed. 

We intentionally chose not to do this. See the issue above, and also see pull requests #3834 and #3844 about `barrier=hedge` with `area=yes`, and related issue #4111

**Closed by jeisenbe** 2020-10-29 18:28 UTC
Labels: duplicate

**Comment by matkoniecz** [comment] 2021-02-13 09:36
https://overpass-turbo.eu/s/12TV https://overpass-turbo.eu/s/12TS  may be useful for detecting bad mapping of `barrier=hedge amenity=school` type - combining barrier around, with area. It is one of main blockers for barrier area rendering in OSM Carto.

See for example amenity=school + barrier=hedge on one closed way.

https://www.openstreetmap.org/way/106629251

Rendering in map style supporting hedges as areas:
https://map.atownsend.org.uk/maps/map/map.html#zoom=17&lat=51.667521&lon=-0.59261

See also https://josm.openstreetmap.de/ticket/10551
