### ISSUE TITLE
PolygonPatternSymbolizer: PNG versus SVG

### ISSUE THREAD

**Issue by Klaus-Tockloth** [gravitystorm/openstreetmap-carto#3562] opened 2018-12-11 09:10 UTC
In some cases PNGs are used as PolygonPatternSymbolizer, in other cases SVGs.

```
<Rule>
  <MaxScaleDenominator>50000</MaxScaleDenominator>
  <Filter>([natural] = 'scrub') and ([int_wetland] != null)</Filter>
  <PolygonPatternSymbolizer file="symbols/scrub.png" alignment="global" />
</Rule>

<Rule>
  <MaxScaleDenominator>100000</MaxScaleDenominator>
  <Filter>([natural] = 'wood') and ([leaf_type] = 'broadleaved')</Filter>
  <PolygonPatternSymbolizer file="symbols/leaftype_broadleaved.svg" alignment="global" />
</Rule>

```
Are there plans to render all PolygonPatternSymbolizers as SVGs?

**Comment by Adamant36** [comment] 2018-12-11 10:46
What would be the advantages/disadvantages? I've been wondering what the pros and cons of going with one format over the other is for a while now.

**Comment by kocio-pl** [comment] 2018-12-11 11:17
There is such plan and there is a #2045 (so I will close it as a duplicate), however there were technical problems with rendering, probably caused by Mapnik. We got stuck in the middle of conversion and the problem hasn't been researched more since then.

With SVG one can use different resolution and have properly scaled patterns. It's also one step less to maintain (see the problems with rasterization in #3051) and also makes it easier to change colors.

**Closed by kocio-pl** 2018-12-11 11:17 UTC
Labels: duplicate
