### ISSUE TITLE
`amenity=festival_grounds` doesn't have the `name` rendered

### ISSUE THREAD

**Issue by mikaeldui** [gravitystorm/openstreetmap-carto#4943] opened 2024-03-14 23:03 UTC
### Expected behavior
One would expect the name of a location that get maybe a million visits per year to have its name on the map.

### Actual behavior
The name isn't rendered at all.

### Screenshots with links illustrating the problem
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/3706841/43e4b534-2164-45ed-a62e-d689da94e135)
https://www.openstreetmap.org/relation/14384584#map=17/59.44505/24.80628 

Similar location, a zoo, with its name clearly visible:
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/3706841/0ed6cc84-46fc-4af2-86c0-cfac315a3ff4)
https://www.openstreetmap.org/relation/4114592#map=16/59.4205/24.6617

**Comment by HolgerJeromin** [comment] 2024-03-15 05:22
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfestival_grounds
Has about 550 area elements in the osm database.

**Comment by imagico** [comment] 2024-03-15 10:58
The tag documentation lacks a language and culture independent definition of a _festival_ and a delineation towards other tags in the domain (in particular `amenity=music_venue`, `amenity=events_venue` and `amenity=theatre` + `theatre:type=open_air`).

Practical use currently has significant concentrations in Estonia (180 uses) and southern Spain (138 uses).

**Comment by imagico** [comment] 2024-05-19 12:44
This is actually a duplicate of #3990 - closing as such. Any new discussion should go there.

**Closed by imagico** 2024-05-19 12:44 UTC
Labels: new features
