### ISSUE TITLE
Please render natural=fell

### ISSUE THREAD

**Issue by abdeldjalil09** [gravitystorm/openstreetmap-carto#2923] opened 2017-11-03 10:30 UTC
This issue is part of #545

**Comment by kocio-pl** [comment] 2017-11-03 19:06
Why do you think it's useful to make it a separate issue?

**Comment by turnsole80** [comment] 2017-11-04 01:02
I'd love this to happen, but for the life of me, I can't think of a rendering style that works. Does anyone have any suggestions?

**Comment by SomeoneElseOSM** [comment] 2017-11-04 10:51
@turnsole80 I can't think of a _distinct_ rendering style that would make sense, for the reasons spelt out at https://github.com/gravitystorm/openstreetmap-carto/issues/545#issuecomment-98479426 .  In a different map style I do render it via https://github.com/SomeoneElseOSM/SomeoneElse-style/blob/0276ca282634b7d6af368e8614b0bf5dfc000530/style.lua#L1536 , but that's essentially based on the fact that people misuse "heath" for "generic upland".
Realistically it's not going to proceed in this style unless someone says "here's a rendering that I've made that works".  If I were you I'd definitely have a go with that, as suggested at https://github.com/gravitystorm/openstreetmap-carto/issues/545#issuecomment-330003458 .

**Comment by matkoniecz** [comment] 2017-11-04 12:56
Closing as duplicate of #545 

Note https://github.com/gravitystorm/openstreetmap-carto/issues/545#issuecomment-98479426

**Closed by matkoniecz** 2017-11-04 12:56 UTC

**Comment by abdeldjalil09** [comment] 2017-11-04 13:24
> Closing as duplicate of #545
I said "This issue is part of #545"

**Comment by matkoniecz** [comment] 2017-11-04 13:28
natural=fell was already discussed in #545. Opening new issue that was not even linking discussion that happened makes no sense.

Overall, I think that #545 from start should be split into separate issues, but as discussion already started there long time ago it is not useful to split this issue now.
