### ISSUE TITLE
Render linear and small features **above** pedestrian area

### ISSUE THREAD

**Issue by apophenic-treehugger** [gravitystorm/openstreetmap-carto#4746] opened 2022-12-09 20:23 UTC
Hi,

pedestrian areas (`highway=pedestrian` + `area=yes`) are currently rendered above almost anything else and thus obscure a lot of features that would otherwise be rendered.

This is unlike the rendering results for other area types (`landuse=residential`, `leisure=park`, `amenity=hospital`, ...), where features that are smaller (buildings, patches of grass, parkings, ...) or 1-dimensional (walls, fences, ...) are rendered _above_ the enclosing (i. e. larger) area.

### Expected behavior
On a pedestrian area, I would expect that smaller areas enclosed by that pedestrian area are drawn **above** the pedestrian area (as is the case for a patch of grass within a park).

Furthermore, and more importantly, I'd expect linear features, like barriers (walls, fences, ...) to be drawn above that pedestrian area.

For 2d-features the desired behaviour can be achieved on the mapping side by making the pedestrian area a multipolygon with the smaller areas as `role=inner`. But this is cumbersome and [somewhat hackish](https://wiki.openstreetmap.org/wiki/Good_practice#Don't_map_for_the_renderer).

### Actual behavior
Only dimensionless features (tagged nodes) and some types of highways area drawn above pedestrian areas.

Walls, fences, retaining walls, grass (and probably much more) which are enclosed by a `highway=pedestrian` + `area=yes` are currently not visible.

### Screenshots with links illustrating the problem
For example, at the North Eastern area of [Trg republike](https://www.openstreetmap.org/relation/14987054#map=18/46.05046/14.50075&layers=N) in Slovenia, [retaining walls](https://www.openstreetmap.org/way/1120556342) are not rendered. (Note that the oneway arrows are from underground parking aisles at layer=-1, but this is _not_ the subject of this request.)

![image](https://user-images.githubusercontent.com/81189494/206787179-62c6051e-52ff-4668-acc2-911f30dca01d.png)

**Comment by imagico** [comment] 2022-12-09 20:50
Thanks for the suggestion, this is a duplicate of #528/#2958/#3281.  I summarized the current status and the difficulties of this topic a few days ago in https://github.com/gravitystorm/openstreetmap-carto/issues/172#issuecomment-1332262761.

Side note: Cutting buildings/flowerbeds/ponds etc. surrounded by a pedestrian areas out of the mapping representation by use of multipolygons is not mapping for the renderer, it is accurate documentation of the geography since a building/flowerbed/pond is not actually part of the pedestrian area.  This is different from most of what we render in the landcover layer where overlapping polygons are often semantically correct (a grass patch or a pond in a park is still part of that park).

**Closed by imagico** 2022-12-09 20:50 UTC
