### ISSUE TITLE
Label for leisure=fishing

### ISSUE THREAD

**Issue by eehpcm** [gravitystorm/openstreetmap-carto#4161] opened 2020-06-14 12:25 UTC
### Expected behavior
Label expected to be central (ish) within area.

### Actual behavior
Label is partially outside the border of the area at all but z=17 and is only just within the border at z=17.

### Links and screenshots illustrating the problem
[Way 815090270](https://www.openstreetmap.org/way/815090270)

**Comment by jeisenbe** [comment] 2020-06-18 01:04
The icon is inside of the area, while the text label is always placed to the south (below the icon) as usual. Unfortunately the automated icon placement, which uses ST_PointOnSurface, is sub-optimal in this case:

<img width="378" alt="Screen Shot 2020-06-17 at 18 03 35" src="https://user-images.githubusercontent.com/42757252/84965857-e331ed00-b0c4-11ea-852a-d23ab99fa7a1.png">

This is a duplicate of #3857, so I will close this issue. Please continue discussion at the older issue.

**Closed** 2020-06-18 01:06 UTC
Labels: duplicate
