### ISSUE TITLE
Render area for amenity=biergarten

### ISSUE THREAD

**Issue by dktue** [gravitystorm/openstreetmap-carto#3668] opened 2019-02-03 14:18 UTC
I would like to see the extent of a biergarten as they often take up big areas.

# Current rendering
![image](https://user-images.githubusercontent.com/2878623/52177805-d01bc700-27c6-11e9-88f9-ff618e1ae566.png)

# Actual extent
![image](https://user-images.githubusercontent.com/2878623/52177815-e6c21e00-27c6-11e9-93a1-9fb19044b3c9.png)

I know the issue 858 was closed in 2014 b want to reopen discussion as now we have 2019 and OpenStreetMap and this style have changed alot.

**Comment by polarbearing** [comment] 2019-02-08 14:11
ref #858 - is it necessary to open a new ticket for this? Discussion can continue there.

**Comment by matkoniecz** [comment] 2019-02-08 16:27
I think that it is impossible to continue increasing number of different landcovers.

Also number of different outlines is limited.

I propose to close this as this area is not critically important to render, unlike some more important areas so starting from rendering biergarten areas is not a good idea.

Also, note that in the given example landuse tagging is not completed.

**Comment by Adamant36** [comment] 2019-02-09 04:53
If this was combined with a landuse what would it be? Retail? Or maybe leisure=Park? 

Not knowning that much about them I would consider them like playgrounds. Maybe not a major feature, but still worth rendering areas due to their significance with the things around them. Like in the example above its next to a park and what looks like a square maybe. It would make sense for it to have a fill color in a case like that so its a clearly seperate area. 

I'm not sure its impossible to increase the number of landcovers either. Its a big world and there will always be empty space. It really wouldn't make a difference here that I can tell. Your complaint sounds like a good condidate for a "meta issue" though. As its not really specific to this.

**Comment by jeisenbe** [comment] 2019-08-02 15:03
If it's like a restaurant or bar, that can be tagged with landuse retail, or if it's part of a brewery perhaps landuse=commercial is better. If that doesn't work and there are large grassy areas  you could tag the landcover as landuse=grass and map any trees, or if it's mainly covered by trees use natural=wood. So I think it's not necessary to map a specific landcover color, and this issue could be closed.

**Comment by pnorman** [comment] 2019-08-02 17:23
Duplicate of #858. We can continue the discussion there and re-open it if there are new reasons that mean the decision should be different.

**Closed by pnorman** 2019-08-02 17:23 UTC
Labels: amenity-points
