### ISSUE TITLE
Dead ends become four-way intersections at lower Zoom levels

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4735] opened 2022-11-25 16:59 UTC
At lower zoom levels this dead end north-south road magically becomes joined to the east-west road to the south. https://www.openstreetmap.org/?mlat=42.181802&mlon=-87.8107858#map=15/42.181802/-87.8107858

Okay, here it is with the marker removed so you can see it:
 https://www.openstreetmap.org/?#map=15/42.181802/-87.8107858

Sure, you can blame the mapper person that s/he didn't give enough distance between the end of that road and the road on the other side of the barrier. But the case still remains: somebody has made this dead end into an intersection that people think they can drive their cars over, until they get there.

Sure, you might say, "Well it's the map user's  own fault for not zooming the map enough." Then they could reply,  "The map is already good enough. Why do I need to remember to zoom it?"

Yes you might say, "But this won't affect routing, so what's the big deal?" Well there's still some people looking at the maps  the old fashioned way...

(I didn't test it, but maybe bridges spring up over rivers too, if the two edges have roads to close together?)

**Comment by imagico** [comment] 2022-11-25 21:37
Duplicate of #286.  That is closed as wontfix-unfeasible - so reopening that is only an option if someone actually comes up with a practically viable method (which is not impossible - but hard).  See also #4375.

**Closed by imagico** 2022-11-25 21:37 UTC
