### ISSUE TITLE
Render `highway=unclassified` after `highway=primary`

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#2055] opened 2016-02-22 11:07 UTC
Hello.

Currently, the rendering order makes `highway=unclassified` being rendered after `highway=primary`, which causes [this rendering](https://www.openstreetmap.org/#map=19/48.30852/6.06667); IMHO, `highway=unclassified` should be rendered under, so before, `highway=primary`, as it is a less important road.

Regards.

**Comment by math1985** [comment] 2016-02-22 11:56
Thanks for reporting! This seems to be a duplicate of of #266, #678, #1334, and #1985.

**Closed by math1985** 2016-02-22 11:56 UTC

**Comment by matkoniecz** [comment] 2016-02-22 13:16
BTW, it may be data error - it seems likely that it is rather highway=service.
