### ISSUE TITLE
Render place names from their relations

### ISSUE THREAD

**Issue by Dimitar5555** [gravitystorm/openstreetmap-carto#4872] opened 2023-09-19 06:26 UTC
### Expected behavior

OSM Carto should render names on nodes with `role=label` in `boundary=place` relations without having to duplicate every tag from the relation to that node.

### Actual behavior

Removing all tags from that node removes the label from the map.

Resolving this issue would allow to stop duplicating the hundreds of names of `place`s on two elements.

**Comment by pnorman** [comment] 2023-09-19 07:05
Duplicate of #105

**Closed by pnorman** 2023-09-19 07:05 UTC
