### ISSUE TITLE
Parking label placement

### ISSUE THREAD

**Issue by eehpcm** [gravitystorm/openstreetmap-carto#3296] opened 2018-07-08 15:34 UTC
### Expected behavior

I expect the "P" label to be within the boundary of the parking area.

### Actual behavior

For obscure shapes of parking area, "P" label can be misleadingly outside the boundary of the area.

### Links and screenshots illustrating the problem

[Link to affected area](https://www.openstreetmap.org/?mlat=52.07901&mlon=-4.65735#map=19/52.07901/-4.65735)

The fix for this may be simply invoking code you already have that is used on other objects, or it could be complex and very resource intensive.  If the latter then I intend to break the car parking up into two adjoining areas (I know this gives a better, but sub-optimal, result, even if it's tagging for the renderer).  If the former then I'll leave it as is.

**Comment by sommerluk** [comment] 2018-07-08 17:00
Thanks for the bug report.

This is a duplicate of  #1456 which is a Mapnik issue solved in https://github.com/mapnik/mapnik/issues/3558 and is pending for installation on openstreetmap.org (may take some weeks or months until deloyed). Closing.

**Closed by sommerluk** 2018-07-08 17:00 UTC

**Comment by eehpcm** [comment] 2018-07-08 17:13
Erm, call me dense but I don't understand how #1456 is remotely similar to this.  Superficially they look like very different problems.

This isn't a layering problem as such, it's a the "P" is in the wrong location problem.  Fixing things so the "P" is underneath the building hides the problem, it doesn't fix it.  It would still be a problem if that building weren't there, it just wouldn't be so obviously a problem.

**Comment by SomeoneElseOSM** [comment] 2018-07-08 18:40
@eehpcm  just for info - I have a rendering server covering that area with an updated Mapnik version and the "P" occurs as expected in the car park.

**Comment by HolgerJeromin** [comment] 2018-07-08 21:09
> Erm, call me dense but I don't understand how #1456 is remotely similar to this. Superficially they look like very different problems.

I think sommerluk referenced the wrong issue. #1465 is probably the right one :-)

**Comment by eehpcm** [comment] 2018-07-08 22:05
@HolgerJeromin 

Yeah, I think so too.  I've made worse typos, though. :)

**Comment by eehpcm** [comment] 2018-07-08 22:17
@SomeoneElseOSM 
If you're who I think you are, that must be a different server from the one of yours I know about.  That one still has the P in the wrong place.  And still uses a chair as the icon for a glazier.

Still, it means the problem will be fixed on OSM if it's fixed in your mapnik renderer.

**Comment by SomeoneElseOSM** [comment] 2018-07-08 22:49
> If you're who I think you are, that must be a different server from the one of yours I know about.

Yes - different server.  The public one is Ubuntu 16.04 and an older version of Mapnik; the less public one is Ubuntu 18.04 and a newer Mapnik.  Same map style on both.

>  And still uses a chair as the icon for a glazier.

(apologies in advance for offtopic diversion but) that's actually a design decision to reduce the total number of icons in use.  As ever, pull requests welcome :)
