### ISSUE TITLE
Render problems with multipolygon natural:wood over leisure:golf_course

### ISSUE THREAD

**Issue by dalkvist** [gravitystorm/openstreetmap-carto#4784] opened 2023-03-03 07:51 UTC
Scenario, when a large multipolygon natural:wood is partly overlapping a leisure:golf_course polygon
### Expected behavior
The multipolygon natural:wood is rendered over the leisure:golf_course just as the simple polygon natural:wood are.
### Actual behavior
The solid green of the natural:wood is rendered under the leisure:golf_course and the broadleaf tree symbols are rendered over the leisure:golf_course
### Screenshots with links illustrating the problem
![image](https://user-images.githubusercontent.com/674035/222661599-9a4dfa06-9f1b-4e75-a114-9813cbcd1a24.png)
https://www.openstreetmap.org/#map=17/68.40857/18.67088

**Comment by imagico** [comment] 2023-03-03 10:20
Thanks for the report.

This is a duplicate of #4371.

Landcover polygon fills are rendered in the order of polygon size with the smallest last.  This is a conscious choice and provides the most comprehensive feedback on what is mapped.

**Closed by imagico** 2023-03-03 10:20 UTC
