### ISSUE TITLE
Combining diacritics rendering wrong in various languages

### ISSUE THREAD

**Issue by claysmalley** [gravitystorm/openstreetmap-carto#2017] opened 2016-01-06 07:10 UTC
Many South Asian alphabets have combining characters that appear to the left of the character they "attach" to. These seem to be rendering on the wrong side of the combining character in various languages. Some other marks are rendering too high, too low, or not at all. It looks hella clowny, and unreadable in some cases, to native readers of these languages.

English | Native Script | Mapnik
---------- | ------------ | --------
Mandalay Myo | Burmese: မန္တလေးမြို့ | ![selection_264](https://cloud.githubusercontent.com/assets/1732117/12136170/cf46c260-b3f9-11e5-9e5c-4c642fc10986.png)
Manikganj | Bengali: মানিকগঞ্জ | ![selection_268](https://cloud.githubusercontent.com/assets/1732117/12136627/b2ef38fe-b3fe-11e5-8358-3ef31087bbb5.png)
Birtamod | Devanagari: बिर्तामोड | ![selection_269](https://cloud.githubusercontent.com/assets/1732117/12136707/5c5e98da-b3ff-11e5-9362-6e9cb10b20fd.png)
Changwat Surin | Thai: จังหวัดสุรินทร์ | ![selection_272](https://cloud.githubusercontent.com/assets/1732117/12137254/baf1d944-b403-11e5-933b-8a2a6dff6366.png) (last mark is too high)
Shigatse | Tibetan: གཞིས་ཀ་རྩེ | ![selection_271](https://cloud.githubusercontent.com/assets/1732117/12136804/2325efe0-b400-11e5-9150-9f923034716c.png) (also bad spacing)
Gondar | Ethiopic: ጎንደር | ![selection_270](https://cloud.githubusercontent.com/assets/1732117/12136754/bc4a782c-b3ff-11e5-8976-3ddbe0463bab.png) (no combining diacritics, just bad spacing)

**Comment by gravitystorm** [comment] 2016-01-06 08:40
There are many font rendering problems currently showing on the openstreetmap.org tileserver, since it is running an older version of the mapnik rendering library. Most will be fixed when the server admins upgrade to mapnik 3, [which will hopefully happen soon](https://github.com/openstreetmap/chef/issues/39).

Can you check your examples against the opencyclemap and/or transport layers please? Both of these are using a similar list of fonts to openstreetmap-carto, but have already been upgraded to mapnik 3.

**Comment by claysmalley** [comment] 2016-01-06 09:33
Just checked. Transport Map and Cycle Map look great! Ethiopic text still has the weird spacing issue but complex text layout is working just fine.

**Comment by pnorman** [comment] 2016-01-06 19:32
It's not needed in this case, but in general it's best to include an image of the correct rendering, since otherwise we're depending on our browser to render the text correctly.

**Comment by qeith** [comment] 2016-01-15 18:17
I can confirm that Tibetan and Devanagari are rendering far better in the cycle and transport layers. Both had the correct order/orientation for the places I checked, and only some spacing issues remained. For Tibetan these spacing issues are far less than they are at present in the default layer's rendering.

**Comment by pnorman** [comment] 2016-05-18 08:42
Burmese, Bengali and Devanagari are all confirmed fixed with Mapnik 3. I'll review the others when done with some pre-rendering.

**Comment by pnorman** [comment] 2016-05-18 20:07
Most of these are fixed in Mapnik 3.

If there are still problems, please open a new ticket for the issue. It's possible some of the fonts might need changing. Include links to the problem area, a **picture** of the correct rendering of the text, and a picture of the rendering of the area. tile.osm.org doesn't use Mapnik 3, so you can't use it for this.

**Closed by pnorman** 2016-05-18 20:07 UTC
Labels: general

**Comment by math1985** [comment] 2016-09-11 18:35
@claysmalley Mapnik 3 has now been rolled out. Could you have a look whether this has improved now? If now, could you provide a link to the map location where you find bad rendering (some tiles might not have been refreshed since the upgrade)?

**Comment by claysmalley** [comment] 2016-09-11 20:57
Burmese: :heavy_check_mark: renders properly. Note: if you find any broken Burmese text, it's likely that it was typed up in the wrong encoding (Zawgyi instead of Unicode)
Bengali: :heavy_check_mark: renders properly
Devanagari: :heavy_check_mark: renders properly
Thai: :warning: renders properly, though the font for city labels is monospace
Lao: :heavy_check_mark: renders properly
Tibetan: :warning: renders properly, although font is small and hard to read
Ethiopic: :heavy_check_mark: renders properly
Sinhala: :x: totally broken; could probably be fixed just by using a better font

I'll open a new ticket for each of the issues here

**Comment by claysmalley** [comment] 2016-09-11 21:27
#2336, #2337, #2338

**Comment by math1985** [comment] 2016-09-11 22:54
Thanks!
