### ISSUE TITLE
Placing of labels should take population numbers into account

### ISSUE THREAD

**Issue by AxelBoldt** [gravitystorm/openstreetmap-carto#1672] opened 2015-07-21 15:50 UTC
https://www.openstreetmap.org/node/1569338041#map=10/49.4396/11.1182 shows the city of Nürnberg, but if you zoom out, the name label "Nürnberg" vanishes. Fürth, just to the north-west, is properly labeled, even though Nürnberg is five times larger. 

City labels should be placed in order of population size, so that in case of conflict the smaller city's label is suppressed.

**Comment by matkoniecz** [comment] 2015-07-21 15:51
Duplicate of #1083

**Closed by matkoniecz** 2015-07-21 15:51 UTC
Labels: duplicate
