### ISSUE TITLE
Underpass road label draped across overpass

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4853] opened 2023-08-07 08:01 UTC
### Expected behavior
If a road goes under another road, then its name should also respect that situation.
(No, not go under too. But instead: James Street ===, === James Street, or James === Street. (One side, the other side, or both sides ("===" represents the overpass.)))
### Actual behavior
Draping the road underneath's name across the road on top's overpass distracts the user's eyes from the very delicate overpass situation, making it look like both roads are on the same level.
### Screenshots with links illustrating the problem
https://www.openstreetmap.org/?mlat=42.18014&mlon=-87.82014#map=17/42.18014/-87.82014
![20230807T025322](https://github.com/gravitystorm/openstreetmap-carto/assets/1230959/c18ffac2-9d07-4b73-8539-bf842e926787)
![20230807T025529](https://github.com/gravitystorm/openstreetmap-carto/assets/1230959/951bfc24-9464-4af4-bf13-148c1eaf3844)

**Comment by imagico** [comment] 2023-08-07 08:27
Duplicate of #4401.

**Closed by imagico** 2023-08-07 08:27 UTC
