### ISSUE TITLE
Regression in highway=track rendering due to color re-definition in #4666

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#4881] opened 2023-10-06 17:55 UTC
#4666 caused a regression in rendering of `highway=track`:

![track](https://imagico.de/files/track_regression.png)

Caused by re-defining `@track-fill`/`@track-casing` in

https://github.com/gravitystorm/openstreetmap-carto/blob/445e5532b934dc68c7a4b0d3929e188bb837ae5a/style/tourism.mss#L3-L4

compared to

https://github.com/gravitystorm/openstreetmap-carto/blob/445e5532b934dc68c7a4b0d3929e188bb837ae5a/style/roads.mss#L18
https://github.com/gravitystorm/openstreetmap-carto/blob/445e5532b934dc68c7a4b0d3929e188bb837ae5a/style/roads.mss#L44

**Comment by MeonStudios** [comment] 2023-11-02 14:19
Hi, I was looking at this issue already last week, since it has the label `good first issue` and you also mentioned it in my previous PR. However I am not quite sure I understand what the issue is and what exactly needs to change.

I assume it has to do with the fact that due to #4666 the track is now rendered in a different color and that should be fixed. Is this correct and/or would you mind elaborating a bit?

**Comment by imagico** [comment] 2023-11-02 15:12
#4666 used the identifiers `@track-casing` and `@track-fill` to define the colors for roller coasters without taking into account that these are already used for highway=track.  This overloading of identifiers needs to be removed, using different ones for the roller coasters.

In addition it would of course be useful to have a check for re-definitions of identifiers in MSS code in the CI workflows - this, however is not required for resolving the regression.

**Closed** 2023-11-09 21:33 UTC
Labels: regression, roads, good first issue
