### ISSUE TITLE
Display of POIs with "more unknown" craft or office-Keys

### ISSUE THREAD

**Issue by SafetyIng** [gravitystorm/openstreetmap-carto#4410] opened 2021-05-20 22:13 UTC
### Expected behavior
Display "business" nodes, like craft or office as normal POI.

### Actual behavior
Shown as adressnodes. so you get doubled adress points on the map.

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=19/52.03218/11.22885 (Map section)
https://www.openstreetmap.org/way/945280202 (building)
https://www.openstreetmap.org/node/8751284334 (POI 1 - correct displayed)
https://www.openstreetmap.org/node/8751284335 (POI 2 - false displayed)

**Comment by HolgerJeromin** [comment] 2021-05-21 06:00
Thanks for filing this issue. 
This is a duplicate of #1697

**Comment by imagico** [comment] 2021-05-21 12:17
We have two issues here in one - the rendering of craft and office features - which as @HolgerJeromin mentioned is covered by #1697 and the multiple renderings of housenumber labels for the same housenumber being tagged on multiple not geometrically separate features (like several offices in a single building).  There appears to be no clear consensus among mappers on this - see https://wiki.openstreetmap.org/wiki/Addresses explaining that address data should not be duplicated although - as you show - this is frequently not followed practically.  In any case - we don't have a solid basis for changing anything here - so closing also this.

**Closed by imagico** 2021-05-21 12:17 UTC
