### ISSUE TITLE
Major cities rendering problem when overlaps at low zoom levels 

### ISSUE THREAD

**Issue by pierzen** [gravitystorm/openstreetmap-carto#1337] opened 2015-02-26 14:02 UTC
The standard style treats differently overlap of cities as compared to Mapquest and Humanitarian styles, We can see this for Montreal http://www.openstreetmap.org/#map=8/45.558/-74.526

There are three cities closed one to the other. The most important one, Montreal is not showed at zoom 8.  Montreal (border relation) overlaps with Longueuil (node Place name). The smallest city is showed at level 8.

Relation : Montréal (1634158) 
population 	1735450

Relation : Laval (1438336) 
population 	401553

Node Longueuil (252025539) 
population 	234352

![montreal](https://cloud.githubusercontent.com/assets/680008/6393215/351210aa-bd96-11e4-80f4-d2d10754a13f.png)

**Comment by mkoniecz** [comment] 2015-02-26 14:56
duplicate of #1083

**Closed by mkoniecz** 2015-02-26 14:56 UTC
