### ISSUE TITLE
unified size rhythm for symbols (and probably also for text)

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1145] opened 2014-12-08 06:09 UTC
from https://github.com/gravitystorm/openstreetmap-carto/issues/710#issuecomment-61376707 - reported by @nebulon42

Having an unified size rhythm for symbols (and propably also for text) would be good. Currently there are symbols with 2 and 3 as base value for their size. A unified size rhythm would improve consistency and it would be easier to agree on a common symbol (SVG) base size like e.g. 16px.

Why this came to my attention: When working on #1108 I tried to represent all the various squares with a single SVG but could not find a suitable base size that would avoid scaling by e.g. 2.667 for some symbols. For this simple square I now chose a size of 1x1px, which can be scaled arbitrarily. For more complex symbols this is, of course, not possible.

**Comment by kocio-pl** [comment] 2017-08-30 01:35
I guess this is mostly duplicate of #974 and it's not clear what we should do with text, so I'm closing it. It can be reopened later if needed.

**Closed by kocio-pl** 2017-08-30 01:35 UTC
Labels: amenity-points
