### ISSUE TITLE
Desert rendering

### ISSUE THREAD

**Issue by Volodimir50** [gravitystorm/openstreetmap-carto#4928] opened 2024-01-29 11:51 UTC
Good day. Is it possible to make natural=desert render in color on the main map and not only on humanitarian?

**Comment by HolgerJeromin** [comment] 2024-01-29 12:03
This is a duplicate of rejected #4488

> Closing as we previously deliberately removed rendering of natural=desert and the tag is generally considered poorly defined and non-verifiable. Further development of tagging arid region physical geography, specifically dunes and dune-fields, would definitely be desirable and if established could be considered for rendering here.

**Comment by imagico** [comment] 2024-01-29 12:43
Closing as duplicate.  Any arguments for re-considering should be brought up in #4488.

**Closed by imagico** 2024-01-29 12:43 UTC

**Comment by Volodimir50** [comment] 2024-01-29 13:48
Deserts are not only sandy. It is a mistake to think that the desert is sand. I am now drawing the territory of Kazakhstan, there are deserts, but not from sand. There will be many such objects and I would like to see them in color. For example, on the humanitarian layer, it is perfectly visible. Add color rendering to the base layer as well
