### ISSUE TITLE
Frankfurt missing in z7 and z8

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#1811] opened 2015-09-03 23:12 UTC
It is there in zoom6 but then disappears in favor of Offenbach:
http://www.openstreetmap.org/?mlat=50.147&mlon=8.600#map=8/50.147/8.600

**Comment by kocio-pl** [comment] 2015-09-04 09:51
That's something related to https://github.com/gravitystorm/openstreetmap-carto/pull/1461, can you test if this code fixes the issue?

**Comment by matkoniecz** [comment] 2015-09-04 11:21
duplicate of #1083

**Closed by matkoniecz** 2015-09-04 11:21 UTC
Labels: duplicate
