### ISSUE TITLE
trees are covering station labels and symbols

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1470] opened 2015-04-03 19:33 UTC
Currently this is not much of an issue as the canopy has an opacity of 0.3. One has to watch closely to notice this. This will likely become an issue if the opacity is increased (e.g. by a fork).

Suggested fix: move tree layer below stations layer

**Comment by nonpenso** [comment] 2015-04-23 06:01
Is not related to stations only, but it seems trees have the priority on every labels and symbols, so that they are shown only if there are a space without trees.
So I suggest to move tree layer below all labels and symbols

**Comment by pnorman** [comment] 2015-04-23 06:14
> Is not related to stations only, but it seems trees have the priority on every labels and symbols, so that they are shown only if there are a space without trees.

That is a different issue, and a duplicate of #1425

**Closed** 2015-10-19 20:13 UTC
Labels: amenity-points, station
