### ISSUE TITLE
Rendering problem if highway=busway is used

### ISSUE THREAD

**Issue by GJDillen** [gravitystorm/openstreetmap-carto#4902] opened 2023-11-12 06:33 UTC
### Expected behavior:
roads tagged with: highway=busway being visible on the Carto-map

### Actual behavior
roads tagged with: highway=busway are not visible 

### Screenshots with links illustrating the problem
![IMG_0204](https://github.com/gravitystorm/openstreetmap-carto/assets/150048160/ed66e8a8-b50b-4f23-8f1f-d4e9f00bf4ff)
![IMG_0205](https://github.com/gravitystorm/openstreetmap-carto/assets/150048160/c037e16a-8af4-4ed2-86fa-347f9bbc7f4b)
![IMG_0206](https://github.com/gravitystorm/openstreetmap-carto/assets/150048160/56fb3d56-384a-433d-b3d0-913d24df7132)

https://www.openstreetmap.org/#map=18/52.38728/4.63838

**Comment by HolgerJeromin** [comment] 2023-11-12 07:44
Thanks for the report.
This is a duplicate of #4226

**Comment by GJDillen** [comment] 2023-11-12 08:01
Maybe my summary post will convince that this issue REALLY needs be solved ?

**Comment by pnorman** [comment] 2023-11-12 09:05
Closing as duplicate.

**Closed by pnorman** 2023-11-12 09:05 UTC
