### ISSUE TITLE
landcover=trees areas are not rendered

### ISSUE THREAD

**Issue by CarlosBrys** [gravitystorm/openstreetmap-carto#3079] opened 2018-02-20 20:05 UTC
Please, consider render the areas tagged as landcover=trees.
This tag is useful to represent groups of urban trees and parks, but actually is not visible on the render.
Actually exist landuse=forest and natural=wood, but neither is applicable to urban areas. In the cities do not exist forestal explotations or woodlands.

**Comment by kocio-pl** [comment] 2018-02-20 20:17
Hi, thanks for your report. I will close this ticket, because it's a duplicate of #2548, but you can help discuss and decide there.

**Closed by kocio-pl** 2018-02-20 20:17 UTC
