### ISSUE TITLE
Use local highway shields, finally distinguishing expressways and highways

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3220] opened 2018-05-06 23:44 UTC
In the US
https://www.quora.com/What-is-the-difference-between-a-US-highway-and-an-interstate-highway
> Numbering of the two systems is "opposite" in order to reduce the
number of times the same number is used twice in the same location.  For
instance, US highway numbers increase from north to south, and from east
to west.  Interstate highway numbers increase from south to north, and
from west to east. 

However in other countries the confusion is enormous.
Please use local highway shields, like Google, etc. **all** do.

https://www.openstreetmap.org/#map=15/24.9094/121.1682
https://maps.google.com/maps?q=24.909023,121.164398

https://www.openstreetmap.org/#map=15/22.7534/120.4925
https://maps.google.com/maps?q=22.7534,120.4925

At least start with the list on
https://wiki.openstreetmap.org/wiki/Custom_Highway_Shields

**Comment by kocio-pl** [comment] 2018-05-06 23:57
This is a duplicate of #508, please discuss it there. However it seems that this is a complex technical problem, so serious coding is needed to solve it.

**Closed by kocio-pl** 2018-05-06 23:57 UTC
Labels: duplicate, roads
