### ISSUE TITLE
railway=station vs public_transport=station. Differences in tags required for rendering as polygons.

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#3303] opened 2018-07-14 13:27 UTC
Hi
To render both infill & name when mapped as a closed polygon, `railway=station` requires an `area=yes` tag:
https://www.openstreetmap.org/way/95350053 (with)
https://www.openstreetmap.org/way/115407400 (without)

Similar for `public_transport=station` doesn't:
https://www.openstreetmap.org/way/431107831

Is there a reason for this?
If `area=yes` is required to determine if `railway=station` is a linear way or a closed poly, doesn't `public_transport=station` require the same.

Or even better, if `area` isn't really required, then remove it. `Area` tags are unnecessarily added to many entities by mappers who get confused.

**Comment by matkoniecz** [comment] 2018-07-15 13:33
I can confirm that problem exists. I removed unneded `area=yes` from 

>  https://www.openstreetmap.org/way/95350053 (with)

and it broke rendering

**Comment by HolgerJeromin** [comment] 2018-07-20 06:31
This is probably the cause:

This line includes the entry into polygon_keys 
https://github.com/gravitystorm/openstreetmap-carto/blob/654ea38dd87ad4dbbaf2b547781bfe14df375981/openstreetmap-carto.lua#L26

This one defines railway stuff as linear.
https://github.com/gravitystorm/openstreetmap-carto/blob/654ea38dd87ad4dbbaf2b547781bfe14df375981/openstreetmap-carto.style#L40

cc @pnorman

**Comment by DaveF63** [comment] 2018-12-22 00:35
To check, as this hasn't been pushed through in the last couple of updates, is this more than a one line of code problem? If it is, I need to re-add the area tags from my previous edits.

**Comment by HolgerJeromin** [comment] 2018-12-22 07:59
> To check, as this hasn't been pushed through in the last couple of updates, is this more than a one line of code problem? 

If I am right this needs a full database reload to fix (after the code change) which needs a few days to perform.

**Comment by DaveF63** [comment] 2018-12-23 17:16
Are these reloads performed on a regular or ad hoc basis?

**Comment by HolgerJeromin** [comment] 2018-12-24 07:05
They are done every few years when needed. For example when new hardware is installed.

**Comment by Adamant36** [comment] 2018-12-24 07:13
They just upgraded the servers recently didn't they? I thought I saw something about them finishing it up a few months back.

**Comment by DaveF63** [comment] 2018-12-24 12:04
So, am I reading correctly? 
This bug can be **only** fixed "every few years" after a " full database reload"?

**Comment by mboeringa** [comment] 2018-12-24 17:03
> `Area` tags are unnecessarily added to many entities **by mappers who get confused**.

I don't really agree "area" tags are superfluous, in fact.

They are _**the one and only real possibility**_ (besides defining a multipolygon) for a mapper to tell **unambiguously** to any data consumer to tread a certain closed way feature as a polygon and not a line element.

The fact that styles like this make their own "best guess" assumptions through settings in configuration files, does not absolve mappers from using an area tag when there is ambiguity caused by a closed way element with tags that are generally interpreted or accepted in the community as meaning line elements.

**Comment by pnorman** [comment] 2018-12-24 18:01
> This one defines railway stuff as linear.

As the top of the file notes, 
https://github.com/gravitystorm/openstreetmap-carto/blob/654ea38dd87ad4dbbaf2b547781bfe14df375981/openstreetmap-carto.style#L4-L6

The problem is railway is **not** a polygon key, as defined in
https://github.com/gravitystorm/openstreetmap-carto/blob/654ea38dd87ad4dbbaf2b547781bfe14df375981/openstreetmap-carto.lua#L5

**Comment by mboeringa** [comment] 2018-12-24 18:02
> This bug can be **_only_** fixed "every few years" after a " full database reload"?

Yes and no, it can be fixed by changing the configuration files, but that won't change retrospectively any existing already imported features. It will only change any feature being updated or added as new feature.

To change the _existing_ features, you need a database reload.

**Comment by matkoniecz** [comment] 2019-06-23 20:55
Note that #3787 PR applied fix for this to `schema_changes` branch.

This issue remains open as for now `schema_changes` branch is not merged into `master` branch.

**Comment by Jez-C** [comment] 2019-10-24 05:54
Worth noting this problem also occurs on the Cycle and Transport layers, but I don't know how to report those.

**Comment by jeisenbe** [comment] 2019-10-24 12:45
The Cycle map (opencyclemap.org) and the Transport map are both provided by @gravitystorm - you can email support “ат” thunderforest (dot) com to report bugs with the stylesheets.

**Comment by jeisenbe** [comment] 2020-03-16 12:31
Fixed by #3787 which will be available in the next release (v5.0.0)

**Closed by jeisenbe** 2020-03-16 12:31 UTC
Labels: bug, code
