### ISSUE TITLE
Canada's CN Tower not on top

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4668] opened 2022-08-29 22:54 UTC
Can't figure out why Canada's CN Tower in Toronto isn't on the very top layer here:
![20220829_185055.jpg](https://user-images.githubusercontent.com/1230959/187312794-0b756ef8-e069-46e9-8d49-2dcb88e31272.jpg)

**Comment by HolgerJeromin** [comment] 2022-08-30 10:34
duplicate of #688

**Closed** 2022-08-30 11:13 UTC
