### ISSUE TITLE
zoom level 4 in N america

### ISSUE THREAD

**Issue by brandoncote** [gravitystorm/openstreetmap-carto#3523] opened 2018-11-23 18:57 UTC

**Comment by kocio-pl** [comment] 2018-11-23 19:02
Hi,

Currently we're using the settings summarized in this file:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/USECASES.md

**Comment by matkoniecz** [comment] 2018-12-08 13:30
Do you consider "empty, land mass" as problem by itself and want to fill it? Or is there some purposes for showing this data earlier?

**Comment by manfredbrandl** [comment] 2019-01-16 22:44
I see that cities dont get the priority from their number of inhabitant, but from Place for the Name at their location on z4:
![3bc85b40-3989-4c0c-9fcb-f5cb7394a5e7](https://user-images.githubusercontent.com/5360273/51283398-5a52e580-19e8-11e9-905a-f9eefa2d866d.jpeg)
Berlin, Vienna and Hamburg have more inhabitants than Munich.

**Comment by jeisenbe** [comment] 2019-01-16 22:52
The country labels are rendered first, and then the names of cities only
appear if there is enough space.

Berlin is probably colliding with the last 4 letters in “Deutschland”,
Warsaw is at the same location as the label for Polska, etc.

**Comment by kocio-pl** [comment] 2019-01-16 22:55
There are some obvious things like labels priority, but this all is more complex - this is the code that count categories and score:

https://github.com/gravitystorm/openstreetmap-carto/blob/6684f0aeba571c01fb774530f3acc8f90b6aaaff/project.mml#L1332-L1375

and then placenames are rendered according to that:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/placenames.mss

**Comment by jeisenbe** [comment] 2019-09-05 12:19
We could try rendering the 2-letter `ref` code for `boundary=administrative` + `admin_level=2` features, but there are 774 states and provinces with a `ref` world-wide. While this would work at z4 for Canadian provinces and larger States in the USA, there might be problems in some countries. 

Perhaps filtering for >1000 way_pixels will avoid rendering the `ref` for too small of provinces, but this will leave off only some labels in countries that have varying-sized provinces, as happens with the name labels currently. 

Anyone want to give it a try?

**Comment by pnorman** [comment] 2019-09-05 17:51
We're going to end up omitting labels regardless, the only way to get all the US states labeled is with lines.

**Comment by brandoncote** [comment] 2019-09-05 17:56
The point isn't to try to put all state labels on it; it's to make use of the empty spaces.

**Comment by pnorman** [comment] 2022-07-08 01:47
Duplicate of #2280

**Closed by pnorman** 2022-07-08 01:47 UTC
Labels: duplicate, admin, text
