### ISSUE TITLE
Render wetland=mangrove with dark green fill

### ISSUE THREAD

**Issue by geaquinto** [gravitystorm/openstreetmap-carto#2025] opened 2016-01-20 12:48 UTC
Mangroves are as dense as forests and `wetland=mangrove` should be rendered with a green fill, the same shade as `natural=wood`. There is already a green fill for `wetland=swamp`. I noticed it when I got myself adding `natural=wood` to mangroves, which would be as redundant as adding it to swamps. A rookie tagging-for-the-renderer mistake. :)

My suggestion is to keep rendering `natural=wetland` as a transparent layer with cyan dashes, but render every heavily used `wetland=*` with an icon and colour combination representative to each type of wetland. 

For instance, while `wetland=swamp` and `wetland=marsh` have this pattern (unique icons and colours identical to `natural=wood` and `natural=grassland`, respectively), `wetland=mangrove` and `wetland=reedbed` have only the unique icon. A similar issue was reported in #2013 for reedbeds, and in my opinion they should be coloured like `natural=scrub` or an already existing colour for `natural=*` with medium density.

**Comment by imagico** [comment] 2016-01-20 13:16
As explained in #2013:

> Currently this style is trying to use pattern only rendering without a fill color for wetlands where the ground is sometimes/partly water covered.

A solid color fill would obscure the land-water boundary and it would render differently relative to natural=water and ocean.

During development of the current wetland styling (#1497) a semitransparent background color like for wetland=tidalflat was considered but dismissed since it was not possible to get desirable colors both with and without water background this way.  With water polygons (#1982) this can be reconsidered.

**Comment by geaquinto** [comment] 2016-01-20 13:31
Why not "flood" with blue when there is a water boundary? It is just how it works in the other wetland types such as in `wetland=marsh`:

![untitled](https://cloud.githubusercontent.com/assets/16483981/12450120/e6d906b6-bf68-11e5-9a75-91c0388bf1fb.jpg)

Later we can consider rendering different solid/transparent colours when there is coastlines/ponds with further discussion, but a blue wetland when flooded could be rendered now just like the other coloured wetland types.

**Comment by imagico** [comment] 2016-01-20 13:38
This is an option when #1982 is resolved but right now this is not possible for coastal wetlands.

**Comment by matkoniecz** [comment] 2016-03-04 11:02
> I noticed it when I got myself adding natural=wood to mangroves, which would be as redundant as adding it to swamp

I am not fully convinced that adding natural=wood to mangroves is pointless. Maybe it is redundant but natural=wood/landuse=forest should be applied to all forested areas, without need to process wetland=mangrove (or other theoretic combinations as man_made=planted_forest).

Also, [enwiki](https://en.wikipedia.org/wiki/Mangrove) defines mangrove as "shrubs or small trees that grow in coastal saline or brackish water." - so maybe not every magrove is a forest?

See for example image from http://www.wlf.louisiana.gov/sites/default/files/pdf/document/32868-coastal-mangrove-marsh-shrubland/coastal_mangrove-marsh_shrubland.pdf that AFAIK is mangrove and is not a forest.

![capture](https://cloud.githubusercontent.com/assets/899988/13525403/01e0d2e4-e201-11e5-979c-b40c731cdc44.PNG)

**Comment by imagico** [comment] 2016-03-04 12:56
I guess this depends on your view of the tagging system - which is somewhat off-topic here.

Yes, there are different kinds of mangrove wetlands but i would consider this the domain of more specific tags (like `mangrove=*`).  For me mangroves are primarily a certain type of tidal wetland and not really a type of wood or scrubland.  This likely also complies with the perspective of mappers on the ground - for human use and movement a mangrove wetland is fundamentally different from a forest.

**Comment by jeisenbe** [comment] 2019-05-28 01:59
Since #3738 was merged over a month ago, we can now consider using a color fill for mangroves.

I've been thinking of using `@scrub` - `#c8d7ab` like @geaquinto suggested above, because many types of mangroves are shrubs in size (1 to 3 meters tall). 

Some mangroves are tall enough to be clearly defined as trees, but `@forest` color (`#add19e; `) is already used for `wetland=swamp`, and I think this is a distinct type of landcover. 

It's quite common for tropical swamplands and mangroves to be rendered with a different color (as well as a different pattern) on maps here in Indonesia.

However, if we end up using `@scrub` `#c8d7ab` for reedbeds or decide against this color, we could also consider using a blue-green shade. The old scrub color (`#b5e3b5`), now only used only for golf course, could be an option - though I had also considered using this for pitches instead of the current dark green-blue pitch color.

Or we could use `@orchard:` `#aedfa3` - which is a blueish green and also represents small trees or shrubs (vineyards and berry plants), but it might be a little odd to combine these with mangroves, which have quite different human landuse.

**Comment by Adamant36** [comment] 2019-05-28 04:04
Going with the scrub color makes the most sense to me.

**Comment by sommerluk** [comment] 2019-05-30 08:59
> so maybe not every magrove is a forest?

Well, I would say a mangrove is a particular ecosystem independently of the size of the plants. The same mangrove species can develop both as a low scrub-like form (dwarf form) and also as a high tree form. This is true for example for the very common and dominant Rhizophora species (see also [this publication](https://www.researchgate.net/publication/242145680_Rhizophora_mangle_R_samoensis_R_racemosa_R_X_harrisonii_Atlantic-East_Pacific_red_mangrove) at page 4) and also Avicennia germinans, but I suppose also for other species. Depending on environment conditions, the plant develops either in the tree form or in the dwarf form. Even at the same place, you can observe both forms depending if you are on the landward or on the seaward side of the mangrove.

> for human use and movement a mangrove wetland is fundamentally different from a forest.

Indeed I can confirm that the human perception is fundamentally different. Typically would would visit a mangrove coming by boat from the seaward side during high tide. From the landward side the access might be more difficult. The center of the mangrove is anyway not well accessible. When “walking” in a mangrove you might be slower than 1 km per hour…

**Comment by jeisenbe** [comment] 2019-06-07 01:45
Initial tests to see if the fill colors will work with the current pattern file:

### Test 1: mangrove with scrub color fill `#c8d7ab` - also shows reedbed in `#b5e3b5` (old scrub / current golf color) and saltmarsh with @grass
- Scrub is the most similar type of vegetation to many areas of mangroves (woody plants, shorter and bushier than wood/forest)

![z16-mangrove-reedbed-saltmarsh-after-test1](https://user-images.githubusercontent.com/42757252/59075538-19625b80-890c-11e9-9a8a-541331a85237.png)

![z17-wetlands-fill-test1](https://user-images.githubusercontent.com/42757252/59075537-18c9c500-890c-11e9-8429-4ce3e5e7cb36.png)

### Test 2: mangrove `#b5e3b5` (golf color) and reedbed `#c8d7ab` (scrub color)
- Not many golf courses next to mangroves, so it's unlikely to cause confusion

![z16-mangrove-b5e3b5-reedbed-scrub-test2](https://user-images.githubusercontent.com/42757252/59075541-1e270f80-890c-11e9-8dfd-dd68c2d84a4a.png)

![z17-wetlands-test2-mangrove-golf-reedbed-scrub](https://user-images.githubusercontent.com/42757252/59075542-1ebfa600-890c-11e9-856c-a858b176fb13.png)

### Test 3:  mangrove `#c9e1bf` "allotments"
- This could work because allotments are basically unknown in the tropics, so there is almost no chance of seeing mangroves near allotments. 

![z16-mangroves-allotments-reedbed-scrub-test3](https://user-images.githubusercontent.com/42757252/59075576-4f074480-890c-11e9-967f-b814e1d8fc9c.png)

![z17-mangrove-allotments-reedbed-scrub-test3](https://user-images.githubusercontent.com/42757252/59075580-52023500-890c-11e9-898a-1683d8dac646.png)

### Test 4?: mangrove @forest `#add19e` 
- I don't like this option, because it makes it too hard to distinguish mangroves from tropical swamps and woodlands. 

![z14-potowai-mangroves-forest-fill-after](https://user-images.githubusercontent.com/42757252/59076466-30f01300-8911-11e9-8916-bd6ebdcaa080.png)

**Comment by jeisenbe** [comment] 2019-06-07 07:10
## Test images from the southwestern coast of New Guinea.

- The options that provide the best visibility for the tidal channels of sea water within the mangroves are 1. `@scrub` and 4. `forest`. 

- The bluer colors like 2. `@golf_course` and 3. `allotments` don't work as well with the current pattern, and the golf color makes it hard to distinguish the channels. 

- While 3. `allotments` `#c9e1bf` works with darker-colored rivers (as planned), it would not work well with lighter-colored seas or the current water color

- I made a new option number **5. mangrove with `@orchard` fill `3 aedfa3`** - this works fairly well with the water colors (better than golf), but is still a little too blue compared to the scrub or forest colors and so has less contrast with the current water color.   

## Test 1: mangrove with `@scrub` fill `#c8d7ab` 
z13 Potowai - current water color - scrub fill
![z13-potowai-mangroves-scrub-fill-after](https://user-images.githubusercontent.com/42757252/59086525-f56b3e00-893c-11e9-86c5-f02c9025f289.png)

z15 mangroves next to scrub and beach  - scrub fill
![z15-mangroves-scrub-fill-beach-scrub-residential-after](https://user-images.githubusercontent.com/42757252/59086619-36fbe900-893d-11e9-9b5b-7ea817d7fa43.png)

z15 mangroves by tidalflat - scrub fill
![z15-mangroves-scrub-fill-tidalflat-beach-aftrer](https://user-images.githubusercontent.com/42757252/59086624-395e4300-893d-11e9-8fd1-d823257433fc.png)

z13 Potowai - tested with **darker rivers and lighter sea** (3 water color system) - scrub fill
![z13-potowai-mangroves-scrub-ocean-river-color](https://user-images.githubusercontent.com/42757252/59086690-7296b300-893d-11e9-9b0a-b22b3852cb8b.png)

z13 Amamapare - **lighter sea** - scrub fill
![z13-amamapare-mangroves-scrub-ocean-color](https://user-images.githubusercontent.com/42757252/59086682-6f032c00-893d-11e9-9fa2-5aa2f753428a.png)

## Test 2: mangrove with `@golf_course` fill `#b5e3b5`

z13 Potowai - current water color - golf fill
![z13-potowai-mangroves-golf-fill](https://user-images.githubusercontent.com/42757252/59086724-8a6e3700-893d-11e9-8d45-07eff9504f42.png)

z13 Potowai -  **darker rivers and lighter sea** - golf fill
![z13-potowai-mangroves-golf-ocean-river-color](https://user-images.githubusercontent.com/42757252/59086761-a70a6f00-893d-11e9-8db3-05dede3af3f2.png)

z13 Amamapare - **lighter sea** - golf fill
![z13-amamapare-mangroves-golf-ocean-color](https://user-images.githubusercontent.com/42757252/59086803-c7d2c480-893d-11e9-829d-962b2e719149.png)

## Test 3:  mangrove with `@allotments` fill `#c9e1bf`

z13 Potowai - current water color - allotments fill
![z13-potowai-mangroves-allotments-fill-after](https://user-images.githubusercontent.com/42757252/59086838-df11b200-893d-11e9-93f9-80cb2d7da3af.png)

z13 Potowai -  **darker rivers and lighter sea** - allotments fill
![z13-potowai-mangroves-allotments-river-ocean-color](https://user-images.githubusercontent.com/42757252/59086842-e5079300-893d-11e9-827f-4c327dd42579.png)

z13 Amamapare - **lighter sea** - allotments fill
![z13-amamapare-mangroves-allotments-ocean-color](https://user-images.githubusercontent.com/42757252/59086867-036d8e80-893e-11e9-92c3-a2e19981ac16.png)

## Test 4: mangrove with `@forest` fill `#add19e` 

z13 Potowai - current water color - forest fill
![z13-potowai-mangroves-forest-fill](https://user-images.githubusercontent.com/42757252/59086937-462f6680-893e-11e9-88fc-168cc2157d42.png)

z14 - mangroves next to swamp (current water color) - forest fill
![z14-potowai-mangroves-forest-after](https://user-images.githubusercontent.com/42757252/59087002-6e1eca00-893e-11e9-8025-8409117eddf9.png)

z13 Potowai -  **darker rivers and lighter sea** - forest fill
![z13-potowai-mangroves-forest-ocean-river-color](https://user-images.githubusercontent.com/42757252/59086897-1ed89980-893e-11e9-83cf-f01e4f33fc4c.png)

z13 Amamapare - **lighter sea** - forest fill
![z13-amamapare-mangroves-forest-ocean-color](https://user-images.githubusercontent.com/42757252/59086921-3c0d6800-893e-11e9-9a7e-022eebb50ba1.png)

## Test 5. mangrove with `@orchard` fill `3 aedfa3`

z13 Potowai - current water color - orchard fill
![z13-potowai-mangroves-orchard-fill](https://user-images.githubusercontent.com/42757252/59087060-93abd380-893e-11e9-99dc-13fdeb22a1a5.png)

z14 mangroves next to swamp - orchard fill
![z14-mangroves-orchard-fill-scrub-swamp](https://user-images.githubusercontent.com/42757252/59087074-9efeff00-893e-11e9-9076-ecb0fad0dbe8.png)

z13 Potowai -  **darker rivers and lighter sea** - orchard fill
![z13-potowai-mangroves-orchard-river-ocean-color](https://user-images.githubusercontent.com/42757252/59087033-7e36a980-893e-11e9-872e-f3963c1f4c8e.png)

z13 Amamapare - **lighter sea**
![z13-amamapare-mangroves-orchard-fill-ocean-river](https://user-images.githubusercontent.com/42757252/59087038-842c8a80-893e-11e9-8778-055c55850914.png)

**Comment by imagico** [comment] 2019-06-08 20:32
Quick comment on all of the background colors for wetlands.  IMO without introducing new colors or patterns the only choices that would semantically sense in the current system of colors in this style are:

* mangrove:  either wood or scrub
* reedbed: grass
* saltmarsh: grass

The choice for mangrove is a tricky one - there are both cases where wood color would be more appropriate and where scrub color would be.  In terms of mapping incentives choosing scrub could lead mappers to tag as swamp if they prefer the wood color and with wood color mappers could choose a generic wetland tag when they feel wood color is wrong.  If i had to pick i'd probably choose scrub color but that's not really a strong preference.

For saltmarsh grass color as background would have a bit of a disadvantage by rendering exactly like marsh and wet_meadow.  But that is not a good reason to select a color that indicates similarity to something where there is definitely no similarity with.  Some sort of fine grain pattern (representing salt) with grass as base color could be worth trying.

**Comment by jeisenbe** [comment] 2019-06-09 03:40
> - mangrove: either wood or scrub

I agree that these are the sensible choices, among the existing options. 

I considered trying to find something slightly darker and bluer than scrub, but sufficiently distinct from both forest and orchard, but this is quite difficult. I think scrub would be the best choice, so that the boundary can be clearly seen between mangroves and woods + swamps.

> - reedbed: grass

I hadn't wanted to use the grass color for reedbeds, because I was thinking they were more like a thicket of shurbs. But wikipedia suggests that almost all the plants commonly called reeds are closely related to grasses and sedges, and I suppose tall-grass prairies have the same fill color and are also similar in height. I'll try testing this option at issue #2013

> - saltmarsh: grass
>  Some sort of fine grain pattern (representing salt) with grass as base color

I agree that this is the best option. I had been wanting to avoid changing the pattern, but if we can add a white or off-white dot pattern to the color fill (rendered first), this would be easy.

**Closed** 2019-08-30 13:24 UTC
Labels: good first issue, landcover
