### ISSUE TITLE
Add rendering for public_transport=platform

### ISSUE THREAD

**Issue by AndiG88** [gravitystorm/openstreetmap-carto#435] opened 2014-03-24 15:08 UTC
**Edit: Okay maybe rather use it on public_transport=platform**

Use the same icon as highway=bus_stop

(if you want to do more use different ones depending on bus/tram=yes/no)

It would be great if you could support the "new" public transport schema, I think one of the main reason people don't use it, is because it does not show up on the map.

http://wiki.openstreetmap.org/wiki/Key:public_transport
http://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport

**Comment by kocio-pl** [comment] 2015-03-17 05:23
I think we should drop rendering public_transport=stop_position, because it's meant just for routing (and it's very helpful, because we can make real time semi-automatic updates of routes here in Warsaw!). If we want to see something people really use, we have public_transport=platform tag (or other kind of platforms etc).

**Comment by AnBuKu** [comment] 2015-03-17 05:36
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1



Am 17.03.2015 um 06:23 schrieb kocio-pl:
> I think we should drop rendering public_transport=stop_position,
> because it's meant just for routing (and it's very helpful, because
> we can make real time semi-automatic updates of routes here in
> Warsaw!).


Fully agree. Same here in Bern with BERNMOBIL using OSM for their mobile
app *


> If we want to see something people really use, we have
> public_transport=platform tag (or other kind of platforms etc).


And yes, rendering of public_transport=platform as a replacement of
public_transport=stop_position would be very nice and helpful for
browser users of osm.org

cheeers, Andreas

* Link (Sorry, German only)
http://www.bernmobil.ch/Seiten/fahrplan/oevbern/faqoevbern/?oid=2211&lang=de#4

> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/gravitystorm/openstreetmap-carto/issues/435#issuecomment-82115282>.
>
> 
- -- 

Andreas Bürki

abuerki@anidor.com
S/MIME certificate - SHA1 fingerprint:
ED:A5:F3:60:70:8B:4C:16:44:18:96:AE:67:B9:CA:77:AE:DA:83:11
GnuPG - GPG fingerprint:
5DA7 5F48 25BD D2D7 E488 05DF 5A99 A321 7E42 0227
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJVB71DAAoJEFqZoyF+QgInebsH/ArTTG319IZsozn4Cpcox1nb
EeVBt7y6XjBGeRmpDjcaUGjy2qDwisJr2T2ODSVcLwlgTDintDyLMKTxwYBsU3aU
kfjVUhV1DcpkY1/G236X1nh57cjQSl+YkrFXVNHt6nEizGFFvsnFNWIYrhFZ91xx
wL67CT6pplNklXmY4Yj1J1lcemtKRXggBHD8SrtWa696IM159kOEBKxvTP1qhDp9
rC/yqmjCN3/2EfYK5PMSPRxQLIZfSrHnvLxgW6G8p3j82ltAJGGteig68BERzfkl
PH+LutlEdEzTrXduO4/HZKdpmBtyJRHwYGheQeO+aTdAAbGgpCdJVwR6bfE98OY=
=W3rL
-----END PGP SIGNATURE-----

**Comment by math1985** [comment] 2015-04-28 11:48
As far as I can see, this was tagged incorrectly as 'Needs upgrade to osm2pgsql'.

**Comment by matkoniecz** [comment] 2015-04-28 12:34
@math1985 

public_transport tag is available in the database, but bus tag and others tags specifying type of stop_position are not. So currently it is impossible to check whatever element is a bus/tram/etc stop. The only available information is that it is some sort of stop position.

**Comment by HolgerJeromin** [comment] 2015-04-28 12:35
Don't we need bus= (and other keys) in the database?

**Comment by math1985** [comment] 2015-04-28 13:39
Re-added milestone.

**Comment by d1g** [comment] 2016-03-21 03:13
> @AndiG88 Yes there has. @RobJN has pointed out that there's been clear agreement on how to use highway=bus_stop for almost 6 years. If you keep refusing to believe this, it inclines me to disregard the rest of this discussion.

and
> For what it's worth, I'm :-1: on rendering public_transport=platform + bus=yes, regardless of the schema change issues. The mapper feedback loop is important, and I don't think encouraging what is a non-standard less common tag is a good idea, 

They kept only for that "mapper feedback loop". And data consumers use public_transport=* because they can get meaningful data (4 separate tags), not randomly placed highway=bus_stop or highway=platform which pretend to cover 3-4 objects at once.

If all software functions, nobody cares about tagging.

And no, this isn't "a non-standard tag" but one of 4 ways to mark a PT http://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport#Stop (s)

Which was approved: 83 approve the proposal, 6 oppose the proposal.

If you want 83 people to respect your opinion, don't neglect fact that this is hugely supported tag/proposal within OSM community.

And if @AndiG88 and @gravitystorm have a short memory on **approved tags** (not random tags like highway=platform or highway=bus_stop):

a highway=* tag reserved for "**highway=* should be changed to importance for the road grid (hierarchical position in the interconnecting network) instead of physical attributes.** " (https://wiki.openstreetmap.org/wiki/Proposed_features/Highway_key_voting_importance)

**Comment by d1g** [comment] 2016-03-21 03:22
Please rename issue to public_transport=platform, [per author request](https://github.com/gravitystorm/openstreetmap-carto/issues/435#issue-30042977):

> Edit: Okay maybe rather use it on public_transport=platform

**Comment by matkoniecz** [comment] 2016-03-21 06:10
> per author request

Creator of issue may edit title of the issue.

**Comment by matkoniecz** [comment] 2019-05-10 16:32
Can anyone supply link with documentation  why `public_transport=platform bus=yes` tag duplication of `highway=bus_stop` is a good idea?

Neither https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform nor https://wiki.openstreetmap.org/w/index.php?oldid=625726 nor https://wiki.openstreetmap.org/wiki/Key:public_transport is explaining this.

I assume that there is some reason for that (Ptv2 is quite widely used).

Note that it makes no sense to render both `public_transport=platform bus=yes` and `highway=bus_stop` as we should discourage fragmenting of tagging. I plan to add " and stop rendering highway=bus_stop" to the title.

**Comment by RobJN** [comment] 2019-05-10 18:04
>Note that it makes no sense to render both public_transport=platform bus=yes and highway=bus_stop as we should discourage fragmenting of tagging. 

> I plan to add " and stop rendering highway=bus_stop" to the title.

The problem is it is already fragmented and after many years it continues to be so. I am not fully up to speed with public transport mapping (I no longer do any as I find it too complicated and don't have the time to read it all), but if mappers who have previously spent many hours using PTv2 have doubts then it seems far from clear cut that this is the way to go.

https://www.openstreetmap.org/user/Polyglot/diary/44333
https://www.openstreetmap.org/user/Polyglot/diary/44440

There is also the Ptv3 proposal from @Zverik :
https://wiki.openstreetmap.org/wiki/Proposed_features/Refined_Public_Transport

p.s. since my post 1 April 2014 the number of highway=bus_stop tags has increased by 1 million. It certainly doesn't feel like something we should stop rendering.

**Comment by A67-A67** [comment] 2019-05-27 11:35
iD now has a new validation rule that adds a highway=footway to a public_transport=platform way. While this is not totally wrong, the public_transport tag already tells us that its primary function is a platform, it makes non-compatible renderers like osm-carto render a platform as a footway.

It would be better when osm-carto knows that a way like [this one](https://www.openstreetmap.org/way/225182662), is a platform and doesn't need an extra highway=platform for compatibility.

**Comment by jeisenbe** [comment] 2019-07-29 14:30
I've just looked into this issue, and the comment above is correct: https://github.com/gravitystorm/openstreetmap-carto/issues/435#issuecomment-46757866

It is not at all standard to use `bus=yes` with `public_transport=platform` - this combination is not suggested at the page Tag:public_transport=platform nor was it mentioned in the approved proposal. The tag `bus=yes` was designed for use with `public_transport=stop_position`.

Some mappers are using the tag in this way. Taginfo shows that only 59% of `public_transport=platform` have `bus=yes` (and <1% are trollybus=yes), while 75% have  `highway=bus_stop`. For rail: 5% have `railway=platform`, compared to only 2% with `train=yes` and 1.5% with  `tram=yes`. 

There's also 6% of public_transport=platform combined with `highway=platform.` Source: https://taginfo.openstreetmap.org/tags/public_transport=platform#combinations

So it appears that the best way to specify a bus stop at the side of a road, as opposed to "any kind of place to wait for a public transportation vehicle", is to use `highway=bus_stop` in addition to `public_transport=platform`. 

The situation is the same for `railway=platform` and other modes, because again, `public_transport=platform` does not specify bus vs train vs tram etc.

Since this is the case, I believe @pnorman is correct: this issue should be closed, and we should continue to rely on the current tags to render bus stops, train platforms and the rest. 

This may even have been the original intention of the public_transport proposal, since there was no other way to specify the mode or vehicle at a public_transport=platform other than using the pre-existing tags?

**Comment by A67-A67** [comment] 2019-07-29 20:10
Actually there are two issues here, that can be solved at once or separately: platform as a node and platform as a way. The reaction above is mostly about the former. The latter is however becoming the biggest issue.

**public_transport=platform as a node**
This combination `public_transport=platform` + `bus=yes` should be rendered as a bus stop symbol. Now the tag `highway=bus_stop `from the old scheme has to be added for compatibility with maps like osm-carto. Note that people have to add `highway=bus_stop`  to get the bus stop on osm.org, even though `public_transport=platform` + `bus=yes` should be enough. 

In my opinion at least both tagging schemes should be rendered, so the compatibility tag `highway=bus_stop` is not necessary anymore.

**public_transport=platform as a way**
`public_transport=platform` on a way, both a normal way and an area, replaces  `highway=platform` and `railway=platform`. Rendering can be done easily by just rendering `public_transport=platform` ways as the dark-gray line/area which is now used for `highway=platform` and `railway=platform`.

Not rendering this is becoming more and more an issue. The iD editor is now adding `highway=footway` to all platform ways. So osm-carto renders these now as a footway, instead of a platform. In the combination `railway=platform` + `highway=footway` + `area=yes` the highway-tag even seems to overrule the railway-tag, so the platform looks like a pedestrian area...

The latter issue could be easily solved, even without solving the former issue. In this case `public_transport=platform` should overrule highway-tags and railway-tags like `highway=footway`  and render as the dark-gray platform color.

**Comment by matkoniecz** [comment] 2019-07-29 20:54
> The iD editor is now adding highway=footway to all platform ways. So osm-carto renders these now as a footway, instead of a platform.

Are you sure? Afaik this iD bug/misfeature was fixed.

> The latter issue could be easily solved, even without solving the former issue. In this case public_transport=platform should overrule highway-tags and railway-tags like highway=footway and render as the dark-gray platform color.

Incorrect data can be shown as incorrect. This style is intended as feedback to mappers so this is OK.

> even though public_transport=platform + bus=yes should be enough.

It seems disputable to me, see comment about yours. Neither PTv2 proposal nor usage supports this. And still nobody answered https://github.com/gravitystorm/openstreetmap-carto/issues/435#issuecomment-491350865 question 

> Can anyone supply link with documentation why public_transport=platform bus=yes tag duplication of highway=bus_stop is a good idea?

**Comment by kocio-pl** [comment] 2019-07-30 00:08
> Can anyone supply link with documentation why public_transport=platform bus=yes tag duplication of highway=bus_stop is a good idea?

I would say that this is how we could get out of ambiguity of what a "bus stop" really means without unexpected dropping common tagging.

**Comment by matkoniecz** [comment] 2019-07-30 06:04
Closing per https://wiki.openstreetmap.org/w/index.php?oldid=625726#What_this_Proposal_does_not_cover

> This proposal does not replace, deprecate or obsolete the already existing and well known tags.

ongoing dominance of standard and simple tagging (see https://github.com/gravitystorm/openstreetmap-carto/issues/435#issuecomment-516016068 ) and lack of documentation why significantly more complex and confusing tagging scheme would be wanted (see https://github.com/gravitystorm/openstreetmap-carto/issues/435#issuecomment-491350865 ).

**Closed by matkoniecz** 2019-07-30 06:04 UTC
Labels: enhancement, features, station

**Comment by gileri** [comment] 2019-11-09 10:05
>I am especially confused why this proposal was created and supported in the first place given that stated intention was to duplicate existing tagging without intention of replacing it.

Just above the section [you cited](https://wiki.openstreetmap.org/w/index.php?oldid=625726#What_this_Proposal_does_not_cover) you can find [why](https://wiki.openstreetmap.org/w/index.php?oldid=625726#Main_Problem_with_the_existing_Schema) that proposal was created. As to why this proposal did not call for replacement of PTv1, I can only guess that was in order to have a gradual deprecation later while keeping compatibility for the time being.

>ongoing dominance of standard and simple tagging

It is older, global transitions are not that quick. 1.5M `highway=bus_stop` vs 2.5M `public_transport=platform` platforms can be called dominance, but [this graph](https://imgur.com/a/d47V6PU) from [OSM tag history](https://taghistory.raifer.tech/) tells another story : PTv2 was introduced later, and even while the renders and tools did not pick it up for years, its usage is growing at a quicker rate than PTv1 (and slightly accelerating), showing a clear interest to map this way.

**Comment by matkoniecz** [comment] 2019-12-27 16:41
> Just above the section you cited you can find why that proposal was created.

Sorry. Not sure why I have not mentioned it. But note that mentioned problems are not really relevant to explaining why new proposal is desirable.

> Inconsistent handling of railway=tram_stop / railway=halt (node on the way) and highway=bus_stop (node beside the way).

This proposal failed to solve it - as old tags are not replaced anyway

> Missing tag for stop position causes extra preprocessing for routing software.

Not sure why this extra preprocessing step should be done manually, instead of automatically. It could be understood if that extra processing was impossible, but it is not such case

>  No separate tags for stop position and platform / pole.

Not sure why it is considered as a problem, tagging both is a pointless duplication.

> Insufficient possibility for line variants for bus lines.

This part maybe makes sense. It is hard to say as I never tagged or really maintained such info. But it is not relevant to other parts.

I still claim that documentation why significantly more complex and confusing tagging scheme would be wanted is missing.

I am still confused why this proposal was created and supported in the first place given that stated intention was to duplicate existing tagging without intention of replacing it.

I still think that simple tagging (highway=bus_stop type) is preferable over more complex that makes everything more complicated (simplest bus stop tagged three times in two different places). Enormous effort went into discussing and using it, without any clear analysis/documentation why additional complexity is worth negative effects.

I hope that bias here is not significant.

**Comment by matkoniecz** [comment] 2019-12-27 16:56
> It is older, global transitions are not that quick. 1.5M highway=bus_stop vs 2.5M public_transport=platform platforms can be called dominance, but this graph from OSM tag history tells another story : PTv2 was introduced later, and even while the renders and tools did not pick it up for years, its usage is growing at a quicker rate than PTv1 (and slightly accelerating), showing a clear interest to map this way.

Interpretation 1 - strict following proposal

> This proposal does not replace, deprecate or obsolete the already existing and well known tags. The usage of the proposed tags is recommended but not mandatory.

So rendering `highway=bus_stop` and not rendering `public_transport=platform` actually is following the proposal. Proposal, as written, is explicitly not deprecating `highway=bus_stop`.



> As to why this proposal did not call for replacement of PTv1, I can only guess that was in order to have a gradual deprecation later while keeping compatibility for the time being.

Maybe. But AFAIK there was never a clear support for such deprecation.

---

Interpretation 2 - `bus=yes` tag

`bus=yes` tag from what I see was in proposal missing for platforms from what I see in https://wiki.openstreetmap.org/w/index.php?title=Proposed_features/Public_Transport&oldid=625726#Platform

Note https://wiki.openstreetmap.org/w/index.php?title=Proposed_features/Public_Transport&oldid=625726#Compatibility_with_well_known_tags - `bus=yes` was supposed to be added only to `public_transport=stop_position`

Looking at it it has about 2 000 k uses for `highway=bus_stop` on start of 2018, and about 900k for `public_transport=platform`

It is now 2 500 k https://taginfo.openstreetmap.org/search?q=highway%3Dbus_stop vs 1 587 k for alternative https://taginfo.openstreetmap.org/tags/public_transport=platform

But only 989 k `public_transport=platform` has `bus=yes`! So only about 60% of `public_transport=platform` represents bus stops.

It is possible that `public_transport=platform` + `bus=yes` grows quicker than `highway=bus_stop`, bot sure how to check this, but linked data is not supporting this.

BTW, https://wiki.openstreetmap.org/w/index.php?title=Proposed_features/Public_Transport&oldid=625726#Compatibility_with_well_known_tags makes clear that to mark something as bus stop according to this proposal one must use `highway=bus_stop`
