### ISSUE TITLE
name of negative level object is rendered atop higher level buildings

### ISSUE THREAD

**Issue by malenki** [gravitystorm/openstreetmap-carto#2003] opened 2015-12-09 20:30 UTC
Although the subterranean stream gets nicely rendered below buildings and highways, it's name sometimes shows up on top of buildings, streets etc.:

![map-z19](https://cloud.githubusercontent.com/assets/188565/11697781/9f5e4e68-9ebb-11e5-97ed-8d4721ad3817.png)
![map_z18](https://cloud.githubusercontent.com/assets/188565/11697782/9f610c3e-9ebb-11e5-9540-1b9d84538c2e.png)  
[link to map](http://www.openstreetmap.org/#map=18/50.90654/13.33973)

**Comment by math1985** [comment] 2015-12-09 21:45
I think this is a duplicate with another issue, but I can't find it right now. Can anybody find it?

**Comment by matkoniecz** [comment] 2015-12-10 11:19
Duplicate of #478

**Closed by matkoniecz** 2015-12-10 11:19 UTC
