### ISSUE TITLE
Add sport pitch icon

### ISSUE THREAD

**Issue by finetjul** [gravitystorm/openstreetmap-carto#487] opened 2014-04-19 15:03 UTC
Until a set of icon is chosen (#277), I think a sport pitch icon should be used because it is currently hard to read the map without this icon.
The one from maki seems to be generic enough and should fit pretty well.
https://www.mapbox.com/maki/

**Comment by g4rpch** [comment] 2015-10-25 07:15
Any news about this improvement? read sport fields on the map is really difficult!
From the map I cannot understand with kind of sport is, I think is frustrating :(
![schermata 2015-10-25 alle 08 13 15](https://cloud.githubusercontent.com/assets/15292575/10714459/465c6910-7af0-11e5-9604-702df2d0923f.png)

**Comment by math1985** [comment] 2015-10-25 11:19
No, it seems nobody has had time to look at this yet.

**Comment by kocio-pl** [comment] 2016-09-24 18:53
There's also another approach considered:

https://github.com/gravitystorm/openstreetmap-carto/issues/1126

**Comment by HolgerJeromin** [comment] 2016-09-24 19:02
This is a duplicate of  #844 or the other way around.

**Comment by math1985** [comment] 2016-09-24 19:13
Thanks, closing as dupliate.

**Closed by math1985** 2016-09-24 19:13 UTC
Labels: amenity-points
