### ISSUE TITLE
Make railways lighter, minor highways less prominent at z8-10

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3538] opened 2018-11-29 19:35 UTC
Zoom levels 8, 9 and 10 looks like a unreadable colorful spagetti in some places at the moment:

Examples:
https://www.openstreetmap.org//#map=8/49.246/15.430
https://www.openstreetmap.org//#map=9/51.0811/5.8173
https://www.openstreetmap.org//#map=10/50.2498/19.2906
https://www.openstreetmap.org//#map=10/53.5550/-2.0627

Problems to solve:

- [x]  too prominent protected areas borders -> done! https://github.com/gravitystorm/openstreetmap-carto/pull/3574
- [x]  too thin country borders on z8-9 (related to https://github.com/gravitystorm/openstreetmap-carto/issues/3489 and https://github.com/gravitystorm/openstreetmap-carto/issues/3526) -> done! https://github.com/gravitystorm/openstreetmap-carto/pull/3563
- [ ] too prominent railways
- [ ] roads system width tuning up

I believe it could be cleaned similar as z13-14 was in https://github.com/gravitystorm/openstreetmap-carto/pull/3467.

What do you think about it? Do you see a problem there, too?

**Comment by kocio-pl** [comment] 2018-11-29 19:56
I would change the title to be more clear that it's about lines.

- country borders on z8-9 could be bolder, I agree 
- protected areas borders might be thinner, although there are only some places when borders of adjacent areas add up which I consider to be a problem:
https://www.openstreetmap.org/#map=8/47.063/-75.457

![screenshot_2018-11-29 openstreetmap](https://user-images.githubusercontent.com/5439713/49248050-1ea09400-f419-11e8-881f-3ea5211d83e9.png)

- I don't feel railways could be thinner, because some roads are grey already

**Comment by Adamant36** [comment] 2018-11-29 20:57
I dont think protected areas borders should be thicker or brighter where the they join/overlap. It makes the map look really scrued up. For instance, in northern California it looks horrible and inconsistant.

**Comment by kocio-pl** [comment] 2018-11-29 20:58
The question is how to fix it...

**Comment by vholten** [comment] 2018-11-29 21:06
Protected area borders have shading on the inside. So borders between adjacent areas become twice as thick (shading on both sides). That could be fixed by shading that is centered on the border instead of inside.

**Comment by kocio-pl** [comment] 2018-11-30 00:44
That's also what I was suspecting. Could you prepare a PR fixing that?

**Comment by Adamant36** [comment] 2018-11-30 05:51
Whats the reason for the borders being shaded in the first place? Is there a special reason why protected areas need to have places where they meet more visible compared to other landuse areas that just have a normal line where they meet?

**Comment by kocio-pl** [comment] 2018-11-30 05:58
These are typically so big, that once you zoom in, it might be hard to know which part is inside and outside the area. Shading gives you a slight hint when the border label is not visible:

![screenshot_2018-11-30 openstreetmap 2](https://user-images.githubusercontent.com/5439713/49271302-41f52e80-f46d-11e8-8adc-81c7b53bb7c9.png)

**Comment by matkoniecz** [comment] 2018-11-30 13:12
> where it creates a weird glowing border effect in only some places

Can you mark this places?

**Comment by matkoniecz** [comment] 2018-11-30 13:15
> too prominent railways

I tested making them narrower/lighter and it resulted in many people being completely unable to distinguish them from minor roads (I was still able to do that, a small minority was also able but others not).

I considered either keeping them in current state or outright removing them as I had no idea for styling other than "narrow black/gray line".

**Comment by matkoniecz** [comment] 2018-11-30 13:19
Looking at it again - it seems that railway tracks at z8 may be considered for removal or for making them lighter, gray roads are not present at z8.

**Comment by Adamant36** [comment] 2018-11-30 13:30
@matkoniecz, here's links to a couple of the places where it does it. 

https://www.openstreetmap.org/#map=13/39.4740/-122.7755
https://www.openstreetmap.org/#map=11/39.4932/-122.7214
https://www.openstreetmap.org/#map=12/39.9238/-122.9981
https://www.openstreetmap.org/#map=12/39.9317/-123.0146

I don't know if "glowing" is the right word, but there's definitely places where the borders are a lot darker green then others. There doesn't seem to be a difference between the darker and lighter places tagging or distance wise. It just looks bad and inconsistent.

**Comment by matkoniecz** [comment] 2018-11-30 14:08
I am pretty sure that it is caused by two green lines merging together - so it ends as a single strongly green line.

Merging may happen in tow ways

- partially transparent part os overlaid on each other and ends as strongly green
- two green lines are located close to each other are rendered as wider/stronger green line

A similar effect is visible for railway lines with one track (fainter) or multiple tracks (stronger) on low zoom levels.

**Comment by Adamant36** [comment] 2018-11-30 14:24
Hhhhmmm makes sense. Something should still be done to tone it down though.

**Comment by Adamant36** [comment] 2018-11-30 16:07
@matkoniecz, what about somewhere like this where its a single line but still darker? If its because of the weird nature reserve/national park co tagging, wouldn't it just prioritize one over the other, instead of rendering them both on top of each other since its the same way?

**Comment by kocio-pl** [comment] 2018-11-30 16:09
On z8-z9 it can be changed, since the area is rendered with green overlay. On z10+ I would leave it until we find something better.

**Comment by matkoniecz** [comment] 2018-11-30 16:40
@Adamant36 Linked location has two lines close to each other - zoom in (say at https://www.openstreetmap.org/#map=19/40.54189/-121.27477 ) to see names - there are at least two protected areas here sharing borders.

**Comment by Adamant36** [comment] 2018-11-30 17:50
Hhhhmmm weird. If you go to edit it looks like only one line and you can't separate it. So....Must be an optical illusion or something.

**Comment by matkoniecz** [comment] 2018-11-30 18:44
Note that https://www.openstreetmap.org/way/417600197 is a member of three relations:
- https://www.openstreetmap.org/relation/6207170
- https://www.openstreetmap.org/relation/6207158
- https://www.openstreetmap.org/relation/5394164

All three are rendered.

(and on top of that has `boundary=national_park` tag (I opened https://www.openstreetmap.org/note/1605307 as I suspected the last one is a tagging error)).

**Comment by vholten** [comment] 2018-12-01 17:35
Here are some tests with lighter railways on z8 and z9. The idea is to fade in railways while zooming in,
- z8: `#a0a0a0`
- z9: `#909090`
- z10 and higher: `#787878` (this is the original railway color)

z8 current:
![z8osm](https://user-images.githubusercontent.com/5209216/49330997-eb840f00-f596-11e8-8853-75b3e79901d0.png)

z8 with lighter railways:
![z8rail](https://user-images.githubusercontent.com/5209216/49331004-05bded00-f597-11e8-8d3e-8e2a0cacdea8.png)

z8 with lighter railways and thicker gray borders:
![z8railborders](https://user-images.githubusercontent.com/5209216/49331007-0a82a100-f597-11e8-9ef9-473a10206f65.png)

z9 current:
![z9osm](https://user-images.githubusercontent.com/5209216/49331009-0f475500-f597-11e8-895b-2ec340d6d76e.png)

z9 with lighter railways:
![z9rail](https://user-images.githubusercontent.com/5209216/49331012-12424580-f597-11e8-94be-00bb20fc704d.png)

z9 with lighter railways and thicker gray borders:
![z9railborders](https://user-images.githubusercontent.com/5209216/49331014-15d5cc80-f597-11e8-9198-7cd990d52f31.png)

**Comment by Tomasz-W** [comment] 2018-12-01 21:00
@vholten Looks very promising. I would also consider dropping rendering of smaller cities on z9.

**Comment by kocio-pl** [comment] 2018-12-01 22:36
I don't feel it helps. Maybe there should be no small grey roads to make lighter railways visible.

**Comment by sommerluk** [comment] 2018-12-02 03:10
Dropping placenames at z9? Yet now there are too few of them at places like https://www.openstreetmap.org/#map=9/-22.4694/20.2670

**Comment by Adamant36** [comment] 2018-12-02 05:12
Id be in favor of dropping grey roads at some zoom levels. Even in more rural areas they can be distracting and hinder viewing of other more important things. 

For me at z9 its about viewing major roads like freeways, major water bodies/ways, and landuse. You could even almost get rid of them at z10 and id still probably be perfectly fine with it.

**Comment by vholten** [comment] 2018-12-02 18:02
Showing gray roads at a later zoom level could help. Currently, secondary roads appear as gray roads on z9 and tertiary roads on z10. I have now changed these to appear one level later, i.e., secondary roads at z10 and tertiary ones at z11. In addition, I have slightly reduced the thickness of the colored roads.

z9 current:
![z9osm](https://user-images.githubusercontent.com/5209216/49343131-6109e100-f664-11e8-9c92-45288620af9b.png)

z9 new:
![z9railbordersroads](https://user-images.githubusercontent.com/5209216/49343135-69fab280-f664-11e8-84fe-c3d3e032cdbf.png)

**Comment by matkoniecz** [comment] 2018-12-02 20:16
Have you checked effects in more rural regions?

**Comment by vholten** [comment] 2018-12-02 21:46
Rural area, z9 current:
![z9rural_osm](https://user-images.githubusercontent.com/5209216/49345356-f10b5300-f683-11e8-9426-e0dc8c1f9793.png)

z9 new:
![z9rural_railbordersroads](https://user-images.githubusercontent.com/5209216/49345359-f7013400-f683-11e8-98af-0c92b8b6d5d2.png)

**Comment by jeisenbe** [comment] 2018-12-02 23:15
This could have a bad result in developing countries.

Indonesia has lots of primary roads on Java, but most other islands only
have one primary road and a few secondary. And main islands are larger than
the average European country.

The USA and Canada also have large, sparsely-populated areas with just a
few primary and secondary roads. I’d suggest testing in Wyoming, Montana,
Alberta or British Columbia.

I’ll try to test this change in Australia today

**Comment by Adamant36** [comment] 2018-12-02 23:49
I think it would have benefit even in sparsely mapped places. Especially as more roads, other main infrastructure, and major waterways get mapped. For instance, where I mainly map [Northern California](https://www.openstreetmap.org/#map=9/40.2575/-121.8549), there isn't much mapped there yet, but the grey roads are still a distraction and don't really add anything at z8-z10. Its enough to know that i5 is the main road going north/south and also to see the other major freeways. But the grey roads, although there isn't many, get in the way of viewing the major waterways. Plus there's the grey mess in the middle of Redding at z9. For the smaller town Shasta lake just north of there you can't even see the roads at z9. So it wouldn't effect anything there or really anything south either. 

In a lot of places in California, Z9/z10 covers the whole east west span of it and also some of Nevada. Its completely unnecessary to display minor roads at that point. Especially since they don't have road names. Its to abstract to ascertain anything from them. I travel around that area all the time and I can't even tell which roads they are from looking at the map on z9. Like the two grey roads going west between Anderson and Red Bluff for instance. I'm definitely not going to do any rural drive planning off it at that zoom level.

**Comment by jeisenbe** [comment] 2018-12-04 03:35
@Adamant36, are you from Shasta county? I'm from Siskiyou.

[Siskiyou is just north of Shasta, and actually contains [Mount Shasta](https://en.wikipedia.org/wiki/Mount_Shasta) (Stratovolcano, 4322 meters elevation with 2979 m of prominence, 96th in the world) for which Shasta county is named.]

Re: https://github.com/gravitystorm/openstreetmap-carto/issues/3538#issuecomment-443127957
The places linked look odd mainly because the Wilderness areas have been marked as separate from the surrounding National Forest, so there are two "nature_reserve" boundaries right next to each other. I think this tagging is incorrect; National Wilderness areas were always shown as being contained within a US National Forest on old USGS maps, and I don't think this has changed. So the Mount Shasta wilderness should be considered part of the surrounding National Forest, for example. This may be a problem related to the lack of rendering for boundary=protected_area in the past leading to the use of nature_reserve inappropriately. 

I'll ask about this on the US-talk email list.

**Comment by Adamant36** [comment] 2018-12-04 07:34
@jeisenbe, yep. I've lived around here most of my life. I use to live in Siskiyou County as a teenager. So I know Mount Shasta and the surrounding area quit well. I was actually going to ask if you lived up here. I figured you were probably from the Bay Area or somewhere down there though. Their isn't really any serious mappers from this area, let alone programmers. At not that I know of. So its cool to see someone else from here. 

As far as the places in the link goes, I think you and @matkoniecz are both correct about it being miss-tagging (probably partly due to the lack of rendering of protected areas as you suggest). A lot of it shows up in GeoFabrics quality assurance tool. So it has to be screwed up. I'm not really good at understanding relations and all that mess. So I decided to just leave it alone. Starting a discussion about it in the US-talk mailing list would be really helpful though. Id like to see it fixed if possible.

**Comment by jeisenbe** [comment] 2018-12-04 13:44
I've checked out some rural areas, and I don't think it is a good idea to remove secondary highways from z9.

Here's Darwin, Australia:
z9, Current master:
![darwin-z9-master](https://user-images.githubusercontent.com/42757252/49445367-1d0a0e00-f815-11e8-8c09-75e386374ec1.png)

z9 Without secondary highways:
![darwin-z9-no-secondary](https://user-images.githubusercontent.com/42757252/49445371-1e3b3b00-f815-11e8-981e-287f2f72cf1b.png)

**Milingimbi (East of Darwin)**
z10 current
![milingimbi-z10-master](https://user-images.githubusercontent.com/42757252/49445378-25624900-f815-11e8-8d06-30b37d337345.png)

z10 without tertiary highways
![milingimbi-z10-without-tertiary](https://user-images.githubusercontent.com/42757252/49445383-298e6680-f815-11e8-8e45-0adca109bdcd.png)

The map is going to be pretty blank in the Northern Territory without these highways.

**Baliem Valley, Papua, Indonesia:**
z9 current master
![baliem-z9-master](https://user-images.githubusercontent.com/42757252/49445430-4165ea80-f815-11e8-87a5-8c9c390b337d.png)

z9 without secondary - the towns are disconnected
(The secondary highways are unpaved, gravel roads. But they are the only roads)
![baliem-z9-no-secondary](https://user-images.githubusercontent.com/42757252/49445508-635f6d00-f815-11e8-828e-0fdc83313dc9.png)

z10 Current master
![baliem-z10-master](https://user-images.githubusercontent.com/42757252/49445517-69554e00-f815-11e8-99bc-43b7d7ac4d75.png)

z10 without tertiary highways
- Bokondini and Kobakma are disconnected
![baliem-z10-no-tertiary](https://user-images.githubusercontent.com/42757252/49445552-8427c280-f815-11e8-9a81-1d9159ef2c3a.png)

**Rogue Valley and Siskiyou County, Oregon/California**
z9 Current:
![siskiyous-z9-master](https://user-images.githubusercontent.com/42757252/49445597-9efa3700-f815-11e8-981c-399762735e8a.png)
Several of the secondary highways shown are rather important; consider the highway that connects the towns of Ashland and Klamath falls. Also the road that connects Yreka with the trunk highway to the southeast, and the road looping south through the Applegate river valley between Medford and Grants Pass. These are tagged as secondary because they are county roads rather than State Highways.

**Comment by matkoniecz** [comment] 2018-12-04 13:58
Thanks for making review of also remote areas. (small caveat for "These are tagged as secondary because they are county roads rather than State Highways." - OSM is not obliged to blindly follow official classification, there is no reason why county-operated road can not be marked as `highway=primary`)

**Comment by Adamant36** [comment] 2018-12-04 14:55
@jeisenbe, what do you think the percent of roads are mapped and mapped properly in a place like Darwin? I know in California a lot of roads might be mapped, but a lot of them classified wrong or don't really exist due to being added with a pretty inaccurate import that hasn't really been fixed yet. So maybe it will be sparse in some areas there for a while, but I'm pretty sure it will improve as people upgrade the roads to their proper classification and implement things like @matkoniecz suggests. Maybe not rendering at z9 will help a little. 

In places like Baliem Valley, if those are the only roads connecting the two towns its debatable if they are even secondary or should upgraded to primary. Same goes for Bokondini and Kobakma. As they all seem to be major routes linking largeish towns.

**Comment by dieterdreist** [comment] 2018-12-04 15:52
sent from a phone

> On 4. Dec 2018, at 14:58, Mateusz Konieczny <notifications@github.com> wrote:
> 
> "These are tagged as secondary because they are county roads rather than State Highways." - OSM is not obliged to blindly follow official classification, there is no reason why county-operated road can not be marked as highway=primary)
> 


I agree that being a county road might not necessarily imply it is a secondary road, but I also second the observation that secondary roads should be kept on z8-10 because they are sufficiently important for the network structure, even more in remote areas with no primary roads nearby.

**Comment by Adamant36** [comment] 2018-12-05 06:55
I say keep them on z10 but get rid of them on z9. You can hardly tell they are there anyway. Especially next to rivers. That or make them more visible at least. 

I still think though that z9 is too zoomed out for village to village route planning yet. Especially if they are close together. The cropped images of Bokondini and Kobakma are a little misleading because it gives the impression that's all the person would be looking at. With a full map though view of the area at z9 though its a couple hundred miles (probably more) that impasses 14 villages, several large mountain ranges/nature reserves, and an ocean on the bottom right side. That's just the zoom level for trying to figure out which road I want to take from point A to point B. Even the visible yellow roads are insignificant at that level. Its good enough to know that "Oh look, Mula is a little east of Karubaga." There's no reason people can't zoom into z10 to found out how exactly they are connected by the road network and in my opinion they should. 

Otherwise, start a meta issue and decide  what the purpose of each zoom level is once and for all. There's no online map though that I can think of, Google maps included, that starts rendering those types of roads that far out and its usually highly dependent on the place. 

Personally, I think its much better to forgo map clutter and bad rendering in a bunch of places at the expensive of a few places, then it is to keep rendering something based on the example of a small number of places that would be negatively effected when people can easily just zoom in one more level to see what they need to. 

(Karubaga at z9 un-cropped to show how the cropped images are misleading)
![karubaga z9 uncropped](https://user-images.githubusercontent.com/30259065/49495386-a91d3500-f817-11e8-9215-31ffc3b6eec1.png)

**Comment by jeisenbe** [comment] 2018-12-05 08:21
I crop images because a 600x400pixel png is 70 to 90kb, while the
1863x839 image you just shared was 588kb, and I pay per megabyte.
Also, I do not usually look at OSM at full screen size (limited to
1280 pixels in my case, at any rate), but usually at about 800x600.
This is also closer to the size of the map shown on
standard-resolution smart phones.

In the USA, only US highways are clearly tagged as primary, and State
highways are often tagged as secondary, with county roads as tertiary.
See https://wiki.openstreetmap.org/wiki/United_States_Road_Classification

This proposed change will lead to very few roads rendered in the rural
parts of California, Oregon and Washington at z9 and z10. I suspect
the same is true in Canada and Russia, an I've shown this to be the
case in rural Australia as well.

**Comment by Adamant36** [comment] 2018-12-05 08:52
I wasnt trying to insenuate that you were cropping the photos to make them look missleading. So I apologize if it sounded that way. 

I just think seeing the surrounding area gives it needed context. Plus, its how it would look to a mapper on a computer. One of the main audiences for the style. It might be benificial to keep the roads for the viewing of people on mobile, but I am constantly reminded by people with more clout then me on the various OSM related projects and sites that the main page is not meant to be for mobile users and therefore will never be mobile friendly. So it shouldnt be a factor in this decisions. Although personally, I wish it could be. 

As I have said, yes a lot of roads in rural areas would disapear on z9, but its just not the zoom level for it. Its not a good zoom level for finding a routing path between towns and renderings roads in grey at that level causes problems with viewing other things like rivers. I have no issue with keeping them at z10. There's no reason people cant zoom in one more level. Its a small price for better rendering. Its a balance. Otherwise, your saying z9 should look bad because its unfair to expect people to use z10 instead. When you have no proof z9 is even being used for routing purposes (it definently doesnt serve a purpose to mappers to show the grey roads at z9). The roads arent "disapearing" either. They are just going down a zoom level where its easier to view them and they dont conflict other things.

**Comment by dieterdreist** [comment] 2018-12-05 09:35
Am Mi., 5. Dez. 2018 um 07:55 Uhr schrieb Adamant36 <
notifications@github.com>:

> . That or make them more visible at least.
>

+1, according to the background they are not very visible or hardly visible
at all currently.

**Comment by jeisenbe** [comment] 2018-12-07 05:03
I've tested some renderings in  Hawaii, Wales, Northern Ireland,and Delaware. 
The first two have some areas that lack secondary highways, and in Hawaii sometimes the main coastal highway is only tagged as tertiary. But in Northern Ireland and Delaware (especially the later) it would be nice to remove tertiary highways from z10. 

It looks like we have a problem with different standards for the different highway classifications. In Hawaii, Indonesia, parts of the West Coast of the USA and in many developing countries it is common to reserve highway=primary for roads between cities or at least between major towns, while in northern Europe it seems common that most towns are connected by highway=trunk, and even many villages are on a highway=primary. Most villages have at least a highway=secondary.

But in Indonesia and Hawaii, many towns (>10,000 people) have only a secondary or tertiary highway under the current system. 

I'm willing to talk about this with the US Tagging list (unfortunately there is no active list for Indonesia), but I don't know if USA mappers are interested in using highway=trunk instead of highway=primary for most US highways and major state highways, so that highway=primary can be used for frequently.

**Oahu to Maui, current z9:**
![oahu-maui-z9-current](https://user-images.githubusercontent.com/42757252/49628498-bb6dbd80-fa27-11e8-858e-f532165a83e7.png)

z9 without secondary highways:
- No roads now visible to connect to two towns on Moloka'i (center)
- Roads missing in northwest Oahu (left) and southeast Maui (right), leaving towns disconnected
![oahu-maui-z9-no-secondary](https://user-images.githubusercontent.com/42757252/49628509-cc1e3380-fa27-11e8-952d-0a0af82d6527.png)

**Maui z10, current**
![maui-z10-current](https://user-images.githubusercontent.com/42757252/49628583-52d31080-fa28-11e8-8fdc-14900a9cb3a6.png)

z10, no tertiary
- towns on east of island  are now disconnected
![maui-z10-no-tertiary](https://user-images.githubusercontent.com/42757252/49628592-63838680-fa28-11e8-8590-2f046d166076.png)

**Oahu z10, current**
![z10-oahu-current](https://user-images.githubusercontent.com/42757252/49628623-857d0900-fa28-11e8-9e9c-7abbbaa0f35e.png)
- You can see that the secondary roads in the north and northwest would be eliminated at z9

**Hawaii (Island), current z9:**
![hawaii-z9-current](https://user-images.githubusercontent.com/42757252/49628541-0687d080-fa28-11e8-87bc-7ac457bf3049.png)

z9 without secondary:
- missing connection between primary road in center and west coast of island. 
- town of Kapaau in north is disconnected
![hawaii-z9-no-secondary](https://user-images.githubusercontent.com/42757252/49628549-14d5ec80-fa28-11e8-872a-04a611546da0.png)

**Hawaii, z10**
![n-hawaii-z10-current](https://user-images.githubusercontent.com/42757252/49628612-79914700-fa28-11e8-8167-97a0403c3593.png)

z10 without tertiary
- not a big difference here
![n-hawaii-z10-no-tertiary](https://user-images.githubusercontent.com/42757252/49628652-b5c4a780-fa28-11e8-9dd6-550f6fd06b4f.png)

**Comment by jeisenbe** [comment] 2018-12-07 05:10
**Wales, z8** - this will not change
![wales-z8](https://user-images.githubusercontent.com/42757252/49628668-ddb40b00-fa28-11e8-8796-ba8325508fa3.png)

**Northern Wales, z9** Before
![n-wales-z9-current](https://user-images.githubusercontent.com/42757252/49628678-f7555280-fa28-11e8-869f-361129789dd6.png)

Without secondary highways
- The peninsula on the lower left looks roadless
![n-wales-z9-no-secondary](https://user-images.githubusercontent.com/42757252/49628681-ffad8d80-fa28-11e8-9bc8-fb608fd2988d.png)

**Pwllheli z10** current
![pwllheli-z10-current](https://user-images.githubusercontent.com/42757252/49628698-1b189880-fa29-11e8-9197-3afe0e85cbb8.png)

z12 - yes, there are roads and villages here
![z12-pwllheli](https://user-images.githubusercontent.com/42757252/49628740-53b87200-fa29-11e8-9011-6348db2f91dc.png)

**Southern Wales, z9** current
![s-wales-z9-current](https://user-images.githubusercontent.com/42757252/49628691-0b00b900-fa29-11e8-94a2-21a29dd08089.png)

Without secondary highways
![s-wales-z9-no-secondary](https://user-images.githubusercontent.com/42757252/49628755-7054aa00-fa29-11e8-9513-79ed1b307e27.png)

**Swansea z10** current
![swansea-z10-current](https://user-images.githubusercontent.com/42757252/49628762-79457b80-fa29-11e8-9ac2-150d56f5b2a6.png)

Without tertiary
![z10-swansea-no-tertiary](https://user-images.githubusercontent.com/42757252/49628768-8498a700-fa29-11e8-8a72-b4a1ae734d83.png)

z12 - to show villages and tertiary roads clearly
![z12-sw-swansea](https://user-images.githubusercontent.com/42757252/49628781-91b59600-fa29-11e8-90e3-d43e138e0058.png)

**Comment by jeisenbe** [comment] 2018-12-07 05:15
Northern Ireland has a large number of trunk roads, which connect most of the towns. There are a couple of places where removing secondary roads at z9 might be a problem, but removing tertiary from z10 will not be harmful in this area.

**Northern Ireland, z8** 
- would not change
![n-ireland-z8-current](https://user-images.githubusercontent.com/42757252/49628863-fb35a480-fa29-11e8-9f8f-38248b9ca23c.png)

**z9 Current**
![n-ireland-z9-current](https://user-images.githubusercontent.com/42757252/49628878-08529380-fa2a-11e8-94f6-8b56b5f0ad25.png)

Without secondary
![n-ireland-z9-no-secondary](https://user-images.githubusercontent.com/42757252/49628889-130d2880-fa2a-11e8-9330-71fdc2e63b28.png)

**Derry z10** Current
![derry-z10-current](https://user-images.githubusercontent.com/42757252/49628904-23bd9e80-fa2a-11e8-8e98-ed594628606e.png)
Without tertiary
![derry-z10-no-tertiary](https://user-images.githubusercontent.com/42757252/49628908-27512580-fa2a-11e8-9003-44e16f482b30.png)

**Enniskillen z10** Current
![enniskillen-z10-current](https://user-images.githubusercontent.com/42757252/49628919-31732400-fa2a-11e8-945a-256ebb40ff98.png)
Without tertiary
![enniskillen-z10-no-tertiary](https://user-images.githubusercontent.com/42757252/49628953-52d41000-fa2a-11e8-9fa4-f25b250291ab.png)

**Comment by jeisenbe** [comment] 2018-12-07 05:20
Delaware has many roads tagged at highway=trunk connecting the main towns. It looks like a few places are tagged as villages that might actually qualify as towns in the southwest corner? But there is certainly no problem with removing secondary roads here, and hiding tertiary roads on z10 will look nice in Delaware:

z10 before
![s-delaware-z10-current](https://user-images.githubusercontent.com/42757252/49629004-aa727b80-fa2a-11e8-9aef-9619af1f4b66.png)

z10 without tertiary
![s-delaware-z10-no-tertiary](https://user-images.githubusercontent.com/42757252/49629010-b0685c80-fa2a-11e8-9dc5-008248607fcd.png)

**Comment by Adamant36** [comment] 2018-12-07 13:13
@jeisenbe, there's a page on the wiki about USA road tagging and it seems like there was any agreement reached as to how it should be. So I'm not sure your statement about them using highway=trunk instead of highway=primary for most US highways and major state highways necessarily holds true. There's wide variance here depending on the state and the whims of the mappers. A lot of it probably has to do with lack of education about road classifications (most people I've talked to about the subject don't even know they exist or that something like urban planning is a thing). Plus, people have a major tendency to re-tagged things that are already tagged correctly based on their whim anyway. 

Also, the TIGER import screwed most of the roads up here a while ago and largely hasn't been fixed. It made a lot of roads more minor then they should have been and wrongly tagged a large amount of track/service roads as residential. 

So I don't think we should use America or reading into it as an example of why to go through with idea. It should be based on if things look better or not in those areas, but not on the theoretical preferences of the mappers here. Although, its still worth bringing up in the USA talk list anyway.

**Comment by Adamant36** [comment] 2018-12-07 15:45
@jeisenbe, also just for clarification are you against this road change completely, just with certain road types, or? Further, have put any thought or done any tests on the suggesting made by and Dieterdreist just to make the roads more visible instead? I'm not that up on how road rendering works, but I might be into just making them easier to see instead of getting rid of them. 

I'd like to see test renderings of both to compare the options though. So if you want to forgo disappearing roads for now, since we all essentially get what it entitles, and work making them more visible instead that would be good. Its pretty obvious at this point that some places would benefit from them being removed and some wouldn't.

**Comment by Tomasz-W** [comment] 2018-12-10 17:38
I think we should focus on original propositions of this ticket and eventually come back to dropping tertiary roads on z10 at the end (examples above shown that dropping secondary roads on z9 is a bad idea).

* bolder country borders on z8-9
* thinner protected areas borders on z8-10
* lighter railways on z8-10

**Comment by vholten** [comment] 2018-12-14 18:45
I've experimented more with making railways less prominent. On z8 this can be done easily: there are no gray roads, so there is no possible confusion between railways and roads.

On z9, secondary roads are shown in gray. If railways are made lighter, it becomes harder to distinguish secondary roads from railways. A possible solution is to remove secondary roads from z9, but this is controversial. Another solution is to make secondary roads a bit lighter as well.

Here I show the result of the following changes on z9:
- Border color from #3553
- Thicker borders as in #3563
- Lighter railways
- Lighter secondary roads
- Thinner colored roads (motorway, trunk and primary)

z9 before:
![z9osm](https://user-images.githubusercontent.com/5209216/50021174-88ec3380-ffd8-11e8-80da-6da9887f1343.png)

z9 after:
![z9preview2](https://user-images.githubusercontent.com/5209216/50021180-8c7fba80-ffd8-11e8-88b3-5044619fdb8a.png)

**Comment by jeisenbe** [comment] 2018-12-15 00:59
We could also solve this problem by changing the road spectrum, with
motorways in violet/purple. Then secondary roads would be yellow-orange and
could be displayed in this color instead of gray at z9, and railways could
be lighter at z8 and z9 without confusion.

(Secondary can’t be shown as the current yellow at z9 and z10 because the
yellow has poor contrast with land-color and farmland)

**Comment by Tomasz-W** [comment] 2018-12-15 08:04
@jeisenbe I'm sure that adding more colours will rather make this mess bigger instead of reduce it.

**Comment by Adamant36** [comment] 2018-12-15 20:34
I'd like to see minor unclassified roads rendered differently then residential. So if adding more colors would help with that I'm for it. Otherwise, not so much and I agree with @Tomasz-W omasz-W that it would just be over complicating things. The only other viable solution I see is not rendering minor roads at higher zoom levels.  

Otherwise, you'll have to reinvent the whole wheel just to patch a small hole in the outer tube (in this case changing the rendering of all or most of the roads, just to make railroads look better. 

To me it seems a way better option would be the road rendering deprioritizion option, which would resolve other issues also, but that's already been shot down due to the few examples where it would be a problem (which is really debatable anyway), at the expense of the many places that would benefit from it. 

Implementing some of @Tomasz-W suggestions in https://github.com/gravitystorm/openstreetmap-carto/issues/3538#issuecomment-447428874 might work also (including a railway pattern). I'd like to see them tried out first before the wheel reinvention commences.

**Comment by vholten** [comment] 2018-12-15 20:46
A railway pattern would be a way to distinguish railways from roads, but the pattern that we currently use would make railways even more prominent at low zooms instead of less.

The [TileMill documentation](https://tilemill-project.github.io/tilemill/docs/guides/styling-lines/) has an example with a more subtle railway pattern:

> A common way of symbolizing railroad lines is with regular hatches on a thin line. This can be done with two line attachments - one thin and solid, the other thick and dashed. The dash should be short with wide spacing.
![styling-lines-9](https://user-images.githubusercontent.com/5209216/50047260-367f4580-00b2-11e9-9afd-51f41b0b51b8.png)

**Comment by Adamant36** [comment] 2018-12-15 20:49
@vholten, to me its 50/50 between making it less prominent versus making it clearly distinguishable from roads. A patter might make it stand out more, but at least its clear its a railroad that way. I'm not sure if it balances out though.

**Comment by Tomasz-W** [comment] 2019-01-03 09:23
We have better protected areas borders and country borders merged, but there are still few things to decide/ test:
* dropping secondary roads from z9
* dropping tertiary roads from z10
* coordinate roads/ railways withs and shades (see https://github.com/gravitystorm/openstreetmap-carto/issues/3538#issuecomment-447417505 and https://github.com/gravitystorm/openstreetmap-carto/issues/3538#issuecomment-447428874)
* test railway pattern from https://github.com/gravitystorm/openstreetmap-carto/issues/3538#issuecomment-447596729

@vholten Do you plan further work on this issue?

**Comment by jeisenbe** [comment] 2019-09-05 10:41
Updated title to match 2 remaining suggestions: lighter railways, less prominent minor highways at z8-10.

**Comment by dieterdreist** [comment] 2019-09-06 07:48
-1 to lighter railways, the dark color is required to distinguish them from
roads. Current railway color is quite intuitive.

Minor highways aren't shown at all at z8, and are unobtrusive in z9 and 10,
if they would be even less prominent they would be hard to see at all.

**Comment by jeisenbe** [comment] 2019-09-06 08:12
Agreed. I'm inclined to close this issue, since the test images above did not seem to be a clear improvement in all areas. 

The current use of highway tags is quite different in places like England  vs developing countries and North America, so it's difficult to get an ideal rendering for all countries with a global stylesheet. Rendering tertiary or secondary roads at a later zoom level would be an improvement in places like England, but not in western Australia or eastern Indonesia. 

And currently roads and railways keep mostly the same colors at different zoom levels - changing railways to a lighter color would make it more difficult to distinguish them from minor roads.

**Closed** 2019-09-06 08:29 UTC
Labels: admin, cartography
