### ISSUE TITLE
Island within lake not properly rendered.

### ISSUE THREAD

**Issue by marczoutendijk** [gravitystorm/openstreetmap-carto#1760] opened 2015-08-17 15:58 UTC
On this spot:
http://www.openstreetmap.org/#map=13/38.1061/-2.7978
The rendering of the island - Isla Cabeza de la Viña - (with landuse=forest) within the lake, is not rendered as it should.
The mulipolygon of the lake has the island as inner.
In my memory this didn't happen in previous versions.

**Comment by jojo4u** [comment] 2015-08-17 16:36
Duplicate of #1754?

**Comment by marczoutendijk** [comment] 2015-08-17 17:42
In a sense yes, but with a difference because in this case whe have an island within a lake, and #1754 is lake within forest....

**Comment by jojo4u** [comment] 2015-08-17 18:20
The outer has natural=water, so this is no surprise:
https://www.openstreetmap.org/way/4987665
Please move everthing to the multipolygon.

**Comment by pnorman** [comment] 2015-08-17 21:06
If there were a bug here, it would be an osm2pgsql bug, but the rendering appears to be correct.

There is https://www.openstreetmap.org/way/4987665 which is a closed way forming a POLYGON with natural=water, and the polygon has no inner holes. There is https://www.openstreetmap.org/relation/971648 which is a relation with type=multipolygon, forming a POLYGON with landuse=reservoir, and the polygon has two inner holes.

**Closed by pnorman** 2015-08-17 21:06 UTC

**Comment by mboeringa** [comment] 2015-08-17 21:29
I fixed it by removing the repeated identical tags from the outer. Seems to render fine now (island appears at z13: https://www.openstreetmap.org/#map=13/38.1152/-2.7543)
