### ISSUE TITLE
landuse=railway vs railway=platform

### ISSUE THREAD

**Issue by UncleOwen** [gravitystorm/openstreetmap-carto#4336] opened 2021-02-24 17:35 UTC
### Expected behavior
railway=platform should be visible even if landuse=railway obscures it.

### Actual behavior
railway=platform is invisible if landuse=railway is present on another area

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/relation/6090975
https://www.openstreetmap.org/way/398260941

**Comment by HolgerJeromin** [comment] 2021-02-26 16:04
The painters algorithm should have taken care of that. Small objects are painted later than larger ones.

[This platform](https://www.openstreetmap.org/way/178307894) is similar tagged and rendered. Perhaps the multipolygon is cause problems here...

**Comment by sun-geo** [comment] 2021-03-01 12:00
Seems duplicate of #4008

**Closed** 2021-03-30 18:43 UTC
Labels: duplicate
