### ISSUE TITLE
Render building=* single nodes

### ISSUE THREAD

**Issue by bjohas** [gravitystorm/openstreetmap-carto#2635] opened 2017-05-19 11:05 UTC
I'd like to raise this issue again: https://github.com/gravitystorm/openstreetmap-carto/issues/806, i.e. buildings that are a node (with tag=building) are not rendered.

https://wiki.openstreetmap.org/wiki/Key:building suggests that nodes tagged as buildings are fine. It seems that if the node is named, it does appear. Not sure about what else makes the node appear. However, building=yes doesn't seem to be sufficient.

https://taginfo.openstreetmap.org/keys/?key=building says there's just under 1m buildings as nodes (about 0.5% of buildings that are areas, which is about 220m in total). 

Running some overpass queries, I'd say there are around 60,000 buildings as nodes in sub-Saharan Africa - seems a shame to not render these, when otherwise map data is still sparse in many areas (despite the amazing work of Missing Maps).

Many thanks for your views!

**Comment by pnorman** [comment] 2017-05-19 11:23
Duplicate of #806, if we need to discuss it it, we can do so there.

**Closed by pnorman** 2017-05-19 11:23 UTC
Labels: duplicate
