### ISSUE TITLE
Render issues in dense area with multiple levels

### ISSUE THREAD

**Issue by Phyks** [gravitystorm/openstreetmap-carto#3811] opened 2019-06-20 13:41 UTC
Hi,

I noticed a few render issues around https://www.openstreetmap.org/#map=18/48.84186/2.32202&layers=N. I was trying to understand what is wrong with the data, but am in a bit of a dead end and think part of the issues can be coming from openstreetmap-carto. Please, let me know if this is not the right place to report it.

### Expected vs actual behavior

In the current render (picture below), there are a couple of things which are wrong:

- [ ] [This area of water](https://www.openstreetmap.org/way/170193273#map=19/48.84210/2.32251) is never displayed, even at higher zooms.
- [ ] On the other hand, [Place Raoul Dautry](https://www.openstreetmap.org/relation/8365033) hides completely the "Avenue du Maine" tunnel.
- [ ] Although the ["Avenue du Maine"](https://www.openstreetmap.org/way/5213104#map=18/48.84117/2.32132) tunnel is hidden by the Place Raoul Dautry, arrows are still shown on top of the Place Raoul Dautry.

### Links and screenshots illustrating the problem

https://www.openstreetmap.org/#map=18/48.84186/2.32202&layers=N

![Capture d’écran 2019-06-20 à 15 34 39](https://user-images.githubusercontent.com/3856586/59853421-21d97e00-9371-11e9-9e1b-e5330c5d015e.png)

My guess so far is that this is coming from a problem of ordering in the roads layers, at least concerning the "Avenue du Maine" / "Place Raoul Dautry" part.

Best,

**Comment by imagico** [comment] 2019-06-20 14:06
> This area of water is never displayed, even at higher zooms.

That's a mapping error - that water area overlaps with a highway=pedestrian area which is a contradiction.

> On the other hand, Place Raoul Dautry hides completely the "Avenue du Maine" tunnel.

Not sure how you would want this to look instead - i assume you would still want non-tunnel roads to be drawn above tunnels?

**Comment by Phyks** [comment] 2019-06-20 14:19
> That's a mapping error - that water area overlaps with a highway=pedestrian area which is a contradiction.

Indeed.

> Not sure how you would want this to look instead - i assume you would still want non-tunnel roads to be drawn above tunnels?

First problem in my opinion so far is that this is not homogeneous. Tunnel is hidden by the pedestrian square, but not by the grass. If the tunnel was to be drawn below the pedestrian square, I'd rather have it below the grass as well (although they probably live in two different Mapnik layers and this might be tricky :/).

My personal preference might be to have something like https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.84154/2.32126 with the road on top of the pedestrian area (but with a tunnel outline indicating it is actually below). Probably with a semi-transparent effect?

![Capture d’écran 2019-06-20 à 16 19 12](https://user-images.githubusercontent.com/3856586/59856445-34ef4c80-9377-11e9-87b5-6fb9c90bde3e.png)

**Comment by imagico** [comment] 2019-06-20 14:38
The example you showed does not render highway=pedestrian as a road type but as a landcover.  Rendering highway=pedestrian polygons continuously with linear road feature is one of the central features of road rendering in this style - see:

https://www.openstreetmap.org/#map=18/45.77987/3.08251
https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/45.77978/3.08332

**Comment by Phyks** [comment] 2019-06-20 17:01
> The example you showed does not render highway=pedestrian as a road type but as a landcover. 

Indeed. (Disclaimer, I'm one of the author of CyclOSM). In my opinion, this has the advantage of showing what is the geometry of the road beneath the square. In case the tunnel road is not oneway, there would not even be any visual hint about the geometry of the road beneath the pedestrian area.

This is however not a strong opinion (and CyclOSM render is far from being the best one we can have here I think).

The main issue here, in my opinion, is the difference between landuse (road is on top, no matter the level) and pedestrian areas (road is below), which makes it quite comfusing.

This also has greater impact on the nearby "Jardin Atlantique" (https://www.openstreetmap.org/way/16923782) which is a garden on the roof. In openstreetmap-carto, it is drawn below the rails whereas it should be on top of the rails (see aerial imagery).

**Comment by jeisenbe** [comment] 2019-08-24 14:10
This is mostly a duplicate of issue #529 "Render tunnels above highway areas".

**Closed** 2019-08-24 14:25 UTC
Labels: duplicate
