### ISSUE TITLE
sport=chess publicly available tables render as picnic tables.

### ISSUE THREAD

**Issue by kubahaha** [gravitystorm/openstreetmap-carto#4417] opened 2021-06-02 11:56 UTC
### Expected behavior

[Wiki](https://wiki.openstreetmap.org/wiki/Tag:sport=chess) recommends tagging outdoor chess tables with

`leisure=picnic_table`
`sport=chess`

such places should be rendered with proper icon.

### Actual behavior

It's rendered just like any other `leisure=picnic_table`.

### Links and screenshots illustrating the problem

[example here](https://www.openstreetmap.org/node/7647066277)
![Screenshot at 13-54-47](https://user-images.githubusercontent.com/6720051/120475865-33738f00-c3aa-11eb-8252-116bff7a4c17.png)

**Comment by imagico** [comment] 2021-06-02 12:25
Thanks for the suggestion.

It is not quite clear what this issue is meant to suggest - the _Expected behavior_ section does not specify an expected behavior.  We will definitely not stop rendering leisure=picnic_table as a picnic table based on the presence of an addon tag - that would support a weirdly non-intuitive view of tagging semantics.  A symbol variation would be possible, but would need to be intuitively recognizable both as a picnic table and for chess.

Numbers:

* `leisure=picnic_table` + `sport=chess`: ~1080, almost all of them nodes.
* `leisure=pitch` + `sport=chess`: ~1450, 990 of them polygons, the wiki suggests using this only for large chess boards although since much of the features are actually mapped with polygons the size can be determined from the data - hence the distinction in tagging based on size seems kind of pointless.

**Comment by polarbearing** [comment] 2021-06-02 12:35
```leisure=pitch + sport=chess``` is quite odd. Obviously the table is used for the game, not for picnic. 
The wiki statement was made by user 'Webmind', with very few contributions 2012/2013. The same-named OSM user has 0 edits. 
I suggest not to change anything with our picnic_table rendering, and I will raise questions about the inconsistent tagging practice.

**Comment by kubahaha** [comment] 2021-06-02 13:44
@imagico thanks for reply. I cannot provide proper icon, as I lack graphic skills, I just suggest it's misleading for OSM Carto users (a today I found a note describing that problem).
I believe distinction in tagging is useful, large chess boards are not designed for elderly people which I often spot at tables with chess board. Other issue is, I am not sure if chess tables fit into definition of picnic table, as they are often really small and not made up for rest.

@polarbearing do you believe we should change tagging instructions? What do you think about `amenity=table` + `sport=chess`?

**Comment by pnorman** [comment] 2021-06-02 16:48
The presence of a sport tag doesn't change that these are picnic tables. Regardless of tagging, I don't think it's practical to have a different icon that makes sense for this, and there's also not enough usage

**Comment by kubahaha** [comment] 2021-06-02 17:28
Is [that](https://commons.m.wikimedia.org/wiki/File:Chess_Fr._Collins_Park.jpg) a picnic table?
There are people confused about current rendering and this is why I opened this issue.

**Comment by imagico** [comment] 2021-06-02 17:35
Closing since the tag combination this is about has:

* low overall use
* no clear adoption by mappers, the issue seems to be based on wiki documentation rather than actual use of the tag.
* questionable semantics (most public chess tables are not picnic tables, not every public table + seats combination is a picnic table)
* unclear delineation towards more common leisure=pitch + sport=chess

Tagging of public chess tables is something that quite clearly deserves some discussion (like on tagging-ML or wiki) but this is not the right venue for that.

**Closed by imagico** 2021-06-02 17:35 UTC
Labels: amenity-points, new features
