### ISSUE TITLE
Chinese render error 

### ISSUE THREAD

**Issue by hanchao** [gravitystorm/openstreetmap-carto#2862] opened 2017-09-23 08:58 UTC
![image](https://user-images.githubusercontent.com/1942091/30771640-1ccf2a2c-a07f-11e7-84fd-a55dee999a25.png)

node 复兴门
http://www.openstreetmap.org/node/339090100

**Comment by pnorman** [comment] 2017-09-23 09:07
duplicate of #2208

**Closed by pnorman** 2017-09-23 09:07 UTC
