### ISSUE TITLE
man_made=bridge label is disproportionately large

### ISSUE THREAD

**Issue by systemed** [gravitystorm/openstreetmap-carto#3979] opened 2019-11-27 12:05 UTC
It appears to be in relation to the bridge size, but for a long bridge this can be disproportionately large compared to other labels in the area.

See: https://www.openstreetmap.org/#map=17/51.45141/-2.56685

![Screenshot 2019-11-27 at 12 05 16](https://user-images.githubusercontent.com/694425/69722099-2ec38000-110e-11ea-9b80-3dd0cf11167b.png)

**Comment by HolgerJeromin** [comment] 2019-11-27 18:45
Bridge outline is https://www.openstreetmap.org/way/677268063

**Comment by polarbearing** [comment] 2019-11-27 19:16
man_made=bridge is indeed labelled based on way-size in roads.mss variably between text_size 10...14

**Comment by jragusa** [comment] 2019-12-05 12:52
Is it technically feasible to align the text along the longest edge of a polygon and to get a similar rendering than we have for lines such as railway and stream for example ?

**Comment by jeisenbe** [comment] 2019-12-09 21:06
> for a long bridge this can be disproportionately large compared to other labels in the area.

I don't see this problem in the included screenshot. The text of the bridge label is the same size as that for "Feeder Canal". Perhaps the issue is that the text color is black?

Perhaps the issue is that the name of this bridge is quite long. Is this feature in fact known locally as "Saint Philips Causeway Overbridge (MLN1)"? The combination of "causeway" and "overbridge" seems redundant, and the MLN1 at the end looks like a `ref` rather than part of the name. 

Another issue is that most of this feature is a viaduct (over land) and the bridge (over water) is just a short portion, so this makes the bridge area larger.

Does anyone have some other examples where bridge labels are too large or too prominent? The other places I've looked seem ok with the current limits

> Is it technically feasible to align the text along the longest edge of a polygon and to get a similar rendering than we have for lines such as railway and stream for example ?

This might make it more likely for the bridge name to be confused with the name of the `highway=` (or `railway=`) feature on the bridge, but it would be interested to see an example.

**Comment by jeisenbe** [comment] 2019-12-09 23:37
Examples from New York:

z14 - Long island viaduct, 2 bridges over short waterways
![z14-pulaski-brige-long-island-viaduct](https://user-images.githubusercontent.com/42757252/70482112-e0b16380-1aa1-11ea-9208-c8a00babb455.png)

z13 - several bridges visible
![z13-manhattan-bridge](https://user-images.githubusercontent.com/42757252/70482113-e0b16380-1aa1-11ea-8f09-dc80bceb87ec.png)

**Comment by matkoniecz** [comment] 2019-12-27 17:44
>I don't see this problem in the included screenshot.

The same for me, and apparently no one else feels differently.

> Does anyone have some other examples where bridge labels are too large or too prominent? The other places I've looked seem ok with the current limits

+1

Note that on any area there will be always one label that is the most prominent.

I am not closing this issue for now as I am author of bridge-labelling code and it is source of bias here, but is making bridge labels smaller is actually going to be improvement overall?

Note that typical bridge is over water / other not very important area and bridges are often useful orientation points. Bridge are often landmarks, along standard routes and chokepoints. 

And yes, some not very important bridges get quite larger labels. But in most cases there is no harm from that as bridge is almost always the most important thing anyway. Though I admit that some motorway bypasses have names that are rarely used, bridge is large and end result is a big label for rarely named feature.

But I am not aware about any better way to automatically assign importance to every single bridge label across the world than current method of basing it on the outline size.

**Closed** 2020-01-07 09:53 UTC
Labels: text
