### ISSUE TITLE
render fuel one zoom earlier

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#1779] opened 2015-08-23 06:28 UTC
On zoom 16 we have few important things like supermarkets, libraries, church icons, taxi, car_sharing and cinemas (hu?). 
IMO fuel stations are equaly important.

**Comment by matkoniecz** [comment] 2015-08-23 06:52
Duplicate of #1764

**Closed by matkoniecz** 2015-08-23 06:52 UTC

**Comment by HolgerJeromin** [comment] 2015-08-23 11:34
Oh, I did not remember this. Thanks.

**Comment by dieterdreist** [comment] 2015-08-25 11:47
sent from a phone

> Am 23.08.2015 um 08:28 schrieb Holger Jeromin <notifications@github.com>:
> 
> On zoom 16 we have few important things like supermarkets, libraries, church icons and cinemas (hu?). 
> IMO fuel stations are equaly important.


IMHO they are clearly not. In Rome it would completely clutter the map for no good reason. Supermarkets, (many) libraries, churches and to some extent cinemas are usually important landmarks, fuel stations are very less so. Please keep them on z17

**Comment by kocio-pl** [comment] 2015-08-25 12:37
There is a separate issue for showing multiple objects earlier outside the city/town/village boundaries and some landuse probably: https://github.com/gravitystorm/openstreetmap-carto/issues/1705

**Comment by matkoniecz** [comment] 2015-08-25 12:49
@dieterdreist You may want to comment on #1764 - this issue was closed as duplicate, #1764 is open.
