### ISSUE TITLE
Enhance visibility of education nodes (school)

### ISSUE THREAD

**Issue by dsauvage** [gravitystorm/openstreetmap-carto#2957] opened 2017-11-24 09:17 UTC
Hi,

As we can see on the screen shot selection below (reference http://www.openstreetmap.org/#map=16/-20.2661/57.4824), school entity (Quatre Bornes State Secondary School) is less visible than supermarkets, the used zoom level is the first where we can see nodes like library, supermarket.

From feedbacks I got on OSM talk mailing list, in some cases, school grounds are big enough for the school to be visible, and they do not need node to reference schools. Unfortunately this is not the case in my country (and in a lot of countries too). 

What a shame ! In my context, the shopping center is bigger than the school ground ! I know another way for me to solve this issue is for us to get bigger schools, we are also working on it ;-)

My proposal is to make the school (or all education family) icons to get the same visibility priority as the library icon one. This will not affect big schools like this one (http://www.openstreetmap.org/#map=16/52.8570/-2.7287) as the convention is not use nodes to refer to big school grounsd.

As an amazing project of public interest as OSM, I hope you would be sensible for our public schools to get the visibility they deserves.

Thanks for your great contributions

![osm-education-priority](https://user-images.githubusercontent.com/1416228/33202906-9a9fa508-d117-11e7-9954-0551e6857533.png)

--
David

**Comment by SomeoneElseOSM** [comment] 2017-11-24 10:16
There was a discussion about having an "amenity=school" icon over at https://github.com/gravitystorm/openstreetmap-carto/issues/120 .  Unfortunately some of the example images referenced there don't seem to be available any more, but rest is still relevant.

**Comment by kocio-pl** [comment] 2017-11-24 12:19
Thanks for the report. It's a duplicate of #120, so I will close it - please discuss the problem there, if needed.

We had a PR which was almost ready, but we were unable to decide how to deal with label scaling, because we do this for schools and the icon is not to be scaled. There are also other similar objects (like hospitals etc), which use the icon, but don't use text scaling, so that would be inconsistent:

https://github.com/gravitystorm/openstreetmap-carto/pull/2361#issuecomment-249383602

So the most important thing is to find a rule for all such objects. If we have it, rendering education icons could be made quite easily.

**Closed by kocio-pl** 2017-11-24 12:19 UTC
