### ISSUE TITLE
Render landuse=forest multipolygon inners when they're a different kind of forest

### ISSUE THREAD

**Issue by grischard** [gravitystorm/openstreetmap-carto#2550] opened 2017-01-16 15:57 UTC
https://www.openstreetmap.org/way/462199313 is a `leaf_type=needleleaved landuse=forest` way that's an `inner` inside of a `leaf_type=broadleaved landuse=forest` multipolygon.

It currently doesn't render at all. Would it please be possible to render it like a `leaf_type=needleleaved` that's not part of a multipolygon? If that's very complicated to achieve, is there a workaround?

Thanks!

**Comment by imagico** [comment] 2017-01-16 16:37
If i am not mistaken the changes surrounding the database reload should solve this - see #2527.

A possible workaround is probably to create another multipolygon relation, add the inner ring there as outer and have the tags on that relation, i.e. completely avoid using tagged closed rings as areas.

**Comment by BushmanK** [comment] 2017-01-21 03:43
I can confirm - this workaround helps:
inner portion http://www.openstreetmap.org/relation/5441403#map=17/55.82396/37.73825
outer portion http://www.openstreetmap.org/relation/5441395#map=16/55.8244/37.7394
Without joining the parts of the inner portion into a relation, they aren't rendered properly.

**Comment by pnorman** [comment] 2017-01-22 00:58
Closing. To the extent this is currently an issue, it's an osm2pgsql one, not an OpenStreetMap Carto one.

With lua transforms it is in scope for us, but the issue is fixed there.

**Closed by pnorman** 2017-01-22 00:58 UTC
Labels: bug

**Comment by grischard** [comment] 2017-01-25 15:41
@pnorman is there a corresponding osm2pgsql bug or ticket?

**Comment by pnorman** [comment] 2017-01-25 20:34
One of https://github.com/openstreetmap/osm2pgsql/issues?q=is%3Aopen+is%3Aissue+label%3Amultipolygon would probably apply
