### ISSUE TITLE
A1303 label is truncated

### ISSUE THREAD

**Issue by occultations** [gravitystorm/openstreetmap-carto#3993] opened 2019-12-27 23:17 UTC
### Expected behavior
I expect to see "A1303" instead of "3".

### Actual behavior
The map at https://www.openstreetmap.org/#map=15/52.2117/0.0875 has a "3" in a box on top of Madingley Road. It's part of "A1303", which appears correctly if you zoom in. It's just at this zoom level that it appears incorrectly.

**Comment by polarbearing** [comment] 2019-12-28 00:01
Looks like a tile-rerendering problem. 
However I dirtied the two tiles, they are freshly rendered with no effect.
Last rendered at Fri Dec 27 23:55:33 2019:
https://b.tile.openstreetmap.org/15/16391/10792.png
Last rendered at Fri Dec 27 23:53:49 2019:
https://b.tile.openstreetmap.org/15/16392/10792.png
Stuck tileserver?

**Comment by jeisenbe** [comment] 2019-12-29 14:26
I suspect this is caused by the boundary between two metatiles. Screenshot of problem:

<img width="360" alt="Madingley Road A1303" src="https://user-images.githubusercontent.com/42757252/71558074-67020980-2a92-11ea-935a-797de8333c39.png">

**Comment by SilentSpike** [comment] 2019-12-30 12:17
duplicate of #3820?

**Comment by polarbearing** [comment] 2019-12-30 15:01
Looks like the same symptom, indeed. The other issue refers upstream: [mapnik issue #889](https://github.com/mapnik/mapnik/issues/889).  Has the comment by erande from 2017 been tested already?

**Comment by jeisenbe** [comment] 2019-12-31 05:56
@occultations thank you for reporting this issue. There is a previously open issue #3820 which reports the same problem, so I will close this one but we can continue discussion [there](https://github.com/gravitystorm/openstreetmap-carto/issues/3820).

**Closed** 2019-12-31 05:56 UTC
Labels: duplicate
