### ISSUE TITLE
Add rendering of houses standing on a road tunnel

### ISSUE THREAD

**Issue by geozeisig** [gravitystorm/openstreetmap-carto#4038] opened 2020-02-21 07:13 UTC
### Expected behavior
Houses that are on a road tunnel should be fully rendered.
### Actual behavior
Houses that stand on a road tunnel are covered by the street.
### Links and screenshots illustrating the problem
One example is the [Cube Berlin](https://www.openstreetmap.org/way/624737072#map=19/52.52344/13.36935) on Washingtonplatz. So that you have an impression this [photo](https://commons.wikimedia.org/wiki/File:CubeBerlin.jpg).

The [Swiss embassy](https://www.openstreetmap.org/#map=19/52.52104/13.37116)

**Comment by HolgerJeromin** [comment] 2020-02-21 07:29
Thanks for filing this issue. This is intentional.
see #3025 and #1609

**Comment by jeisenbe** [comment] 2020-02-21 07:45
Yes, this was intentionally changed in PR #623 

Screenshots from the linked areas above:
https://www.openstreetmap.org/way/624737072#map=19/52.52344/13.36935
<img width="608" alt="cube-berlin-screenshot-z19" src="https://user-images.githubusercontent.com/42757252/75014093-e3c8c700-54c8-11ea-8e3d-9d68f66e142d.png">

https://www.openstreetmap.org/#map=19/52.52104/13.37116
<img width="577" alt="swiss-embassy-screenshot-z19" src="https://user-images.githubusercontent.com/42757252/75014101-e7f4e480-54c8-11ea-92ed-f4c7cc0ab867.png">

While it is true that the buildings are harder to interpret, the main reason these areas look counter-intuitive is that the highway=pedestrian areas are rendered above tunnels, so it then seems strange that the building is below. Unfortunately this issue ( #529 - also see #688 ) is not easy to fix - see attempt at PR #3872

I am closing this issue as a duplicate of #1609, but feel free to discuss the related highway area issues at open issues #529 and #688

**Closed by jeisenbe** 2020-02-21 07:45 UTC
