### ISSUE TITLE
Render ford=yes

### ISSUE THREAD

**Issue by geozeisig** [gravitystorm/openstreetmap-carto#2202] opened 2016-06-28 08:55 UTC
[highway=ford](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dford) (status=Deprecated) is already rendered. Please render [ford=yes](http://wiki.openstreetmap.org/wiki/Key:ford) too or even better instead.

**Comment by gravitystorm** [comment] 2016-06-28 09:08
Duplicate of #267

**Closed by gravitystorm** 2016-06-28 09:08 UTC
