### ISSUE TITLE
Streets as areas at high zooms

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1298] opened 2015-02-08 13:53 UTC
I guess it's time to start thinking about rendering highways as areas at higher zoom levels. Pedestrian/footway areas are already possible (and used), so I think about the streets. I'm not sure what model would we use, but I think this draft is quite interesting:

http://wiki.openstreetmap.org/wiki/Street_area

I also don't know what is technically possible to render right now and what needs to be prepared yet, but I think we could start at the highest available zoom with at least rendering the street outlines.

**Comment by math1985** [comment] 2015-02-08 14:53
As area:highway is not in the database, this would require a database reload.

**Comment by kocio-pl** [comment] 2015-02-08 15:27
Then it probably depends on https://github.com/gravitystorm/openstreetmap-carto/issues/1286 - but even if it takes some months before next db reload, I'd like to know if it will be included there at all.

BTW - demo of this feature is made as a script for Maperitive:
https://github.com/javnik36/highway-area-style

**Comment by pnorman** [comment] 2015-02-09 06:34
dupe of #180

**Closed by pnorman** 2015-02-09 06:34 UTC
