### ISSUE TITLE
junction=yes on roundabout way prevents rendering 

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#3753] opened 2019-04-19 10:50 UTC
### Expected behavior
To render 
### Actual behavior
Doesn't render
I'm aware junction=yes isn't the correct tag in this situation, but it shouldn't prevent it from rendering. 

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/170483383/history
The two examples are being updated, but this image shows the problem 
![image](https://user-images.githubusercontent.com/9528328/56421142-f23ac680-6298-11e9-90f0-4d3ab96d6523.png)

**Comment by jeisenbe** [comment] 2019-04-19 13:57
This happened because the roundabout is mapped as a closed way: that is, a "way" that starts and ends at the same node. A closed way can either be used to map an area or just a line. 

Highways are normally imported as lines when mapped as a closed way, but they are imported as polygons (areas) if they are tagged `junction=yes` because this tag can be used for both nodes and areas. 

See the wiki page: https://wiki.openstreetmap.org/wiki/Tag:junction%3Dyes - this page says that "junction=yes" can be tagged on a node or an area, but not on a linear way:

"Draw an area (a closed way or a multipolygon) around the junction area as found on the ground. The area is tagged with junction=yes. The area shares nodes with the incoming and outgoing ways, so routing/turn-to-turn navigation engines can determine which ways are concerned."

I'm not sure how useful it is to map a junction as an area, but it does happen, and importing these closed ways as polygons (areas) allows us to render the name of a junction properly when it is mapped as an area. 

But fortunately this rendering problem will disappear as soon as the incorrect `junction=yes` tag is replaced with `junction=circular` or `junction=roundabout` as appropriate.

**Comment by matkoniecz** [comment] 2019-04-19 14:17
I created https://josm.openstreetmap.de/ticket/17623#ticket

**Comment by DaveF63** [comment] 2019-04-19 16:05
@matkoniecz Thanks for raising the ticket.

@jeisenbe 
> Highways are normally imported as lines when mapped as a closed way, but they are imported as polygons (areas) if they are tagged junction=yes because this tag can be used for both nodes and areas.
> 
> See the wiki page:...

I'm not sure that's correct. 
Although I concur about the lack of usefulness for `junction=yes` as a closed polygon, as described in the wiki, I don't think they're meant to include `highway `tags:

> Draw an area...  **around** the junction 

If they do, as in the case of this roundabout, `highway `should take precedence & be rendered as a highway. The `junction `tag should be treated as an error & ignored.

**Comment by jeisenbe** [comment] 2019-04-19 23:59
> highway should take precedence & be rendered as a highway. The junction tag
should be treated as an error & ignored

Unfortunately computers are dumb.

When objects are imported into the rendering database from the OSM data,
there is a list if keys and tags that are checked: if any of these keys
(like “landuse”) or tags (like “junction=yes”) are found on a closed way
object, it is then imported as a polygon.

Changing this would require rewriting the software that imports the
polygons, and I suspect it would make the performance much worse.

Also, this rendering style attempts to show when features are mapped
incorrectly, so it is ok if the rendering appears wrong when the data is
wrong.

**Comment by DaveF63** [comment] 2019-04-20 12:20
And here we go again....

Is there a webpage explaining the OSM-carto process^ so it can be understood why the software (written by humans, not computers) is repeatedly used as an excuse to not resolve a problem?

A closed way with just a highway tag renders just fine.
With the additional tag of junction=roundabout it still renders
With the additional tag of the nonsense junction=banana it still renders (I've checked.)
With the additional junction=yes tag it fails.

As certain highway tags renders closed ways with infill: https://www.openstreetmap.org/way/159417642 ^^ there must be instructions specifically telling it jump out of the rendering process.
Remove this line of code would hardly slow down the performance.

> or tags (like “junction=yes”) are found on a closed way object, it is then imported as a polygon.
Why would it be imported but then not rendered?

^^ Could you point to a wiki explanation of using `junction `as a means to infill instead of the much more popular `area=yes`?

^ I'd genuinely like to understand OSM-Carto's procedures. Is there something like a 'beginner's guide'

**Comment by jeisenbe** [comment] 2019-04-20 13:18
> ... why  the sisoftware (written by humans, not computers) repeatedly used as an excuse to not resolve a problem?

Please be nice (All the contributors and maintainers are unpaid volunteers, and most do it just for fun) 

I'm sorry if it sounded like I was making excuses. I was trying to explain why the current rendering happens this way. 

The reason for not changing the rendering is not only due to technical considerations, but also because "this style attempts to show when features are mapped incorrectly, so it is ok if the rendering appears wrong when the data is wrong". Mappers use the rendering as a hint that they have mapped a feature correctly. If it doesn't render, then they may have misspelled the name of a tag or failed to create a closed way for an area. 

Or in this case, there is a line feature (a highway) and an area feature (junction=yes) tagged on the same way, which is ambiguous, so the data needed to be fixed. Thank you for doing that!

> A closed way with just a highway tag renders just fine.
> With the additional tag of junction=roundabout it still renders
> With the additional tag of the nonsense junction=banana it still renders (I've checked.)
> With the additional junction=yes tag it fails.

Yes, in this case the key "junction" is used for 2 different things. This is common in OSM, where you can use "any tags you like" and many old tags were not developed very systematically.  

In this case "junction=roundabout", "junction=circular" etc tell you "what type of junction is this highway?", while "junction=yes" tell you "this node or area is a named junction". I personally would not map a junction as a closed way / area, but it appears to have been done 30,000 times: https://taginfo.openstreetmap.org/tags/?key=junction&value=yes

> As certain highway tags renders closed ways with infill: eg https://www.openstreetmap.org/way/159417642 there must be instructions specifically telling it jump out of the rendering process.

Ah, yes, that's a bit confusing. This `highway=residential` with `junction=yes` renders the same as a `highway=residential` with `area=yes`. Certain highway, including highway=pedestrian and highway=residential, can be mapped as an area when they open up into a square or plaza. But `highway=trunk` is not supposed to be mapped as an area, so there is no rendering when it is tagged with `area=yes` or otherwise marked as an area by being double-tagged with something like `landuse=*` or `junction=yes`

Specifically, highway = 'residential', 'unclassified', 'pedestrian', 'service', 'footway', 'cycleway', 'living_street' are rendered with area fills from `planet_osm_polygon` - a category created when the raw OSM data are imported into the rendering servers as polygons by the program osm2pgsql, based on the tags on the object. 

But all other types of highway are only rendered from `planet_osm_line`. A closed way either ends up in `planet_osm_polygon` or `planet_osm_line`; it can either be a line or a polygon, not both. 

This means that a closed way tagged highway=trunk with area=yes or junction=yes will not rendered because it is in `planet_osm_polygon` not `planet_osm_line`

> Why would it be imported but then not rendered?

If there is a `name=*` tag this would be rendered for a `junction=yes` area.

> Could you point to a wiki explanation of using `junction `as a means to infill instead of the much more popular `area=yes`?

https://wiki.openstreetmap.org/wiki/Tag:junction=yes#How_to_use_on_an_area

Area=yes is certainly the correct way to tag a highway=pedestrian as a highway area, eg a plaza or square where you can walk in any direction. 

But as I mentioned above, "area=yes" is just a tag that tells the import process to consider a closed way to be an area that should be imported as a polygon. 
 
> I'd genuinely like to understand OSM-Carto's procedures. Is there something like a 'beginner's guide'

This might help, but it's complicated. (It took me several months of contributing here to understand most of it, and I still may not understand the details, but I don't have any IT background):
https://ircama.github.io/osm-carto-tutorials/osm-rendering-process/

The best way to understand is to set up a rendering server on your own computer and try editing things. You can use Docker for Mac and PC, or set things up directly if you use Ubuntu or another version of Linux. I'm using Docker on an old Mac laptop; it works. See: https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

**Comment by matkoniecz** [comment] 2019-05-18 20:20
Klumbumbus just implemented a validator warning in JOSM, hopefully it will make this situation less confusing for mappers. Note that it was implemented minutes ago, it is not yet present in your JOSM version but after next update it should appear. It may or may not be a good idea to request validator warning also in iD.

I will close this issue as it was caused by incorrect data, so incorrect rendering is OK.

**Closed by matkoniecz** 2019-05-18 20:20 UTC

**Comment by matkoniecz** [comment] 2019-05-18 20:22
Thanks for reporting! In this case JOSM was software that become improved, not this map style but it ended improving OSM ecosystem.  Without your report (and patch by Klumbumbus) it would not happen, and probably other were confused by this situation earlier!
