### ISSUE TITLE
landuse=allotments and highway=service

### ISSUE THREAD

**Issue by luiswoo** [gravitystorm/openstreetmap-carto#1994] opened 2015-12-06 01:27 UTC
"highway = service" not visible against the background of "landuse = allotments"
mapnik: http://nadoloni.com/c/39.76004,47.46909,14/l/mapnik
mapsurfer: http://nadoloni.com/c/39.76004,47.46909,14/l/ms
http://www.openstreetmap.org/#map=14/47.4672/39.7545

**Comment by polarbearing** [comment] 2015-12-06 17:22
The smaller highways look more like tracks to me on the aerial views. Tracks are also more typical in allotments.

**Comment by luiswoo** [comment] 2015-12-07 04:42
This place is marked as it should be. "Tracks" is not acceptable in this case.

**Comment by math1985** [comment] 2015-12-07 09:10
I think you closed it accidentally :)

**Comment by polarbearing** [comment] 2015-12-07 11:05
Besides the two inaccessible-hatchings (military and prison), allotments is the only use of hatching in landuse I remember. Maybe a symbol would be better, somewhere between the random trees in forest and the regular dot grid in orchard.

**Comment by imagico** [comment] 2015-12-07 11:25
The orchard-grid would be fairly appropriate IMO.  The problem shown here is partially due to the fact that what constitutes allotments is quite variable internationally.  The wiki mentions an upper limit of 400 square meters per parcel but practically this is not usually a criterion.  With small parcels it is generally uncommon to have roads between the allotments but with larger ones it is not.

In addition to the pattern it might also be considered making allotments brighter now that farmland is much brighter - this would ensure other stuff (buildings, paths, etc.) are better visible within allotments.  Would need to take care to keep it distinguishable from farmyard of course.

**Comment by polarbearing** [comment] 2015-12-07 12:04
The size in the OSM wiki was taken straight from Wikipedia, where it is also uncited and implausible, contradicting the further analysis in the article. In OSM the range was later lowered from 50-400 to 15-400. Probably I'll going to remove that in both places.

Orchard-grid on a different colour than orchard is fine for me also, accommodating all sizes.

**Comment by luiswoo** [comment] 2015-12-07 13:30
>This place is marked as it should be. "Tracks" is not acceptable in this case.
This is "allotments" in Russian:
https://www.google.ru/maps/@47.2912585,39.6710373,3a,75y,91.81h,70.7t/data=!3m6!1e1!3m4!1sJzQP2BYALL8PXqQSENj2LQ!2e0!7i13312!8i6656!6m1!1e1?hl=ru
It is not "allotments" in Russian:
https://www.google.ru/maps/@47.229861,39.8245799,3a,75y,309.33h,85.27t/data=!3m6!1e1!3m4!1sKUosBa19t6PG3mpE25-40A!2e0!7i13312!8i6656?hl=ru
Find the differences.

**Comment by polarbearing** [comment] 2015-12-07 13:55
> Find the differences.

As you might see we are already discussing a solution to your problem. Finding games however are less productive than concise descriptions of what is typical in particular countries, people here are open minded regarding cultural differences.

**Comment by luiswoo** [comment] 2015-12-07 15:34
As you can see, it was a complement to my comment. Nothing more.
It's not my problem, it is a problem "mapnik" where the legend of "landuse=allotments" is tuned for "highway=track,path and footway" ("Tracks are also more typical in allotments" Where it is more typical? In England?). In other styles this is no problem.

**Comment by polarbearing** [comment] 2015-12-07 16:49
We want you to comment the differences, not giving us riddles as in "find the differences". 
Your example of Канатная ул. still looks like a track to me, as the aerial image suggested. 

We already recognised that the hatching pattern in this style interferes with small white roads.

**Comment by imagico** [comment] 2015-12-07 18:50
There is apparently a bit of a language problem here.  What @luiswoo is probably trying to say is that the roads are correctly classified as service roads even if they are unpaved because they are access roads to the parcels which - due to their size - are more like small farms.  These are tagged `landuse=allotments` because they are in sharp contrast with the larger corporate farms and are operated by families and individuals usually on a part time basis.  See

https://en.wikipedia.org/wiki/Household_plot

for the background.

**Comment by luiswoo** [comment] 2015-12-07 19:36
Within the city limits of Rostov-on-Don, there is no significant difference. The streets are all "allotments" included in the general list of the streets of Rostov-on-Don. Plots in the "allotments" can be designed as a place of residence. The only difference is, as shall be specified in the Land Registry (http://maps.rosreestr.ru/PortalOnline/). In one case it would be "for an individual house," in the other case it would be "for gardening" (But in fact used as a dwelling. Seasonal or permanent.).
In other cities, there is another option: to "allotments" using the internal addressing, regardless of the city.
It's hard to explain through a translator, but "allotments" is more suburban or locality than just gardens. Often with an uncertain legal status.

>What @luiswoo is probably trying to say is that the roads are correctly classified as service roads even if they are unpaved because they are access roads to the parcels which - due to their size - are more like small farms. 

not only service... http://nadoloni.com/c/30.11649,59.7921,15/l/mapnik

**Comment by polarbearing** [comment] 2015-12-07 19:51
That's all fine for me, let's focus on how to improve it. 

A PR for replacing the hatching with orchard-like dots would be quite simple, just copying the orchard.png (which is transparent already) onto allotments.png (which is coloured, but the colour is painted in the previous line already).

@luiswoo - would you want to try that and provide examples how it looks before/after?

**Comment by luiswoo** [comment] 2015-12-07 21:41
I'm for any variant, in which the roads are not merged with the background and distinguishable from it.

**Comment by BushmanK** [comment] 2015-12-07 22:26
Dot pattern, similar to orchard, with the same background color as allotments pattern currently uses (#E5C7AB) would be nice. Hatching pattern (especially - transparent one), indeed, can bring a lot of confusion. 

And regarding of what @luiswoo said above, I can confirm, that in Russia and some other ex-USSR countries, allotments, originally intended for private agricultural use only, are currently widely used for building summerhouses and even houses for permanent residence. In this way, the whole area of allotments turns into a mixed use area, combining residential and agricultural parcels and mapped by landuse=allotments due to its primary/original/main use (it's not always possible to map every parcel individually). 
Therefore, it's completely normal to have service, residential and even regular streets there.

**Comment by imagico** [comment] 2015-12-07 22:38
As @polarbearing mentioned changing the allotments pattern would be a fairly simple modification so a good opportunity for you or anyone else from the Russian community interested in working on the style to get involved.

**Closed** 2016-08-07 22:10 UTC
Labels: landcover, roads
