### ISSUE TITLE
amenity=parking rendered with two parking icons

### ISSUE THREAD

**Issue by Prince-Kassad** [gravitystorm/openstreetmap-carto#3860] opened 2019-09-01 10:24 UTC
This also seems to be related to our switch to ST_PointOnSurface.

Example: https://www.openstreetmap.org/#map=18/51.94370/13.89742

**Comment by kocio-pl** [comment] 2019-09-01 11:37
Could anyone review _all_ the changes from #3712 then in a systematic way, so we know what else can be broken?

**Comment by imagico** [comment] 2019-09-01 12:06
This is probably due to parkings being both in `amenity-points` and `amenity-low-priority-poly` - which has been the case before #3712 but did not show up because the placement was identical.

In other words: #3712 revealed a coding error that was present before.

`amenity-low-priority` and `amenity-low-priority-poly` need to be reviewed for duplicates with  `amenity-points` (and possibly merged into one layer just like `amenity-points`).

**Comment by jragusa** [comment] 2019-09-01 20:16
This also affects other features such as buildings (I guess):

https://www.openstreetmap.org/way/452206220
![bug1](https://user-images.githubusercontent.com/9897203/64081767-ad727200-cd05-11e9-9a2d-1032d7264c78.png)

https://www.openstreetmap.org/way/225166573
![bug2](https://user-images.githubusercontent.com/9897203/64081774-cc710400-cd05-11e9-9e38-ec7d44b64eee.png)

**Comment by imagico** [comment] 2019-09-01 20:37
@jragusa - this is already known, see https://github.com/gravitystorm/openstreetmap-carto/pull/3781#pullrequestreview-236378201.  In principle there is nothing wrong with displaying both building name/POI and address but in this form this is of course confusing - see https://github.com/gravitystorm/openstreetmap-carto/issues/3780#issuecomment-491362430

**Comment by pnorman** [comment] 2019-09-02 18:49
> This also affects other features such as buildings (I guess):

This has been fixed with #3781

**Comment by Grillmannen** [comment] 2019-09-04 16:52
Copied from issue 3866 referenced above:

### Expected behavior
A parking lot should only be rendered with a P once on the centroid of the area

### Actual behavior
In the example it's rendered twice with no visible data error

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/116351847
https://www.openstreetmap.org/#map=19/56.06334/12.70951
![image](https://user-images.githubusercontent.com/5609686/64205357-0d008700-ce98-11e9-81e1-0c03ff74417e.png)

**Comment by jeisenbe** [comment] 2019-09-07 00:06
Looks like we need to fix this one; lots of reports about the same problem. 

Should we merge the  `amenity-low-priority-poly` and `amenity-low-priority` layers at the same time?

**Closed** 2019-09-20 04:23 UTC
Labels: bug
