### ISSUE TITLE
tourism=apartment, is rendered different if applied to separate element or tagged together with a building

### ISSUE THREAD

**Issue by Ruediger34** [gravitystorm/openstreetmap-carto#3487] opened 2018-11-01 10:43 UTC
### Expected behavior
Render tourism=apartment on a node in the same way as on an area.

### Actual behavior

If tourism=apartment and name=XXX is set on an area, the name is renderd on zoom=17 without the icon of tourism=apartment. On zoom=18 the icon is renderd correctly.

If tourism=apartment is set as node all work as expected.

### Links and screenshots illustrating the problem
First, I will show if the tag is applied to an area.

Zoom=17, shows the name is renderd without the icon:
![grafik](https://user-images.githubusercontent.com/20127481/47705171-0d037b00-dc26-11e8-9d89-089cd2c25e93.png)

Zoom=18 is renderd correctly:
![grafik](https://user-images.githubusercontent.com/20127481/47705215-27d5ef80-dc26-11e8-9ebc-158724efb07b.png)

Second, the tag is applied to a node:
Zoom=17, nothing is visible:
![grafik](https://user-images.githubusercontent.com/20127481/47705280-58b62480-dc26-11e8-91dd-4e3ec65291cb.png)

Zoom=18, the icon is renderd:
![grafik](https://user-images.githubusercontent.com/20127481/47705288-64a1e680-dc26-11e8-96f4-6bf83887a478.png)

**Comment by matkoniecz** [comment] 2018-11-01 13:22
Very similar to #3472 

1) Can you link affected object?

2) Is this apartment really covering entire building? I would expect that either it is not filling entire house or it is not an apartment. Entire building for rent sounds like https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dguest_house

3) Is name applying also to the building or just to a rentable accommodation?

**Comment by Ruediger34** [comment] 2018-11-01 21:01
1. Tag applied to an area: https://www.openstreetmap.org/way/395066145#map=19/49.06968/13.10727 - tag applied to a node: https://www.openstreetmap.org/node/1826689349

2. I have also seen multiple tourism=apartments in one building. But in most cases it should be only one tourism=apartment in a house.

3. These names are not the name of the building. The name applies to the rentable apartment.

**Comment by matkoniecz** [comment] 2018-11-03 12:19
Closing as caused by an an invalid data.

situation 1

name tag applies only to the apartment - then there should be separate objects for apartment and building

situation 2

name tag applies to both building and apartment - then rendering is correct

**Closed by matkoniecz** 2018-11-03 12:19 UTC
Labels: amenity-points
