### ISSUE TITLE
Render suburb name on centroid

### ISSUE THREAD

**Issue by Grillmannen** [gravitystorm/openstreetmap-carto#2114] opened 2016-04-28 12:18 UTC
I'm not sure if this has already been discussed but there's an issue when suburbs are mapped as administrative borders, the suburb's name only renders on the border line, which is really not that useful.

For example, the city of Helsingborg in Sweden has been mapped with administrative boundaries that correspond to the suburbs. They are tagged like this: http://www.openstreetmap.org/relation/5525178

If zoomed in at the border of the suburb the name is shown, but one would also predict that the names of the suburbs would be shown on the map at the centroids of each respective suburb when zoomed out, like on the municipality's official map: http://kartor.helsingborg.se/stadsatlas/

Currently, the only way to solve this is to map for the renderer, that is create a separate place=suburb node in the middle of each suburb. This is something I don't want to do, but at the same time I want the suburbs to render in a meaningful way. There used to be suburb nodes instead of multipolies all over Helsingborg, but when the more detailed data was added the nodes were of course removed. In that edit for the common eye data was lost.

In the neighbouring Lund place=neighbourhood is used instead, so the same should be applicable there: http://www.openstreetmap.org/relation/4055467

Same in Malmö: http://www.openstreetmap.org/relation/3050043 together with some tagging for the renderer: http://www.openstreetmap.org/node/314525863

**Comment by pnorman** [comment] 2016-04-28 15:54
duplicate of #103

**Closed by pnorman** 2016-04-28 15:54 UTC
