### ISSUE TITLE
amenity=arts_centre name is not displayed area

### ISSUE THREAD

**Issue by olo81** [gravitystorm/openstreetmap-carto#4192] opened 2020-08-18 17:28 UTC
### Expected behavior
name display
### Actual behavior
when amenity = arts_centre is not pinned to a terrain only building no name is displayed
### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/431050062
https://www.openstreetmap.org/way/784039349

**Comment by imagico** [comment] 2020-08-18 17:57
Your issue is a bit cryptic - as it is i am inclined to close it as invalid - rendering of amenity=arts_centre was added in #2520 (against opposition i would add - candidate for #3977) and polygon fill rendering was added in #2994.

If you have a different thing in mind please clarify.

**Comment by olo81** [comment] 2020-08-18 18:39
polygon fill rendering  does not add a name

**Comment by imagico** [comment] 2020-08-18 21:35
As linked to labels are rendered for amenity=arts_centre - why it does not show up in this particular case i don't know.  Possibly the oneway arrow on the road is blocking the label here - that would make it a duplicate of #2429.

**Comment by olo81** [comment] 2020-08-18 22:52
I changed the name of this report to check which one is actually displayed

https://www.openstreetmap.org/relation/2003527

**Comment by olo81** [comment] 2020-08-19 01:36
"As linked to labels are rendered for amenity=arts_centre - why it does not show up in this particular case i don't know. Possibly the oneway arrow on the road is blocking the label here - that would make it a duplicate of #2429." 

so that was it, the name appeared

**Comment by mboeringa** [comment] 2020-08-19 07:14
> I changed the name of this report to check which one is actually displayed
> 
> https://www.openstreetmap.org/relation/2003527

Just a side note, but be aware that **type=site** relations, as the one you linked here, are handled by almost no OpenStreetMap software.

**type=site** relations are poorly defined geometrically, and a container for nodes, ways and other relations. As such, it is technically virtually impossible to do something sensible with it in rendering, and vital tools like osm2pgsql ignore them.

To be honest, I personally would drop the https://www.openstreetmap.org/relation/2003527 in favor of the much simpler closed way that is already present https://www.openstreetmap.org/way/431050062, as there are now duplicate references to what is essentially the same thing. And every reasonable person understands that all buildings within the closed way belong to the facility / arts_centre, so no real need for the added complexity of a type=site relation.

As to **type=site** relations, I only see them as a kind of "administrative" tool, to group disparate stuff together, especially disjunct (e.g. multiple campuses of a single university), allowing you to navigate them on the OpenStreetMap website by clicking the hyperlinks of the linked objects, but nothing else.

**Comment by imagico** [comment] 2020-08-19 09:17
You should of course not remove correct tagging in the data to circumvent problems with the rendering here.  In any case - this is the same problem as #2429 so closing as duplicate.  Thanks for pointing out this also occurs with symbol labels.

**Closed by imagico** 2020-08-19 09:17 UTC
