### ISSUE TITLE
No distinction between passenger and goods aerialways

### ISSUE THREAD

**Issue by martenjj** [gravitystorm/openstreetmap-carto#1557] opened 2015-05-19 08:17 UTC
There is no distinction, by colour or any other means, between aerialways which can carry passengers and those for goods alone (i.e. tagged with aerialway=goods - a disputed tag, but widely used - or foot=no).  This should be an important distinction for route planning.  It is useful to see goods aerialways on the map because they are large visible features for orientation, so they should not be hidden but need to be distinguished.

Most of the examples that I have are in Switzerland.  The official maps for that country (at medium scale) distinguish them by drawing them with a different line pattern (hopefully this is clear in ASCII!):

passenger:  ----|----|----|----|----|----|----
goods:      --- | --- | --- | --- | --- | ---

but this may not be clear at the smaller feature size that OSM uses.  I'd suggest using the same line pattern as a passenger aerialway but in a different colour - maybe the same brown as highway=track uses.

**Comment by nebulon42** [comment] 2015-05-19 09:04
Duplicate of #875. See also #889.

Bottom line was that we could not agree on the pattern and I had to close the PR due to my (back then) unfamiliarity with PRs. But I'm still interested in this. Maybe you could go ahead by providing a more concrete rendering proposal beyond ASCII art?

**Closed** 2015-05-19 09:37 UTC

**Comment by martenjj** [comment] 2015-05-19 18:56
Thanks for the pointer; apologies for the duplicate requests, but I'd looked through the list of open issues and didn't find anything relevant there.  Should have looked at closed ones too...

I'll try to do a proposal, but will have to get a test renderer working first - watch this space.

**Comment by nebulon42** [comment] 2015-05-19 19:00
#875 is still open so it may be worthwhile to continue discussing there, even if the discussion in the middle went a bit off-topic. Maybe a test setup is not yet needed, some roughly drawn input regarding pattern ideas would be great though.
