### ISSUE TITLE
waterway=stream + tunnel=flooded isn't rendered as a tunnel

### ISSUE THREAD

**Issue by Nekzuris** [gravitystorm/openstreetmap-carto#5006] opened 2024-08-21 17:54 UTC
waterway=stream + tunnel=culvert ✔️
waterway=canal+ tunnel=flooded ✔️
waterway=stream + tunnel=flooded ❌ is rendered as a normal stream, should be tunnel

**Comment by imagico** [comment] 2024-08-22 06:50
Thanks for the suggestion.

`waterway=stream` + `tunnel=flooded` is used <1000 times with many use cases clearly synonyms for the more common `tunnel=culvert`.

We render `waterway=canal` + `tunnel=flooded` with a tunnel signature since #4087, it is now predominantly and very consistently used for Qanats, which calls for addressing #3354.

Closing this as wontfix/duplicate of #3179 - since we made the decision in #4087 to selectively only support `tunnel=flooded` on `waterway=canal`.  Should tagging practice change this can be re-assessed.

As said before a more comprehensive look at the whole artificial water infrastructure domain and how to render this in a consistent and differentiated fashion would be very desirable - see in particular #3180, #3354, #4405 and https://github.com/gravitystorm/openstreetmap-carto/pull/4087#pullrequestreview-382783504

**Closed by imagico** 2024-08-22 06:50 UTC

**Comment by imagico** [comment] 2024-09-01 13:45
> I don't understand how you can defend the idea that something tagged as tunnel=* should be rendered like an open river, even if the tag has low usage.

We render tags, not keys.  And i have explained that currently `tunnel=flooded` is - in combination with `waterway=stream` - predominantly used as a synonym for `tunnel=culvert`.  I am not sure what is not understandable about that.

As said there are <1000 uses of that tag combination, there is no documentation on what this combination is supposed to mean, You have provided no example of how the tag is used in a distinctly meaningful way or a description of how you think the tag should be used that we are supposed to support with our rendering.  That IMO leaves zero basis to even consider supporting it at this time.

Regarding rendering of `waterway=canal` - we already have #3354 for that.  Contributions there are welcome, previous discussion there points into various directions where this might go.

**Comment by Nekzuris** [comment] 2024-09-01 14:15
[This](https://www.openstreetmap.org/way/1306464653#map=17/48.035972/6.982687) is a small flooded tunnel coming from a small dam that diverts part of a small stream into an artificial lake.

**Comment by imagico** [comment] 2024-09-01 14:44
I don't think it is anywhere close to global consensus to map penstocks as `waterway=stream`.  If it is in your local community then you should document that somewhere.  Right now neither the English nor the French wiki page on `waterway=stream` suggest anything in that direction.

**Comment by Nekzuris** [comment] 2024-09-01 23:10
You're right, it should be a canal because it's artificial, but since it's only a fraction of a stream less than a meter in width, the current rendering isn't appropriate. I think the tunnel is 0.3m in width.

**Comment by dch0ph** [comment] 2026-01-03 16:28
> At https://wiki.openstreetmap.org/wiki/Tag%3Atunnel%3Dflooded the difference between all 3 values are quite clearly discribed.

But it makes clear that `tunnel=flooded` is associated with `waterway=canal`. It may be that people are using `waterway=stream` because they feel that `waterway=canal` has too wide a line signature (#3354), but we definitely don't want to encourage mis-tagging for the renderer.

**Comment by imagico** [comment] 2026-01-03 17:27
The renewed discussion here is not productive, especially the attempts at wiki exegesis.

The next steps for improving rendering of waterways, in particular of artificial ones, have been described in https://github.com/openstreetmap-carto/openstreetmap-carto/issues/5006#issuecomment-2303912558.  Contributions of actual design work are highly welcome, especially on #3354.  If there is a change of mapping practice regarding use of `tunnel=flooded` on `waterway!=canal` then presenting observations in #3179 would be helpful (though i have looked and practice for `waterway=stream` has quite clearly not changed substantially).
