### ISSUE TITLE
Park name only visible at zoom level 16

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4859] opened 2023-08-12 20:33 UTC
https://www.openstreetmap.org/?mlat=42.089047&mlon=-87.7031427#map=16/42.089047/-87.7031427

**Comment by imagico** [comment] 2023-08-12 23:01
Duplicate of #3880.

Not your first i might add - #4828, #4831.  So please remember looking for existing issues already covering what you observe before opening a new one.  This saves everyone a lot of time.

**Closed by imagico** 2023-08-12 23:01 UTC
