### ISSUE TITLE
linear ways with amenity=bicycle_parking not rendered

### ISSUE THREAD

**Issue by emmexx** [gravitystorm/openstreetmap-carto#4406] opened 2021-05-18 08:35 UTC
Tagging bicycle_parking is allowed for nodes, ways and areas but only nodes and areas are rendered on the map.

Ways tagged as bicycle_parking should be rendered as the nodes or the areas are.

This is a 36 stands line that is not being rendered:
[bicycle_parking way](https://www.openstreetmap.org/way/935032718)
The area of the stands is not marked as such, there's only a line of stands, difficult to map as an area, too.

(The picture is of stands nearby the one I linked)
![curvo-rastrelliere-dietro](https://user-images.githubusercontent.com/1785010/118618485-f4e3af00-b7c3-11eb-911e-2652e484044a.jpg)

This is a 35 stands area, it is marked on the pavement, and it is rendered:
[bicycle_parking area](https://www.openstreetmap.org/way/446541102)

![rastrelliere-cattolica](https://user-images.githubusercontent.com/1785010/118618615-15136e00-b7c4-11eb-98e3-382e00595e7a.jpg)

**Comment by HolgerJeromin** [comment] 2021-05-18 09:10
[English Wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity=bicycle_parking) allows lines, while German page forbids it... :-(

**Comment by imagico** [comment] 2021-05-18 09:30
In principle i agree - and we should look in general at features we render both as nodes and polygons in amenity-points if we should also render them on linear ways.

The issue in general is that the semantics of mapping something with a linear way are more sophisticated than those of a node or a polygon because a linear way is directed.  Therefore in OSM we usually want to have a well defined rule in what direction a linear way is supposed to be drawn - like we have for waterways, cliffs/embankments and also for roads (as far as the road has direction specific properties like a oneway tag).  No such rule is currently documented for amenity=bicycle_parking despite most picycle parkings being directed (i.e. you can only park your bike from one side).

@HolgerJeromin - the wiki is not in a position to forbid anything in OSM.  The question is if the tag is practically used on linear ways or not - and the answer is in this case:  Yes, it is - not a lot but quite clearly beyond the level of only mapping errors.  And there are many cases where mapping with a linear way would be more meaningful and better verifiable than with a polygon.

**Comment by HolgerJeromin** [comment] 2021-05-18 10:24
Could be closed as a duplicate of #2711 which has already bicycle_parking in the list.

**Comment by imagico** [comment] 2021-05-18 10:56
Yes, good point.

**Closed by imagico** 2021-05-18 10:56 UTC
Labels: amenity-points
