### ISSUE TITLE
`residential=rural` should be styled same as `allotments`

### ISSUE THREAD

**Issue by skfd** [gravitystorm/openstreetmap-carto#4135] opened 2020-04-30 01:24 UTC
I often see detached houses with a garden marked as `allotments` +`residential=rural`. From one hand it looks nice and appropriately green in Carto. From the other hand it's not dachas, it's a permanent housing -- `residential=rural` should be enough.

Why not render things that look the same from satellite (lots of green + house) with same style?

![image](https://user-images.githubusercontent.com/159640/80662792-d4eb2b80-8a9a-11ea-9c30-a9f4ec6adce2.png)

**Comment by imagico** [comment] 2020-04-30 10:19
You have to be a bit more specific - for example linking the feature you think should be rendered differently and how it should be rendered.

Generally speaking our color choices are not meant to resemble actual physical appearance.  We are not aiming to create a simulated aerial imagery style.  We render landuse=residential differently from landuse=allotments because of the semantic differences for the map user, not because they physically look different.

**Comment by skfd** [comment] 2020-05-06 16:54
I agree -- only semantic difference should be a factor. And my point is that `residential=rural` is much closer to `landuse=allotments`, then it is to `residential=urban`.

`residential=rural` and `landuse=allotments` are semantically almost the same thing -- a house with some backyards.

I would also add these residential areas to be simantically grouped with allotments:
* `residential=single_family`
* `residential=detached`

They all mean the same thing.

**Comment by imagico** [comment] 2020-05-06 17:26
I see no evidence that landuse=allotments is widely used for residential areas (i.e. where people have their primary home) and i see no evidence that landuse=residential + residential=rural is widely used for areas where the primary use is non-professional gardening by individuals/families.  If there are countries or regions where this is the case please point to them.

Obviously there are always borderline cases - that is inevitable with classification systems.

**Comment by skfd** [comment] 2020-05-06 18:04
I would say in Ukraine and Russia realities all `allotments` inside the city boundary should be tagged `residential=rural`. It's a permanent housing, we have no distinct "no residing, no sleeping allowed" laws as they do in Berlin, for example.

But if I switch all these tags to `residential=rural` I would loose this sweet and helpful rendering that `allotments` have. There will hardly be any zones with this fill style at all.

**Comment by imagico** [comment] 2020-05-06 18:57
Well - this is not really the place to discuss what the right tagging is for certain things.  As said from the dominant use of tags as i can see it landuse=allotments implies private gardening as the primary use.  How this practically looks like - if there are buildings where people also sleep for example - varies. landuse=residential + residential=rural however in no way implies gardening - it just means a residential area in a rural setting or with small houses.  It is not suitable to differentiate residential areas with small houses and large gardens from other forms of small and rural housing.

Don't get me wrong - if the Ukrainian or Russian communities develop a tagging for allotments areas which also serve as permanent housing i would be open to rendering this like or similar to landuse=allotments.  But landuse=residential + residential=rural does not generally indicate this, not even in Russia - where it is also used for classic middle-class suburban housing areas with high building density and small gardens:

https://mc.bbbike.org/mc/?lon=39.014473&lat=45.013596&zoom=17&num=2&mt0=bing-satellite&mt1=mapnik
https://mc.bbbike.org/mc/?lon=39.772251&lat=47.228538&zoom=17&num=2&mt0=bing-satellite&mt1=mapnik
https://mc.bbbike.org/mc/?lon=45.03091&lat=53.212095&zoom=17&num=2&mt0=bing-satellite&mt1=mapnik

**Comment by jeisenbe** [comment] 2020-05-09 23:00
The definition of the tag `landuse=allotments` is "allotment gardens with multiple land parcels assigned to individuals or families for gardening."

In contrast, `landuse=residential` is for areas with "predominantly houses or apartment buildings."

In rural and suburban areas, it is normal that residential gardens (aka yards) will be included in this landuse area, but the tag for allotments was intended for areas that are used for gardening, not as permanent residences.

Because of this significant differences in the meaning of the two tags, landuse=residential and landuse=allotments should be distinguished with a different rendering, even if an additional tag like residential=rural is added.

**Closed** 2020-05-09 23:00 UTC
Labels: declined, landcover

**Comment by skfd** [comment] 2020-05-15 17:13
These are very good counterpoints. Thank you!

These are large areas and `allotments`-style would be a little distracting. I would still prefer them to be painted differently to indicate that this city is mainly low-rise detached housing. Just would be cool to see a difference between `rural` and `urban` are residential areas....
