### ISSUE TITLE
natural=spring rendering a z14 appears incongruous

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#4821] opened 2023-05-29 13:02 UTC
natural=spring rendering a z14 appears incongruous.

Would it not be better to render it at z16, the same as another water node feature  ford=yes?

### Screenshots with links illustrating the problem
z14
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/9528328/091395b3-d0b7-4bc2-8f06-d8cb621722eb)
z16 showing ford=yes
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/9528328/2eff0bf8-94eb-4e99-92c8-36c36834f0d7)

Ties in with #4011

**Comment by imagico** [comment] 2023-05-29 13:33
This is a duplicate of #3274/#3461.

A good solution for both springs and fords (#4000) would be to move to a non-blocking context adjusted symbology.  I have shown this can work nicely with an early starting zoom level [here](https://imagico.de/blog/en/the-way-of-the-water/) and [here](https://imagico.de/blog/en/water-under-the-bridge/).

**Closed by imagico** 2023-05-29 13:33 UTC
