### ISSUE TITLE
Render vending=parcel_pickup;parcel_mail_in

### ISSUE THREAD

**Issue by dktue** [gravitystorm/openstreetmap-carto#3558] opened 2018-12-10 14:25 UTC
In germany we have a lot of discussion about parcel services having capacity issues due to the growth of e-commerce.

One discussed solution is to have less parcels be delivered to the home directly but to other parcel pickup-locations.

The biggest parcel service in germany is DHL: Most of their parcel pickup-locations are tagged with:

[```vending=parcel_pickup;parcel_mail_in```](https://wiki.openstreetmap.org/wiki/Tag:vending%3Dparcel_pickup;parcel_mail_in)

I guess this kind of problem occurs worldwide and the people should be aware of parcel pickup-locations, hence we should render them.

**Comment by Tomasz-W** [comment] 2018-12-10 16:00
Duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/1561#issuecomment-401756335

**Comment by kocio-pl** [comment] 2018-12-10 16:11
I will close it as a duplicate, please discuss further problems in a proper ticket.

**Comment by imagico** [comment] 2021-04-14 18:30
Reopening as #1561 has been closed without support for this so it is not a duplicate.

**Comment by imagico** [comment] 2021-04-14 18:35
Current numbers:

* vending=parcel_pickup: 2800
* vending=parcel_mail_in: 326
* vending=parcel_pickup;parcel_mail_in: 6100
* vending=parcel_mail_in;parcel_pickup: 240

**Comment by dieterdreist** [comment] 2021-04-14 22:14
Am Mi., 14. Apr. 2021 um 20:36 Uhr schrieb Christoph Hormann <
***@***.***>:

> Current numbers:
>
>    - vending=parcel_pickup: 2800
>    - vending=parcel_mail_in: 326
>    - vending=parcel_pickup;parcel_mail_in: 6100
>    - vending=parcel_mail_in;parcel_pickup: 240
>
>
>
the numbers aside, this tagging does not make sense and should be
discouraged. These machines do not sell anything, or only in rare
occasions, parcel pickup and mail in are not sold at the machine, the
recipient does not pay for parcels she receives and if you pay fees, it is
not for parcel mail in but for sending the parcel somewhere, but most are
parcel pickup boxes where you do not buy anything i.e. the machine is not a
vending machine and "vending" is not a suitable key.

**Comment by Tomasz-W** [comment] 2021-04-21 06:22
Just for the note: my icon proposal from 2018.

![vending parcel](https://user-images.githubusercontent.com/25656654/42159143-fe76efa4-7df2-11e8-93f6-3119170201d7.png)

Gist link: https://gist.github.com/Tomasz-W/18032cc646055bf17b866cb4eb48fa48

**Comment by ttomasz** [comment] 2021-11-04 22:51
I launched a proposal to change the tagging https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_lockers
Comments welcome. Currently discussion is mainly about whether restricting parcel lockers to nodes is valid or should we allow mapping them as areas.

**Comment by xsuchy** [comment] 2021-11-17 09:07
We have recently imported 1300 parcel_pickups using this tagging schema
  https://wiki.openstreetmap.org/wiki/Tag:vending%3Dparcel_pickup
An example is here  https://www.openstreetmap.org/node/9172378855
Having it rendered at the same level as post boxes will be nice.

**Comment by dieterdreist** [comment] 2021-11-19 18:06
Am Mi., 17. Nov. 2021 um 10:07 Uhr schrieb Miroslav Suchý <
***@***.***>:

> We have recently imported 1300 parcel_pickups using this tagging schema
> https://wiki.openstreetmap.org/wiki/Tag:vending%3Dparcel_pickup
>


that's perfectly fine for those that ask for a fee in order to use them.
Vending machine is for machines selling services and or goods.

**Comment by ttomasz** [comment] 2021-12-15 00:58
Voting for proposal: https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_lockers started

**Comment by ttomasz** [comment] 2021-12-20 23:45
Proposal was reworked due to high number of opposing votes being against a "machine" in the tag. New vote started: https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_locker

**Comment by ttomasz** [comment] 2021-12-28 23:44
Looks like the proposal is going to pass so I think we can start thinking on how to render the feature. Since this is a new tag it doesn't matter when exactly it will be implemented in carto i.e. it can be added before features are retagged from old tags since they are not rendered right now anyway.

There are two options so far:
A. icon from @Tomasz-W : 
![image](https://user-images.githubusercontent.com/31594210/147615061-f6e9512a-d370-4873-867d-131003c66793.png)
 https://gist.github.com/Tomasz-W/18032cc646055bf17b866cb4eb48fa48
B. icon from iD: 
![image](https://user-images.githubusercontent.com/31594210/147615085-67a24dc9-dbb3-4946-baf3-7997221a6163.png)
 https://cdn.jsdelivr.net/gh/ideditor/temaki/icons/vending_lockers.svg
Which would be better?

Additionally should other stuff be rendered like "ref"?

**Comment by xsuchy** [comment] 2021-12-29 12:07
I vote for A.
ref is usually some internal number, which has no meaning for the public.  I think the name can be rendered and if not present then the operator.

**Comment by mutipg** [comment] 2021-12-29 12:19
I also vote for the A icon

When it comes to 'ref' rendering, it's not a bad idea, as it's the only ref that distinguishes devices that sometimes stand close together. Receiving parcels requires finding a specific parcel locker of a given operator, not as in the case of, for example, an ATM, where we can use any device of the operator you are looking for.

Rendering the description of parcel machines could look like this:
```
operator (if the tag operator is missing then name)
ref
```
i.e.
```
InPost
BAN1702N
```

**Comment by xsuchy** [comment] 2021-12-29 21:59
Here is the example from my country
  https://www.openstreetmap.org/node/9172378855
the `ref=11208` the number tells you exactly nothing. It is just a number referencing the ID in the operator DB (they share their DB with OSM with explicit agreement).

**Comment by ttomasz** [comment] 2021-12-29 23:59
Here is an example from Polish operator who put two machines next to each other:
https://inpost.pl/paczkomat-warszawa-waw57a-grojecka-paczkomaty-mazowieckie
https://inpost.pl/paczkomat-warszawa-waw194ap-grojecka-paczkomaty-mazowieckie
![image](https://user-images.githubusercontent.com/31594210/147711236-f8a065dd-32e1-4ecb-b3d3-196aef213c36.png)
Currently only one of them is in osm: https://www.openstreetmap.org/node/3718207074#map=19/52.20092/20.96930
but these IDs are shared with the user, example from e-mail informing of package:
![image](https://user-images.githubusercontent.com/31594210/147711445-572ea1e3-1877-4c48-a69a-8e55c9bcd99f.png)
(In the picture there is: id, city, address, description of location.)

These ids can potentially be useful depending on operator. I'm not trying to push this one way or the other, just wanted to provide an example to what @mutipg  wrote.

**Comment by starsep** [comment] 2022-01-03 23:36
I prefer icon A. It's easy to see the package (box).
I think an average person wouldn't know what icon B shows unless given some hint. 
It looks like an electronic device (?) at first glance.

Rendering `ref` would be useful in Poland (as mentioned already): InPost (the most popular operator) puts multiple machines next to each other and it allows to differentiate them.

**Comment by ttomasz** [comment] 2022-01-07 01:05
The proposal has been approved.

Seems like there is consensus to go for icon A.

@Tomasz-W the icon comes from https://thenounproject.com/icon/package-34255/ right?
Did you get it with paid licence which doesn't require attribution (and would allow us to use it) or free version which requires visible author attribution (which would mean we can't use it)?

**Comment by pnorman** [comment] 2022-01-07 03:10
> Did you get it with paid licence which doesn't require attribution (and would allow us to use it) or free version which requires visible author attribution (which would mean we can't use it)?

OpenStreetMap Carto is CC0. We can't use icons under any other terms.

**Comment by kuba-medrek** [comment] 2022-01-10 00:22
Would it be possible to add small arrow "in" icon on lockers tagged with [parcel_mail_in](https://wiki.openstreetmap.org/wiki/Key:parcel_mail_in) and "out" icon on [parcel_pickup](https://wiki.openstreetmap.org/wiki/Key:parcel_pickup)?

Wouldn't it be better to render `brand=*` instead of `operator=*`?
I assumed following tagging example:

    amenity=parcel_locker
    brand=DHL Packstation
    brand:wikidata=Q1766703
    brand:wikipedia=de:Packstation
    operator=DHL
    parcel_pickup=yes
    parcel_mail_in=yes
    ref=1234

What about rendering `brand` (fallback to `operator`, fallback to `name`) and `signed_ref` in bottom line (if present)? That would be most consistent with whole tagging scheme I believe.

**Comment by ttomasz** [comment] 2022-01-13 18:15
> OpenStreetMap Carto is CC0. We can't use icons under any other terms.

Okay, I clarified with Tomasz-W and this is icon that he created specifically for this purpose so licensing wise it's good.
New cleaned up file: https://gist.github.com/Tomasz-W/2d384de0d06e1991f449f5439320d0e8

I propose to use this icon as everyone above was in favour of it and then add text below if data from tags available:
1. brand or operator or name
2. ref

**Comment by Tomasz-W** [comment] 2022-01-20 15:06
@Adamant36 Do you still remember how to write code for new icons? :sweat_smile:  Would you like to help with adding this element to map?

**Comment by Adamant36** [comment] 2022-01-21 18:41
> @Adamant36 Do you still remember how to write code for new icons? 😅 Would you like to help with adding this element to map?

Probably. I'd have to setup the environment again though and I'm sorta on a break anything related to OSM at the moment. Although I've been meaning to set things up for #4146. I can work on this whenever I get around to that issue if no one else does it in the meantime.

**Comment by imagico** [comment] 2022-01-30 19:34
Updated use numbers (compare to https://github.com/gravitystorm/openstreetmap-carto/issues/3558#issuecomment-819743737):

* vending=parcel_pickup: 5776
* vending=parcel_mail_in: 285
* vending=parcel_pickup;parcel_mail_in: 11980
* vending=parcel_mail_in;parcel_pickup: 245

As mentioned in #4512 - the symbol designs discussed so far do not really work.  As said there: *When you want to illustrate infrastructure for human interaction the most intuitive symbol is often coming from illustrating the human activity itself. And perspective is not typically going to work well at our standard symbol size, we therefore with good reason mostly use profile depictions in our symbol designs.*

To try providing a bit of a teaching moment here a draft based on this paradigm:

![package_plain.svg](https://imagico.de/files/package_plain.svg) https://imagico.de/files/package_plain.svg

Feel free to experiment with different design ideas - this is not meant to say that only this concept has a chance to be accepted.  But you need to put some thought and ambition into it - not just take some design from elsewhere, maybe even from a non-map context, and assume this will just work in a map for an international audience like this.

**Closed** 2022-07-29 02:27 UTC
Labels: new features, POI
