### ISSUE TITLE
Placenames are not rendered when places are areas e.g. (place=village)

### ISSUE THREAD

**Issue by stevenLAD** [gravitystorm/openstreetmap-carto#2792] opened 2017-09-01 11:37 UTC
If an area is marked as a village and named, the name does not show in the main osm map (but does show in, for example, the cycle map.

In project.mml at line 1311, it appears to only pull place names from the points database (and not the polygon db). 

Without fulling understanding the code, it would seem based on similar areas, that if this restriction was removed, that village place names would be correctly rendered.

**Comment by matkoniecz** [comment] 2017-09-01 13:48
duplicate of #103

**Closed by matkoniecz** 2017-09-01 13:48 UTC
Labels: cartography
