### ISSUE TITLE
Render building housenumber for building:part too

### ISSUE THREAD

**Issue by jengelh** [gravitystorm/openstreetmap-carto#2133] opened 2016-05-27 13:41 UTC
Please consider rendering the house number of "building:part=*" objects the same way it is done for "building=*" objects.

Rationale:
Sometimes, a row of independent-but-edge-sharing houses have a visually matching roof pattern. When this pattern happens to be one of those which lose their symmetry if cut in half (as it happens with "hipped"), the row is converted to building:part=, and a superimposed OSM building=* is added for the sake of the roof. When that is done, the house numbers rendered on the standard map disappear.

**Comment by matkoniecz** [comment] 2016-05-27 14:31
duplicate of #1746

**Closed by matkoniecz** 2016-05-27 14:31 UTC
