### ISSUE TITLE
Rendering: railway=tram and highway=* on bridges

### ISSUE THREAD

**Issue by cyper85** [gravitystorm/openstreetmap-carto#1322] opened 2015-02-19 19:49 UTC
Tram-lines are rendered over highwaylines on ground . But on bridges (both ways included the tag bridge=yes), the road is rendered over the tram.

Can you fix the layer, so trambridges are rendered over road-bridges?

[Example](http://www.openstreetmap.org/way/194083416#map=19/50.92851/11.59543&layers=N)

**Comment by cyper85** [comment] 2015-02-19 19:55
OK, the problem of the rendering in this example was: The highway-bridge uses layer=1 but not the tram-bridges. I fixed it.

Now you see an gap between the Tram-Bridge and the tramlines on ground.

**Comment by polarbearing** [comment] 2015-02-19 20:24
http://www.openstreetmap.org/#map=18/52.45987/13.51452 has a situation where the road is layer=1 and the tram is layer=2. Still at the ends there are gaps in the railway line. 

Another example with a different highway type. Bridge tag on tram freshly fixed:
http://www.openstreetmap.org/#map=18/52.44849/13.57481&layers=N

**Comment by mboeringa** [comment] 2015-02-19 21:43
> Now you see a gap between the Tram-Bridge and the tramlines on ground.

> Still at the ends there are gaps in the railway line.

This is a known and pretty much unsolvable issue. It has to do with the way how casing of lines must be rendered, the fact that bridge symbols are always drawn over road and tram lines of the same layer in carto, and the interior of a line needing a rounded edge to ensure proper connectivity of line elements. This rounded edge hence overlaps the tram lines at a lower *and equal* layer number. @math1985 explained this in detail in the below linked issue.

There is pretty much no solution for this, because removing the rounded edge would cause much worse issues with *apparently* unconnected or broken casings and lines.

Rendering tramlines on top of everything ignoring layer altogether, would be another bad solution, as it would cause tramlines no longer obeying underpasses below bridges etc...

So this is a trade off between a minor issue with tramlines on top of road lines, or more serious visual issues with road and railway lines in general.

This issue is not unique to openstreetmap-carto. It is a rather generic issue with cased lines, similar issues are also seen in GIS's like ArcGIS for Desktop or QGIS.

For your reference, see the rather lengthy discussion in this issue ticket:
**gap in rendering when moving from a highway+railway to a highway+railway+bridge**
https://github.com/gravitystorm/openstreetmap-carto/issues/934

**Comment by mkoniecz** [comment] 2015-02-19 22:05
Duplicate of #934

**Closed by mkoniecz** 2015-02-19 22:05 UTC
