### ISSUE TITLE
Rendering of railway=platform + public_transport=platform + light_rail=yes + area=yes

### ISSUE THREAD

**Issue by jc86035** [gravitystorm/openstreetmap-carto#3242] opened 2018-05-21 17:08 UTC
### Expected behavior
The platforms, given that they have the four tags, should render
### Actual behavior
Platforms don't render at z19 (either a tile caching issue, or an issue with light_rail not being styled, or something about railway=platform)
### Links and screenshots illustrating the problem
[The platform](https://www.openstreetmap.org/way/161558800)

**Comment by Tomasz-W** [comment] 2018-05-21 17:12
Duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/435

**Comment by jc86035** [comment] 2018-05-21 17:13
@Tomasz-W this is not the same issue; the issue is that railway=platform stopped rendering, and I don't know why

**Comment by kocio-pl** [comment] 2018-05-21 22:05
That's because it has `covered=yes` tag, see #3162.

**Comment by kocio-pl** [comment] 2018-05-21 22:30
Compare it also with other covered platform, which has a cover (building) tagged:

https://www.openstreetmap.org/way/220343050

**Comment by jc86035** [comment] 2018-05-22 04:30
Are the platforms tagged incorrectly? They are entirely covered by a canopy but perhaps using shelter=yes instead would be appropriate.

**Comment by kocio-pl** [comment] 2018-05-22 10:39
Interesting case. This was my design decision to hide covered platforms, because this usually means being under the roof and that makes clutter. Covered roads are treated like tunnels IIRC, so we treat the cover as something solid. See also: https://wiki.openstreetmap.org/wiki/Key%3Acovered

**Comment by kocio-pl** [comment] 2018-05-22 12:31
Probably `covered=trees` would be both accurate and rendering as expected.

**Closed** 2018-05-22 12:40 UTC
Labels: roads

**Comment by jc86035** [comment] 2018-05-22 12:55
@kocio-pl [Not a tree canopy, a metal one](https://upload.wikimedia.org/wikipedia/commons/0/04/LRT_Tong_Fong_Stop.JPG) (although there are trees next to it). Should I remove the covered=yes tag from the 140 or so platforms which have the same sort of metal shelter?

**Comment by kocio-pl** [comment] 2018-05-22 12:57
Oh, I see. I guess adding this shelter (looks like `building=roof` to me) is the right way.

**Comment by jc86035** [comment] 2018-05-22 12:58
Should that tag be on the same way as the platform, or should a new area with the same nodes have that tag?

**Comment by kocio-pl** [comment] 2018-05-22 13:01
I think new area, since it's probably not exactly the same shape.

**Comment by kocio-pl** [comment] 2018-06-01 13:31
Another possibility is to use `covered=partial`in some cases:

https://taginfo.openstreetmap.org/tags/covered=partial

**Comment by jc86035** [comment] 2018-06-01 13:35
Out of interest, is it possible in Mapnik to only render parts of a multipolygon? (For the case where an object is partly under a building, and the bits outside the building are separate ways without covered=yes. Platforms with a single ref=* cannot be split into multiple ways/areas, since the label should only be rendered once in the middle of the platform.)

**Comment by jc86035** [comment] 2018-06-01 13:37
On second thought, it would be fairly difficult to render the label sensibly if the middle of the platform were invisible.
