### ISSUE TITLE
Show `brand` for `amenity=fuel` and `shop=*`

### ISSUE THREAD

**Issue by marioxcc** [gravitystorm/openstreetmap-carto#4838] opened 2023-07-15 05:25 UTC
Currently the brand is not shown. I duplicate the same information on `name` just to make it show in OSM Carto.

**Comment by imagico** [comment] 2023-07-15 11:37
Thanks for the suggestion, this is a duplicate of #1874 for `amenity=fuel`, of #698 regarding `shop=*`.

See also #4575 and #4629 regarding additional context of brand labeling in this style.

**Closed by imagico** 2023-07-15 11:37 UTC

**Comment by marioxcc** [comment] 2023-07-15 16:45
How do you suggest we tag fuel stations and shops?

**Comment by imagico** [comment] 2023-07-15 17:54
What my preferred tagging scheme would be is not of interest here. What you indicate to do, recording a brand (a class identifier selected by a business for marketing purposes, as discussed in https://github.com/gravitystorm/openstreetmap-carto/issues/4575#issuecomment-1158651857) in the name tag (which by wide consensus records a _proper name_ of the feature in question) is not a good idea.

 The question if and how we should label features in OSM-Carto, especially also features which might not have a proper name (`noname=yes`) needs to be discussed for the specific features and that is a matter for the issues i linked to.
