### ISSUE TITLE
Render highway=busway

### ISSUE THREAD

**Issue by andrepoiy** [gravitystorm/openstreetmap-carto#4376] opened 2021-04-17 16:37 UTC
A new tag of highway=busway, which is used to tag Bus Rapid Transit Lanes, has been approved on the OSM Wiki. I have noticed that it does not render on OSM.

https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbusway

### Expected behavior
Render something

### Actual behavior

Nothing renders

### Links and screenshots illustrating the problem

There's a busway in the middle of Highway 7 here, which no longer renders after this new tag is added. 

![image](https://user-images.githubusercontent.com/47615278/115120091-a8fdda00-9f79-11eb-899f-81f69ff6196b.png)
https://www.openstreetmap.org/#map=18/43.84081/-79.39879&layers=N

**Comment by imagico** [comment] 2021-04-17 17:33
Duplicate of #4226.

**Closed by imagico** 2021-04-17 17:33 UTC
