### ISSUE TITLE
Wrong highway color at intersection at tile boundary

### ISSUE THREAD

**Issue by andrewguertin** [gravitystorm/openstreetmap-carto#2425] opened 2016-11-02 00:49 UTC
At http://www.openstreetmap.org/#map=18/43.47736/-72.39731 where Ascutney Street transitions from secondary to residential, there is a slight miscoloration. The road's fill color is the same as the tile background (or maybe transparent?) instead of white.

The tile in question is http://a.tile.openstreetmap.org/18/78354/95847.png . I marked it as dirty to force re-rendering, with no change.

![intersection-color](https://cloud.githubusercontent.com/assets/957407/19912808/b4005fb8-a073-11e6-9a63-3a3ece178b0f.png)

**Comment by pnorman** [comment] 2016-11-02 01:01
I was initially suspecting this was a case of PNG quantization leading to an odd colour for a shade that is not used often in the metatile (#1940), but there are so few colours in the tiles this seems odd so it might be something else.

**Comment by sorcrosc** [comment] 2016-11-02 01:52
See here too:
http://www.openstreetmap.org/#map=19/43.70138/12.97895

**Comment by andrewguertin** [comment] 2016-11-06 06:22
Interesting things about sorcrosc's link:

a) It shows up in two different places both visible from that link: most obviously at the end of the service road the map is centered on, but also at the southern end of the parking aisle southwest of the first place

b) It shows up at multiple zoom levels (both 18 and 19) for at least one of the places.

**Comment by kocio-pl** [comment] 2016-11-15 17:26
I don't see this bug in either locations. Could somebody else confirm it?

**Comment by pnorman** [comment] 2016-11-16 23:58
> I don't see this bug in either locations. Could somebody else confirm it?

I still get it. The tile in question is http://orm.openstreetmap.org/18/78354/95847.png for me

**Comment by kocio-pl** [comment] 2016-12-15 02:00
Rendering local current data with current master shows no such problem on z18:
![ggoamk8e](https://cloud.githubusercontent.com/assets/5439713/21209088/7c8342be-c272-11e6-96e8-5f49d05b9ebe.png)

Looks like it's a server problem.

**Comment by kocio-pl** [comment] 2016-12-15 03:09
Looks similar to https://github.com/gravitystorm/openstreetmap-carto/issues/1940 - I think it's a duplicate, so I would close it.

**Comment by pnorman** [comment] 2016-12-15 03:11
> Looks similar to #1940 - I think it's a duplicate, so I would close it.

That's what I initially thought, but

> I was initially suspecting this was a case of PNG quantization leading to an odd colour for a shade that is not used often in the metatile (#1940), but there are so few colours in the tiles this seems odd so it might be something else.

The way to test this is to reproduce it locally with png256 and then see if changing to png fixes it.

**Comment by kocio-pl** [comment] 2016-12-15 03:15
Do you mean [this option in project.mml](https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L14)?

**Comment by pnorman** [comment] 2016-12-15 04:39
> Do you mean this option in project.mml?

Yes. It is possible kosmtik overrides format, but I don't *think* so.

**Comment by kocio-pl** [comment] 2016-12-18 05:42
There is an export format option in Kosmtik, which should override this value, but choosing png256 there (and also in `project.mml`) still shows no sign of this problem locally on z18:
![popogusm](https://cloud.githubusercontent.com/assets/5439713/21291750/4788573a-c4ec-11e6-9117-5bb9e78da301.png)

Do you think we can close this issue too (as in https://github.com/gravitystorm/openstreetmap-carto/issues/1940#issuecomment-267228885)?

**Comment by pnorman** [comment] 2016-12-18 08:41
> Do you think we can close this issue too (as in #1940 (comment))?

It *might* not be a duplicate of that, but probably is.

Even if it isn't, the severity of it, difficulty reproducing it, and low number of people who can debug something like this mean that I'm closing it anyways

**Closed by pnorman** 2016-12-18 08:41 UTC
Labels: bug, roads
