### ISSUE TITLE
The tallest buildings in the world... but who would know?

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3552] opened 2018-12-06 21:49 UTC
After examining Ferris wheels (#3550), let's move on to...
(you can't get much bigger:) skyscrapers.
https://en.wikipedia.org/wiki/List_of_tallest_buildings

- The Empire State Building, but who would know?
https://www.openstreetmap.org/way/34633854#map=18/40.74857/-73.98491
You have to zoom to highest zoom level to even see its name.

And what taller than...
- https://www.openstreetmap.org/way/137153127#map=19/25.19703/55.27422
"York University"?!?
(Well there is a "BK" there, Burger King one would think.)

And who would guess
- https://www.openstreetmap.org/way/165792123
is the second tallest building in the world?
Might as well be some ho-hum one story warehouse in some industrial district.

Ah, finally at rank fourth do we see something I'm happy with,
- https://www.openstreetmap.org/way/535860513
apparently the key is the "tower" tag.

Conclusions:
1. The mapper people need to use the right tags.
2. The right tags (what ever they are) need to be documented.
3. Maybe there should be a skyscraper icon, since it is even bigger than a Ferris wheel.

References:
1. https://wiki.openstreetmap.org/wiki/Key:building
2. https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dtower

**Comment by jeisenbe** [comment] 2018-12-06 22:18
I don’t believe there is a tag for “skyscraper”. You may want to discuss
this on the Tagging mailing list.

How would you suggest to display tall buildings?

We can’t do actual 3D.

We could try to display the name labels at earlier zoom levels, but most
tall buildings are in dense commercial or retail areas with many map
features, so the name of the Empire State Building would might be blocked
by other features.

Icons are normally used for specific tags, and there doesn’t seem to be one
for tall office or mixed-use buildings. As mentioned, we have a tag and
icon for man_made=tower, but whether this can. be used for tall office
buildings is debatable. This could also be discussed at the Tagging mailing
list first.

(We currently render man_made tower at lower zoom levels based on height
because they can be useful for orientation in rural areas. If the tag was
used for many tall buildings on city centres we would probably need to
remove the rendering from z14 and z15)

**Comment by polarbearing** [comment] 2018-12-07 00:13
OSM has 3D tags, and there are maps specialised in 3d-rendering. 

This style is a 2D map.

**Comment by matkoniecz** [comment] 2018-12-07 00:41
This map style is not focused on showing labels of high objects so it is not issue by itself.

More generally it is really hard to decide whatever building label is more important than amenities inside.

Can you propose any reliable method of checking whatever building name is worth displaying earlier than names of other buildings of a similar footprint?

**Comment by kocio-pl** [comment] 2018-12-07 00:42
> I don’t believe there is a tag for “skyscraper”. You may want to discuss this on the Tagging mailing list.

I think this is the first step toward different rendering. There are some buildings with such value, but none of them is documented and the usage is very low (28 and 32 respectively) and the problem is that this is not just one:

https://taginfo.openstreetmap.org/tags/building=skyscraper
https://taginfo.openstreetmap.org/tags/building%3Atype=skyscraper

**Comment by matkoniecz** [comment] 2018-12-07 00:55
building=skyscraper seems really incorrect.

It is likely that building=office/apartments or other l would be correct (buildings are unlikely to be built just to build a skyscraper).

I thank that better way to find skyscrapers would be to look for building with high value in building:levels tag

But anyway it would be better to discuss it on tagging mailing list.

**Comment by Adamant36** [comment] 2018-12-07 04:10
@jeisenbe, what exactly is the issue with rendering buildings based on height that you referenced above? I might be against it, but it seems like the only practical option. There might be something else like building:levels, but what if the building has only one level but a really tall ceiling, like a cathedral or ampitheater?

**Comment by jeisenbe** [comment] 2018-12-07 04:39
How would you render them differently?

Use a darker color fill, like places of worship and airport terminals?

Use an icon?

**Comment by Tomasz-W** [comment] 2018-12-07 08:29
We shouldn't make any category and special rendering of skyscrapers - as I live in Poland, for me 100m tall building is a skyscraper, but for someone from e.g. Dubai, it would be propably just a regular building. So it would be not clear. Another thing is that if we focus on objects shapes instead of their functions, map would look like this:

![](http://3.bp.blogspot.com/-x2LYoAmzFp8/VFDucg0tneI/AAAAAAAAHvU/Weu6zxqtgpg/s1600/mapa_end.jpg)

**Comment by Adamant36** [comment] 2018-12-07 12:59
All good points @Tomasz-W's makes. Although we already render some things by height. But doing it also with buildings might be a bad idea. Looking over places you would have to start at like 14 or more likely z15 for it work, but normal buildings are already being rendered at those levels. Normal buildings could be removed from z15 and start at z14, but I think it was already discussed and shot down. If its a possibility though, there's still other things to work out. Like the fact that wider, but shorter buildings wouldn't be rendered anymore at z15, Although they might be just as important,  because there isn't a comparably width tag. Also it might conflict with how major and minor buildings get rendered. If they ever do. 

Instead, different fill color might work like was (is?) being tested for major and minor buildings. Then there could be three different buildings colors, minor=lighter, major=darker, skyscraper(or whatever)=darker then major. That would probably complicate things quit a lot though. 

As a side to that, I've tweaking around with different water colors based on the type of water feature. It seems like a good idea and might look good or help mapping, but it introduces some rendering problems I don't think are fixable, and after like 2 variations it gets hard to keep track. I think the issue would happen here. So, in my opinion it would be better just to go with major/minor building rendering based on color shades, include these in there, and leave it at that. Unless there's a better to do it I'm not thinking about.

**Comment by kocio-pl** [comment] 2018-12-07 14:09
Since there are multiple problems with this proposition, I will close this ticket now. We lack tagging solution first of all, so this should be where it all may start.

**Closed by kocio-pl** 2018-12-07 14:09 UTC
Labels: buildings, text

**Comment by jidanni** [comment] 2018-12-08 06:47
At least building names and address numbers should always have priority over the stuff inside (or minor stuff next to, #3435) the building.

**Comment by HolgerJeromin** [comment] 2018-12-08 07:31
This would hide many shops. Not ideal either

**Comment by matkoniecz** [comment] 2018-12-08 07:35
That in turn would make objects inside tall objects be always hidden.

**Comment by jidanni** [comment] 2018-12-08 10:10
Okay, but when should a shop name cause the words Empire State Building to disappear?

**Comment by Adamant36** [comment] 2018-12-08 10:55
The way the code works there's no practical way to make a single exception. You'd either have to display all building names before shops or not  There's currently 4.6 million building with the name tag. id guess 99% of those aren't notable. Probably a good number are also miss-tagged. In most cases the name of the building is way less important to the names  of the businesses in the building. Let alone displaying building names first would also cover the specific icons. Same goes for addresses.

**Comment by jidanni** [comment] 2018-12-08 12:15
Okay, but have a look how Google Maps handles the Empire State Building. Looks great to me, through most if not all zoom levels.

**Comment by Adamant36** [comment] 2018-12-08 13:03
Google Maps doesn't use CartoCSS. So it can handle rendering priority better. Plus, having a team of like 5,000 developers, versus a few volunteers here, probably helps.

**Comment by Adamant36** [comment] 2018-12-08 14:47
That could be it also.

**Comment by Adamant36** [comment] 2018-12-08 17:43
Can you provide a link to where that happens?

**Comment by jidanni** [comment] 2018-12-08 21:51
@Adamant36 Observe the [two mirrored C shaped buildings](https://www.openstreetmap.org/?mlat=24.78695&mlon=120.99705#map=18/24.78695/120.99705). We note that the [right one](https://www.openstreetmap.org/way/134752749) has its name wiped out thanks to a drinking fountain, whereas, at the same zoom level, [the left one](https://www.openstreetmap.org/way/134752750) is unscathed.

**Comment by Adamant36** [comment] 2018-12-08 23:20
That sucks. It might because the drinking fountains have names that are blocking the other stuff. Especially if they are two lines. As a side note, as far as know things aren't suppose to be named what they are. They aren't suppose to contain descriptions or the type of the item. See https://wiki.openstreetmap.org/wiki/Names "Name is the name only" section.

**Comment by jidanni** [comment] 2022-12-13 15:57
Checking again today with towers:

- https://www.openstreetmap.org/search?query=Eiffel%20tower needs zooming, but name eventually shows up.
- https://www.openstreetmap.org/search?query=Tower%20of%20London Same.
- https://www.openstreetmap.org/search?query=Sutro%20Tower due to antennas perhaps, name alas  never shows up no matter what zoom level. Looks good on OSM France though.
- https://www.openstreetmap.org/search?query=Leaning%20Tower%20of%20Pisa name shows up right away. Good.
