### ISSUE TITLE
Render tower/mast nodes at different zoom levels according to height if present

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#2024] opened 2016-01-18 10:35 UTC
Hello, there.

I had an idea, but I don't know if it would be desirable or practical : the main use for communications masts and tower, IMHO, is for orientation in open field. Currently, the rendering of these features begins at the same zoom level, regardless of their height, but, for orientation purpose, a 300m tall tower is useful on a much wider area than a 25m tall one. Wouldn't it be great if the zoom level for rendering these was selected according to their height ? By making taller masts appearing at lower zoom levels than shorter ones, the displayed set of these objects would be more fitted to the use of the map at the different zoom levels.

I must add that I don't know or am not sure about the following criterias:
- which tag combinations are currently displayed as a communication tower, as the modelling of these features is quite confusing to me;
- if such differentiated rendering could be technically practical or would complexify rendering or code;
- how to render them when their height wasn't modelled — at a default zoom level? at the lower one? the higher one?
- if the height of these structures is given often enough for this differentiated rendering to be effective;
- if this idea could be useful for other features like trees or peaks.

Hope this can help to improve the rendering.

Regards.

**Comment by dieterdreist** [comment] 2016-01-18 11:08
2016-01-18 11:35 GMT+01:00 Penegal <notifications@github.com>:

> I must add that I don't know or am not sure about the following criterias:
>
>    - if such differentiated rendering could be technically practical or
>    would complexify rendering or code;
>
>
any differentiation is augmenting complexity, here the main problem will
likely be units: while most of height data is likely entered in meters,
there are also a lot of values in feet or other units. E.g.
http://taginfo.osm.org/search?q=height%3Dft (another common notation is '
).

>
>    - how to render them when their height wasn't modelled — at a default
>    zoom level? at the lower one? the higher one?
>
>
the higher (number) one.


>
>    - if the height of these structures is given often enough for this
>    differentiated rendering to be effective;
>
>
the higher ones will likely already bear this information, and as soon as
we start interpretating it people will quickly add the missing ones.


>
>    - if this idea could be useful for other features like trees or peaks
>
>
for trees there are other tags to explicitly state importance and for peaks
there are also other properties more relevant than absolute heights
(prominence and topographic isolation)

**Comment by Tomasz-W** [comment] 2018-03-08 14:33
Actualy, we have discussion about towers/masts and certain zooms in https://github.com/gravitystorm/openstreetmap-carto/pull/2671#issuecomment-370700507

This issue should be closed as duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/2556, or be referenced with "Resolves" line to https://github.com/gravitystorm/openstreetmap-carto/pull/2671#issue-128854828

@kocio-pl ?

**Comment by kocio-pl** [comment] 2018-03-08 14:37
Thanks for spotting these all tickets! I think we should continue where the real work is and this ticket is too general (it was open before I started working with actual code), so I referenced it with _Resolves_.

**Closed** 2018-03-13 14:36 UTC
Labels: amenity-points
