### ISSUE TITLE
Relation name ends up 60 km south of the relation.

### ISSUE THREAD

**Issue by anderfo** [gravitystorm/openstreetmap-carto#2881] opened 2017-10-06 18:36 UTC
Here's the relation: https://www.openstreetmap.org/relation/1419087
However, the label ends up 60 km south of it: https://www.openstreetmap.org/#map=11/62.9245/9.8637

The name is green and belongs to a natural=wood relation. There's only one such relation named "Bymarka" in OSM, according to taginfo and overpass...

**Comment by pnorman** [comment] 2017-10-06 19:34
Duplicate of #1465

**Closed by pnorman** 2017-10-06 19:34 UTC
