### ISSUE TITLE
Golf Course Icon Displayed Instead of Outer Sports Centre

### ISSUE THREAD

**Issue by cwmke** [gravitystorm/openstreetmap-carto#4184] opened 2020-07-29 17:56 UTC
### Expected behavior
The leisure=sports_centre name and icon is displayed.

### Actual behavior
Unnamed icon for leisure=golf_course located within the sports centre is displayed.

### Links and screenshots illustrating the problem
**Standard Open Streetmap** - https://www.openstreetmap.org/way/28487558
**OSM France** - https://tile.openstreetmap.fr/?q=milwaukee%20country%20club

![MCCosmcarto](https://user-images.githubusercontent.com/1923967/88835348-bb8d7480-d19a-11ea-8ad4-7dfac7fee8dd.png)
![MCCosmfr](https://user-images.githubusercontent.com/1923967/88835304-b03a4900-d19a-11ea-968f-9221c65af78d.png)

**Comment by jeisenbe** [comment] 2020-08-04 00:50
This feature was recently edited to create a separate leisure=golf_course multipolygon, which does not have a name: https://www.openstreetmap.org/relation/11363289#map=16/43.1643/-87.9377

This style is displaying the icon for the golf course, but because there is no name tag on the relation, no name is rendered.

There is also a slightly larger area which is tagged with leisure=sports_center and has the name (and some other tags are duplciated, like architect=, phone=, fax=, etc). However this name appears to be blocked by collision with the golf course icon at some zoom levels, since it is nearly the same shape:

The name label still renders at z14:
<img width="611" alt="Screen Shot 2020-08-03 at 17 48 09" src="https://user-images.githubusercontent.com/42757252/89240629-8aa1ab00-d5b1-11ea-8488-cd31ac73205e.png">

But at z15 we get only the icon:
<img width="623" alt="Screen Shot 2020-08-03 at 17 48 46" src="https://user-images.githubusercontent.com/42757252/89240642-98efc700-d5b1-11ea-9a94-d1df87237826.png">

(Is it true that this golf course has no name? Usually a golf course has a name. "County Club" seems to be a common part of names of golf courses in the USA, so perhaps mapping these two areas separately is not the best practice. Most leisure=sports_centre features are not golf courses)

**Comment by cwmke** [comment] 2020-08-04 14:58
[The wiki page describes](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dsports_centre), "A sports centre is a distinct facility where sports take place within an enclosed area. It can be a building (indoor sports centre), just outside (outdoor sports centre) or contain indoor and outdoor sports features mixed together." This seems to accurately describe most US country clubs that are almost universally multi sport facilities with some social aspects added.

The leisure=sports_centre tag seems most appropriate as there are multiple pitches in one unified location. A golf course is within the club but is not the sole sport provided. Our currently discussed example includes golf, swimming, tennis, paddle tennis, bocce ball etc. There are competitive teams for several of these sports. Therefore naming the golf course would be inappropriate as the entire (multisport) club has a name not just the golf course located within.

The trigger for changing the tag was the inclusion of tennis courts, pitches and buildings within the formerly outer golf course tag that are completely unrelated to golf or a golf course. An example of a golf course tag used in the outer tag is available [up the street here](https://www.openstreetmap.org/way/28487648).

**Comment by Adamant36** [comment] 2020-08-15 09:40
Just to pointlessly throw my hat in the ring, I'd still consider this a golf course. Since 90% of the area is taken up with golf related things. Just as I would still consider my local gym a gym. Even though it has a swimming pool and handball courts. I don't think having those things change the nature of it. Otherwise, it's kind of "mapping every blade of grass." 

That said, one possibility you might want to consider is tagging the grounds as club=sport + sports=whatever. I think that's a good compromise. Especially since it considers itself a "country club." To me (and I think to other people to), a sports center is a completely different thing then a country club. While they do have their origins as men's sporting clubs and still serve that purpose to some degree. 

BTW, I'd also nix the descriptive names on the service roads. As it goes against [the naming rule](https://wiki.openstreetmap.org/wiki/Key:name). " names should not include additional information not contained in the official name such as categories, types, descriptions, addresses, refs, or notes."

**Comment by cwmke** [comment] 2020-08-17 15:27
Thanks for your thoughts @Adamant36. I think club=sport makes a good deal of sense. Golf courses by their nature will take up a large majority of the grounds of any place they are located. I consider knowing the actual boundaries of the course to be useful information and separating the course from the non-golf aspects of the rest of the grounds provides that.

For the service road: there is a sign outside of the labeled road with that written on it. I agree it's descriptive but with a prominent sign I figured it can be mapped. I've done the same at a hospital that placed a large sign by the emergency entrance which I consider the same basic idea. Is that still frowned upon in these instances? 

For the main topic of this issue, I still believe an unnamed golf course should not take priority over a named sports centre (or now club.)

**Comment by jeisenbe** [comment] 2020-08-31 23:42
I'm closing this issue, since what is happening here is a collision between the golf_course icon and the text label of the sports_centre area. Unfortunately there is no computational cheap way to fix these collisions. In a style which was designed to take more time during rendering, it could be feasible to try multiple text label positions, if the first option was blocked. But this does not seem to be feasible for this style, which is oriented toward frequent, rapid updates so that mapper get quick feedback. 

Also, it's likely that the initial problem can be corrected by more standard mapping, rather than having 2 overlapping features with nearly the same size and shape, only one of which is named.

**Closed** 2020-08-31 23:42 UTC
Labels: invalid, text
