### ISSUE TITLE
Add rendering for amenity=watering_place

### ISSUE THREAD

**Issue by G10h4ck** [gravitystorm/openstreetmap-carto#4441] opened 2021-07-18 13:02 UTC
### Expected behavior

Watering places should be rendered on the map at least when the drinking_water tag is present if not always. In Sicily we have traditional watering places for both animals and humans called "Abbriviratura", those watering place usually made of squared stone features a pipe where the water continuously flow and humans usually drink there, the same water going out of the pipe end up in a pool where animal (cattle, sheep, horse...) can drink easily. Tag such as natural=spring which is rendered is not accurate as more often then not the spring where the water comes from is far away and the water is brought by some piping into the "Abbriviratura". Also amenity=drinking_water seems inaccurate because it hides the possibility of cattle watering and usually indicate a small city fountain with a tap.

### Actual behavior

Watering places are not rendered at all

### Links and screenshots illustrating the problem

https://www.openstreetmap.org/way/916337308
https://www.openstreetmap.org/way/965324950
https://www.openstreetmap.org/node/3987658197

**Comment by StyXman** [comment] 2021-07-18 13:09
I would say `amenity=drinking_water` is ok and should probably have extra tags about the animal stuff.

**Comment by imagico** [comment] 2021-07-18 13:47
Thanks for the suggestion, this is a duplicate of #3703, see also #1224 and #3011.  Your use case is yet another good example for the need to have compound symbols for the illustration of different tag combinations (is this case natural=spring or man_made=water_well plus amenity=drinking_water/drinking_water=yes and  amenity=watering_place)

**Closed by imagico** 2021-07-18 13:47 UTC
