### ISSUE TITLE
Render natural=shrubbery

### ISSUE THREAD

**Issue by FriederHannenheim** [gravitystorm/openstreetmap-carto#4882] opened 2023-10-08 20:32 UTC
I'm editing the map here: https://www.openstreetmap.org/#map=19/51.07489/13.72553 and around this playground there's an area of maintained shrubs to separate the area from the street.

### Expected behavior
The shrubbery is shown on the map

### Actual behavior
It is not rendered.

### Screenshots with links illustrating the problem
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/41985738/2d6b8ecd-1f95-410b-ac9b-892f580e92bd)
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/41985738/d540f580-60c6-4717-bab2-4ceaa97863a1)

**Comment by pnorman** [comment] 2023-10-08 20:37
Duplicate of #4473. Please check for duplicate issues before submitting one, as this was easily found by searching for "shrubbery"

**Closed by pnorman** 2023-10-08 20:37 UTC

**Comment by FriederHannenheim** [comment] 2023-10-08 20:38
Sorry. I usually do that but I forgot this time
