### ISSUE TITLE
oneway symbols not placed well (regression)

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#3890] opened 2019-09-17 07:08 UTC
### Expected behavior
be able to discern oneway roads even when short
### Actual behavior
not
### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/725258276
![E84570DD-93BD-47E2-A475-A5F15582F37B](https://user-images.githubusercontent.com/581288/65019019-ad3fbc80-d92a-11e9-900e-890b6c14704e.jpeg)

**Comment by imagico** [comment] 2019-09-17 09:54
If you think this is a regression you'd have to be clearer in what way this has been better in the past.

**Comment by imagico** [comment] 2019-09-17 09:56
Apart from that this is at least partly a duplicate of #595.

**Comment by jeisenbe** [comment] 2019-09-17 11:55
Also a duplicate of #2476

**Comment by jeisenbe** [comment] 2019-09-17 13:19
Closed, let's continue the discussion at #595

**Closed** 2019-09-17 13:19 UTC
Labels: duplicate

**Comment by dieterdreist** [comment] 2019-09-17 22:15
sent from a phone

> On 17. Sep 2019, at 11:54, Christoph Hormann <notifications@github.com> wrote:
> 
> If you think this is a regression you'd have to be clearer in what way this has been better in the past.



regression because the arrows used to start very close to the beginning of the way (once when they were made of overlapping linear ways with differing thickness), and apparently this changed at some point.

**Comment by jeisenbe** [comment] 2019-09-18 01:13
That's true, though it was several years ago.

Should we reopen this as more specific than #595 and change the title to:

"Oneway symbols not placed on short ways"

Or just discuss at #595 which also includes too few arrows on longer ways?
