### ISSUE TITLE
 Names off-on-off-on-off while zooming

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4734] opened 2022-11-25 00:21 UTC
The name of https://www.openstreetmap.org/way/510921128  goes
 off-on-off-on-off while zooming.
Indeed, a twinkling effect. Yes simply explainable but undesirable nonetheless. Users used to other web maps won't be used to this.

**Comment by HolgerJeromin** [comment] 2022-11-25 07:40
related/duplicate of #3880 and others

**Comment by imagico** [comment] 2022-11-25 10:53
Indeed.  Closing in favor of #3880.

Note the link to example shows an additional difficulty that has not been considered explicitly in #3880 so far, that is the role of dynamic line labeling.  Since the label positions of roads etc. change as you zoom in even without collisions with other features, a simple prioritization by starting zoom level is not going to fully address the problem here.

**Closed by imagico** 2022-11-25 10:53 UTC
