### ISSUE TITLE
icon not placed inside polygon

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#2457] opened 2016-11-21 16:12 UTC
As mentioned in the discussion of #2428, I have a parking P icon rendered outside the [polygon](https://www.openstreetmap.org/way/454480657), so it appears the parking would be in the building, where it is not. 

![52778](https://cloud.githubusercontent.com/assets/8266355/20455432/5cd41d78-ae5c-11e6-94d4-fdc99499c882.png)

Whether a mapnik issue or not, <br>@pnorman found it worth a ticket, and @math1985 commented Nov 19:

> Hmm, it sees the relevant code on our side does contain ' marker-placement: interior;'. Is somebody able to create a mimimal example (minimal db and minimal cartocss/xml) to definitely prove it's not a problem on our side?

**Comment by pnorman** [comment] 2016-11-21 17:15
A starting place would be to take the way/454480657/full XML and import it into the DB to render it.

**Comment by kocio-pl** [comment] 2018-01-10 11:59
Most probably this is a Mapnik problem, which is fixed in 3.0.16 - duplicate of #1465.

**Closed by kocio-pl** 2018-01-10 11:59 UTC
Labels: amenity-points, bug

**Comment by polarbearing** [comment] 2018-01-10 13:24
Not fixed in the example in the first post.

**Comment by kocio-pl** [comment] 2018-01-10 13:33
In the case of OSM.org, we have to wait until Mapnik 3.0.18 is released and packaged for Ubuntu, then for the OSMF server admins [to deploy this package](https://github.com/openstreetmap/chef/issues/132#issuecomment-341579984), so yes - the result is still not visible there.

However that's the problem outside the osm-carto code - if you deploy proper Mapnik version on your server, you will get proper placement of icons and labels.

**Comment by kocio-pl** [comment] 2018-01-24 06:08
Using 3.0.18-rc1 it's really fixed:
![rizzlmyx](https://user-images.githubusercontent.com/5439713/35317061-3016a220-00d5-11e8-9c36-a1f8885d4127.png)
