### ISSUE TITLE
Rendering for tag amenity=animal_shelter.

### ISSUE THREAD

**Issue by woodmiser** [gravitystorm/openstreetmap-carto#4511] opened 2022-01-27 00:35 UTC
### Expected behavior
It would be nice to have this icon show up on the standard tile layer.  Pet and animal shelters are becoming more commonplace as public attention has focused on abandoned and neglected animals.  Would make it easier for people to find facilities.  The icon is available.  Very attractive icon too.  https://wiki.openstreetmap.org/wiki/Tag%3Aamenity%3Danimal_shelter
Thank you
### Actual behavior
Doesn't appear on map

**Comment by HolgerJeromin** [comment] 2022-01-27 07:25
> The icon is available. Very attractive icon too.

We need icons with 14x14 px². Resizing the icon from wiki does not work:
![image](https://user-images.githubusercontent.com/2410353/151310768-eac2394d-18df-4959-8436-6f6f70c6488f.png)

**Comment by imagico** [comment] 2022-01-27 11:15
Duplicate of #4260.

**Closed by imagico** 2022-01-27 11:15 UTC
