### ISSUE TITLE
Labels for swimming facilities are displayed with an offset on low zoom levels

### ISSUE THREAD

**Issue by map-per** [gravitystorm/openstreetmap-carto#4802] opened 2023-04-07 14:49 UTC
### Actual behavior
swimming facilities (leisure=water_park, leisure=sports_centre + sport=swimming and leisure=swimming_area) are displayed with an icon until zoom 17. For zoom 16-14 no icon is used but the label still has an offset (text-dy) of 11 which looks weird.

### Expected behavior
I would either display the icon together with the label (similar to how it is done for golf_course) or display the label without an offset. I think showing the label is better as this avoids confusion with similar looking leisure=parks.

### Code
https://github.com/gravitystorm/openstreetmap-carto/compare/master...map-per:openstreetmap-carto:water_park

### Screenshots with links illustrating the problem 
(https://www.openstreetmap.org/way/174549769)
- icon
![icon15](https://user-images.githubusercontent.com/79519062/230628063-43f88cb2-6970-43bd-b743-afd49871d5e5.png)
![icon16](https://user-images.githubusercontent.com/79519062/230628080-9b5886f0-5045-4300-b589-1a20c1df6fdc.png)

- no icon, without offset
![no-icon15](https://user-images.githubusercontent.com/79519062/230628101-4a7df911-4dd7-42c3-8b21-db9ecd4364ea.png)
![no-icon16](https://user-images.githubusercontent.com/79519062/230628113-57239edd-c125-42b4-a13c-c79ca8bb215e.png)

**Comment by imagico** [comment] 2023-04-07 16:00
Duplicate of #4620.

**Closed** 2023-04-07 16:00 UTC
Labels: duplicate
