### ISSUE TITLE
Railway: service=crossover

### ISSUE THREAD

**Issue by zetx16** [gravitystorm/openstreetmap-carto#2295] opened 2016-08-20 06:22 UTC
Render service=crossover as the rest service=\* for railways

**Comment by HolgerJeromin** [comment] 2016-08-20 13:21
Thanks for your suggestion. 
This was discussed earlier in issue #1971

**Comment by kocio-pl** [comment] 2016-11-15 21:44
Closing as a duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/1971.

**Closed by kocio-pl** 2016-11-15 21:44 UTC
