### ISSUE TITLE
Place=village not rendered as an area

### ISSUE THREAD

**Issue by stevenLAD** [gravitystorm/openstreetmap-carto#2794] opened 2017-09-01 11:47 UTC
This may be a policy decision, but if an area is declared a village then should it not be shaded as it would be if it were landuse=residential.

This also applies to all other place areas (superb, hamlet etc).

**Comment by scaidermern** [comment] 2017-09-01 12:04
Related discussion: https://help.openstreetmap.org/questions/58884/rendering-of-areas-with-place

**Comment by matkoniecz** [comment] 2017-09-01 13:48
duplicate of #103

**Closed** 2017-09-01 13:48 UTC
Labels: enhancement, landcover
