### ISSUE TITLE
Bad name posistion for area/multipolygon

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#2331] opened 2016-09-05 15:54 UTC
Names are often placed in a bad spot for areas.

https://www.openstreetmap.org/relation/5742213
Notice how the name is put in the western corner of the glacier arm.

I have seen this other places as well, but can't seem to find them now.

**Comment by ethan-nelson** [comment] 2016-09-06 00:47
I just noticed this today as well after adding in survey data. [Here's another example](http://www.openstreetmap.org/way/374776705) where the name is rendered at westernmost point (though I'm not sure if it's related to the beauty node within the way or not).

**Comment by pnorman** [comment] 2016-09-06 01:00
Duplicate of #349

**Closed by pnorman** 2016-09-06 01:00 UTC
