### ISSUE TITLE
place = 'suburb' from planet_osm_polygon not shown

### ISSUE THREAD

**Issue by nafis042** [gravitystorm/openstreetmap-carto#2857] opened 2017-09-21 20:34 UTC
I have some rows in planet_osm_point table where place = 'suburb' and its showing in the map perfectly but when I have some rows in planet_osm_polygon table where place = 'suburb' it's not showing on the map. How can I show these on the map? or its just simply not possible to show from polygon table?

**Comment by pnorman** [comment] 2017-09-23 09:09
Duplicate of #103

**Closed** 2018-01-05 09:45 UTC
Labels: placenames
