### ISSUE TITLE
Confusing symbol for amenity=ferry_terminal

### ISSUE THREAD

**Issue by vss-devel** [gravitystorm/openstreetmap-carto#2785] opened 2017-08-29 13:52 UTC
As discussed at the bottom of #2385, v4.2.0 uses an anchor symbol ![anchor symbol](http://wiki.openstreetmap.org/w/images/2/24/Ferry-icon.svg) for the amenity=ferry_terminal which is quite confusing.

It may be not so obvious along the rivers, as depicted at #2385, but at a sea shore it looks weird. Common sense suggests that an anchor is for an [anchorage](http://wiki.openstreetmap.org/wiki/Tag:seamark:type%3Danchorage). As a matter of fact, ferries don't usually deploy an anchor to moor at their docks. 

Not only [nautical](http://wiki.openstreetmap.org/wiki/Seamarks/INT-1_Section_N#Anchorages.2C_Anchorage_Areas), but also some topographic maps modern and historical maps are using an anchor symbol to denote an anchorage. 

See, for example, Topografska karta at the https://geoportal.dgu.hr/, Carte littorale https://www.geoportail.gouv.fr/donnees/carte-littorale or as suggested by @imagico: "for example chapter 2, symbol 226 in http://www.lib.berkeley.edu/EART/pdf/soviet.pdf - likewise for some pre-digital German TK100/TK200 (don't have a digitized sample at the moment)."

**Comment by Klaus-Tockloth** [comment] 2017-08-29 15:47
I agree with the thread opener. The anchor symbol is confusing and too dominant. Especially at locations where "amenity=ferry_terminal" is similar/identical to a bus stop.

**Comment by kocio-pl** [comment] 2017-08-29 16:10
Even on the sea there's a ferry line attached most of the times, so it should be clear from the context that it's a terminal, not a anchorage place. The initial level was chosen as a middle ground between big ferry stations and small ferry stops, because we have no way to distinguish their size currently, so it's expected to be sometimes too late and sometimes too early. In this case it's the 3 lines name labels which bothers me.

You can suggest a solution if you feel this could be improved.

**Comment by vadp** [comment] 2017-08-29 20:02
I don't see a point of breaking an established and reasonable practice. I'm quite confident that for quite a number of people if they see an anchor on a map they'd assume there is an anchorage there. Here is another example http://www.physicalgeography.net/fundamentals/2d.html. Personally when I saw an anchor on the land I've rushed to JOSM to see what's wrong with the map.

By the way the anchor symbol has a quite broad connotation in this context. Perhaps it's better to have a vessel to be depicted on the symbol. So, I'm happy to make a suggestion. 

[CEVNI – European Code for Inland Waterways](http://www.unece.org/index.php?id=40105) uses this symbol ![ferry-boat](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Vesiliikennemerkki_27.svg/40px-Vesiliikennemerkki_27.svg.png) for a ferry-boat. An **inverted version** of it would resemble a ferry sign used at some topo maps. You may like its Polish version ![ferry-boat](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/POL_Znak_Żeglugowy_E4b.svg/40px-POL_Znak_Żeglugowy_E4b.svg.png).

Otherwise here are some options I've found at the Wikipedia commons:
 ![ferry-boat](https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/AIGA_ferry.svg/40px-AIGA_ferry.svg.png),  ![ferry-boat](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Ic_directions_ferry_48px.svg/40px-Ic_directions_ferry_48px.svg.png),  ![ferry-boat](https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Ferry.svg/40px-Ferry.svg.png)

and a couple of options at the OSM wiki:  ![ferry-boat](https://wiki.openstreetmap.org/w/images/1/1d/Ferry_terminal_icon_16x16.png),  ![ferry-boat](https://wiki.openstreetmap.org/w/images/0/08/Ferryterminal20.png)

**Comment by kocio-pl** [comment] 2017-08-29 20:23
> I don't see a point of breaking an established and reasonable practice. 

It was very late idea, because no vessel icon I've tried was even remotely as recognizable.

> By the way the anchor symbol has a quite broad connotation in this context. 

It was deliberate choice to use broad symbol, because it was also suggested that not every ferry is a ship. See also my conclusions: https://github.com/gravitystorm/openstreetmap-carto/pull/2385#issuecomment-321999068.

> So, I'm happy to make a suggestion.

Thanks! However I should have said that any proposition needs to look good on 14 px matrix and only last 2 icons are as small. I'm not able to recognize second one of them and the first of them was not recognized by other people. See #2385 for more failed attempts.

**Comment by pnorman** [comment] 2017-08-29 22:22
Icons with wavy lines are not likely to be suitable at the size we need.

**Comment by kocio-pl** [comment] 2017-08-29 22:40
Hm, @Klaus-Tockloth case gave me idea to improve rendering a bit - what if we show terminals with area from z14 and terminal nodes from z16? This should be possible with SQL query and could encourage more detailed drawing for bigger ones. There are [11415 such nodes and 1309 ways](https://taginfo.openstreetmap.org/tags/amenity=ferry_terminal#overview) currently.

**Comment by Klaus-Tockloth** [comment] 2017-08-30 06:16
> You can suggest a solution if you feel this could be improved.

Basic idea:
Use something similar to bus stops. Start with a symbol (e.g. circle, point, square, triangle, ...) without a label. Continue with an icon (e.g. wave line with vessel). Continue with the label.

Rationale:
A ferry object consist of two elements: ferry line and ferry terminals. Where the ferry line hits the land there is typically a terminal. The ferry line is very dominant, so there is no need to make the ferry terminal also dominant.

Improvement:
Distinguish (if technically possibly) if the terminal is at the coast or is inland. Enlarge symbol and icon if the terminal is at the coast.

**Comment by Klaus-Tockloth** [comment] 2017-08-30 06:32
A year ago we also renewed the ferry terminal icon for our Android map. We end up with this:

![bildschirmfoto 2017-08-30 um 08 30 15](https://user-images.githubusercontent.com/5493128/29858442-ae2ab96c-8d5d-11e7-814f-b94e844ab9e8.png)

**Comment by vadp** [comment] 2017-08-30 08:27
@kocio-pl I've corrected links for the Commons icons. As you'd see the thumbnails are generated by Mediawiki from SVGs, so you'd scale them easily.

Perhaps it's better to have bow/stern view of a vessel, so they'd the difference from a bus icon is quite distinct.

**Comment by kocio-pl** [comment] 2017-09-02 00:18
I'm not ready to get back again to the same problem that took me so long at the moment (still you can play with different renderings and post it here). I just wanted to note that [Sputnik](https://wiki.openstreetmap.org/wiki/Sputnik) is using the anchor too.

**Comment by vadp** [comment] 2017-09-02 08:16
>  I just wanted to note that Sputnik is using the anchor too.

Using anchor to demote ferry is actually quite common for tourist city plans. So Sputnik apparently follows this venue. But this actually this makes their map look amateurish. It's the same with the Yandex maps.  

Perhaps the thing is that, and one could argue, but Russia is not a marine country, just a few people live by sea there. Funny enough, but no one from them uses a car horn a bus wheel or even a steering wheel to denote a bus stop. 

Let's look at what real maps do. They've put many years of experience in there. BTW, even Google (not a "real" map) use a ship for this purpose, and this brings some consistency to their maps.

**Comment by vadp** [comment] 2017-09-02 08:57
>  I just wanted to note that Sputnik is using the anchor too.

Using anchor to demote ferry is actually quite common for tourist city plans. So Sputnik apparently picked up this tendency from there. But this actually this makes their map look amateurish. It's the same with the Yandex maps.  But even Google (not a professional map either) use a ship for this purpose, and this brings some consistency to their maps.

Funny enough, but no one from them uses a car horn a bus wheel or even a steering wheel to denote a bus stop. 

Let's look at what real maps do. They've put many years of experience in there.

**Comment by pnorman** [comment] 2017-09-04 23:55
I've seen both used in different maps. I'm okay with our current symbol. If someone feels a different symbol would be better, provide an example **rendering** for comparison, then we can evaluate it.

**Comment by kocio-pl** [comment] 2017-09-05 04:53
Yes, it would help to see the real output, not general ideas, because this issue is about details. Preparing simple rendering/testing environment is documented here:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

**Comment by printmaps** [comment] 2017-09-08 13:23
Here a sample map (scale 1:10000) with an alternative ferry icon.

Original icon:
![potsdam-org](https://user-images.githubusercontent.com/26689799/30213476-6941ecc8-94a9-11e7-9706-8385f036e3e2.png)

Alternative icon (without label):
![potsdam-neu](https://user-images.githubusercontent.com/26689799/30213496-7a52c19a-94a9-11e7-9f4c-65de1e011f48.png)

**Comment by kocio-pl** [comment] 2017-09-08 13:42
The icon looks is probably smaller than 14x14 px and is unreadable for me - at 100% resembles bread (bakery) icon.

**Comment by printmaps** [comment] 2017-09-08 14:56
Hard to read ... I agree. BTW: I don't see the need for a realistic looking icon ... an abstract symbol (here a triangle) is in my eyes sufficient (analog to bus stops or train station). The ferry line makes clear what it is:

![potsdam-dreieck-3](https://user-images.githubusercontent.com/26689799/30217379-42c5152c-94b6-11e7-95b3-20390c7b3a8b.png)

**Comment by kocio-pl** [comment] 2017-09-08 15:01
Please remember that we have also bigger ferry terminals, drawn as an area, and abstract symbol wouldn't look good there IMO:
![3szsjaex](https://user-images.githubusercontent.com/5439713/29244614-c2d540fc-7fbc-11e7-8af3-59afa59694b2.png)

**Comment by pnorman** [comment] 2017-09-08 20:24
👎 to the small "breadbox" symbol as being unreadable, and 👎 to the triangle. I don't think an abstract symbol works here.

**Comment by printmaps** [comment] 2017-09-09 07:15
To distinguish between nodes and areas could be an good idea.
- Nodes are small terminals like bus stops with late labeling and small icons or abstract symbols.
- Areas are large terminals with early labeling and larger icons.

**Comment by dieterdreist** [comment] 2017-09-09 07:22
sent from a phone

> On 9. Sep 2017, at 09:15, printmaps <notifications@github.com> wrote:
> 
> Nodes are small terminals like bus stops with late labeling and small icons or abstract symbols.
> Areas are large terminals with early labeling and larger icons.


there is no such difference between small and large, a small thing will often be mapped as area and big terminals can be mapped as nodes as well.
Btw, taggingwise, maybe very small (bus stop like) ferry route endpoints aren't actually "ferry terminals"? Clearly intermediate stops of a ferry route aren't terminals (semantically). The resulting gaps are part of the reason for the seaway proposal

**Comment by printmaps** [comment] 2017-09-09 07:36
The OSM wiki defines "amenity=ferry_terminal" as: 

A place where people/cars/etc. can board and leave a ferry.

**Comment by dieterdreist** [comment] 2017-09-09 18:57
sent from a phone

> On 9. Sep 2017, at 09:36, printmaps <notifications@github.com> wrote:
> 
> The OSM wiki defines "amenity=ferry_terminal" as:
> 
> A place where people/cars/etc. can board and leave a ferry.
> 


I know, but everytime the definition is broader as the tag wording, sooner or later it fires back

**Comment by kocio-pl** [comment] 2017-09-09 19:05
If it's too specific from beginning, it can be also source of troubles (amenity=cafe/restaurant - and what if you don't know exactly?). But that's the way it is and that's why we have "2.0" specifications:

https://wiki.openstreetmap.org/wiki/Proposed_features/Seaway

Sadly, it's not approved and not even used:

https://taginfo.openstreetmap.org/search?q=Seaway#keys

**Comment by boothym** [comment] 2017-09-10 23:38
Agree with the OP, when I saw the anchor on the map I didn't realise it was a ferry terminal. 

The second wikimedia icon from @vadp looks ok at 14px. The iD editor also has a couple of ferry icons.

**Comment by kocio-pl** [comment] 2017-09-10 23:42
OK, so please render them so we could evaluate it.

**Comment by vadp** [comment] 2017-10-10 15:33
> OK, so please render them so we could evaluate it.

Just found some time to play with the thing:

![ferry-boat](https://gist.github.com/vadp/3c5c8aacfbe119a61de23305a7a4ed02/raw/dfcd0259dafbfc36c823bbfc961dc894beb4a69a/Screenshot%2520Ferry-boat.svg%2520OpenStreetMap%2520Carto%2520%25E2%2580%2594%2520Kosmtik.png)

![ferry-boat](https://gist.github.com/vadp/3c5c8aacfbe119a61de23305a7a4ed02/raw/dfcd0259dafbfc36c823bbfc961dc894beb4a69a/Screenshot%2520AIGA_ferry.svg%2520OpenStreetMap%2520Carto%2520%25E2%2580%2594%2520Kosmtik.png)

![ferry-boat](https://gist.github.com/vadp/3c5c8aacfbe119a61de23305a7a4ed02/raw/dfcd0259dafbfc36c823bbfc961dc894beb4a69a/Screenshot%2520Ic_directions_ferry_48px.svg%2520OpenStreetMap%2520Carto%2520%25E2%2580%2594%2520Kosmtik.png)

![ferry-boat](https://gist.github.com/vadp/3c5c8aacfbe119a61de23305a7a4ed02/raw/dfcd0259dafbfc36c823bbfc961dc894beb4a69a/Screenshot%2520Ferry.svg%2520OpenStreetMap%2520Carto%2520%25E2%2580%2594%2520Kosmtik.png)

**Comment by kocio-pl** [comment] 2017-10-10 15:40
2 is unreadable, 3 is better by a narrow margin, 1 is recognizable, but too cartoonish/geometric, 4 looks the most promising for me for nodes, but I'm afraid of areas. Could you check how would it look [here](http://www.openstreetmap.org/way/136695687)?

**Comment by vadp** [comment] 2017-10-10 15:44
> Could you check how would it look here?

Tell me how to get a pbf for it

**Comment by kocio-pl** [comment] 2017-10-10 15:49
You can just export .osm file from website export, since it's quite small area and can be imported as easily as PBF. 

There are however additional services like OSMaxx or HOT export tool, which allows you to download data for arbitrary area if they are bigger.

**Comment by kocio-pl** [comment] 2017-10-10 16:20
It looks strange for me. Maybe you should use the existing color, to make it look different than slipways?

**Comment by vadp** [comment] 2017-10-10 16:27
Here you are:
![ferry](https://gist.github.com/vadp/3c5c8aacfbe119a61de23305a7a4ed02/raw/04b4e58418712200bb6b2358806b9ba2685314e9/Screenshot%2520Ferry.svg%2520Sidney%25202%2520OpenStreetMap%2520Carto%2520%25E2%2580%2594%2520Kosmtik.png)

I think the former is better as it uses transportation colour, but that's not critical.

**Comment by kocio-pl** [comment] 2017-11-14 17:15
@vss-devel I wanted to revisit this issue, but something bad happened to the images from you - they are not shown on this page and the links to them don't work too.

**Comment by vss-devel** [comment] 2017-11-15 17:30
@kocio-pl: The images are fixed. Enjoy!

**Comment by kocio-pl** [comment] 2017-11-18 07:04
After some time to keep the perspective, my inspection shows that unfortunately this shape is hard to recognize. I also believe it would be too heavy for small river terminals (example from https://github.com/gravitystorm/openstreetmap-carto/issues/2785#issuecomment-325707003 would be even worse than just too much of text). Therefore I close this issue.

Thanks for the work with searching for a replacement.

**Closed by kocio-pl** 2017-11-18 07:04 UTC
Labels: amenity-points, cartography

**Comment by DENelson83** [comment] 2017-12-21 00:57
May I then suggest to use a white anchor on a purple box for a ferry terminal, while a blue anchor can be used to refer to "leisure=marina"?  I draw my inspiration from "highway=bus_stop" using a blue bus symbol, while "amenity=bus_station" using a white bus symbol on a blue box.

**Comment by kocio-pl** [comment] 2017-12-21 01:04
Bus/bus station does not sound to me as a parallel to ferry terminal/marina - these are two different uses, not just a bigger/smaller feature, so I don't think it would work. It would be better suited for `ferry_port=stop/terminal` dfference for example, if `seaway=*` tagging will ever take off.

**Comment by DENelson83** [comment] 2017-12-21 01:20
Well, as I associate the anchor icon with a marina, I would then suggest that the anchor icon be moved to "leisure=marina" and that no icon at all be used for a ferry terminal, instead implying a ferry terminal from the ferry routes that land there.

**Comment by kocio-pl** [comment] 2017-12-21 01:31
AFAIR we already render marinas and nobody even reported that's insufficient, so this would be separate change (the issue is not about "this icon is needed elsewhere"). 

On the other hand general transport rendering was incomplete without a ferry icon and we haven't found anything better. There are also examples where ferry routes are not tagged and terminals are the only thing visible, like here:

https://www.openstreetmap.org/#map=15/29.9800/31.2261

**Comment by DENelson83** [comment] 2017-12-21 01:47
Well, that doesn't change the fact that the use of an anchor to refer to a ferry terminal is still confusing.  The vast majority of systems use the pictogram of a ship to refer to a ferry terminal, and whenever I see an anchor picture, I think marina.  If you can find the absolute simplest pictogram of a ship that is easily recognized from a distance, please use it for a ferry terminal instead.

**Comment by kocio-pl** [comment] 2017-12-21 01:52
Unfortunately, we couldn't find such ship icon for many months, even if I started with such idea - please look at this discussion, #1673 and #2385. This seems to be the only shape which is easily recognizable and not too heavy, plus there are maps which use the anchor exactly this way.

**Comment by daganzdaanda** [comment] 2017-12-21 15:47
For what it's worth, I have no complaint against the anchor, but the [icon No1 here](https://github.com/gravitystorm/openstreetmap-carto/issues/2785#issuecomment-335513129) looks perfectly fine to me. I think it's actually a point in favour that it is simple / geometric, just like the icons for buses, taxis etc.
