### ISSUE TITLE
Housenumber sometimes renders in a corner

### ISSUE THREAD

**Issue by danieldegroot2** [gravitystorm/openstreetmap-carto#4655] opened 2022-08-21 10:33 UTC
### Expected behavior

Housenumbers on buildings always render in the approx. center of the building

### Actual behavior

Housenumber on one of slightly non-square buildings renders in its northern corner (at least on zoom 19). There doesn't seem to be anything which could cause this rendering (ie. duplicate nodes).

This does not happen on the CyclOSM or Humanitarian layers on any of their zoom levels.

Is this due to tile boundary logic?

### Screenshots with links illustrating the problem

https://www.openstreetmap.org/way/300990833

![image](https://user-images.githubusercontent.com/67521919/185786804-d70775c2-5e5c-4fdb-a328-e769dd3efa84.png)

https://www.openstreetmap.org/way/300990817

![image](https://user-images.githubusercontent.com/67521919/185787170-b4ec97cd-9559-488e-8ade-b29e34c486b4.png)

**Comment by imagico** [comment] 2022-08-21 10:51
Duplicate of #3857.

Note this is not exclusively a matter of the (non-rectangular) shape, it is also a matter of rotation.  As pointed out in https://github.com/gravitystorm/openstreetmap-carto/issues/4241#issuecomment-1180465712 ST_PointOnSurface() is not invariant against rotation.

**Closed by imagico** 2022-08-21 10:51 UTC
