### ISSUE TITLE
swimming_pool outlines too noisy

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#585] opened 2014-05-29 20:23 UTC
It's not a big problem, but have a look at 
http://www.openstreetmap.org/#map=18/-20.27700/-40.29099 
and then zoom out. The outlines of the many small pools create a lot of visual clutter. Even at z14 there are tiny dark blue lines: 
http://www.openstreetmap.org/#map=14/-20.2731/-40.2982

I would say that the outlines should only render at close up zooms, 18 and 19 maybe. And the outlines could be less prominent.

**Comment by kocio-pl** [comment] 2016-09-24 19:26
I would take 2 (drop outlines for small swimming pools) with at least z19 showing everything. Probably similar filters we have for some other small objects could be used here.

**Comment by kocio-pl** [comment] 2017-12-11 20:24
I don't feel this problem is too common nor serious. If there are no similar places (or their amount is small), I'm inclined to close this issue.

**Comment by matthijsmelissen** [comment] 2017-12-11 21:33
It is a serious issue to me.

<img width="605" alt="screen shot 2017-12-11 at 22 32 40" src="https://user-images.githubusercontent.com/5251909/33854792-3cb9b0d2-dec3-11e7-804b-c29618bc11ba.png">

https://www.openstreetmap.org/search?query=andorra#map=14/43.7283/7.3771

**Comment by andrewharvey** [comment] 2018-04-22 04:44
https://www.openstreetmap.org/#map=15/-33.8783/151.0839

![swimming pools](https://user-images.githubusercontent.com/117278/39091644-a352c3da-463b-11e8-8674-4470c1b6abe1.png)

**Comment by pnorman** [comment] 2018-04-22 05:56
I'm not too worried about the Strathfield example, because the mapping there is *so* atypical, with swimming pools and very little else.

@matthijsmelissen shows a good example of the problem on z14, and I think part of the problem is we reduce the visual weight of the building outline going from z15 to z14, but not of swimming pools.

z14
![image](https://user-images.githubusercontent.com/1190866/39092004-19abec4e-45b7-11e8-9b20-099b507bcafc.png)

z15
![image](https://user-images.githubusercontent.com/1190866/39092007-2c61681e-45b7-11e8-83f4-aeceb83b2bee.png)

Higher zooms might need some adjustment, but z14 is particularly bad.

**Comment by jragusa** [comment] 2018-10-07 19:40
Vésenaz near Geneva, following suggestion of @CloCkWeRX
https://www.openstreetmap.org/#map=16/46.2311/6.1972

`z=16`
Before
![swimming_pool_before_z16](https://user-images.githubusercontent.com/9897203/46586040-f465d200-ca78-11e8-8037-209a13071f69.png)
After
![swimming_pool_after_z16](https://user-images.githubusercontent.com/9897203/46586049-13fcfa80-ca79-11e8-9f1c-26741fbfe9b0.png)

`z=18`
Before
![swimming_pool_before_z18](https://user-images.githubusercontent.com/9897203/46586070-6b9b6600-ca79-11e8-851d-931cbfe7b015.png)
After
![swimming_pool_after_z18](https://user-images.githubusercontent.com/9897203/46586056-2aa35180-ca79-11e8-8e92-fac254b33c68.png)

**Comment by Tomasz-W** [comment] 2018-10-07 20:05
@jragusa Can you try with:
```
polygon-fill: @water-color;
line-color: saturate(darken(@water-color, 30%), 20%);
```
for all swimming pools? I think that adding different shades of water is a bad idea and it might be misunderstood (eg. confused with ice rink https://github.com/gravitystorm/openstreetmap-carto/pull/3330)

**Comment by Tomasz-W** [comment] 2018-10-08 08:31
I like effect of 3/

**Comment by jragusa** [comment] 2018-10-08 19:05
4/
z16
![swimming_pool_after4_z16](https://user-images.githubusercontent.com/9897203/46628431-d31ae980-cb3d-11e8-9114-3da1854ebe0d.png)

z18
![swimming_pool_after4_z18](https://user-images.githubusercontent.com/9897203/46628436-d9a96100-cb3d-11e8-9787-bc81b563d677.png)

**Comment by Tomasz-W** [comment] 2018-10-08 19:26
I think 4/ gives the best effect - border is visible, but it's not too dark.

**Comment by jragusa** [comment] 2018-10-08 19:55
The initial purpose of the issue is to reduce the noise of swimming-pool at low zoom. So I suggest following the [comment](https://github.com/gravitystorm/openstreetmap-carto/issues/585#issuecomment-249382848) of @kocio-pl to remove the outline from z14 and then add from z17 with proposition 4.

z16
![swimming_pool_after5_z16](https://user-images.githubusercontent.com/9897203/46630396-63f4c380-cb44-11e8-9aae-ebd636720534.png)

z17
![swimming_pool_after5_z17](https://user-images.githubusercontent.com/9897203/46630486-97cfe900-cb44-11e8-9b32-b4215f757276.png)

**Comment by Tomasz-W** [comment] 2018-10-08 20:14
@jragusa It would be nice to see some before/ after test renderings with locations form previous posts:
https://www.openstreetmap.org/#map=17/-20.27660/-40.28934
https://www.openstreetmap.org/#map=15/-33.8776/151.0818
https://www.openstreetmap.org/#map=16/43.7054/7.3070

**Comment by jragusa** [comment] 2018-10-08 20:24
Ok I will try tomorrow

**Comment by jeisenbe** [comment] 2018-10-08 23:13
Great ideas, guys. It's looking good.

Are many of these backyard pool tagged with access=private? I would think
this should be used on backyard pools.

Would it make sense to render public pools sooner than private pools, or
render the border on pools with public access?

I would think that a swimming pool at a public park, even if it has a fee,
is much more interesting than a pool that is only accessible to one house.

**Comment by jragusa** [comment] 2018-10-10 21:17
@jeisenbe the code to render differently private swimming-pool is already available in my branch. I don't know what do @kocio-pl and @Tomasz-W think about it but it would easy to tweak this.

https://www.openstreetmap.org/#map=17/-20.27660/-40.28934
z16
![swimming_pool2_z16](https://user-images.githubusercontent.com/9897203/46765698-f8dff400-ccdf-11e8-8f35-3b72c7e4aab9.png)
z17
![swimming_pool2_z17](https://user-images.githubusercontent.com/9897203/46765701-fe3d3e80-ccdf-11e8-904f-7dac8dfb4112.png)
z18
![swimming_pool2_z18](https://user-images.githubusercontent.com/9897203/46765711-04331f80-cce0-11e8-86f2-2a98fdd11d6c.png)

https://www.openstreetmap.org/#map=15/-33.8776/151.0818
z16
![swimming_pool3_z16](https://user-images.githubusercontent.com/9897203/46766511-79075900-cce2-11e8-9f8a-a20db7916c48.png)

z17
![swimming_pool3_z17](https://user-images.githubusercontent.com/9897203/46766523-87ee0b80-cce2-11e8-933e-5ffc06cbcc69.png)

z18
![swimming_pool3_z18](https://user-images.githubusercontent.com/9897203/46766530-8d4b5600-cce2-11e8-9b73-45df331f97b0.png)

https://www.openstreetmap.org/#map=16/43.7054/7.3070
z16
![swimming_pool4_z16](https://user-images.githubusercontent.com/9897203/46766544-93413700-cce2-11e8-8ed7-66a685ac06f1.png)

z17
![swimming_pool4_z17](https://user-images.githubusercontent.com/9897203/46766554-9b00db80-cce2-11e8-8fe3-0c2c20d5a448.png)

z18
![swimming_pool4_z18](https://user-images.githubusercontent.com/9897203/46766565-a05e2600-cce2-11e8-8777-9439773d4622.png)

**Comment by jragusa** [comment] 2018-10-10 21:20
1/ What do you think about z17 as threshold or do you prefer I move it to z18 or z19 ?

2/ As most of the swimming pool displayed in the pictures are private, I would propose to use this for former and to use a different strategy for public ones. What do you think ?

**Comment by kocio-pl** [comment] 2018-10-11 03:15
I don't have a strong opinion how to solve this problem and I'm not involved in it. I think you should probably talk with @matthijsmelissen about it, because for him it's important (https://github.com/gravitystorm/openstreetmap-carto/issues/585#issuecomment-350865179).

**Comment by Tomasz-W** [comment] 2018-10-11 06:46
I don't see both of no-outline and different fill versions as good, intuitive way to show that is a private pool. No-outline may be interpretated as some pool construction thing, and different fill may be considered as totaly different feature. At the other hand a swimming pool is always private or not in real world, but this information may be provided or not, so it migth be confusing if someone will take untagged private swimming pool as a public one. I would render all swimming pools the same.

**Comment by Tomasz-W** [comment] 2018-10-21 13:54
@jragusa There was also suggestion of not using outlines up to some zoom level (https://github.com/gravitystorm/openstreetmap-carto/issues/585#issuecomment-427959516), I don't remember if you included it or not.

**Closed** 2018-10-26 08:03 UTC
Labels: landcover
