### ISSUE TITLE
Render operator=* as label if no name=* is present

### ISSUE THREAD

**Issue by fuddl** [gravitystorm/openstreetmap-carto#1548] opened 2015-05-14 08:19 UTC
a lot of franchise restaurants, hotels & banks have no individual name so mapping it with `operator=*`would be appropriate. But because the `name=*` will always be rendered as a label, contributors feel encouraged to use it instead

**Comment by math1985** [comment] 2015-05-14 08:28
See also #972.

**Comment by dieterdreist** [comment] 2015-05-14 08:34
> Am 14.05.2015 um 10:19 schrieb fuddl <notifications@github.com>:
> 
> a lot of franchise restaurants, hotels & banks have no individual name so mapping it with operator=*would be appropriate. But because the name=* will always be rendered as a label, contributors feel encouraged to use it instead


mostly "brand" is more appropriate for rendering than "operator"

**Comment by RicoElectrico** [comment] 2015-06-16 15:27
For consideration: many forests, or rather forest compartments in Poland have `ref=<number> landuse=forest operator=PGL LP` (Polish national forests administration). Whether that's correct is left open by me.

**Comment by Skippern** [comment] 2015-08-15 12:53
Actually, several features, such as Banks, Restaurants, Fast Food, Fuel Stations should rather be rendered with ```brand=*``` than ```operator=*``` or ```name=*```. Hiarcic order of rendering should probably be discussed for each of these features.

**Comment by kocio-pl** [comment] 2015-08-15 14:00
This was exactly the point of https://github.com/gravitystorm/openstreetmap-carto/issues/698. It's closed now as wontfix, but I think the problem is not resolved properly and wait for the response of the opponents to know if the compromise is still possible.

**Comment by naoliv** [comment] 2015-09-17 17:26
Could we have banks and fuel stations with both `brand` and `name` displayed, please?

**Comment by leite** [comment] 2015-09-18 13:40
+1 nice feature

**Comment by kocio-pl** [comment] 2017-09-16 22:19
I don't think operator is proper text to be shown, it's rather brand, but it should be reported for specific objects anyway, so I'm closing this ticket.

**Closed by kocio-pl** 2017-09-16 22:19 UTC
Labels: amenity-points
