### ISSUE TITLE
trunk_link wider than motorway_link

### ISSUE THREAD

**Issue by jojo4u** [gravitystorm/openstreetmap-carto#1955] opened 2015-11-04 15:18 UTC
Perhaps introduced by #1861

![map](https://cloud.githubusercontent.com/assets/156724/10942231/75978c10-830f-11e5-9c5f-8b1ca24ba5cc.png)
http://osm.org/go/0DpSzmveu

**Comment by sommerluk** [comment] 2015-11-04 21:01
Duplicate of #1109

**Comment by matkoniecz** [comment] 2015-11-05 06:34
I am not entire

**Comment by jojo4u** [comment] 2015-11-05 08:21
Yes, looks like duplicate.

**Closed** 2016-03-23 15:43 UTC
Labels: duplicate, roads
