### ISSUE TITLE
Icon for historic=wayside_shrine

### ISSUE THREAD

**Issue by wernerschka** [gravitystorm/openstreetmap-carto#2008] opened 2015-12-15 16:53 UTC
Dear openstreetmap-carto Team,

please add an icon for historic=wayside_shrine to the
openstreetmap.org map.
These small shrines/columns (often with religious motives) are very popular especially in Germany, Austria, Italy and other countries and up to now over 32000 of them are tagged in OSM.

They are similiar to wayside_crosses, a mixture of historic and/or religious properties.

**Comment by kocio-pl** [comment] 2015-12-15 20:10
Duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/131.

**Closed** 2015-12-15 20:26 UTC
