### ISSUE TITLE
Highway numbers seemingly placed for maximum confusion at zoom level 14

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4421] opened 2021-06-06 14:18 UTC
https://www.openstreetmap.org/?mlat=23.0686&mlon=120.1916#map=14/23.0686/120.1916
Here in the southwest corner, and northeast corner, we see "178" ambiguously placed on junctions,
"almost on purpose". It seems the renderer holds back on placing a marker, until there is some big road to cross,
then slaps it there for "maximum confusion"!
![20210606T221042](https://user-images.githubusercontent.com/1230959/120927683-4cff3880-c714-11eb-8e37-ee3d3603f5ed.jpg)

**Comment by jidanni** [comment] 2021-06-06 14:27
Moving to the northeast, we note the 南122 marker has for some reason, had the worst possible place selected for its placement.
There could only be a 1 out of 100 chance of this happening "on its own". It's almost as if some mysterious force is at work, picking the worst possible place. 
![20210606T222049](https://user-images.githubusercontent.com/1230959/120928013-913f0880-c715-11eb-934c-a482595f7ee2.jpg)
南133 ends up smack dab on top of the expressway too.
I've seen too many of these to "buy" that they are mere coincidences.

**Comment by jidanni** [comment] 2021-06-06 14:36
Back in the first image, the 南40 marker ends up right on Highway 19.
You might say, "Well there's nothing wrong with 南132, 南134."
Well yes, but perhaps that's just due to a "bug in the evil algorithm to create maximum confusion."
Or "There's just no junction with a bigger road to grab on to create confusion."
Or "Well, if it created 100% confusion, people would report bugs. So it is limited to 80%." etc.

**Comment by imagico** [comment] 2021-06-06 15:17
Duplicate of #3219.

See also #497, #951.

**Closed by imagico** 2021-06-06 15:17 UTC
