### ISSUE TITLE
Diameter of turning_circle to large

### ISSUE THREAD

**Issue by Klaus-Tockloth** [gravitystorm/openstreetmap-carto#1996] opened 2015-12-06 10:27 UTC
In conjunction with highway=service the diameter of turning_circle is too large. This affects only zoomlevel 16.

http://www.openstreetmap.org/#map=16/51.9396/7.5990

![bildschirmfoto 2015-12-06 um 11 21 15](https://cloud.githubusercontent.com/assets/5493128/11612888/2a201142-9c0c-11e5-8245-218dcc5a8f87.jpg)

Cheers Klaus

**Comment by polarbearing** [comment] 2015-12-06 17:37
Duplicate of #1931

**Closed** 2015-12-06 18:18 UTC
