### ISSUE TITLE
Inconsistencies in amenity-points

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#710] opened 2014-07-10 13:45 UTC
There are several inconsistencies in the amenity-points (https://github.com/gravitystorm/openstreetmap-carto/blob/master/amenity-points.mss) specification:

- [ ] The name of some POI is printed in bold or oblique, but it is not clear what the rationale behind that is
- [x] The name of POIs are printed in different text-sizes, again without a clear rationale.
- [x] Some POI have a larger halo-radius than others, without a clear reason.
- [x] Some landuse labels are rendered in black and others in the background color
- [x] Some POI have a smaller text-dy than others. This is likely to cause that some labels containing capitals or accents are never rendered. Note that text-dy depends both on the icon size and font size. It would probably be best to test this with a tall string such as 'ÉÉÉÉÉÉ'.
- [x] Some POI with icons, such as leisure = 'playground' (but potentially others), have no text-dy at all, meaning their text will never be rendered.
- [x] The length of text-wrap-width is inconsistent.
- [x] <s>The order of the attributes per selector is inconsistent (best resolve in separate commit)</s> =- now as #1172 .
- [x] Replace hardcoded colour values by variables

**Comment by nebulon42** [comment] 2015-05-02 21:44
I think the last point on the list was already done by #1378.

**Comment by matkoniecz** [comment] 2015-09-02 18:55
> Some POI have a smaller text-dy than others. This is likely to cause that some labels containing capitals or accents are never rendered. Note that text-dy depends both on the icon size and font size. It would probably be best to test this with a tall string such as 'ÉÉÉÉÉÉ'.

Marked as solved. I made and sometimes use https://github.com/matkoniecz/CartoCSSHelper to catch this problem.

**Comment by matkoniecz** [comment] 2015-09-03 19:07
halos will be nearly finished by #1810 - but there are also shop labels

**Comment by matkoniecz** [comment] 2016-06-19 09:17
> I tested and recommend switching to bold for all POI labels, as it significantly improves readability at cost of minor label size increase.

And now almost two years later I tested it again, and to my surprise book seems to be preferable. It is much prettier at very minor readability cost.

But I have no strong opinion on this topic.

https://cloud.githubusercontent.com/assets/899988/16176415/215deece-360f-11e6-9f0a-d6274986a06d.png
https://cloud.githubusercontent.com/assets/899988/16176416/2160c0b8-360f-11e6-81c2-ea4034bc25d7.png

https://cloud.githubusercontent.com/assets/899988/16176417/2161001e-360f-11e6-856b-0bdf30279c57.png
https://cloud.githubusercontent.com/assets/899988/16176419/2161b6a8-360f-11e6-947d-72ba4c7bdd37.png

https://cloud.githubusercontent.com/assets/899988/16176418/21610186-360f-11e6-8fa3-4887c9aba5ba.png
https://cloud.githubusercontent.com/assets/899988/16176420/2161ea4c-360f-11e6-9729-7f8d5485cf25.png

https://cloud.githubusercontent.com/assets/899988/16176421/2174a06a-360f-11e6-8b2c-3b6e89769b58.png
https://cloud.githubusercontent.com/assets/899988/16176423/2179662c-360f-11e6-901d-b0a4e74bf53e.png

https://cloud.githubusercontent.com/assets/899988/16176424/217b9cee-360f-11e6-9c50-9672b4808932.png
https://cloud.githubusercontent.com/assets/899988/16176422/21793ef4-360f-11e6-80ff-865522bc336a.png

**Comment by kocio-pl** [comment] 2016-06-19 09:55
I also think it's a bit nicer and more balanced - especially on crowded places, but works reasonably also outside them. 

We could use the bold font one day to show that something is more important (like we do with some buildings), but I prefer to use it by design, not by an accident.

**Comment by math1985** [comment] 2016-06-19 10:23
To me, the bold font is significantly more legible.

I don't have an opinion on whether or not this is an overall improvement though.

**Comment by math1985** [comment] 2016-06-19 10:32
I think the bold font is too dominant compared to street names. How would bold font but one pixel size smaller look like?

Or perhaps we can increase legibility by playing with the halo?

**Comment by kocio-pl** [comment] 2016-06-19 10:48
IMHO only halo tuning makes sense - changing size creates more inconsistency we try to get rid of (especially with https://github.com/gravitystorm/openstreetmap-carto/pull/2154).

**Comment by math1985** [comment] 2016-06-19 17:59
Yes, then I'd recommend decreasing the size for all POI. I can imagine 9pt bold is better legible than 10pt regular.

**Closed** 2016-07-06 18:54 UTC
Labels: amenity-points
