### ISSUE TITLE
Odd bridge/highway rendering quirk at z15

### ISSUE THREAD

**Issue by Jonobennett** [gravitystorm/openstreetmap-carto#1338] opened 2015-02-27 09:25 UTC
See http://osm.org/go/eup~em6m--?m=

This is very minor point, but I can't see why it's happening. At z15 *only*, the northbound carriageway of Frimley Road (http://www.openstreetmap.org/way/154292507) renders on top of the M3, but the southbound carriageway (http://www.openstreetmap.org/way/25066309) -- seemingly identically tagged -- doesn't. 

This doesn't happen at other zoom levels.

**Comment by mkoniecz** [comment] 2015-02-27 10:13
Note that name of Frimley Road (with associated halo) is rendered, road itself is not. It may happen with any name on linear feature, for example see http://www.openstreetmap.org/?mlat=50.0210&mlon=19.9319#map=16/50.0210/19.9319

![selection_004](https://cloud.githubusercontent.com/assets/899988/6410691/a01d1b34-be71-11e4-830a-a805a9913650.png)

**Comment by mkoniecz** [comment] 2015-02-27 10:18
And therefore duplicate of #478 where it was decided that complexity of fixing it seems worse than this effect.

**Closed by mkoniecz** 2015-02-27 10:18 UTC
