### ISSUE TITLE
Bridges on highway=bus_guideway

### ISSUE THREAD

**Issue by printmaps** [gravitystorm/openstreetmap-carto#2897] opened 2017-10-16 08:14 UTC
Bridges on highway=bus_guideway are currently not rendered. highway=bus_guideway is rarely used. So treat this issue with very low priority.

https://www.openstreetmap.org/#map=18/51.45873/7.05146

![bildschirmfoto 2017-10-16 um 10 11 37](https://user-images.githubusercontent.com/26689799/31601604-b4fa5adc-b25a-11e7-8e3c-df05814fe8af.png)

**Comment by matkoniecz** [comment] 2017-10-16 12:31
Duplicate of #2489

**Comment by kocio-pl** [comment] 2017-10-17 19:09
See also similar problem with highway=construction: #398.

**Comment by imagico** [comment] 2021-04-26 10:25
Closing in favor of #3581, which covers the broader underlying issue.

**Closed by imagico** 2021-04-26 10:25 UTC
Labels: roads
