### ISSUE TITLE
Issue with pedestrian areas visualization

### ISSUE THREAD

**Issue by Sirorezka** [gravitystorm/openstreetmap-carto#4832] opened 2023-06-22 15:47 UTC
### Expected behavior
Pedestrian areas should be rendered before buidlings, ponds and green areas. Green areas (for example flower bed on top of pedestrian area) and water features (fountains, ponds on top of pedestrian area) are not visible if mapped on default `layer=0` on top of pedestrian area. To fix this you need to manually add `layer=1 `to all buildings, green areas, fountains and etc.

Same issues with old tag combination "Highway=footpath".

1. Pedestrian area:
```
area=yes
highway=pedestrian
```

2. Highway Footpath area:
```
area=yes
highway=footway
```

### Actual behavior
Buidlings that are drawn on top of pedestrian area on the same layer disappear
<img width="1076" alt="image" src="https://github.com/gravitystorm/openstreetmap-carto/assets/10659800/ad502637-ae0f-49ff-97a6-98057db29601">

<img width="1224" alt="image" src="https://github.com/gravitystorm/openstreetmap-carto/assets/10659800/cbfb7451-334b-42e3-b238-a0c2e59fa38f">

**Comment by imagico** [comment] 2023-06-22 15:54
Thanks for the report, this is a duplicate of #688/#2958.  See https://github.com/gravitystorm/openstreetmap-carto/issues/172#issuecomment-1332262761 for more context.

**Closed by imagico** 2023-06-22 15:54 UTC

**Comment by Sirorezka** [comment] 2023-06-23 01:11
Hi,

Sorry, it's not clear. Why can't you downgrade "area=yes, highway=pedestrian" and "area=yes, highway=footpath" to level of "amenity=parking"? This will solve the issue/
