### ISSUE TITLE
Potential incorrect rendering of pedestrian area on top of tunnel and subway 

### ISSUE THREAD

**Issue by strongwillow** [gravitystorm/openstreetmap-carto#4370] opened 2021-04-13 21:13 UTC
Pedestrian areas (`highway=pedestrian` and `area=yes`), commonly mapped for squares, are rendered more as highway instead of area. As a result, 
1. quite often pedestrian areas are mapped as multipolygon to make room for other areas like natural=water / landuse=grass
2. they completely cover underground elements like underground railway / roads / stations

If a pedestrian area is rather small, underground facilities can still be partly seen and inferred, which is no problem. However it will be an issue if it's a very large area.

### Expected behavior

My expectation for pedestrian area is more like area (for example leisure=park), so
1. underground line elements `railway/highway` are rendered
2. underground areas elements `buildings/subway stations` are rendered
3. other land cover elements like landuse=grass can be rendered without using multipolygon

These underground elements can be rendered with lower transparency.

### Actual behavior

1. Underground elements are not rendered at all
2. Landcover elements (leisure=park/natural=*/building etc.) are not rendered without making them inner multipolygon

### Links and screenshots illustrating the problem

1. Place Charles de Gaulle: https://www.openstreetmap.org/#map=18/48.87386/2.29473

Pedestrian area is small and covers part of underground facilities, which is acceptable.

<img width="1261" alt="Screenshot 2021-04-13 at 23 09 45" src="https://user-images.githubusercontent.com/359745/114621926-9b143480-9cad-11eb-8bea-3cb72517e6de.png">

2. Guangzhou Opera House: https://www.openstreetmap.org/#map=18/23.11753/113.31907

Pedestrian area is large and covers all of underground facilities, which is unacceptable. The oneway arrows of tunnel roads are wrongly displayed.

<img width="1014" alt="Screenshot 2021-04-13 at 23 10 52" src="https://user-images.githubusercontent.com/359745/114621920-9780ad80-9cad-11eb-9317-49a14fdb5e6a.png">

**Comment by HolgerJeromin** [comment] 2021-04-14 07:36
Is this a duplicate of #529 ?

**Comment by imagico** [comment] 2021-04-14 10:07
Duplicate of #3281, see also #529, #688 and #3872.

**Closed by imagico** 2021-04-14 10:07 UTC
