### ISSUE TITLE
Subway in Kyiv, Ukraine is rendered poorly

### ISSUE THREAD

**Issue by k-bx** [gravitystorm/openstreetmap-carto#1314] opened 2015-02-15 09:26 UTC
Hi!

Subway entrance seems to be one of most important things in city-navigation. Often, when you see a map, you first look for subway-stations and then detalize your understanding from there.

For some reason, I have a feeling that OSM (at least the default one used at openstreetmaps.org website) doesn't put a subway on top of other symbols. Even worse, sometimes it actually hides one for rendering other things. Also, it renders subway-entrance as a simple blue square, while other symbols have pictograms. I find it to be really confusing:

Consider this, center of Kyiv (Ukraine): https://www.openstreetmap.org/#map=18/50.44694/30.52306

In the very middle of the screen there should be one "Хрещатик" stagion, there, between two blue men pictograms going underground. There it is on google: https://www.google.com.ua/maps/place/%28120%29+Khreshchatyk,+Kyiv,+Kyiv+city/@50.4475539,30.5220287,17z/data=!4m7!1m4!3m3!1s0x40d4ce56b2456d3b:0xd062ae171b57e947!2sKhreschatyk+St,+Kyiv,+Kyiv+city!3b1!3m1!1s0x40d4ce56b77acee3:0x98a3c079a237b1bf?hl=en

The problem is that this pictogram is hidden, while only alternative entry to this subway is shown on the right.

I find this to be very weird choice and wondered if I'm the only one who thinks so and if this is known or not.

Thank you!

**Comment by mkoniecz** [comment] 2015-02-15 13:58
Related to #851

**Comment by math1985** [comment] 2015-03-21 00:40
The station name is only rendered once, and not repeated for every entrance. I think that's not a problem.

@k-bx Which pictogram do you think is hidden?

**Comment by k-bx** [comment] 2015-03-21 09:27
@math1985 I investigated a little more and maybe it's not a renderer fault, but rather incorrect data on map itself. Please help figuring out which problems these are!

So, Khreschatyk (Хрещатик) is the most popular subway station in Kiev. It has 3 entrances, 1 of which I think is not listed on OSM at all so let's forget about it for now. One of entrances has the most people and goes to big street with the same name (Khreschatyk). The other is less popular and less people know about it and use it.

Here is an image how OSM currently renders things: http://i.imgur.com/7OOb1hh.png

Under Point 1, the most popular entrance is located. It is most well-known and used. You can see it's not shown currently at all.

Under Point 2, less popular entrance is located. It is rendered as a blue dot, which makes it hard to figure out that it's a subway (common Kiev citizen would recognize subway by an "M" letter).

So, now let's take a look how editor shows us these objects: http://i.imgur.com/qrRhA8o.png

Under Point 1, the "Subway Entrance" object is located.

Under Point 2, the "Railway Station" object sits.

And, just to have some comparison, let's take a look and analyze how Google Maps are rendering same piece: https://i.imgur.com/pCMhFav.png

You can see Google is rendering "M" logo, which makes it very intuitive to see where an entrance is. Also, it renders less popular entrance as the main one, making it bigger and putting some text there, which confuses a bit, and I think could be changed. (On the right, you can see one more entrance that's missing on OSM currently, I'll add it after we figure out this bug).

So, I'm not sure how to change things in this situation, and I hope you can help me, but I see the following problems:

1. It would be absolutely best to render a subway-entrance with an "M" logo of Kiev's subway logo.
2. It would be super to render this logo for all entrances, making the most popular the biggest, while others smaller and with hover-only description.
3. The most popular entrance to station which most people use should be rendered at least in some form.

@math1985 what do you think can be done in this situation? Thanks for your help in advance!

**Comment by math1985** [comment] 2015-03-21 09:55
This is at least partially duplicate with #851

**Comment by k-bx** [comment] 2015-03-21 09:57
Fully agreed, so we can forget about "rendering subway entrance" problem, since it is indeed confused with "underground walking" currently.

**Comment by k-bx** [comment] 2015-03-21 10:00
@math1985 also, I found 3rd entrance, it's marked as "Railway" object currently. So, we have 3 different objects, which are entrances to subway, yet each of them is marked as a different object, a "Railyway station", a "Subway entrance" and a "Railway". How do we deal with this mess? Should the last one be edited to become a "Railway Entrance"?

**Comment by math1985** [comment] 2015-03-21 11:30
* The place (underground) where the metro stops should be railway=station
* The place (above ground) where you can enter the station should be railway=subway_entrance

**Comment by k-bx** [comment] 2015-03-23 08:04
@math1985 I want to ask you for help again :)

So, the first dot (the one that is the most popular entry and that's not rendered clearly) is set like this in editor: https://i.imgur.com/5eBrLKr.png . I made additional screenshot of unfolded "tags": https://i.imgur.com/knOQqCX.png .

Now, if I edit the third entry (which I thought is not present initially), I see this: https://i.imgur.com/ch9kkWH.png

The problem I have is: when I try to edit the third dot (field "Railway") and type text "Subway Entrance" there, it doesn't autocomplete with any result (https://i.imgur.com/hph7tZi.png)!

Please help again. Thank you!

**Comment by math1985** [comment] 2015-03-23 09:44
The third entrance has a missing _, it should be "subway_entrance" rather than "subway entrance". I'm not sure why it doesn't autocomplete, I guess if it doesn't autocomplete it's best to enter the tags manually.

**Comment by kocio-pl** [comment] 2016-09-24 20:42
I guess this issue is now just a duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/645?

BTW: I would move the station name on the centre, in this case - on the platform. That's what I've done in Warsaw.

**Comment by kocio-pl** [comment] 2016-12-15 04:25
@k-bx Refs will be rendered soon, because the [corresponding code](https://github.com/gravitystorm/openstreetmap-carto/pull/2370) was merged. Do you want to change something else?

**Comment by k-bx** [comment] 2016-12-15 07:30
@kocio-pl can you help me here please, since I'm not experienced with OSM yet. So if I'll use an editor, should I edit the entrance and add a name field there in order for it to show up? Adding it like this currently: https://i.imgur.com/rX4PkeG.png

**Comment by kocio-pl** [comment] 2016-12-15 12:49
The name rendering for subway entries was rejected in the ticket I linked. See [what the `name` and `ref` keys are for](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dsubway_entrance).

**Comment by k-bx** [comment] 2016-12-15 15:30
@kocio-pl I see, thanks for the reference. It seems that neither `name` nor `ref` are related to the problem I originally wanted to solve and they should not be filled in due to that wiki page.

**Comment by kocio-pl** [comment] 2016-12-15 15:36
Do you see any things that could be still fixed given OSM and this style limitations and rules? Otherwise I would like to close this issue.

**Comment by k-bx** [comment] 2016-12-16 14:26
@kocio-pl I still think it's quite a major issue and there should be a way to resolve it. Just to re-state the problem, here's a comparison with Google maps and Yandex maps of the same piece:

- Google: https://i.imgur.com/M3WQWEi.png
- Yandex: https://i.imgur.com/Jai012l.png
- OSM: https://i.imgur.com/ZDoqHiT.png

Please notice the round building on top-right of the screenshots, it's a subway entrance and is clearly marked as such on other maps. OSM does have an information about that that's visible by a very small icon https://i.imgur.com/G14vSsI.png That icon is rendered smaller than some Pubs and Restaurants, which clearly seems like a wrong thing to do, since it's one of the central objects in city transportation and orientation.

I'm not an expert on what exactly are the limitations that we have here, but I see currently that we could at least:
- render it on smaller zoom level, basically same as rendered for Subway station itself
- render the name besides an icon
- render a better icon, for example OSM editor has a beautiful one that's much more like subway wagon on it https://i.imgur.com/PVx90GD.png

If none of those are possible, that's a pity, but of course feel free to close the ticket then. Thank you for your assistance anyway!

**Comment by kocio-pl** [comment] 2016-12-16 15:00
We've made that icon to be universal, because we avoid any country-specific rendering, so we won't change it probably (unless you think it could be better - then open a new ticket). 

I also doubt that we would render it earlier (but you can also try to open specific ticket about it). 

Name rendering was rejected, as I have mentioned, and you probably saw that the name is a name of the entry (if it has one, like "South entry"), not the station it leads to, so this is already not possible.

I'm closing it then, but thanks for your propositions, anyway!

**Closed by kocio-pl** 2016-12-16 15:00 UTC
Labels: amenity-points
