### ISSUE TITLE
Displaced Label (specific case)

### ISSUE THREAD

**Issue by ServusWorld** [gravitystorm/openstreetmap-carto#3044] opened 2018-01-30 14:48 UTC
A Label of a building is rendered somewhere else than it should be.

**Zoom levels:** 18, 17, 16
**OpenStreetMap Link:** https://www.openstreetmap.org/#map=17/48.26004/16.36901 (text "Karl-Marx-Hof" in the middle of the map)
**Affected object:** Relation 64435 - https://www.openstreetmap.org/relation/64435
**Wrong coordinates of Label:** 48.2602, 16.3694
**Where it should be placed:** 48.2526, 16.3653

**Comment by kocio-pl** [comment] 2018-01-30 17:59
Thanks for reporting. It seems like a duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/1465.

**Closed by kocio-pl** 2018-01-30 17:59 UTC
Labels: duplicate
