### ISSUE TITLE
render bridge encased highways without half round end caps

### ISSUE THREAD

**Issue by cm8** [gravitystorm/openstreetmap-carto#2131] opened 2016-05-26 11:19 UTC
See [e.g. this view](http://www.openstreetmap.org/#map=18/51.30931/12.39084) for the implications of rendering half round end caps of bridge=yes layer=1 tagged highways.

**Comment by matkoniecz** [comment] 2016-05-26 18:55
duplicate of #934 closed as wontfix ("If someone has a bright idea for resolving, implementations welcome.")

**Closed by matkoniecz** 2016-05-26 18:55 UTC
