### ISSUE TITLE
Render area:highway= when zoomed in

### ISSUE THREAD

**Issue by krolinventions** [gravitystorm/openstreetmap-carto#4954] opened 2024-04-14 22:52 UTC
### Expected behavior

For pedestrian navigation (or even when lost/confused with another mode of transport) it is very useful to see the actual shape of all the roads/sidewalks/cycle paths. I would like to tag these with area:highway=, according to the standard that seems to have developed, and have them visible on the map.

This has been discussed before a number of times. The main one seems to be https://github.com/gravitystorm/openstreetmap-carto/issues/180

Feel free to re-open that issue. It's not something I can do myself.

If you need a patch, I can give that a try. In that case, some pointers on what files to look in would be welcome.

### Actual behavior

You only see the highway way itself, with confusing background colors caused by the general tagged area (like industrial, hospital, park etc.).

### Screenshots with links illustrating the problem

This is an area which would be useful to micromap. Even people arriving by car will have to walk a bit to get here. You can see that there is very little to orient yourself on. And this is after I put in the pedestrian zone, which already helps a lot.

![image](https://github.com/gravitystorm/openstreetmap-carto/assets/1233620/4118ca60-770d-4b42-bcbc-5d3817c368b9)
https://www.openstreetmap.org/#map=19/52.16598/4.47947

Example of the confusing colors. Users will think that the road is pink and there's sand on the sidewalk:
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/1233620/ae52c77d-533b-4134-8920-f77dc08ab6d4)
https://www.openstreetmap.org/#map=19/52.16830/4.47723

### Q & A

Q: Isn't this complicated to render?
A: Grass, water, forests, and pedestrian areas render fine, this can be done the same way.

Q: What about tunnels?
A: I'm not sure there's even something sensible to show, so let's not map this inside tunnels for now. From a rendering standpoint, consider it undefined behavior and feel free to screw up in interesting ways.

Q: What about overpasses crossing other overpasses?
A: Not sure how relevant this is, but drawing a thin white border outside an element is a common clue that this element is on top.

Q: Don't we need a completely new system to render highways? That would solve all our problems.
A: Maybe, but that will be at least five years. Remember that the perfect is the enemy of the good.

Q: It's just clutter, embrace the schematic depiction of a map.
A: You might as well stop rendering trees and water and even buildings, and people seem to appreciate those.

Q: Isn't this harder to map?
A: It's slightly more work, but it's not mandatory. Most places don't need this, only the highly traveled ones, and for those there's a lot of people around to do the mapping.

Q: Won't this cause people to only map the area and not put in a highway?
A: They can try, but (as someone suggested) if you just not render the area when zoomed out they will figure out something is wrong quickly enough. Also, editors could warn about an area:highway that does not actually have a highway in it.

Q: What colors to use?
A: I suggest standardized colors per region. Here in the Netherlands we'd do fine with making roads black, cycle paths red and sidewalks grey. Some other area's may need green cycle paths. Alternatively, we could use the surface that's specified, but that would make it less schematic.

**Comment by pnorman** [comment] 2024-04-15 06:01
Duplicate of #180.

**Closed by pnorman** 2024-04-15 06:01 UTC
