### ISSUE TITLE
Icon and Text is not placed inside (centered) of building=church

### ISSUE THREAD

**Issue by HostedDinner** [gravitystorm/openstreetmap-carto#2863] opened 2017-09-23 11:26 UTC
I came accross this chuch, were the label and the icon is somehow not centered on the bulding, rather on the outline: http://osm.org/go/0DaRJKnUy It looks a little bit strange, as there is plenty of space inside to print the label.
The tagging is correct and all tags are on the outline of the building and no tag is on an outer point or something like this.

This church http://osm.org/go/0DaRh6yRC looks also suspicious.

**Comment by kocio-pl** [comment] 2017-09-23 11:35
Thanks for reporting, but it's a duplicate of #2511, #2709 and #1465, so I'm closing it.

**Closed by kocio-pl** 2017-09-23 11:35 UTC
Labels: duplicate
