### ISSUE TITLE
Add rendering for vending=cigarettes

### ISSUE THREAD

**Issue by tbertels** [gravitystorm/openstreetmap-carto#2542] opened 2017-01-08 06:37 UTC
wiki: [vending=cigarettes](https://wiki.openstreetmap.org/wiki/Tag:vending%3Dcigarettes)
taginfo: [about 15 000 uses](https://taginfo.openstreetmap.org/tags/vending=cigarettes).

**Comment by kocio-pl** [comment] 2017-01-08 07:15
It's partial duplicate of #1561, closing it.

**Closed by kocio-pl** 2017-01-08 07:15 UTC

**Comment by tbertels** [comment] 2017-01-08 07:32
This isn't a duplicate, #1561 is about a generic icon for vending_machine, and was closed because of that.
