### ISSUE TITLE
Is missing tram signature a carto issue?

### ISSUE THREAD

**Issue by manfredbrandl** [gravitystorm/openstreetmap-carto#2810] opened 2017-09-06 10:49 UTC
Line 365772420 ( http://www.openstreetmap.org/way/365772420 ) shows no tram signature although Linie 197669353 ( http://www.openstreetmap.org/way/197669353 ) does and both have identical attributes:
![image](https://user-images.githubusercontent.com/5360273/30108241-de416ad4-9301-11e7-822d-d2492845115d.png)

**Comment by dieterdreist** [comment] 2017-09-06 10:54
looks more like a server hickup, as both ways have the same tags there's nothing we can do in the style

**Comment by HolgerJeromin** [comment] 2017-09-06 11:06
I am pretty sure this is a duplicate of the known regression #2781 
The different rendering are probably an outdated rendering tile.

**Comment by dieterdreist** [comment] 2017-09-06 11:09
2017-09-06 13:06 GMT+02:00 Holger Jeromin <notifications@github.com>:

> I am pretty sure this is a duplicate of the known regression #2781
> <https://github.com/gravitystorm/openstreetmap-carto/issues/2781>
> The different rendering are probably an outdated rendering tile.
>

you are probably right, the tram has in the meantime vanished from the
other tile as well...

**Closed** 2017-09-06 14:59 UTC
Labels: duplicate

**Comment by manfredbrandl** [comment] 2017-09-07 08:45
Now the tram has reappeared on both lines
![image](https://user-images.githubusercontent.com/5360273/30154053-f2f33680-93b8-11e7-8c07-b9e45185dcac.png)
Is this really a duplicate fo #2781 ?

**Comment by pnorman** [comment] 2017-09-07 11:12
> Now the tram has reappeared on both lines

Yes, looks like it.
