### ISSUE TITLE
Suggestion for rendering barrier=kerb again

### ISSUE THREAD

**Issue by swedneck** [gravitystorm/openstreetmap-carto#4230] opened 2020-10-21 12:25 UTC
@kocio-pl wanted me to open a new issue about this:

I suggest that kerbs could be rendered as a light gray line, possibly with triangles or other markers on one side of the line, like in JOSM/iD.

![image](https://user-images.githubusercontent.com/40505480/96718441-52d42380-13a8-11eb-9391-45bb5212b38a.png)

**Comment by kocio-pl** [comment] 2020-10-21 12:39
Thanks, that sounds interesting. I guess it would be good to have some softer rendering for lowered kerbs and with height=0, for example triangles lacking filling, shorter, replaced with half circles etc.

**Comment by imagico** [comment] 2020-10-21 14:36
Duplicate of #3714.  @kocio-pl - suggest you re-open that if there are any meaningful new ideas for rendering kerbs (as it is was the consensus conclusion - see https://github.com/gravitystorm/openstreetmap-carto/issues/3714#issuecomment-552428534, https://github.com/gravitystorm/openstreetmap-carto/issues/3714#issuecomment-557010763)

Anyone who wants to work on something along these lines is well advised to read up the past discussion there - which is why it is established practice to re-open existing issues as needed instead of starting new duplicates.

**Comment by swedneck** [comment] 2020-10-22 12:38
I was told to open a new issue, so i opened a new issue. Sorry about that.

**Comment by kocio-pl** [comment] 2020-10-26 11:30
I thought it makes more sense to start a new proposition in a new ticket, but that's OK to move the discussion there, sorry for the inconvenience. Could you do that once more?

**Comment by jeisenbe** [comment] 2020-11-05 19:36
Closing this issue as a duplicate of #4230

**Closed by jeisenbe** 2020-11-05 19:36 UTC
Labels: barrier, duplicate
