### ISSUE TITLE
Suggested: Rendering: Passing Place

### ISSUE THREAD

**Issue by Tysseract** [gravitystorm/openstreetmap-carto#4367] opened 2021-04-11 00:26 UTC
### Rationale
The [Passing Place](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpassing_place) ("turnout" in the US) has been [used over 30k times](https://taginfo.openstreetmap.org/tags/highway=passing_place) but I have a hard time believing there are that few places matching the description. Rendering is often a chicken-or-the-egg problem, but I believe the Passing Place has enough use to be worth rendering and enough momentum that more people will tag them when they start being rendered. 
### Suggestion
![Rendering Suggestion](https://upload.wikimedia.org/wikipedia/commons/9/98/Mapping-Features-Passing-Place.png)
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpassing_place#Possible_Rendering
My suggestion for tagged points is to create a semicircle version of the rendering for the [Turning Circle](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dturning_circle) on the side of the road the Passing place is on (value of passing_place=). We could also use the same full circle rendering of Turning Circle in the event passing_place is undefined or =both, or—if the semicircle is hard to program—for all passing places.
Although Passing Places aren't officially supported for ways, they could be rendered the same as [highway=service](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dservice)

**Comment by Tysseract** [comment] 2021-04-11 01:12
Just realized this was already an open suggestion but I still think it needs more attention.
#2356

**Comment by pnorman** [comment] 2021-04-11 01:51
Duplicate of #2356

**Closed by pnorman** 2021-04-11 01:51 UTC
