### ISSUE TITLE
Do not render water areas names at z2, z3

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#3705] opened 2019-03-05 13:19 UTC
### Expected behavior

No water area names are rendered at z2 (only oceans are a potential fit and ocean naming is a subjective cultural issue, there are even multiple competing ideas how many oceans exist, making it a really poor idea)

### Actual behavior

![selection_001](https://user-images.githubusercontent.com/899988/53807772-b8b03500-3f50-11e9-88ee-23b3e2f3aa15.png)

I strongly suspect tagging for renderer here, but it is a separate problem.

### Links and screenshots illustrating the problem

See above

**Comment by imagico** [comment] 2019-03-05 13:36
Duplicate of #3634.

The solution would IMO be to stop rendering labels based on way_area for features for which there is no visual feedback on the geometry in the map.  Moving the threshold up to z4 would just attempt hiding the problem but not solve it.  The incentive for free style label polygon drawing with no basis in verifiable reality is not limited to z3 and below.

**Comment by matkoniecz** [comment] 2019-03-05 13:40
Thanks for spotting duplicate!

**Closed** 2019-03-05 13:40 UTC
Labels: duplicate
