### ISSUE TITLE
tunnels are covered by highway=* with area=yes

### ISSUE THREAD

**Issue by lsyrotas** [gravitystorm/openstreetmap-carto#2001] opened 2015-12-09 15:04 UTC
Main metro stations in my hometown are located below pedestrian streets.
Those stations have entrance on the pedestrian street and tunnels under it.

The tunnels are usually tagged with : `highway=footway`, `tunnel=yes`, `level=-1`, (sometimes `layer=-1`).
The pedestrian streets are usually tagged with : `highway=pedestrian`, `area=yes`.

However, the underground tunnels are not rendered by mapnik when under these pedestrian streets.

[There is a perfect example here](http://www.openstreetmap.org/#map=19/50.63163/3.06073)

The underground tunnel __is not rendered when under the pedestrian street but is rendered correctly under the__ `landuse=grass` that are represented on this example....

**Comment by Circeus** [comment] 2015-12-13 13:07
A particularly silly aspect is that building will "punch through" the pedestrian part an reveal the tunnels in question: http://www.openstreetmap.org/#map=19/42.65058/-73.75884

**Comment by polarbearing** [comment] 2015-12-13 17:48
While I agree that it looks strange, the reason that the way inside the building is visible is that the building is the inner ring of the pedestrian multipolygon. Thus where the building is, there is no pedestrian area, thus it does not "punch through".

**Comment by matkoniecz** [comment] 2016-06-21 11:41
It turns out to be duplicate of #529

**Closed by matkoniecz** 2016-06-21 11:41 UTC
Labels: roads
