### ISSUE TITLE
Roundabout doesn't appear on map

### ISSUE THREAD

**Issue by matt-twam** [gravitystorm/openstreetmap-carto#2508] opened 2016-12-13 12:14 UTC
[Way 5005597](http://www.openstreetmap.org/way/5005597) doesn't appear to be rendering at the moment despite having what I believe are accurate tags applied (highway=primary & junction=roundabout). For example, [way 3806378](http://www.openstreetmap.org/way/3806378) a few miles down the road is rendering correctly with those two tags.

Is this a bug or am I missing something?

Thanks.

**Comment by SomeoneElseOSM** [comment] 2016-12-13 12:52
(just for info) it's not a rendering server glitch because I'm seeing the same issue on a tile server using a map style that diverged from this one a couple of years ago.  It does appear to be the only junction=roundabout;historic=roman_road in the world.

http://overpass-turbo.eu/s/kCM

**Comment by matt-twam** [comment] 2016-12-13 13:12
How's that for an edge case! Just to confirm - do you think that the historic=roman_road tag is the cause of the problem? I don't mind decoupling the tag from the roundabout as suggested, but is there a wider issue here regarding an additional tag preventing something from being rendered? 

I did notice that the A29 directly north & south of the roundabout is also tagged with historic=roman_road, so is it a combination of highway=primary, junction=roundabout and historic=roman_road that is the issue?

**Comment by math1985** [comment] 2016-12-13 13:45
Closed loops tagged with historic are always treated as areas. So the problem is a combination of a closed loop, highway=* and historic=*.

Cutting the roundabout in two semicircles should be a roundabout.

On our side, we should exclude historic=roman_road from the list of tags that are a polygon by default.

**Comment by nebulon42** [comment] 2017-03-22 22:21
The problem is that `historic=roman_road` is only a draft for a proposed feature and it has been noted that a likely better tagging for it  would be `historic=road` and maybe `historic:civilization=roman`. So a exception for `historic=road` would be conceptually okay for me. In reality `historic=road` is never used and `historic=roman_road` has 2706 uses. Both are not really established.

As I think there is no action to be taken for us right now I'm closing this.

**Closed by nebulon42** 2017-03-22 22:21 UTC
Labels: bug, lua, roads

**Comment by dieterdreist** [comment] 2017-03-23 00:04
2017-03-22 23:21 GMT+01:00 Michael Glanznig <notifications@github.com>:

> The problem is that historic=roman_road is only a draft for a proposed
> feature and it has been noted that a likely better tagging for it would be
> historic=road and maybe historic:civilization=roman.
>

I'm not sure anymore that a generic "road" together with a tag for the
culture that built it would be better, after all, people seem to prefer
"roman_road". 2706 are not few uses for this feature.

**Comment by nebulon42** [comment] 2017-03-23 13:21
True, this number is not so insignificant, but no documentation on the Wiki yet and the proposal never went anywhere. This has to be addressed in the Post-Lua-Era anyway, so we can re-open later if it comes up again.
