### ISSUE TITLE
Add rendering for vending=public_transport_tickets

### ISSUE THREAD

**Issue by tbertels** [gravitystorm/openstreetmap-carto#2544] opened 2017-01-08 06:40 UTC
wiki: [vending=public_transport_tickets](https://wiki.openstreetmap.org/wiki/Tag:vending%3Dpublic_transport_tickets)
taginfo: [about 12 000 uses](https://taginfo.openstreetmap.org/tags/vending=public_transport_tickets).

**Comment by kocio-pl** [comment] 2017-01-08 07:14
It's partial duplicate of #1561, closing it.

**Closed by kocio-pl** 2017-01-08 07:14 UTC

**Comment by tbertels** [comment] 2017-01-08 07:32
This isn't a duplicate, #1561 is about a generic icon for vending_machine, and was closed because of that.
