### ISSUE TITLE
man_made=bridge ignores layers

### ISSUE THREAD

**Issue by james2432** [gravitystorm/openstreetmap-carto#3203] opened 2018-04-27 18:37 UTC
https://www.openstreetmap.org/#map=18/45.42231/-75.62625
![image](https://user-images.githubusercontent.com/498547/39379141-61f957f0-4a28-11e8-94e9-a38c96300f89.png)

The bridge should render over < it's layer value in this case it should render over the building and the roads below

**Comment by sommerluk** [comment] 2018-04-27 19:09
Duplicate of #1799 and #2509

**Closed** 2018-04-28 08:35 UTC
Labels: duplicate, roads

**Comment by matkoniecz** [comment] 2018-04-28 08:54
See linked issues. Situation is not ideal but there is no good idea how it should be improved.

Even if bridges should hide everything below (what will make map worse in some places and better in other, it should be analysed whatever overall effect is positive), they're are serious technical issues hope it should be implemented (road layer is already very complex so I would not recommend it as a good starting point for getting involved with improving map style).

**Comment by james2432** [comment] 2018-04-28 09:50
Not necessarily hide, but there could be an alpha channel on bridges that allow you to see through them.

**Comment by dieterdreist** [comment] 2018-04-28 16:29
sent from a phone

> On 28. Apr 2018, at 10:54, Mateusz Konieczny <notifications@github.com> wrote:
> 
> Even if bridges should hide everything below (what will make map worse in some places and better in other, it should be analysed whatever overall effect is positive), they're are serious technical issues hope it should be implemented


if we agree it is too complicated to fix it now, or moving bridge areas in between the roads layers would increase complexity in an undesirable way, maybe we could tweak the style to account for it, e.g.render only an outline for bridges (there would still be issues with the current position, it would probably have to move above the roads layer and get dashed)

**Comment by matkoniecz** [comment] 2018-04-28 16:31
I doubt whatever rendering only outlines would be readable at all.

**Comment by HolgerJeromin** [comment] 2018-05-01 21:17
> Not necessarily hide, but there could be an alpha channel on bridges that allow you to see through them.

Alpha channel would change color depending on the (landuse?) color under the bridge. Thats why this is in general not used in this style
