### ISSUE TITLE
Render highway=trailhead

### ISSUE THREAD

**Issue by paulw1010** [gravitystorm/openstreetmap-carto#4195] opened 2020-08-25 02:13 UTC
Trailheads would be a beneficial feature to render, and are featured on many other mapping programs and recreational maps. They are normally mapped as nodes; a few are (incorrectly?) tagged on parking lots located adjacent a trail.

Trailheads could be rendered with a common hiker icon, colored in green, along with a name if also tagged:
![hiker-icon](https://user-images.githubusercontent.com/55370518/91114791-bd8e0a80-e656-11ea-92d6-c6f11639bd87.png)

Link to OSM wiki page documenting the tag: https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrailhead

**Comment by imagico** [comment] 2020-08-25 08:54
Duplicate of  #3585.

**Closed by imagico** 2020-08-25 08:54 UTC
