### ISSUE TITLE
Different rendering for access=agricultural, forestry and delivery

### ISSUE THREAD

**Issue by hikemaniac** [gravitystorm/openstreetmap-carto#2943] opened 2017-11-10 21:16 UTC
It would be very helpful to have highway objects with _[access=agricultural](https://taginfo.openstreetmap.org/tags/access=agricultural)_, _[access=forestry](https://taginfo.openstreetmap.org/tags/access=forestry)_ and _[access=delivery](https://taginfo.openstreetmap.org/tags/access=delivery)_ rendered the same as _access=no_ or _access=private_. This would reduce confusion and probably also have more mappers adding the objects with the more detailed tags instead of just _access=no_. What do you think about it?

**Comment by matkoniecz** [comment] 2017-11-11 10:14
Can you give examples of ways where it would help?

**Comment by aceman444** [comment] 2017-11-11 15:45
Beware that in many cases you actually want to tag motor_vehicle=forestry (or delivery) on those roads as often pedestrians and cyclists may be allowed. Rarely is access=agricultural/forestry/delivery the correct tag. And I think it was already discussed in some other reports that rendering car-only (or motor_vehicle) restrictions could be complicated/made the map car-centric.

**Comment by matkoniecz** [comment] 2017-11-11 16:16
Closing as duplicate of #1308 See https://github.com/gravitystorm/openstreetmap-carto/issues/1308#issuecomment-140999773 for reasons why it was rejected.

Please comment in #1308 iff there a country where access=agricultural/forestry/delivery is widespread and correct tagging

**Closed** 2017-11-11 16:17 UTC
Labels: duplicate, roads

**Comment by SomeoneElseOSM** [comment] 2017-11-11 17:15
Re the "delivery" part of the question (not mentioned at https://github.com/gravitystorm/openstreetmap-carto/issues/1308 ) I'd suggest that https://www.openstreetmap.org/way/228249285 is arguably correct tagging.  You could make the case for private as well of course.

**Comment by matkoniecz** [comment] 2017-11-11 17:48
I would not expect that access=delivery is correct anywhere - see https://wiki.openstreetmap.org/wiki/Talk:Key:access#is%20*=delivery%20correct%20for%20any%20case? for explanation and discussion

**Comment by dieterdreist** [comment] 2017-11-16 12:14
2017-11-11 18:15 GMT+01:00 SomeoneElseOSM <notifications@github.com>:

> Re the "delivery" part of the question (not mentioned at #1308
> <https://github.com/gravitystorm/openstreetmap-carto/issues/1308> ) I'd
> suggest that https://www.openstreetmap.org/way/228249285 is arguably
> correct tagging. You could make the case for private as well of course.
>

but this is surely an extremely rare case which we don't want to cater for
on this generic map style, no?

**Comment by SomeoneElseOSM** [comment] 2017-11-16 14:48
@dieterdreist It's not that rare: https://taginfo.openstreetmap.org/search?q=delivery#values .  FWIW I figured it was worth adding to https://map.atownsend.org.uk/maps/map/map.html#zoom=19&lat=53.959323&lon=-1.069193 (though obviously OSM Carto has different inclusion guidelines).

**Comment by dieterdreist** [comment] 2017-11-16 23:32
sent from a phone

> On 16. Nov 2017, at 15:48, SomeoneElseOSM <notifications@github.com> wrote:
> 
> @dieterdreist It's not that rare: https://taginfo.openstreetmap.org/search?q=delivery#values


I meant these (113 ways): https://taginfo.openstreetmap.org/tags/service=delivery
