### ISSUE TITLE
Locale-aware Typography

### ISSUE THREAD

**Issue by Artoria2e5** [gravitystorm/openstreetmap-carto#2608] opened 2017-04-11 16:04 UTC
Quite a few Unified CJK Ideographs ("Chinese Characters") are written in different ways in different countries/languages. Such difference is why Adobe and Google has released a bunch of local variants for their Source Han Sans/Noto Sans CJK fonts. In Mapnik for example, at https://www.openstreetmap.org/way/25097203, the "门" (door, gate) character (the last char on its own line) happens to be presented in the Japanese form with a vertical stroke over its rectangular body:

![image](https://cloud.githubusercontent.com/assets/6459309/24877043/e20d59dc-1dfb-11e7-94fe-3102fe4b7c3f.png)

Since these locations are found in China, a Chinese form is expected for these characters. Such form is shown below, from a screenshot of, well, this issue:
![image](https://cloud.githubusercontent.com/assets/6459309/24877055/eb01ed82-1dfb-11e7-8154-8c6eba8a1c6c.png)

(There are quite a few other "门"s to the north.)

I understand that OSM's current rendering, generally only taking the `name` part without a language label attached, cannot reliably infer the language used for the string and therefore the `locl` value to use for font rendering (as well as just the language value to feed into stuff like fontconfig). But with a crude heuristic based on national/regional borders, OSM should be able to get most of the cases right.

A Latin-script (Romanian) example of such a `locl` feature is available at https://en.wikipedia.org/wiki/Pango#Support_for_OpenType_features. Also try pasting "关门吃草逛街" into the four previews at https://typekit.com/lists/source-han-sans.

(moved from mapnik/mapnik#3655)

**Comment by nebulon42** [comment] 2017-04-11 17:40
Thanks for the comprehensive description of the issue. Just a few remarks. That this style is referred to as "Mapnik" is a left-over from previous days where there was a "Mapnik" and "Osmarender" rendering. Today it is often less confusing to refer to this style as openstreetmap-carto or osm-carto.

We tend to avoid country-specific renderings as it is complex and leads to all sorts of problems and wishes. Would there be another way to determine from the OSM data what font to use apart from evaluating boundaries? Would Mapnik (the software) understand this `locl` or language setting? How odd does this Japanese char look to a Chinese reader? Mildly odd, very odd, outrageous?

**Comment by Artoria2e5** [comment] 2017-04-11 19:49
> Would there be another way to determine from the OSM data what font to use apart from evaluating boundaries?
Perhaps this can be done by equivalence checks between `name` and language-specified `name:<lang>` keys. Many nodes only have a un-languaged `name` still...

> Would Mapnik (the software) understand this locl or language setting?
Not sure, to be honest. It seems to use some harfbuzz which does do the OpenType part right.

> How odd does this Japanese char look to a Chinese reader? Mildly odd, very odd, outrageous?
Pretty odd I would say. 门's difference is probably one of the most obvious in all differences seen between jp/cn variants of a Chinese character. Unfortunately both cultures have a lot of gates to deal with.

**Comment by pnorman** [comment] 2017-04-11 21:33
Duplicate of #2208

**Closed by pnorman** 2017-04-11 21:33 UTC
Labels: duplicate, text
