### ISSUE TITLE
Add rendering for vending=excrement_bags

### ISSUE THREAD

**Issue by tbertels** [gravitystorm/openstreetmap-carto#2543] opened 2017-01-08 06:39 UTC
wiki: [vending=excrement_bags](https://wiki.openstreetmap.org/wiki/Tag:vending%3Dexcrement_bags)
taginfo: [about 12 000 uses](https://taginfo.openstreetmap.org/tags/vending=excrement_bags).

**Comment by kocio-pl** [comment] 2017-01-08 07:14
It's partial duplicate of #1561, closing it.

**Closed by kocio-pl** 2017-01-08 07:14 UTC

**Comment by tbertels** [comment] 2017-01-08 07:32
This isn't a duplicate, #1561 is about a generic icon for vending_machine, and was closed because of that.
