### ISSUE TITLE
Icon and black dot artefact with tourism=guest_house and amenity=restaurant

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#3081] opened 2018-02-21 14:05 UTC
It seems that ways with tourism=guest_house and amenity=restaurant sometimes produce a black dot in addition of the icon:
https://www.openstreetmap.org/way/154180596#map=19/48.94396/13.80058&layers=D
![08f090a5-1a9b-455f-837c-9b80df55cd22](https://user-images.githubusercontent.com/7693297/36483733-3e86f65e-1717-11e8-95db-b492f2b6d7c8.png)

https://www.openstreetmap.org/way/140294440#map=19/47.94632/14.89645&layers=D
![bb4ca49f-28d9-49be-ad9a-43a5446d9a5b](https://user-images.githubusercontent.com/7693297/36483744-443c7dee-1717-11e8-8c40-06cff3f4ce80.png)

https://www.openstreetmap.org/way/125420536#map=19/49.00323/12.20109&layers=D
![d3a0f8a5-914a-44d2-9600-02b5778147f9](https://user-images.githubusercontent.com/7693297/36483780-6204dbaa-1717-11e8-8601-ffb096185dc1.png)

Here's a query to check for more instances: http://overpass-turbo.eu/s/wmi

My guess is that there are some different methods of finding the placement for an icon at work, and I  suspect this might not only be happening with these two tags. 

Notice that the label in the third example is centered under the black dot, the guest_house icon looks displaced.

**Comment by dieterdreist** [comment] 2018-02-21 14:25
> I’m not sure having both tags on the same object is a good idea. Do they share all properties (e.g. do they have the same opening hours)? 

The actual situation rather than something being both, a restaurant and a guest house, is more likely a guest house having also a restaurant (i.e. I suspect a mapping problem)

**Comment by kocio-pl** [comment] 2018-02-21 14:55
I think this is a Mapnik problem with shaded SVGs - probably it's tourism=guest_house which produces bad output, not the amenity=restaurant. I will close it now, since it's most probably duplicate of #2787 and the main ticket, which can result in fixing this bug, is in Mapnik repo: https://github.com/mapnik/mapnik/issues/3813.

**Closed by kocio-pl** 2018-02-21 14:55 UTC
Labels: duplicate
