### ISSUE TITLE
Render the name of man_made=bridge inside the polygon

### ISSUE THREAD

**Issue by LucFreitas** [gravitystorm/openstreetmap-carto#2364] opened 2016-09-23 01:35 UTC
The `man_made=bridge` name appears out of curved shape of the bridge.
![ponte](https://cloud.githubusercontent.com/assets/19976610/18771374/d286ad12-8114-11e6-82e0-ece5d42efc97.png)
[http://www.openstreetmap.org/#map=18/-20.32355/-40.28492](url)

_Sorry for my english!_

**Comment by HolgerJeromin** [comment] 2016-09-23 07:24
This is the object:
http://www.openstreetmap.org/way/443482563#map=16/-20.3256/-40.2880

**Comment by kocio-pl** [comment] 2016-11-16 00:26
This is related to Mapnik and the way it handles placing names for complex shapes (like arc), so it's probably a duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/2428 or just another issue to report here:

https://github.com/mapnik/mapnik/issues/

**Comment by HolgerJeromin** [comment] 2016-11-16 03:12
Our landuse polygons have 
point-placement: interior;
Perhaps this is missing on bridges.

**Comment by kocio-pl** [comment] 2016-11-16 16:50
Thanks for the hint! Using _text-placement: interior;_ (text has its own options) really helped here, so I'm reopening this issue:

![5pseblz5](https://cloud.githubusercontent.com/assets/5439713/20356315/796ae14a-ac24-11e6-9518-04bfee41928e.png)

However it looks a bit different and I don't know why. If there are no unwanted side effects possible, I will create PR for this issue.

**Closed** 2016-11-18 22:20 UTC
Labels: text
