### ISSUE TITLE
inner area not rendered over enclosing one

### ISSUE THREAD

**Issue by a-pirard** [gravitystorm/openstreetmap-carto#2286] opened 2016-08-17 02:05 UTC
I have mapped a miniature golf [269106021](http://www.openstreetmap.org/way/269106021) and, to my surprise, it wasn't rendered.
To my even greater surprise, there is a rendering defined.
But, despite the info saying that inner areas appear over enclosing ones, it did not.
So, I've had to make the enclosing area a polygon with an inner cut to show through.
That's mapping for the renderer and not a convenient way to do, is it?
I have reproduced the problem with dummy [437322170](http://www.openstreetmap.org/way/437322170) tell me when to remove it.

**Comment by pnorman** [comment] 2016-08-17 03:52
When reporting a rendering problem please include [a screenshot of what you're seeing](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#reporting-issues) as without it we can't be sure what you're seeing.

**Comment by math1985** [comment] 2016-08-17 07:51
Can somebody reproduce this?

**Comment by pnorman** [comment] 2016-08-17 09:25
> Can somebody reproduce this?

If there is an issue it's probably out of scope here and coming from the version of osm2pgsql used, bad data, or something else in the rendering chain. `leisure=miniature_golf` is in the landcover layer and that is ordered by `layernotnull, way_area desc`

**Comment by mboeringa** [comment] 2016-08-17 09:29
> But, despite the info saying that inner areas appear over enclosing ones, it did not.
> So, I've had to make the enclosing area a polygon with an inner cut to show through.
> **That's mapping for the renderer** and not a convenient way to do, is it?

No, that's not "mapping for the renderer". It is just one way of representing the landcover of the surface of the globe, which is perfectly valid.

Mapping for the renderer would be if you had used e.g. a building polygon with building=yes tag to represent your miniature golf course by naming it "miniature golf course" because you liked the color of the buildings as representative of a golf course.

**Comment by dieterdreist** [comment] 2016-08-17 10:00
sent from a phone

> Il giorno 17 ago 2016, alle ore 11:30, mboeringa <notifications@github.com> ha scritto:
> 
> No, that's not "mapping for the renderer". It is just one way of representing the landcover of the surface of the globe, which is perfectly valid.
> 


if you consider the miniature golf to be inside the park then excluding it with a multipoligon from the park to make it show up in the rendering is indeed mapping for the renderer, and should be undone.

**Comment by kocio-pl** [comment] 2016-08-17 11:11
@dieterdreist I think it's not easy question - take for example lake in the forest: is it part of the forest or it just happens to be inside the forest?

**Comment by math1985** [comment] 2016-08-17 11:44
@a-pirard Are you able to reproduce the situation yourself, by creating a other miniature golf as test?

**Comment by dieterdreist** [comment] 2016-08-17 13:50
sent from a phone

> Il giorno 17 ago 2016, alle ore 13:11, kocio-pl <notifications@github.com> ha scritto:
> 
> @dieterdreist I think it's not easy question - take for example lake in the forest: is it part of the forest or it just happens to be inside the forest?


that's because there are different kinds of "forest". For landuse=forest or landcover=trees I wouldn't include a lake, for forest toponyms I would include it.

**Comment by a-pirard** [comment] 2016-08-17 15:24
On 2016-08-17 13:44, Matthijs Melissen wrote:
>
> @a-pirard <https://github.com/a-pirard> Are you able to reproduce the
> situation yourself, by creating a other miniature golf as test?
>
Oops.
I did make a demonstration case and I waited more than one hour to be
convinced it did not show before sending this.
But now, I see that it does !
Some bug was self-corrected since I mapped that mini golf (and saw that
others too were not rendered).
I'm progressively (day by day!) removing the inner areas and then
returning the multi polygon itself to plain way.
I'll let you know when probably closing this issue.
Sorry for disturbing you.

**Comment by a-pirard** [comment] 2016-08-19 13:12
On 2016-08-17 17:23, André Pirard wrote:
> On 2016-08-17 13:44, Matthijs Melissen wrote:
>>
>> @a-pirard <https://github.com/a-pirard> Are you able to reproduce the
>> situation yourself, by creating a other miniature golf as test?
>>
> Oops.
> I did make a demonstration case and I waited hours to be convinced it
> did not show before sending this.
> But now, I see that it does !
Indeed some bug was self-corrected since I mapped that mini golf.  It
had not appeared for weeks before I devised the polygon inner area
kludge to do so.
Now I removed that demo and inner area and it was displayed as intended
24 hours later.
Closing.
Sorry again for disturbing you.
Thanks.

**Closed** 2016-08-19 13:22 UTC

**Comment by polarbearing** [comment] 2016-08-19 13:34
My guess is that the OP just did not refresh his browser cache once the tile was rerendered.

**Comment by a-pirard** [comment] 2016-08-19 16:01
Yes I did many times.  I even purged the cache.
