### ISSUE TITLE
Change rendering order to display landcover on top of landuse

### ISSUE THREAD

**Issue by map-per** [gravitystorm/openstreetmap-carto#4418] opened 2021-06-04 07:20 UTC
### Expected behavior
I think that the map woud look better if de facto landcover woud be displayed on top of de facto landuse.

With de facto landuse I mean e.g.:
landuse=residential, commercial, industrial
leisure=park, water_park, sports_center, recreation_ground
amenity=hospital, school, kindergarten

With de facto landcover I mean e.g.:
landuse=forrest, grass
natural=* (wood, water, grassland, scrub,...)
(leisure=playground could be displayed like landcover as these areas are quite small)

### Actual behavior
On the map landuse and landcover are currently added in the same processing step sorted by size. This results in landuse sometimes overlapping landcover which looks weird. This occurs although the areas are correctly mapped and tagged.
This problem can be seen especially often with leisure=park and forrest areas. 
Moreover I think that in many areas mappers tried to avoid this problem by mapping for the render and splitting forrest areas up into small areas to make sure they are displayed on top of leisure=park.

### Links and screenshots illustrating the problem
![OSM - Kopie](https://user-images.githubusercontent.com/79519062/120761798-d98fd800-c515-11eb-8417-9db89ede97f8.png)
leisure=park and natural=wood: [https://www.openstreetmap.org/#map=18/48.09671/11.55969](https://www.openstreetmap.org/#map=18/48.09671/11.55969)

leisure=water_park and natural=wood: [https://www.openstreetmap.org/#map=19/48.11630/11.54451](https://www.openstreetmap.org/#map=19/48.11630/11.54451)

landuse=residential and natural=wood: [https://www.openstreetmap.org/#map=19/47.69104/11.56338](https://www.openstreetmap.org/#map=19/47.69104/11.56338)

Thanks for considering this proposal
map per

**Comment by imagico** [comment] 2021-06-04 09:09
Thanks for the suggestion.  From the examples the issue you have wit the current rendering seems to be a duplicate of #1796.   We have deliberately decided to render the wood/forest symbols this way to provide mapper feedback on (often unintended) overlaps in mapping and to visualize intentional overlaps.  Your suggestion - to abolish the size based drawing order in the landcover layer - would not change anything about that - the landcover symbols overlay is rendered above both the landcover layer and the water layers.

Note the use of the term _landcover_ in this style (landcover layer, landcover.mss) refers to landcover in the cartographic sense - i.e. features that graphically cover the land on the map (which is by default colored in `@land-color`) with a different fill color.  No statement with regards to geographic/remote sensing classification paradigms (land use/land cover classification systems) and how meaningful such are to represent local geographic knowledge in OSM is implied.

**Comment by map-per** [comment] 2021-06-04 11:50
Thanks for the quick answer. I don't want to abloish the size based drawing order. I woud suggest to split the rendering of the landcover layer up into two parts, the rendering of de facto landuse areas and the rendering of de facto landcover areas. Within both parts I woud stick to the size based drawing order.

In my opinion de facto landcover areas and de facto landuse areas can can overlap. There can e.g. be a residential area where a natural=wood covers parts of the garden of a house (e.g. https://www.openstreetmap.org/#map=19/47.69104/11.56338). So making these overlaps look weird on the map gives mappers a wrong feedback.

And this proposal doesn't conflict with the intention of highliting unintended overlaps as amongs de facto landcover areas these errors woud still be highlighted.

**Comment by imagico** [comment] 2021-06-04 12:55
> So making these overlaps look weird on the map gives mappers a wrong feedback.

As said in #1796 this is intentional - we want to give mappers explicit visual feedback if they map landuse=forest/natural=wood and landuse=residential with overlapping polygons.

That aside the suggestion to introduce a classification of the features of the landcover layer into two groups not founded in verifiable geography as recorded by mappers but defined subjectively by the style developers and rendering one on top of the other independent of size is not going to find consensus support here as it would be non-intuitive for mappers and map users.

**Closed by imagico** 2021-06-04 12:55 UTC

**Comment by map-per** [comment] 2021-06-04 18:42
> it would be non-intuitive for mappers and map users

I woud rather see it the other way round. That sometimes displaying the forrest and sometimes the residential area on top is rather unintuitive for map users.

However I do unterstand that it might be difficult to agree on what sould be displayed on top and what below.

**Comment by map-per** [comment] 2021-06-05 05:59
> not founded in verifiable geography

I would argue that if one loots at the earth from the bird's eye view trees within e.g. an insutrial area are on top of the industrial area

**Comment by map-per** [comment] 2021-06-06 16:53
This is a demo of how one coud fix this issue by rendering de facto landuse in the first step and everything else in the second step: https://github.com/map-per/openstreetmap-carto/tree/landcover

current carto on the left                                                                    and demo on the right


![Screenshot (661)_LI](https://user-images.githubusercontent.com/79519062/120932676-0bac6000-c6f7-11eb-9ff8-b8062191fb74.jpg)
https://www.openstreetmap.org/#map=17/48.09721/11.55894

![Screenshot (666)](https://user-images.githubusercontent.com/79519062/120932691-1b2ba900-c6f7-11eb-983e-516632c2f5f2.png)
https://www.openstreetmap.org/#map=18/47.69152/11.56462

![Screenshot (665)](https://user-images.githubusercontent.com/79519062/120932701-24b51100-c6f7-11eb-9146-611d8f573b11.png)
https://www.openstreetmap.org/#map=17/48.13427/11.59244

![Screenshot (662)](https://user-images.githubusercontent.com/79519062/120932707-2c74b580-c6f7-11eb-9acd-df6a02039237.png)
https://www.openstreetmap.org/#map=18/48.11644/11.54575

The change has little ot no side effect
![Screenshot (669)](https://user-images.githubusercontent.com/79519062/120932717-326a9680-c6f7-11eb-9b2b-c9bd70646f3d.png)
https://www.openstreetmap.org/#map=17/48.13342/11.56675

![Screenshot (668)](https://user-images.githubusercontent.com/79519062/120932722-37c7e100-c6f7-11eb-957e-83066287223e.png)
https://www.openstreetmap.org/#map=17/48.16173/11.54884

![Screenshot (664)](https://user-images.githubusercontent.com/79519062/120932732-44e4d000-c6f7-11eb-9926-6b38206ba9e1.png)
https://www.openstreetmap.org/#map=18/48.11020/11.56314

![Screenshot (663)](https://user-images.githubusercontent.com/79519062/120932738-4b734780-c6f7-11eb-9afc-cde4c5a1a644.png)
https://www.openstreetmap.org/#map=19/48.10391/11.55856

![Screenshot (667)](https://user-images.githubusercontent.com/79519062/120932743-529a5580-c6f7-11eb-8e8c-ff7b953230da.png)
https://www.openstreetmap.org/#map=18/48.17098/11.55984

**Comment by map-per** [comment] 2021-07-24 16:17
> As said in #1796 this is intentional

I don't think that declaring the current rendering a feature really solves this problem
