### ISSUE TITLE
Skipping parts of bigger objects on lower zoom levels

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#2896] opened 2017-10-15 17:32 UTC
Is it possible to skip rendering parts of bigger objects on some zoom levels?

I meant well mapped cases like:
- paths belonging to cemetery (like [here](http://www.openstreetmap.org/way/5080251#map=13/52.2721/21.0665) - it's rather red than green, especially when comparing with another cemetery on the south):
![screenshot-2018-1-8 openstreetmap](https://user-images.githubusercontent.com/5439713/34655722-abf86d66-f40e-11e7-98a6-71b1e4d6f086.png)
- grass belonging to a park or a hospital (like [here](http://www.openstreetmap.org/way/66266360#map=14/52.1966/21.0093) - there's almost no visible yellowish background, but on z14 it should be rather visible instead of grass and park)
- shops inside a marketplace (see https://github.com/gravitystorm/openstreetmap-carto/pull/2893#issuecomment-336694603)

I doubt in any special tagging, it would be good if the software would be able to make "hard" priorities for some areas, but maybe using relations would be the most reasonable way to recognize parts in general. Would it work within our current toolbox?

**Comment by kocio-pl** [comment] 2017-11-14 13:58
Two partial solutions to make some areas more visible:

1. We could hide all the small parkings (=when they don't show the letter). Testing shows that with gray color [they become unobtrusive](https://github.com/gravitystorm/openstreetmap-carto/issues/2904#issuecomment-341896809), but they still take some space on areas like hospital, so such area is less visible than it could be.

2. Wikimedia maps use interesting approach: if there are some buildings on the colored area, they are colored the same, but darker up to z17 (on z.max=z18 they look like all the other buildings). 

Examples:
* https://maps.wikimedia.org/#17/52.22667/20.96999
* https://maps.wikimedia.org/#17/52.19953/20.99703 - grass is still unchanged, but buildings blend nicely with the background and it makes it easier to see the hospital area

I haven't yet look how it's done and if it's possible for us to do the same. The other problem is that we use dark violet for other features, so buildings on industrial area would look to close to them. However for societal amenities, commercial and garages this would help.

**Comment by math1985** [comment] 2017-11-14 14:03
> if there are some buildings on the colored area, they are colored the same, but darker up to z17 

This is the same approach as Google's.

The problem is particularly important for landuse=retail: the retail color is generally not visible, because retail areas in Europe tend to be very high densitiy areas. Example: https://www.openstreetmap.org/#map=16/52.0774/4.3125

**Comment by kocio-pl** [comment] 2017-11-14 15:27
I think it's also important for schools and hospitals, because we use very pale color there. 

I guess it's this code:
https://github.com/kartotherian/brighmed/blob/1eb5ba52fad3d6c40c2f691c9f021b19bcc38eca/building.mss#L13

**Comment by jeisenbe** [comment] 2018-09-10 12:04
"The problem is particularly important for landuse=retail: the retail color is generally not visible, because retail areas in Europe tend to be very high densitiy areas."

I agree with this! It's also true in mid-sized towns and villages here in Asia, where retail areas often have 90% building coverage of the non-street surface area.

As a start, rendering retail buildings as a darker version of the retail landuse would be a nice test for this concept, especially since retail areas are the most important destinations for visitors and new residents. (The OsmAnd app already offers this as an option with their vector-based maps, and it works well)

**Comment by Tomasz-W** [comment] 2018-11-24 11:00
@kocio-pl I think https://github.com/gravitystorm/openstreetmap-carto/pull/3467 resolved this issue.

**Comment by kocio-pl** [comment] 2018-11-24 11:04
Unfortunately there's no easy way to tell "now hide the grass and show the hospital area", even on z13.

**Comment by jeisenbe** [comment] 2019-09-10 04:33
I don't believe there is a reasonable way to solve this issue with the current tools, so I'm closing this issue. 

However, if I'm incorrect I would be happy to reopen the issue. 

Is there a way to avoid rendering footways in a cemetery, shops in a marketplace, or grass in a hospital or university at a certain zoom level (but still render paths, shops and grass which are not inside of these areas), with performance good enough for this style?

**Closed by jeisenbe** 2019-09-10 04:33 UTC
Labels: question

**Comment by kocio-pl** [comment] 2019-09-10 10:23
What about SQL/PostGIS functions to check conditions like below (using pseudocode)? I imagine it might be quite fast:

```SQL
SELECT grass WHEN not INSIDE (hospital_area AND school_area) 
```
