### ISSUE TITLE
How will OSM.ORG default layer ever be reliable for addresses if max zoom level is only 19?

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4352] opened 2021-03-24 20:48 UTC
https://www.openstreetmap.org/node/8547736296 is an example of an address that will not appear on OSM.ORG due to the maximum zoom level (19) in the default (carto) layer.  This means OSM.ORG will not be reliable when it comes to people looking for addresses. Mainly just reliable for roads, etc.
Yes, it appears in some other layers, but not the default layer.

**Comment by HolgerJeromin** [comment] 2021-03-24 21:52
This style is independent from deploy on osm.org
The problem will be best solved with #3201

This is kind of duplicate of https://github.com/openstreetmap/openstreetmap-website/issues/1919  which was opened by... you :-) 

Ref https://github.com/openstreetmap/openstreetmap-website/issues/2094

**Closed** 2021-03-24 21:53 UTC
