### ISSUE TITLE
name rendered for disused:shop 

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#2999] opened 2017-12-29 14:45 UTC
Hi
Is there a reason polygons tagged as disused:shop=* and name=* still renders the shop's name.
www.openstreetmap.org/way/376275104

To me, this gives the impression it is still open.

**Comment by kocio-pl** [comment] 2017-12-29 15:00
This is rendered as a building name - if this was a shop label, it would have been violet. I will close this ticket, because it's a tagging issue.

**Closed by kocio-pl** 2017-12-29 15:00 UTC

**Comment by matkoniecz** [comment] 2017-12-29 16:42
If it is really a good idea to tag closed shops probably tagging it on node would be a better idea.

It is impossible to guess whatever name applies to building or closed shop.

**Comment by DaveF63** [comment] 2017-12-29 17:40
Changing the meaning of the name tag in osm-carto due to the presence of another tag is very poor.
Not rendering building:name or shop:name makes it an osm-carto issue.
I don't want closed shops to render
Mappng using polygons instead for nodes is more accurate, improving the quality of OSM. To map as nodes just to suit osm-carto is to be discouraged.

**Comment by kocio-pl** [comment] 2017-12-29 18:25
> Changing the meaning of the name tag in osm-carto due to the presence of another tag is very poor.

The meaning of `name=*` tag is just not really clean when we have more tags for some object and this is not the rendering fault.

You can't be sure if it's name of amenity, shop, building or anything else, if such tags are present. Why do you think this name belongs to disused:shop and not the building? This is not `disused:shop:name=*` nor `building:name=*`, so it can be attached to any object.

We use some rules to render names, but they are just reasonably good - the problem is that this scheme works only for single types and it need discussion about tagging.

**Comment by matkoniecz** [comment] 2017-12-29 18:35
In this case as a human I have no idea whatever name tag applies to building or closed shop.

**Comment by dieterdreist** [comment] 2017-12-29 22:47
sent from a phone

> On 29. Dec 2017, at 18:40, DaveF63 <notifications@github.com> wrote:
> 
> Changing the meaning of the name tag in osm-carto due to the presence of another tag is very poor.


no, this is poor mapping and the rendering just brings it to light.
A shop is not the same as the building, hence you should not use the same object to represent both. Either use a node for the shop, or an overlapping way, or a multipoligon. 

This is not limited to the name. All tags are unclear. If you added start_date for example you would not know either if that is referring to the shop or to the building.
