### ISSUE TITLE
Icon for hospital amenity should not refer to the Red Cross emblem

### ISSUE THREAD

**Issue by vmalep** [gravitystorm/openstreetmap-carto#3408] opened 2018-09-22 16:01 UTC
### Expected behavior
The hospital amenities are rendered with the cross within a circle that clearly refers to the Red Cross emblem. However, the use of this emblem is restricted by IHL. See also: https://www.icrc.org/en/guidelines-red-cross-emblem-fundraising

Another icon should be find.

### Actual behavior
Shows a cross withing a circle refering to the Red Cross emblem.
### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=19/3.40715/-76.46967&layers=H
![image](https://user-images.githubusercontent.com/2742150/45919130-b18be380-be56-11e8-8826-3c91016619e1.png)

**Comment by sommerluk** [comment] 2018-09-22 16:11
Thanks for the issue report.

The cross as a sign for health facilities is in quite common use. In France for example it is the standard symbol for pharmacies. I don’t think there is any legal possibility to restrict the usage of such a common and simple geometry like a cross.

That being said, this Github repository is the repository for the map style named “openstreetmap-carto”. The screenshot you posted is not a screenshot of this map style. So this is not the right place to report it. Therefore closing this issue.

**Closed by sommerluk** 2018-09-22 16:11 UTC

**Comment by kocio-pl** [comment] 2018-09-22 16:53
We are working on red icons for health and this problem is addressed by using red circle with a white cross inside there. Current color is not red in the first place, so I think we're on the safe side.

**Comment by imagico** [comment] 2018-09-22 17:32
@vmalep - if you truly think that use of the red cross symbol for indicating medical facilities in maps is lot legal you might also want to contact mapping authorities in various countries like in [France](http://professionnels.ign.fr/sites/default/files/DC_SCAN25_3.2.pdf) or in [Germany](http://www.landesvermessung.sachsen.de/inhalt/produkte/karten/top/tk50/tkL5142-ze_600.gif).  But i think you are misunderstanding the legal situation here and misinterpret the somewhat excessive claims of the ICRC.

OTOH use of the Swiss coat of arms (white cross on red background) for purposes other than referring to Switzerland is legally problematic by the way.

**Comment by vmalep** [comment] 2018-09-22 17:59
Thanks for responding! ;-)

1) And first of all I would like to apologize if I sound obstinate on this as I understand that for many people, this does not sounds like an real issue. However, for Red Cross workers dealing with people worried about the Red Cross neutrality, it may be. And since OSM is more and more used on humanitarian contexts (which is wonderful), it becomes more and more relevant to address it. But I insist that my point is not to argue with other OSM members. I just would like to share a concern and I truly appreciate that you are responding it.

2) @Imagico: Regarding mapping authorities in various countries, you may be right, but it is the responsibility of the respective national Red Cross societies, like the French one for France, to address it in their respective countries.

3) I am quite sure about the legal aspect of the protection of the emblem, but my point is not a legal one. It is a personal initiative to share with the OSM community (that I am part of) a concern I have as I trust that its members share the concern of the humanitarian workers and are interested in finding the best solution to those kind of issues.

All this being said, if you believe that this specific request and exchange is becoming cumbersome, please feel free to close the issue and I will leave it as it this. I only kindly ask the readers to keep this concern in mind and reflect on it.

Thanks for your understanding and best regards,
Pierre

**Comment by imagico** [comment] 2018-09-22 18:34
If your point is not a legal one i have to say i don't quite understand what your point is.

If you are worried that hospital tagging in OSM is used for facilities that do not fall under the protection of the Geneva convention and accordingly the map might show the symbol at unsuitable locations that would be something to clarify in the tag documentation (although it seems implicitly clear already).

**Comment by kocio-pl** [comment] 2018-09-22 19:36
I'm not even sure what's the best solution, since I also don't understand what is the problem then. 

By the way - I might be too cautious, because current icon is not a red cross (it's magenta cross in a circle) and proposed white cross in red circle is also not white cross in red square. There is also cultural and religious problem with using cross at all, so there are many catches one might not have think of.

But of course if there is something new that we could use, I'm happy to hear that. You never know what could work better.

**Comment by dieterdreist** [comment] 2018-09-22 21:35
sent from a phone

> On 22. Sep 2018, at 18:23, vmalep <notifications@github.com> wrote:
> 
> Thanks for responding. The use of the emblem is protected by international law (and there is indeed a possibility to do so) and the fact that there is a common misuse of it in a country does not means that it is not a problem.
> 
> You can check this webpage for more details: https://www.icrc.org/en/document/emblems
> 
> Sorry if I use the wrong screenshot... Is this the right one?:
> 
> 

it is the correct screenshot. I also would reject the request for trademark infringement, our cross is quite different to the int. red cross brand, it is not even red.

IMHO the international red cross cannot claim trademark on all kinds of crosses not even in all red ones.

If they start to enforce their presumed rights they will find out that it will not hold up. 
eg streetsigns with the symbol 
https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.gR_v2NE0o5z4qOFOigvG3wHaEK%26pid%3D15.1&f=1
http://static5.depositphotos.com/1008458/490/i/950/depositphotos_4906383-Hospital-sign.jpg


This said, there is an issue with the cross as a symbol for a global map, as it is not universally used in all cultures.

**Comment by vmalep** [comment] 2018-09-22 22:12
Thanks again. There are a few interesting comments and I would like to make a few additionall clarifications.

About legal aspects, I precisely meant that my point was not about "treadmark" or "protection under Geneva conventions", 2 different things that are not part of the discussion here.

You can argue on the exact color of the cross, but honestly, there is no discussion that if such a cross is used for hospital amenities, it is because it refers to the "Red Cross" known for being linked to rescue and health operations. And my point is precisely this: red cross should not be equal to whatever health or rescue operation. It should be restricted to specific uses by Red Cross members and rescue army's units, period. Of course in France this confusion does not have a lot of implications, but it does in armed conflict contexts. And OSM and it's default map rendering are more and more likely to be used, including in such contexts.

I quite agree with the comment that the use of the cross may lead to cultural issues. It is the exact reason why Muslims countries denied using the red cross and rather opted for the red crescent (even though the red cross has no religious connotation but is the Swiss flag inverted).

And therefore I would encourage using another emblem for hospitals or rescue facilities for the default OSM map style. Which one is a good question since the white "H" within blue I first thought about may be confused with landing spot for helicopters...

If someone has a better idea, I would love listening to it.

Best regards,
Pierre

PS for @kocio-pl: any civilian facilities not used for military purpose is protected by IHL and cannot be targeted. A protective Red Cross emblem will be displayed on specific facilities at specific times to bring a special attention to the parties to the conflict, including hospitals (with the approval of the Red Cross), but it may be a shelter for civilians, a water scheme especially needed, etc. Obviously the use of a red cross icon on OSM map does not bring any additional protection as such.

**Comment by Adamant36** [comment] 2018-09-22 23:00
@vmalep, the cross was used by catholic hospitals and healthcare facilities long before the Red Cross started using it. So its not the Red Crosses thing exclusively as you claim and the association of the symbol with healthcare has zero to do with them. They just co-opted it from the Catholics. Its been the almost universally known symbol of healthcare for a few thousands years though. Also, the H symbol is used on helipads. Its almost a universally known symbol for that. So it wouldn't work as an alternative. The only thing that might be an issue is the cross being red, but as @kocio-pl said, that's not really a thing. So I don't see what the problem is. Some things on the map have to be based on universally recognized symbols and icons can't be adopted to every circumstance, minor issue, or geographical variance. I think that goes for this case.

**Comment by jeisenbe** [comment] 2018-09-22 23:14
I had already been thinking about this issue in the context of Muslim
countries, where cross icons for Hospitals may be mistakenly thought
of as a Christian symbol. But I can't think of a good solution.

It looks like some people think of it as "the plus symbol" rather than
a cross, according to some Quora questions and this article title:
https://timesofindia.indiatimes.com/Why-do-doctors-have-plus-symbols-What-does-it-mean/articleshow/646.cms

The Hospital "emoji" 🏥 has a modified red-cross style symbol in Apple
iOS and Whatsapp: https://emojipedia.org/whatsapp/2.17/hospital/
https://emojipedia.org/apple/ios-11.3/hospital/

The ⚕️ Rod of Asclepius is a symbol for doctors, but is also specific
to European-background cultures and isn't specifically for hospitals.

We can't use a letter "H" for "Hospital", like Google Maps, because
this is language-specific.

I just can't think of a good alternative icon.

Pierre, do you have a suggestion for a different symbol?

Are you just concerned about protecting the Red Cross organization's
claim on the particular symbol, which we can solve by slightly
altering the shape or color (eg currently it is light red or pink), or
do you think we should avoid a plus-sign shaped symbol?

-Joseph

**Comment by Adamant36** [comment] 2018-09-23 02:27
@vmalep, either way the H is a none starter. As there is strick rules (or whatever) against using letters in icons. So even if you go with the assumption that the Red Cross has a monopoly on the cross symbol, which it clearly doesnt, there isnt an alternative to use anyway. Plus, the issue was closed. So giving us icon posibilities at this point is is totally useless. The consensous is clearly against changing it. Thanks for the suggestions though. Maybe it will be revisited at some future time when need be.

**Comment by vmalep** [comment] 2018-09-23 03:35
@Adamant36 and @kocio-pl , thanks for your replies and the suggestion to raise it on the OSM forum.

Once again I appreciate your time for this exchange and I hope that my suggestion was not perceived as capricious or arrogant.

I kindly invite you to document yourselves a bit more on the Red Cross emblem and the humanitarian world (especially for armed conflicts) and hopefully you will understand the importance of this question.

And thanks you for your work and contribution to the OSM project that is so wonderful and very useful to so many extends.

All the best!
Pierre

**Comment by kocio-pl** [comment] 2018-09-23 03:42
It's the proper question (you are welcome to ask it) and I see its importance, but it's already documented enough in other tickets. What we need is how to solve it, any more awareness will simply not help. It's design proposition phase now.

**Comment by polarbearing** [comment] 2018-09-23 09:53
What about the _bed_ from the hotel icon in health colour?

**Comment by kocio-pl** [comment] 2018-09-23 09:55
Didn't @Tomasz-W try that idea already?

**Comment by polarbearing** [comment] 2018-09-23 09:59
I vaguely remember it was discussed somewhere, so what was the outcome?

**Comment by Tomasz-W** [comment] 2018-09-23 10:00
I've proposed a circle with cross-shaped hole inside. There are even test renderings: https://github.com/gravitystorm/openstreetmap-carto/issues/2938#issuecomment-422304667

**Comment by kocio-pl** [comment] 2018-09-23 10:03
IIRC you have done bed in a circle too before and it was just not too clear.

**Comment by Tomasz-W** [comment] 2018-09-23 10:05
No, I didn't. 

I think that bed shape (even in red) without red cross wouldn's say that is a hospital, see a road signs: https://commons.wikimedia.org/wiki/Category:Hospital_road_signs .

**Comment by polarbearing** [comment] 2018-09-23 10:16
The traffic signs have to cope with their restrictions, e.g. black on blue, thus they need that explanation, to be distinguished from all the other blue.

Here we could have just the health selection (mostly doctor, clinic, pharmacy, and hospital) in the reddish colour, which makes that recognisable.
