### ISSUE TITLE
Via ferrata not rendered (highway=via_ferrata)

### ISSUE THREAD

**Issue by Tyg-g** [gravitystorm/openstreetmap-carto#4157] opened 2020-06-08 13:55 UTC
### Expected behavior
The _highway=via_ferrata_ tagged lines shall be **rendered** with style a clearly **distinguishable** from _highway=path_.

### Actual behavior
The _highway=via_ferrata_ tagged lines are **not rendered** at all.

### Links and screenshots illustrating the problem
Here at (49.08800, 18.83455) there is a via ferrata way along the stream, not rendered.
[https://www.openstreetmap.org/#map=17/49.08800/18.83455](https://www.openstreetmap.org/#map=17/49.08800/18.83455)
![Screenshot_20200608_154908](https://user-images.githubusercontent.com/40174710/84037987-9e5cd680-a99f-11ea-9ae5-aa323e52010f.png)

**Comment by imagico** [comment] 2020-06-08 14:24
Thanks for your suggestion.  This is a duplicate of #156, please post any new ideas or arguments about the matter there.  We can reopen that issue if needed.  See also #1500, in particular https://github.com/gravitystorm/openstreetmap-carto/issues/1500#issuecomment-486990206.

**Closed by imagico** 2020-06-08 14:24 UTC
