### ISSUE TITLE
embankment and cutting as man_made

### ISSUE THREAD

**Issue by AllroadsNL** [gravitystorm/openstreetmap-carto#2902] opened 2017-10-22 11:56 UTC
On a roadline, way, there is embankment=yes and cutting=yes.
[Embankment](https://wiki.openstreetmap.org/wiki/Key:embankment)
You can also draw it beside the road, draw two parallel ways then we use a way with man_made=embankment, we place it on the highest edge line, where the embankment characteristic is a raised bank, in the landscape, with on top a road or something else, topographically correct.

The opposite is a lowered bank, a cut in the landscape, we should use there man_made=cutting, like embankment have a two unit. So should cutting have the same.
The characteristic of cutting is a lowered bank.

The pitfall is now people use embankment because the other is not rendered, this is not right.
I like to use the man_made=cutting. Although it has not a wiki page, yet, and not often used so far.

It feels so normal to have a opposite tag.

This for [sunken lane, hollow way](https://en.wikipedia.org/wiki/Sunken_lane)
![image](https://user-images.githubusercontent.com/8817345/31861559-be8f49ca-b72f-11e7-9aaa-19e21468afa5.png)

With for OSM use, hillshade ground-level layers, I could draw the landcsape cutting line in. Where the cut is.
Also on other places.

**Comment by SomeoneElseOSM** [comment] 2017-10-22 12:39
For info (in case it provides inspiration) I'm also looking at embankments elsewhere,  For example, http://map.atownsend.org.uk/maps/map/map.html#zoom=18&lat=53.281645&lon=-0.782162 shows a footway on an embankment to the south of the stream, and an embankment without a path on it to the north.  I tried a bunch of different renderings, but "2 sided cliff" (for just an embankment) and "not quite a bridge" for a footway on one) looked best to me.

**Comment by kocio-pl** [comment] 2017-11-01 10:36
Tag [man_made=cutting](https://taginfo.openstreetmap.org/tags/man_made=cutting) has only 98 uses. Should we render it?

**Comment by AllroadsNL** [comment] 2017-11-01 10:54
For me I think so, because it is the opposite of embankment and also used on way line roads.

It should be very strange when cutting=yes is on the road and a embankment is drawn next to it.

**Comment by sommerluk** [comment] 2017-11-01 21:35
Ways with embankment=yes: 134 356
Ways with cutting=yes: 49 471

So: As an additional road attribute, cutting is less frequent than embankment, but still frequent. Currently, we render neither of them. Anyway, for embankment=yes on roads, we have yet the ticket #791 which will probably not be solved fast. Nevertheless, the numbers show that “cutting” is a feature that exists yet in OSM. So the usage of man_made=cutting _might_ grow in the future beyond the current 98 objects…

**Comment by mboeringa** [comment] 2017-11-01 22:26
Note that especially for **cutting=yes** tagged on a highway element, there is unfortunately lots of inappropriate usage. While the embankment and cutting tags were likely originally developed based on the symbols visible in topographic maps, especially those used to depict large embankment and cuttings of railways and motorways, people less experienced with reading or using true topographic maps misinterpret the tags and use it for all kinds of stuff I consider inappropriate, and making uncluttered rendering difficult:

- Many mountainous roads on mountain and hillsides are being tagged with **cutting=yes**, because rock and debris needs to be moved to create them. However, this is not an appropriate usage IMO, as a classical topographic cutting symbol usually assumes both sides of the railway or road cut into the landscape, not just one. What makes it even more disputable is, that most of these mountaneous roads also have embankments or **man_made=retaining_wall** structures on the opposite site of the road, thus symbolizing it with a two sided "cut" symbol looks really weird and wrong for these type of mountain roads.

- I have also seen people tag footpaths cut like an open-sided "tunnel" into a totally vertical cliff face (e.g. think a path through a highly touristic natural gorge), with cutting... ;-() OK, it needed to be "cut" from the cliff face, but this is far from classic "cutting" symbol usage on topographic maps.

- As to embankments, in some parts of the world, many tiny footpaths hardly above the surrounding landscape, e.g. between rice paddies, are being tagged with **embankment=yes**. Again, while maybe technically correct, this is not the type of feature usually symbolized with embankment symbology in topographic maps.

**Comment by matkoniecz** [comment] 2017-11-02 14:08
Is it possible to have properly looking map and render both man_made=embankment and embankment=yes? In case that it is not possible I think that more detailed tagging (man_made=embankment) should be encouraged.

**Comment by kocio-pl** [comment] 2017-11-02 14:09
I think we should close this issue now. It can be reopened once there's some discussion on Tagging list and wiki page at least, but also few thousands of usage is highly recommended.

**Comment by matkoniecz** [comment] 2017-11-02 14:12
Also, it is almost duplicate of #791 

In general I recommend promotion of tags by using them, documenting on wiki, adding them to editing presets - not by requesting to render tag used less than 1000 tones.

**Closed by matkoniecz** 2017-11-02 14:12 UTC
Labels: cartography
