### ISSUE TITLE
Fix Milano, Napoli, Torino (hidden at zoom 6)

### ISSUE THREAD

**Issue by valerio-bozzolan** [gravitystorm/openstreetmap-carto#4729] opened 2022-11-14 10:14 UTC
### Expected behavior

* [ ] **Milano** (https://www.openstreetmap.org/relation/44915)
    * Make visible at zoom 6. Proposed solution: hide "Novara" and/or "Piacenza" to have more space for "Milano"
* [ ] **Napoli** (https://www.openstreetmap.org/relation/40767)
    * Make visible at zoom 6. Proposed solution: hide "Giugliano in Campagna" to have more space for "Napoli"
* [ ] **Torino** (https://www.openstreetmap.org/relation/43992)
    * Make visible at zoom 6. Proposed solution: just display "Torino" under "Piemonte"

### Actual behavior

You see that Milano, Napoli and Torino are not visible at zoom 6 on Carto:

![Missing Milano Napoli Torino Zoom 6 OpenStreetMap Carto](https://user-images.githubusercontent.com/6052909/201631091-19a64007-fc52-4264-ad3f-81c831f24e66.png)

### More documents

Thank you for any feedback but please keep this bug small so a fix is easier.

List of bigger parent tasks:

* https://github.com/gravitystorm/openstreetmap-carto/issues/3034
* https://github.com/gravitystorm/openstreetmap-carto/issues/1391#issuecomment-411772569

Other documents/discussions:

* https://blog.jochentopf.com/2022-11-07-selection-of-generalization-problems.html
* https://help.openstreetmap.org/questions/47147/how-can-we-make-philadelphia-show-on-openstreetmaporg-at-zoom-levels-6-and-7

### Troubleshooting

To help, you can try to do this and share a comment for your progresses:

1. [ ] install Carto locally to debug this problem
2. [ ] in Carto, try to disable labels "Lombardia", "Piemonte" to see if these are the current problems

**Comment by imagico** [comment] 2022-11-15 20:42
Thanks for the report.

The linked to features are `admin_level=8` boundary relations.  We don't render those with a label at any zoom level and render their outline at z12+.  We will definitely not render them at z6.

As far as rendering `place=city` labels is concerned - i.e.:

https://www.openstreetmap.org/node/62505581
https://www.openstreetmap.org/node/428339558
https://www.openstreetmap.org/node/63621589

that would be a duplicate of #1391, #3034, #3880.

These are not parent tasks, these are the issues we need to solve here.  The specific case examples you showed here are just examples demonstrating the problem, fixing them without fixing the underlying problem is not an approach we would consider taking.

I am therefore closing this as declined (for admin_level 8 boundaries) and duplicate (for place=city).

**Closed by imagico** 2022-11-15 20:42 UTC
