### ISSUE TITLE
Major buildings are rendered twice

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1997] opened 2015-12-06 17:37 UTC
Currently major buildings have their own layer, which renders them twice. First as "normal" building and then as major one on top of the normal one. I think this is unnecessary and buildings should be handled by only one layer.

Here would be my proposal how to rewrite the buildings query to do that (which also removes the building catch-all rendering):

```
(SELECT
    way,
    building,
    'type_' || CASE WHEN building IN ('castle', 'cathedral', 'chapel', 'church', 'manor', 'monastery', 'mosque', 'temple')
        AND (amenity = 'place_of_worship' OR historic = 'castle')
      THEN 'major'
      ELSE
        CASE WHEN building = 'yes'
        THEN
          CASE WHEN amenity = 'place_of_worship' OR historic = 'castle'
          THEN 'major'
          ELSE 'normal'
          END
        ELSE
          'normal'
        END
      END AS category
  FROM planet_osm_polygon
  WHERE building IN ('apartments', 'barn', 'bridge', 'bungalow', 'bunker', 'cabin', 'castle', 'cathedral', 'chapel',
      'church', 'civic', 'college', 'commercial', 'construction', 'cowshed', 'detached', 'dormitory',
      'farm', 'farm_auxilliary', 'garage', 'garages', 'greenhouse', 'hangar', 'hospital', 'hotel', 'house',
      'houseboat', 'hut', 'industrial', 'kindergarten', 'kiosk', 'manor', 'manufacture', 'monastery', 'mosque', 'office',
      'public', 'residential', 'retail', 'roof', 'ruins', 'school', 'service', 'shed', 'slurry_tank', 'stable',
      'static_caravan', 'supermarket', 'terrace', 'temple', 'train_station', 'transformer_tower', 'transportation',
      'university', 'warehouse', 'yes')
    AND way_area > 0.01*!pixel_width!::real*!pixel_height!::real
  ORDER BY z_order, way_area DESC
) AS buildings
```

This introduces a category column, which is either 'type_normal' or 'type_major' and can be used in the style file. (The query contains also a logic, which includes buildings tagged as castle in the major category.)

Related to #1897.

**Comment by kocio-pl** [comment] 2015-12-07 11:35
I still think that the "approved list" approach, which generally works with shops (with some problems, because it's meant to be one-time hack, which would be enough for a static data set, but hard to maintain in the long run in the OSM case), is too simplistic for buildings, because we have a lot more of them in the database.

My questions:
1. How did you create this list? What should be the rule?
2. What about unexpected invisibility which breaks the sane feedback loop (exactly as in my example, [building=stadium will vanish](https://github.com/gravitystorm/openstreetmap-carto/issues/1897#issuecomment-145812428) with this code)? 
3. How should we monitor and add (new ones) or remove (inconsistent spelling or deprecated ones) building types? What about tools to help maintain it or people who will look after it in a months and years to come?

If we don't think about these problems, we will have a short moment of comfort and a problem of massive distorted tagging in the future. It will backfire much sooner than with shops.

**Comment by pnorman** [comment] 2015-12-07 17:11
I'm against using a white-list approach for building tag values.

**Comment by mboeringa** [comment] 2015-12-07 17:29
I think - based also on the issue title - that the original proposal of @nebulon42 was not so much about whether there should be a "white-list" for buildings, but about the fact that some features are actually being rendered multiple times, which is a different issue, albeit somewhat obscured by the fact there is a list of building types in the proposed query.

Let's first decide if we consider the multiple rendering an issue. If not, this issue could be closed, and a new one opened for a catch-all / white-list issue (and there is probably already one in the tracker history).

**Comment by kocio-pl** [comment] 2015-12-07 17:40
It's interesting for me (1) how it can be done without white list and (2) how bad is this issue performance wise. If it's possible to exclude just special buildings from the rest, I have nothing against it, even if the performance gain would be small, but if not, the performance gain should be substantial for me to even consider white listing.

**Comment by matkoniecz** [comment] 2015-12-07 17:51
> I think - based also on the issue title - that the original proposal of @nebulon42 was not so much about whether there should be a "white-list" for buildings, but about the fact that some features are actually being rendered multiple times, which is a different issue, albeit somewhat obscured by the fact there is a list of building types in the proposed query.

I used approach of rendering buildings twice because it resulted in simpler code. IMHO code is currently simpler than proposed, but given that any code seems simpler to person who wrote it this opinion is not highly useful.

**Comment by matkoniecz** [comment] 2015-12-07 17:55
> I'm against using a white-list approach for building tag values.

I'm also against - values for this key are freeform and constantly expanding. This approach would also result in de facto support of building=abandoned, building=proposed and other similar bad tagging schemes.

**Comment by nebulon42** [comment] 2015-12-07 21:10
Maybe it was not a good idea to post that example (!) query. I'd like to keep this issue on topic so I'm not going to expand on all the input about whether the building catch-all should be dropped or not. I just want to note that I think (and I have said this before) that the reluctance of dropping the building catch-all is contradicting with what is outlined here regarding cartography and data quality.

> I used approach of rendering buildings twice because it resulted in simpler code. IMHO code is currently simpler than proposed

I agree regarding the SQL, but having two layers instead of one could also be viewed as being more complex. Additionally, this approach only works well with the current styling. If one would like to change something for major buildings (e.g. dashed outlines) this would be a problem. Purely hypothetical, I know.

**Comment by pnorman** [comment] 2015-12-07 21:15
To the issue raised, I'd like to avoid having buildings twice.

In a vector tile source, you'd do that by having one building layer and unioning the low-zoom and high-zoom queries, each with a zoom conditional to avoid duplicates.

In our case, we can't reasonably do that, so we should either

- Drop use of major buildings at higher zooms
- Exclude major buildings from the buildings layer

I prefer the former.

**Comment by dieterdreist** [comment] 2015-12-09 11:45
2015-12-07 18:55 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> I'm also against - values for this key are freeform and constantly
> expanding. This approach would also result in de facto support of
> building=abandoned, building=proposed and other similar bad tagging schemes.
>


the current proposal above would even render building=no. On the other
hand, while abandoned isn't a building type, this combination still
describes a building. If building=proposed was rendered like a building,
people would more likely improve the tagging.

The proposed rendering rules also require that amenity=place_of_worship is
tagged on the same object as is the building, and it supposes that every
place of worship is worth a more particular building rendering, while it
doesn't give this rendering to churches that are not used as such any more
(I do not believe this is why churches are highlighted currently and why
they should be).

**Comment by nebulon42** [comment] 2015-12-09 18:17
I'm not sure why this renders building=no, proposed, abandoned statements pop up. Am I not able to write correct SQL or are misunderstanding it? Where in the above WHERE building IN (...) do you see support for building=no and the other mentioned values? If you are talking about rules what to include in the list: What hinders us to exclude bad tagging schemes in the same way as typos?

Additionally, I'd like to point out that the above major buildings categorization does not change anything regarding the status quo, see https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.yaml#L473-L484.
If you think this categorization could be improved you should open a new issue.

**Comment by pnorman** [comment] 2015-12-10 20:35
> Where in the above WHERE building IN (...) do you see support for building=no and the other mentioned values?

By *not* including something like `building=demolished`, you're supporting it as a non-building. It's a bit reversed from normal, since building=demolished is reversed from normal.

I'd go for doing a change to the SQL to stop duplicated buildings without changing any styling, and we can consider other changes after.

**Comment by mboeringa** [comment] 2015-12-10 21:57
Be aware that duplicated features are almost certainly lurking in other render rules as well. It is almost unavoidable once you start rendering things in thematic groups / layers like landuse, natural, wetland etc... I have actually added a whole bunch of "exclusion clauses" in my personal ArcGIS Renderer, to take care of the most common duplications caused by tagging and the specific thematic rendering I wanted to achieve. It is far from perfect, but at least avoids most of the especially disturbing label duplication that otherwise may occur.

**Comment by kocio-pl** [comment] 2017-01-03 02:43
It looks for me as a wontfix issue, because it really has some merits, but it would introduce other problems, which are bigger for me than this one.

**Comment by pnorman** [comment] 2017-01-03 05:40
The discussion diverged into white-lists, which is unrelated to the duplication in buildings and buildings-major. That could be fixed by adding `AND NOT (aeroway = 'terminal' OR amenity = 'place_of_worship' OR building = 'train_station')` to the buildings SQL.

**Comment by kocio-pl** [comment] 2017-01-03 05:44
Do you think it's worth doing? For example what would be performance implications?

**Comment by nebulon42** [comment] 2017-01-03 19:00
Unifiying both building layers is something that I think is worth doing. I don't see any problems with that. What am I missing?

**Comment by pnorman** [comment] 2017-01-03 21:24
> Do you think it's worth doing?

Yes.

> For example what would be performance implications?

Perhaps slightly faster, but probably no different.

-----

> Unifying both building layers is something that I think is worth doing. I don't see any problems with that. What am I missing?

Unifying them would be a different issue, and could theoretically have performance implications for the low-zoom buildings.

**Comment by kocio-pl** [comment] 2017-01-03 21:29
OK, I'll try to make the PR fix soon.

BTW: the name of this ticket is misleading - AFAIK it's not about rendering, but reading from database.

**Comment by pnorman** [comment] 2017-01-03 21:33
> BTW: the name of this ticket is misleading - AFAIK it's not about rendering, but reading from database.

No, they're rendered twice. Once on the buildings layer, once on the buildings-major layer. If you tweak the styling (e.g. transparency on both layers, or a wide border on the lower layer) you should be able to see this.

**Comment by kocio-pl** [comment] 2017-01-04 04:32
I'm not a programmer (let alone SQL expert), but I thought that would be easy, yet:

```SQL
        (SELECT
            way,
            building,
            amenity,
            aeroway
          FROM planet_osm_polygon
          WHERE building IS NOT NULL
            AND building != 'no'
            AND NOT (aeroway = 'terminal' OR amenity = 'place_of_worship' OR building = 'train_station')
            AND way_area > 0.01*!pixel_width!::real*!pixel_height!::real
          ORDER BY z_order, way_area DESC
        ) AS buildings
```

doesn't work as expected - it hides all the buildings.

When trying to debug I've found that adding just one element:
```SQL
AND NOT amenity = 'place_of_worship'
```

shows the buildings different than pow, but _only with amenity tag_, so it probably assumes:

```SQL
AND amenity IS NOT NULL
```

How should I tell it to don't assume this value and select all the buildings without pow, but _also_ without amenity tag?

**Comment by pnorman** [comment] 2017-01-04 08:53
Oh right. If amenity is null, then `NOT amenity = 'place_of_worship'` evaluates to NULL. We have `AND (amenity IS NULL OR amenity <> 'place_of_worship' )` in places, but I think 

```sql
WHERE building IS NOT NULL
  AND building != 'no'
  AND amenity IS DISTINCT FROM 'place_of_worship'
  AND aeroway IS DISTINCT FROM 'terminal'
  AND building != 'train_station'
  AND way_area > 0.01*!pixel_width!::real*!pixel_height!::real
```
would work.

https://www.postgresql.org/docs/current/static/functions-comparison.html

**Comment by mboeringa** [comment] 2017-01-04 08:55
> How should I tell it to don't assume this value and select all the buildings without pow, but also without amenity tag?

**(building IS NOT NULL AND building NOT IN ('no','train_station')) AND (aeroway IS NULL OR aeroway NOT IN ('terminal')) AND (amenity IS NULL OR amenity NOT IN ('place_of_worship'))**

Can you try this for the WHERE clause? Remember/hint: any key can also be NULL. You need to take care of this in your exclusion queries.

Other hint: if you use 'IS NOT NULL' in these exclusion queries, it must be followed by an **'AND'** before the 'NOT IN' or '!=' statement, so:

(building _IS NOT NULL_ **AND** building _NOT IN_ ('no','train_station'))

If you use 'IS NULL' in the exclusion query, it must be followed by an **'OR'** before the 'NOT IN' or '!=', so: 

(aeroway _IS NULL_ **OR** aeroway _NOT IN_ ('terminal'))

This latter thing with the OR may not feel intuitive, but a single record can not be NULL and something else at the same time.

**Comment by mboeringa** [comment] 2017-01-04 09:04
Hmm... I think @pnorman's solution and mine are equivalent (no surprise of course ;-)). 

Mine is pure ANSI SQL though, and potentially portable to other databases. @pnorman's solution is more readable though, but requires the IS DISTINCT FROM of PostgreSQL, and thus might not port to other databases.

**Comment by pnorman** [comment] 2017-01-04 09:09
> @pnorman's solution is more readable though, but requires the IS DISTINCT FROM of PostgreSQL, and thus might not port to other databases (probably not an issue here though).

`IS DISTINCT FROM` is ANSI SQL from SQL:1999, and `IS NOT DISTINCT FROM` is ANSI SQL from SQL:2003. PostgreSQL got support in 9.1

Given that our minimum requirement is PostgreSQL 9.1, I'm not worried about databases that don't meet that criteria.

**Comment by mboeringa** [comment] 2017-01-04 09:11
> IS DISTINCT FROM is ANSI SQL from SQL:1999, and IS NOT DISTINCT FROM is ANSI SQL from SQL:2003. PostgreSQL got support in 9.1

Ah, OK, didn't know that, thanks.

> Given that our minimum requirement is PostgreSQL 9.1, I'm not worried about databases that don't meet that criteria.

Yes, thought so.

**Comment by kocio-pl** [comment] 2017-01-04 13:11
Thanks!

I'm using current Ubuntu (16.10) with PostgreSQL 9.5 and with ```IS DISTINCT FROM``` notation I get this error:

```Postgis Plugin: ERROR:  syntax error at or near "'place_of_worship'"
LINE 1: SELECT ST_SRID("way") AS srid FROM 'place_of_worship' WHERE ...
                                           ^
in executeQuery Full sql was: 'SELECT ST_SRID("way") AS srid FROM 'place_of_worship' WHERE "way" IS NOT NULL LIMIT 1;'
  encountered during parsing of layer 'buildings' in Layer
```

@mboeringa notation works for me, so I'll just try to make it more readable and blend it nicely with the rest.

**Comment by kocio-pl** [comment] 2017-01-04 13:27
This is what is working and looks clear to me:
```SQL
          WHERE building IS NOT NULL 
            AND building != 'no'
            AND (aeroway IS NULL OR aeroway != 'terminal')
            AND (amenity IS NULL OR amenity != 'place_of_worship')
            AND building != 'train_station'
            AND way_area > 0.01*!pixel_width!::real*!pixel_height!::real
```

I'm not sure if joining building statements is necessary? This way it's easy to modify and all the elements are corresponding 1:1 to elements in buildings-major section, which I find good.

**Comment by pnorman** [comment] 2017-01-05 00:21
> I'm using current Ubuntu (16.10) with PostgreSQL 9.5 and with IS DISTINCT FROM notation I get this error:

This might be a mapnik error... It could be seeing `FROM 'place_of_worship'` in the query and assuming that there is a table named `'place_of_worship'`

**Closed** 2017-01-07 08:04 UTC
Labels: buildings, code
