### ISSUE TITLE
Enable Noto Nastaliq Urdu as the default font for locations in Pakistan

### ISSUE THREAD

**Issue by bgo-eiu** [gravitystorm/openstreetmap-carto#4547] opened 2022-05-14 02:44 UTC
### Expected behavior

For locations in Pakistan which have the default 'name' in an Arabic-based script (could be Urdu, Pashto, Punjabi, etc.) to show in Nastaliq script. In most countries which use an Arabic-based script, people are familiar with other type settings and this is less of an issue, even in Afghanistan and Iran. However, Pakistanis almost exclusively read and write using the Nastaliq style and generally find it to be much more readable. Any site or media source which specifically has a Pakistani audience in mind will show the script this way.
 
### Actual behavior

Currently, the fonts.mss file includes this comment:

> 2. Noto provides various variants of Arabic: Noto Kufi Arabic, Noto Naskh
> Arabic, Noto Nastaliq Urdu and Noto Sans Arabic. Kufi and Urdu styles are not
> widespread in use. Noto Sans Arabic (a Naskh-style low-contrast “Sans” font) and
> Noto Naskh Arabic are the fonts with the greatest coverage and provide an UI
> variant. This style uses Noto Sans Arabic UI because it’s consistent with the
> other Sans fonts and legible. The Arabic fonts are placed behind Sans fonts
> because they might re-define some commonly used signs like parenthesis or
> quotation marks, and the arabic design should not overwrite the standard design.
> The list still includes Noto Naskh Arabic UI for compatibility on systems
> without Noto Sans Arabic UI.

These statements may have been true at some point in the past, but the status of these fonts and expectations have definitely shifted to a widespread support of Noto Nastaliq Urdu as the most accessible and legible font for Pakistani readers. While it is true that Noto Naskh and Noto Sans Arabic are considered the most legible in a larger number of countries, these are definitely not considered the most legible options in Pakistan. See the links/screenshots section below for specific documentation regarding the use of Noto Nastaliq in Pakistan. The shift to Noto Nastaliq as an expected default generally became clear in 2017, when a number of larger tech companies switched to using it in response to feedback from Pakistani users.

### Links and screenshots illustrating the problem

* Pakistani users of Windows have complained that Windows 10 does not provide a legible/easy to read default option for Urdu readers. This issue comment shows a comparison between the Microsoft Urdu Typesetting and Noto Nastaliq, pointing out that Noto Nastaliq is much closer to what people in Pakistan find to be legible: https://github.com/MicrosoftDocs/typography-issues/issues/382#issuecomment-631019744

** Note that Microsoft Urdu Typesetting was added to Windows in the first place for Pakistani users, it just happens that in this case their version of the font was not good enough.

* Google/Android devices, Mac OS X, and iOS have all shifted to Noto Nastaliq as the default font for Pakistani users. Pakistani news article commending Apple for including it by default: https://tribune.com.pk/story/1514433/apple-finally-enables-nastaleeq-typeface-urdu-keyboard-ios-11

* The Urdu Wikipedia uses Nastaliq by default: https://ur.wikipedia.org/wiki/%D8%B5%D9%81%D8%AD%DB%82_%D8%A7%D9%88%D9%84 This is a good example of what people can expect Urdu labels in Pakistan to look like. You would not see this on the Farsi or Arabic Wikipedia projects, but it is considered essential for Urdu. The stylesheet uses a list of possible Nastaliq fonts, placing Jameel Noori Nastaliq over Noto Nastaliq, but this is more a reflection of older/legacy standards before the proliferation of the Noto fonts. Jameel Noori Nastaliq was the preferred font for a long time, but it is proprietary and does not support the characters as well as Noto does. The Uninastaliq template on Wikipedia is a re-write of the older Nastaliq ranking to accomodate the current situation: https://en.wikipedia.org/wiki/Template:Uninastaliq

** This new wiki template places Noto Nastaliq and the Microsoft Urdu Typesetting at the top above Jameel Noori and asks that the first two fonts be at the top of the priority list no matter what. The reason for this being that the vast majority of Pakistani users on an operating system from 2017 or more recently has at least one of these two fonts on their system. Noto is more legible, Urdu Typesetting is a compromise.

![image](https://user-images.githubusercontent.com/100172442/168407421-9a5068de-aa05-49ac-bdc5-a93ed95ba583.png)
This is a screenshot of what Karachi looks like at the moment for reference

![image](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Sindh_Dist_Karachi.svg/733px-Sindh_Dist_Karachi.svg.png?20120828111659)
This is an Urdu map of Karachi and its surrounding subdivisions in Sindh province by Pakistani Wikimedia Commons uploader Tahir mq.

**Comment by imagico** [comment] 2022-05-14 08:36
This is technically a part of #2208 (the title is somewhat misleading there - this is generally about scripts where the same unicode characters are used for different variants of the same script or different closely related scripts, CJK as well as Cyrillic and Arabic).

Thanks for pointing out that this is an issue with languages using Arabic script as well.

There are different problems that make this an issue that is hard to solve, primarily the fact that there is no agreement in OSM to record the language of the name tag (or to agree to abolish use of the name tag in favor of separately recording language specific names and the local naming conventions - see http://blog.imagico.de/you-name-it-on-representing-geographic-diversity-in-names/).

What is a different issue is that the font used on https://ur.wikipedia.org/wiki/%D8%B5%D9%81%D8%AD%DB%82_%D8%A7%D9%88%D9%84 seems unsuitable for being used at small font sizes - like those we use for POI or road labels, see for example https://www.openstreetmap.org/#map=18/24.85637/66.99087.  Is something like this:

https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/%D9%81%D9%88%D9%86_%DA%A9%D8%B1%DB%8C%DA%BA.svg/200px-%D9%81%D9%88%D9%86_%DA%A9%D8%B1%DB%8C%DA%BA.svg.png

actually readable to an Urdu speaker?  The font used on

https://ur.wikipedia.org/static/images/project-logos/urwiki.png

seems better - but i don't know which it is.

**Comment by bgo-eiu** [comment] 2022-05-14 19:31
I did see the Han unification / CJK thread, though this particular situation is definitely simpler and potentially more actionable. There would be no requirement to know anything about the language of the tagged name, as the Romanized script text and Arabic script text do not have any overlapping characters like different CJK characters can have, and people expect to see any Arabic-based script written the same way as they expect to see Urdu no matter what the original etymology is. If a place name is identical in Urdu and Sindhi, it does not really matter if the reader speaks Sindhi, the place name would look just the same either way. A closer analogy for how place names are seen in Pakistan would be Canada, where English speakers and French speakers expect to see Romanized script presented the same way regardless of language, and whether or not your native tongue is English or French does not really matter when it comes to reading the place names in the other language.

The way to implement this would be the same regardless of how name tagging is approached, it would be just to prioritize the Nastaliq font over Naskh within Pakistan - just that country, no need anywhere else. I checked regarding Afghanistan and Iran, and users on their respective Wiki sites for example actually rejected the idea of making it default there. They may use Nastaliq in some specific situations, but Pakistan is really the only country where this typesetting is used as the default for everything; on signs, in the media, at school, etc. Nothing with a Romanized script name would be affected because it doesn't overlap, and essentially everything else would be legible in Nastaliq.

That first example of the small wikimedia upload with the phone icon does look crowded, but I think that is just an artefact of the source file, which is an SVG that has the actual paths and nodes of the lettering explicitly defined rather than referring to a font, so it does not scale down like a font is supposed to. It is also not clear what font was used as the basis for the SVG. Noto Nastaliq is a bit magic in the way it does font scaling, which is probably why it has quickly become the preferred font for this purpose. If you look at a one-to-one example of Noto Nastaliq vs. Noto Naskh at the same font size, I think it looks at least as legible. It is arbitrary at the end of the day but note that the "tails" which make the Nastaliq script taller help to keep the letters looking distinct from each other at smaller sizes.

Noto Naskh 10px
![image](https://user-images.githubusercontent.com/100172442/168445691-63025c11-1afb-49f9-84a0-699e087ad6ce.png)

Noto Nastaliq 10px
![image](https://user-images.githubusercontent.com/100172442/168445701-c97f92ff-1816-41f6-8309-4c89c659e31f.png)

Noto Naskh 8px
![image](https://user-images.githubusercontent.com/100172442/168445722-c51fea18-0b46-44e1-9248-b4b76966d90e.png)

Noto Nastaliq 8px
![image](https://user-images.githubusercontent.com/100172442/168445744-2e7cd31e-a5fa-4ff6-a7c8-6aef6eba2b22.png)

I think the 8px is even smaller than the size I am seeing on the roads of the OSM.org link you provided, so I think Nastaliq could work at that scale.

I am not familiar with the technical details of how font styling works in Carto - if the Noto fonts are in the project itself, even better.

**Comment by imagico** [comment] 2022-05-14 20:17
> it would be just to prioritize the Nastaliq font over Naskh within Pakistan

Which is exactly the same approach as the most frequently suggested solution to the Han unification problem.  This however makes the assumption that languages are strictly separated by administrative unit - which is not the case, neither in China/Korea/Japan nor in Pakistan and Middle East countries.

Note we will most likely not want to federate the style based on design preferences in different countries.  If we come up with a solution to #2208 we will still want to render names in a certain language in a unified form globally and not differently based on location.  So all Urdu names would be rendered in one font globally and not differently depending in what country the feature with that name is located.  If the Pakistan OSM community would like to use a certain font for any Arabic script names independent of language the way to go would be to set up a distinct map for that (which could obviously be a derivative of OSM-Carto).

Regarding your samples - note that nominal text size is often not that meaningful.  Your Noto Naskh 10px example has a total height of 18px, the Noto Nastaliq 10px example has a total height of 25px.

**Comment by bgo-eiu** [comment] 2022-05-15 14:16
Well, it doesn't really make that assumption about languages themselves, just about typesetting. Keep in mind most Pakistanis don't speak Urdu natively - it's a lingua franca. They learn Urdu writing a certain way through the education system, media etc. and then that has resulted in people writing their mother tongues the same way. Urdu is also mutually intelligible with Hindi, so you are already seeing many of the same words and names printed in a different font on either side of Pakistan and India. If you were to actually enforce rendering the same language the same way in every country, you would have to alter the labels in large parts of India as they appear currently, which would not be popular. For example, the majority of Punjabi speakers live in Pakistan, but you will never see Punjabi in the same form in India even though it is the same language. Part of how this has happened without Carto accounting for it is that the ISO language codes tend to duplicate the same language for different countries in South Asia, because those codes were made people who were ignorant of languages in the region.

The point here though is that as far as the style of writing is concerned, that does begin and end at the country borders - carto wouldn't be seen as an arbiter of that, because it has to do with how people learn to write, and school systems are government run and end and begin at those borders. India is actually the only other country where you will see Urdu names and while it's unlikely you will see them written in the Arabic script, if you do, the Nastaliq script would be more appropriate there too. The main language that would look different around the border that doesn't already is actually Pashto - that is shared with Afghanistan. If you would rather it be tied to language than border, you could have Nastaliq on Urdu, Punjabi, Sindhi, and Baloch, and leave Pashto the same.

I would also say this isn't quite the same as design preferences, as this has a significant impact on legibility, and within the current policy to show things in the language of the area it makes sense. Even though these are languages with Arabic based scripts, none of them are particularly close to Arabic, and there are different sounds referred to and even letters or modifications that are never used in Arabic. (Unicode/font developers have tended to group these with Arabic, kind of like how dotless ı is part of Romanized scripts but only used for Turkic languages.)

Imagine if, for example, the font used for Romanized scripts did not include support for the range of diacritics used in French, so names in France did not include them as if they were written in an English a speaking country. This would be seen as inaccurate even by English-speakers, who expect to see French written that way, even when French-origin names in English speaking countries are written without them. The same goes for all of the languages spoken in Pakistan. Any person familiar with any of the languages spoken in Pakistan would expect to see them written in the Nastaliq form there, in the same way anybody in America or England would expect Romanized script to be to include features they don't use in France or Turkey.

It may also help to know that the convention in Arabic scripts is to admit "short" vowels, so someone from an actual Arabic speaking country isn't necessarily going to have an easy time reading Urdu correctly even if it's in a familiar typeface. It requires some working familiarity with the words/names themselves to know the pronunciations as these are essentially cursive strings of consonants. So this wouldn't be seen as making the map less legible to people using Arabic scripts in different languages, because they're not necessarily that interchangeable to begin with. The only language where you would see the script change around the border as I mentioned, is Pashto. Even with that though, the official lingua franca in Afghanistan is Persian (called Dari there), not Urdu, so people there are familiar with non-Nastaliq script through that in a way Pakistanis are not.

**Comment by bgo-eiu** [comment] 2022-05-15 14:23
https://en.m.wikipedia.org/wiki/Lam_with_tah_above

This is a letter that is only used in Pakistan. Noto Nastaliq is one of the only fonts that includes it. If rendered in the Nastaliq font, people who speak other languages would at least be able to see what it is, rather than an empty character box as it shows in most fonts

**Comment by bgo-eiu** [comment] 2022-05-15 14:34
As far as sizing goes, if there's a reference for how the smaller sizes are selected in the renderer code that would be helpful. The point still stands in any case that the font does look a lot better at smaller scales than the rasterized vector path image, if you make the two fonts the same pixel height it still seems fine.

**Comment by 1ec5** [comment] 2022-05-18 17:27
> The font used on
> https://ur.wikipedia.org/static/images/project-logos/urwiki.png
> seems better - but i don't know which it is.

[An earlier version of the Urdu Wikipedia logo](https://meta.wikimedia.org/wiki/Wikipedia_logo_in_each_language#U) used Jameel, Noori, and Nastaleeq. [A later revision](https://commons.m.wikimedia.org/wiki/File:Wikipedia-logo-v2-ur.svg) uses Nafees Web Naskh based on a community consensus.

**Comment by bgo-eiu** [comment] 2022-05-18 18:07
I want to point out the obvious here as well for the sake of clarity - the name of Wikipedia transliterated to Arabic script is not a great reference point for legibility or recognizability because it's not a recognizable word.

**Comment by pnorman** [comment] 2022-05-19 19:40
> it would be just to prioritize the Nastaliq font over Naskh within Pakistan - just that country, no need anywhere else.

This is not possible. The fonts used are worldwide, and we do not have the ability to use different fontstacks per country.

**Comment by imagico** [comment] 2022-05-19 20:57
> This is not possible. The fonts used are worldwide, and we do not have the ability to use different fontstacks per country.

Well - theoretically we could filter the data in SQL by location and style it differently (using different font lists) depending on if the feature is within a certain admin boundary or not.  But this would be technically rather complex (and would make the whole style quite a bit more complex) and we have always had in the past a clear consensus that we do not want to federate the style.

There are a number of things i think that would be good to know that are not clear to me at the moment.  Regarding real wold use of writing styles - since the information i have seems to be conflicting on that:

* What is common as a writing style for Urdu using Arabic script in various countries where Urdu is used significantly?  In general everyday life but specifically of course also in maps?  The [English Wikipedia page on Urdu](https://en.wikipedia.org/wiki/Urdu) shows two examples from India and the UAE (https://en.wikipedia.org/wiki/File:UAE_signboard.jpg, https://en.wikipedia.org/wiki/File:Trilingual_road_sign_in_India.png) that use Nastaliq.

* What styling is typically used for Arabic language text in Pakistan?  That is practically probably not that common so it might be difficult to assess reliably.

And regarding legibility at small font sizes:

*  it would be very useful if someone would do some tests with Noto Nastaliq - both for horizontal point labels (populated places, POIs) and for line labels (e.g. roads) to see if at a size that is legible this works with the label offsets and the road rendering widths we use so far.

**Comment by bgo-eiu** [comment] 2022-05-19 22:15
Yes, I have realized now that scoping a font to a geographic region in the existing Carto infrastructure is a much more challenging task than I had initially assumed. I still think it is worth considering, especially since this would not be the only use case for it, but it is likely I will also spend some time looking into how to achieve this through a vector tiles library that has some existing features in place for geographic queries.

> What is common as a writing style for Urdu using Arabic script in various countries where Urdu is used significantly? In general everyday life but specifically of course also in maps? The [English Wikipedia page on Urdu](https://en.wikipedia.org/wiki/Urdu) shows two examples from India and the UAE

Pakistan is the only country where Urdu written in Arabic script is in widespread use. Urdu is also spoken widely in India, but because it is mutually intelligible with Hindi, and most Indians use the Devanagari script, most Urdu speaking Indians would be fine to use the Devanagari script for practical purposes because that is what others locally understand. Historically, when India and Pakistan were one country, this was something that differed depending on whether you were Muslim or Hindu, but in present day situation, Indian Muslims are increasingly less likely to have much context or reason to use the Arabic script. Some references which discuss this:
* Present day situation: https://www.cambridge.org/core/journals/language-in-society/article/abs/urdu-in-devanagari-shifting-orthographic-practices-and-muslim-identity-in-delhi/F89F162B15A6720008639E627D6F0242
* Historic situation: https://en.wikipedia.org/wiki/Hindi%E2%80%93Urdu_controversy

If you do see Arabic script written in India, it will be in Nastaliq, since writing that way is something people have been doing since before Pakistan and India split apart.

The reason the UAE has Urdu signage is because in large parts of the UAE, the majority of the population is comprised of Pakistani immigrants. Only about 1 in 10 people living in the UAE is Arab, and there are more Pakistanis there than Arabs, so even though the government is operated by Arab nationals they have to provide documents, signage, etc. in Urdu for all the Pakistanis that live and work there. If you see Urdu in the UAE, it is for that purpose specifically as people of other nationalities there would not understand it. There are parts of Bahrain, Oman, Kuwait, Saudi Arabia, and Qatar additionally where Pakistani immigrants are numerous enough that you may encounter examples like this.

> What styling is typically used for Arabic language text in Pakistan? That is practically probably not that common so it might be difficult to assess reliably.

Most Pakistanis are actually exposed to some Arabic language text through religion, as Muslims are expected to read and memorize religious texts in their original language even if they do not understand the meaning of the words. However, readability is not necessarily an objective of religious texts, and they are most typically styled in elaborate calligraphic forms that are considered more suited for their significance. Arabic in a Quran would look like this:
![image](https://user-images.githubusercontent.com/100172442/169412578-9b445ad5-2800-4c2c-9420-2c73330be003.png)

In some older Qurans, the calligraphy may be complex in such a way that no two instances of a letter look quite the same. Often the way this is taught is not even by breaking down the letters and sounds that make up words, but just how to say the corresponding passage or phrase as a whole and the general form it takes.

There is actually a set of Quranic ligature characters in unicode that comes from this context. ﷽‎ is a whole phrase condensed to a single character that is practically impossible to read if you try to look at the original words. Someone familiar with the religion though would recognize that general shape/form as being associated with the Islamic phrase it references just from looking at it and would not need to actually read the individual letters. None of that is really helpful or relevant for a map, and does not really make it easy for Pakistanis to read non-religious Arabic (which also does not resemble Arabic for every day use that closely), but that would be the literal answer to this question.

> it would be very useful if someone would do some tests with Noto Nastaliq - both for horizontal point labels (populated places, POIs) and for line labels (e.g. roads) to see if at a size that is legible this works with the label offsets and the road rendering widths we use so far.

I do want to try this, I will share if I have time for it at some point soon.

**Comment by imagico** [comment] 2022-05-19 22:35
If i understand you right you essentially seem to indicate that Urdu is - when written in Arabic script - overwhelmingly written in Nastaliq style independent of the country.  That would mean if we knew what the language in the name tag is we could select the font based on language (which would still technically challenging - but that would be a general problem of solving #2208).

I understand that this issue is not exclusively about Urdu - but solving it for Urdu would already be an improvement obviously.

**Comment by bgo-eiu** [comment] 2022-05-20 20:59
Yes, if that is easier to do it would definitely be an improvement. If it were implemented based on language it would have to follow some kind of rule system to avoid conflating languages.

Some scenarios from the map...

* [`name=جدة` + `name:ar=جدة` + `name:ur=جدة` + `name:en=Jeddah`](https://www.openstreetmap.org/node/1933393717)

Jeddah, Saudi Arabia has a three letter name that does not have any sounds which are incompatible between Arabic and Urdu. The most reliable way I can think of to discern that  this is an Arabic name is the Wikidata item, which is tagged, which contains the "native label" property that states the origin language of the name. For any name which is tagged with multiple identical language labels, some of which are not written with Nastaliq, the renderer would have to consult an index based on the wikidata in the absence of geographic context. Tagging the "native label" in OSM itself has historically been unpopular, and at this point would likely be seen as redundant to the wikidata tag if  proposed again.

*  [`name=پشاور‎` + `name:ar=بيشاور` + `name:fa=پيشور` + `name:ur=پشاور‎` + `name:sd=پشاور` + `name:en=Peshawar`](https://www.openstreetmap.org/node/294107164)

Peshawar, Pakistan starts with the letter پ which is not used in Arabic, so the Arabic name does not match. Persian (name:fa) does have the letter پ, but the Persian localization also omits the vowel ا, so it does not match. The only matches to the name tag here are the Urdu and Sindhi (name:sd) localizations - Sindhi is a language which is only written in an Arabic-based script in Pakistan, so the presence of an identical name:ur and name:sd can be used to infer that this name is safe to display in Nastaliq without referencing the wikidata tag.

* [`name=لاہور - سرگودھا روڈ` + `name:ur=لاہور - سرگودھا روڈ` + `name:en=Lahore - Sargodha Road`](https://www.openstreetmap.org/way/1010039650)

This has no other name tags so we can safely infer this is Urdu. Road names do not often have Wikidata tags, but it is also uncommon for them to be translated outside of a local language.

**Comment by imagico** [comment] 2022-05-21 07:35
As your examples show determining the language of the name tag is highly non-trivial and very often not possible without additional information.  I would be very reluctant to use external data sources for that unless there is clear consensus in the OSM community that this information is not to be recorded (which there quite clearly is not).  I also doubt it would be good if we require mappers to redundantly record `name=*` and `name:<lang>=*` to ensure proper label rendering - that is inefficient mapping practice and most local communities with a single dominant language do not see this favorably.  And as you illustrated this is not without ambiguities either.  A real solution would be if the OSM community could either agree on a method to record the language of the name tag or to abolish the generic name tag and record the locally used language(s) instead in some way.

I would suggest to move any general discussion how to practically determine the language of the name tag to #2208 because it is a generic issues for many languages that make shared use of the same unicode characters.

**Comment by khaledhosny** [comment] 2022-06-20 17:00
> you could have Nastaliq on Urdu, Punjabi, Sindhi, and Baloch, and leave Pashto the same.

A nitpick, AFAIK, Sindhi is written in Naskh and it is nearly impossible to find examples of it written in Nastaliq, there are even Sindhi letters like ڪ that has no known Nastaliq model.

**Comment by pnorman** [comment] 2022-07-07 21:52
Duplicate of #2208.

Both issues are a case of a unicode codepoint having different renderings depending on language and/or location. If we ever figure out a solution to Han unification, it will also apply here.

**Closed by pnorman** 2022-07-07 21:52 UTC

**Comment by sommerluk** [comment] 2022-07-08 18:17
I've updated the description of #2208 to cover this issue.

**Comment by Feliks-WR** [comment] 2024-05-16 13:50
By the way, I have tried *Noto Nastaliq *on Windows (11) via WinAeroTweaker.
It sucks, a lot is broken.
**Gulzar**, though, is much better, though annoying when file explorer "compact mode" is less compact than the normal mode.
***Urdu typesetting*** wins, iff it is made a bit bigger.
Also, some Windows apps (e.g. settings, taskbar) are mostly unaffected by system font change...

Microsoft, PLEASE learn from **Apple** and *Google*!
