### ISSUE TITLE
CJK blurred beyond recognition

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4187] opened 2020-08-10 13:38 UTC
I am sorry but for e.g., building names, Chinese characters,
```
警察廣播
電台臺東
  分臺
```
are blurred beyond recognition,
![4930-2](https://user-images.githubusercontent.com/1230959/89787531-3158ef00-db50-11ea-93f1-a748554a01d2.jpg)

I assume nobody on the team reads Chinese, so are unaware of the problem.
But this makes OSM.ORG barely useful for major Asian populations. Seen on Desktop at
https://www.openstreetmap.org/?mlat=22.75587&mlon=121.15131#map=19/22.75587/121.15131

I'm sorry I can't find the previous report.

**Comment by jidanni** [comment] 2020-08-10 13:54
[Here](https://www.openstreetmap.org/node/7786127350#map=19/22.75569/121.15334) we see the words at the right are only half the size of their readable equivalents at the left. 
![4765-3](https://user-images.githubusercontent.com/1230959/89789873-c6111c00-db53-11ea-92dd-742d52d8f0aa.jpg)

**Comment by imagico** [comment] 2020-08-10 14:06
Duplicate of #2265, see also https://github.com/gravitystorm/openstreetmap-carto/issues/4103#issuecomment-608356434.

**Closed by imagico** 2020-08-10 14:06 UTC
