### ISSUE TITLE
small building=retail not rendered

### ISSUE THREAD

**Issue by Newbie07** [gravitystorm/openstreetmap-carto#2311] opened 2016-08-27 12:45 UTC
Have a look at https://www.openstreetmap.org/way/232286493. 

the building is not rendered only the icon for the shop. All other three maps on the main page render the building.

![carto_2016_08_27_14 32 15](https://cloud.githubusercontent.com/assets/3267800/18027459/0b11643a-6c64-11e6-90ef-a8e9dc36285e.png)
![osm_data_2016_08_27_14 30 47](https://cloud.githubusercontent.com/assets/3267800/18027460/0b3f4602-6c64-11e6-8eff-75e352956d9f.png)

**Comment by daganzdaanda** [comment] 2016-08-27 13:19
Hello and welcome :)

This issue has been reported already: #688
That time, it was about highway=pedestrian covering buildings, in your example it is a highway=path with area=yes. 
The decision was made on purpose, and for a good reason, as you can read in the discussion at the link above. The solution in your example would be to make a multipoygon with the outline https://www.openstreetmap.org/way/51731497 and the building as "inner".

**Comment by dieterdreist** [comment] 2016-08-27 14:04
2016-08-27 14:45 GMT+02:00 Newbie07 <notifications@github.com>:

> Have a look at https://www.openstreetmap.org/way/232286493.
>
> the building is not rendered only the icon for the shop. All other three
> maps on the main page render the building.
>

it's clearly a mapping error because the building is tagged as both, part
of the path area and as building, at least the walls of the building have
to be excluded from the path area. Please also consider to add the new
place=square with name=* for the name of the square (as an area over the
whole square, not just the walkable parts).

**Comment by pnorman** [comment] 2016-08-27 22:21
duplicate of #688

**Closed by pnorman** 2016-08-27 22:21 UTC
