### ISSUE TITLE
Add tourism=aquarium symbol!

### ISSUE THREAD

**Issue by IVAN-RSM** [gravitystorm/openstreetmap-carto#3691] opened 2019-02-23 11:55 UTC
It is a type of museum that many cities have, it is not even a point. I think it's time to create a symbol :)

**Comment by Adamant36** [comment] 2019-02-23 12:05
Copy of or related to #2223. Which is closed. It might be worth revisiting though. It seems like it was never resolved.

**Comment by polarbearing** [comment] 2019-02-23 12:15
I propose to close this a duplicate and reopen  #2223. As zoo has no icon, a label for aquarium would be sufficient.

**Comment by IVAN-RSM** [comment] 2019-02-23 12:39
Then you have to rethink represent the zoo and the aquarium with a symbol, there are things that are used less that have their own symbols!

**Comment by matkoniecz** [comment] 2019-02-23 13:46
I am closing it as a duplicate of #2223

I am not considering reopening of #2223 as it has quite low usage - https://taginfo.openstreetmap.org//search?q=tourism%3Daquarium - just 683 uses worldwide

> It seems like it was never resolved.

It was resolved by declining to render it.

**Closed** 2019-02-23 13:47 UTC
Labels: declined, duplicate

**Comment by Adamant36** [comment] 2019-02-23 23:00
I meant not resolved because nothing was ever said about it after Polarbearing's last comment about usage, for or against. An issue just being closed by a single devoid of discussion doesn't really mean that much. 

Btw, there's an extremely small number of aquariums world wide in the first place. I seem to remember there being a discussion somewhere before about how using usage numbers as standard for rendering something or not is as much based on how many of those things are actually out there then some arbitrary thershold. Im pretty sure aquarium was part of that discussion to. 

If I remember correct the barrier to rendering it was that an icon would be to abstract, but a border like zoos have might work. I can't remember exactly, but it something like that. Areas are worth rendering though because they are often large compounds comprising multiple buildings. At least the ones ive seen. 

The important though is that yes there might only be 600 something mapped, but theres only like 700 in the world in the first place and they will never reach the normal arbitrary thereshold.

**Comment by jeisenbe** [comment] 2019-02-23 23:49
If there are fewer than 1000 public aquariums on the planet (and this is
certainly possible) we shouldn’t use a distinctive icon, but sharing the
same rendering with zoos and theme parks would be sensible.

**Comment by polarbearing** [comment] 2019-02-24 00:02
Please let's continue discussion in #2223 so it won't get fragmented.
