### ISSUE TITLE
Rendering of intermittent streams broken

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#2633] opened 2017-05-14 20:59 UTC
Rendering of intermittent streams seems broken in master.

Screen shot:
![screenshot_2017-05-14_22-58-37](https://cloud.githubusercontent.com/assets/5251909/26037683/f10bd4e6-38f8-11e7-856f-85529ae47555.png)

**Comment by math1985** [comment] 2017-05-14 21:05
Did something go wrong with the hstore merge perhaps?

**Comment by imagico** [comment] 2017-05-14 21:57
I don't think this is due to the hstore changes, i think this is caused by https://github.com/gravitystorm/openstreetmap-carto/commit/970df74006598a246201b51e68c49b5ee8ed599b, specifically

https://github.com/gravitystorm/openstreetmap-carto/blame/master/water.mss#L195-L197

Side note: the water-lines code is quite difficult to understand meanwhile with all the tunnel/background/bridge stuff mixed fairly wildly.

**Comment by pnorman** [comment] 2017-05-18 04:04
Does this also impact 3.3.0?

**Comment by pnorman** [comment] 2017-05-18 04:07
> I don't think this is due to the hstore changes, i think this is caused by 970df74, specifically
> 
> https://github.com/gravitystorm/openstreetmap-carto/blame/master/water.mss#L195-L197

Yes, that looks like an error. some background/line-* properties are set, while background/line-color is unset except when int_tunnel = yes

**Comment by nebulon42** [comment] 2017-05-20 15:04
Well spotted. This was somehow an leftover I have missed. This also impacts 3.3.0. I will cherry pick the commit to the 3.x branch once committed. As I have seen that 3.3.0 is now live we should probably release 3.3.1.

**Comment by boothym** [comment] 2017-05-20 18:46
I noticed something similar with a large black line on the map - is it related to this issue?  https://www.openstreetmap.org/way/4301350 ok on z18/19 though

**Comment by andischan** [comment] 2017-05-21 07:14
Have you stopped the z=12 rerendering because of this?
![1faa5ada-f904-4802-9eda-f072c11a818c](https://cloud.githubusercontent.com/assets/24589670/26281923/dc50a0ce-3e05-11e7-8686-d30712d0645b.png)

**Comment by nebulon42** [comment] 2017-05-21 11:23
@boothym Thanks for reporting this. It is now also fixed in #2636.
@andischan I'm not aware of anybody of us getting in touch with the sysadmins about this regression. So might be a tile server load or cache issue.

**Closed** 2017-05-22 17:21 UTC
Labels: bug, regression

**Comment by Robot8A** [comment] 2017-05-28 20:26
It also happens in channel bridges: https://www.openstreetmap.org/#map=17/41.62288/-0.90528

**Comment by nebulon42** [comment] 2017-05-28 21:01
@Robot8A thanks, this was also fixed.

**Comment by andrewharvey** [comment] 2017-06-16 11:33
Not sure if you're aware but this is still visible/an issue on osm.org, see the black lines which are intermittent streams:

![image](https://user-images.githubusercontent.com/117278/27224975-5ae7ecd2-52db-11e7-9e12-0705fb54f57d.png)

https://www.openstreetmap.org/#map=13/-31.5630/159.0870

**Comment by imagico** [comment] 2017-06-16 11:41
You have old tiles here - either browser cache or server side caching.

**Comment by andrewharvey** [comment] 2017-06-16 11:42
> You have old tiles here - either browser cache or server side caching.

No worries, I'll let it sort itself out over time then.

**Comment by naoliv** [comment] 2017-06-18 22:34
New way https://www.openstreetmap.org/way/501481012 and it's still being rendered black: https://www.openstreetmap.org/#map=17/-28.96073/-52.65422

It can't be a cache issue with new data.

**Comment by HolgerJeromin** [comment] 2017-06-19 07:05
The fixed version of the style has not yet been rolled out. Just look when https://github.com/openstreetmap/chef/issues/124 is closed.
