### ISSUE TITLE
Above ground platforms mapped as areas that overlap roads render beneath the roads instead of above them.

### ISSUE THREAD

**Issue by evansiroky** [gravitystorm/openstreetmap-carto#4221] opened 2020-10-14 19:38 UTC
### Expected behavior

Platforms mapped as areas that have the `layer` tag greater than a road beneath should render on top of the roads below.

### Actual behavior

Platforms mapped as areas always seem to render beneath the roads regardless of whether they are actually above them in real life and via the use of the `layer` tag.

### Links and screenshots illustrating the problem

See example here: https://www.openstreetmap.org/#map=19/39.73658/-75.54966.

![Screen Shot 2020-10-14 at 12 36 57 PM](https://user-images.githubusercontent.com/3112493/96037000-1b9acb00-0e1a-11eb-9b03-98e6d9304d44.png)

**Comment by mboeringa** [comment] 2020-10-14 21:20
This is essentially a duplicate of the man_made=bridge issue, that has been discussed multiple times before, see e.g.:

https://github.com/gravitystorm/openstreetmap-carto/issues/3203

Unfortunately, people expect miracles to happen, and all stuff to magically adhere to **layer=x** tagging in OSM, but that is not the case. 

It is not without reason that essentially all other real world competing styles (think e.g. the big ones like Google, Bing, Mapbox), never render this kind of stuff at all (unless it is maybe part of small scale "indoor" rendering of pseudo 3D models at high zoom).

In reality though, rendering both polygons and lines, and the potentially _hundreds of different thematic layers_ that can be created from the OSM tagging system, in a properly layered fashion is really tough. Just imagine, there are eleven valid layer values (-5 to 5),  and each thematic layer (platform / bridges etc.) needs to be interleaved.

I developed a personal renderer that does resolve _some_ of these issues related to bridges and platforms, but in my case that already requires a few hundred layers to be rendered... Each thematic layer results in eleven separate "layers" for each OSM layer=x tag. That is tough to translate into a system that also needs to perform like this main style.

See this comment though, for an example result of Edinburgh Waverly station, and notice how the man_made=bridge structures properly render on over railroads and platforms:
https://github.com/gravitystorm/openstreetmap-carto/issues/3491#issuecomment-531568138

And for a number of other related issues:

https://github.com/gravitystorm/openstreetmap-carto/issues/2130
https://github.com/gravitystorm/openstreetmap-carto/issues/2037
https://github.com/gravitystorm/openstreetmap-carto/issues/688

**Comment by pnorman** [comment] 2020-10-14 22:19
Platform areas are rendered independently of roads, and it is not practical to change this. We could move them before roads or after roads, but not interleave them with roads based on the layer tag.

**Closed by pnorman** 2020-10-14 22:19 UTC
