### ISSUE TITLE
Rendering of natural=ridge

### ISSUE THREAD

**Issue by drgweber** [gravitystorm/openstreetmap-carto#1148] opened 2014-12-08 20:52 UTC
Ridges are important geographical objects which, to my knowledge, are not currently rendered in carto style 

They can range in length from 1 km to over 100 km and are commonly shown on printed maps in large upper case letters (see public domain image from IBGE, Serra=Ridge). Current usage is around 17000 http://taginfo.openstreetmap.org/tags/?key=natural&value=ridge#overview, but I guess usage would be higher if rendered. It also seems that natural=ridge was used in many cases instead of natural=mountain_range because the key ridge is formally defined while mountain_range is not.

In South America ridges are very important reference points defining whole regions, for example the Serra da Mantiqueira http://www.openstreetmap.org/way/266727831. Frequently, when planning trips the lack of rendering can be an important drawback since passing over ridges can be difficult or impossible.

While important ridges are commonly shown on printed maps, commercial digital maps (e.g. Bing, Google) usually do not show them. Therefore, this could be a nice opportunity to add a distinguishing feature to OSMs main rendering style.

My suggestion is to render at zoom levels smaller than 10, but perhaps this would depend on the length of the ridges.

Similar issue seems to be #1097

![image](https://cloud.githubusercontent.com/assets/9018415/5346375/79ef4522-7f06-11e4-967d-3efcf56d5980.png)

**Comment by mboeringa** [comment] 2015-01-03 13:23
I have now made an attempt to render natural=ridge. This actually turns out to be quite difficult. A solid line like for the one sided natural=cliff representing a steep decline, isn't a suitable representation. Neither is a simple dashed line, as they look to much like paths. The image below represents about the best I could come up with, trying to represent the not so prominent nature of this feature (click to enlarge).

The image also contains another novelty, the rendering of the natural=valley tag, which really adds something in combination with contour lines.

![ridge rendering example](https://cloud.githubusercontent.com/assets/7635726/5602530/85ff9e8c-9353-11e4-94b5-ae099ea80b23.jpg)

**Comment by drgweber** [comment] 2015-01-03 21:58
I think your first attempt looks very promising, but the ridges shown here seem to be quite small. 

How would larger structures be rendered? For example Serra da Moeda in Brazil:
http://www.openstreetmap.org/way/318209935#map=10/-20.3028/-43.9494

or an even larger one like Serra Geral de Goiás
http://www.openstreetmap.org/way/318565962

I've added several new ridges in my region over the past weeks, don't know how many, but certainly over a hundred, and I am not remotely done. It would seem than ridges are currently severely under-represented in OSM database.

One thing I noticed is that many ridges define boundaries, in a very similar way as some rivers do, Serra Geral de Goiás is one of those. Therefore one need to keep in mind that in many cases the rendering of ridges and boundaries will overlap. I don't know what kind of challenge that represents for rendering, but I think it is worthwhile to mention it. 

I like your representation of valleys quite a lot, in fact it is closer to what I had in mind initially for ridges.

**Comment by mboeringa** [comment] 2015-01-03 22:29
> How would larger structures be rendered? For example Serra da Moeda in Brazil:
> http://www.openstreetmap.org/way/318209935#map=10/-20.3028/-43.9494
> 
> or an even larger one like Serra Geral de Goiás
> http://www.openstreetmap.org/way/318565962

@drgweber, to be honest, *all* of the examples you linked here in the this issue thread are in my opinion **natural=cliff**, not **natural=ridge**. All of them represent steep descends coming from relatively flat high areas, as can clearly be seen if you look at the data using the OpenCycleMap view and its great relief view using shading and contours:

E.g.
http://www.openstreetmap.org/way/266727831#map=11/-22.7198/-45.5524&layers=C
http://www.openstreetmap.org/way/318565962#map=11/-12.6078/-46.3390&layers=C
http://www.openstreetmap.org/way/318209935#map=12/-20.3239/-43.9862&layers=C

A natural=ridge is something that should have **two** clearly sloping sides, not one:

http://wiki.openstreetmap.org/wiki/Tag:natural%3Dridge
and
http://en.wikipedia.org/wiki/Ridge

and compare that with cliff:
http://wiki.openstreetmap.org/wiki/Tag:natural%3Dcliff
and
http://en.wikipedia.org/wiki/Cliff

I would also strongly recommend you to digitize the course of the **natural=cliff** (ridges) more accurately, following the top of the cliffs, as represented e.g. by the contours in OpenCycleMap. This will make an ultimate rendering of the cliffs or ridges together with contours or shading *much* more useful.

E.g. look at the accurately drawn cliffs / ridges in the first image I posted with the comparison of Snowdon Mountain in North Wales in both my own renderer, and OpenStreetMap Carto:

![ridge rendering](https://cloud.githubusercontent.com/assets/7635726/5378396/26556ea2-808a-11e4-931e-f22b9ee05774.jpg)

(I am assuming here the location of the contours is accurate, if your GPS/GPX trace says something different when walking past the edge of a cliff, it may be wise to use that GPS data in some cases).

**Comment by drgweber** [comment] 2015-01-03 23:39
> @drgweber, to be honest, all of the examples you linked here in the this issue thread are in my  opinion natural=cliff, not natural=ridge. All of them represent steep descends coming from relatively flat high areas, as can clearly be seen if you look at the data using the OpenCycleMap view and its great relief view using shading and contours:

Dear mboeringa

Sorry, no they are not cliffs. Please trust me, viewing this from OpenCycleMap is misleading you. 

I mean, I go to Serra da Moeda frequently, and I can assure you it is a ridge which is what the name "Serra" actually means. In fact "Serra"  literally means a "saw" and probably got this name because the sequence of peaks resemble a saw when facing upwards. The name has nothing in common with the Portuguese name for "cliff" which is "penhasco".

I mean, I know what a cliff is, here is an example which I mapped 
http://www.openstreetmap.org/way/197862027
this is clearly a cliff, I have been there and seen it myself.

Serra Geral de Goiás is bordered by a *lower* plateau and *some* parts are indeed cliff-like, but no, not the whole structure. I mean tagging the whole 200km (or more) of that Serra as a cliff because some parts are cliffs sounds strange to me.

What you could argue though is that they are perhaps better described as "Mountain Ranges", but this tagging is not covered by OSM rules. Probably that is the reason why neither Andes nor Alps show up in nominatim. Therefore, the closest match at present for serra is ridge and not cliff.

Here is another example of a large structure if you like, Serra do Espinhaço
http://www.openstreetmap.org/way/248919543
(if you look up Serra do Espinhaço in nominatim you will see many entries because it has been mapped separately over several regions. Eventually we will have to join the pieces, in other words, it is really much larger than this.)

> I would also strongly recommend you to digitize the course of the natural=cliff (ridges) more accurately, following the top of the cliffs, as represented e.g. by the contours in OpenCycleMap. This will make an ultimate rendering of the cliffs or ridges together with contours or shading much more useful.

Of course, given enough time, I would be more than happy to get a more accurately mapping of ridges, but we are *very* short of mappers in our region.

At present I am trying to get as many ridges into the map as possible, even with an just approximate location. Why? Because it looks *very* stupid when a local user searches OSM for the name of a famous ridge and nothing at all shows up. Therefore I am afraid that accuracy will have to wait a bit.

Anyway, thanks a lot for your comments.

**Comment by pnorman** [comment] 2015-01-04 00:11
> All of them seem to represent nearly impassable steep descends coming from relatively flat high areas

Not to say that they are definately ridges, but they've got tertiary roads crossing them (e.g. http://www.openstreetmap.org/way/318209935#map=15/-20.2713/-43.9533&layers=C). Taking a look at photos of that road, it's not a cliff.

I had a look on MQ to see if we're doing anything with ridges or similar features, and all I spotted were some very large-scale labels like [Rocky Mountains](http://www.openstreetmap.org/#map=7/47.554/-116.521&layers=Q)

**Comment by pnorman** [comment] 2015-01-04 00:30
In any case, alignment with contours doesn't matter here - we don't render contours, and they are examples of long natural=ridge features, which do exist.

**Comment by mboeringa** [comment] 2015-01-04 08:41
> Sorry, no they are not cliffs. Please trust me, viewing this from OpenCycleMap is misleading you.
> 
> I mean, I go to Serra da Moeda frequently, and I can assure you it is a ridge which is what the name "Serra" actually means. In fact "Serra" literally means a "saw" and probably got this name because the sequence of peaks resemble a saw when facing upwards. The name has nothing in common with the Portuguese name for "cliff" which is "penhasco".
> 
> I mean, I know what a cliff is, here is an example which I mapped
> http://www.openstreetmap.org/way/197862027
> this is clearly a cliff, I have been there and seen it myself.
> 
> Serra Geral de Goiás is bordered by a lower plateau and some parts are indeed cliff-like, but no, not the whole structure. I mean tagging the whole 200km (or more) of that Serra as a cliff because some parts are cliffs sounds strange to me.

OK, I agree your local knowledge is more valuable than my looking at OpenCycleMap. So if you know they are better classified as ridges, than that is fine with me.

> What you could argue though is that they are perhaps better described as "Mountain Ranges", but this tagging is not covered by OSM rules. Probably that is the reason why neither Andes nor Alps show up in nominatim. Therefore, the closest match at present for serra is ridge and not cliff.

***However***, if the general consensus in your country is, and I can well imagine this considering the size of the features you are digitizing, that this is a "mountain range", than please add a **natural=mountain_range** tag instead of declassifying them to **natural=ridges** just for rendering... Of course the distinction between these two is a bit vague, but I would rather think that features this big (hundreds of kilometres), would generally be better served with **natural=mountain_range**. The tag is already unofficially documented on this proposal page:

http://wiki.openstreetmap.org/wiki/Proposed_features/Mountains

Although OpenStreetMap Carto doesn't yet support this tag in rendering, you can always post another issue here on the bug-tracker with a request to do so.

In addition, my OSM Renderer for ArcGIS that I have in development, already supports rendering of this tag. In the below image, starting at the red arrow, you see the name of the Great Dividing Range in Australia, tagged as **natural=mountain_range**, as just letters spread out along its major length, as most topographical maps display this type of feature:

![mountain range rendering](https://cloud.githubusercontent.com/assets/7635726/5605290/5bc62604-93f3-11e4-9529-e0b92eb19db7.jpg)

**Comment by mboeringa** [comment] 2015-01-04 09:10
> I had a look on MQ to see if we're doing anything with ridges or similar features, and all I spotted were some very large-scale labels like Rocky Mountains

I wonder where this data is coming from? Running an overpass turbo query for areas, nodes, ways, relations using **natural=ridge**, **natural=mountain_range** and **natural=massif**, doesn't return anything named Rocky Mountains in the western US... (it does return other named features though). Is it Natural Earth?

**natural=ridge**
http://overpass-turbo.eu/s/6P9

**natural=mountain_range**
http://overpass-turbo.eu/s/6P8

**natural=massif**
http://overpass-turbo.eu/s/6Pa

**Comment by imagico** [comment] 2015-01-04 09:57
To hopefully clear up confusion a bit:

http://www.openstreetmap.org/way/318565962

is an escarpment - in large parts forming cliffs, in very small parts possibly also ridges.  Neither of them are continuous along the whole thing.

http://www.openstreetmap.org/way/318209935

is mostly ridges, but with several interruptions, a ridge is supposed to be a continuously convex structure.

http://www.openstreetmap.org/way/248919543

is neither - it is a mountain range, strongly structured so ridges and possibly cliffs - if they exist - only extend a few kilometers.

> What you could argue though is that they are perhaps better described as "Mountain Ranges", but this tagging is not covered by OSM rules.

There are taggings in use for mountain ranges, some maps also render them.

Like:

http://www.openstreetmap.org/relation/2127978
http://www.openstreetmap.org/relation/3932224

As far as rendering goes - i still think a fairly thick gray line would be a good option for this style.  The examples mboeringa showed are not that useful i think since they render contours and showing ridge lines together with contours is problematic at best.  Of course ideally ridge lines should be interrupted by other features along their path (roads, peaks etc.) - not sure if there is a good way to do this in mapnik.

It does not have to look perfect, the most important thing is to properly show what mappers have mapped without disturbing the map too much.

**Comment by mboeringa** [comment] 2015-01-04 10:38
> There are taggings in use for mountain ranges, some maps also render them.
> 
> Like:
> 
> http://www.openstreetmap.org/relation/2127978
> http://www.openstreetmap.org/relation/3932224

The two examples you show actually use another tagging scheme than **natural=mountain_range**. They use:
**place=region**
**region:type=mountain_area**

This is probably justified, since these are subdivisions of the bigger Alps and Himalaya natural=mountain_range, so the tag **region:type=mountain_area** seems suitable.

> **It does not have to look perfect**, the most important thing is to properly **show what mappers have mapped without disturbing the map too much**.

I am not to sure if that is a good basis or justification for any render rule development, if i take your assumption to the extreme, I could say: drop ***all*** rendering using carefully crafted symbols, colors and labels, *just show nodes and ways as in* ***ID's editor window*** because that shows every last node and way ever digitized in OSM even if it not rendered on any style yet... I guess we don't want to go there...

I do think careful thought should be given to any type of rendering. I am not yet sure if I will keep the ridge rendering as I currently have it, or only start render *named* ridges, by showing their label stretched along the digitized line, as in valleys.

**Comment by imagico** [comment] 2015-01-04 16:16
> I am not to sure if that is a good basis or justification for any render rule development, if i take your assumption to the extreme, I could say: drop all rendering using carefully crafted symbols, colors and labels

I did not mean this as a general rule for anything mapped but specifically for natural=ridge which is (a) widely mapped - >15000 times (b) is not at all uncommon to be shown in maps in general (c) other tags, i.e. natural=cliff, are widely abused to make ridges show up in the map and (d) it is repeatedly being requested to be added to the style.

**Comment by mboeringa** [comment] 2015-01-04 17:51
> I did not mean this as a general rule for anything mapped but specifically for natural=ridge which is (a) widely mapped - >15000 times (b) is not at all uncommon to be shown in maps in general (c) other tags, i.e. natural=cliff, are widely abused to make ridges show up in the map and (d) it is repeatedly being requested to be added to the style.

I am not disputing the sense of rendering ridges at all..., that's why I am investing time in this, I just think it needs careful consideration how. And if it needs just a label, or that a "physical" rendering in the form of a line is necessary... 

Thanks for the clarifications about the map features @drgweber pointed out, and your opinions about them. As you already more or less pointed out in your clarifications, considering the size of the features, is probably vital in terms of calling something a **natural=mountain_range** or a **natural=ridge**. To my feeling, **natural=mountain_range** should be used for features in the minimum 5-10 km wide , to 100's of kilometres length ranges. So this includes the: 

Serra Geral de Goiás
http://www.openstreetmap.org/way/318565962

which clearly extends for 100's of km. **natural=ridge** is probably best suited for anything in the range of a minimum 100 meter wide to 5-10 km length range or so.

Maybe an image explains it better, at least how I currently interpret these tags, or how they possibly should be interpreted, @imagico, let me know what you think...:

![landforms](https://cloud.githubusercontent.com/assets/7635726/5606831/6f56404c-9442-11e4-92ce-85af6b993597.jpg)

**Comment by mboeringa** [comment] 2015-01-04 18:37
Well, to get a clearer picture of this, I decided to try and locate this place of the above image - Serra de Moeda - on Google. This gives the image below. As @drgweber pointed out, the "contours" were slightly confusing. It does look like the original line digitized by @drgweber could be interpreted as a rather big **natural=ridge**, albeit probably an eroded escarpment...

![serra da moeda_google](https://cloud.githubusercontent.com/assets/7635726/5607004/78c3edea-9448-11e4-8358-a615d599169a.jpg)

**Comment by drgweber** [comment] 2015-01-05 11:47
When I started to map the Serras in this region my understanding was that "Serra" translates best as "ridge". The official IBGE maps which we are allowed to use for OSM simply show in capital letters the approximate location of these Serras, they do not go into any geological details. At the same time, the only documented/approved tag I found on OSM's wiki was natural=ridge. So it was a natural step to map all the Serras as ridges. It is now clear to me that it best to revise this.

After your comments, I am realizing that English word "ridge" is being used in this discussion in a very strict context, while the Portuguese "Serra" seems to be applied in a very broad sense. (Please correct me if I am wrong, English is not my first language.) I don't know if the related Spanish "Sierra" is used in a similar broad context, but I suspect it is. 

On the other hand this wiki page http://wiki.openstreetmap.org/wiki/Proposed_features/Mountains as well as the http://wiki.openstreetmap.org/wiki/Proposed_features/ridge do not give me the impression of such a strict context for ridges. So clearly, there seems to be the need for a revision of these tags to get some consistent definitions.

Still, there are numerous Serras that fit the strict definition of ridges, one of them is Serra do Curral in which defines de border between Belo Horizonte (where I live) and Nova Lima. 
http://www.openstreetmap.org/way/319501931

Another point that I am understanding now is how difficult it is to pin-point Serras from aerial images. Historically of course these Serras were named by looking at them from the ground. What you see from the ground are seemingly continuous stretches of peaks running along the horizon which completely dominate the landscape.  For example the interesting picture @mboeringa found of Serra da Moeda doesn't make justice to the  view you get when driving alongside. Clearly, it is not at all straightforward to correlate the known Serras to what is shown on Bing images or altimetric contour lines. This is one of the reasons why I have not yet been able to map several other Serras in my region, such as Serra da Gandarela.

**Comment by yopaseopor** [comment] 2015-08-06 22:42
In Spanish and Catalan there's the same meaning about ridge .In Catalan also it sounds and have to be written like Portuguese : SERRA.

Ridges are very important for our territories.There are studied at the schools and they are one of the most important part of our environmental joyness. 
Also I don't understand why Natural Parks that covers some of the "ridges" here in Catalonia are showed (administrative thing) and why not the ridges itself (real and natural thing).

I think about Serra de Collserola , near Barcelona city or Serra del Cadí  near Pyrenees.

**Comment by Tomasz-W** [comment] 2018-07-15 11:12
@kocio-pl Please close this ticket as a duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/788 meta ticket. Move further discussion there.

**Comment by kocio-pl** [comment] 2018-07-15 11:18
OK.

**Comment by jeisenbe** [comment] 2019-09-21 06:53
Reopened, since `natural=valley` is the only tag mentioned on #788 now

**Comment by jeisenbe** [comment] 2020-04-13 14:58
Closed by #3767

**Closed by jeisenbe** 2020-04-13 14:58 UTC
Labels: landcover
