### ISSUE TITLE
Dark Mode support?

### ISSUE THREAD

**Issue by Vectorial1024** [gravitystorm/openstreetmap-carto#5044] opened 2024-11-15 06:50 UTC
A very recent update from the OSM website team itself: https://en.osm.town/@osm_tech/113482687301656785

> 🚀 https://www.openstreetmap.org/ is now also available in [#DarkMode](https://en.osm.town/tags/DarkMode) 🕶️ 🔦 🤓  [#Black](https://en.osm.town/tags/Black) [#OpenStreetMap](https://en.osm.town/tags/OpenStreetMap) [#UI](https://en.osm.town/tags/UI)

The current implementation of "dark mode" in the OSM website is to keep using the default tileset but apply a dimming effect to it, which obviously is only a stop-gap measure since (as far as I know) osm-carto does not have any sort of dark-oriented color scheme yet:

![image](https://github.com/user-attachments/assets/a8fdfe03-98bf-45b1-b5e3-5e5b735cbc1b)

It has quickly drawn criticisms:

https://github.com/openstreetmap/openstreetmap-website/pull/4761#issuecomment-2477526339

> [...] can someone (other than TH) explain the reason for [...] the dimmed tile window?

Then, obviously, the next question to ask is whether osm-carto would get a dark mode update in the future. Perhaps there is some way to generate a canonical "dark tileset" so that the OSM website may use it when it wants to do dark mode?

**Comment by imagico** [comment] 2024-11-15 14:19
Closing as duplicate of #4412.  As mentioned there: Making changes to the style that make it easier to customize colors (and other aspects) are most welcome.  But actually developing a second style with a different color scheme is clearly out of scope here.  Anyone is free to develop a style fork or add-on for that purpose.

As far as the OSM website is concerned.  If they substantially modify the map display from what we created here as a design - like by contrast reducing the rendering as shown - it should of course be indicated to the user that this is not OSM-Carto.  But since osm.org does not mention OSM-Carto at all in the first place this suggestion is kind of moot obviously.

**Closed by imagico** 2024-11-15 14:19 UTC
