### ISSUE TITLE
Amenity=research_institute should be rendered as same as university

### ISSUE THREAD

**Issue by LaoshuBaby** [gravitystorm/openstreetmap-carto#4277] opened 2021-01-06 14:16 UTC
### Expected behavior
when an area was tagged with ```amenity=research_institute```, it should have a colour as same as the area tagged with ```amenity=university```

It should be like this
![Expected background colour like university](https://user-images.githubusercontent.com/42690037/103777888-7f750e80-506c-11eb-94d4-e4483ea95fdf.png)

### Actual behavior
But infact is don't have any background colour!

![Wrong Rendered](https://user-images.githubusercontent.com/42690037/103777957-974c9280-506c-11eb-9875-439cce1d3228.png)

### Links and screenshots illustrating the problem
For example , IMCAS(https://www.openstreetmap.org/way/489691058) is an institute of CAS, the main purpose of that is conduct research, not teach a lot of high school student. So I tagged it with ```amenity=research_institute```, and because it don't open to the public, so I remove ```landuse=commercial ```.It's institute! NOT commercial area!

![data show in iD editor](https://user-images.githubusercontent.com/42690037/103778041-a9c6cc00-506c-11eb-8dae-9df2e6d35fe2.png)

But When I removed this tag, I find it lost background color.

**Comment by LaoshuBaby** [comment] 2021-01-06 14:18
I think this problem will not only happen in China, but will also in other countries which have a institute that intend to conduct research not teach student.
Thanks for you review.

**Comment by imagico** [comment] 2021-01-06 15:51
Duplicate of #2077.

**Closed by imagico** 2021-01-06 15:51 UTC
