### ISSUE TITLE
Access rendering is too prominent

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#749] opened 2014-07-20 16:39 UTC
The rendering of access rendering attracts too much attention, especially also on paths.

See for example [here](http://www.openstreetmap.org/#map=18/28.12186/-81.41984).

See also https://trac.openstreetmap.org/ticket/4837.

**Comment by matkoniecz** [comment] 2015-09-12 20:03
Duplicate of #278

**Closed by matkoniecz** 2015-09-12 20:03 UTC
Labels: roads
