### ISSUE TITLE
Different P icons depending on parking type

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#1823] opened 2015-09-10 06:45 UTC
Is this even possible to do? Would the icon be to small to make it visually possible?
Basically want to see difference between a multi story P building, underground parking and simple surface parking.
Multi story could have a roof shape above the P and an underground would could have a / with a P above or below.

**Comment by HolgerJeromin** [comment] 2015-09-10 07:44
duplicate of #839
In the not too distant future we are technical able to do it (see #1504 ). 
But the icon size is probably a problem. Quick and dirty hack in inkscape:
![underground_parking](https://cloud.githubusercontent.com/assets/2410353/9782843/7b066800-57a0-11e5-9813-f6804cefa360.png)

**Closed** 2015-09-10 11:51 UTC
