### ISSUE TITLE
Add casing for leisure=sports_centre

### ISSUE THREAD

**Issue by Klaus-Tockloth** [gravitystorm/openstreetmap-carto#2464] opened 2016-11-26 07:55 UTC
Currently an area of type leisure=sports_centre has no casing. In my opinion it should be rendered similar to amenity=school which has a casing.

Example:
![bildschirmfoto 2016-11-26 um 08 53 35](https://cloud.githubusercontent.com/assets/5493128/20638933/099b76e2-b3b6-11e6-94fc-6c5f983905c6.jpg)

Link: http://www.openstreetmap.org/#map=17/51.93376/7.57682

Regards Klaus

**Comment by kocio-pl** [comment] 2016-11-26 08:07
Thank you for the report. I'm closing this, as it is the duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/2388 (which just had a wrong title). Feel free to comment there.

Could you prepare the code and maybe test it initially? It would make fixing faster.

**Closed by kocio-pl** 2016-11-26 08:07 UTC
Labels: duplicate
