### ISSUE TITLE
Relation landuse=forest green under leisure park render.

### ISSUE THREAD

**Issue by AllroadsNL** [gravitystorm/openstreetmap-carto#2641] opened 2017-05-24 20:38 UTC
![forest relation](https://cloud.githubusercontent.com/assets/8817345/26424318/16f238be-40d1-11e7-95d4-7550b64b8fa0.PNG)

[situation](http://www.openstreetmap.org/#map=18/52.22840/6.88034)

The relation multipolygon landuse=forest should be rendered above the leisure park?
The tree icons are rendered above.
When a polygon landuse=forest is made, it is above the leisure=park.

![forest relation polygon](https://cloud.githubusercontent.com/assets/8817345/26424452/89d0befa-40d1-11e7-858c-0ad32943de8c.PNG)

**Comment by imagico** [comment] 2017-05-24 21:04
You need to be clearer on what you think the problem is.

In the area you link to i see nothing wrong with the rendering - although the mapping looks fairly chaotic.

For information: The area fills are rendered in order of the polygon sizes with the largest first and the smaller ones above.  This might be confusing if you don't know it.

**Comment by AllroadsNL** [comment] 2017-05-24 21:22
> In the area you link to i see nothing wrong with the rendering - although the mapping looks fairly chaotic.

The link of the situation, the mapping was changed to polygon landuse=forest, this is now the second image.

> For information: The area fills are rendered in order of the polygon sizes with the largest first and the smaller ones above. This might be confusing if you don't know it.

This explains it, the multipoygon was bigger then the leisure polygon, but i think, leisure=park should be rendered under the landuse=forest.

Mostly people want to see the park name in the map. Not a boundary of the park.

A park include all kind of landuses and waters etc., now maybe more and more landcover is used.

**Comment by imagico** [comment] 2017-05-24 21:39
Closing this since there does not seem to be any specific suggestions on what should be changed except

> leisure=park should be rendered under the landuse=forest

As said we order by polygon size, not by area type.  If you have a forest polygon that is smaller than the park it is drawn above, if it is larger it is drawn below with the base color, the pattern is always drawn above.

**Closed by imagico** 2017-05-24 21:39 UTC

**Comment by SK53** [comment] 2017-07-12 13:38
This may be the same or similar problem.

User Breau reported natural=wood rendering in two different colours for [Odell Park](https://www.openstreetmap.org/#map=15/45.9527/-66.6740), Fredricton, NB, Canada, screengrab:

![screenshot 63](https://user-images.githubusercontent.com/5452818/28120113-03c8ff34-670f-11e7-9bb4-1b0ffd6b213d.png)


I downloaded area an checked for anomalies with JOSM validator, but no serious issues. Given that the paler green was parkland colour I immediately suspected this to be the wood fill being rendered under the park. Originally woodland was mapped as one large MP covering the majority of two parks (Odell Park & the Botanical Gardens).

To test this [I split](https://www.openstreetmap.org/changeset/50230122) the original MP along the borders of the park to create 4 elements:

* Woodland associated with Odell Park: the original MP [7347445](https://www.openstreetmap.org/relation/7347445)
* Woodland associated with Fredericton Botanical Gardens as an MP relation
* 2 parcels of wood outside the parks, remapped as simple polygons 

The woodland colour then renders correctly over the parkland.

![odell_park_fixed](https://user-images.githubusercontent.com/5452818/28120212-45d4ba58-670f-11e7-88a5-32992f93332a.jpg)

Naively I'd assume that park should (could?) always be rendered beneath wood/forest. The situation where a park borders a much large woodland which dips toes into the park is not that uncommon.

Anyway even if you wish to keep the issue closed: this note shows at least one workaround which may be appropriate in other situations.

**Comment by dieterdreist** [comment] 2017-07-12 15:04
sent from a phone

> On 12. Jul 2017, at 15:55, Christoph Hormann <notifications@github.com> wrote:
> 
> If there is a logical and objectively justifiable order of different landcover features we could use that instead of size but at the moment i don't see this being the case.


"park" isn't a landcover, it's a legal designation and a cultural phenomenon. In osm-carto it is put under landcover, but that's not something logical or meaningful outside the purpose of this style, that's why we'll hardly find an intrinsic, objective and universally valid order for these things.

**Comment by imagico** [comment] 2017-07-12 15:09
To clarify: _landcover features_ was used here to refer to the features rendered in the landcover layer.  No particular meaning of the term was implied.

Separating the current _landcover features_ into different layers would also mean defining a rendering order since one layer is always rendered above the other.

**Comment by SK53** [comment] 2017-07-12 15:13
Actually it's entirely because of social/cultural aspects, at least for urban parks, such as on a day like today: "is there any shade in park X?". There may also be cultural assumptions based on familiarity with classic english parks which rely on scattered trees, groves and patches of woodland to achieve their effect. However, for the same reasons I think it's entirely reasonable to do what I did for Odell Park and separate the woods in the park from adjacent woodland. They are likely to have different access arrangements, different amenity value, and (only now wearing a botanical hat) management and ground cover. So in other words, one can justify editing elements to make them render as desired under this regime on the basis that one is likely to be reflecting reality, and thus there is no need to change the style.

It would be an interesting exercise to identify places, or through thought experiments where the opposite applies.

On your last point, when I looked at Urban Atlas and OSM I managed with an explicit ordering of landuse features (as defined by UA). I dont know if I still have my mapnik stylesheet for the same.

**Comment by imagico** [comment] 2017-07-12 15:31
Well - the question is of course always if it is actually correct to map both a park and a wood forest here separately in light of [One feature, one OSM element](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element).  But this is of course a fairly theoretical question since a park will rarely have completely homogeneous vegetation.  You are probably right that the trees in the park can well be understood to constitute a wood/forest separate from the trees outside so can well be mapped separately.

For info: if the same feature is tagged both `leisure=park` and `landuse=forest` it is (based on my interpretation of the code, i have not checked) rendered as forest.  If it is tagged `leisure=park` and `natural=wood` it should be rendered as park but with wood symbols.  This is kind of strange and not really understandable for the map user - see also #1291.

**Comment by dieterdreist** [comment] 2017-07-12 16:20
2017-07-12 17:09 GMT+02:00 Christoph Hormann <notifications@github.com>:

> To clarify: *landcover features* was used here to refer to the features
> rendered in the landcover layer. No particular meaning of the term was
> implied.
>
>
>

to clarify as well, I had understood this and was confirming your view that
it depends on your interest and intent which kind of feature prefer over
which (physical aspects like kind of plants, or cultural aspects), or in
which way to represent both.
