### ISSUE TITLE
Please render boatyard

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4982] opened 2024-06-23 23:04 UTC
- Boatyard is not rendered.
- It also is a strange tag, being a value for a waterway.

See [issue 4514](https://github.com/gravitystorm/openstreetmap-carto/issues/4514).

**Comment by imagico** [comment] 2024-06-23 23:13
Duplicate of #4514 - we discussed both `amenity=boat_storage` and `waterway=boatyard` there.

**Closed** 2024-06-23 23:13 UTC
