### ISSUE TITLE
Bug: railway=rail + service=* is not rendered since v2.29.0

### ISSUE THREAD

**Issue by Nakaner** [gravitystorm/openstreetmap-carto#1453] opened 2015-03-22 10:05 UTC
Ways tagged with `railway=rail` + `service=*` have not been rendered since update to v2.29.0. This bug does not affect [`railway=light_rail` + `service=yard`](https://www.openstreetmap.org/#map=19/48.99211/8.39530) and [`railway=narrow_gauge` + `service=yard`](https://www.openstreetmap.org/#map=18/49.43972/8.62068).

[Example](https://www.openstreetmap.org/#map=18/48.99364/8.40237): Karlsruhe Hauptbahnhof (Central Station) has a lot of tracks with `service=siding` and `service=yard`. Btw, it is nice that these "minor tracks" are only rendered at higher zoom levels (14+ or 15+) as it has been happening for about one year.

**Comment by jzvc** [comment] 2015-03-22 10:44
http://www.openstreetmap.org/#map=17/50.05190/14.46964

Same issue, there are many tracks with service tag.

**Comment by nebulon42** [comment] 2015-03-22 12:12
#1443 should fix this and there is already a tag for 2.29.1 (https://github.com/gravitystorm/openstreetmap-carto/releases/tag/v2.29.1). I'm not sure if it has been rolled out yet.

**Comment by pnorman** [comment] 2015-03-22 21:22
Duplicate of #1442

**Comment by math1985** [comment] 2015-03-22 21:23
>  I'm not sure if it has been rolled out already.

It hasn't, see [here](http://git.openstreetmap.org/chef.git/). @gravitystorm usually doesn't work over the weekend.

**Closed by pnorman** 2015-03-22 21:22 UTC
