### ISSUE TITLE
render craft=brewery

### ISSUE THREAD

**Issue by g4rpch** [gravitystorm/openstreetmap-carto#1966] opened 2015-11-09 19:23 UTC
Dear all

Please render craft=brewery with a nice icon :)

Thanks a lot
G4rp

**Comment by HolgerJeromin** [comment] 2015-11-09 21:21
If you can buy a beer, it is a pub or bar. 
If it is large, it is landuse industrial. 
I don't think we need an icon for this...

**Comment by g4rpch** [comment] 2015-11-09 21:34
are small craft brewing company, in the last years always more and more are opening, here one example: http://www.openstreetmap.org/node/3693191925

**Comment by polarbearing** [comment] 2015-11-09 22:42
currently 1500 uses

**Comment by math1985** [comment] 2015-11-10 09:09
I think features like these deserve to have their name rendered, but are too rare to deserve their own icon.

**Comment by kocio-pl** [comment] 2015-11-10 10:47
Looks like a subset of https://github.com/gravitystorm/openstreetmap-carto/issues/1697.

**Comment by matkoniecz** [comment] 2016-06-09 18:26
So it is for places 

- where it is impossible to buy anything (otherwise it would have pub or bar icon or at least would be tagged as shop)
- it is impossible to visit them for tour or something similar (it would be tourism=museum/attraction) 
- are not big enough to draw even small landuse 
- are even not filling entire building (building names are rendered)

I am unsure whatever rendering name would be valuable (alcohol-related icon would be clearly misleading as it is not bar/pub/shop so it is unacceptable).

**Comment by SomeoneElseOSM** [comment] 2016-06-09 19:12
Why should it be "impossible to buy anything" or "impossible to visit for a tour" at a craft=brewery?  In OSM I've always tried to use the most appropriate tag, even if some other more popular tag may also apply.  See e.g. http://www.openstreetmap.org/way/359616375 and the adjacent pub.

**Comment by matkoniecz** [comment] 2016-06-09 19:26
In cases where it is possible to buy something or visit proper tagging already results in rendering. Or would it be valuable for such cases to display second label?

**Comment by matkoniecz** [comment] 2016-06-09 19:27
As `craft` key is not currently in the database.

**Comment by SomeoneElseOSM** [comment] 2016-06-09 19:36
... "already results in rendering" indeed, but as something that isn't the best tag for an object.  I'm sure that you can go on occasional brewery tours to Springhead Brewery linked above, but it's primarily a brewery rather than a tourist attraction (I certainly didn't consider it enough of a tourist attraction to tag it as such).

**Comment by dieterdreist** [comment] 2016-06-10 10:29
sent from a phone

> Il giorno 09 giu 2016, alle ore 20:26, Mateusz Konieczny <notifications@github.com> ha scritto:
> 
> So it is for places
> 
> where it is impossible to buy anything (otherwise it would have pub or bar icon or at least would be tagged as shop)


no, it is a different notion, craft is not for places, it is for people/businesses (operating at these places). It can also be added in addition to other tags like pub or factory (works)


> it is impossible to visit them for tour or something similar (it would be tourism=museum/attraction)


not necessarily. Not every place that has guided visits is a museum


> are not big enough to draw even small landuse


landuse is a property of the land, how it is roughly used, not a feature like a brewer making beer



> are even not filling entire building (building names are rendered)


this is not about a building (see also 1st point), but about a business. These should ideally not be mixed on the same object (I know that doing it is widespread nonetheless) as they very likely have different attributes (name, start_date, wikipedia, etc.)


cheers,
Martin

**Comment by dieterdreist** [comment] 2016-06-10 10:30
sent from a phone

> Il giorno 09 giu 2016, alle ore 21:26, Mateusz Konieczny <notifications@github.com> ha scritto:
> 
> would it be valuable for such cases to display second label?
> 

what about "different label" rather than "second"?

**Comment by nebulon42** [comment] 2016-09-03 09:38
I think this issue does not belong to the Mapnik upgrade milestone but rather to the Style upgrade milestone.

**Comment by Tomasz-W** [comment] 2018-02-22 07:16
Please close this ticket and move further discussion to #1697

**Comment by Tomasz-W** [comment] 2018-09-21 06:12
@kocio-pl Please close this issue as duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/1697

**Closed** 2018-09-21 07:38 UTC
Labels: amenity-points, duplicate
