### ISSUE TITLE
Add directional arrows on bike lanes!

### ISSUE THREAD

**Issue by IVAN-RSM** [gravitystorm/openstreetmap-carto#3365] opened 2018-08-29 10:59 UTC
Add directional arrows on highway=cycleway and highway=footway and others...

**Comment by Tomasz-W** [comment] 2018-08-29 11:33
It's duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/2865. 
Please always do a search for similar issues before you add a new one.

**Closed** 2018-08-29 14:00 UTC
Labels: duplicate
