### ISSUE TITLE
Minor roads rendering above trunk & primary links

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#1985] opened 2015-11-27 19:03 UTC
Hi
Lower grade roads (tertiary, residential etc) are rendering above primary & trunk _link roads where they join. Is this their intended appearance?:

![capture](https://cloud.githubusercontent.com/assets/9528328/11447008/81cc9ef0-9537-11e5-932e-6361e2e83cfb.JPG)

It looks a bit weird to me. 

http://www.openstreetmap.org/#map=18/51.52603/-2.57241
https://www.openstreetmap.org/#map=18/35.85888/128.62599

I note #1456 which appears to be claiming the opposite (It's been fixed so links are hard to see the problem). 

Is it possible to distinguish which is the continuous way & render that on top? If both/all ways are end nodes could it be determined by higher grade road?

Cheers
Dave F.

**Comment by pnorman** [comment] 2015-11-27 21:04
> Lower grade roads (tertiary, residential etc) are rendering above primary & trunk _link roads where they join. Is this their intended appearance?:

Yes.

> I note #1456 which appears to be claiming the opposite (It's been fixed so links are hard to see the problem).

It was a bug, which was fixed.

> Is it possible to distinguish which is the continuous way & render that on top?

Not really, or at least it's complicated enough that I can't think of a good way.

**Comment by matkoniecz** [comment] 2015-11-27 21:44
Duplicate of #678, #266 (these tickets contain explanation why current ordering is used).

**Closed by matkoniecz** 2015-11-27 21:44 UTC
