### ISSUE TITLE
Feature request: Extend highest zoom level to 21

### ISSUE THREAD

**Issue by c933103** [gravitystorm/openstreetmap-carto#4145] opened 2020-05-14 10:09 UTC
In low longitude area like Singapore or Hong Kong, the current highest zoom level of 19 is only sufficient to distinguish buildings, but not details within buildings or other similarly small objects, for example the location of individual shops, apartment units, door in building, or location of bus stop pole, telephone booth, trees, post box on street, as well as numerous other details. Please enable the rendering for level 20 and 21 so that these details can be shown in the map. (At zoomlevel 20 it would be somewhat possoble to distonguish their rough location in buildings while at zoomlevel 21 it would be easier to tell and would also be somewhat possible to map small shops and such in a building using area.)

**Comment by imagico** [comment] 2020-05-14 10:51
See #3686.

In short - adding additional zoom levels to the OSMF tile servers is off topic here - see https://github.com/gravitystorm/openstreetmap-carto/issues/3686#issuecomment-466755349 and what you can do from the side of this style is actually working on cartography at z20+ - see https://github.com/gravitystorm/openstreetmap-carto/issues/3686#issuecomment-466952855 (or more accurately - even z19 cartography is so far almost exclusively a simple extrapolation of z18 so it would be advisable to start there).

**Comment by mboeringa** [comment] 2020-05-14 13:38
@c933103 , for the specific purpose you mention related to buildings, there is indoor mapping:

https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging

Since indoor mapping often also requires displaying multiple building levels, rendering up to Z21 would essentially not solve anything, and would likely result in incomprehensible mess of stacked building levels. What is needed is the kind of dynamic display of individual building levels as e.g. offered by OpenLevelUp, that allows you to select a specific OpenStreetMap "level=x" tag, and only display those features:

https://openlevelup.net

I really recommend you to use this kind of specialized indoor mapping viewer for this kind of work.

**Comment by c933103** [comment] 2020-05-14 13:47
> @c933103 , for the specific purpose you mention related to buildings, there is indoor mapping:
> 
> https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging
> 
> Since indoor mapping often also requires displaying multiple building levels, rendering up to Z21 would essentially not solve anything, and would likely result in incomprehensible mess of stacked building levels. What is needed is the kind of dynamic display of individual building levels as e.g. offered by OpenLevelUp, that allows you to select a specific OpenStreetMap "level=x" tag, and only display those features:
> 
> https://openlevelup.net
> 
> I really recommend you to use this kind of specialized indoor mapping viewer for this kind of work.

I am specifically talking about any shops/unit/etc that locate on the ground floor of a building, including 1-story-high building, and especially when they face streetward with opening to street. Surely they are also covered by indoor mapping, but even without indoor mapping, they are still features that would frequently be mapped and is also useful to anyone who aren't indoor.

**Comment by pnorman** [comment] 2021-04-16 01:40
Duplicate of #3686, since to render z21 we'd need to first render z20.

For the style, as stated above, z19 cartography is so far almost exclusively a simple extrapolation of z18 so it would be advisable to start there

**Closed by pnorman** 2021-04-16 01:40 UTC
Labels: cartography
