### ISSUE TITLE
Rendering issue with tram lines on road on bridge

### ISSUE THREAD

**Issue by joto** [gravitystorm/openstreetmap-carto#1993] opened 2015-12-05 19:19 UTC
Tram lines on a road going over a bridge seem discontinuous. Tagged in three parallel lines, all tagged `bridge=yes` and `layer=1`, inner as `highway`, two outers as `railway=tram`. If you look closely you can see the round line cap of the road bridge hiding the tram lines of the non-bridge ways. Looks like a layer ordering issue to me.

![bridge-road-tram](https://cloud.githubusercontent.com/assets/113756/11609651/91870d70-9b8c-11e5-890f-edc8de98e01a.png)

This is the area of the example: https://www.openstreetmap.org/#map=19/51.04068/13.80249

**Comment by mboeringa** [comment] 2015-12-05 19:46
This is a duplicate of #934, and as discussed in depth there, there is unfortunately no good technical solution for this.

**Closed** 2015-12-05 20:42 UTC
Labels: duplicate
