### ISSUE TITLE
red lines

### ISSUE THREAD

**Issue by xalulax** [gravitystorm/openstreetmap-carto#2122] opened 2016-05-07 18:11 UTC
Hi,
I download openstreetmap-carto and everything works good, but in some zooms I see red lines. 

For example when _[zoom < 14]_ layers in zooms < 14 are ok, but in zooms >14 have this red lines. 
Next example: layer should disappear in zooms >14 and it works, but red lines are still around this layer.

How can i fix it?

![bez nazwy-1](https://cloud.githubusercontent.com/assets/19242066/15093621/6c7fd9a6-148d-11e6-8b6b-6691224f615a.png)

**Comment by pnorman** [comment] 2016-05-08 04:48
What version of tilemill?

I see a number of other oddities such as missing background fills.

**Comment by xalulax** [comment] 2016-05-08 08:45
TileMill-v0.10.1 Windows 7

True, background color is missing

**Comment by nebulon42** [comment] 2016-05-08 08:51
I can rule out that this has to do with recent carto colour regressions as TileMill has not yet officially upgraded to carto 0.16, so unless you would be using master from the repository it is still on 0.9.3.

**Comment by pnorman** [comment] 2016-05-09 02:46
The colours are off. The buildings on the lower-right are `#bbb9b6` instead of `@building-fill`, which is `#d9d0c9`.

Because there's only one layer that should be involved, this should be easier to debug.

Can you disable all layers but `#buildings` and see what the colour of the lower-right buildings is? If that changes it, check layer by layer to see what changes it.

If that doesn't change it, with all the layers disabled, try turning off all the MSS files except style.mss and buildings.mss

**Comment by xalulax** [comment] 2016-05-09 07:46
The buildings color I changed, when I tried find a problem. 
I turning off all the MSS files and I turn on the MSS by MSS and layer by layer. I found wrong style/layers so thanks for good idea.

Still I have a problem with fills landscape.  _polygon-fill_ work only for _polygon-pattern-file_, but background is empty.

**Comment by pnorman** [comment] 2016-05-09 08:18
Wait, are you getting the lines with a modified osm-carto or an unmodified one?

**Comment by xalulax** [comment] 2016-05-09 10:09
I getting the lines with a unmodified osm-carto. I modified osm-carto later, when I try find a problem

**Comment by matkoniecz** [comment] 2016-05-10 18:00
Note also that this is based on old version of openstreetmap-carto, certainly before road recolour.

For comparison http://www.openstreetmap.org/#map=17/50.01741/19.89226 with current style is rendered as

![selection_001](https://cloud.githubusercontent.com/assets/899988/15156932/999e8be0-16e9-11e6-9d77-40603272e5fd.png)

How you obtained osm-carto style files? Can you obtain fresh osm-carto style?

**Comment by math1985** [comment] 2016-05-10 18:20
Closing the issue as it is not a problem with openstreetmap-carto, but feel free to keep asking more questions if you need further assistance.

**Closed** 2016-05-10 18:20 UTC
