### ISSUE TITLE
Walls too visible?

### ISSUE THREAD

**Issue by Rovastar** [gravitystorm/openstreetmap-carto#1214] opened 2015-01-09 14:41 UTC
Now the buildings have been washed out walls to me are too prominent.

Here is an example:
http://www.openstreetmap.org/way/132701201#map=17/52.91187/-1.48218

I imagine they should be the same colour as the buildings.
Maybe look too at other barriers= like fence and stuff too.

**Comment by mkoniecz** [comment] 2015-01-09 18:59
duplicate of #582

**Closed by mkoniecz** 2015-01-09 18:59 UTC
