### ISSUE TITLE
Objects at tile boundaries can be quantized to two different colours

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#1940] opened 2015-11-01 00:25 UTC
The parking (yellow area) east of the American embassy construction zone ([link](http://www.openstreetmap.org/#map=15/52.0994/4.3504)) is rendered in two slightly different tones of yellow. 

The parts of different colour are separate tiles, but the same meta-tile. Does anybody know what could be the cause of this?

![screenshot from 2015-11-01 01 18 45](https://cloud.githubusercontent.com/assets/5251909/10866613/24c4c274-8037-11e5-9fe8-44c754e8af9d.png)

**Comment by pnorman** [comment] 2015-11-01 01:30
> The parts of different colour are separate tiles, but the same meta-tile. Does anybody know what could be the cause of this?

Did we change the colour? If so, it could be caching. renderd operates on metatiles, but your browser cache and the CDN don't

**Comment by math1985** [comment] 2015-11-01 09:09
I don't think we changed the colour.

Can others reproduce the issue?

**Comment by pnorman** [comment] 2015-11-01 09:13
I can see it there, but I haven't tried to reproduce yet

**Comment by Rovastar** [comment] 2015-11-01 12:46
Access=yes and access=private  (and customers I think) render differently.
This is by design and has always done this.

**Comment by HolgerJeromin** [comment] 2015-11-01 12:48
The area http://www.openstreetmap.org/way/47026919 was changed 6 years ago...

**Comment by polarbearing** [comment] 2015-11-01 17:18
In landcover.mss, parking: #f7efb7; is defined. 
When I measure the tile png, the upper part, as well as the bigger car park north of it, is #f6eeb6.
The lower corner is #f6f8bd.
Is the defined fill colour tuned in a later step?

**Comment by HolgerJeromin** [comment] 2015-11-01 18:12
Perhaps the png  tile files are optimized for size in the pipeline

**Comment by gravitystorm** [comment] 2015-11-02 12:45
In mod_tile, the metatiles are rendered as large 32-bit mapnik image buffers, but are then split into individual parts (using image_views looped over the large buffer). These individual parts are saved as png files, and the colour palette is calculated per-tile, not per-metatile.

https://github.com/openstreetmap/mod_tile/blob/6b9611aaf763f4f776d1fd363433aac7e25cb34b/src/gen_tile.cpp#L269-L279

This is a plausible explanation of the different polygon colours within the same metatile.

**Comment by gravitystorm** [comment] 2015-11-02 12:55
I should add that many, many years ago I worked with a non-mod_tile setup that generated the palette per-metatile and it looked awful, since there were far too many colours in each 8x8 zone and lots of different things were all collapsed into the same meta-tile-spanning colour. So I can understand why the palettes are best done per-tile rather than per-metatile.

Of course, there might be room for improvement in the palette creation process - I don't think anyone has examined whether mod_tile might work better with [different palette creation options](https://github.com/mapnik/mapnik/wiki/OutputFormats), and it's [almost 8 years since the png256 option was first used](https://github.com/openstreetmap/mod_tile/commit/bfeb1026625a7f8c9ebd035ff43e9873b82823db) in mod_tile. But unless something else arises to explain the problem, it might be best investigated elsewhere.

**Comment by math1985** [comment] 2015-11-02 13:17
This is a very noticeable place where the colour is different from the defined colour (in at least one of the two tiles).

Does this mean that there will also be other places where the colour that is rendered is different from the colour that is defined in the stylesheets?

**Comment by pnorman** [comment] 2016-12-15 03:25
After thinking about this, I believe we should close this for a few reasons

- We specify png, not png256. Generating 8x8 metatile png256 images and cutting them to tiles is a deployment consideration, not a style consideration, and changing the format settings here will do nothing.
- The only influence we can have over this bug is to change the number of colours in the style, and even that might not work. While there are arguments for and against the number of colours we have here, I don't think we should change that because of this bug.

Although out of scope of osm-carto, I agree with the choice of png256 made for mod_tile and tile.osm.org

- The scope of this is inherently limited, as larger areas will not end up palletted like this
- png256 offers huge performance gains

**Comment by kocio-pl** [comment] 2016-12-18 05:50
The same as in https://github.com/gravitystorm/openstreetmap-carto/issues/2425#issuecomment-267804711 - setting png256 both in `project.mml`and in export options does not show the problem described in this ticket:

![fkrtapgy](https://cloud.githubusercontent.com/assets/5439713/21291816/0b33077e-c4ee-11e6-83ab-6070ea11e800.png)

**Comment by pnorman** [comment] 2016-12-18 07:09
Is it actually a png256 that gets generated, or does Kosmtik override it? You can look at a tile with `pnginfo` and see what it is.

**Comment by kocio-pl** [comment] 2016-12-18 07:17
The image is here, so anybody can check it, but it looks like a proper PNG256:
```
FKrtapGY.png...
  Image Width: 210 Image Length: 181
  Bitdepth (Bits/Sample): 8
  Channels (Samples/Pixel): 1
  Pixel depth (Pixel Depth): 8
  Colour Type (Photometric Interpretation): PALETTED COLOUR (256 colours, 0 transparent)
  Image filter: Single row per byte filter 
  Interlacing: No interlacing 
  Compression Scheme: Deflate method 8, 32k window
  Resolution: -1285909878, 22098 (Unknown value for unit stored)
  FillOrder: msb-to-lsb
  Byte Order: Network (Big Endian)
  Number of text strings: 0
```

**Closed** 2016-12-18 08:39 UTC
Labels: bug, landcover

**Comment by pnorman** [comment] 2016-12-18 08:55
> The image is here,

Just to note, the image isn't there, the image in the post above is one image covering both sides of the metatile boundary.
