### ISSUE TITLE
Add rendering for amenity=parking_space

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#776] opened 2014-07-28 16:24 UTC
The following issue has been moved over from [trac](https://trac.openstreetmap.org/ticket/3742):

now that the proposal for parking_spaces has been approved with 94%, mapnik should add a style for areas tagged with amenity=parking_space. i suggest to render it as the same yellow area as amenity=parking, but without the blue P, since such areas are relatively small and often occur in groups. the blue P could later be rendered through evaluation of the type=site + site=parking relation, which is also part of the proposal (but that would be a separate ticket).

i know, that this tag is brand new and you normally don't add features, that aren't heavily used, but this tag has potential to supersede the amenity=parking tag. but i fear, as long as it doesn't get rendered, people won't start mapping it.

for more information, you can find the proposal under  http://wiki.openstreetmap.org/wiki/Proposed_features/parking

**Comment by mkoniecz** [comment] 2015-01-06 14:56
As this map style supports zoom levels up to 22, I think that thsi feature request should be rejected.

**Comment by yopaseopor** [comment] 2015-01-09 15:51
Two things, there's no layer about parking features (very important information when you go to a strange city), and also there's no sign for special spaces.Also if information is given why not P symbol give us the amount of parking spaces you will find in that parking ?

**Comment by mkoniecz** [comment] 2015-01-09 18:57
> There's no layer about parking features

It is not valid reason to show too many details in general map style. The question is not whatever it displayed somewhere, but whatever it should be displayed in general purpose map style.

> why not P symbol give us the amount of parking spaces you will find in that parking

(1) see above
(2) currently capacity is not present in database - see https://github.com/gravitystorm/openstreetmap-carto/blob/master/openstreetmap-carto.style for list of available tags

**Comment by pnorman** [comment] 2015-01-09 21:41
Duplicate of #428 - although with more information here. See also #81

Based on the comments in this as well as previous issues, I'm going to close this.

**Closed by pnorman** 2015-01-09 21:41 UTC
Labels: landcover
