### ISSUE TITLE
Missing visual representation for emergency=life_ring

### ISSUE THREAD

**Issue by nitricware** [gravitystorm/openstreetmap-carto#4993] opened 2024-07-12 07:03 UTC
### Expected behavior

Nodes that are tagged as emergency=life_ring have a visual representation/rendering on the map. Just like emergency=phone is rendered.

### Actual behavior

Nodes that are tagged as emergency=life_ring do not have a visual representation/rendering on the map.

### Screenshots with links illustrating the problem

Node: https://www.openstreetmap.org/node/12029562815

![life_ring-missing](https://github.com/user-attachments/assets/0068f0e3-5171-482e-b82c-939cc9e402ca)

*Possible duplicate of #3629*

**Comment by danieldegroot2** [comment] 2024-07-12 10:20
Part of #3629 as mentioned. See https://github.com/gravitystorm/openstreetmap-carto/pull/3688#issuecomment-753246639

See also other issues and existing maps for emergency rendering.

**Comment by imagico** [comment] 2024-07-13 11:36
Closing as duplicate of #3629.  Also see previous attempt at adding rendering of this in #3688 regarding what things need to be considered for a suitable rendering.

**Closed** 2024-07-13 11:36 UTC
