### ISSUE TITLE
Add rendering for natural=cape (headlands)

### ISSUE THREAD

**Issue by lakedistrictOSM** [gravitystorm/openstreetmap-carto#3148] opened 2018-03-27 13:42 UTC
https://wiki.openstreetmap.org/wiki/Tag:natural=cape

We render `natural=bay`, so it make sense to render `natural=cape` too.

**Comment by kocio-pl** [comment] 2018-03-27 14:16
Would you like to provide the code to resolve this issue?

**Comment by lakedistrictOSM** [comment] 2018-03-27 15:41
Someone more experienced can provide the code.

Things to consider:
- Font size to match `natural=bay`?
- Not a water feature so use black, not blue
- Zoom level to match `natural=bay`?
- Or just render it like `place=locality`?

Also mentioned in #788 and #2796

**Comment by kocio-pl** [comment] 2018-03-27 15:45
I think the text should be also slanted, like for islands and other areas.

So we look for a coder mainly - we need more of them. Even if they will make simple tasks now, it's the only way to have more people able to learn more complicated things.

**Comment by kocio-pl** [comment] 2018-06-28 15:06
Great,

You may start with reading general introduction and installation instructions:

https://wiki.openstreetmap.org/wiki/Standard_tile_layer
https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

**Comment by Tomasz-W** [comment] 2018-07-15 10:40
@kocio-pl Please close this ticket as a duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/788 meta ticket. Move further discussion there.

**Comment by lakedistrictOSM** [comment] 2018-10-05 17:14
@kocio-pl Please reopen this issue as suggested in https://github.com/gravitystorm/openstreetmap-carto/issues/3298#issuecomment-427218691 so that it's not buried away in #788 (which isn't a duplicate but more of a task list) and can be coded and tested more easily.

**Comment by Adamant36** [comment] 2018-10-16 07:42
@lakedistrictOSM, thank's for getting it reopened. I did a PR for it.

**Closed** 2018-11-25 22:31 UTC
Labels: text
