### ISSUE TITLE
Differentiate shields to avoid collisions

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4691] opened 2022-09-18 01:14 UTC
At one magnification the 8 is on the top road, at the other magnification the 8 jumps down to the bottom road.

At least differentiating their shields, like the highway departments do, would alleviate 95% of the mystery.

![Screenshot_20220917-210328_Maps.jpg](https://user-images.githubusercontent.com/1230959/190881294-1755d078-ca06-41c2-b1cd-c449bd5de2d0.jpg)

![Screenshot_20220917-203411_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/190881304-5666b562-3fad-4664-a108-98a95bdf81aa.jpg)![Screenshot_20220917-203340_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/190881305-6ac7530b-9fa8-4d2e-8313-3317fea7c5ce.jpg)
Let's see how some other maps take care of this problem:
![Screenshot_20220917-202527_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/190881321-936e4cb3-3f27-43a8-951d-a7732bc2fb49.jpg)
![Screenshot_20220917-202205_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/190881329-0378dbf7-55c1-406b-9866-7d27d303611e.jpg)
[Location](https://www.openstreetmap.org/?#map=16/43.42395197176742/-80.42306812029425).

**Comment by jidanni** [comment] 2022-09-18 01:27
Here NRCAN's map sufferers the same problem.:
![Screenshot_20220917-202400_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/190881652-fd77987a-8f79-4738-9243-c9789345ad36.jpg) One can see what hazards might ensure using such map in the field.

**Comment by jidanni** [comment] 2022-09-18 01:31
Here NRCAN's map sufferers the same problem.:
![Screenshot_20220917-202400_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/190881652-fd77987a-8f79-4738-9243-c9789345ad36.jpg) One can see what hazards might ensure using such map in the field.

**Comment by jidanni** [comment] 2022-09-18 01:32
![Screenshot_20220917-202128_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/190881804-bcadba87-71b5-40f1-858b-a59a54029822.jpg) OSM France style is another example to avoid.

**Comment by kennykb** [comment] 2022-09-18 03:15
This duplicates about a zillion other requests, and OSM's data model makes it, uhm, rather difficult.

Some renderers can more or less manage it: https://kbk.is-a-geek.net/catskills/test4.html?la=43.4432&lo=-80.4704&z=13

**Comment by sommerluk** [comment] 2022-09-18 08:20
@jidanni Thanks for the bug report. But please use the search function to see if there is already a bug report for your issue before submitting a new bug report.

Closing as duplicate of #508

**Closed by sommerluk** 2022-09-18 08:20 UTC
