### ISSUE TITLE
Render platforms ontop of pedestrian areas

### ISSUE THREAD

**Issue by swedneck** [gravitystorm/openstreetmap-carto#4527] opened 2022-03-27 07:04 UTC
### Expected behavior
Platforms should be fully visible when part of a pedestrian area
### Actual behavior
Platforms are obscured by pedestrian areas

**Comment by imagico** [comment] 2022-03-27 11:55
We render platforms as part of the road layers, as a result platforms mapped with linear ways are rendered above pedestrian areas but below pedestrian linear roads due to z-order:

https://www.openstreetmap.org/#map=19/58.39078/13.85272

We have had many discussions if and how to change that (see for example: #527, #3281, #3872, #4221) - but with no definitive conclusion so far.

The semantics of mapping at the location you showed are of course fairly questionable - this is not the kind of mapping we would want to model our rendering after.  That however does not mean that the problem of inconsistent drawing order between polygons and linear ways visible here is not an issue that would be good to address.

Side note: Trying to keep secret the location of your example is both pointless and counterproductive of course:

https://www.openstreetmap.org/#map=19/58.39078/13.85272

I suggest we close this because it is only a specific concrete manifestation of a problem we have existing issues open about.

**Comment by swedneck** [comment] 2022-03-29 12:12
well thanks for doxxing me, that's very appreciated.

**Comment by matkoniecz** [comment] 2022-05-18 18:32
@imagico can you edit out that location comment? Yes, it is trivially recoverable, but pointing this out can be done without making even more accessible what someone has tried to not reveal (even if they failed).

Though doxxing is usually reserved for stronger actions especially as in this case it was really trivial to recover.

**Comment by imagico** [comment] 2022-05-18 19:41
> @imagico can you edit out that location comment?

Sure.

Assessing an issue like this without determining the location is not possible of course.  So as a general advice to anyone who wants to report an issue that they can only find at a specific location in the map and who at the same time does not want this location to be known to anyone else:  The best way to do so - if you cannot find the same problem at any other location - is to try reproducing it in a test database and then posting the test data.  If you post a screenshot from the actual map without a link to the location there are only two possibilities:

* the developers here determine the location (which takes time not available for development work).
* the problem can't be addressed because no one other than the person reporting the issue can analyze what causes it.

**Comment by matkoniecz** [comment] 2022-05-18 20:01
Also, note that in general if map view includes even a single name / ref code then it is almost always easy to find where it was located.

Even "bicycle parking near greengrocer and butcher" would allow locating given place.

If worried about privacy: find equivalent example in some remote location.

**Comment by mmd-osm** [comment] 2022-05-18 20:35
It's not exactly trivial to find an equivalent example, so here's a first try:

https://www.openstreetmap.org/#map=19/48.40266/10.00024  --> https://www.openstreetmap.org/way/248783286

I used the following Overpass query for this stuff. I hope that's similar enough to the location described by the OP.

```
[bbox:{{bbox}}];

way[highway=pedestrian][area=yes];

way(area)[highway=platform][ref](if:!is_closed())->.a;
foreach .a -> .b {

way(around.b:3)[highway=pedestrian](if:!is_closed());
if (count(ways) > 0) {
  out geom;
  .b out geom;
};
}

```

**Comment by mmd-osm** [comment] 2022-05-31 18:00
As a reminder to everyone here, if you want to make sure that previous versions of your comments really are no longer accessible, you need to follow this description: https://docs.github.com/en/communities/moderating-comments-and-conversations/tracking-changes-in-a-comment

**Comment by jeisenbe** [comment] 2022-06-03 18:13
> As a reminder to everyone here, if you want to make sure that previous versions of your comments are really no longer accessible, you need to follow this description: https://docs.github.com/en/communities/moderating-comments-and-conversations/tracking-changes-in-a-comment

Unfortunately, even in that case your originaly comments will still be visible to users who follow the respository with email notifications. For example, I still have the original 3 comments to this issue in my email inbox, including the image and the link which have been subsequently removed. It is important to only share information on Github which you are willing to have publically available to anyone on the internet.

Also, note that editing a comment does not notify people who follow by email. For example, the statement above:  _"You are aware this violates your own CoC, right?”_  was not visible to me or other maintainers who follow issues vis email, since that phrase was not originally included in the comment and was only added later.

**Comment by jeisenbe** [comment] 2022-06-03 18:16
This issue is similar to #4221 and more broadly #3281, and cannot be easily solved without causing other problems, due to complexities in how road/pedestrian areas are rendered in relation to linear roads and platforms. I believe we should close this issue as a duplicate of those 2 earlier issues.

**Closed** 2022-06-04 01:13 UTC
