### ISSUE TITLE
At zoom <=13, leisure=sports_centre, building=* shows up green

### ISSUE THREAD

**Issue by pkoby** [gravitystorm/openstreetmap-carto#3525] opened 2018-11-23 21:48 UTC
### Expected behavior
Buildings tagged with leisure=sports_centre (such as stadiums, gyms e.g. YMCA) should look like buildings, and in fact do at zooms 14–19 (stadium in center of image):
![image](https://user-images.githubusercontent.com/7786285/48960887-62d5f500-ef3e-11e8-821c-8cdb1603bd76.png)

### Actual behavior
At z13 and I think 12, 11, and maybe 10 (hard to find a large enough building to see at that zoom), the buildings turn green. At z13, the green has a darker green outline:
![image](https://user-images.githubusercontent.com/7786285/48960928-c8c27c80-ef3e-11e8-9585-0c45d28f76c4.png)
The fill green is lighter than that for parks (#dffce2 vs #c8facc at that zoom), and I can't find anything that does have that same color.

If these are meant to show at lower zoom levels, shouldn't they be shown as buildings? But most other buildings aren't shown, so I think they shouldn't be visible.

Examples:
Stadium in Huntington, WV: https://www.openstreetmap.org/#map=18/38.42486/-82.42079
YMCA: https://www.openstreetmap.org/#map=18/38.41186/-82.44063
Ohio Stadium, Columbus, OH: https://www.openstreetmap.org/#map=17/40.00164/-83.02162

**Comment by mboeringa** [comment] 2018-11-23 22:13
You are mistaking the light green color of **leisure=stadium** that is additionally tagged with these features, for being the buildings. These objects sit below the buildings, and become visible once you zoom out to a zoomlevel where buildings are no longer shown.

This is not an error, e.g. see this tagged feature for **leisure=stadium**

https://www.openstreetmap.org/relation/7811639 

for the "Joan C. Edwards Stadium". As you can see, it is a separate feature from the actual building, and encompasses the actual pitch as well.

**Comment by pkoby** [comment] 2018-11-23 22:18
No, that's not the only reason. That may be the case for the stadiums (though I don't feel like it should be showing like that, either), but what about the YMCA (https://www.openstreetmap.org/way/587260120)? The only tags are building=yes, leisure=sports_centre, and name=YMCA. It's in a landuse=commercial, near an amenity=parking, and that's it.

So I assume it's some bug/oversight that includes these in leisure=* at z13 and lower.

**Comment by mboeringa** [comment] 2018-11-23 22:59
All of the examples you show actually support my theory: 

- The YMCA building you pointed out, which actually is to small to be easily recognizable at Z13, does not seem to have a "green representation" at Z12, which is logical, because it does not have either **leisure=stadium** or **leisure=sports_centre** tag, both of which get the light green color.

- The other "building" (which is grossly mis-tagged as in reality this is an outdoor shooting range based on aerial in iD) again shows the same effect: the leisure=sports_centre tag is tagged on the same object as the building tag, and hence shows up once the building stops being rendered.

> So I assume it's some bug/oversight that includes these in leisure=* at z13 and lower.

So, again, this is not a bug, but a decision to show **leisure=stadium** and **leisure=sports_centre** in a wider scale range, which is logical, because in general these should be tagged on the outline of the entire facility, so including things like parking space, roads and other stuff considered part of the sports center and usually encompassed by a fence or hedge.

**Comment by pkoby** [comment] 2018-11-23 23:06
I guess it's understandable to have the leisure=* features at a lower zoom level, and I'll admit that I didn't consider the tag being used across the whole area vs. the building.

And yeah, that "building" was obviously badly tagged, but showed a larger version of what I was trying to convey. I guess my somewhat erroneous tagging of just the buildings as the sports_centre is why I was misled.

**Comment by Adamant36** [comment] 2018-11-24 07:09
Not that its uber relevant, but YMCA's probably shouldn't be tagged as leisure=stadium or leisure=sports_centre anyway. Since they are more of a social facility for children that also has exercise equipment. That's not its main purpose though. So if anything, its more akin to a gym or just a social facility.

**Comment by Adamant36** [comment] 2018-11-26 09:37
Good call. I hadn't thought of that. I've been adding tags to social facilities to. It might be off topic, but its always nice to learn something new anyway ;)

**Comment by pkoby** [comment] 2018-11-26 13:09
This YMCA is strictly a fitness center (their website: http://www.huntingtonymca.org/), so I guess it's a mistagging (bad preset? I don't remember) and should be leisure=fitness_centre. 

I do not agree that it should have a religion=* tag, though, because while there may be pictures of Jesus on the wall, and "Christian" is part of the acronym, this facility is not a religious place. That might be case-by-case with YMCAs, but I feel like they have mostly moved away from the Christian part, just like they let women and seniors in the Young Men's Association.

**Comment by dieterdreist** [comment] 2018-11-27 08:52
sent from a phone

> On 26. Nov 2018, at 14:09, pkoby <notifications@github.com> wrote:
> 
> I do not agree that it should have a religion=* tag, though, because while there may be pictures of Jesus on the wall, and "Christian" is part of the acronym, this facility is not a religious place.


would you think you can find pictures of Jesus on the wall and Christian as part of the name also at e.g. Muslim Associations or say anarchist political clubs? It may not be a place of worship or considered a sacred place, but it is hard to defend that YMCA is not christian.

**Comment by Adamant36** [comment] 2018-11-27 09:42
Being pictures of Jesus on the wall or not, it still might be worth tagging as a Christian organization out of respect for people from other religions that might not want to receive help from Christians because it would cause friction or for whatever other reason. The same could be said for religious organizations of any religion that isn't necessarily a place of worship. From what I remember there's some Christian group homes and rehab places tagged as such. I think the tag is appropriate in those places for the same reason. Even if they places of worship either.

**Comment by pkoby** [comment] 2018-11-27 13:18
Regarding a social facility like a clearly denominational halfway house, rehab home, or group home, a kindergarten, or a shop selling religious items, a religion=* tag makes sense to me. These are places that make religion a clear focus of their purpose. Personally, I as a non-religious person might avoid a clearly Christian kindergarten for my kids, because I would expect that religious teaching would be a part of it. Social facilities might be less overt about these kinds of things, but I would still expect prayer before meals, etc.

This YMCA (speaking nothing of any others) is a gym. It has a picture of Jesus on the wall. And that's all the Christian influence you'll get. I think it's a slippery slope to tag things as a religion because they might offend, too. The shop I work at is run by a religious man, and I wouldn't put it past him to put up a picture of Jesus. I've been to an auto repair shop with Bible quotes. Should these be tagged with a religion=* tag?

> It may not be a place of worship or considered a sacred place, but it is hard to defend that YMCA is not christian.
Certainly not, but I'd say there's a grade of religiosity in many venues in the USA, and I don't think most of them deserve a religion=* tag.

An Overpass search shows 732 features with name=YMCA, but only 3 of those with religion=christian. I think I'll leave it without.

**Comment by matkoniecz** [comment] 2018-12-07 22:40
Can anyone show example where at zoom <=13, leisure=sports_centre, building=* shows green, it is causing problems and it is not caused by leisure=stadium tagging?

**Comment by matkoniecz** [comment] 2018-12-09 13:49
Please comment here with examples for

> Can anyone show example where at zoom <=13, leisure=sports_centre, building=* shows green, it is causing problems and it is not caused by leisure=stadium tagging?

and I will reopen. I am closing as, there is no evidence that it is a problem anywhere.

**Closed by matkoniecz** 2018-12-09 13:49 UTC
Labels: buildings
