### ISSUE TITLE
Open Street Map (OSM Carto) Icon issue

### ISSUE THREAD

**Issue by hjuk88** [gravitystorm/openstreetmap-carto#4817] opened 2023-05-20 00:14 UTC
### Screenshots with links illustrating the problem - shot 1 shows ordinray view with icon over the co-op. Shot 2 shows edit mode. I was told the following on OSM forum:

That looks like a bug in one of the six maps available at [openstreetmap.org](http://openstreetmap.org/), the “OSM Carto” one. Of the others, [Cyclosm](https://www.openstreetmap.org/#map=17/51.58233/-0.12058&layers=Y) and the [humanitarian map](https://www.openstreetmap.org/#map=18/51.58233/-0.12058&layers=H) get it right, [Cycle Map](https://www.openstreetmap.org/#map=17/51.58233/-0.12058&layers=C) and [Transport Map](https://www.openstreetmap.org/#map=17/51.58233/-0.12058&layers=T) don’t show it, [Oepnvkarte](https://www.openstreetmap.org/#map=18/51.58233/-0.12058&layers=O) seems mostly broken.

To raise an issue with the OSM Carto developers, you could explain the problem here
![shot 1](https://github.com/gravitystorm/openstreetmap-carto/assets/134112425/63195043-6f60-4fd4-88b4-3f30834a6b1b)
![shot 2](https://github.com/gravitystorm/openstreetmap-carto/assets/134112425/9d085951-309e-4d70-b800-abd5557c7d01)

**Comment by pnorman** [comment] 2023-05-20 03:17
Please provide a link to the object in question so we can reproduce the issue.

**Comment by imagico** [comment] 2023-05-20 07:27
The links to the non-OSM-Carto maps provide the rough location, the feature in question is https://www.openstreetmap.org/way/1068164496.

This seems a duplicate of #3857 - hence i am closing this, though in this specific case this is likely also inaccurate mapping because the supermarket is probably not part of the fuel station.

**Closed by imagico** 2023-05-20 07:27 UTC
