### ISSUE TITLE
Trees prohibit labeling of road names

### ISSUE THREAD

**Issue by plepe** [gravitystorm/openstreetmap-carto#1495] opened 2015-04-22 09:58 UTC
Alleys with lots of trees prohibit labeling of road names. In Vienna, where tree were imported from OpenData, roads are not labeled on certain zoom levels, as trees are close to the road.

See: http://www.openstreetmap.org/#map=16/48.1515/16.3164

Both the red north-south and the orange west-east road miss a road name label on them.

**Comment by matkoniecz** [comment] 2015-04-22 12:49
duplicate of #1425 (fixed in development, waits for release)

**Closed by matkoniecz** 2015-04-22 12:49 UTC
Labels: duplicate
