### ISSUE TITLE
Render bus guideways underneath highway bridges

### ISSUE THREAD

**Issue by BjornRasmussen** [gravitystorm/openstreetmap-carto#3359] opened 2018-08-23 01:33 UTC
Bus guideways currently render above highway bridges creating confusing and incorrect rendering.
![map 11](https://user-images.githubusercontent.com/37753777/44499670-f273bb00-a652-11e8-9818-709554e999f9.png)
https://www.openstreetmap.org/way/381661497

**Comment by kocio-pl** [comment] 2018-08-29 14:28
We need coders willing to look at this. Would you like to try?

**Comment by HolgerJeromin** [comment] 2018-08-30 03:57
Dupe of #2489

**Comment by jeisenbe** [comment] 2019-09-05 11:29
Closed as duplicate of #2489, please discuss further there.

**Closed by jeisenbe** 2019-09-05 11:29 UTC
Labels: roads
