### ISSUE TITLE
Big lakes not in Z5

### ISSUE THREAD

**Issue by manfredbrandl** [gravitystorm/openstreetmap-carto#2877] opened 2017-10-03 11:37 UTC
Z6:
![image](https://user-images.githubusercontent.com/5360273/31123306-a54d1d92-a83f-11e7-95fb-be7c598ef10a.png)
Z5:
![image](https://user-images.githubusercontent.com/5360273/31123338-ca1e4542-a83f-11e7-990c-aeea96f542af.png)
Is this desired?

**Comment by math1985** [comment] 2017-10-03 11:41
Duplicate of #1604. We are currently working on it!

**Closed by math1985** 2017-10-03 11:41 UTC
