### ISSUE TITLE
[bug] steps should be rendered above platform

### ISSUE THREAD

**Issue by endim8** [gravitystorm/openstreetmap-carto#4715] opened 2022-10-14 10:26 UTC
<img width="165" alt="Screenshot 2022-10-13 at 22 22 23" src="https://user-images.githubusercontent.com/26939824/195713477-de90f9cb-8fc6-4b93-b0ee-996135920969.png"> 
<img width="165" alt="Screenshot 2022-10-13 at 22 24 21" src="https://user-images.githubusercontent.com/26939824/195713630-fa14e529-edf1-470c-8d99-a9605a8e4ac0.png">

https://www.openstreetmap.org/#map=19/51.48268/0.00332

**Comment by imagico** [comment] 2022-10-14 12:46
Features in question are:

https://www.openstreetmap.org/way/27368378
https://www.openstreetmap.org/way/27368377

Duplicate of #529.

**Closed by imagico** 2022-10-14 12:46 UTC
