### ISSUE TITLE
Broken landuse label

### ISSUE THREAD

**Issue by scaidermern** [gravitystorm/openstreetmap-carto#1332] opened 2015-02-23 16:30 UTC
We got a broken landuse label here: http://www.openstreetmap.org/?mlat=51.03154&mlon=13.75489#map=17/51.03154/13.75489

It is broken in all zoom levels it appears (17-19) and it should actually read "Bundeswehr-Dienstleistungszentrum Dresden" (see [way 24902583](http://www.openstreetmap.org/way/24902583)).

We already tried the dirty flag and tried to update data to the left and right side of the label in order to trigger a re-rendering. But so far nothing worked.

As far as I can tell the label seems to run through a meta tile border. Are such things supposed to happen or is this a bug?

**Comment by math1985** [comment] 2015-02-23 17:15
> Are such things supposed to happen 

Obviously not... Thanks for reporting (although I'm not sure if there's an easy fix).

**Comment by HolgerJeromin** [comment] 2015-02-23 18:15
Perhaps this is the same as my #1135 report.

**Comment by math1985** [comment] 2015-02-23 18:21
Yes, same issue as #1135. Closing this one as duplicate.

**Comment by pnorman** [comment] 2015-02-27 23:09
re-opening. they're both meta-tile issues, but I'm not convinced they're the same meta-tile issue.

This one looks to be simpler, as it's happening at higher zooms too, where there are no possible label collisions.

**Comment by pnorman** [comment] 2015-03-02 00:25
As strange as it sounds, I'm going to close this as cannot reproduce/wontfix.

Loading the area into a DB I can't get the label at all until z20. This is true even if I delete any other objects with names from the tables, or if I adjust the meta-tile size.

This label has a few things that are odd about it.

* It is (or would be) extremely large, over 256px. This means it can have a centroid within the bbox. Mapnik doesn't seem to want to break at the hyphen

* Using st_pointonsurface instead of letting mapnik do the calculation doesn't solve the problem. it moves it, but still doesn't place on all zooms.

* Changing the label to have some spaces in it to allow it to break helps it place, but still not reliably.

**Closed by pnorman** 2015-03-02 00:25 UTC

**Comment by math1985** [comment] 2015-03-02 00:51
> Mapnik doesn't seem to want to break at the hyphen

This is something we could report upstream.

**Comment by pnorman** [comment] 2015-03-02 01:11
Dev versions of mapnik have different support for wrapping - see mapnik/mapnik#2333. But it's not a fix for this bug, as I still got it if I added spaces, which it can break on.

**Comment by scaidermern** [comment] 2015-03-02 09:37
> Loading the area into a DB I can't get the label at all until z20. This is true even if I delete any other objects with names from the tables, or if I adjust the meta-tile size.
But then there must be some difference in either the setup or the data. Do you expect it to go away eventually? I understand that you can't do very much if you can't reproduce it.

**Comment by pnorman** [comment] 2015-03-02 22:56
> Do you expect it to go away eventually?

Yes, but entirely by itself for reasons we won't understand.

**Comment by scaidermern** [comment] 2015-11-10 07:57
Unfortunately this problem still exists and the landuse rendering is still broken.
