### ISSUE TITLE
Don't render `ref` on ways if `name` is present

### ISSUE THREAD

**Issue by bgo-eiu** [gravitystorm/openstreetmap-carto#4716] opened 2022-10-15 03:25 UTC
### Expected behavior

The names of major roads should be visible before finer details.

### Actual behavior

The road names are obscured by road route `ref` tags for routes that are often obscure and unsigned, making the map look crowded and harder to recognize.

### Screenshots with links illustrating the problem
![Screenshot_20221014-232132](https://user-images.githubusercontent.com/100172442/195966687-5e2ba1c7-52ff-4681-8c9f-ccf7b533aa3b.png)

The major road here is called North Avenue but the giant bubble saying US Truck 1 obscures this. This is not really useful information, and most people do not really recognize these routes.

**Comment by wmisener** [comment] 2022-10-17 18:24
The lack of road names at low zoom is indeed a major problem with Carto in my view. In my area, you cannot see the names of most primary roads until z=15 or later, when they are less useful for city-scale orientation. However, the problem is not the route number labels, but the fact that in many cities, the roads are split into short segments to accommodate, e.g., lane and route information, and carto does not coalesce the roads to make labels. So if the segment is shorter than the road name's length at a zoom, the name won't render. This has been brought up in #497 and #951.

I think this suggestion has unintended problems: namely, it would remove the route number labels from ways like I 83 in the west of the image (`name=Jones Falls Expressway`), and dare I say most freeways and state roads with a ref. In general, many roads around the world, and in the US, have both a name and a recognizable route number, and so I don't think removing the ref rendering if the road is named is a good choice.

**Comment by imagico** [comment] 2022-10-17 18:52
I don't see the shown example pointing to a real problem.  As far as i can see it shows six road shields and it is doubtful if any of them is blocking a road name label to be shown that is missing right now.  If road refs are important for orientation depends on the culture of the area so this cannot be generalized.  We have problems with both the name and the ref rendering (like #596 and #951) but these are separate issues.

The suggestion to categorically not render refs on road ways with a name tag is definitely not something i would support because it provides a bad mapping incentive.  If there are situations where prioritizing road refs before road names leads to problems that are not covered by existing issues please point them out.  Prioritization could be adjusted here - but it would only be a good idea to consider this if we have a concrete problem we want to fix.

I am closing this as declined as is - for any concrete problems that mandate a change in priorities please open a new issue.

**Closed by imagico** 2022-10-17 18:52 UTC
