### ISSUE TITLE
Support amenity=research_institute

### ISSUE THREAD

**Issue by Simon0Harms** [gravitystorm/openstreetmap-carto#4185] opened 2020-07-30 09:24 UTC
### Expected behavior
Show the (Short) Name of a  Research Institute
### Actual behavior
You have to bypass by using e.g. landuse.
### Links and screenshots illustrating the problem
Was discussed here (german):
https://forum.openstreetmap.org/viewtopic.php?pid=796166#p796166

**Comment by imagico** [comment] 2020-07-30 09:54
Duplicate of #2077.

**Closed by imagico** 2020-07-30 09:54 UTC
