### ISSUE TITLE
Unusual rendered display of addr:unit in Australia

### ISSUE THREAD

**Issue by PeterLeGras** [gravitystorm/openstreetmap-carto#4208] opened 2020-09-25 08:36 UTC
### Links and screenshots illustrating the problem
![Villa complex with unit numbers example](https://user-images.githubusercontent.com/52308086/94245117-27067f00-ff5d-11ea-8252-97630edd14c3.png)

**Comment by imagico** [comment] 2020-09-25 11:31
Duplicate of #3568.

Please don't use formatting to gather more attention in the general issue description.

**Closed by imagico** 2020-09-25 11:31 UTC

**Comment by PeterLeGras** [comment] 2020-09-25 12:25
My apologies, it's my first time opening an issue so I didn't realise it was all bolded. Thanks for linking the duplicate.
