### ISSUE TITLE
Rendering coworking_space

### ISSUE THREAD

**Issue by arnaudlecam** [gravitystorm/openstreetmap-carto#2118] opened 2016-05-01 23:58 UTC
Hi,
Wiki pages was unclear if I have to make a proposal or working here.
And I failed pulling my request, sorry....
You will find a SVG file to render amenity=coworking space.
I found it [here](http://wiki.coworking.org/w/page/16583882/Logo), [with those sources](http://wiki.coworking.org/w/page/16583882/Logo)

[Coworking-16.svg.zip](https://github.com/gravitystorm/openstreetmap-carto/files/244404/Coworking-16.svg.zip)

**Comment by pnorman** [comment] 2016-05-02 00:00
duplicate of #1628

**Closed by pnorman** 2016-05-02 00:00 UTC
