### ISSUE TITLE
Circular bench as line not rendered at all.

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4693] opened 2022-09-22 16:43 UTC
I added a circular bench as a line.
https://www.openstreetmap.org/#map=19/51.75494/3.85930

A bench should be applicable as a point and a line.
I ended up with nothing. No line, no icon.

So, is this a bug?
It forces me to a workaround.

**Comment by HolgerJeromin** [comment] 2022-09-23 07:46
Thanks for reporting. 
Has nothing to do with circular. No bench line features are rendered.
https://www.openstreetmap.org/way/79639567

duplicate of #2711

**Comment by imagico** [comment] 2022-09-24 15:04
Closing as duplicate of #2711.

**Closed by imagico** 2022-09-24 15:04 UTC
