### ISSUE TITLE
building=roof does not render over highway=pedestrian | area = yes

### ISSUE THREAD

**Issue by artischocke** [gravitystorm/openstreetmap-carto#2247] opened 2016-07-26 10:04 UTC
See this feature at the Berlin Institute of Technology: https://www.openstreetmap.org/way/411717033

**Comment by artischocke** [comment] 2016-07-26 10:05
See this feature at the Berlin Institute of Technology: https://www.openstreetmap.org/way/411717033

**Comment by polarbearing** [comment] 2016-07-26 11:18
Duplicate of #688. Please search for existing tickets before opening new ones.

**Closed** 2016-07-26 12:07 UTC

**Comment by artischocke** [comment] 2016-07-26 12:43
I did search, but there was no mention of pedestrian in the ticket you linked, so my search query didn't return any results. A simple "duplicate of X" would've sufficed.

**Comment by polarbearing** [comment] 2016-07-26 13:10
pedestrian is mentioned a couple of times in #688, and dup #755 explicitly mentiones "roof over pedestrian area" in the title.

**Comment by artischocke** [comment] 2016-07-26 13:32
Yes, there is the possibility I may have missed it. This is, after all, my first time here.

I take it this sort of "curtness" and desire to be right over being welcoming is the norm here: https://github.com/gravitystorm/openstreetmap-carto/issues/2206

Not really the sort of thing that makes people want to get engaged in a project.

**Comment by gravitystorm** [comment] 2016-07-28 09:53
> Duplicate of #688. Please search for existing tickets before opening new ones.

As @artischocke says, we should be more welcoming that this.

**Comment by math1985** [comment] 2016-07-28 10:28
> As @artischocke says, we should be more welcoming that this.

+1.
