### ISSUE TITLE
Switch to Natural Earth for very low zoom water

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2293] opened 2016-08-19 14:48 UTC
Large lakes (e.g. Great Lakes) have been a long-standing problem (#1604). In any other style, I would have switched to a more appropriate LZ data source, or used one from the very start like every other stylesheet. z4 is such a low resolution that we don't need to worry about updates to OSM data.

This conflicts with our goal to move away from non-OSM data, but I'm okay with that.

**Comment by imagico** [comment] 2016-08-19 17:22
I have never specifically reviewed the Natural Earth lakes data set but looking at it now - you have got to be kidding me.

Not only is Natural Earth of course not for Mercator so it looks ugly when used in a web map in any case but it is also hopelessly outdated and incomplete and full of poor choices.

Bad choices are for example including Lago Maggiore but not Lac de Neuchâtel, having various intermittent lakes in Australia but not in Africa.  Even without special consideration for the Mercator projection there is a clear bias against lakes on the Arctic islands (lakes of more than 200 square kilometers missing in northern Greenland while ones with less than 30 included elsewhere).

Missing newer reservoirs are Bakun Reservoir, Merowe Reservoir and Indirasagar Reservoir. 

Currently water areas are rendered from z6 by the way so another source would be used up to z5.

According to https://github.com/gravitystorm/openstreetmap-carto/issues/1604#issuecomment-214758374 the requirement is a data set that is regularly updated and the process for this being available as open source.  If the the need is only to be better than Natural Earth the hurdle would be significantly lower.

**Comment by kocio-pl** [comment] 2016-08-19 20:20
Lack of big lakes on early zoom levels is disturbing to me. Do you have a hint how should we make them appear without using NE data?

And what about NE data - is it possible (and does it make sense) to fix them, so they become usable for us?

**Comment by kocio-pl** [comment] 2016-12-03 21:50
Looks like the problem of missing part of Uruguay/Argentina border (z1-z3) is caused by great Río de la Plata estuary, which is not visible then.

**Comment by StyXman** [comment] 2016-12-04 12:02
I think this is a data/tagging problem. I think the Río de la Plata's riverbanks should also be considered coastlines. I don't think Río de la Plata should be called a river, it's too big, bigger than several gulfs; for instance, the Thermaic Gulf. But the fact is that it is. So, what about extending the coastine with the river's riverbank?

**Comment by imagico** [comment] 2016-12-04 12:19
The Río de la Plata issue is fairly off-topic here - see

http://wiki.openstreetmap.org/wiki/Proposed_Features/Coastline-River_transit_placement

Local mappers seem pretty opinionated about the matter - mostly for political reasons since Argentina and Uruguay claim it to be internal waters.

**Comment by kocio-pl** [comment] 2017-10-14 00:40
Looks like this solution is not needed now, it's effectively closed by #2873.

**Closed by kocio-pl** 2017-10-14 00:40 UTC
Labels: water
