### ISSUE TITLE
Please render sports_centre

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4697] opened 2022-09-26 14:01 UTC
https://www.openstreetmap.org/#map=19/51.75357/3.85196

I have added 2 sports_centre as follows.
```
leisure=sports_centre
sport=<sport>
```
They do not show up in any way.
Frustrating as ever.

Maybe there is some magic combination of tags to succeed, which I have not yet discovered.
But this should be simple.

Please render this.

Adding a name renders that. 
But I would expect some icon without a name.

**Comment by HolgerJeromin** [comment] 2022-09-26 14:17
They are rendered (when not the same as a building):
https://www.openstreetmap.org/way/549930092

What object is missing a rendering?

You mean https://www.openstreetmap.org/node/10053730860 ?
This is rendered
![image](https://user-images.githubusercontent.com/2410353/192299985-4a0fb9b6-7fd0-4e89-a8e8-da561ab86aec.png)

**Comment by imagico** [comment] 2022-09-26 14:57
We render `leisure=sports_centre` with a name label.  And we have #844 for ideas for sport specific rendering.

If you have a concrete idea for a generic rendering other that with a name label that works for all kinds of sports and that provides useful additional information that would be of interest.  It seems unlikely to me that this is feasible though.  Closing this as unfeasible (for not sport specific rendering other than a name label), as duplicate of #844 for sport specific rendering and as invalid for the lack of rendering in general.

**Closed by imagico** 2022-09-26 14:57 UTC

**Comment by BertMule** [comment] 2022-10-04 18:14
I really wish you would at least apply generic icons or name-behaviour to entities.
This is already strongly suggested by the use of one within the ID-editor (a running figure).
So often the icons are already available.
Even more specific, like for pitches.

**Comment by jeisenbe** [comment] 2022-10-04 21:52
@BertMule this style usually renders an icon when a feature is mostly mapped as a node or building, such as shops and other small amenity features. 

When a larger feature is usually mapped as an area of ground, including several smaller buildings, it maybe rendered with a color for the area, plus a name label. In that case we do not usually have an icon, because the area is rendered instead. 

In the case of `leisure-sports_centre` there is a rendering for the area in `@stadium` (`@leisure`) color, since often this includes several buildings, pitches, a pool etc - https://github.com/gravitystorm/openstreetmap-carto/blob/6508b486353eebdf902dfb7b2fa23eaccbeb836f/style/landcover.mss#L671-L675

There is also a rendering for the name - https://github.com/gravitystorm/openstreetmap-carto/blob/6508b486353eebdf902dfb7b2fa23eaccbeb836f/style/amenity-points.mss#L2326-L2328

Similarly, schools and parks have a rendering for the area, but do not have an icon because the meaning is usually understood from the context and name.
