### ISSUE TITLE
Render tunnel=flooded with tunnel styling

### ISSUE THREAD

**Issue by jragusa** [gravitystorm/openstreetmap-carto#3400] opened 2018-09-17 22:14 UTC
### Expected behavior
Support `tunnel=flooded` for waterways

### Actual behavior
Only `tunnel=yes` and `tunnel=culvert` are rendered.

There is only 573 flooded tunnels but the lack of support creates confusion with superficial waterways.

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/586127462

before
![flooded_before](https://user-images.githubusercontent.com/9897203/45653186-62048b00-bad7-11e8-9045-8c644b8c20ca.png)

after
![flooded_after](https://user-images.githubusercontent.com/9897203/45653194-692b9900-bad7-11e8-8529-4e4ef50f19cb.png)

**Comment by HolgerJeromin** [comment] 2018-09-18 04:40
Thanks for your suggestion.
Is there a documentation for this tag available?

**Comment by Adamant36** [comment] 2018-09-18 05:42
@HolgerJeromin, https://wiki.openstreetmap.org/wiki/Tag:tunnel%3Dflooded

It comes up fifth in the search for the term tunnel=flooded for some reason.

**Comment by matkoniecz** [comment] 2018-09-18 15:20
I changed the title a bit to make it more clear what is requested.

**Comment by Gazer75** [comment] 2018-11-15 21:05
This is due to the approval of this:
https://wiki.openstreetmap.org/wiki/Proposed_features/Hydropower_water_supplies

**Comment by matkoniecz** [comment] 2019-04-09 14:05
Given that it is just new value of tunnel tag I think that it would be OK. I would recommend checking random `tunnel=flooded`, check history and look whatever the edit was problematic (problematic as in "there is an ongoing discussion in changeset or proposal to revert it for some good reason")

**Comment by imagico** [comment] 2019-04-09 15:40
Small correction:  About 1/3 of uses of tunnel=flooded + waterway=canal are correctly used for qanats (together with canal=qanat) - which is probably also the most widespread real life situation where this tag could be used.  This is something that would be good to render (though better with a dedicated styling rather than a generic waterway tunnel signature)

**Comment by Gazer75** [comment] 2019-04-09 16:05
https://www.openstreetmap.org/#map=17/58.65856/6.73393
That hydro plant I mapped is a good one to test at. You have headrace, penstock and tailrace.
Zoom out a bit and you'll see all the tunnels feeding it from different lakes and river intakes.

**Comment by imagico** [comment] 2019-04-09 17:19
Yes, but as said it is highly unfortunate if mappers choose to re-purpose established waterway tags for those so data users have no reliable way to distinguish between these and something like

https://www.openstreetmap.org/way/242158791

which equally qualifies as waterway=canal + tunnel=flooded.

Therefore at the moment i would say that tunnel=flooded is not currently used specifically enough to base rendering decisions on it.  Interpreting usage=* is a different question.

**Comment by Gazer75** [comment] 2019-04-09 17:35
Is that really flooded? Looks like a canal with locks for boats to get up and down the river.

**Comment by imagico** [comment] 2019-04-09 17:48
I think you just made my point that you interpret tunnel=flooded to mean no free surface flow - which is what is meant to be indicated with waterway=pressurized.

The problem with using supplemental tags to exclude something from rendering is that this is confusing for mappers and likely to encourage some to deliberately leave out the tag to have things rendered.

**Comment by Gazer75** [comment] 2019-04-09 18:15
Read wiki description. Flooded canal would not allow anything like a boat inside under normal operation.
https://wiki.openstreetmap.org/wiki/Tag:tunnel%3Dflooded

**Comment by imagico** [comment] 2019-04-09 18:36
We should not turn this into a tagging discussion - but there is no mentioning of boats or ships on the wiki page.

And we have a well established tag of course to indicate a canal is not suitable for boats - that is boat=no.

**Comment by jeisenbe** [comment] 2019-10-18 04:07
This is a duplicate of #3179 "Render waterway with tunnel=flooded like tunnel=yes" - please continue discussion there.

**Closed by jeisenbe** 2019-10-18 04:07 UTC
Labels: duplicate
