### ISSUE TITLE
Great Lakes missing at zoom levels <= 5

### ISSUE THREAD

**Issue by meased** [gravitystorm/openstreetmap-carto#2201] opened 2016-06-28 00:56 UTC
![great_lakes](https://cloud.githubusercontent.com/assets/14190496/16400433/22aa6a8c-3c90-11e6-8821-6587da7c1a32.png)

They were present before the recent update.

**Comment by math1985** [comment] 2016-06-28 01:00
No, this was always the case.

Duplicate of #1604.

**Closed by math1985** 2016-06-28 01:00 UTC

**Comment by matkoniecz** [comment] 2016-06-28 09:14
> No, this was always the case.

It may be a bit more complicated. In the past some lakes for some time were mapped as ocean/sea (natural=coastline) - see for example https://github.com/gravitystorm/openstreetmap-carto/issues/1604#issuecomment-172147711
