### ISSUE TITLE
v4.21 release

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#3736] opened 2019-04-04 06:23 UTC
I'd like to get out a v4.21 release for a branch point for schema changes, and to get the pointonsurface stuff out.

Are there any other *ready to merge* PRs that we should get in before release?

**Comment by imagico** [comment] 2019-04-06 13:18
I have merged a number of things that were ready a few days back so i think we would be fine for a release now.

**Comment by jeisenbe** [comment] 2019-04-12 14:03
I'm fine with doing the release now. The PRs that are currently open can wait till the next month.

**Comment by pnorman** [comment] 2019-04-12 17:01
If someone else can test and handle the release process that would be good. I'm busy with a move that includes my computer.

**Comment by pnorman** [comment] 2019-04-17 19:14
Just noting that this is on my to-do list, and my development machine is still in its shipping box.

**Comment by pnorman** [comment] 2019-05-02 05:01
Done, and created the `schema_changes` branch. As a reminder for maintainers, when tagging a new release it's your responsibility to merge it to this branch

> If there are any long-running development branches check them out and merge the new release with git merge $NEW_RELEASE

**Comment by jeisenbe** [comment] 2019-05-02 12:09
I wish I had mentioned that #3759 should have been fixed before this release (All shop text labels are no longer being displayed after #3712). I've submitted #3760 with the fix.

It would also be nice to fix #3765 which is also caused by #3712 but it's not as noticeable.

**Comment by pnorman** [comment] 2019-05-04 16:34
These sound like big enough bugs to release a v4.21.1

**Comment by kocio-pl** [comment] 2019-05-05 05:11
Another big enough regression problem: #3765.

**Comment by kocio-pl** [comment] 2019-05-10 00:23
Yet another regression bug: #3780.

**Comment by pnorman** [comment] 2019-05-30 03:16
I've tagged v4.21.1 somewhat belatedly. Do we think there's enough stuff for v4.22.0 soon? If so I'll hold off the v4.21.1 announcement.

**Comment by jeisenbe** [comment] 2019-08-21 11:22
It looks like no new bugs have been discovered in the past couple of months. Do we have enough for v4.22.0 or should v4.21.1 be released soon?

**Comment by pnorman** [comment] 2019-08-21 19:07
I'd go for v4.22.0 after reviewing PRs

**Comment by jeisenbe** [comment] 2019-09-17 01:33
Close in favor of v4.22.0

**Closed by jeisenbe** 2019-09-17 01:33 UTC
