### ISSUE TITLE
highway=escape

### ISSUE THREAD

**Issue by printmaps** [gravitystorm/openstreetmap-carto#2898] opened 2017-10-16 08:20 UTC
highway=escape is currently not rendered. I recommend to draw these emergency infrastructure as gray line.

https://www.openstreetmap.org/#map=17/50.67673/8.29081

![bildschirmfoto 2017-10-16 um 10 19 30](https://user-images.githubusercontent.com/26689799/31601892-a2a2ef60-b25b-11e7-9673-094617807ddb.png)

**Comment by polarbearing** [comment] 2017-10-16 08:44
Duplicate of #1239. Please use the search function before opening tickets, this was an easy find.

**Closed** 2017-10-16 08:46 UTC
