### ISSUE TITLE
Use surface in addition to tracktype for highway=track

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#2513] opened 2016-12-15 21:31 UTC
I never liked the tracktype numbers, so i added only a surface tag. But sadly this style does only [support tracktype](https://github.com/gravitystorm/openstreetmap-carto/blob/356a655ccbfc92941f200225db63a15445abb719/roads.mss#L1768-L1800) on tracks.
This raises the question which tag has priority. I would fallback to surface if no tracktype is there.
Related to #110

**Comment by dieterdreist** [comment] 2016-12-15 21:54
2016-12-15 22:31 GMT+01:00 Holger Jeromin <notifications@github.com>:

> This raises the question which tag has priority. I would fallback to
> surface if no tracktype is there.




no, it's not about "priority", because the issue is about showing both,
tracktype and surface.

**Comment by HolgerJeromin** [comment] 2016-12-15 21:59
A small solution would be fallback to surface if not tracktype is there. But this would be revisited by implementing #110.
While i am not sure if you can squeeze tracktype and surface in one visualisation. But this should be discussed not here.

**Comment by matkoniecz** [comment] 2018-04-19 14:32
> While i am not sure if you can squeeze tracktype and surface in one visualisation

I am pretty sure that it is not feasible, and I would expect these values to generally be consistent (there are cases like extremely overgrown asphalt track, but it is fairly rare)

**Comment by imagico** [comment] 2021-02-07 11:45
Closing this since rendering both tracktype and surface does not seem to be feasible, removing tracktype rendering is suggested in #4322 instead.

**Closed by imagico** 2021-02-07 11:45 UTC
Labels: enhancement, roads

**Comment by dieterdreist** [comment] 2021-02-11 00:07
I guess it could be confusing ;)
but it wouldn't be technically impossible to show both, tracktype and
surface, e.g. tracktype could be shown as line width and surface through
dashes. Or opacity for tracktype. Or encode something in the casing...
