### ISSUE TITLE
Rendering of addresses of things that aren't rendered

### ISSUE THREAD

**Issue by loominade** [gravitystorm/openstreetmap-carto#2005] opened 2015-12-10 12:37 UTC
[This Office](http://www.openstreetmap.org/node/3859644828) is not rendered: which I think is reasonable. But its address is rendered, which normally would be good but there already is an address mapped on the building entrance. In this case the address looks redundant.

So my idea was, if it is something which is not rendered, the address should be hidden too. But I'm not sure if thats a good idea.

Any idea how to fix this?

**Comment by math1985** [comment] 2015-12-10 13:56
Duplicate of #962.

**Closed by math1985** 2015-12-10 13:56 UTC

**Comment by BalooUriza** [comment] 2015-12-15 09:14
On Thu, Dec 10, 2015 at 6:37 AM, loominade <notifications@github.com> wrote:

> This Office <http://www.openstreetmap.org/node/3859644828> is not
> rendered: which I think is reasonable. But its address is rendered, which
> normally would be good but there already is an address mapped on the
> building entrance. In this case the address looks redundant.
>
> Any idea how to fix this?
>

I see that the node appears to have the same address as on the area; is
there any reason why this is mapped as a node instead of the node's tags
applied to the area of the same address?

**Comment by loominade** [comment] 2015-12-16 15:35
@BalooUriza the [area](http://www.openstreetmap.org/way/382745745) has no address. But the [entrance](http://www.openstreetmap.org/node/1552074563) has an address which – I think – should be rendered.
