### ISSUE TITLE
golf=tee and golf=green should be changed to draw on top of golf=fairway

### ISSUE THREAD

**Issue by leijurv** [gravitystorm/openstreetmap-carto#4147] opened 2020-05-16 06:57 UTC
### Expected behavior

 "Golf Course Tee Box" and "Golf Course Putting Green" should draw on top of "Golf Course Fairway"

"Golf Course Sand Trap" already renders on top of "Golf Course Fairway", as one would expect.

### Actual behavior

"Golf Course Fairway" draws on top of "Golf Course Tee Box" and "Golf Course Putting Green", defeating the point, and requiring very bad workarounds such as what you can see at https://www.openstreetmap.org/edit#map=17/37.42721/-122.43336

### Links and screenshots illustrating the problem

https://www.openstreetmap.org/edit#map=17/37.42721/-122.43336

**Comment by Adamant36** [comment] 2020-05-16 07:01
It's not rendering that way because of the golf tags. Since none of them are currently implemented. It's because of how the other added tags are rendered in priority.

**Comment by leijurv** [comment] 2020-05-16 07:02
OK then I suggest that tee box and putting green, get a slightly lighter shade of green, and be drawn on top.

**Comment by Adamant36** [comment] 2020-05-16 07:07
There's already a couple of issues open for rendering golf tags. I'll probably work on it myself when I get some free time soon. Maybe comment what you want in one of them. Since this will more then likely get lost when it's closed.

**Comment by leijurv** [comment] 2020-05-16 07:08
? 

Tee box and putting green should get a slightly lighter shade of green than fairway, and be rendered on top? I'm not sure what else I might describe.

**Comment by imagico** [comment] 2020-05-16 10:00
What you see rendered in the area you linked to is landuse=grass and natural=sand, not golf=* tags.

Hence this seems to be a duplicate of #661 - closing as such.

**Closed by imagico** 2020-05-16 10:00 UTC
