### ISSUE TITLE
roller_coaster=track does not yet render

### ISSUE THREAD

**Issue by chatelao** [gravitystorm/openstreetmap-carto#4445] opened 2021-07-29 10:37 UTC
### Expected behavior
Roller coaster tracks are currently only rendered, if worked around with "railway" or "leisure=track"

### Actual behavior
As this objects are prominent in the landscape and mostly visible on satellite images, a direct rendering would be nice.

### Links and screenshots illustrating the problem
Here everythink is tagged (without "map for render"):
https://www.openstreetmap.org/#map=19/46.91977/7.44223
![image](https://user-images.githubusercontent.com/2461532/127477667-d86417bf-33c6-4360-8bc6-e3a996a040a0.png)

But only the house and the drag line appears on the map, not the main track:
![image](https://user-images.githubusercontent.com/2461532/127477778-6ec74c17-3d67-4eb6-b977-302d768aa7ab.png)

**Comment by imagico** [comment] 2021-07-29 11:00
Duplicate of #3596.

**Closed by imagico** 2021-07-29 11:00 UTC
