### ISSUE TITLE
Stop landuse labels based on area

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#1028] opened 2014-10-07 21:05 UTC
#941 gave us labels which start rendering based on area.We should be doing the counterpart to this and stop rendering when an area gets too big.

As one of the more extreme examples, http://www.openstreetmap.org/#map=19/39.18521/-96.81765
![image](https://cloud.githubusercontent.com/assets/1190866/4550284/2ddaa842-4e65-11e4-9e40-585e21ce4877.png)
[Continued in all directions]

From that zoom, I have to zoom out 5 times (128x) to see a boundary, meaning placing text in the middle is rather meaningless. I have a 1080p screen, so most people will be 5 or 6 times.

A few options
- Stop rendering labels based on way_pixels
- Scale the label to _very_ large, keeping it a reasonable percentage of the overall size. Requires expr everywhere and Mapnik 3
- Repeat the label. Not technically trivial, and probably would cause issues in some other cases.

**Comment by math1985** [comment] 2016-02-27 18:29
A solution for the Carto bugs that prevented doing this (https://github.com/mapbox/carto/issues/369 and https://github.com/mapbox/carto/issues/370) have been merged today.

Writing a

**Comment by math1985** [comment] 2016-02-27 18:30
A solution for the Carto bugs that prevented doing this (https://github.com/mapbox/carto/issues/369 and https://github.com/mapbox/carto/issues/370) have been merged today.

Solving the issue here would imply that we require the tileservers to run the latest Carto version. @gravitystorm @pnorman Any opinions on this?

**Comment by gravitystorm** [comment] 2016-02-29 13:42
I want to ensure that this style can be run on a variety of systems, such as tilemill and kosmtik. So I certainly don't want to depend on anything that is in an unreleased version of carto, and I'd prefer to wait until kosmtik has a release containing that version of carto too (ideally Tilemill but that seems unlikely).

Of course, the OSMF tileservers are a separate task, but after a carto release that should be straightforward.

**Comment by math1985** [comment] 2016-02-29 14:00
>  I'd prefer to wait until kosmtik has a release containing that version of carto too (ideally Tilemill but that seems unlikely).

Would that involve more than bumping the carto version in package.json in both respective projects?

**Comment by gravitystorm** [comment] 2016-02-29 19:11
I don't know exactly what's involved, tbh.

**Comment by math1985** [comment] 2016-02-29 23:44
Confirmed that changing the node version in kosmtik can simply be accomplished by changing the version number in package.json and running npm install from the kosmtik directory.

In Tilemill, it should work likewise. Could somebody running Tilemill confirm that?

**Comment by pnorman** [comment] 2016-03-01 15:14
We need

- a carto release with the new code
- a kosmtik release requiring the new cargo
- a tilemill release requiring the new cargo
- new tilemill binaries

**Comment by nebulon42** [comment] 2016-04-11 22:13
carto 0.16.0 has been released. Kosmtik PR pending (https://github.com/kosmtik/kosmtik/pull/121).

**Comment by math1985** [comment] 2016-04-12 07:33
Thanks a lot!

**Comment by math1985** [comment] 2016-08-04 12:13
> a carto release with the new code
> a kosmtik release requiring the new carto
> a tilemill release requiring the new carto

These we have got now.

> new tilemill binaries

What is the situation here? Is there any chance somebody is going to create new binaries?

**Comment by nebulon42** [comment] 2016-08-05 20:21
Just to be exact there hasn't been a new Tilemill release. The last one was in 2012.
I think you have to ask @springmeyer if he would be so kind to provide binaries.

**Comment by math1985** [comment] 2016-08-05 20:29
Correct, a pull request has been accepted for tilemill requiring the new carto version, but no release has been made.

**Comment by springmeyer** [comment] 2016-08-05 20:31
@math1985 @nebulon42 - can you use TileMill master. Iv'e been keeping that passing (along with keeping binaries published and update to date for the hard to install deps (like node-mapnik). The idea is that you can install like https://github.com/mapbox/tilemill#installation.

**Comment by kocio-pl** [comment] 2016-12-15 04:58
I guess we are now [old dependencies free](https://github.com/gravitystorm/openstreetmap-carto/pull/2473) and we could use label repeating?

**Comment by pnorman** [comment] 2016-12-15 05:27
The issue @math1985 ran into were bugs with selectors when trying to stop labels from rendering at high zooms. He was exploring the first of the three options in my original post

I have no idea which of the original three is the best way to solve this issue, and that's hard to say without exploring what it looks like when implemented.

**Comment by math1985** [comment] 2016-12-15 08:55
As war as I know this problem has indeed been resolved in carto, so I think it'd be good to implement this now.

**Comment by kocio-pl** [comment] 2016-12-15 12:57
Not that I plan to test it any time soon, because I see some other tasks as more important, so please don't hesitate if you want to do it yourself.

**Comment by Tomasz-W** [comment] 2018-07-03 09:39
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/3284

**Comment by matthijsmelissen** [comment] 2018-07-03 10:36
Now carto 0.16.0 is out, I think this should be a fairly simple fix.

**Comment by jeisenbe** [comment] 2018-11-27 01:07
@matthijsmelissen are you planning to do a PR?

**Comment by matthijsmelissen** [comment] 2018-11-27 09:39
Not at the moment, but it shouldn't be too hard, so feel free to try!

**Comment by sommerluk** [comment] 2019-08-31 06:51
Closed in #3764

**Closed by sommerluk** 2019-08-31 06:51 UTC
Labels: landcover, text

**Comment by jeisenbe** [comment] 2019-08-31 07:47
Thanks @sommerluk.

One issue that is now apparent: `aeroway=aerodrome`, which last renders at z13, does not usually follow the example set in #3764. Now other features drop the text label at >768,000 `way_pixels`.

Some aerodromes are still mapped as nodes, so we shouldn't rely on waypixels. But examining the large, high-lattitude airports which are mapped as areas shows that z14 is far too soon to stop rendering aerodromes. 

Here's Belfast International, a major airport in a rural area far from the city which takes up a large surface area. Since it's at 56 degrees north, it's almost twice as large on-screen as similar sized airports at the equator; it's bigger than the vast majority of aerodromes with an ICAO and IATA code.

But at z15 it's still only at 524000 way_pixels, so it ought to still render at z14 and z15:
![z15-belfast-international-before-waypixels-524418](https://user-images.githubusercontent.com/42757252/64060905-35755080-cc0e-11e9-9193-e52da16bef8f.png)

Belfast city airport is also a large, major airport with a full-length runway at high lattitude, but it only hits 36,000 way_pixels at z14, so it should render till z16 (576k waypixels). Note that there is no icon or text currently rendered at z14
![z14-belfast-city-airport-waypixels-35864](https://user-images.githubusercontent.com/42757252/64060925-7c634600-cc0e-11e9-896a-9afa4669583e.png)

Smaller aerodromes should render till z17, especially near the equator. This one is actually a commercial airport with several passenger flights every day, with turboprop planes. Waypixels = 36,000 at z16, so could render even at z18.
![z16-bandar-udara-oksibil-inspector-way_pixels-35973](https://user-images.githubusercontent.com/42757252/64060942-b7657980-cc0e-11e9-8c95-65c72c53138f.png)
