### ISSUE TITLE
Different halfs of map different styles at different zoom levels

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3810] opened 2019-06-19 23:15 UTC
At https://www.openstreetmap.org/#map=14/11.1137/-0.1806 half of the map is blue.
Zoom in. Now it's the other half. Despite CTRL+Refresh.

**Comment by jidanni** [comment] 2019-06-19 23:18
![X0](https://user-images.githubusercontent.com/1230959/59807701-9be71400-932b-11e9-95bf-f98290200c3f.jpg)

**Comment by Adamant36** [comment] 2019-06-20 00:10
Its been an ongoing problem for a while now and might be not related to the style. See #3791 for reference.

**Comment by pnorman** [comment] 2019-06-20 00:49
This is not a style issue but one specific to the deployment and outside osm-carto's control.

One of the rendering servers had an error with downloading the shapefiles, so that's probably the cause, which would make it a duplicate of #3791.

**Closed by pnorman** 2019-06-20 00:49 UTC
