### ISSUE TITLE
Rendering of name is "off"

### ISSUE THREAD

**Issue by martiensch** [gravitystorm/openstreetmap-carto#2056] opened 2016-02-22 13:05 UTC
The rendering of the name of this area is not within the area, but two kilometres south of it and about five from the centre of the area: https://www.openstreetmap.org/way/34868804#map=14/52.5656/7.1662

(I know that I should tag the relation instead of this outer member, but I noted that too late ;) )

**Comment by matkoniecz** [comment] 2016-02-22 13:14
duplicate of #1465 (bug fixed upstream, once rendering on osm servers will be upgraded to Mapnik 3 this problem will disappear).

**Closed by matkoniecz** 2016-02-22 13:14 UTC
