### ISSUE TITLE
Big facilities unnamed but little parks are named at certain zoom levels

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4789] opened 2023-03-19 04:44 UTC
### Expected behavior
Big facility's name shows up when the name of the little park next to it shows up.
### Actual behavior
Big facility's name still a mystery, but park next door has a name.
### Screenshots with links illustrating the problem
https://www.openstreetmap.org/#map=16/40.8671/-88.6319
![20230319T123959](https://user-images.githubusercontent.com/1230959/226154082-02bba88d-5c86-4b5d-85e2-90e4745e0642.jpg)

**Comment by imagico** [comment] 2023-03-19 10:51
Closing because:

* it lacks a concrete problem definition and a matching issue title.  Because of that everyone reading it would unnecessarily have to research the problem observed.  Since this has become more common recently i have created a new label (https://github.com/gravitystorm/openstreetmap-carto/labels/lacks%20concrete%20problem%20description) for that and suggest we close such issues until such definition can be added.
* the problem this is likely meant to point out is probably a duplicate of #1022.

**Closed** 2023-03-19 11:29 UTC
Labels: duplicate
