### ISSUE TITLE
Parks: we should add detail, but then sacrifice the park's name?!

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4828] opened 2023-06-08 13:32 UTC
### Expected behavior
Mappers are encouraged to add details to parks, like picnic benches and buildings.
### Actual behavior
Doing so knocks out the most important thing: the park's name! 
### Screenshots with links illustrating the problem
![20230608T082642](https://github.com/gravitystorm/openstreetmap-carto/assets/1230959/41f3c7be-204d-4890-934f-838c24e84108)
https://www.openstreetmap.org/#map=17/42.16643/-87.84181
In the northeast, the park's name is wiped out.
In the southwest, a vanilla park with no features added, the park's name survives.

Think of some world famous parks. Now imagine them unnamed.

**Comment by imagico** [comment] 2023-06-08 19:47
I don't see this being an actionable issue and the observed behavior is due to things for which - as explained in the following - we already have issues, hence i suggest we close it.

The causes of the observed behavior are:

* that picnic tables are rendered relatively early at z17 - which has been suggested to be changed in #1745 and #4783.
* that we currently render point symbols with priority over point labels independent of the starting zoom level.  That could be reconsidered but that would depend on solving #3880.

That being said - if the latter is desirable or not depends on your point of view.  There are about 96 million features in the OSM database right now with a name tag, more than half of this are roads.  And even though some of those do not actually contain a proper name, names are evidently something mappers do consider significant to map.  But the suggestion that names are the most important thing to show about features in the OSM database is quite clearly something that is highly questionable when you look at what mappers map.

Personally i would consider the benches, picnic tables, playgrounds, memorials, trees etc. in a park more important than the name - both for the map user and for the mapper for feedback.

**Comment by imagico** [comment] 2023-06-13 09:50
Closing for the mentioned reasons.

**Closed by imagico** 2023-06-13 09:50 UTC
