### ISSUE TITLE
A service highway is not displayed while a track is

### ISSUE THREAD

**Issue by PontiacCZ** [gravitystorm/openstreetmap-carto#2092] opened 2016-03-20 18:25 UTC
Subject area: http://www.openstreetmap.org/?mlat=49.08807&mlon=17.11303&zoom=12#map=15/49.1089/17.0781

As you can see, in zoom 15 (and less) the service highway is not displayed.
When you zoom into zoom 16, it finally shows up.

Highway=service is typically broader and more important that a highway=track so I suppose if something was to be ignored it should be a track, not a service way.

![2016-03-20_mapnik_zoom_15_service_off](https://cloud.githubusercontent.com/assets/9153595/13906217/76a6c0fc-eed1-11e5-8bf7-80a93e2ad923.png)

![2016-03-20_mapnik_zoom_16_service_on](https://cloud.githubusercontent.com/assets/9153595/13906219/7fe4487e-eed1-11e5-8672-ffc9ca04e1b6.png)

**Comment by dieterdreist** [comment] 2016-03-20 19:12
sent from a phone

> Am 20.03.2016 um 19:25 schrieb PontiacCZ <notifications@github.com>:
> 
> Subject area: http://www.openstreetmap.org/?mlat=49.08807&mlon=17.11303&zoom=12#map=15/49.1089/17.0781
> 
> As you can see, in zoom 15 (and less) the service highway is not displayed.
> When you zoom into zoom 16, it finally shows up.
> 

I would see this as a very probable tagging error (a service that is only connected to tracks is very likely itself a track), but I agree that the way should be rendered at this zoom level nonetheless

**Comment by PontiacCZ** [comment] 2016-03-20 20:18
Well, I was there yesterday and it really is a service - it is wide enough for two cars to pass by. The road is used by forest management for transporting cut trees, regular traffic is not allowed there.

**Comment by dieterdreist** [comment] 2016-03-20 20:25
sent from a phone

> Am 20.03.2016 um 21:18 schrieb PontiacCZ <notifications@github.com>:
> 
> Well, I was there yesterday and it really is a service - it is wide enough for two cars to pass by. The road is used by forest management for transporting cut trees, regular traffic is not allowed there.


sounds like a perfect track to me

**Comment by SomeoneElseOSM** [comment] 2016-03-20 21:30
@PontiacCZ I suspect that this is related to one of the changes made around the same time as https://github.com/gravitystorm/openstreetmap-carto/pull/747 (though not actually that change; this is a service=driveway and it's that tag that causes it not to appear).  The problem is that many service=driveway are quite short and occur quite close together (in urban areas).  The rendering is the same for everywhere in the world (a driveway in the middle of Antarctica will get rendered the same at the same zoom level as one in the middle of New York City), and it's simply not possible with the "standard" style as it is now to optimise it for everywhere.

That said, as @dieterdreist suggests about are you sure it's tagged correctly?  Although the original versions are redacted it looks like it might have been a "highway=track; surface=paved; tracktype=grade1" at some point.  Even if "highway=service" is correct is it really a driveway?  Your description sounds like it may not be.

**Comment by PontiacCZ** [comment] 2016-03-20 21:55
You are right about it not being driveway. That is nonsense here. I removed the service=driveway tag and the service renders now.
I am going to rethink the service vs. track issue, look into my photos and eventually change that as well.
We may consider the issue  solved now, thank you! :-)

**Comment by aceman444** [comment] 2016-03-20 22:34
So it can be a highway=service, but it probably shouldn't be tagged service=driveway.

**Comment by matkoniecz** [comment] 2016-03-21 06:08
> The road is used by forest management for transporting cut trees

So it is highway=track. It is highly confusing but highway=track is not about quality - unpaved residential road is not highway=track, high quality asphalt road used solely for forest management/field access is highway=track.

Also duplicate of #561

Given that this case is a clear tagging error (especially service=driveway) this is not a good example of rendering problem.

**Closed by matkoniecz** 2016-03-21 06:08 UTC
