### ISSUE TITLE
Tibetan language is getting rendered extra wide 

### ISSUE THREAD

**Issue by katpatuka** [gravitystorm/openstreetmap-carto#2089] opened 2016-03-14 19:01 UTC
Tibetan language is getting rendered extra wide between letters (open for example https://www.openstreetmap.org/#map=8/29.071/89.352) - is this an issue of the font chosen or of the style ? Wideness of normal text (like here inline ཁྲན་ཡུལ་མཚོ།) would be ok - only the font-size may be a problem...

**Comment by HolgerJeromin** [comment] 2016-03-14 19:35
If the rendering is ok or better in the transport and cycle layer it is probably the same as #2017 and will disappear in the future on updating the mapnik rendering software (which is planned).

**Comment by katpatuka** [comment] 2016-03-14 19:45
All right - I didn't check the other layers - cycle, transport and humanitarian maps look ok.

**Comment by matkoniecz** [comment] 2016-03-14 20:09
duplicate of #2017

**Comment by matkoniecz** [comment] 2016-03-14 22:51
@HolgerJeromin Thanks for spotting duplicate!

**Comment by pnorman** [comment] 2016-05-18 20:10
re-opening, it's independent of Mapnik version and this ticket is more specific than #2017 

Near https://www.openstreetmap.org/#map=10/28.7112/89.9364

tile 10/767/426
Mapnik 3
![image](https://cloud.githubusercontent.com/assets/1190866/15373285/c3b77a34-1cf9-11e6-98b0-d29731d6c6ff.png)

Mapnik 2
![image](https://cloud.githubusercontent.com/assets/1190866/15373289/cb259ac6-1cf9-11e6-8109-c090fee62e81.png)

**Comment by sommerluk** [comment] 2016-09-16 00:13
> Near https://www.openstreetmap.org/#map=10/28.7112/89.9364

This seems to render okay currently at openstreetmap.org

**Closed** 2016-10-31 02:09 UTC
Labels: general
