### ISSUE TITLE
through traffic restriction rendering

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#1715] opened 2015-08-02 16:20 UTC
Currently it appears the blue dashed line only work with the access=destination and not more specific ones like motor_vehicle=destination.
The destination value should be the factor for when to render blue dashes not the key.

The use of the access=* is also used to much imo. I consider this a blanket key for all access regardless of transportation method.

**Comment by matkoniecz** [comment] 2015-08-03 13:32
duplicate of #214

**Closed by matkoniecz** 2015-08-03 13:32 UTC
