### ISSUE TITLE
Add rendering for barrier=bollard when applied to a way

### ISSUE THREAD

**Issue by ElminsterAU** [gravitystorm/openstreetmap-carto#3073] opened 2018-02-15 15:32 UTC
A way tagged with barrier=bollard should be rendered as a series of dots (same as the single dot that's rendered for barrier=bollard on a node already).

I'm pretty sure at some point in the past (around 2012 IIRC) such ways actually did get rendered in the standard tiles on osm.org as such a dotted line.

**Comment by kocio-pl** [comment] 2018-02-19 17:23
Could you prepare the code to show this effect?

**Comment by eFrysTon** [comment] 2018-02-19 17:39
Unfortunately I so far have zero experience working on openstreetmap-carto and have no environment setup for creating/testing such rendering changes.

I would like to point out that the label "roads" might be wrong here.

You wouldn't normally tag barrier=bollard on a way that also has highway=* (as that would imply that you basically have a series of bollards running in the direction of the road in the middle of it, which seems unlikely)

Instead, you have a way that only represents a line of bollards somewhere, which may or may not be crossing with a road.

It is in nature very similar to having a way tagged with barrier=wall or barrier=fence, the only difference is that it should be rendered as a line of dots (distance could be taken from the maxwidth tag on the way if it exists, otherwise 1m) instead of a solid line.

**Comment by kocio-pl** [comment] 2018-02-19 17:43
So maybe you can learn or find someone who is willing to try, otherwise there are low chances to have this feature in osm-carto.

**Comment by SomeoneElseOSM** [comment] 2018-02-19 18:53
> Unfortunately I so far have zero experience working on openstreetmap-carto and have no environment setup for creating/testing such rendering changes. 

Maybe [this](https://www.openstreetmap.org/user/SomeoneElse/diary/43041) will be helpful?  There's a fair bit to do if you're starting from scratch but the good news is that you can take things step by step and each of the steps is actually quite straightforward.

**Comment by kocio-pl** [comment] 2018-02-19 19:37
You can start with Docker testing environment - I guess it's the easier way to start with testing and you can always ask if you are not sure what to do next:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

**Comment by Tomasz-W** [comment] 2018-10-18 13:29
@kocio-pl Please close this ticket as a duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/1908

**Comment by kocio-pl** [comment] 2018-10-18 21:49
Thanks for spotting it!

**Closed by kocio-pl** 2018-10-18 21:49 UTC
Labels: barrier, duplicate
