### ISSUE TITLE
rendering leisure=resort

### ISSUE THREAD

**Issue by benoit-dd** [gravitystorm/openstreetmap-carto#4521] opened 2022-03-03 12:20 UTC
### Expected behavior
I think that the same rendering as camping would be good (icon+name in blue, green background)
example of a new specific icon:https://cdn.pixabay.com/photo/2015/10/22/16/42/village-icon-1001598_960_720.png (maybe 3 houses are enough :) )

the tag is documented and widely used
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dresort 

### Actual behavior
no rendering of the area and no rendering of the name, no icon.

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/947163160
the resort is not different from the residential area

**Comment by imagico** [comment] 2022-03-03 12:29
Duplicate of #2290.

**Closed by imagico** 2022-03-03 12:29 UTC
