### ISSUE TITLE
Render craft=

### ISSUE THREAD

**Issue by dch0ph** [gravitystorm/openstreetmap-carto#4550] opened 2022-05-14 17:46 UTC
The craft key is used to tag places where goods are created / skills exercised, as opposed to retail (shop=) and large factories (man_made=works). It has been used ~250k times (taginfo), compared to say shop= (over 5m), and has an extensive set of JOSM presets. Currently craft is not rendered, and so mapping areas such as industrial estates is frustrating as nothing appears and units appear vacant. But there are also high-street outlets which are currently not rendered e.g. craft=key_cutter.

There is a strong connection with shop=, e.g. craft=confectionery indicates a site where (primarily) confectionery is made, while shop=confectionery sells confectionery made elsewhere.

It would seem straightforward to extend the machinery of rendering shop to craft, distinguishing the two based on colour; shop uses purple, craft would use a visually distinct colour with the same icon, e.g. the burnt orange colour used to label landuse=farmyard.

In the absence of an icon, a coloured dot would be used in the same way as shop= or office=. This would ensure the name was rendered, which is often sufficient to indicate the nature of the business.

The craft rendering would be prioritised over shop in cases where both tags are present (the wiki suggests that both can be used where goods are both manufactured and sold). Rendering craft would encourage its use to highlight places where original items are made.

This would seem to be a relatively easy win?

**Comment by imagico** [comment] 2022-05-14 18:45
In this generic form this is a duplicate of #1697 - i am therefore going to close it as such.  If you would like to suggest rendering specific craft tags, e.g. `craft=confectionery` please open distinct, concrete issues for that.

What we quite definitely will not want to do is introducing a catch-all rendering for any and all values of `craft=*`.

**Closed by imagico** 2022-05-14 18:45 UTC
