### ISSUE TITLE
Different names on different sides of the road

### ISSUE THREAD

**Issue by sanderd17** [gravitystorm/openstreetmap-carto#1988] opened 2015-12-01 13:04 UTC
In some cases, streetnames can differ by side. This happens mostly when the street also forms an administrative boundary, and the different administrations chose a different name for it. Sometimes only differing at a spelling level, and sometimes completely different.

Some examples:
* http://www.openstreetmap.org/way/49276147 : this way in on a municipal boundary, and both municipalities give completely different names to it
* http://www.openstreetmap.org/way/42942798 : for this way, the municipalities probably used the same name originally, but one thought it would be good to standardise name suffixes, and added a "straat" suffix to the street, resulting in two different names

The current way to solve this is to put something random in the name tag. Like both names concatenated with a hyphen, or combined with a semicolon, or just one name if they resemble each other enough. So the name tag is basically just a fallback to please the renderer and display something to the user. Next to the name tag, we also use name:left and name:right to give the correct name to both sides of the road.

IMO, if both name:left and name:right are present, it would be a lot better not render the name tag, but render the name:left and name:right tags on different sides of the road (as is done with boundary name rendering). 

Regards,
Sander

**Comment by math1985** [comment] 2015-12-01 13:08
Thanks for the report. This seems to be a duplicate of #1735, so I will close this issue - discussion can continue in #1735.

**Closed by math1985** 2015-12-01 13:08 UTC
