### ISSUE TITLE
Nearly junctions / not junctions

### ISSUE THREAD

**Issue by pmailkeey** [gravitystorm/openstreetmap-carto#1509] opened 2015-04-30 11:23 UTC
Road ends - can we have them terminated squarely at the node or half-line-width before the node when close to another road - so that it's clear the terminating road is not connected to the adjacent road ?

**Comment by matkoniecz** [comment] 2015-04-30 12:16
duplicate of unfortunately unfixable #286

**Closed by matkoniecz** 2015-04-30 12:16 UTC
