### ISSUE TITLE
Simplified Chinese characters rendered using Japanese font

### ISSUE THREAD

**Issue by xsgu** [gravitystorm/openstreetmap-carto#2807] opened 2017-09-03 14:30 UTC
Simplified Chinese characters are being apparently rendered using noto for Japanese font, not for Chinese font. This is causing unfamiliar/foreign characters to appear in the Chinese map. 
See for example the following (三门路, Sanmen Road):
![image](https://user-images.githubusercontent.com/8139439/30003853-6479864e-9092-11e7-9ed0-c77290a343f9.png)

or 沪太路, Hutai Road:
![image](https://user-images.githubusercontent.com/8139439/30003862-8e79d750-9092-11e7-9f8a-cbee3fb79180.png)

In the first case, the simplified Chinese character for 门 (meaning door), should look like this:
![image](https://user-images.githubusercontent.com/8139439/30003816-ca201a5e-9091-11e7-90ce-31122bbe1ac4.png) 

However, it currently looks like this: 
![image](https://user-images.githubusercontent.com/8139439/30003820-dbe54110-9091-11e7-9e1a-6818794e4d2b.png)

Similarly, the character for 沪 should look like:
![image](https://user-images.githubusercontent.com/8139439/30003872-c0c0ceda-9092-11e7-9162-115bbe5b46d9.png)

Currently rendered like this (the Japanese version):
![image](https://user-images.githubusercontent.com/8139439/30003879-cf20762e-9092-11e7-95ac-78008fc269cd.png)

There are other examples that I can see just by a quick glance at the Chinese map, but this is the most noticeable one that will affect our Chinese users.

**Comment by sommerluk** [comment] 2017-09-03 16:54
Yes, I know. This problem is tracked at the issue #2208 

Currently, we cannot distingish it and have to render the hole map in either Japanes or Simplified Chinese or Traditional Chinese or Korean.

In short there are two remaining problems that need to be solved:
- We need to know the language that a name has. The problem is that this cannot reliably be determined from the OSM nodes (on a node-by-node basis) because the information in which language the “name” tag is is currently missing. Currently voting is open for a proposal that I have written at http://wiki.openstreetmap.org/wiki/Proposed_features/Language_information to get this language information into the wiki. Support is welcome ;-)
- Support in Mapnik (the rendering engine that we are using) for the OpenType “locl” feature (to select either Japanese or Simplified Chinese or any other language system). The Mapnik team seems to be interested in doing this for the next 3.1 release, so that’s no problem.

**Comment by math1985** [comment] 2017-09-03 21:34
Closing as duplicate.

**Closed by math1985** 2017-09-03 21:34 UTC
Labels: text
