### ISSUE TITLE
highway=pedestrian not shown at z12

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1964] opened 2015-11-08 17:25 UTC
Is this by design? I think it might be worth to display them like highway=residential at this zoom level, otherwise this could lead to effects like this "empty" city centre like in Villach (right below the name label): https://www.openstreetmap.org/#map=12/46.6153/13.8567

![villach_z12](https://cloud.githubusercontent.com/assets/3531092/11021591/81c5736e-8646-11e5-90f4-27bedf61a016.png)

**Comment by matkoniecz** [comment] 2015-11-08 19:52
> Is this by design?

Yes, stopping rendering of pedestrian, living_street, track, footways, cycleways etc at z12 is intentional.

Displaying them like highway=residential would be confusing. In case of changes it would be better to start form/remember about living_street.

**Comment by nebulon42** [comment] 2015-11-08 20:03
> Displaying them like highway=residential would be confusing.

I don't think that would be the case at z12. With "residential" I mean basically the style of "unimportant roads" at z12. At this zoom level the intention for this change would be more to show that something is there, it might be too small to distinguish classes anyway. At z13 pedestrian should of course be rendered distinctly as it is the case already.

**Comment by math1985** [comment] 2015-11-08 20:25
I think the Villach example expresses exactly what is intended: there are no roads (in the sense of roads that you can drive through) there.

**Comment by dieterdreist** [comment] 2015-11-08 20:31
sent from a phone

> Am 08.11.2015 um 20:52 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> Yes, stopping rendering of pedestrian, living_street, track, footways, cycleways etc at z12 is intentional.
> 



I believe this is a bad decision. Typically, in German and other European cities, the "main" pedestrian area is in the city center, and this way we are omitting important streets. Also in Rome there is the Via Appia Antica which is a pedestrian road, and not rendering it at z12 leads also there to a big gap. Btw., this is a regression, was already fixed many years ago.

> Displaying them like highway=residential would be confusing.
> 


they are the same kind of significance, at least, why would it be "confusing "?

**Comment by dieterdreist** [comment] 2015-11-08 20:33
Martin Koppenhöfer
23maps

> Am 08.11.2015 um 21:25 schrieb math1985 <notifications@github.com>:
> 
> I think the Villach example expresses exactly what is intended: there are no roads (in the sense of roads that you can drive through) there.


you are overrating cars with this comment, roads are not only for driving motor vehicles, especially in town centres

**Comment by math1985** [comment] 2015-11-08 20:46
I don't use maps with a distance of 200km from one edge of the screen to the other for pedestrian routing, though. :)

**Comment by polarbearing** [comment] 2015-11-08 21:27
z12? Wow, how large is your screen? :-)

At z12 we could even afford to drop highway=residential as it has not interconnecting function. 
That would give fairness between peds vs cars, and make the landuses more distinguishable by reducing clutter.

**Comment by dieterdreist** [comment] 2015-11-08 23:10
sent from a phone

> Am 08.11.2015 um 21:46 schrieb math1985 <notifications@github.com>:
> 
> I don't use maps with a distance of 200km from one edge of the screen to the other for pedestrian routing, though. :)


have a look here, zoom 1 out
http://www.openstreetmap.org/#map=13/41.8077/12.5642

**Comment by daganzdaanda** [comment] 2016-02-18 10:48
Looking at a few cities in Europe, I think having the pedestrian highways faintly visible at z12 would be OK, probably better than not showing them. In many cases, these areas will be hidden behind the city label anyway. I'd show the pedestrian highways just like other unimportant roads, no need to differentiate. 
As @matkoniecz said, maybe showing living streets at that zoom would not be wrong either.

**Comment by dieterdreist** [comment] 2016-02-18 11:10
2016-02-18 11:48 GMT+01:00 daganzdaanda <notifications@github.com>:

> Looking at a few cities in Europe, I think having the pedestrian highways
> faintly visible at z12 would be OK, probably better than not showing them.




+1, in case of main roads that have become "pedestrianized" it is IMHO a
requirement to show them at that zoom level. The via Appia Antica (see link
above) is another famous example where not rendering these pedestrian roads
leads to a noticable gap.

**Comment by matkoniecz** [comment] 2018-08-07 08:49
#3331 proposed dropping highway=pedestrian also from z13

**Comment by matthijsmelissen** [comment] 2018-10-07 18:04
Z12 is not a zoom level for pedestrian routing. I think showing gaps on the road network at z12 is fine - because these *are* gaps in the road network from a car perspective. Pedestrians/cyclists will rather use the higher zoom levels anyway.

I am therefore going to close this issue.

**Closed by matthijsmelissen** 2018-10-07 18:04 UTC
Labels: roads
