### ISSUE TITLE
problems with rendering of highway=raceway

### ISSUE THREAD

**Issue by rwelty1889** [gravitystorm/openstreetmap-carto#1939] opened 2015-10-31 22:50 UTC
highway=raceway is rendering properly in some cases and not others. it appears to fail when rendering a closed way. the following link is for Lebanon Valley Speedway & Lebanon Valley Dragway; the dragstrip is rendering properly but the oval track is not.

http://www.openstreetmap.org/#map=16/42.4913/-73.4906

**Comment by SomeoneElseOSM** [comment] 2015-10-31 23:15
Sounds like it might be the same as https://github.com/gravitystorm/openstreetmap-carto/issues/854 perhaps?

**Comment by rwelty1889** [comment] 2015-10-31 23:33
it could be related, but this is relatively new. closed ways tagged highway=raceway were rendering properly earlier this year.

**Comment by pnorman** [comment] 2015-11-01 01:46
http://www.openstreetmap.org/way/20068287 has sport=motor, so at least **this** case is a duplicate of #854.

If there's an example without sport=* or another area tag, we can reopen.

**Closed by pnorman** 2015-11-01 01:46 UTC

**Comment by SomeoneElseOSM** [comment] 2015-11-01 09:41
@rwelty1889 (just in case you haven't already seen it) a full explanation of why some might be showing and some not is over at  https://help.openstreetmap.org/answer_link/44502/

**Comment by rwelty1889** [comment] 2015-11-01 20:52
On 11/1/15 4:41 AM, SomeoneElseOSM wrote:
>
> @rwelty1889 <https://github.com/rwelty1889> (just in case you haven't
> already seen it) a full explanation of why some might be showing and
> some not is over at https://help.openstreetmap.org/answer_link/44502/
>
>
thanks. i actually knew about the sport=motor problem, worked
it out a couple of months ago and completely forgot about it.

richard

-- 
rwelty@averillpark.net
 Averill Park Networking - GIS & IT Consulting
 OpenStreetMap - PostgreSQL - Linux
 Java - Web Applications - Search
