### ISSUE TITLE
Add rendering for highway=busway

### ISSUE THREAD

**Issue by kolgza** [gravitystorm/openstreetmap-carto#4373] opened 2021-04-15 14:24 UTC
The proposal for `highway=busway` has been approved, but rendering needs to be added.

https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbusway

Related:  #4226

**Comment by pnorman** [comment] 2021-04-15 15:36
Duplicate of #4226
When usage becomes wider spread we can reopen that issue.

**Closed by pnorman** 2021-04-15 15:36 UTC

**Comment by kolgza** [comment] 2021-04-16 16:52
@pnorman I think it would be appropriate to reopen #4226 now.
![image](https://user-images.githubusercontent.com/46303203/115057907-9cfb1500-9eb2-11eb-93fa-36e2d5e854e8.png)

https://taginfo.openstreetmap.org/tags/highway=busway
