### ISSUE TITLE
New landuse=farmland rendering color too close of amenity=hospital

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#1991] opened 2015-12-04 10:33 UTC
Hello, there.

I noticed a change in the color used to render landuse=farmland; I wasn't able to find references to this change in the last issues or pull requests, but it now seems too close of the amenity=hospital rendering to me: https://www.openstreetmap.org/#map=15/48.2899/6.1141 In this case, I was working on the landuses on this area, and I first thought I mis-modelled the landuses and mixed them with amenity=hospital. Improving the landuse=farmland rendering color, which was somewhat pinkish to me, was a good idea, but now I would say it became confusing.

Regards.

Edit: I found the corresponding pull request, #1701

**Comment by donaldrnoble** [comment] 2015-12-04 10:55
As the same shade of yellow is used for schools and universities, it also affects them. And to me it seems more of an issue at lower zoom levels, even though the same colours are being used. 

![screen shot 2015-12-04 at 10 53 56](https://cloud.githubusercontent.com/assets/6844639/11588001/5c3a11de-9a75-11e5-83b2-37417933a6c0.png)
http://www.openstreetmap.org/#map=14/55.9084/-3.3080

**Comment by polarbearing** [comment] 2015-12-04 23:58
This could be solved if we eventually switch to boundary-rendering for amenities as in #1624.

**Comment by Vort** [comment] 2015-12-05 05:41
Also farmland now is one of the brightest things, attracting attention like it is the most important feature on the map.

**Comment by mboeringa** [comment] 2015-12-05 09:31
> As the same shade of yellow is used for schools and universities, it also affects them. And to me it seems more of an issue at lower zoom levels, even though the same colours are being used.
> 
> screen shot 2015-12-04 at 10 53 56
> http://www.openstreetmap.org/#map=14/55.9084/-3.3080

Personally, looking at these to examples on my color calibrated screen, I see no real problem. The distinction in colour is still clearly visible, and the amenities stick out by their prominent - impossible to miss - labelling and icons.

> This could be solved if we eventually switch to boundary-rendering for amenities as in #1624.

\+ 1, for quite a lot of amenities, if not all, this would be appropriate (exception of course for additionally tagged as building). In fact, I have done this for many of these features in my personal ArcGIS renderer.

**Comment by imagico** [comment] 2015-12-05 11:28
On a general note: with changes like this which have a huge influence on the overall impression of the map - we had similar changes like those of wood and grass colors before - it is always good to take a few days to let it settle and try to look at it without bias.  Being used to the old rendering we tend to have a more negative impression of changes because they are less intuitive to us at first.

That being said - yes, similarity to hospital/education is strong but there is not much room here.  In the process (#1701, #1691) several options were considered and each of them has its problems.  So those who are dissatisfied with the new color should think in alternatives and try out if these are really better overall - not only with respect to hospital/education but also to other similar colors.

Here is the current area color set so you can see the various problems:

![area colors](http://www.imagico.de/files/carto-areacolors.png)

My current opinion is i like the new color, especially since it encourages mapping other things than farmland.  In the sample area shown above for example urban landuses are largely missing which is well visible as a problem.  With the previous color urban areas not mapped with landuse were actually better visible than with which essentially discouraged proper mapping.  The new color looks much more pleasant with fine grained farmland mapping and less so with coarse large farmland polygons which is just the right direction.

I would probably consider improving contrast with hospital/education to be more a matter of tuning that color than of modifying farmland.

**Comment by Vort** [comment] 2015-12-05 12:47
All yellow-orange group can be balanced I think.

**Comment by kocio-pl** [comment] 2015-12-05 13:03
Somebody [has already proposed](https://lists.openstreetmap.org/pipermail/dev/2015-December/028959.html) farmland color tuning with #faebd7 (Antique white). I can even make a mockups, but I just don't know how to calculate @farmland-line.

**Comment by Vort** [comment] 2015-12-05 13:10
1/255 of intensity is not a big change.

**Comment by math1985** [comment] 2015-12-05 13:22
> I just don't know how to calculate @farmland-line.

I don't think we have a systematic way to calculate that, I'd say just do what looks nice :)

Now the farmlands are brighter, I think grass should be brighter too, at least at low zoom: http://www.openstreetmap.org/#map=14/51.8470/4.2284

**Comment by imagico** [comment] 2015-12-05 14:45
> Now the farmlands are brighter, I think grass should be brighter too, at least at low zoom

I was thinking about swapping campsite and grass colors although the resulting difference between grassland and heath seems somewhat large.

In general it seems the fairly ugly appearance of the Netherlands at z10/11 is mostly due to the distorting color mixing and not due to the actual colors chosen.

**Comment by math1985** [comment] 2015-12-05 21:03
> the distorting color mixing 

What do you mean with that?

**Comment by imagico** [comment] 2015-12-05 21:32
The old Mapnik/AGG issue with pixels partially covered by multiple polygons that also causes the gaps.  Illustrated this in the context of gamma tuning in #1117.

AGG renders by drawing one polygon after the other and if multiple polygons intersect the same pixel it does not remember which part of the pixel was covered by the first polygon when drawing the second.  Therefore the rendered color at low zooms where most pixels are mixed color from several polygons is quite far from the color that would correspond to the actual coverage fractions of the pixel.

**Comment by Tomasz-W** [comment] 2018-09-03 05:57
@kocio-pl It's resolved by https://github.com/gravitystorm/openstreetmap-carto/pull/3327, please close.

**Comment by kocio-pl** [comment] 2018-09-03 07:15
Are you sure? We just switched colors basically.

**Comment by kocio-pl** [comment] 2018-09-03 08:34
See the example area with new colors - the problem is with both colors being similar and not one big area for school and the other one for the farmland, they're both mixed a bit:

![_tkhpguz](https://user-images.githubusercontent.com/5439713/44976223-e3e7a680-af64-11e8-8c64-4ce2f9dbadec.png)

**Comment by Tomasz-W** [comment] 2018-09-03 08:46
I think that adding outlines for these campuses would fix it.

**Comment by kocio-pl** [comment] 2018-09-03 08:57
What do you mean more precisely?

**Comment by Tomasz-W** [comment] 2018-09-03 10:11
Showing amenity area borders (above the landcover) may clear the view.

**Comment by Tomasz-W** [comment] 2018-09-03 11:09
I find previous farmland colour to dark for using it for amenity fill. Please see examples how bad (too prominent) it will look in urban areas. 

I did some Photoshop mock-ups with lighter (what makes it more neutral) #FFFAF2. Please spotlight matching of both colour with parking areas which are very often present on amenity areas. I think  #FFFAF2 matches with them better.

University area mixed with farmland (farmland colour)
![44976223-e3e7a680-af64-11e8-8c64-4ce2f9dbadec](https://user-images.githubusercontent.com/25656654/44983306-07b4e780-af79-11e8-8d26-55d58d8b9fb8.png)
University area mixed with farmland (#FFFAF2)
![a1-2](https://user-images.githubusercontent.com/25656654/44983307-084d7e00-af79-11e8-9216-bd528e3c07f9.jpg)
City example (farmland colour)
![a2-1](https://user-images.githubusercontent.com/25656654/44983308-084d7e00-af79-11e8-912a-23e1be23b0d3.jpg)
City example (#FFFAF2)
![a2-2](https://user-images.githubusercontent.com/25656654/44983310-084d7e00-af79-11e8-87d8-2c2cac2a2598.jpg)
Hospital area (farmland colour)
![a3-1](https://user-images.githubusercontent.com/25656654/44983311-084d7e00-af79-11e8-80b7-a6d0fd58d926.jpg)
Hospital area  (#FFFAF2)
![a3-2](https://user-images.githubusercontent.com/25656654/44983313-084d7e00-af79-11e8-82e9-61c2e4fea537.jpg)

**Comment by kocio-pl** [comment] 2018-09-04 02:11
I don't feel convinced, however I still don't like this bright peach color and prefer to tune it eventually. #FFFAF2 is too close to the land color, there's no visible difference for me:

https://github.com/gravitystorm/openstreetmap-carto/blob/5fd79b7bfad1d895c543e52838c65657fcd9fe1a/style.mss#L6

**Comment by Tomasz-W** [comment] 2018-09-04 06:17
Just as my free tests for reference point and compare - the same amenity fill colour with #eeeeee (parking colour) as land colour.

![amenity](https://user-images.githubusercontent.com/25656654/45013201-92015800-b01a-11e8-82a0-ba0d951c7956.jpg)
![amenity2](https://user-images.githubusercontent.com/25656654/45013202-9299ee80-b01a-11e8-9080-5ba2b61c3f66.jpg)

**Comment by Tomasz-W** [comment] 2018-09-21 18:01
Further amateur Photoshop test, this time with a little bit yelowish #FFFCEB (I started playing with former parking fill colour and makie it more pale)

![amenity1](https://user-images.githubusercontent.com/25656654/45897741-48658b00-bdd8-11e8-8a33-a01d5b892d08.jpg)
![amenity2](https://user-images.githubusercontent.com/25656654/45897742-48658b00-bdd8-11e8-915e-f9bc9d35aa66.jpg)
![amenity3](https://user-images.githubusercontent.com/25656654/45897743-48658b00-bdd8-11e8-9016-1b7226dc8d7a.jpg)

I think it's not too close to farmland colour (see example no. 1) and not too close to land colour (see example no. 2). I see it also not too pale and not too bright. @kocio-pl What do you think?

**Comment by kocio-pl** [comment] 2018-09-21 18:14
Looks nice for me - if it will work, I would be happy to use it instead of this peach bright orange...

**Comment by Tomasz-W** [comment] 2018-09-22 06:29
@Adamant36 Can you make some more normal test renderings (including well-mapped-areas, isolated amenity areas, areas surronded by different landcover etc.) with #FFFCED?

**Comment by Adamant36** [comment] 2018-09-22 06:46
@Tomasz-W, yeah sure. I was actually just thinking about doing that.

**Comment by Tomasz-W** [comment] 2018-09-22 07:57
Btw. @Penegal or @kocio-pl you can swich tags in issue name as it's not up to date and may confuse people ;)

**Comment by kocio-pl** [comment] 2018-09-22 07:59
Why? It's still true. Or I miss something?

**Comment by Tomasz-W** [comment] 2018-09-22 08:00
This name suggest a little bit that we are working on landuse=farmland colour, but we are working more on amenity=hospital colour.

**Comment by kocio-pl** [comment] 2018-09-22 08:02
I don't see the problem - they are still too close and we can fix it in multiple ways.

**Comment by Adamant36** [comment] 2018-09-23 06:54
@Tomasz-W, which color are we going with here? It looks like you tried like three of them.

**Comment by Adamant36** [comment] 2018-09-23 06:55
By "going with" I mean testing.

**Comment by Adamant36** [comment] 2018-09-23 07:33
![download](https://user-images.githubusercontent.com/30259065/45925337-3e22ba00-bec8-11e8-8022-88ec775b2b2f.png)
![download 1](https://user-images.githubusercontent.com/30259065/45925338-3e22ba00-bec8-11e8-82da-d268f34661f3.png)
![download 2](https://user-images.githubusercontent.com/30259065/45925339-3e22ba00-bec8-11e8-805d-510819429191.png)
![download 3](https://user-images.githubusercontent.com/30259065/45925340-3ebb5080-bec8-11e8-905b-acd62a375fa9.png)
![download 4](https://user-images.githubusercontent.com/30259065/45925341-3ebb5080-bec8-11e8-8350-190fbd4dec87.png)
![download 5](https://user-images.githubusercontent.com/30259065/45925342-3f53e700-bec8-11e8-809c-55475a2c80f5.png)
![download 6](https://user-images.githubusercontent.com/30259065/45925343-3f53e700-bec8-11e8-97e0-90e3a7f1e6d6.png)
![download 7](https://user-images.githubusercontent.com/30259065/45925344-3f53e700-bec8-11e8-811b-7e271138641e.png)
![download 8](https://user-images.githubusercontent.com/30259065/45925345-3fec7d80-bec8-11e8-8506-d84b414b24a2.png)
![download 9](https://user-images.githubusercontent.com/30259065/45925346-3fec7d80-bec8-11e8-914c-a580d75554e9.png)
![download 10](https://user-images.githubusercontent.com/30259065/45925347-3fec7d80-bec8-11e8-937a-e38174a448f4.png)
![download 11](https://user-images.githubusercontent.com/30259065/45925348-40851400-bec8-11e8-97eb-d3aa13445120.png)
![download 12](https://user-images.githubusercontent.com/30259065/45925349-40851400-bec8-11e8-9090-89cf3478b06f.png)
![download 13](https://user-images.githubusercontent.com/30259065/45925350-411daa80-bec8-11e8-8900-d9c2e99d55c9.png)
![download 14](https://user-images.githubusercontent.com/30259065/45925351-411daa80-bec8-11e8-9a30-b6b8850f28a3.png)
![download 15](https://user-images.githubusercontent.com/30259065/45925352-411daa80-bec8-11e8-9623-cb30568ffbf0.png)
![download 16](https://user-images.githubusercontent.com/30259065/45925353-41b64100-bec8-11e8-8165-be5b1dbb8a74.png)

**Comment by Adamant36** [comment] 2018-09-23 08:58
![download 17](https://user-images.githubusercontent.com/30259065/45926138-294c2380-bed4-11e8-8e4b-b7c05e881626.png)
Looks really good.

**Comment by Adamant36** [comment] 2018-09-23 23:27
Should I do a PR for it?

**Comment by kocio-pl** [comment] 2018-09-23 23:28
Yes, I think so.

**Comment by Tomasz-W** [comment] 2018-09-24 05:59
@Adamant36 Where is the PR for this issue? Or is it needless here for some reason?

**Comment by Tomasz-W** [comment] 2018-09-24 06:44
@Adamant36 Where is the PR for this issue? Or I don't know something and it's needless here?

**Comment by Adamant36** [comment] 2018-09-24 06:57
@Tomasz-W, sorry. I was working on it a while ago, but I had to reload Docker and Kosmtik for some reason. Unfortunately, its been stuck at re-importing the shape file for like an hour. Its in the process though. So hopefully I can do it any minute now.

**Comment by matthijsmelissen** [comment] 2018-09-25 08:15
Can we close this issue now?

**Comment by kocio-pl** [comment] 2018-09-25 09:53
PR fixing it is on the way, but it's not done yet.

**Closed** 2018-10-08 16:37 UTC
Labels: landcover

**Comment by dktue** [comment] 2018-10-19 19:11
Now that this is online I don't really like it. The contrast with buildings is just too high, it hurts in the eye.

**Comment by Adamant36** [comment] 2018-10-20 01:05
@dktue, it could be darkened a little. That might put it to close to other colors though, like farmland.
