### ISSUE TITLE
add line rendering for benches 

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#1890] opened 2015-10-03 09:01 UTC
As reported in #1824

Some benches are tagged as lines 
http://www.openstreetmap.org/way/313487068
http://www.openstreetmap.org/way/79639567
http://www.openstreetmap.org/way/79639568

**Comment by pnorman** [comment] 2015-10-03 11:07
I can't think of any way to render them except for sticking the bench symbol somewhere on the linestring.

Surprisingly, there are about 3k benches mapped as lines.

**Comment by HolgerJeromin** [comment] 2015-10-03 11:49
you are right, this is a problem. But i think the symbol in the middle is a good enough solution.

**Comment by jojo4u** [comment] 2015-10-03 11:54
Tagging as way  is allowed in wiki since 2011 and makes sense for long ones. Symbol in middle sounds reasonable.

http://wiki.openstreetmap.org/w/index.php?title=Tag:amenity%3Dbench&oldid=705902

**Comment by NonnEmilia** [comment] 2017-01-13 05:55
Now the benches mapped as line are 7k (according to [taginfo](https://taginfo.openstreetmap.org/tags/?key=amenity&value=bench)).

**Comment by Tomasz-W** [comment] 2017-07-27 17:00
I would like to see some examples of bench ways rendered as brown lines

**Comment by kocio-pl** [comment] 2017-07-27 17:30
That would probably look like tracks, isn't it?

**Comment by pnorman** [comment] 2017-07-27 18:20
I don't see how it would be obvious to someone that a brown line means a bench line, particular given the confusion with existing brown lines.

**Comment by Tomasz-W** [comment] 2017-07-27 18:41
Well, if it would be thick as barrier=city_wall (eg. http://www.openstreetmap.org/way/363795561) or thicker, and dark-brown, it propably wouldn't be that bad and wouldn't confused with tracks. Notice that a lot of things on map are obvious from the context. Like always, a rendering preview is the only way to check how it works...

**Comment by Tomasz-W** [comment] 2018-07-15 13:11
@kocio-pl Please close this ticket as a duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/2711 meta ticket. Move further discussion there.

**Closed** 2018-07-15 13:12 UTC
Labels: amenity-points
