### ISSUE TITLE
Render name on place=neighbourhood polygons

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#4090] opened 2020-03-23 12:13 UTC
Currently place=neighbourhood polygons don't have name rendering unless they are also tagged with landuse=residential. Which seems like a workaround and bad tagging because it involves tagging landuse areas inside other landuse areas if you want neighbourhood names to render. Since there can be multiple neighbourhoods inside a residential area. Plus, like the Wiki says, neighbourhoods can be a mix of different landuses. So not rendering place=neighbourhood names on polygons encourages bad tagging practices. 

Possibly related to #2816 since it was mentioned there, but that issue is about rendering larger aras like place=village and similar tags. Which are different then neighbourhoods and have harder to determine boundaries IMO.

**Comment by jeisenbe** [comment] 2020-03-23 14:53
This is a duplicate of #103

**Closed** 2020-03-23 16:46 UTC
Labels: duplicate

**Comment by Adamant36** [comment] 2020-03-24 01:22
How so? That was similar to the other issue in that it wasnt specific to neighbourhoods and inovolved larger areas with less definable boundaries like place=sattelement. Place=neighbourhood was only brought up a few times in it and known responded to anyone. In no does an issue about different tags where this one in only mentioned twice make this a duplicate of that one. Anymore then it would make every issue about icons a duplicate of the icon rendering issue or every issue about something to do with waterways a duplicate of a closed issue about bays. Or can we not have new issues about specific tags anymore just because similar ones where rejected?

**Comment by jeisenbe** [comment] 2020-03-24 02:56
#103 also requests rendering on place=* settlement polygons, including place=neighborhood in addition to =quarter, =suburb, =village, =hamlet, =town, =city. And the linked PR addressed all of these. If we only render place=neighborhood lables on areas, but not other parts of settlements like place=quarter and place=suburb, this will be confusing to mappers and lead to requests to render the others, and that will lead to request to render place=town, place=village etc (since the distinction between a town and a suburb is vague).

Two PRs about this were rejected:  #2816 (as mentioned above) and also #2939 (which would only render settlement place nodes on areas if there is no node with the same tags inside). 

Comments in the first PR=: 
- https://github.com/gravitystorm/openstreetmap-carto/pull/2816#issuecomment-328308294
- https://github.com/gravitystorm/openstreetmap-carto/pull/2816#issuecomment-328333053
- https://github.com/gravitystorm/openstreetmap-carto/pull/2816#issuecomment-328333664
- https://github.com/gravitystorm/openstreetmap-carto/pull/2816#issuecomment-451648350 (mentions place=suburb and place=neighborhood)
 - https://github.com/gravitystorm/openstreetmap-carto/pull/2816#issuecomment-451686985

See these comments in the second PR:
- https://github.com/gravitystorm/openstreetmap-carto/pull/2939#issuecomment-343258037
- https://github.com/gravitystorm/openstreetmap-carto/pull/2939#issuecomment-343309777
- https://github.com/gravitystorm/openstreetmap-carto/pull/2939#issuecomment-343344048
- https://github.com/gravitystorm/openstreetmap-carto/pull/2939#pullrequestreview-75718084
- https://github.com/gravitystorm/openstreetmap-carto/pull/2939#issuecomment-387222949

I believe most of these concerns apply equally to place=neighborhood as to place=village or place=town. Also see the discussion in the previous issue #103 for more. 

I don't think there is consensus to render this features when mapped as an area. 

It is normal to map boundary=administrative areas which might be the same as the neighborhood, and we do render these. Unfortunately in the USA the sub-city admin levels are poorly developed, so this solution does not work as well, but because of this, the names and areas of neighborhoods are undefined in many American towns and cities, making their areas non-verifiable.

**Comment by jeisenbe** [comment] 2020-03-24 05:39
I check the current use of place=neighbourhood in several regions:
https://wiki.openstreetmap.org/wiki/Talk:Tag:place%3Dneighbourhood#Review_of_usage_on_areas

Out of 14 places, only the 2 States in the USA, and Uruguay, had a significant number of areas mapped with place=neighbourhood, but even there nodes are more common, and most of the areas are landuse=residential areas or sometimes administrative boundaries. In most places I checked, I found that only nodes were used.

**Comment by Adamant36** [comment] 2020-03-24 06:37
Because names on areas aren't rendered and names on nodes are. So there's no incentive to map them as areas. It says on the Wiki that they can be rendered that and its an improved tag with 40,000 uses as lines. So I dont see what the problem is. Especially since your recomending boundary=administrative be used instead. Which has the same issues but is still rendered. You should support what the community wants and approves instead of picking and chosing. Or just dont render anything that has the problem. Maybe you could at least compromise by making name rendering on polygons dependent on being a relation with nodes like it is with admin boundaries. I dont think anyone would have a problem with that and then it wouldnt be favoring one scheme over another.

**Comment by imagico** [comment] 2020-03-24 12:26
Note as mentioned in https://github.com/gravitystorm/openstreetmap-carto/pull/2816#issuecomment-451998593 many polygons with place=neighbourhood tag also have a landuse or an administrative boundary tag.

At the moment of the 52k features >29k have a landuse tag and nearly 10k have an administrative boundary tag.

Emphatic :+1: on not re-iterating the discussion from #103.

**Comment by Adamant36** [comment] 2020-03-24 13:26
> Emphatic +1 on not re-iterating the discussion from #103. 

No supprise there. Its already pretty clear what your opinion on this type of thing is. 

Would it at least be possible to get rid of the border around landuse=residential when its co-tagged with place tags since mapping them that way would involve "nesting landuse" and sometimes places dont have clear boundaries (the Wiki doesnt require them to)? It would be wrong to render a border arbitary for something and it just looks wierd having a random border inside a landuse area. It might be confused for a fence or something.

**Comment by jeisenbe** [comment] 2020-03-24 14:54
> get rid of the border around landuse=residential when its co-tagged with place tags

That would be a separate issue

>  mapping them that way would involve "nesting landuse"

What do you mean? Each landuse=residential area can be mapped as a separate closed way or multipolygon to represent the area. The area would represent the actual residential area, which might be surrounded by a fence or wall, or just streets + other features on some sides. 

Looking at Shasta County, it looks like there are already many "subdivisions", "housing developments" and apartment complexes mapped as landuse=residential areas with the name of the housing area. This looks fine.

There is also the older tag place=suburb for slightly larger sections of a town or city, bigger than a neighborhood, and even place=quarter for big cities which need 3 levels of subdivisions.

**Comment by Adamant36** [comment] 2020-03-25 07:10
> What do you mean? Each landuse=residential area can be mapped as a separate closed way or multipolygon to represent the area.

From my understanding not within another landuse=residential area though. Otherwise, your double mapping it over the larger one. Like if you mapped a mall as building=retail and then a store inside of it as another building=retail area or something. 

>Looking at Shasta County, it looks like there are already many "subdivisions", "housing developments" and apartment complexes mapped as landuse=residential areas with the name of the housing area.

Yeah, but I'm not a big fan of it or anything for the reason I stated. Like with these two apartment complexes it look like they have a barrier around them when they don't have one due to the border. Although it is lighter then the fences, but it could still confuse people in cases where there isn't a fence to compare the lighter shade to. Also, the Wiki says not to use landuse=residental to make things at the parcel level. So, I'm not a big fan of it because of that either. 
![Apartments](https://user-images.githubusercontent.com/30259065/77509303-b786ca00-6e29-11ea-8b3d-41597d609383.png)

> That would be a separate issue

I think it's related as far tagging places as residential landuse like you recommend to make the label render would give the false impression of a border that might not exist (although that could go for landuse=residential areas in general I guess). Which wouldn't be an issue if the label where just rendered on places mapped as areas. Plus, the Wiki explicitly says not to use landuse=residential "as additional tag for urban administrative units."

My calculation here is what's better, rendering labels on place=neighbourhood even though there areas might not be 100% precise in some cases, or using a non-approved work around, that leads to mapping residential areas inside of other ones (plus gives the impression of a border that might not exist and could potentially be confused with a barrier) just so the name will render? Neither one is great, but the first option seems like the better option to me. Especially since like I said already the Wiki explicitly says not use landuse=residential "as additional tag for urban administrative units."

It's also worth mentioning that 414,719 uses of landuse=residential are tagged with the name tag. While there's only 6,190 uses of landuse=residential tagged on places. I'm pretty sure a good percent of those 414,719 landuse=residential areas with names would better be tagged as place=whatever, but aren't because of the lack of name rendering and because you aren't suppose to map landuse=residential by adding it to the place or boundary=administrative tags.

**Comment by Adamant36** [comment] 2020-03-25 07:25
Btw, my thing above is why I think this is a issue specific place=neighbourhood and that it should be considered separately from other places, because place=village isn't wrongly being tagged as landuse=residential to make the name render and people aren't recommending it be tagged that way against the recommendation of the Wiki article for landuse=residential like is being done in this case.

**Comment by siliconninja** [comment] 2020-05-17 14:35
@Adamant36 I understand your reasoning. I can see advantages and disadvantages for including the name.

If the label was on the map, it's handy to have so people know the different neighborhoods. However, it would look a little cleaner if the label wasn't on the map (especially if there are a lot of overlapping neighborhoods and other subdivisions of a town).

I wouldn't draw a grey box and border around it the same way as landuse=residential which is ok because the issue is related to rendering names on the map.

> It is normal to map boundary=administrative areas which might be the same as the neighborhood, and we do render these.

I wonder if it would be a fair compromise to render neighborhood tags like boundary=administrative tags, but use a different color (like blue instead of purple?) and show the borders of each neighborhood.

> that leads to mapping residential areas inside of other ones (plus gives the impression of a border that might not exist and could potentially be confused with a barrier)

From what you're saying, the tricky thing about having a neighborhood have a border like an administrative area is it looks like a "border" that might not exist for neighborhoods. But there is usually a well defined border for neighborhoods with areas, according to the wiki.

The current process on the [wiki (under How to Map > Node or Area?)](https://wiki.openstreetmap.org/wiki/Tag:place%3Dneighbourhood) has you draw an area and add another center node for the neighborhood. I think this is very convoluted, and I could argue that adding another tag to somewhere near the center to look good is "mapping for the renderer".
Here's an idea to render the label of the area better: We could have some sort of algorithm to figure out where to place the label (in the center but not on top of any houses), so at higher zoom levels, you wouldn't see the neighborhood name on top of anything, to make it less confusing.

But the name is already included if we tag the center node according to the wiki, so making areas render with just the name wouldn't change very much.

**Comment by Adamant36** [comment] 2020-05-21 01:22
> The current process on the wiki (under How to Map > Node or Area?) has you draw an area and add another center node for the neighborhood. I think this is very convoluted

It also goes against the "One feature, one OSM element" rule IMO. Plus, it's ridiculous that if you search for a location you get two results that way and they often have different tags. Like sometimes the node is tagged as a hamlet but the area is tagged as a city. Or the node will include Wikipedia tags etc but the area won't. It unnecessarily turns the whole thing into a crap shot, and makes it so people either get bad information or non at all.
