### ISSUE TITLE
Empty tile error message during generating tiles with: generate_tiles.py

### ISSUE THREAD

**Issue by zsoooc** [gravitystorm/openstreetmap-carto#3091] opened 2018-02-26 12:37 UTC
I have a problem while generating tiles with generate_tiles.py. It writes randomly "empty tiles" on the log during the process (zoom level 15). It seems that it is totally random and not connected to a geographic area (I loaded a full country pbf to postgis, and now generate tile to a subset). I checked these tiles and they are really empty.
Screenshot:
https://uploads.disquscdn.com/images/2981f3445a10fad61058bb799369fed1608757a8fd9e9e45a92eca74b9838cde.jpg

**Comment by StyXman** [comment] 2018-02-26 14:13
This is not a bug in osm-carto, and I would even sty it's not even a bug. This is how `generate_tiles` reports that a tile has no other features but and plain color background. It's mostly associated to empty sea tiles, but it could be any tile with nothing more than the white background or a plain landuse color, for instance.

**Comment by kocio-pl** [comment] 2018-02-26 14:27
So I will close this issue as an external problem.

**Closed by kocio-pl** 2018-02-26 14:27 UTC
