### ISSUE TITLE
Highway=pedestrian + area=yes means no geography drawn inside it is rendered

### ISSUE THREAD

**Issue by picsi** [gravitystorm/openstreetmap-carto#2563] opened 2017-02-03 22:42 UTC
Example: https://www.openstreetmap.org/#map=19/-23.00821/-43.30419

There are two buildings here, a church and a flowershop, but neither is rendered because `highway=pedestrian` + `area=yes` hides them. Anything mapped on top of a `highway=pedestrian` should be shown on top.

**Comment by aceman444** [comment] 2017-02-03 23:09
If you do not want that to happen you need to exclude the buildings from the pedestrian area. Use a multipolygon and add the buildings as members with "inner" role.

**Comment by picsi** [comment] 2017-02-03 23:19
@aceman444 Yes, that's the current workaround, but it's a hassle to create relations just for that. It should be intuitively logical that a building over a pedestrian area would be mapped on top of the pedestrian area, wouldn't you say?

**Comment by aceman444** [comment] 2017-02-03 23:27
Not always, the building could be underground. But the default is probably on-ground :)

**Comment by picsi** [comment] 2017-02-03 23:39
Yeah, I can only really see it happening if the building had `level=-1`

**Comment by HolgerJeromin** [comment] 2017-02-04 21:55
Cutting the building out of the area is the right way to do it. 
Think about a routing engine. Should this direct you around the building or should it ignore the building and force you through the building?

**Comment by picsi** [comment] 2017-02-04 22:27
A routing engine should absolutely notice a bulding on the sidewalk, shouldn't it?

**Comment by pnorman** [comment] 2017-02-05 01:39
duplicate of #688

**Closed by pnorman** 2017-02-05 01:39 UTC
Labels: duplicate

**Comment by HolgerJeromin** [comment] 2017-02-05 10:25
@picsi Most routing engine do not detect "free flowed" (not connected) buildings in the middle of an area.
