### ISSUE TITLE
Zoom Level 5: different rendering at Longitude 0

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#2955] opened 2017-11-23 11:48 UTC
Hi
Any specific reason why at zoom level 5 there's a different rendering either side of Longitude 0? 
I've refreshed the cache & AFAIR it's been like this for a while.
![image](https://user-images.githubusercontent.com/9528328/33171415-eb17baae-d043-11e7-814b-3c5abda8f1e2.png)

I guess this has bee noticed previously but find no posts about it.

**Comment by sommerluk** [comment] 2017-11-23 12:05
Cannot reproduce this:

![screenshot 1](https://user-images.githubusercontent.com/6830724/33172030-761b9600-d046-11e7-8b8e-0ae87a7b612c.png)

Maybe one of the tileservers is more slowly with re-rendering than others…

**Comment by SomeoneElseOSM** [comment] 2017-11-23 12:15
For info I'm seeing the effect and a.tile.openstreetmap.org resolves to:

Non-authoritative answer:
Name:    london.tile.openstreetmap.org
Address:  185.73.44.30
Aliases:  a.tile.openstreetmap.org
          tile.geo.openstreetmap.org
          gb.tile.openstreetmap.org

It's surely just a (temporary) operational issue though.

**Comment by math1985** [comment] 2017-11-23 13:19
As it's an operational issue and not something with our close, I'm closing the issue here. Please continue discussion at https://github.com/openstreetmap/chef/issues/138.

**Closed** 2017-11-23 14:20 UTC
