### ISSUE TITLE
Render area:footway

### ISSUE THREAD

**Issue by ZeLonewolf** [gravitystorm/openstreetmap-carto#4316] opened 2021-02-02 04:00 UTC
Recently, there have been a series of edits on foot paths in Washington, DC.  (See the history of: 
https://www.openstreetmap.org/relation/12194017)

In summary, the area of these footpaths were tagged `highway=pedestrian` + `area=yes`, presumably because that combination currently renders in Carto.  However, the area of foot paths are not correctly tagged `highway=pedestrian` based on the wiki description of this tag.  On review of the wiki, it seems like `area:highway=footway` is the best available option for tagging the area around footways.  However, this tag does _not_ render in Carto.

I suggest that the tag `area:highway=footway` ought to render in the same style as `highway=pedestrian` + `area=yes`.  This will provide a rendering tag for footway areas and discourage inappropriate usages of `highway=pedestrian`.

**Comment by ZeLonewolf** [comment] 2021-02-02 04:04
Showing difference between rendering footway areas and current behavior (based on partial tile refresh):
![image](https://user-images.githubusercontent.com/3254090/106550689-a2ff6d80-64e1-11eb-977e-21b8f6b69f9f.png)

**Comment by 501Ghost** [comment] 2021-02-02 04:21
A side-effect of this is that it encourages people to map more area:footway because it will render nicely, but I don't think that's what we want. We want to encourage people to spend their time mapping more interesting things.

**Comment by jeisenbe** [comment] 2021-02-02 04:23
@ZeLonewolf this is a partial duplicate of #180 which requested rendering of all `area:highway=` features way back in Sep 2013, and was closed as declined. This comment explains why most concisely: https://github.com/gravitystorm/openstreetmap-carto/issues/180#issuecomment-249563060 

The request has been made a couple of other times, e.g. #1483, but it remains not feasible technically once we consider what will happen with bridges and tunnels

**Closed by jeisenbe** 2021-02-02 04:23 UTC
Labels: duplicate

**Comment by 1ec5** [comment] 2021-02-03 22:00
Are the technical and stylistic considerations still significant if `area:highway=pedestrian` is treated as an alias of `highway=pedestrian` `area=yes` but other `area:highway` values continue to be unsupported? Seems like any issue around layers and bridges already affects pedestrian areas anyways.

**Comment by imagico** [comment] 2021-02-03 23:44
The main consideration speaking against that is the lack of a viable long term strategic concept behind the idea.

All of the issues with rendering `area:highway=*` in general of course also apply to rendering `area:highway=pedestrian`.  Some of them already cause problems with existing rendering of highway areas (see #529, #2046 and #3872 in particular).

There are also still very unclear semantics about the whole `area:highway` mapping concept.  When the idea was originally developed some wanted there to be a 1:1 relationship between linear highway ways and area:highway polygons.  But some think that an area:highway polygon can - like in the example linked to above - also correspond to dozens of linear highways with complex topology.  If and how tunnel and bridge tagging should be applied to area:highway polygons is also something where there seems to be no agreement on.  Taginfo shows 385 area:highway features with a bridge tag and 152 with a tunnel tag (of 170k features in total).  So this is not a common practice.  Does that mean the polygons should inherit the bridge/tunnel status from the linear highways?  But that would require the mentioned 1:1 relationship - which is practically not maintained either.

Finally we would not want to incentivize mappers to manually buffer the linear highways to map constant width roads/paths so if we would want to render area:highway polygons we definitely would want to equally render roads with a width tag in their ground unit width at higher zoom levels - which is technically challenging as well and would require revising the decision on ground unit rendering (#1290).
