### ISSUE TITLE
Double rendering name  for some features on buildings

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#3780] opened 2019-05-10 00:21 UTC
Probably regression after #3712, which was replacing centroid algorithm for amenities from the one used by current Mapnik to PostGIS `ST_PointOnSurface`.

### Expected behavior
When building contains some feature we render, the name should be rendered only for this feature.

### Actual behavior
A name can be rendered both for the feature and for the building in different places if the shape is non-trivial.

### Links and screenshots illustrating the problem
[Example](https://www.openstreetmap.org/relation/2965344) with `amenity=library`+`building=*`+`name=*`:

![Screenshot_2019-05-10 OpenStreetMap Carto — Kosmtik](https://user-images.githubusercontent.com/5439713/57494100-2b7abb00-72c8-11e9-8b01-24891cfabe49.png)

### Proposed solutions

Possible solutions might be:
1. Remove selecting buildings for name rendering when they share the geometry with amenity tag.
2. Pass the building name rendering also to PostGIS.

**Comment by kocio-pl** [comment] 2019-05-10 00:39
The same problem with office+building combinations with non-trivial shapes (the one with almost square shape renders properly):

![Screenshot_2019-05-10 OpenStreetMap Carto — Kosmtik(1)](https://user-images.githubusercontent.com/5439713/57495098-cf666580-72cc-11e9-8b5d-9bc8baf15c1d.png)


[ https://www.openstreetmap.org/way/35008161 ]

**Comment by kocio-pl** [comment] 2019-05-10 01:58
The same with [`historic` example](https://www.openstreetmap.org/way/249395313), so there are more tags with this problem probably.

**Comment by pnorman** [comment] 2019-05-10 04:35
We'll need to move building names to st_pointonsurface too

**Comment by kocio-pl** [comment] 2019-05-10 04:39
What about limiting building name rendering? Wouldn't it make the database response smaller (and maybe faster)?

**Comment by pnorman** [comment] 2019-05-10 04:51
> What about limiting building name rendering? Wouldn't it make the database response smaller (and maybe faster)?

What do you mean?

**Comment by kocio-pl** [comment] 2019-05-10 04:59
Database query for rendering building name could just exclude the cases when there is also some other tag we render (amenity/office/historic etc).

**Comment by imagico** [comment] 2019-05-10 09:28
> We'll need to move building names to st_pointonsurface too

Yes, and we should check if there are other labels which potentially have the same problem.

Generally speaking this bug is also an indicator for ambiguous tagging - it is simply not clear if the name is the name of the building or the name of the amenity/office/etc.  But it of course has become the implicit assumption of mappers that the name applies to the feature it is rendered for in the standard style.

**Comment by matkoniecz** [comment] 2019-05-10 16:46
I am not sure is it something that should be fixed. 

Such tagging (though common) is IMHO violation of https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element

Maybe rather validators should complain about merging POI and building into one element?

**Comment by kocio-pl** [comment] 2019-05-10 16:50
Such a big rendering change would require discussion first, so people can think about it, comment for some time and probably make changes in documentation and tools. I would not just slip that change without the intention into release.

**Comment by imagico** [comment] 2019-05-10 17:10
I think this should be fixed independent of the question if this is correct mapping or not because the two labels are the result of the mapnik label location and ST_PointOnSurface by chance resulting in locations sufficiently distant from each other for both labels to show.  This random nature of the double labels is highly confusing for mappers.

If we'd deliberately try to label both the building and the POI by moving the labels we could indeed try to display both since that is a valid interpretation of the data.  Same as for something tagged both as an amenity and a shop for example.  I am not sure if that is ultimately a good idea but it could be worth discussing.

**Comment by pnorman** [comment] 2019-05-11 03:17
> Database query for rendering building name could just exclude the cases when there is also some other tag we render (amenity/office/historic etc).

We don't know what is labeled at query time. If we de-duplicated at query time we'd need to reproduce most of the amenity query in the building query which isn't an option.

**Comment by kocio-pl** [comment] 2019-05-15 02:46
We have no clear idea how to attribute name to buildings, though there are some tags for this:

![taghistory(54)](https://user-images.githubusercontent.com/5439713/57744996-a4648300-76cb-11e9-8157-51b1380e0345.png)

![taghistory(52)](https://user-images.githubusercontent.com/5439713/57744758-d6291a00-76ca-11e9-8db3-382108c788af.png)

![taghistory(53)](https://user-images.githubusercontent.com/5439713/57744857-30c27600-76cb-11e9-82a6-7050520848a4.png)

Also I don't think it's really not proper tagging when more objects share the same database object. For example I would tag shop with cafe functions as one object. I believe object occupying a whole building can be seen as similar case.

**Comment by jeisenbe** [comment] 2019-05-15 05:44
address:housename is not for the name of a building, but for a postal /
mailing address that uses a name for a house instead of a housenumber. This
is common in some rural areas in Britain.

**Comment by imagico** [comment] 2019-05-15 11:39
Note `building=yes` + `name=*` is perfectly valid tagging for a named building.  If there are other tags on the same feature it is not clear which of them the name applies to though.  The solution to this is not to create additional name tags but to separate the building from its uses in mapping and to have in rendering a clear and consistent prioritization.

**Closed** 2019-05-15 16:10 UTC
Labels: amenity-points, buildings, regression, text
