### ISSUE TITLE
display kindergarten vs childcare node objects

### ISSUE THREAD

**Issue by sun-geo** [gravitystorm/openstreetmap-carto#4172] opened 2020-06-28 19:00 UTC
According to the wiki's: 
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dkindergarten
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dchildcare
kindergarten has a more valuable status (green "de facto") compared to childcare (white "in use"). But the current presentation/rendering of childcare node objects seems more prominent than kindergarten node objects.

### Expected behavior
Add a dot for kindergarten node objects, as it is done for childcare node objects
(potentially remove the dot for childcare node objects)

### Actual behavior
There is a dot rendered for childcare node objects
There is no dot rendered for kindergarten node objects

### Links and screenshots illustrating the problem
kindergarten:
https://www.openstreetmap.org/node/1217417049/history (v#2)
![image](https://user-images.githubusercontent.com/47290585/85955803-992cef00-b981-11ea-9ecf-cb51651dc09b.png)

childcare:
https://www.openstreetmap.org/node/7452971127/history (v#1)
![image](https://user-images.githubusercontent.com/47290585/85955836-d09b9b80-b981-11ea-94af-39d63cf01e20.png)

**Comment by imagico** [comment] 2020-06-30 09:10
Duplicate of #4037.

**Closed by imagico** 2020-06-30 09:10 UTC
