### ISSUE TITLE
Suppress underground buildings

### ISSUE THREAD

**Issue by ZeLonewolf** [gravitystorm/openstreetmap-carto#4477] opened 2021-09-22 03:37 UTC
### Expected behavior
Underground buildings (tagged with `location=underground`) should not be rendered.

### Actual behavior
Underground buildings are rendered in the same style as above-ground buildings.

### Links and screenshots illustrating the problem
Example of an underground building in Luxembourg:
https://www.openstreetmap.org/way/582873794
![image](https://user-images.githubusercontent.com/3254090/134279653-e4aef7bd-99bf-447c-bb02-2fe50a4ced35.png)

**Comment by pnorman** [comment] 2021-09-22 04:52
Duplicate of #552.

**Closed by pnorman** 2021-09-22 04:52 UTC
