### ISSUE TITLE
Too many tiny private airports on the map at small scales

### ISSUE THREAD

**Issue by talllguy** [gravitystorm/openstreetmap-carto#1143] opened 2014-12-01 14:57 UTC
![screen shot 2014-11-30 at 11 12 31 pm](https://cloud.githubusercontent.com/assets/1827881/5241237/8edd6a02-78e6-11e4-9299-0adbb8f1c41d.png)
Any suggestions on how to handle lots of tiny private airports? It doesn't look like there is a way to differentiate between tags but perhaps only airports with an ICAO or IATA ref should appear at the z10ish.

Perhaps only areas or relations with the `aeroway=aerodrome` could be shown. Any way to handle this programmatically?

**Comment by purpleplanes** [comment] 2015-01-03 00:41
Airports are way too prominent now that they're purple and solid color. [Link](http://www.openstreetmap.org/#map=10/39.7341/-86.2873)
![planes](https://cloud.githubusercontent.com/assets/10376879/5600996/1c3d59b8-92b7-11e4-84ce-a1555aa36419.png)

**Comment by mkoniecz** [comment] 2015-01-03 06:19
@purpleplanes People proposed checking area of airport, checking presence of icao and iata tags, whether the name or name:en tags contain clue words such as "international" or "heliport".

What would work in this case?

**Comment by pnorman** [comment] 2015-01-03 11:54
The root of the problem is really that anything a plane lands at is tagged with `aeroway=aerodrome`. iata is the best I've seen proposed, but I really think we're trying to work around bad tagging.

**Comment by mkoniecz** [comment] 2015-01-03 13:15
>I really think we're trying to work around bad tagging.

Yes, I will post about it on a tagging mailing list.

**Comment by talllguy** [comment] 2015-01-03 16:25
Yikes that purple is pretty bold. I'll look for the discussion on tagging

**Comment by mkoniecz** [comment] 2015-01-04 07:05
So there is no good way to check whatever airport is tiny. Is there some tag that would allow to check whatever it is private? And is it a good indicator of importance?

**Comment by SK53** [comment] 2015-02-06 20:05
A quick comment: this is a long term historic tagging problem: at one stage we had at least 3 tags for aeroway: airport, aerodrome & airstrip which were used in decreasing order of importance. There was an undiscussed mechanical edit which changed them all to aerodrome. I cant locate it quickly, but IIRC it was around mid-2009. It has just got worse because many more minor to extremely minor places have been added (for instance locations where it is possible to land a plane on glaciers in the alps, which are not aerodromes in any sense at all).

**Comment by math1985** [comment] 2015-03-21 16:07
@matkoniecz Did anything come out of the discussion on the mailing list?

**Comment by Rovastar** [comment] 2015-03-21 16:55
Just use way_area.

**Comment by matkoniecz** [comment] 2015-03-21 17:16
@math1985 

> Did anything come out of the discussion on the mailing list?

Using way_area is not bad, rendering depending on feature density would be cool.

**Comment by matkoniecz** [comment] 2015-03-21 17:18
way_area is not perfect, but better than alternatives including current state.

**Comment by Rovastar** [comment] 2015-03-21 17:57
I know it is not perfect but other solutions seem to be over-engineering and need other or new subjective tags in the carto database.
way_area is simple if it is big then it is rendered on lower zoom level/rendered big.

Sure there will always be edge cases but they will be rare and no solution is perfect.

**Comment by pnorman** [comment] 2015-03-21 18:25
> A quick comment: this is a long term historic tagging problem: at one stage we had at least 3 tags for aeroway: airport, aerodrome & airstrip which were used in decreasing order of importance. There was an undiscussed mechanical edit which changed them all to aerodrome. I cant locate it quickly, but IIRC it was around mid-2009. It has just got worse because many more minor to extremely minor places have been added (for instance locations where it is possible to land a plane on glaciers in the alps, which are not aerodromes in any sense at all).

Ugh. So we used to have sane tagging, then someone got rid of it?

**Comment by SK53** [comment] 2015-03-21 20:37
@math1985 @Rovastar: way_area does look like it will resolve most issues and is about the best proxy likely to occur. Most smaller places are just drawn as nodes or as a single way for the runway. Anything would be a dramatic improvement over cases like this: 

![daft_airports](https://cloud.githubusercontent.com/assets/5452818/6766730/103f5a9a-d00a-11e4-8384-4ab28d76e618.png)


@pnorman: yup

**Comment by mrwojo** [comment] 2015-09-03 01:37
FYI: [OurAirports](http://ourairports.com/data/) has a public domain CSV with their own classification of global airports as small, medium, or large.

**Comment by talllguy** [comment] 2016-04-12 21:56
:thought_balloon: FYI: This issue has resurfaced on the talk-us mailing list, as there is an active MapRoulette campaign to address aerodrome nodes that haven't been updated in the past three years. Read on: https://lists.openstreetmap.org/pipermail/talk-us/2016-April/016143.html

**Comment by pnorman** [comment] 2016-04-12 22:22
I don't see that anything has changed. Cleaning up bad imported data is good and will help slightly, but there are lots of small rural aerodromes for agricultural purposes. Until tags are consistently used which allow differentiation between aerodrome types, there's nothing we can do with the style.

**Comment by systemtester** [comment] 2016-04-12 22:35
Is a review of the mechanical edit warranted given tags were once split across 3 types?  Airport + IATA, for example, might give a good visual indication of commercial (domestic/international) premises.  It might not as well but the simplification of 3 types into 1 hasn't helped this issue at all.

**Comment by dieterdreist** [comment] 2016-04-13 10:11
> Am 13.04.2016 um 00:22 schrieb Paul Norman <notifications@github.com>:
> Until tags are consistently used which allow differentiation between aerodrome types, there's nothing we can do with the style.


years ago it was argued that rather than specifying more detailed
aerodrome subclasses renderers should look at the features offered
(surface, amount and length of runway/s, availability of customs,
etc). Some discussion about this can be found here:

https://www.mail-archive.com/tagging@openstreetmap.org/msg17947.html
https://lists.openstreetmap.org/pipermail/talk/2009-June/037823.html
https://lists.openstreetmap.org/pipermail/tagging/2011-February/006815.html
https://lists.openstreetmap.org/pipermail/tagging/2010-December/006144.html
https://lists.openstreetmap.org/pipermail/tagging/2011-January/006240.html
https://lists.openstreetmap.org/pipermail/tagging/2010-June/002563.html

**Comment by pnorman** [comment] 2016-04-13 16:15
> Is a review of the mechanical edit warranted given tags were once split across 3 types? Airport + IATA, for example, might give a good visual indication of commercial (domestic/international) premises. It might not as well but the simplification of 3 types into 1 hasn't helped this issue at all.

No, it hasn't helped, but after 6 years, it'd be a question of a new edit, not undoing a previous one.

> years ago it was argued that rather than specifying more detailed
> aerodrome subclasses renderers should look at the features offered
> (surface, amount and length of runway/s, availability of customs,
> etc).

Time and what renderers have ended up doing have shown that argument was wrong.

I was considering airport rendering in a stylesheet which doesn't have osm-carto's design constraint of using just OSM data, and concluded that the easiest way to get sensible rendering would be to either use another data source for airports, or match OSM airport data against another data source. That is not an option for osm-carto.

**Comment by imagico** [comment] 2016-04-13 16:45
> I was considering airport rendering in a stylesheet which doesn't have osm-carto's design constraint of using just OSM data, and concluded that the easiest way to get sensible rendering would be to either use another data source for airports, or match OSM airport data against another data source. That is not an option for osm-carto.

Have you tried matching airports with their runways and rating them based on runway properties?  I am not sure this is feasible here performance wise and i am not sure this leads to good results without relative rating (treating a large airport different when close to an even larger one) but it would definitely be worth trying.  And it would also be good for mapper feedback since it would encourage proper runway mapping.

**Comment by mboeringa** [comment] 2016-04-13 16:54
> In Europe, there are many tiny airports with ICAO code, such as Ameland or Kitzebourg Ultralight Airfield.
> 
> Not so much tiny airports with IATA code, but still some.


> was considering airport rendering in a stylesheet which doesn't have osm-carto's design constraint of using just OSM data, and concluded **that the easiest way to get sensible rendering would be to either use another data source for airports,** or match OSM airport data against another data source.

To be honest, and it has been suggested before like by the quote from @math1985 and others, using the IATA code seems the most reasonable and easy fix.

I have implemented this in my ArcGIS Renderer, and at least for the render results I've done so far in Europe, things are looking pretty good.

It is just very simple, three types of aerodromes. Major airports are rendered at scale >=1:250k, minor and heliport >=1:50k

**Major airports:**
_aeroway IN ('aerodrome') AND (iata IS NOT NULL AND iata NOT IN ('','no'))_

**Minor airports:**
_aeroway IN ('aerodrome') AND (iata IS NULL OR iata IN ('','no'))_

**Heliports**, using the latest tagging scheme
_aeroway IN ('heliport')_

**Comment by talllguy** [comment] 2016-04-13 17:18
@mboeringa I like that approach, especially if in your test it seems to work out. In the [original comment](https://github.com/gravitystorm/openstreetmap-carto/issues/1143#issue-50532411), I hypothesized that:
> perhaps only airports with an ICAO or IATA ref

should appear at certain scales. We keep coming back to this, and I think it is a great indicated of relative important, especially with all the tiny ones, such as what @purpleplanes pointed out.

Can you update your script to include `icao=*` as an OR to the `iata=*` logic?

[According to the wiki](http://wiki.openstreetmap.org/wiki/Key:icao), ICAO is more widespread. Also of interest:

>The ICAO code is hierarchically organized in regions of the globe, and it changes it's prefix accordingly. This kind of information can be used when doing automated quality assurance checks.

**Comment by kocio-pl** [comment] 2016-04-14 00:14
Looking at Indianapolis example (https://github.com/gravitystorm/openstreetmap-carto/issues/1143#issuecomment-68576491) even iata=* filter may be still too weak:
http://overpass-turbo.eu/s/fDH

**Comment by pnorman** [comment] 2016-04-14 06:24
> Have you tried matching airports with their runways and rating them based on runway properties? I am not sure this is feasible here performance wise and i am not sure this leads to good results without relative rating (treating a large airport different when close to an even larger one) but it would definitely be worth trying. And it would also be good for mapper feedback since it would encourage proper runway mapping

Yes. I don't want to go that route for OSM Carto with the non-obvious SQL. For my own work I'm still considering it, but I'm reluctant for similar reasons as here, as well as being not an option for another part of the toolchain I'm working on.

-----
> Looking at Indianapolis example (https://github.com/gravitystorm/openstreetmap-carto/issues/1143#issuecomment-68576491) even iata=* filter may be still too weak:
http://overpass-turbo.eu/s/fDH

Yes, that's what I'm finding locally too. There might also be a data quality issue. It still might be the best we can do.

**Comment by mboeringa** [comment] 2016-04-14 09:15
> Looking at Indianapolis example (#1143 (comment)) even iata=* filter may be still too weak:
> http://overpass-turbo.eu/s/fDH

Part of this problem is that airports are rendered to early. I only render them from >=1:250k. That is roughly equivalent to the viewport in this image:

http://www.openstreetmap.org/node/153353016#map=12/39.7385/-86.3711

While the view you showed is something like 1:1M.

Indianapolis is a huge city, it seems to cover an area roughly equivalent to something like 30x30 km, which is almost the size of an entire province here in the Netherlands...

Anyway, it seems most of these tiny airports with IATA code also have an **access=private** tag, so an adjustment like this might work if you want to maintain the Z10 rendering:

**Major airports:**
_aeroway IN ('aerodrome') AND (iata IS NOT NULL AND iata NOT IN ('','no')) AND (access IS NULL OR access NOT IN ('private'))_

**Minor airports:**
_aeroway IN ('aerodrome') AND ((iata IS NULL OR iata IN ('','no')) OR ((iata IS NOT NULL AND iata NOT IN ('','no')) AND access IN ('private')))_

**Heliports**, using the latest tagging scheme
_aeroway IN ('heliport')_

**Comment by jojo4u** [comment] 2016-05-03 22:10
Unfortunately at most 2,7% of all aerodromes have access=*, it's not even on the list of taginfo combinations: https://taginfo.openstreetmap.org/tags/aeroway=aerodrome#combinations

**Comment by mboeringa** [comment] 2016-05-03 22:47
> Unfortunately at most 2,7% of all aerodromes have access=*, it's not even on the list of taginfo combinations: https://taginfo.openstreetmap.org/tags/aeroway=aerodrome#combinations

Even so, with the queries I suggested, including checking the IATA tag, you will probably weed out quite a lot of the clutter. And it is likely that more aerodromes will get the access tag, once it makes a difference in the rendering...

**Comment by kocio-pl** [comment] 2016-08-11 22:22
Revisiting the issue after reading [this entry](http://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/39069).

We still don't have any good measure for recognizing important airports, but for Indianapolis area multiple simple conditions filtering would be quite effective:
- [“aeroway=aerodrome”](http://overpass-turbo.eu/s/hOF) gives 409 airports (only 60 on z16)
- [“icao=* and iata=* and (type:way or type:relation)”](http://overpass-turbo.eu/s/hOE) gives 17 airports (only 3 on z16)

So about 95% current airports there would be hidden on z16, even if it's still quite loose condition set. Even small airports [could have all these properties too](http://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/39069), but at least it shouldn't filter out any important airport and it gives us wide margin to think about something more strict (which probably means collecting the data for all the most important airports in the world and finding the common thread). Maybe just pushing the rest to z17 would be enough.

**Comment by math1985** [comment] 2016-08-11 22:51
Sounds good for now.

**Comment by StyXman** [comment] 2016-08-12 08:30
Maybe another source of data:

https://query.wikidata.org/#SELECT%20%3FplaceLabel%20%3FplaceAltLabel%20%3Fiata%20%3Ficao%20%3Fcoords%20WHERE%20%7B%0A%20%20%23%20Is%20an%20airport%0A%20%20%3Fplace%20wdt%3AP31%2Fwdt%3AP279%2a%20wd%3AQ1248784%20.%0A%20%20%3Fplace%20wdt%3AP238%20%3Fiata%20.%0A%20%20%3Fplace%20wdt%3AP239%20%3Ficao%20.%0A%20%20%3Fplace%20wdt%3AP625%20%3Fcoords%20.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%20%0A%20%20%7D%0A%7D

WikiData is really powerful, once you get the hang of it :)

**Comment by giggls** [comment] 2016-10-05 12:43
FYI: I Implemented the suggestion from mboeringa in german style fork.
https://github.com/giggls/openstreetmap-carto-de/commit/fa181b13795c0d3921ecd95e8a8710a17ce8c182

**Comment by talllguy** [comment] 2016-10-06 20:10
@giggls any screenshots of how it looks around one of the areas in this thread?

**Comment by HolgerJeromin** [comment] 2016-10-06 21:44
https://www.openstreetmap.de/karte.html

**Comment by kocio-pl** [comment] 2016-10-06 21:57
Is this really deployed already? I don't see the difference in the number of airport icons:

https://www.openstreetmap.de/karte.html?zoom=10&lat=39.80332&lon=-86.33519&layers=B000TF

**Comment by mboeringa** [comment] 2016-10-06 22:56
> Is this really deployed already?

+1.

I think it is not yet deployed, it was only committed to master yesterday.

Clearly, a private airport like this one, should no longer display once implemented based on its tagging:
http://www.openstreetmap.org/way/409314905

**Comment by giggls** [comment] 2016-10-07 07:51
https://www.openstreetmap.de/karte.html?zoom=10&lat=39.75167&lon=-86.14035 shows the current version now.

Re-Rendering is not done that often on this server as you are used to from tile.osm.org

If you like to have a tile re-rendered faster just use the /dirty trick on the particular tile:
https://help.openstreetmap.org/questions/1049/how-to-trigger-a-repaint-for-a-specific-osm-map-tile

The version (git hash) currently active on or tiles-erver is available at http://tile.openstreetmap.de/

**Comment by kocio-pl** [comment] 2016-10-07 11:05
For me making minor airports to show [from z13](https://github.com/giggls/openstreetmap-carto-de/commit/fa181b13795c0d3921ecd95e8a8710a17ce8c182#diff-5d9237083037cf1d6d91c329a0ff61adR1027) is too far. After all this distinction is rather subtle - we don't have clear definition of major and minor airports. I guess z11 would be enough, even in such extreme case as Indianapolis.

Still I find my query to be better, even including nodes (major airports are probably easy to draw):
http://overpass-turbo.eu/s/j9G (German style)
http://overpass-turbo.eu/s/j9H (my take)

**Comment by utack** [comment] 2016-10-07 11:07
You have an "acces" in your query, german style is a lot stricter actually

http://overpass-turbo.eu/s/j9J


Am 07.10.2016 um 13:05 schrieb kocio-pl:

**Comment by kocio-pl** [comment] 2016-10-07 11:34
Thanks! I've pasted a link to the corrected query. But it's still weaker than mine because of ICAO.

**Comment by giggls** [comment] 2016-10-07 12:35
@utak: I render all airports with IATA tag and access != private in z10-z12 and all airports in z13. I did not consider ICAO because all airports with IATA code also seem to have an ICAO code.
I can issue a pull request on https://github.com/giggls/openstreetmap-carto-de/commit/396da79b5ac96bf6afd6e94b0f705de6bd8a1bc7 if desired.

**Comment by kocio-pl** [comment] 2016-10-07 12:50
So ICAO can just promote more careful tagging (just like excluding nodes), but is not necessary. 

I like your code (type labels make it clear), but I think z11 (or z12) for small would be better for any other place, which is not that loaded with small airports. Tuning for extreme case (z13) will be too strict everywhere else.

What do you think?

**Comment by imagico** [comment] 2016-10-07 13:13
Note there are already 36 cases with iata=none or iata=N/A - using this as a rating criterion could encourage such tagging.

I would still think using runway length as a rating criterion is probably the most universal approach.  Would be great to see if that is practically feasible in live rendering.

**Comment by SK53** [comment] 2016-10-07 13:33
@imagico I'm sure you are right about runway length, but one counter-example comes to mind: Machrihanish (Campbeltown) Airport has the longest runway in Scotland (was US AFB with Galaxy G5, SR-71 etc. visiting). With under 10k passengers it is one of the smaller ones, but still 14th overall in Scotland.

**Comment by imagico** [comment] 2016-10-07 14:37
Yes, military airports often follow different rules regarding runway length and this often continues if an airport is re-purposed for civilian use.  The idea here is however not to have a fixed threshold like _only show airports with a runway of more than 2000m at z12_ but to have a rating criterion that allows prioritization and this way makes sure important airports are shown while less important ones are dropped where things are dense.  To do this really well will require preprocessing but it would be interesting to see to what extent this also works ad hoc.

**Comment by giggls** [comment] 2016-10-07 14:40
@imagico I consider IATA tagged on airports where there is no such code a bug.

**Comment by SomeoneElseOSM** [comment] 2017-06-25 12:59
If it helps, here's what I'm currently doing in a different style:

https://github.com/SomeoneElseOSM/SomeoneElse-style/blob/master/style.lua#L2303

That suppresses disused one, includes only non-military ones with an IATA code and renders grass strips less prominently.  That works for the UK, but "non-military with an IATA code" may need expanding elsewhere (e.g. the US).  I take the points above about use and misuse of IATA codes, but it works well enough to be useful.

**Closed** 2017-07-30 01:51 UTC
Labels: amenity-points
