### ISSUE TITLE
Not rendering : aerialway=magic_carpet 

### ISSUE THREAD

**Issue by AntonioLagoD** [gravitystorm/openstreetmap-carto#4649] opened 2022-08-17 08:57 UTC
### Expected behavior
Magic carpet is a kind of people mover used as ski lifts, but not only. It is expected to render the way as a straight line with some ticks.
### Actual behavior
All ski lifts are well rendered but where carpets are placed nothing is shown.
### Screenshots with links illustrating the problem
![CarpetisThere](https://user-images.githubusercontent.com/44477003/185078335-95fba2c4-07e3-4d77-9dc7-bd70c3385222.png)
![noCarpetShown](https://user-images.githubusercontent.com/44477003/185078340-d1a7203f-90d6-474e-8518-125adb0a68a3.png)

**Comment by AntonioLagoD** [comment] 2022-08-17 08:58
Link to the example way:
https://www.openstreetmap.org/way/251027114

**Comment by danieldegroot2** [comment] 2022-08-17 16:02
Duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/3169#issuecomment-449221199.

**Comment by imagico** [comment] 2022-08-17 16:35
Closing as duplicate of #3169 - please comment there with any arguments to reopen.

**Closed by imagico** 2022-08-17 16:35 UTC
