### ISSUE TITLE
does not render public_transport=platform area

### ISSUE THREAD

**Issue by olo81** [gravitystorm/openstreetmap-carto#4191] opened 2020-08-18 17:21 UTC
### Expected behavior
platform rendering
### Actual behavior
no map rendering of bus stop platforms when they are training grounds 
### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/226759676

**Comment by imagico** [comment] 2020-08-18 18:12
How would you suggest to render them?

Note we render railway=platform and highway=platform - which are both tags for physical features (a raised structure) as well as highway=bus_stop, amenity=taxi, amenity=ferry_terminal and aeroway=gate - which are non-physical features.  public_transport=platform is according to the documentation not necessarily physical.  Nearly all uses of public_transport=platform on nodes are in combination with highway=bus_stop, 2/3 of all uses on ways are in combination with railway=platform or highway=platform.

**Comment by olo81** [comment] 2020-08-18 18:36
similar to railway = platform only brighter


https://www.openstreetmap.org/way/300053684

**Comment by pnorman** [comment] 2020-08-18 21:26
This request to render public_transport=platform is a duplicate of #435.

**Closed by pnorman** 2020-08-18 21:26 UTC
Labels: duplicate
