### ISSUE TITLE
Small islands names

### ISSUE THREAD

**Issue by emmexx** [gravitystorm/openstreetmap-carto#1496] opened 2015-04-22 10:32 UTC
The current mapnik rendering doesn't show the name of relatively small islands whatever zoom level you are.
Examples:
http://www.openstreetmap.org/#map=10/42.7667/10.2228 Isola d'Elba
http://www.openstreetmap.org/#map=12/42.5942/10.0844 Pianosa
http://www.openstreetmap.org/#map=12/43.0141/6.2097 Porquerolle
http://www.openstreetmap.org/#map=10/38.8392/1.3513 Ibiza & Formentera
http://www.openstreetmap.org/#map=9/36.9049/12.0245 Pantelleria

Is it a rendering or a tagging matter?

If it is a rendering matter I'm not sure the reasoning behind the choice of what name to show is good. I mean, it is more important to a user to see the name of the island whilst the administrative region or country are secondary infos. There's already the boundary most of the times and the region or country info can be rendered in other ways, for example: Pantelleria (I) or Pantelleria (Italy)

**Comment by imagico** [comment] 2015-04-22 11:01
Yes, this is a rendering and not a tagging problem.

See also #1448.

In most cases giving island labels priority over admin unit labels would be an improvement although in some cases this might lead to important admin units not be labeled at all.  Much of this is related to the unresolved issues introduced by #1134 and of course also to Mapnik's very inflexible label placement.

My favorite  example by the way is http://www.openstreetmap.org/#map=7/28.907/-15.634 where all kind of stuff is displayed at the various zoom levels but never the islands themselves (neither individually nor as a group).

**Comment by matkoniecz** [comment] 2017-10-16 13:18
Seems to be fixed now.

**Comment by kocio-pl** [comment] 2017-10-16 20:49
Confirmed - all the examples have a name now.

**Closed by kocio-pl** 2017-10-16 20:49 UTC
Labels: amenity-points
