### ISSUE TITLE
Render cross in the centroid of christian churches

### ISSUE THREAD

**Issue by LucFreitas** [gravitystorm/openstreetmap-carto#2709] opened 2017-07-26 12:16 UTC
The cross and name appear out of shape.

Example "Santadart":
![1](https://user-images.githubusercontent.com/19976610/28620238-79285dc8-71e2-11e7-899d-f5b0501a1049.PNG)

HOT:
![2](https://user-images.githubusercontent.com/19976610/28620239-792902e6-71e2-11e7-9a44-9d65a9fd5a45.PNG)

http://www.openstreetmap.org/way/49840192

**Comment by polarbearing** [comment] 2017-07-26 15:23
related to #2457 ? Though there, the P is in the centre of an oddly shaped polygon, while here at least the centre of the text label is inside.

**Comment by HolgerJeromin** [comment] 2017-07-26 22:09
Duplicate of  #2511 which was closed as a duplicate,  too. 
Someone should collect the current issues and report them to the mapnik repository

**Closed** 2017-07-26 22:52 UTC
Labels: duplicate, enhancement

**Comment by HolgerJeromin** [comment] 2017-07-27 12:24
Thanks pnorman!
