### ISSUE TITLE
Rendering of the approved landuse=education

### ISSUE THREAD

**Issue by SafetyIng** [gravitystorm/openstreetmap-carto#4413] opened 2021-05-21 14:34 UTC
Hey,

on the community there is a "new" approved landuse=education ; [Link to the wiki](https://wiki.openstreetmap.org/wiki/Proposed_features/Multiple_schools_on_one_ground)
It was also mentioned in #3381 and #774

The voting is still very fresh. In the course of the weekend, the corresponding wiki pages will be adapted. 
What does the carto team think about supporting the rendering? What do you think about the proposed rendering from the proposal?

**Comment by imagico** [comment] 2021-05-21 15:03
Duplicate of #774 - if you think there is basis for re-opening that please present your case on that issue

**Closed by imagico** 2021-05-21 15:03 UTC
