### ISSUE TITLE
Large ways are not rendered.

### ISSUE THREAD

**Issue by aaronstar** [gravitystorm/openstreetmap-carto#2180] opened 2016-06-20 03:42 UTC
Large ways are not rendered.
Hello,
As described above, large ways are not rendered. This issue became apparent when mapping administrative boundaries (tagged with boundary=administrative and admin_level=X) JOSM and the OSM backend only raise issues for ways over 2,000 nodes. Several ways between approx. (possibly starts much lower) 1,700 and 2,000 nodes are not rendered. As only the rendering system raises issues and not OSM itself these ways were not split into multipolygons (some of which are rendered with greater success than non-multipolygon ways**)

Regards,
Aaron

**Comment by matkoniecz** [comment] 2016-06-20 08:22
Is it duplicate of #713 #1362? If not - please link an affected object.

**Comment by aaronstar** [comment] 2016-06-20 12:47
Hi matkoniecz, yes this appears to be similar to #713

**Closed** 2016-06-20 13:14 UTC
Labels: duplicate
