### ISSUE TITLE
Building above pedestrian area not rendered

### ISSUE THREAD

**Issue by apophenic-treehugger** [gravitystorm/openstreetmap-carto#4540] opened 2022-04-25 14:09 UTC
### Expected behavior
A `building=*` should be rendered above a `highway=pedestrian + area=yes `if the pedestrian area's layer is (implicitly or explicitly) lower than the building layer. 

### Actual behavior
https://www.openstreetmap.org/way/1036396664 is tagged `building=yes + layer=1` but isn't rendered above the pedestrian area https://www.openstreetmap.org/way/1036396665 which passes underneath.

### Links and screenshots illustrating the problem
![image](https://user-images.githubusercontent.com/81189494/165106215-175e91ff-cbb8-45e1-9516-a7e0c0e32d07.png)
![image](https://user-images.githubusercontent.com/81189494/165106113-ee4306ab-4e1b-47ae-ac2c-548304ff7332.png)

**Comment by HolgerJeromin** [comment] 2022-04-25 14:34
Thanks for your report. 
This is being discussed in an older issue. Therefore this item is a 
duplicate of #688

**Closed** 2022-04-25 15:56 UTC
