### ISSUE TITLE
Render landuse=education in same style as amenity=school

### ISSUE THREAD

**Issue by joelamos** [gravitystorm/openstreetmap-carto#4425] opened 2021-06-20 12:02 UTC
[landuse=education](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Deducation#:~:text=A%20landuse%20%3D%20education%20usually%20exist,membership%20in%20a%20Relation%3Asite.) is used primarily when there is an educational campus containing multiple amenity=school that do not have clear boundaries. It fills a clear niche and has had steady growth.

The proposal is to render it the same as amenity=school areas.

**Comment by polarbearing** [comment] 2021-06-20 18:52
Duplicate of #4413 and #774

**Comment by joelamos** [comment] 2021-06-20 19:25
Whoops, thanks

**Closed** 2021-06-20 19:25 UTC
