### ISSUE TITLE
Not rendering "public_transport=stop_position"

### ISSUE THREAD

**Issue by KenAlin** [gravitystorm/openstreetmap-carto#2002] opened 2015-12-09 18:55 UTC
Hi,
As stated in the title, stop position for public transportation doesn't seem to render on the map.
[Here is an exemple](https://www.openstreetmap.org/node/3672498356) for an unrendered node.

**Comment by Circeus** [comment] 2015-12-09 20:17
public_transport=platform (missing here) the tag that is meant to be rendered?

**Comment by matkoniecz** [comment] 2015-12-09 21:13
duplicate of  #435

**Closed by matkoniecz** 2015-12-09 21:13 UTC
