### ISSUE TITLE
Add rendering for amenity=* and office=*

### ISSUE THREAD

**Issue by jremillard** [gravitystorm/openstreetmap-carto#108] opened 2013-08-09 01:41 UTC
Hi,

Any point that has an amenity or office tag and a name tag, should at least get its named rendered even if we don't have an icon at max zoom. 

Most of the POI's in the mall are not rendered.

http://osm.org/go/ZfJD0RleX--
- [x] bench #194
- [x] public_building (won't fix)
- [x] bicycle_parking #591
- [x] waste_basket #418
- [x] townhall #77
- [X] parking_space #776 (won't fix)
- [x] hunting_stand #966
- [ ] vending_machine #1561
- [x] fountain #705
- [x] social_facility #1776
- [x] car_wash #1777
- [x] marketplace #751
- [x] dentist
- [x] waste_disposal #419
- [x] community_centre #506
- [x] taxi #879
- [x] fire_hydrant (won't fix)
- [x] veterinary clinic #1656
- [ ] parking_entrance #270
- [ ] nursing_home
- [x] arts_centre #2520
- [x] nightclub #456

**Comment by math1985** [comment] 2015-01-13 22:39
@nebulon42 Do you have any suggestion for a dentist icon? The SJJB icon @nebulon42 ![dentist](http://www.sjjb.co.uk/mapicons/png/amenity_dentist.p.20.png) is not that nice.

**Comment by kocio-pl** [comment] 2015-01-13 23:50
I also vote for the tooth icon with nothing else.

**Comment by math1985** [comment] 2015-01-14 00:14
I added the most used ones (>10000 occurrences) to the top of this post. For most of them, finding a suitable icon is the toughest task.

**Comment by math1985** [comment] 2015-01-14 00:18
I propose not to render amenity=fire_hydrant (too specialistic).

**Comment by mkoniecz** [comment] 2015-01-14 07:25
Main problem with amenity=fire_hydrant is that displaying would make sense on z22 or z21. And that zoom levels currently are not used anywhere (AFAIK - it is not going to change in near future).

**Comment by mkoniecz** [comment] 2015-01-14 07:27
BTW, the same problem is with amenity=bench - though Humanitarian style displays benches on z19.

**Comment by AnBuKu** [comment] 2015-01-14 07:52
Am 14.01.2015 um 08:25 schrieb Mateusz Konieczny:
> Main problem with amenity=fire_hydrant is that displaying would make
> sense on z22 or z21. And that zoom levels currently are not used
> anywhere (AFAIK - it is not going to change in near future).

This is the only one I know with z21
http://www.osm.ch/#21

But, sure, emergency=fire_hydrant should not be rendered in the main map
(even if I'm a fanboy of fire hydrants :-)

And, amenity=firehydrant should be avoided or existing ones changed
towards emergency=fire_hydrant

https://taginfo.openstreetmap.org/tags/emergency=fire_hydrant -> 303 482


https://taginfo.openstreetmap.org/tags/amenity=fire_hydrant -> 12 274


> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gravitystorm/openstreetmap-carto/issues/108#issuecomment-69878437>.
> 

-- 

Andreas Bürki

abuerki@anidor.com
S/MIME certificate - SHA1 fingerprint:
ED:A5:F3:60:70:8B:4C:16:44:18:96:AE:67:B9:CA:77:AE:DA:83:11
GnuPG - GPG fingerprint:
5DA7 5F48 25BD D2D7 E488 05DF 5A99 A321 7E42 0227

**Comment by mkoniecz** [comment] 2015-01-14 08:06
I marked fire_hydrant as "(won't fix)".

**Comment by nebulon42** [comment] 2015-01-14 09:25
@math1985 I have a suggestion for dentist (https://github.com/nebulon42/osmic/blob/master/health/dentist-16.svg) and will open a PR.

**Comment by math1985** [comment] 2015-02-10 02:05
dentist and townhall have been added in the meanwhile.

**Comment by matkoniecz** [comment] 2015-07-28 22:44
I updated the first post marking implemented feature. 

amenity=public_building should be rejected based on its wiki page - http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_building

> Short Answer: Don't.

**Comment by kocio-pl** [comment] 2015-07-28 23:40
@matkoniecz nightclub is also already implemented and we have [an open ticket for veterinary clinic](https://github.com/gravitystorm/openstreetmap-carto/pull/1656). 

I wish we start using Wiki for maintaining such big and long lasting lists of features...

**Comment by matkoniecz** [comment] 2015-07-28 23:44
I would prefer individual tickets over collections like that - for example this ticket seems to offer absolutely no benefit over opening individual ones that may be handled separately.

**Comment by kocio-pl** [comment] 2015-07-28 23:50
For me it does: you have a bunch of related issues together in one place if  the problem is more general (like rendering important/popular objects other than just shop=*). Individual tickets are linked for individual cases related to this problem.

**Comment by math1985** [comment] 2015-07-29 00:09
I also like having the meta-tickets.

**Comment by matkoniecz** [comment] 2015-07-29 06:23
I marked public_building as "won't fix" (as recommended by http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_building).

**Comment by kocio-pl** [comment] 2015-07-29 10:41
While I agree we don't want to show the icon for public_building, I think we may render it as a "major" building type (currently only PoW buildings).

**Comment by matkoniecz** [comment] 2015-07-29 10:55
According to wiki it is a bad tagging scheme, therefore not deserving promotion by using it in rendering.

**Comment by kocio-pl** [comment] 2015-07-29 11:04
Ok, right :smile: - it's just very popular, but building=public is the answer. I guess once we start displaying them as major, people will start migrating.

**Comment by dieterdreist** [comment] 2015-07-29 11:22
sent from a phone

> Am 29.07.2015 um 13:04 schrieb kocio-pl <notifications@github.com>:
> 
> but building=public is the answer


I'm pretty sure it isn't ("public" is a very rough building type, could be anything from an office tower to a library or..., it is similar to "residential", where a more refined distinction is detached house or apartments etc.)

**Comment by kocio-pl** [comment] 2015-07-29 11:26
It's always better to be more specific if possible, but I guess major buildings are just different kinds of public buildings. However Iit needs some testing probably to know if it's not too wide.

**Comment by tuxayo** [comment] 2015-08-02 16:23
I agree that it would be useful to distinguish public buildings.

After testing few capitals
http://overpass-turbo.eu/s/aJL
http://overpass-turbo.eu/s/aK3
http://overpass-turbo.eu/s/aJI
http://overpass-turbo.eu/s/aK2
the density don't seem to pose visual cluttering problems.

**Comment by kocio-pl** [comment] 2015-08-22 12:50
Community centre and veterinary clinic rendering is now merged.

**Comment by math1985** [comment] 2015-08-22 22:05
Updated

**Comment by kocio-pl** [comment] 2015-09-16 18:08
car_wash is now merged too: https://github.com/gravitystorm/openstreetmap-carto/pull/1777.

**Comment by matkoniecz** [comment] 2015-09-16 19:51
Updated, thanks.

**Comment by matkoniecz** [comment] 2015-09-18 20:30
> vending_machine

I think that in this case value of rendering it is rather low (though waste baskets are rendered) and rendering it in understandable way would be problematic.

**Comment by kocio-pl** [comment] 2015-09-19 12:15
See https://github.com/gravitystorm/openstreetmap-carto/issues/1561#issuecomment-141659855.

**Comment by planemad** [comment] 2015-12-21 10:24
- [ ] office=government https://github.com/gravitystorm/openstreetmap-carto/issues/271

In places like India government offices are the most important public amenity in smaller towns and villages. Can we please boost this up in priority? This will also help mappers retag amenity=public_building which is now an abandoned tag.

**Comment by kocio-pl** [comment] 2016-02-12 20:38
@jremillard: fountain and social_facility are now merged, so you can check their boxes as done.

**Comment by math1985** [comment] 2016-02-12 22:05
I can do so too :)

**Comment by valhentai** [comment] 2016-03-20 17:10
can we add [amenity=retirement_home](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dretirement_home) to the list?

**Comment by polarbearing** [comment] 2016-03-20 21:00
No that is old-fashioned tagging, used too little. 
Such facility should be tagged amenity=social_facility + [social_facility=assistant_living](https://wiki.openstreetmap.org/wiki/Key:social_facility). 
Social facilities are rendered.

**Comment by valhentai** [comment] 2016-03-21 08:24
@polarbearing Thanks for the info. I updated tags in my city. now they are rendered.

**Comment by james2432** [comment] 2016-07-13 17:48
Can we add:
[office=tax_advisor](http://wiki.openstreetmap.org/wiki/Tag:office%3Dtax_advisor)
[office=accountant](http://wiki.openstreetmap.org/wiki/Tag:office%3Daccountant)
Both are used a lot : 
http://overpass-turbo.eu/s/hi0   (tax_advisor)
http://overpass-turbo.eu/s/hi1   (accountant)

**Comment by math1985** [comment] 2016-07-13 21:24
Are there icons for them?

**Comment by james2432** [comment] 2016-07-13 22:35
JOSM has them as: 
![test](https://cloud.githubusercontent.com/assets/498547/16822125/683ea4e2-4928-11e6-936c-f1157c06471d.PNG)

Accountant = Person beside a box with a dollar sign on it
Tax Advisor = Same icon as Accountant but with a green arrow pointing down from above

**Comment by math1985** [comment] 2016-07-13 22:48
The JOSM icons don't seem to go very nice with this style though.

**Comment by james2432** [comment] 2016-07-13 22:51
I'm aware they are ugly, but I'm not a graphics designer... and anything i'd make would look like rubish

**Comment by kocio-pl** [comment] 2016-07-14 02:16
This is 16x16 PNG export of those icons in black - they are very similar, but IMO we may just use the same icon for both (1 is better, because 2 is less clear):
1) ![accountant](https://cloud.githubusercontent.com/assets/5439713/16825858/b5b19234-4978-11e6-9ce1-c0c85e4f6760.png)
2) ![tax_advisor](https://cloud.githubusercontent.com/assets/5439713/16825914/2cb6296c-4979-11e6-8029-b0962e39325d.png)

**Comment by polarbearing** [comment] 2016-07-14 08:23
ATM and bank intentionally use a generic bank not icon. The above re-introduces a particular currency symbol.

**Comment by james2432** [comment] 2016-07-14 10:06
So put a guy beside the stack of money, or use generic currency symbol https://en.m.wikipedia.org/wiki/Currency_sign_(typography)

**Comment by kocio-pl** [comment] 2016-07-14 10:32
We have only 14x14 pixel monochrome matrix, so I see it as a very difficult task. Unless you - or anybody else - show some promising sketch, so I can refine it somehow, I doubt it can be done within our current framework. 

Still I think at least (brown) dot with a name is better than not showing it at all (or as a house number) - see also https://github.com/gravitystorm/openstreetmap-carto/issues/1697 for similar POIs.

**Comment by SomeoneElseOSM** [comment] 2016-07-14 11:41
I know that while OSM carto has a liking for individual icons for individual shop types, but for offices I'd definitely start with something very generic - a dot, like the "other type of shop" dot, but in a colour that doesn't get confused with existing features.

Here's an example, using black for offices:


![screens_20160520007](https://cloud.githubusercontent.com/assets/5311740/16838238/253c4440-49c0-11e6-87a3-9d7ac8830825.png)

(that's http://www.openstreetmap.org/#map=19/52.95297/-1.15692 BTW).

**Comment by math1985** [comment] 2016-07-14 11:55
> Here's an example, using black for offices:

Looks very nice to me. I agree keeping adding icons might be not good for readability.

**Comment by polarbearing** [comment] 2016-07-14 12:00
Looks nice for one office per building. What do we do if a skyscraper fills up with 250 offices?

**Comment by kocio-pl** [comment] 2016-07-14 12:00
The same as with malls: some of them will be eclipsed by the others.

**Comment by SomeoneElseOSM** [comment] 2016-07-14 12:42
Yes - in that example at z19 you can see that not all offices have names shown for exactly that reason.  Zoom in one more level and you get most (but all), and z21+ support AIUI needs some mod_tile changes, so very much in the distance I suspect.

For _very_ multilevel buildings you need something like http://wiki.openstreetmap.org/wiki/OpenLevelUp to make sense of them; I'd expect it'd be out of scope here.  Have a look at New Street Station in Birmingham if you want an example of a multi-use, multi-level structure that's well mapped in OSM.

**Comment by ccamara** [comment] 2016-08-22 15:43
As far as I see it, the main difference between most `shop=*` and `office=*` is that whereas the first sell goods, the latter sell services. For that reason I think that if it has been decided that shops have to be rendered because they might be of any interest, offices should be rendered as well, as they are at least as interesting as shops, if not (I'm thinking now about government offices, which additionally may be considered of public interest).

It is quite another thing the already mentioned problems of readability, but IMHO that should be addressed later as a different issue (eg: by defining the right icons, colours and zoom levels), but that should come after displaying offices (I find @SomeoneElseOSM 's [proposal](http://github.com/gravitystorm/openstreetmap-carto/issues/108#issuecomment-232641882) a good workaroung to be used in the meanwhile)

**Comment by boothym** [comment] 2016-08-23 12:53
Agree with adding something for office=* - looks a bit strange to have the addr:housenumber displayed in High Street full of shops when for example a lawyer or accountant's "shop" is not rendered either with a name or icon.

**Comment by kocio-pl** [comment] 2017-09-12 16:16
The question is - how standard office rendering should look like? Black dot + name? Adding icons for specific offices might be done later if needed, but we have to start with something generic.

And which offices should be shown?

**Comment by math1985** [comment] 2017-09-12 16:33
What about name only, without fot?

**Comment by kocio-pl** [comment] 2017-09-12 17:05
We can try it, but I guess it will make it harder to guess which feature the label describes, because black is generic color we use for different things.

I guess office=government and office=administrative (#271) should be rendered brown as they are public services similar to townhall or police station. Maybe also some other offices too.

Maybe it would be good to have a test server to check how does it look all around the world.

**Comment by kocio-pl** [comment] 2017-10-09 03:35
I think we should render nursing_home as we do with social_facility. It has 13 977 uses and is still gaining popularity:

![taghistory 4](https://user-images.githubusercontent.com/5439713/31324506-8efed5f8-acb3-11e7-9faf-cf1961db370e.png)

**Comment by abdeldjalil09** [comment] 2017-10-24 18:50
marketplace is now rendered

**Comment by kocio-pl** [comment] 2017-10-24 18:59
Thanks, updated.

**Comment by polarbearing** [comment] 2017-10-27 00:06
> I think we should render nursing_home as we do with social_facility.

Both iD and JOSM have recently updated their presets in favour of amenity=social_facility + social_facility=nursing_home. Your graph is not showing the 2017 development. 

I wonder what (import?) cause that strange peak in 2011?

**Comment by kocio-pl** [comment] 2017-10-27 09:23
Unfortunately http://taghistory.raifer.tech is not refreshed as frequently as I'd like it. Thanks for the info.

**Comment by andrzej-r** [comment] 2017-11-26 19:40
I see my report #2953 has been referred here. Thanks. 

However, this discussion is much broader and more open-ended. I would like to point out there is an actual bug (so it isn't just an enhancement request) in the way office PoIs are currently rendered:

The rendered uses a house number + house name instead of a name tag. I can't think of any scenario where such result would be desirable. Most likely it is a leftover from the address PoI implementation. 

Could that be fixed first, before we sort out icons and other enhancements?

**Comment by kocio-pl** [comment] 2017-11-26 19:45
Could you link an example?

**Comment by andrzej-r** [comment] 2017-11-26 20:40
http://www.openstreetmap.org/#map=19/52.23241/0.14955

**Comment by kocio-pl** [comment] 2017-11-26 20:45
> Could that be fixed first, before we sort out icons and other enhancements?

You mean something like http://www.openstreetmap.org/node/5237606800 ?

I don't feel we could fix it in the other way than just start rendering kind of icon, probably just a grey dot similar to shop dot. What do you think could be done before, which could be easier?

**Comment by andrzej-r** [comment] 2017-11-26 21:28
Icons would be great but I guess that may take some time (there are many office tags). For start, we could simply change the text we already render (from addr:housenumber to name). 

BTW, iD currently renders an icon + the name tag. OsmAnd renders only a "name (addr:housenumber)" text, which personally I think is a bit too much.

The way company names are currently displayed discourages correct tagging. So it would be good to fix it first and focus on aesthetics later.

**Comment by kocio-pl** [comment] 2017-11-26 21:57
I also think special icons will be needed only for some special types and we can work on it later. A dot should be easy (probably with man_made gray color) and I would use it because a name alone may suggest an area, while most offices are tagged as a node.

So - is anybody willing to prepare such PR and test it?

**Comment by andrzej-r** [comment] 2018-01-10 00:29
I've just noticed https://map.atownsend.org.uk/maps/map/map.html renders office=company as a dot and a name. Perhaps the implementation can be reused.

**Comment by kocio-pl** [comment] 2018-01-10 00:36
Would you like to prepare the code? That would help a lot.

**Comment by geesona** [comment] 2018-01-12 03:29
I provided a suggest icon for a bbq #2996 a week ago is some one able to check it for me to see if it is suitable and maybe implement it?
https://gist.github.com/geesona/a5912e34c377d644e088889ecf40d09d

**Comment by Tomasz-W** [comment] 2018-02-10 08:39
I think this issue should be renamed to "Render amenity=* as dots + names".

Let's review first comment https://github.com/gravitystorm/openstreetmap-carto/issues/108#issue-17843225 : 
* vending_machine -> it has ticket for separate icon (#1561)
* parking_entrance -> it has ticket for separate icon (#270)
* nursing_home -> this tag was moved to a subtag of amenity=social_facility (which has it's own icon at this moment), so it's not up to date
* there are some amenity=* tags which already has separate tickets for icon and wasn't included here (e.g. bbq or studio) and it's ok

The only thing which stay left to discuss here is generic dots for amenities which don't have separate tickets for own icons.

**Comment by andrzej-r** [comment] 2018-04-06 15:40
I partially disagree. Yes, we would like to have icons for amenity tags (BTW, office= tags are not an exception, there are some good candidates for an icon as well) but the priority should be in supporting all documented or popular tags in the first place.

What I propose is a 2 stage approach. First we implement all missing tags as dots and then, one by one, add icons for them.

**Comment by Tomasz-W** [comment] 2018-04-06 19:38
I looked at amenity=* issues which has been referenced here, and also at all issues with "amenity-points" label    https://github.com/gravitystorm/openstreetmap-carto/issues?page=2&q=is%3Aissue+is%3Aopen+amenity+label%3Aamenity-points

I don't see any amenity=* candidates for dot-rendering. 
@andrzej-r Can you give examples which tags do you consider?

**Comment by kocio-pl** [comment] 2018-04-07 09:28
While office sounds OK for me to always be rendered with a dot, amenities are too different. It might be another kind of eating place, street furniture or almost anything else. Therefore I would be more careful when rendering amenities and do it only for whitelisted values. Probably some of them need to move to the new keys to make it more clear what they really are.

**Comment by dieterdreist** [comment] 2018-04-07 12:12
sent from a phone

> On 7. Apr 2018, at 11:28, kocio-pl <notifications@github.com> wrote:
> 
> While office sounds OK for me to always be rendered with a dot,


I could imagine limiting these to large offices, i.e. on areas and >=limit

Generally, while bigger offices can be landmarks, most offices are IMHO not significant enough for this general style.

**Comment by andrzej-r** [comment] 2018-04-07 16:32
dieterdreist, you have to tweak both icon and label rendering paths. Not saying it is not possible (I tried it before) but the combinations quickly pile up. For example, office= tags are quite often combined with landuse= (not just building= tags) and there are likely a lot of other corner cases. Also, without rendering at least an icon or dot you will often not see the tag at all - in congested areas labels often hidden even at z19.

Do more people agree that dots on the buildings are undesirable? If so, do you have any ideas for a solution?

**Comment by matkoniecz** [comment] 2018-04-08 18:27
> office= tags are quite often combined with landuse=

This sounds like a tagging mistake, can you give an example of place where this tagging is correctly used?

**Comment by andrzej-r** [comment] 2018-04-08 19:54
There are many such unexpected tag combinations in use. Given their popularity I wouldn't automatically dismiss them as tagging errors. One reason is lack of support for office tags in carto, so there is no visual feedback to the mappers.

[example](https://overpass-turbo.eu/s/xIs)

**Comment by Tomasz-W** [comment] 2018-04-20 05:45
For me, this issue is resolved by #3163 . 
See https://github.com/gravitystorm/openstreetmap-carto/issues/108#issuecomment-364636355 and later comments, there wasn't much support for amenities generic dots idea.

**Comment by matthijsmelissen** [comment] 2018-04-20 05:48
I think we should still consider the last three individual amenities in the initial post.

**Comment by Tomasz-W** [comment] 2018-04-20 07:11
> I think we should still consider the last three individual amenities in the initial post.

@matthijsmelissen  I agree, but:
* vending machines -> separate ticket https://github.com/gravitystorm/openstreetmap-carto/issues/1561
* parking entrances -> PR https://github.com/gravitystorm/openstreetmap-carto/pull/2875
* nursing_home -> this tag was moved to a subtag of amenity=social_facility (which has it's own icon at this moment), so it's not up to date

This meta-issue is useless in this situation.

**Comment by matthijsmelissen** [comment] 2018-04-20 07:42
Alright, happy to close this item!

**Closed by matthijsmelissen** 2018-04-20 07:42 UTC
Labels: amenity-points, enhancement, features
