### ISSUE TITLE
Render tunnel=yes and covered=yes on highway=raceway

### ISSUE THREAD

**Issue by SuperFlomm** [gravitystorm/openstreetmap-carto#4269] opened 2020-12-21 18:25 UTC
### Expected behavior
Tunnels rendered similar to tunnels on regular roads.
### Actual behavior
Tunnels are not rendered and are therefore indistinguishable from raceways without tunnels.
### Links illustrating the problem
https://www.openstreetmap.org/way/176695255
https://www.openstreetmap.org/way/397149462
https://www.openstreetmap.org/way/712371562
https://www.openstreetmap.org/way/175563701

**Comment by imagico** [comment] 2020-12-21 18:55
highway=raceway + tunnel=yes: 118 uses.
highway=raceway + covered=yes: 84 uses.

**Comment by matkoniecz** [comment] 2020-12-23 09:17
Duplicate of display tunnels and bridges for highway=raceway #1688

**Closed by matkoniecz** 2020-12-23 09:17 UTC
Labels: new features, roads
