### ISSUE TITLE
Render name of leisure=horse_riding

### ISSUE THREAD

**Issue by Nic787** [gravitystorm/openstreetmap-carto#4368] opened 2021-04-11 01:59 UTC
### Expected behavior

We should be able to see the name of the horse riding facility.

### Actual behavior

Name is not showing on both area and node.
I know you can use farmyard and give it a name, but sometimes the actual borders are not clear enough to use this tag and it's much easier to use a node or a small area for the facility.

### Links and screenshots illustrating the problem

![image](https://user-images.githubusercontent.com/11185348/114289697-fe049200-9a47-11eb-83d1-84ae153916ff.png)

Thank you

**Comment by HolgerJeromin** [comment] 2021-04-11 14:07
Thanks for opening this issue. 
This is a duplicate of #2344

**Comment by pnorman** [comment] 2021-04-11 17:39
duplicate of #2344

**Closed by pnorman** 2021-04-11 17:39 UTC
