### ISSUE TITLE
Floating solar panel not rendering

### ISSUE THREAD

**Issue by tntchn** [gravitystorm/openstreetmap-carto#4449] opened 2021-08-18 08:56 UTC
Hi all,
I'm mapping some solar farm in my country and have got some problems. There are more and more floating PV panel installations nearby my home and I found that those installations cannot be rendered correctly in the OSM standard layer.

### Agongdian Reservior 10 MW installation ([osm object](https://www.openstreetmap.org/way/961524179))
This is a basic case of a floating PV project, not rendered.

![截圖 2021-08-18 下午4 04 17](https://user-images.githubusercontent.com/15895303/129861742-7868caed-3e98-4654-bd6a-63658f0025cc.png)

<img src="https://user-images.githubusercontent.com/15895303/129862072-8a769d10-b65e-4be7-8110-5f54b1b4d627.jpg" width="500" />

### Sanyeipi 1 MW installation ([osm object](https://www.openstreetmap.org/way/793306489))
This is a small installation over a farm basin/pond, with a `layer=1` tag, still not rendered.

![截圖 2021-08-18 下午4 19 58](https://user-images.githubusercontent.com/15895303/129863685-fc2f981a-65ae-47bc-918f-8dcc9b2fc4a5.png)

<img src="https://user-images.githubusercontent.com/15895303/129863753-fda3c62f-4b98-418c-84aa-5d3ed32479c2.jpg" alt="高雄農田水利會三爺埤" width="500" />

### Xiashepi 1.6 MW installation ([osm object](https://www.openstreetmap.org/way/793404532))
This is an interesting case. The pond is tagged with `intermittent=yes`, and the PV panel seems to be rendered below the blue stripes.

![截圖 2021-08-18 下午4 26 19](https://user-images.githubusercontent.com/15895303/129864663-531ac1ec-862d-437c-9af0-aaf412880357.png)

<img src="https://user-images.githubusercontent.com/15895303/129865109-8cf62bfd-dd31-4a34-b6a5-86d2d8ce360d.jpg" alt="Xiashepi solor panel" width="500" />

### Chang Bin 181 MW Floating Solar Farm ([osm object](https://www.openstreetmap.org/way/933153632))
I think the method to tag this solar farm should be discussed in other places, now it render the name but no area.

![截圖 2021-08-18 下午4 36 35](https://user-images.githubusercontent.com/15895303/129866263-4611b929-505b-413a-8fef-579b8528a233.png)

<img src="https://user-images.githubusercontent.com/15895303/129867428-7f96ad1b-2e42-4e6e-91fa-17fd0115210f.jpg" alt="Chang Bin Floating Solar Farm" width="500" />

## Possible fix
It is possible to set the solar panel as inner of a multipolygon to render correctly, but since the places where the PV panels installed are still a part of the water body, I think it is not a good practice to do so.

The power panel should be rendered as `man_made=pier` or `man_made=breakwater`, drawn overlaid the water to show that there is a solar farm on the map.

**Comment by imagico** [comment] 2021-08-18 09:37
Thanks for the report, this is a duplicate of #4345.

As said there a well established tagging for floating power generators would be important to provide a meaningful rendering.

**Closed by imagico** 2021-08-18 09:37 UTC
