### ISSUE TITLE
Tram lines broken at bridge ends

### ISSUE THREAD

**Issue by RicoElectrico** [gravitystorm/openstreetmap-carto#2646] opened 2017-05-27 21:51 UTC
http://www.openstreetmap.org/note/1008823#map=19/50.27001/19.11184&layers=N

There are gaps in tram tracks at the ends of bridges. It seems that data is OK.

**Comment by pnorman** [comment] 2017-05-27 22:10
![image](https://cloud.githubusercontent.com/assets/1190866/26524626/41278976-42ee-11e7-9180-7b3f82b2107f.png)

Please include a cropped screenshot when [reporting issues](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#reporting-issues).

Given the ordering constraints we have the only possible fix I can see would be to change the line-cap on road bridges to butt, but that would cause more problems elsewhere and I think be worse overall.

I'll leave the issue open in case anyone else has different ideas.

**Comment by math1985** [comment] 2017-05-27 22:15
This is a duplicate of #934.

**Closed by math1985** 2017-05-27 22:15 UTC
