### ISSUE TITLE
Rendering of amenity=parking is doubled

### ISSUE THREAD

**Issue by Grillmannen** [gravitystorm/openstreetmap-carto#3866] opened 2019-09-03 20:37 UTC
### Expected behavior
A parking lot should only be rendered with a P once on the centroid of the area

### Actual behavior
In the example it's rendered twice with no visible data error

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/116351847
https://www.openstreetmap.org/#map=19/56.06334/12.70951
![image](https://user-images.githubusercontent.com/5609686/64205357-0d008700-ce98-11e9-81e1-0c03ff74417e.png)

**Comment by cwmke** [comment] 2019-09-04 05:38
Hey @Grillmannen, this looks like a duplicate of #3860. You might want to close this and add your info there as they have already begun discussing it.

**Closed** 2019-09-04 08:34 UTC
