### ISSUE TITLE
Labels for railway=station areas not rendered

### ISSUE THREAD

**Issue by planemad** [gravitystorm/openstreetmap-carto#2097] opened 2016-03-25 11:18 UTC
<img width="307" alt="screenshot 2016-03-25 16 44 00" src="https://cloud.githubusercontent.com/assets/126868/14043307/ca5d7184-f2a8-11e5-9645-e8cf4476f3ab.png">
https://www.openstreetmap.org/way/66239966#map=17/10.99836/76.96558

The label only shows up if there is an additional `building` tag, but then one would have multiple stations if there are more than one entrance building.

**Comment by dieterdreist** [comment] 2016-03-25 19:32
sent from a phone

> Am 25.03.2016 um 12:18 schrieb Arun Ganesh <notifications@github.com>:
> 
> The label only shows up if there is an additional building tag, but then one would have multiple stations if there are more than one entrance building


+1, stations and buildings are different things and the building tag has nothing to do with an (active) train station, besides some people using it like this ;-)
Any train station will also have a part with rails and might have no building at all

**Comment by kocio-pl** [comment] 2016-03-25 19:56
Subset of https://github.com/gravitystorm/openstreetmap-carto/issues/2094.

**Comment by martinum4** [comment] 2016-04-24 03:00
you are using the railway=station tag wrong, it is not intended for areas, just for nodes, it is intended to contain all i think what you want here is landuse=railway, it is rendered like an industrial area, for better instructions see: http://wiki.openstreetmap.org/wiki/File:A-simple-station.svg

**Comment by dieterdreist** [comment] 2016-04-24 07:01
sent from a phone

> Il giorno 24 apr 2016, alle ore 05:00, martinum4 <notifications@github.com> ha scritto:
> 
> you are using the railway=station tag wrong, it is not intended for areas, just for nodes,


no, using it on a node is very old, approximate style and an area is clearly better, as stations always do have a significant spatial extension.


> it is intended to contain all i think what you want here is landuse=railway, it is rendered like an industrial area, for better instructions see:


landuse=railway is not for stations, it is for all areas with railway related use.

**Comment by matkoniecz** [comment] 2016-04-24 09:16
> you are using the railway=station tag wrong, it is not intended for areas, just for nodes

In overhelming majority of cases tagging railway station as areas makes more sense than tagging as nodes.

**Comment by matkoniecz** [comment] 2016-04-24 09:17
> landuse=railway is not for stations, it is for all areas with railway related use.

To make it more clear: landuse=railway is not only for stations, it is for all areas with railway related use.

**Comment by martinum4** [comment] 2016-04-24 09:57
Well, if you want to map it as a area then where do you draw the line where a station begins? at the first switch that is controlled from it? at the entry/exit signals? at the platforms?

**Comment by dieterdreist** [comment] 2016-04-24 10:11
sent from a phone

> Il giorno 24 apr 2016, alle ore 11:57, martinum4 <notifications@github.com> ha scritto:
> 
> Well, if you want to map it as a area then where do you draw the line where a station begins? at the first switch that is controlled from it? at the entry/exit signals? at the platforms?


this discussion does not belong here, please ask your questions on the tagging ML

**Comment by matkoniecz** [comment] 2016-06-17 22:19
I am confused. I wanted to fix it as short break from more complex things but I am missing something. Layer code is

```
  - id: "stations"
    class: "stations"
    name: "stations"
    geometry: "point"
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: |-
        (SELECT
            way,
            name,
            railway,
            aerialway,
            CASE railway 
              WHEN 'station' THEN 1 
              WHEN 'subway_entrance' THEN 3
              ELSE 2
            END
              AS prio
          FROM planet_osm_point
          WHERE railway IN ('station', 'halt', 'tram_stop', 'subway_entrance')
            OR aerialway = 'station'
          ORDER BY prio
        ) AS stations
    properties:
      minzoom: 12
    advanced: {}
  - id: "stations-poly"
    name: "stations-poly"
    class: "stations"
    geometry: "polygon"
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: |-
        (SELECT
            way,
            name,
            railway,
            aerialway
        FROM planet_osm_polygon
        WHERE railway IN ('station', 'halt', 'tram_stop')
          OR aerialway = 'station'
        ) AS stations_poly
```

with rendering in stations.mss, and I see no bug here (and I see no reason why https://github.com/gravitystorm/openstreetmap-carto/blob/master/stations.mss would treat polygons differently as far as labels are concerned).

**Comment by kocio-pl** [comment] 2016-12-03 01:24
This area is retagged as landuse=railway, so I guess this issue can be closed now if no other similar problems are found. Unless this tagging is reverted as misused, so we could look if the bug is still here.

**Comment by kocio-pl** [comment] 2016-12-15 02:47
This bug is real - I've made a tuned import and there's no label really. 

It also doesn't render area color - probably area=yes is needed, which should not be needed, since I can't think of linear station and [wiki page](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dstation) makes it clear.

See also this example:
https://www.openstreetmap.org/way/114507529

**Comment by Tomasz-W** [comment] 2018-07-03 08:56
In both cases I can see a label 
https://www.openstreetmap.org/way/66239966
or an icon with label
https://www.openstreetmap.org/way/114507529

@kocio-pl Is there still some issue?

**Comment by matkoniecz** [comment] 2018-07-03 09:13
>  https://www.openstreetmap.org/way/66239966

See tags (landuse=railway, not railway=station)

>  https://www.openstreetmap.org/way/114507529

Hm, this one may be viable example.

**Comment by kocio-pl** [comment] 2018-07-03 12:07
I'm not sure right now, could someone check if the problem is still here, just in case?

**Comment by matkoniecz** [comment] 2018-07-03 12:09
I looked through PRs for now, I see nothing claiming to fix it.

Maybe it was fixed accidentally.

**Comment by Tomasz-W** [comment] 2018-07-03 12:59
@kocio-pl 
Another examples showing no-issue:
https://www.openstreetmap.org/way/479178948
https://www.openstreetmap.org/way/368474789

**Comment by kocio-pl** [comment] 2018-07-03 13:05
OK, so I'm closing it - it might be reopened if we're wrong, of course. Thanks for testing!

**Closed by kocio-pl** 2018-07-03 13:05 UTC
Labels: station
