### ISSUE TITLE
Render the area of maritime / ship museums

### ISSUE THREAD

**Issue by dandv** [gravitystorm/openstreetmap-carto#2672] opened 2017-07-05 00:52 UTC
[Tag:historic=ship](http://wiki.openstreetmap.org/wiki/Tag:historic%3Dship) is "for a decommissioned ship/submarine which has become a tourist attraction and generally remains in one place". The page links to a few examples, such as this one:

![image](https://user-images.githubusercontent.com/33569/27845186-69e7704a-60e1-11e7-8bcf-7c5fe3b503e7.png)

A visitor only sees the name of the museum floating on the  water. Can OSM render that area on the map, so it's closer to the underlying data?

![image](https://user-images.githubusercontent.com/33569/27845194-7eece8c6-60e1-11e7-890c-417a57db62a0.png)

**Comment by imagico** [comment] 2017-07-11 12:55
Just noticed this has not been answered yet.

There are about 500 uses of `historic=ship` on areas not all of which are actually swimming, 140 of these also have a building tag, half of them use `building=ship`.  There is a total of 160 `building=ship`.

I am mostly wondering about stationary ships that are not historic and not museums.

Anyway i see no problem rendering areas with `historic=ship` like buildings - it seems sufficiently well established that the tag is not meant to be used for wrecks.

**Comment by dieterdreist** [comment] 2017-07-11 13:13
2017-07-11 14:55 GMT+02:00 Christoph Hormann <notifications@github.com>:

>
> I am mostly wondering about stationary ships that are not historic and not
> museums.
>


a stationary ship is always "historic", or do you know other examples? For
the avoidance of doubt, "historic" doesn't have a min age requirement and
isn't defined in any way if not tautological as "being of historic
interest" (this isn't an objective criterion either).

Cheers,
Martin

**Comment by imagico** [comment] 2017-07-11 13:31
I don't want this to drift again into a tagging discussion so just quickly: The tag documentation for `historic=ship` says _tag for a decommissioned ship/submarine_ - indicating it is meant for ships that have been originally built and used for a different purpose.  A purpose built houseboat is therefore quite clearly not a `historic=ship` - for this we have `building=houseboat` - which is however limited to housing purposes by definition.

**Comment by dieterdreist** [comment] 2017-07-11 16:23
sent from a phone

> On 11. Jul 2017, at 15:31, Christoph Hormann <notifications@github.com> wrote:
> 
> I don't want this to drift again into a tagging discussion so just quickly: The tag documentation for historic=ship says tag for a decommissioned ship/submarine - indicating it is meant for ships that have been originally built and used for a different purpose


yes, ships and some boats (submarines), doesn't say anything about other boats though (you might argue they are included, literally they are not)


> . A purpose built houseboat is therefore quite clearly not a historic=ship


it isn't a ship in any regard, nor is it a submarine 


> - for this we have building=houseboat - which is however limited to housing purposes by definition.


there are also floating houses, usually for housing, but may also fulfill other purposes (community spaces for a floating community etc.). Btw: according to the wiki it is sufficient that the houseboat is designed as a home (although this seems copied from wikipedia and there hasn't been a discussion about this definition in the osm community, afaik)

**Comment by sabas** [comment] 2017-07-14 09:57
Here are two submarines which are accessible in a museum exposition

http://www.openstreetmap.org/way/41677804
http://www.openstreetmap.org/way/162825962

**Comment by Bibi56** [comment] 2017-07-17 20:55
> a stationary ship is always "historic", or do you know other examples?

You may consider [La Recourance](http://www.openstreetmap.org/way/356798573/history#map=18/48.37983/-4.48581) as historic (it's a replicate of an historic vessel). N.B.: the pontoon is missing here.
But [L'Abeille Bourbon](http://www.openstreetmap.org/way/356798560/history#map=18/48.38024/-4.48628) is an active work-boat (a tow-ship). Note: a previous tag building=boat has been removed.
Note: there are weather conditions for presence at this place (Beaufort scale < 5). And tide conditions as well (no neap tide). Not speaking about distress alerts of course.

**Comment by HolgerJeromin** [comment] 2017-07-20 21:26
If a ship is not "always" at this place I would not map it.

**Comment by Bibi56** [comment] 2017-07-21 18:29
> If a ship is not "always" at this place I would not map it.

I wouldn't either and was surprised to see the vessels on the map. But it was not the question ;-).

Well if you tag it with conditions, then it makes sense. You map show shops even if they are closed. Ideally you add opening hours.

Both vessels can be visited. For La Recouvrance the pontoon has a sign on it, we could remove the Recouvrance and add "Ponton de la Recouvrance" on the pontoon, but it's more a description than a name.

Now if you're looking for [La Recouvrance, Brest](http://www.openstreetmap.org/search?query=la%20recouvrance%2C%20brest), you find it. And enjoy the sail trip later.
You won't ask for "Ponton de la Recouvrance, Brest", would you?

For ferries, you don't have the issue as the route is shown on the map.

**Comment by pnorman** [comment] 2017-08-07 07:55
> a stationary ship is always "historic", or do you know other examples?

There are abandoned ships that are permanently moored up - at least for several years.

**Comment by Tomasz-W** [comment] 2018-02-25 12:16
Remember, that in OSM we map mainly ground level. The outline from 
https://github.com/gravitystorm/openstreetmap-carto/issues/2672#issue-240514816
is in some way "in the air".

Ship cross-section to show what I mean:
http://directtrafficsolutions.com/wp-content/uploads/2016/02/thehull.jpg

We could consider rendering it like man_made=pier or man_made=bridge - another objects "in the air".

**Comment by dieterdreist** [comment] 2018-02-25 15:45
2018-02-25 13:16 GMT+01:00 Tomasz Wójcik <notifications@github.com>:

> Remember, that in OSM we map mainly ground level. The outline from
> #2672 (comment)
> <https://github.com/gravitystorm/openstreetmap-carto/issues/2672#issue-240514816>
> is in some way "in the air".
>

I agree it should be so, but it isn't actually documented, on the contrary,
the building:parts definition says on building=* " there should be one area
(closed way) marking the outline of the whole building, tagged with building
<https://wiki.openstreetmap.org/wiki/Key:building>=*"
"The whole building" to me suggests the maximum over all floors, projected
on the ground.

**Comment by polarbearing** [comment] 2018-02-26 12:21
Area outline rendering for museum is planned in #2704. Thus this issue would be solved en passant, I suggest to close as duplicate.

**Comment by Tomasz-W** [comment] 2018-02-26 14:08
> Area outline rendering for museum is planned in #2704. Thus this issue would be solved en passant, I suggest to close as duplicate.

Not all of these ships are museums (some of them are tagged just as historic=ship) so it isn't the same thing. 
Notice also, that outline without anything inside would look a little bit weird on water areas.

**Comment by matkoniecz** [comment] 2018-05-09 15:10
Closing as duplicate of #2704

In addition permanently moored ships are frequently tagged with building tag - see https://wiki.openstreetmap.org/wiki/Buildings and https://wiki.openstreetmap.org/wiki/Tag:building%3Dhouseboat

**Closed by matkoniecz** 2018-05-09 15:10 UTC
Labels: amenity-points, cartography

**Comment by BertMule** [comment] 2023-06-25 15:45
I keep stumbling (modelling) into historic/museum ships. Some of them quite famous, like HMS Belfast. And it is important to note they are usually quite static.
They are either invisible, or by lack of better alternative, modelled as building.

The latter is not bad if it is a houseboat (which is common practice in the Netherlands, being addresses).
But I would still prefer to have a separate tag for real ships. That could also result in a more distinctive rendering.

I noticed the reference to https://github.com/gravitystorm/openstreetmap-carto/issues/2704. (Also https://github.com/gravitystorm/openstreetmap-carto/issues/4272 is related, though less static.)
But disappointingly, both that and this issue are effectively abandoned since 2017!
