### ISSUE TITLE
render landuse = plant_nursery

### ISSUE THREAD

**Issue by geostonemarten** [gravitystorm/openstreetmap-carto#2303] opened 2016-08-24 11:57 UTC
Hi,

There is no render for landuse = plant_nursery. For want of anything better, I think it can be the same as landuse =  greenhouse_horticulture.

Thanks.
Jérôme

**Comment by daganzdaanda** [comment] 2016-08-24 17:50
Hi, I agree with your request. But there's already an issue about this: #1772

**Comment by pnorman** [comment] 2016-08-24 23:49
Duplicate of #1772

**Closed** 2016-08-24 23:49 UTC
Labels: duplicate
