### ISSUE TITLE
Render recycling_type=centre on areas

### ISSUE THREAD

**Issue by coolultra1** [gravitystorm/openstreetmap-carto#4586] opened 2022-07-07 21:14 UTC
`recycling_type= centre` is mostly used on areas, though only utilizes the default `amenity=recycling`-rendering, which is a single icon. This can make it hard to tell the exact area of a recycling centre and really, just doesn't look good. I think, an area rendering of this tag would be appropriate.

Example of current rendering:
![image](https://user-images.githubusercontent.com/77762440/177872326-422cbd49-a204-4012-93ae-eef1ca0f1a19.png)

**Comment by coolultra1** [comment] 2022-07-07 21:47
@pnorman Am proposing to render areas with `recycling_type=centre`, which is, to be exact, an area of interest, just like, when mapped correctly, `amenity=school` is, which, IIRC, has areas with it rendered.

**Comment by imagico** [comment] 2022-07-08 14:40
I am not very keen of rendering additional features with no physically defined extent with polygon fills.  

Neither of the corresponding wiki pages:

https://wiki.openstreetmap.org/wiki/Tag:amenity=recycling
https://wiki.openstreetmap.org/wiki/Tag:recycling%20type=centre

contains even hints at what constitutes the verifiable perimeter of a place like that.  If mappers want to document a verifiable perimeter they can typically do so (by mapping the barrier defining it - like a fence, which would probably apply in your case as well)

In principle we could use the fill of landuse=industrial for such, however recycling_type=centre is widely used for small self service places open 24/7 without access restrictions and with a few containers for throwing waste into - for which rendering it like an industrial area seems misleading.  And nothing prevents mappers from mapping an amenity=recycling that constitutes an industrial facility with landuse=industrial explicitly.

**Comment by danieldegroot2** [comment] 2022-07-08 16:20
Welcome back to GitHub @coolultra1 ,

This issue is a duplicate of #4529 .
Make sure to check for existing issues, please.

cc: @imagico

**Comment by imagico** [comment] 2022-07-08 18:10
Right, thanks, closing as duplicate.

**Closed** 2022-07-09 01:34 UTC
Labels: duplicate
