### ISSUE TITLE
Add rendering for amenity=bicycle_repair_station

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3069] opened 2018-02-12 20:17 UTC
A public-access stations equipped usually with air pump, screwdriver, wrenches, allen keys etc. Very useful feature.
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_repair_station

About 2800 uses.
https://taginfo.openstreetmap.org/tags/amenity=bicycle_repair_station

Icon proposal:
![amenity bicycle_repair_station](https://user-images.githubusercontent.com/25656654/36116934-5299d82c-1038-11e8-96a7-c9a78560f166.png)

**Comment by kocio-pl** [comment] 2018-02-12 20:30
It's a duplicate of #1353, let's discuss it there.

**Comment by kocio-pl** [comment] 2018-02-12 20:41
Sorry, it seems that we had 2 PRs which were rejected then (#1353 and #1864), but no issue ticket before.

We already have the icon, so making a PR would be rather easy now:
https://github.com/gmgeo/osmic/blob/master/shop/repair-bicycle-14.svg

**Comment by Tomasz-W** [comment] 2018-02-12 20:48
Notice that @nebulon42 icon indlude single-sided wrench, and it could be confused with the key from amenity=bicycle_rental.
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/rental_bicycle.svg

I don't know is brown color (from PR test renderings) right for this feature. Bicycle parkings and rentals are blue.

**Comment by nebulon42** [comment] 2018-02-12 21:05
Rental has the thicker side on the left while repair has the thicker side on the right. This should work against confusion.

**Comment by Tomasz-W** [comment] 2018-02-12 21:28
Anyway, I would like to see a test rendering with my icon, so I'm putting Gist link:
https://gist.github.com/Tomasz-W/b4641535717e8b36ae8fcae4acae95a3

**Comment by polarbearing** [comment] 2018-02-12 22:17
Voila. Still quite similar on the first glance. I wonder if we might turn the repair icon 90 deg, so the bike comes in repair position, and the spanner easier to distinguish from the key. Or the bike upside down. 
![z18_bike_rent](https://user-images.githubusercontent.com/8266355/36122667-778dc5a0-104a-11e8-8de3-2e82bc2d4770.png) ![z18_bike_repair](https://user-images.githubusercontent.com/8266355/36122691-910a9e54-104a-11e8-8c9e-6f3797dd991e.png)

**Comment by Tomasz-W** [comment] 2018-02-13 07:44
For comparsion:
![amenity bicycle_repair_station](https://user-images.githubusercontent.com/25656654/36138413-a04686ea-1099-11e8-901d-cb2e21970675.png)  

 ![amenity bicycle_repair_station bok](https://user-images.githubusercontent.com/25656654/36138386-8dfe5d50-1099-11e8-8f43-f74066fab3a2.png)  

 ![amenity bicycle_repair_station oo](https://user-images.githubusercontent.com/25656654/36138332-3ff145d2-1099-11e8-96b2-87aa5500f641.png)

**Comment by polarbearing** [comment] 2018-02-13 10:21
The 90 deg in the middle works for me. Maybe with the wheels towards the spanner. 
The wheels up might be too hard to guess when you see it first.

**Comment by geowas-github** [comment] 2018-02-13 10:38
Yes, the second one is good. But I would switch bike and tool (so you can read the symbol from left to right). Then it will also have the wheels towards the tool, which I agree should be better.

**Comment by Tomasz-W** [comment] 2018-02-13 13:15
> I would switch bike and tool (so you can read the symbol from left to right)

Good point. Version with bike on the left side:
![amenity bicycle_repair_station bok](https://user-images.githubusercontent.com/25656654/36151627-4bd13fcc-10c8-11e8-8cd5-a756744e6283.png)


Gist link (with two versions of the icon): https://gist.github.com/Tomasz-W/9c66f9b37345fdb35f8f6cecce9fe925

**Comment by polarbearing** [comment] 2018-02-13 13:55
Wheels towards the spanner:
<img src=https://cdn.rawgit.com/polarbearing/8378030afdfa372eea39dfbff2ace454/raw/477466a9e2a9d2da4e1544ab3b3f1998acde6db5/bike-repair-3.svg>
[source](https://gist.github.com/polarbearing/8378030afdfa372eea39dfbff2ace454)

**Comment by Tomasz-W** [comment] 2018-02-13 14:20
Version with wheels to the edge reminds me wall hangs, so I like it more.
http://www.wirecrafters.com/images/products/bicycle-storage/bicycle-wall-rider/Bicycle-Wall-Rider-Bike-Storage-Hooks.jpg
http://coolamon.org/wp-content/uploads/2017/10/valuable-how-to-hang-a-bike-on-wall-with-best-25-storage-solutions-ideas-only-pinterest-shed.jpg

We should choose between this: 
![amenity bicycle_repair_station](https://user-images.githubusercontent.com/25656654/36154283-3bf5d67c-10d1-11e8-9fa5-69fda7adaad4.png) 
and this: 
![amenity bicycle_repair_station bok](https://user-images.githubusercontent.com/25656654/36154294-438ea332-10d1-11e8-8d99-92005457670a.png)

**Comment by kocio-pl** [comment] 2018-02-13 14:22
It helps to use numbers as a reference if there are few propositions and they are changing into new versions.

**Comment by geowas-github** [comment] 2018-02-13 14:41
I would go for #2 (with bike in the left side)

**Comment by kocio-pl** [comment] 2018-02-13 14:45
On GitHub hash+number links to some old issues. 😃

**Comment by kocio-pl** [comment] 2018-02-13 15:12
We already show [car repair](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/car_repair.svg), for me it's better if they are similar and they are distinct enough for me (see https://github.com/gravitystorm/openstreetmap-carto/issues/3069#issuecomment-365061697), so I still prefer Osmic version.

**Comment by Tomasz-W** [comment] 2018-02-13 17:49
I just don't like this single-sided wrench. If you want, I can make a car repair icon with double-sided wrench, and both icons will match each other.

**Comment by polarbearing** [comment] 2018-02-14 01:51
Not sure about the colours. We need to distinguish a repair shop (where you have your bike repaired and pay money) from the repair-station (self service, more on-the-go). Thus I would see the repair-station in blue (as in the render test above), it is already distinguished from rental by the hanging bike. To summarize:
* shop=car, car-repair, bike, bike-repair --> violet
* car-rental, bike-rental, bike-self-repair, fuel, air (tyre pressure) --> blue

**Comment by kocio-pl** [comment] 2018-02-19 17:26
I would prefer to show services (including repairs) in brown, selling things in violet and blue only when this is something you do to get the vehicle or (rental) let it rest (parking).

**Comment by lakedistrictOSM** [comment] 2018-03-17 22:12
The only `amenity=bicycle_repair_station`s that I've ever come across have only had air pumps (`service:bicycle:pump=yes`). IMO this is as useful to a cyclist as a petrol station is to a motorist, therefore the icon should be in blue. This will also match `amenity=bicycle_parking`.

**Comment by Martin-Lbg** [comment] 2018-07-05 19:00
I like the two "repair" icons from previous post. The same colour and very similar in shape they show, that the two transportation modes (car and bicycle) benefit from similar amenities.

**Comment by polarbearing** [comment] 2018-07-26 10:19
The non-drivable positions (upside, sidewards) were chosen somewhere above to distinguish repair from rental situations more clearly.
However we could also think about the spanner under the vehicle (being lifted for repair), while the rental key is above.

**Comment by Tomasz-W** [comment] 2018-07-29 08:04
@polarbearing repair icons with spanner under the vehicle:
* amenity=bicycle_repair_station
![amenity bicycle_repair_station 2](https://user-images.githubusercontent.com/25656654/43364202-2fb7067a-9316-11e8-835a-cf8403af64cf.png)
* amenity=car_repair
![amenity car_repair 2](https://user-images.githubusercontent.com/25656654/43364204-36dc41f4-9316-11e8-8c5b-55bc58e7553e.png)

I vote for 'above the vehicle' versions in both cases.

**Comment by polarbearing** [comment] 2018-07-29 08:54
Well I find your 'spanner under the vehicle' convincing. As said, symbolising 'lifted for repair'.

**Comment by Tomasz-W** [comment] 2018-07-29 09:34
Both versions are in Gist links in https://github.com/gravitystorm/openstreetmap-carto/issues/3069#issuecomment-401627495. We should choose better-fitting version after some test renderings.

**Comment by Martin-Lbg** [comment] 2018-07-29 16:53
Today I discussed these issues with some friends, we came to the following suggestions

- the tool above the vehicle gives the icon a closer, square look (the tool under the vehicle might be confused with some other tag just showing a single tool (=some kind of generic workshop) --> we vote for "tool above bicycle"

to distinguish the "rental place" from the "service station" I suggest to use a brown color like 

https://user-images.githubusercontent.com/25656654/42137842-cd4f6bb0-7d73-11e8-9417-33e5d1fdb921.png 

- additionally the tool above the bicycle opens a little space on the right of the icon between the bicycle and the tool which we could use to put a green rectangle symbolizing an air pump (some of this unattended service stations provide air pumps (tagged with service:bicycle:pump), most do not provide compressed air thus not allowing for the tag "amenity=compressed-air"

I suggest to color this additional rectangle green, because pressured air is sold in steel-bottles with this color-code. All other color codes (ISO, ANSI) I researched this afternoon are for large pipes and facilities not for such small devices as a bicycle air pump. It is a light green (hex 00FF01)

Sorry, I'm still in the process of getting my Windows-box to run all of the parts of OSM-development, therefore I cannot help directly at the moment, but I hope to get this up and running in a few weeks (with a new computer I presume)

**Comment by kocio-pl** [comment] 2018-07-29 16:56
Did you try just running Linux (Ubuntu for example) in the VirtualBox?

**Comment by meased** [comment] 2018-07-29 17:57
I vote for "tool above". The spanner/key icons should provide enough distinction.

I don't think a green rectangle would mean "air pump" to anyone without further explanation. This is a use case for [clickable POIs](https://github.com/osmlab/osm-planning/issues/16).

**Comment by polarbearing** [comment] 2018-07-29 19:21
This icon should not introduce little dots in other colours to symbolize something obscure. 

On the map you won't have the rental and the repair side by side to spot the differences, so the only way to distinguish the key from the spanner is the gable-end of the spanner. 

I would not rely just on colour to distinguish them since we also want to plan to differentiate between repair-as-a-service and self-repair stations.

**Comment by Tomasz-W** [comment] 2018-08-01 09:44
@Adamant36 If you are ready you can make test renderings with different icons versions (bicycle repair and car repair) from https://github.com/gravitystorm/openstreetmap-carto/issues/3069#issuecomment-401627495. Then we choose better one for PR.

**Comment by Adamant36** [comment] 2018-08-01 20:57
@Tomasz-W is it suppose to be amenity=car_repair up above or shop=car_repair? Because it seems that amenity=car_repair is depreciated and there are no uses of it. If its shop=car_repair, would you mind updated the posts referencing it? Thanks.

**Comment by Tomasz-W** [comment] 2018-08-02 06:08
@Adamant36 Can you also take care of https://github.com/gravitystorm/openstreetmap-carto/issues/2658?

**Comment by Adamant36** [comment] 2018-08-02 06:17
@Tomasz-W sure. I'm waiting for the shop=paint icon to get merged. Then I'll do this one and that issue to if there is feedback on which icon to use here by then. Otherwise I'll do leisure=outdoor_seating next.

**Comment by Martin-Lbg** [comment] 2018-08-02 06:38
I prefer the wrench being above the vehicles (both bicycle and car)

**Comment by polarbearing** [comment] 2018-08-02 09:16
I find the wrench being below the vehicles (both bicycle and car) easier to understand and to distinguish.

For the colour #2658, I still prefer shop=car, car-repair, bike, bike-repair --> violet

**Comment by Tomasz-W** [comment] 2018-08-02 10:01
We shouldn't be glued to colours in this way. Yeah, it's **shop**=car_repair, but it's not a place where you go to buy some goods but to get some service. It makes this feature closer to amenity key than a shop one. Rendering it in amenity-brown will be intutive, and violet could be confusing for map users.

**Comment by polarbearing** [comment] 2018-08-02 11:32
Yes it's a service, like hair dresser and nail studio, which we do purple:
<img src=https://user-images.githubusercontent.com/8266355/36122691-910a9e54-104a-11e8-8c9e-6f3797dd991e.png>
(The image is from [above](3069#issuecomment-365081861) and shows blue for the bike repair, which should only be used for self-repair stations)

Brwon has amenities like bar, restaurant, museum, which do not compare to car/bike-repair.

**Comment by meased** [comment] 2018-08-02 16:05
Would blue really be that crazy? (For both bike and car repair.) They're transport related, and (based on the above comments) they don't seem to cleanly fit into either the amenity or shop categories.

We render fuel stations in blue and I could make a pretty good argument that they should be violet.

**Comment by Tomasz-W** [comment] 2018-08-02 20:00
@meased See https://github.com/gravitystorm/openstreetmap-carto/issues/3069#issuecomment-365296071

**Comment by dieterdreist** [comment] 2018-08-03 00:15
sent from a phone

> On 2. Aug 2018, at 18:07, meased <notifications@github.com> wrote:
> 
> Would blue really be that crazy? (For both bike and car repair.) They're transport related, and (based on the above comments) they don't seem to cleanly fit into either the amenity or shop categories.


I agree with blue for bicycle repair stations

**Comment by Tomasz-W** [comment] 2018-08-03 05:34
@Adamant36 After discussion summary, I think you should use amenity-brown 'wrench above' versions in both cases.

**Comment by polarbearing** [comment] 2018-08-03 08:36
I don't get the system. You argue for the repair services to use the same colour than tourism-brown, but propose to move tourism-related gastronomy to a different colour? Maybe we should have a meta-ticket first to clarify the colour schemes and what concept they relate to, before shuffling individual cases around.

**Comment by Tomasz-W** [comment] 2018-08-03 08:56
> tourism-related gastronomy

Going to a restaurant or some fast food in your own city makes you a tourist then? Interesting...

**Comment by kocio-pl** [comment] 2018-08-03 13:00
The problem of classification is that many objects can belong to multiple categories. It might be a problem, but it also gives us some space to tune the things a bit. Maybe we could discuss the system, but we have too few colors available to make it strict and rich, color reuse is already necessary (see the problem with offices - https://github.com/gravitystorm/openstreetmap-carto/pull/3163#issuecomment-378745427).

I'm currently not interested too much in object colors (including gastronomy), so if anyone is interested, please open the issue and - more important - lead the discussion about it.

**Comment by Adamant36** [comment] 2018-08-04 03:06
@Tomasz-W OK. I'll probably do this next after outdoor seating gets merged. I also think it would be a good idea to open a meta ticket in order to discuss @polarbearing's concerns and the system in general though. Then we can change the color again later if need be. I don't know what to think about it at this point myself though, because like Kocio-pl says, lots of objects can belong to multiple categories. Plus, it seems like there's other priorities. So I rather get the icons on the map now in brown at least and deal with the color thing as a separate issue.

**Comment by dieterdreist** [comment] 2018-08-05 09:44
I’ve always opposed the idea to associate museums or artwork with tourism, but that’s how we tag them (me included), it is just a word (that doesn’t hit it nicely), seeing food related amenities as tourism related neither is helpful from my point of view (although for some it is the case). Therefore I would not insist in brown for tourism related stuff.

Bicycle repair stations to me are a feature similar to the compressed air facilities you find at petrol stations, a place you can go to do basic fixes “on the go”/ while you are not at home.

**Comment by Adamant36** [comment] 2018-09-10 01:49
What do you think on this one @Tomasz-W? Wrench above and amenity brown for both? It seemed like it was mixed on what to go with, but the discussion appears to have stalled out. So id like to do the PR and get it rendered already if its possible.

**Comment by Tomasz-W** [comment] 2018-09-10 05:45
Surely wrench above in both icons, but as we have around 50:50 for amenity-brown/ transportation-blue, please make test renderings with both colours to compare. It would be good to see how these both colours matches bicycle/ car parkings/rentals placed nearby.

**Comment by Adamant36** [comment] 2018-09-13 19:35
@Tomasz-W, sorry about that. I really wanted to get it through before now myself. I was waiting for the conversation to figure itself out and it took longer then I expected. Plus, I got distracted with other stuff. I did some looking around with car repair and seems that it has some weird code and is render as a purple icon with brown text for some reason. So id like to just leave it as is except for updating the icon, and deal with it in another PR. That way we can get this done before #3370 at least. Here's some test renderings of bicycle repair stations in the mean time though, with both brown and blue. I don't know if they are the best spots, but I can find more if necessary. I'll do a PR for it as soon as its figured out and maybe @kocio-pl can fast track it if need be. Since there's already been a lot of discussion here. Otherwise, I'll feel a little like I failed on it too. 
![bike repair blue 1](https://user-images.githubusercontent.com/30259065/45511242-53257d80-b751-11e8-853e-46ef5f42f11d.png)
![bike repair brown 1](https://user-images.githubusercontent.com/30259065/45511247-57ea3180-b751-11e8-8c06-1d801f3ab051.png)
![bike repair blue 2](https://user-images.githubusercontent.com/30259065/45511255-5caee580-b751-11e8-9e0b-bc882c51456f.png)
![bike repair brown 2](https://user-images.githubusercontent.com/30259065/45511262-620c3000-b751-11e8-84fc-b2477aae5e7d.png)
![bike repair blue 3](https://user-images.githubusercontent.com/30259065/45511277-69333e00-b751-11e8-932f-93ebfcecc9f0.png)
![bike repair brown 3](https://user-images.githubusercontent.com/30259065/45511291-6fc1b580-b751-11e8-98ec-8aa75f54c916.png)
![bike repair blue 4](https://user-images.githubusercontent.com/30259065/45511299-78b28700-b751-11e8-9d60-266b81d946b4.png)
![bike repair brown 4](https://user-images.githubusercontent.com/30259065/45511309-823bef00-b751-11e8-96d1-b9606719631a.png)

**Comment by Tomasz-W** [comment] 2018-09-13 20:12
I think this feature in blue looks like more important than it actually is. As this is free-standing non-interactive small amenity, it should be in _amenity-brown_.

As https://github.com/gravitystorm/openstreetmap-carto/issues/2658 may be hard to resolve but on the other hand it would be nice to have bicycle repair stations on map, you are right to do at least icon update and left colour inconsistency fixing for later (btw. there is the same problem with shop=massage, it's propably because we don't have _amenity-brown_ generic dot and also no _leisure-green_ generic dot)

**Comment by Adamant36** [comment] 2018-09-13 20:31
@Tomasz-W, I agree. I'll wait awhile to see if anyone else chimes in and then do the PR with amenity brown later tonight if there is no major objections.

**Comment by lakedistrictOSM** [comment] 2018-09-13 22:31
Given that this icon is one of the more detailed fiddly ones, it is more readable in a darker colour, so brown wins this time.

**Comment by Martin-Lbg** [comment] 2018-09-14 08:03
Ok, brown is it for me

Martin
Am 14. Sep. 2018, 00:31 +0200 schrieb lakedistrictOSM <notifications@github.com>:

**Comment by lakedistrictOSM** [comment] 2018-09-14 17:29
@polarbearing The colour choice was already between blue and brown based on logical reasoning, and I was just saying that it stood out better in brown. Of course blue might be better in other areas, but my comment was based on the example rendering above.

**Closed** 2018-09-21 01:11 UTC
Labels: amenity-points

**Comment by kocio-pl** [comment] 2018-09-21 01:22
> If it won't show on map till october (when most of people in Poland hide their bikes to the basement), I will consider it as my fail as unofficial icon-issues manager here ;) ;)

@Tomasz-W You can consider it your victory then. :smile: 

Of course meeting this goal (or any other single goal) is just kind of coincidence, but it's hard to measure coordinating work, so this symbolic win and the fact that things go smooth is quite good benchmark. I consider you not only good icon designer, but also talented project manager. Thanks! :heart:

**Comment by Martin-Lbg** [comment] 2018-09-23 09:15
Hello

You are my hero and made my Sunday, the icon did just now appear for my 
hometown. Thx for the great work



I did not yet hide my bicycle

Martin

Am 21. Sep. 2018, 03:22 +0200 schrieb kocio-pl <notifications@github.com>:

**Comment by Tomasz-W** [comment] 2018-09-23 09:47
https://www.openstreetmap.org/node/5404985083

If I would have some bicycle accident in the last week of my summer break and I will loose my memory. I would can at least find bicycle repair station on the map :sweat_smile: Thanks to all involved!

**Comment by polarbearing** [comment] 2018-09-23 11:32
Have a subborn little tile here. Dirty! Dirty! Dirty!.

```Tile is due to be rendered. Last rendered at Tue Sep 18 08:13:26 2018. Last accessed at Sun Sep 23 10:25:25 2018.```

I guess it has ADS.
