### ISSUE TITLE
Text rendering leisure=park / letter dropped

### ISSUE THREAD

**Issue by tilmanb** [gravitystorm/openstreetmap-carto#1398] opened 2015-03-17 16:44 UTC
At Z17 at this point http://www.openstreetmap.org/way/23490387#map=17/52.46751/13.35931 there is a rendering bug: The first letter of the name is not rendered. The way is tagged correctly as "Hans...", and this is rendered on all levels except z17, where it is only "ans".

![Hans lost his "H"](https://cloud.githubusercontent.com/assets/779297/6692484/1b22f66e-cccd-11e4-8852-b5af654770be.PNG)

**Comment by math1985** [comment] 2015-03-17 16:56
Tiles are up-to-date.

**Comment by polarbearing** [comment] 2015-03-17 18:33
But on different meta tiles:
file:///srv/tile.openstreetmap.org/tiles/default/17/16/26/40/240/136.meta
file:///srv/tile.openstreetmap.org/tiles/default/17/16/26/56/0/8.meta

**Comment by matkoniecz** [comment] 2015-03-17 18:38
Probably fixable by adding `marker-clip: false;` for landcovers - see https://github.com/gravitystorm/openstreetmap-carto/blob/2e22d987018e145fc5179e5034ab991998969be9/amenity-points.mss#L1057

**Comment by math1985** [comment] 2015-03-18 01:45
Duplicate of #1135.

**Closed by math1985** 2015-03-18 01:45 UTC
