### ISSUE TITLE
Airport names gone above zoom level 13

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#2664] opened 2017-06-25 16:57 UTC
This airport only has names at
http://www.openstreetmap.org/#map=12/23.5180/119.5891
http://www.openstreetmap.org/#map=13/23.5180/119.5891
When you reach
http://www.openstreetmap.org/#map=14/23.5180/119.5891
and above, the name is gone. Imagine an airport without a name.

**Comment by jidanni** [comment] 2017-06-25 17:01
http://www.openstreetmap.org/way/294458118

**Comment by kocio-pl** [comment] 2017-06-27 21:22
I guess this was by design to not clutter map when dealing with details (name and the icon too). You can see city names going away when zooming in for the same reason. What is your proposition, how long name and the icon should be visible (to which zoom level)?

**Comment by jidanni** [comment] 2017-06-27 23:05
Hmmm, how does Google deal with all that?

**Comment by jidanni** [comment] 2017-06-27 23:06
Maybe only have it disappear when the item fully covers the screen...
but perhaps not that simple.

**Comment by imagico** [comment] 2017-06-28 07:40
Airport icons and labels are not rendered at z14 and above.  The idea behind this is that at these scales the elements of the airport take precedence and the airport icon and label, placed at an arbitrary location, are not useful any more.  This of course does not really work for small airports at low latitudes at z14/z15.

Making this threshold dynamic based on airport size is not easily possible since most airports are mapped as nodes.  What would be possible is to increase the threshold a bit and/or render the label only without the icon at higher zoom levels - but not at the highest levels, at z17+ this will usually look silly.

**Comment by jidanni** [comment] 2017-06-28 16:21
Hmmm... paper topo maps never had to face this issue, because you couldn't
zoom them.

I suppose in all cases one should think "if I were to print out what is
shown on the screen to paper and make a tourist map that I could hand to
people, what should it say?" (Sorry I didn't help much.)

**Comment by aceman444** [comment] 2017-06-28 16:30
This is a problem when the whole airport is mapped as a node. Then in the high zoom the airport wanishes and there are no "more detailed elements of the airport to take precedence".

**Comment by jidanni** [comment] 2017-06-28 16:42
Hmmm, airports are often larger than entire cities. So maybe they should
follow the same creation rules/methods. (Sorry I'm not too much help
here again.)

**Comment by dieterdreist** [comment] 2017-06-29 15:27
sent from a phone

> On 28. Jun 2017, at 09:40, Christoph Hormann <notifications@github.com> wrote:
> 
> Making this threshold dynamic based on airport size is not easily possible since most airports are mapped as nodes.


maybe we can encourage mappers towards a transition to areas? Nodes aren't very suitable for representing huge areas (e.g. because they don't convey a size).

**Comment by imagico** [comment] 2017-06-29 15:49
We have had this discussion before (#1143), mapping airports as areas is often non-verifiable and we should not push mappers to map things differently just to make life easier for us.

I would suggest to concentrate on how to address the problem in rendering based on what is currently mapped.

**Comment by jeisenbe** [comment] 2019-08-24 07:13
I believe this issue can be partially resolved by changing the zoom level when the airport icon and label stop being rendered to be later. It doesn't appear that the current zoom level cut-off was based on an overall evaluation of global airport size, but rather what might look best for large, high-latitude airports.

**Closed** 2019-09-20 04:08 UTC
Labels: amenity-points, cartography
