### ISSUE TITLE
Housenumber are blocking landcover names

### ISSUE THREAD

**Issue by Circeus** [gravitystorm/openstreetmap-carto#1854] opened 2015-09-20 06:07 UTC
This is about the only reason I can figure out that [areas](http://www.openstreetmap.org/way/26698638) [such as](http://www.openstreetmap.org/way/161477308) [these](http://www.openstreetmap.org/way/188238939) don't have their names appearing at any zoom level. (And I know for a fact that the names of the latter two used to show).

**Comment by matkoniecz** [comment] 2015-09-20 06:54
> This is about the only reason I can figure out that areas such as these don't have their names appearing at any zoom level.

Duplicate of #1800 (fixed, waiting for release https://github.com/openstreetmap/chef/issues/36 )

**Closed by matkoniecz** 2015-09-20 06:54 UTC
