### ISSUE TITLE
Runway surface=grass rendered looking like asphalt

### ISSUE THREAD

**Issue by kennethgillen** [gravitystorm/openstreetmap-carto#4534] opened 2022-04-17 21:06 UTC
### Expected behavior

Runways with `surface=grass` should look green.

### Actual behavior

Runways with `surface=grass` actually look like asphalt/tarmac.

### Links and screenshots illustrating the problem

See the side-by-side of an aerdodrome in Scotland called Perth Airport - runway 33/15 is grass. The default OSM render shows this as asphalt-coloured, despite the OSM data 'surface=grass'.

![image](https://user-images.githubusercontent.com/2727871/163731992-a03e8875-ea2f-49cc-a4af-0da5a9c1f60d.png)

**Comment by HolgerJeromin** [comment] 2022-04-18 06:45
Duplicate of #1024

#4346 has an experimental redesign of aeroway which includes grass runways.

**Closed** 2022-04-18 08:37 UTC
Labels: duplicate

**Comment by kennethgillen** [comment] 2022-04-18 08:43
@pnorman - the issue you claim this is a duplicate of is closed as "won't fix", becuase someone included 2 issues on the same issue, one of which was use of incorrect tagging.

This is actually still a problem, it shouldn't be close on the basis of 'incorrect taggin' and will be fixed if #4346 actually goes ahead. 

I have no idea if an 'experimental' PR will get into the public OSM rendered tiles myself - I'd like to do everything I can to support it to make that happen.

**Comment by imagico** [comment] 2022-04-18 10:36
#1024 was closed because there was agreement that special rendering for different kinds of runways specifically is considered out of scope for this style.  We have an open issue about rendering unpaved roads (#110) which includes runways and would include surface=grass as a type of unpaved surface (just like it already does for highway=path etc.).  Bringing that forward (we have existing PRs for that in #3399 and #4137 - which however have not made progress for some time now) would be the logical next step here.

The color chosen for runways might have led you to the conclusion that it is meant to depict an asphalt surface but it is not.  Our road rendering in general is functional in nature - i.e. the differences in color and styling are primarily meant to depict differences in function and purpose and not in physical appearance.

**Comment by kennethgillen** [comment] 2022-04-18 10:51
@imagico thanks for the explanation.

>The color chosen for runways might have led you to the conclusion that it is meant to depict an asphalt surface but it is not. Our road rendering in general is functional in nature - i.e. the differences in color and styling are primarily meant to depict differences in function and purpose and not in physical appearance.

Well that's me learned something new. Grey grass feels wrong to me, regardless, especially when the metadata exists to make the render appear closer to how it appears in reality. 🤷‍♂️

**Comment by HolgerJeromin** [comment] 2022-04-18 20:45
> Well that's me learned something new. Grey grass feels wrong to me, regardless, 

It is not so easy to not mix it with hedges or other green patches we have on the map.

> We have an open issue about rendering unpaved roads (https://github.com/gravitystorm/openstreetmap-carto/issues/110) which includes runways...

Both strings "runway" or "aeroway" are not part of the whole discussions of 110. Roads are VERY different to highways (in osm and reality) so we should not mix them.
Especially with the experimental runway PR we should/could keep one issue open for that.

**Comment by jdhoek** [comment] 2022-05-17 17:04
> I have no idea if an 'experimental' PR will get into the public OSM rendered tiles myself - I'd like to do everything I can to support it to make that happen.

That would be nice, but I would need a willing maintainer to work with to further that project. I still think that approach has potential. I strongly agree with you that unpaved and grass-surfaced runways would benefit from a rendering more representative and easier to grasp for users: runways are completely different from roads because of their huge surface area. Like bodies of water or areas of grass, it makes sense to reflect their surface property in a more intuitive way (as suggested in #4346).
