### ISSUE TITLE
Rendering of barrier over highway (area)

### ISSUE THREAD

**Issue by javiersanp** [gravitystorm/openstreetmap-carto#2762] opened 2017-08-17 22:31 UTC
Highway areas are drawn on top of barriers and these are not visible. Please see this example: ways  tagged as barrier=wall and relation tagged with highway=pedestrian.

http://www.openstreetmap.org/way/252837417
http://www.openstreetmap.org/way/252837418
http://www.openstreetmap.org/way/252837419
http://www.openstreetmap.org/way/252837420
http://www.openstreetmap.org/relation/7483027 

I think it's a bug and barriers should be drawn on top of highway areas.

Regards

**Comment by kocio-pl** [comment] 2017-08-17 22:47
Thanks for this comment, but it's a duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/528, so I'm closing it.

**Closed by kocio-pl** 2017-08-17 22:47 UTC
Labels: duplicate
