### ISSUE TITLE
Add rendering for waterway=waterfall

### ISSUE THREAD

**Issue by ghost** [gravitystorm/openstreetmap-carto#336] opened 2014-02-10 23:05 UTC
It would be nice if mapnik would display a waterfall icon for nodes marked with waterway=waterfall

I have created http://wiki.openstreetmap.org/wiki/Waterfall some time ago and this part  seems fairly stable.

**Comment by nebulon42** [comment] 2015-05-20 15:55
Icon available in [Osmic](https://github.com/nebulon42/osmic) now: ![waterfall-16](https://cloud.githubusercontent.com/assets/3531092/7730234/520064a4-ff19-11e4-88ea-b66f37688152.png)

**Comment by kocio-pl** [comment] 2015-05-20 16:07
Not bad, but before/after images would be welcome, because the color may have some impact on the final look.

BTW: I'm almost done with Tilemill rendering at last, so I'm almost ready for making real PRs, but want to know some hints how to make such before/after images, like:

1. What zoom level to choose (or any will do, including z>19 if the details will be better visible)? 

2. Is there a simple way for recreating the same box after closing TileMill (or there's no need or its purely manual)?

**Comment by nebulon42** [comment] 2015-05-20 16:38
I choose the zoom level depending on the situation as I see fit. Using z20+ is not a good idea as it is not rendered live. I'm not aware of a method to get the same box again in TileMill, maybe it can be adjusted in the settings?

**Comment by StyXman** [comment] 2015-05-20 16:55
Maybe it should be rendered at the same zoom level as sources.

**Comment by kocio-pl** [comment] 2015-05-20 17:02
@StyXman You mean the same level for before and after? Sure! In my case however if there's a lot of shops around I would choose zoom level which shows mainly the one I want to render, so z>19 for both would make same sense.

One more question regarding pushing - if I want to push multiple shop icons, should I push them with separate PRs or just one for all? I guess the later would be better in my case, since they all deal with the same, long YAML lines, so probably there would be too many conflicts to resolve.

**Comment by nebulon42** [comment] 2015-05-20 17:08
New icons trigger discussions. According to my experience it is less likely to get them merged the more (controversial) icons a PR contains. If you split them you have to deal with possible merge conflicts, especially if you modify the project file. It depends, I would say. :)

**Comment by pnorman** [comment] 2015-05-20 17:11
> One more question regarding pushing - if I want to push multiple shop icons, should I push them with separate PRs or just one for all? I guess the latter would be better in my case, since they all deal with the same, long YAML lines, so probably there would be too many conflicts to resolve

It depends. If the icon changes are tied together (e.g. hotels and hostels) they're better as one PR. If they're discrete changes, they're better as different PRs.

Merge conflicts caused by adding to a list on the same line in two PRs are easy to resolve - word diff shows that all you did is add a word, and that change can then be redone by hand quickly.

**Comment by matkoniecz** [comment] 2015-05-20 17:39
> Is there a simple way for recreating the same box after closing TileMill

Unfortunately, not using TileMill interface (it may be done with command line export - see https://www.mapbox.com/tilemill/docs/manual/exporting/)

**Comment by StyXman** [comment] 2015-05-20 18:25
What you can do to generate a specific tile starting from osm-carto is:

* Convert the project to MapnikXML with `carto`: `carto project.mml openstreetmap-carto.xml`.
* Use [this script](https://github.com/StyXman/elevation/raw/master/generate_tiles.py) to render a particular tile (or even a set of tiles in a bbox); one that has a waterfall is: `generate_tiles.py --tile 19,271295,188504 --input-file openstreetmap-carto.xml`.

I hope the program works out of my setup; I just heavily modified the original one in the old repo. Currently it also needs `python-sqlalchemy` for its basic MBTiles support.

**Comment by RicoZ-OSM** [comment] 2015-05-24 11:55
I have recently clarified http://wiki.openstreetmap.org/wiki/Waterfalls to suggest adding height=* and width=* to the node waterway=waterfall.

Following properties could be used to decide at which zoom level to render the icon:
* waterfall  height, width - if present, so far not used afaics
* presence of key:name, tourism=attraction
* is it a river or stream

**Comment by daganzdaanda** [comment] 2016-06-19 19:07
We really should show something that indicates a waterfall. I think @nebulon42 's icon from #1564 is good, and for the colour, we can use the same as fords.

For big and well-mapped waterfalls, we could render the natural=cliff line in blue, labelled with the name, if it also is tagged as waterway=waterfall. That kind of tagging is used at Niagara Falls at the moment, but I'm not sure if it's been agreed and documented.

**Comment by RicoZ-OSM** [comment] 2016-06-19 19:40
@daganzdaanda : also had the idea tagging the waterfall cliffs as natural=cliff + waterway=waterfall. This does not work for artificial waterfalls which fall over a waterway=weir instead of natural=cliff. This may not be a big loss but for example the Rhine falls have a small section where the water falls over a weir. It is one of the http://wiki.openstreetmap.org/wiki/Waterfalls#Open_issues

**Comment by kocio-pl** [comment] 2017-09-16 23:23
Maybe we should just drop the icon and show only the name and height when available. For example "[Salto Ángel (979)](http://www.openstreetmap.org/node/366604035)" in a standard water color would be clear indicator of what it is.

**Comment by andrewharvey** [comment] 2017-12-22 04:55
> Maybe we should just drop the icon and show only the name and height when available. For example "Salto Ángel (979 m)" in a standard water color would be clear indicator of what it is.

I'd prefer an icon. There are many unnamed waterfalls which would be useful to show, and without the icon and only the name, it can be unclear what the name is for.

**Comment by kocio-pl** [comment] 2017-12-22 06:00
And what icon should it be then?

**Comment by andrewharvey** [comment] 2017-12-22 06:10
How about this one? https://gitlab.com/gmgeo/osmic/blob/master/nature/waterfall-14.svg

**Comment by kocio-pl** [comment] 2017-12-22 07:35
That's the same as proposed by @nebulon42 in https://github.com/gravitystorm/openstreetmap-carto/issues/336#issuecomment-103936778. :smile: 

Because I was the one who opposed back then and now I am willing to accept it, I guess we could use this shape.

**Comment by SomeoneElseOSM** [comment] 2017-12-22 09:38
For info (just to show another rendering example) I went with a blue dot over at https://map.atownsend.org.uk/maps/map/map.html#zoom=17&lat=54.413704&lon=-2.0975 .  The text has a big halo because often it gets rendered over natural=water colour.

**Comment by gpsvisualizer** [comment] 2018-03-31 02:34
I'm resurrecting this old thread because most of my mapping efforts are outdoors-related, and we have a LOT of waterfalls in Oregon, and the lack of an icon for them seems like a major omission to me.  What can we do to make this happen?

**Comment by kocio-pl** [comment] 2018-03-31 02:51
If you share my opinion that this icon:

https://github.com/gmgeo/osmic/blob/master/nature/waterfall-14.svg

is good enough, you can try to prepare the code to show it (with a label perhaps and maybe even with height if you can, but that might be added later on). 

Basically we need more coders, from copy-paste level beginners willing to fix small bugs to SQL/Carto CSS/Mapnik experts ready to make code refactoring (like #2869) and everyone in between who wants to implement selected features (like https://github.com/gravitystorm/openstreetmap-carto/labels/good%20first%20issue). The basic facts about this style and how to install testing environment relatively easily using Docker:
- https://wiki.openstreetmap.org/wiki/Standard_tile_layer
- https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

Would you like to try? Let me know if you want any help.

**Comment by gpsvisualizer** [comment] 2018-03-31 03:04
I'm afraid I don't know anything about the coding. My hands-on help will probably have to be limited to graphics.

I was hoping that in this case, no new code need to be invented; since a waterfall is just a point, wouldn't it be rendered the same way as a peak or a saddle or a spring?  In fact, the rules and zoom levels for waterway=spring would probably be just about perfect for waterfalls.

I'll take a look at that waterfall-14 icon.

**Comment by kocio-pl** [comment] 2018-03-31 03:12
I'm not a coder too, yet I'm able to make decent PRs just by cloning and tuning code similar features, as you have just noted. It doesn't matte how small a given feature is - it has to be selected form database in `project.mml` and have a style defined in a related MSS file.

This is not a rocket science, for example style definition for peak icon looks like this:
https://github.com/gravitystorm/openstreetmap-carto/blob/94fe461654bd1424e775a23207eed6ffb4aa2203/amenity-points.mss#L1106-L1112

**Comment by gpsvisualizer** [comment] 2018-03-31 03:16
It's not the .css code itself that worries me.  I'm unfamiliar with the whole terminology of "pull requests" and git and all of that.  And I'm spread too thin right now to learn a whole new process!

**Comment by kocio-pl** [comment] 2018-03-31 03:19
Sure, you can do it whenever you feel you're ready (or just frustrated enough :smile: ).

Basic facts about our workflow:
https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#workflow

**Comment by gpsvisualizer** [comment] 2018-03-31 07:27
Here's my attempt to clean up the proposed waterfall icon a little bit; I chaged the "waves" at the bottom, the top a tiny bit thicker, and extended the vertical lines.

Original: ![waterfall-14](https://user-images.githubusercontent.com/8356259/38160871-05c7d278-3479-11e8-96fd-49cd1c956ec4.png)

Adjusted: ![waterfall2-14](https://user-images.githubusercontent.com/8356259/38160913-c8ecf8c8-3479-11e8-848f-15bc234b2431.png)

In blue: ![waterfall2-14-blue](https://user-images.githubusercontent.com/8356259/38160919-02c4f762-347a-11e8-99e2-bd44961cec2e.png)

**Comment by kocio-pl** [comment] 2018-03-31 07:31
I like original more because there's a space between water streams and waves, which makes this shape more readable.

**Comment by gpsvisualizer** [comment] 2018-03-31 07:40
I added a little space.

v1: ![waterfall-14](https://user-images.githubusercontent.com/8356259/38160990-c7227250-347b-11e8-8681-8c0bde6130c2.png)

v2: ![waterfall2-14](https://user-images.githubusercontent.com/8356259/38160992-d3828fbc-347b-11e8-9b17-b53ace69b3cd.png)

v3: ![waterfall3-14](https://user-images.githubusercontent.com/8356259/38160996-dde3aab8-347b-11e8-99f6-a1b06d38a193.png)

v3: ![waterfall3-14-blue](https://user-images.githubusercontent.com/8356259/38161000-e545bcd8-347b-11e8-884d-300b330b05e9.png)

v1-v2-v3: ![waterfall-14](https://user-images.githubusercontent.com/8356259/38160990-c7227250-347b-11e8-8681-8c0bde6130c2.png) ![waterfall2-14](https://user-images.githubusercontent.com/8356259/38160992-d3828fbc-347b-11e8-9b17-b53ace69b3cd.png) ![waterfall3-14](https://user-images.githubusercontent.com/8356259/38160996-dde3aab8-347b-11e8-99f6-a1b06d38a193.png)

**Comment by kocio-pl** [comment] 2018-03-31 07:44
I like v3, since it's taller than original, has a space and the waves are a bit easier to recognize. Could you share this code as a gist?

**Comment by gpsvisualizer** [comment] 2018-03-31 07:53
v3 as gist: https://gist.github.com/gpsvisualizer/cd9c43f103a343873df8a692fa6c1ce1

**Closed as completed** 2018-04-17 02:20 UTC
Labels: amenity-points
