### ISSUE TITLE
Neighbourhood relation doesn't give a neighbourhood name

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#2566] opened 2017-02-09 07:32 UTC
I've moved some neighbourhoods names from landuse=residential to a separate boundary relations (because residential landuse is just part of those neighbourhoods), and the names disappeared.

Here are the examples:
http://www.openstreetmap.org/relation/1851062
http://www.openstreetmap.org/relation/1859279

Place=neighbourhood nodes works fine, but there is problem with neighbourhood relations.

**Comment by pnorman** [comment] 2017-02-09 11:38
Note: that object is both a boundary relation with no boundary tag and a place polygon. To the extent it's an issue about the boundary relation, that's bad tagging. To the extent this issue is about the place polygon, it's a duplicate of #103

**Closed by pnorman** 2017-02-09 11:38 UTC
