### ISSUE TITLE
Add rendering for amenity=marketplace

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1622] opened 2015-06-28 13:06 UTC
Marketplace should be rendered the same as landuse=retail probably, because that's what it really is - and 2.031 out of 28.124 objects has this tag added explicitly.

**Comment by matkoniecz** [comment] 2015-06-28 14:22
duplicate of #751

**Closed** 2015-06-28 14:27 UTC
Labels: duplicate
