### ISSUE TITLE
marker-placement: interior ignored for place_of_worship

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#2511] opened 2016-12-14 18:18 UTC
I have no idea why, but the [marker-placement: interior](https://github.com/gravitystorm/openstreetmap-carto/blob/master/amenity-points.mss#L384) seems to be ignored in this [PoW](http://www.openstreetmap.org/way/96821031#map=19/50.76494/6.07436):
![image](https://cloud.githubusercontent.com/assets/2410353/21194906/f8e1297a-c231-11e6-9b96-bd50ee221b3e.png)

Same [here](http://www.openstreetmap.org/relation/3019551#map=19/51.18407/6.81401):
![image](https://cloud.githubusercontent.com/assets/2410353/21195154/eae86918-c232-11e6-9ae3-b7519d377374.png)

**Comment by jojo4u** [comment] 2016-12-14 18:30
perhaps related to #2457

**Comment by HolgerJeromin** [comment] 2016-12-14 19:36
Such pow are rare but both I found were not very complex and both wrong. Perhaps someone can find a working example.

**Comment by HolgerJeromin** [comment] 2016-12-30 10:53
https://www.openstreetmap.org/way/4372002

![image](https://cloud.githubusercontent.com/assets/2410353/21563841/85efd964-ce86-11e6-906c-b9078bfcb477.png)

**Comment by jojo4u** [comment] 2017-01-14 14:06
Also for a leisure=park multipolygon (https://www.openstreetmap.org/relation/5197622). Label "Rosensteinpark" is on the left near the inner, but text-placement should be interior per amenity-points.mss. JOSM validator says multipolygon is ok.

![park](https://cloud.githubusercontent.com/assets/156724/21955396/c94a2f3a-da6a-11e6-9aad-be580346f072.png)

**Comment by pnorman** [comment] 2017-04-18 02:21
Duplicate of #1465

**Closed by pnorman** 2017-04-18 02:21 UTC
Labels: buildings, text

**Comment by kocio-pl** [comment] 2017-11-25 21:40
Looks like Mapnik v3.0.16 fixed that bug:

![ftckm3fs](https://user-images.githubusercontent.com/5439713/33235089-93b6c01c-d231-11e7-8473-ba5c754788d7.png)
![2uadkzdn](https://user-images.githubusercontent.com/5439713/33235090-9582ac80-d231-11e7-87e9-bd2c0d50af55.png)
