### ISSUE TITLE
Bridge "A" labeled using nearby invisible bridge "B"'s name instead of its own

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3805] opened 2019-06-11 22:58 UTC
We have an [interesting situation](https://www.openstreetmap.org/?mlat=24.19331&mlon=120.85656#map=18/24.19331/120.85656). At zoom level 18:
```
Shown? (Yes, No)
---- A B
BODY Y N
NAME N Y
```

This causes bridge "A" to be labeled using nearby invisible bridge "B"'s
name instead of its own!

**Comment by matkoniecz** [comment] 2019-06-12 05:19
So https://www.openstreetmap.org/way/696526916 dominates over https://www.openstreetmap.org/way/228962647 and name of bridge of main road is not displayed at all?

I am not sure is it the best possible rendering in this specific situation. But it was intentional to render bridge labels with higher priority than road labels, otherwise bridge label would disappear during zooming. Also typically bridge names are worth not showing name of small road part.

Note that in this case larger bridge is not mapped at all, in case that it would be label of larger bridge would be rendered first.

In this specific case anyway it looks like large bridge is not mapped (so it is partially a data issue) and small bridge is a tourism attraction so rendering may be surprising but looks acceptable to me.

**Comment by jidanni** [comment] 2019-06-12 05:30
Also the notice board has the same name as the small bridge, so maybe I'm seeing the name of the notice board.
OK, but we're not talking about road names in this case.
Anyway, maybe there should be a rule: never show names if you don't show the corresponding body.

**Comment by matkoniecz** [comment] 2019-06-12 05:42
> maybe I'm seeing the name of the notice board.

No, note position of name. Also boards and their names are not displayed so early.

For this specific case - is larger bridge also named?

**Comment by jidanni** [comment] 2019-06-12 05:49
> For this specific case - is larger bridge also named?

Yes, right there in https://www.openstreetmap.org/way/228962647 as you posted.

**Comment by jidanni** [comment] 2019-06-12 05:55
[Streetview](https://goo.gl/maps/wkTp7pzCRZbjZzUX7) (not for mapping) lets you get a feel for the historic flavor of the smaller bridge, one of the https://www.google.com/search?q=Glutinous+Rice+Bridges made out of rice!

**Comment by matkoniecz** [comment] 2019-06-12 05:59
> Yes, right there in openstreetmap.org/way/228962647 as you posted.

In that case mapping bridge outline as `man_made=bridge` with `name` tag will fix rendering.

**Comment by jidanni** [comment] 2019-06-12 06:06
> In that case mapping bridge outline as `man_made=bridge` with `name` tag will fix rendering.

The bridges' name already [appears at zoom level 19](https://www.openstreetmap.org/#map=19/24.19332/120.85665). Are you sure you want me to mess up this bug report by editing the bridge now?

**Comment by matkoniecz** [comment] 2019-06-12 06:42
Yes, on zoom 19 both `man_made=bridge` label with bridge name and `highway` road label with bridge name fit so both are displayed.

Earlier `man_made=bridge` label is prioritized over road label. This behavior is desirable and expected.

Wrong display is caused by combination of missing larger bridge outline (`man_made=bridge`) and mapping of `man_made=bridge` for a small bridge, there is no reason to change things on side of map style.

**Comment by jidanni** [comment] 2019-06-12 06:58
OK, I edited it, following all the advice in the iD editor, and ended up **wiping it off the map**!
https://www.openstreetmap.org/changeset/71167651

**Comment by jidanni** [comment] 2019-06-12 07:16
OK! (Please repair the bridge for me before the village chieftain finds out! I don't want to do any more damage. Plus a thundercloud is approaching and I must power-off all equipment. See you tomorrow.)

**Comment by matkoniecz** [comment] 2019-06-12 07:23
Note that `man_made=bride` is a bridge outline, road/path across bridge still needs to be mapped.

I added footway across small bridge. I moved `man_made` bridge to new way that represents bridge outline. 


Please, check is it mapped correctly - note that footway from smaller bridge joins in the middle of bridge what is weird. Also, please add name to the larger bridge outline.

I opened https://github.com/openstreetmap/iD/issues/6525 to cover part of iD confusion.

I opened https://www.openstreetmap.org/note/1809581 - to report one more issue. Lets discuss further in this note.

I will close this issue as it is not a map style issue, but thanks for a report - it seems that iD issue was found and I will improve https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge page to make it more clear.

**Closed by matkoniecz** 2019-06-12 07:23 UTC
