### ISSUE TITLE
research_institute at heart of coronavirus scandal not rendered

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4036] opened 2020-02-17 18:14 UTC
https://www.openstreetmap.org/way/766090654
https://wiki.openstreetmap.org/wiki/Tag:amenity=research%20institute

**Comment by imagico** [comment] 2020-02-17 18:27
Please don't use a sensationalist title in attempting to lobby for rendering tags.

Duplicate of #2077 - if you see reason to reopen that based on changed tagging practice please comment there.

**Closed by imagico** 2020-02-17 18:27 UTC

**Comment by polarbearing** [comment] 2020-02-17 18:35
Besides, the virus is not a 'scandal', which is defined as an action "morally or legally wrong and causing general public outrage" - a disease has no moral.
