### ISSUE TITLE
historic=ruins on a node not rendered

### ISSUE THREAD

**Issue by PontiacCZ** [gravitystorm/openstreetmap-carto#2435] opened 2016-11-11 12:21 UTC
I wanted to add castle ruins to the OSM but to my surprise they already are in the map, just not rendered in Mapnik. I only added `"ruins=castle"` but it did not help anyway.

http://www.openstreetmap.org/node/1347630199#map=19/49.28130/16.07907

According to the [Wiki page](http://wiki.openstreetmap.org/wiki/Tag:historic%3Druins) this tagging on a node should be okay. Or is it not?

**Comment by HolgerJeromin** [comment] 2016-11-11 18:26
Thanks for your contribution!
The issue is already discussed in #331

**Comment by pnorman** [comment] 2016-11-11 23:38
Closing as duplicate. Please remember to search for existing issues before filing a new one.

**Closed by pnorman** 2016-11-11 23:38 UTC
Labels: duplicate
