### ISSUE TITLE
Render man_made=telescope

### ISSUE THREAD

**Issue by geozeisig** [gravitystorm/openstreetmap-carto#3389] opened 2018-09-13 06:40 UTC
Render **man_made=telescope + tower:construction=dish** with
![dish](https://user-images.githubusercontent.com/17127509/45470794-590a6700-b72f-11e8-8ef3-ba56861d1582.jpg)
It should be rendered as well as man_made=tower + tower:construction=dish.
Sometimes the dish is not on a tower and is called a telescope (telescope:type=radio). It should then also get an icon.

**Comment by Adamant36** [comment] 2018-09-13 06:48
Not to nitpick the icon, but telescopes don't really send out information do they? Last time I checked they are passive collectors. Even radio telescopes receive information and don't send it out. So icon should probably be modified to reflect the passiveness, instead of looking like its sending out information when its not.

**Comment by geozeisig** [comment] 2018-09-13 15:28
Of course you are right that telescopes are passive collectors. But an icon is a symbol and does not need to depict reality 1: 1. If someone designs a better symbol, so much the better.

I think that a dish is mapped to the outer appearance or satellite picture and one does not recognize at first glance whether it is also sending or just receiving. But it may also be that we need another tag for large transmitter antennas. 
![320px-uplink_antenne](https://user-images.githubusercontent.com/17127509/45498288-05713b00-b77a-11e8-93fb-41ecd3c1a58f.jpg)
_Satellite uplink antenna_
There are transmit antennas where man_made=tower does not fit.

**Comment by kocio-pl** [comment] 2018-09-13 16:05
Probably removing waves would be enough.

**Comment by HolgerJeromin** [comment] 2018-09-13 20:16
> Not to nitpick the icon, but telescopes don't really send out information do they? Last time I checked they are passive collectors. Even radio telescopes receive information and don't send it out.

Sometime they do  :-D 

https://en.wikipedia.org/wiki/Arecibo_message

**Comment by Tomasz-W** [comment] 2018-09-14 05:46
Icon proposal (dish icon without waves and rescaled to 14x14):

![pobrany plik](https://user-images.githubusercontent.com/25656654/45531613-dcd85800-b7f0-11e8-962c-14371ce75ce9.png)

to compare, dish icon without waves but not rescaled, I'm not sure is it readable enough without them in this size:
![tower_type dish](https://user-images.githubusercontent.com/25656654/45531642-fc6f8080-b7f0-11e8-934d-e9833f2b9af3.png)  -> ![pobrany plik](https://user-images.githubusercontent.com/25656654/45531570-a8fd3280-b7f0-11e8-942f-05d3fb718597.png)

Both versions in Gist link:
https://gist.github.com/Tomasz-W/f8b8e3b06d6e6ec2867b50269fbe427c

**Comment by geozeisig** [comment] 2018-09-15 05:39
The icon without waves and rescaled fits well.

Do you think you could extend the proposal to man_made=telescope + telescope:type=radio? The number should be larger even if the shape of the antenna is not always dish.

And then there are the optical telescopes (telescope:type=optical). Do we need another icon maybe like a refractor? However, these are usually in a dome building and not always visible.
![yerkes_40_inch_refractor_telescope-2006](https://user-images.githubusercontent.com/17127509/45582961-a7e40800-b8b9-11e8-9db9-1c4394545653.jpg)

**Comment by kocio-pl** [comment] 2018-09-15 05:47
I think that instead of just removing waves, we could add support lines, similar to this one (this one has waves too): https://cdn3.iconfinder.com/data/icons/space-5/512/radio_transmitter-512.png

**Comment by Tomasz-W** [comment] 2018-09-15 11:03
1. ![1](https://user-images.githubusercontent.com/25656654/45531613-dcd85800-b7f0-11e8-962c-14371ce75ce9.png) 
2, ![man_made telescope](https://user-images.githubusercontent.com/25656654/45585620-bcd79000-b8e7-11e8-81bb-840971433e88.png)

**Comment by matkoniecz** [comment] 2018-09-16 10:33
Can somebody give examples of objects where rendering icon would be beneficial?

Sorry, offtopic ahead:

> telescopes don't really send out information do they?

Rarely they may do that - see https://en.wikipedia.org/wiki/Radar_astronomy

**Comment by Adamant36** [comment] 2018-09-16 11:08
Hhmm, well you learn something new every day. 

Sorry, offtopic ahead. 
@matkoniecz, what do you think the purpose of the style is? Is it not to work as a feedback mechism to spur on better tagging/more mapping that evolves? Or is something completely different to you? Like a final place to arrive at, and then stops being actively developed?

**Comment by kocio-pl** [comment] 2018-09-16 11:27
I have an idea lately - in a general style it's not about benefits and use cases, it's about neutral showing on the ground truth (I plan to write more about this soon). And telescopes are usually quite visible, very similar to the dish antennas. Even biggest of them are not too big (like https://www.openstreetmap.org/#map=15/18.3430/-66.7506), so showing them on the same scale (z17+) but with a bit different icon makes sense for me.

**Comment by matkoniecz** [comment] 2018-09-16 11:28
> what do you think the purpose of the style is

It is trying to do multiple contradictory things at once. I started to write more about that - but that would be basically duplicate of https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md

> Is it not to work as a feedback mechism to spur on better tagging/more mapping that evolves?

It is one of targets, but sometimes what would be beneficial for this purpose goes against "Legibility and clarity", "Maintainability", "Adaptability and ease of use". Note "The aim is not however to show all or even most of the OSM data.".

> Like a final place to arrive at, and then stops being actively developed?

Certainly not. First of all, we are far, far away from ideal map style (see open issues on the bug tracker for start, there are some issues unfixable without switching technology or improving upstream software). As with most projects new ones will appear as long as someone is using this map style.

And anyway - world changes, for example electric car charging stations appeared relatively recently in numbers that made their display a good idea. Other changes like this will appear in future.

**Comment by Adamant36** [comment] 2018-09-16 11:46
@matkoniecz, I can mostly agree with that. Since its multiple purpose and one is not more important then any other, then wouldnt it also follow that for ever issue there should be equal amounts of discussion of the pros and cons of all of them? Instead of the singular obsession that seems to exist with clairty? 

Wouldnt it also mean to that it should be a 50/50 of us reasoning why things should be added and you reasoning why they shouldnt and  us meeting somewhere in the middle once all the arguments are laid out? Instead of it only being on us and you having ultimate say in the end as if we have to convience you to somethings benefit, instead of us having a reason dialog on it as equals that covers all the goals equally? 

Altough I agree that as a maintainer maybe you should have more "clout" so to speak, I dont think it should involve a power dynamic where none maintainers are forced to be on the defensive just to contribute. Which is the case if only one side, mainly them, has to argue their position on an issue. While you and the other maintainers only have to claim clutter to close an issue and not have it implemented. It puts an uncessary/unfair burden of proof on us. Especially for issues like this that arent major changes.

**Comment by kocio-pl** [comment] 2018-09-16 13:39
Bigger areas already get rendered earlier than smaller ones, so yes, it applies there as well.

**Comment by matkoniecz** [comment] 2018-09-16 20:31
> Instead of the singular obsession that seems to exist with clairty?

I think it is not a fair description. It is a really rare even that something stops being rendered. This style over time displays more and more features with more and more icons.

**Comment by kocio-pl** [comment] 2018-09-16 20:35
I would also not go with that description. However it's natural for me to follow the changes in database and more icons are more intuitive for me when it's something easy to observe on the ground, like with memorials or towers.

**Comment by kocio-pl** [comment] 2018-09-17 04:39
> Note "The aim is not however to show all or even most of the OSM data.".

@matkoniecz And we're not doing this. It's simply not possible with the current size of database.

I'm also curious why IIRC nobody ever mentioned that this is only the last comment to the primary rule? What about core message, which reads as follows:

_**A rich map** - This style deliberately creating a fairly rich map showing a significant number of different features. This way it shows the richness of OSM data and gives a broad recognition to the mappers' work._ 

What is the problem here?

**Comment by matkoniecz** [comment] 2018-09-17 05:08
> A rich map

Yes, but I was trying answer the question why sometimes it may be preferable to do not display something. ("It is one of targets, but sometimes what would be beneficial for this purpose goes against(...)").

**Comment by geozeisig** [comment] 2018-09-19 10:44
I have cleaned up some wiki pages and I found that there are several tags in this context that are similar:

- man_made=telescope

- man_made=observatory

- man_made=antenna

- man_made=radio_telescope

- man_made=communications_dish

- man_made=satellite_dish

- man_made=satellite_antenna

We need a discussion about the definition of these tags. We certainly does not need everything. Others who mean the same thing can be put together.

There is e.g. the question if man_made=telescope + telescope:type=optical is the same as man_made=observatory + observatory:type=astronomical?

Do we judge the object by appearance (antenne, dome, dish,tower)  or function (astronomical, meteorological, espionage, scientific, public? Often the antennas are in a building. Nevertheless, it would be important not only to describe the building but also the object inside.

Where can we discuss this best so that a resolution comes out?

**Comment by kocio-pl** [comment] 2018-09-19 10:51
I believe we should start with testing how popular they really are and maybe Tagging list will be needed to sort things out.

**Comment by dieterdreist** [comment] 2018-09-19 11:33
sent from a phone

> On 19. Sep 2018, at 12:44, geozeisig <notifications@github.com> wrote:
> 
> There is e.g. the question if man_made=telescope + telescope:type=optical is the same as man_made=observatory + observatory:type=astronomical?


while this should be discussed on the tagging mailing list rather than here, I would say an observatory is a facility, a telescope is an instrument

**Comment by matkoniecz** [comment] 2018-09-20 19:28
> I have cleaned up some wiki pages and I found that there are several tags in this context that are similar:

Thanks! That is really, really useful. 

> There is e.g. the question if man_made=telescope + telescope:type=optical is the same as man_made=observatory + observatory:type=astronomical?

From looking just at tag names it should clearly diffferent

- man_made=observatory + observatory:type=astronomical should be the entire facility, typically with multiple telescopes (though there may be just single telescope, none, some or all telescopes may not be optical, in extreme case it may not use telescopes at all - like LIGO that has gravitational wave sensors).

**Comment by Tomasz-W** [comment] 2018-09-21 06:02
I think we should consider using this icon only for `man_made=telescope`, because as @matkoniecz said `man_made=observatory` refers more to the whole "campus" area than a certain object, `man_made=antenna` can be small and in differen shape, so this icon could be not fit there, and all of the rest of tags from https://github.com/gravitystorm/openstreetmap-carto/issues/3389#issuecomment-422752364 are discouraged by the Wiki (https://wiki.openstreetmap.org/wiki/Tag:man_made=antenna)

**Comment by geozeisig** [comment] 2018-09-23 09:07
@dieterdreist  _I would say an observatory is a facility, a telescope is an instrument_ Thanks for the hint. I have considered it in the [wiki page](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dobservatory). Please check again.

There are large antenna dishes that keep in touch with satellites and spacecraft. How are they tagged and should not they also get an icon?

**Comment by dieterdreist** [comment] 2018-09-24 08:51
2018-09-23 11:07 GMT+02:00 geozeisig <notifications@github.com>:

> There are large antenna dishes that keep in touch with satellites and
> spacecraft. How are they tagged and should not they also get an icon?



+1 for icon, for the tagging question you should ask on the tagging ML, my
guess would be something with "communication" "relay" "antenna", "ground
station" etc.

**Comment by geozeisig** [comment] 2018-09-26 11:12
You can find landuse=observatory 287x. Should not that be done with man_made=observatory? Even if the terrain is meant?
There is a [preset for JOSM](https://josm.openstreetmap.de/wiki/Presets/Tagsforobservatories) that is probably responsible for landuse=observatory.
Do we really need landuse=observatory? It is not mentioned on the [Feature : Landuse](https://wiki.openstreetmap.org/wiki/Landuse) or [Key:landuse](https://wiki.openstreetmap.org/wiki/Key:landuse).

**Comment by matkoniecz** [comment] 2018-09-26 11:27
> There is a preset for JOSM that is probably responsible for landuse=observatory.
> Do we really need landuse=observatory? It is not mentioned on the Feature : Landuse or Key:landuse.

Tagging mailing list is probably the best place to discuss whatever wiki or JOSM preset or both should be improved.

**Comment by jeisenbe** [comment] 2018-10-20 15:07
Rendering of radio telescopes on Mauna Kea in Hawaii, z17, with icon 1:
![hawaii-telescopes-1](https://user-images.githubusercontent.com/42757252/47257059-cabe9900-d4c3-11e8-9ec7-7deccc81a861.png)

Icon 2 (rescaled to 14px) at z17: 
![hawaii-telescopes-2](https://user-images.githubusercontent.com/42757252/47257116-bcbd4800-d4c4-11e8-89cd-346ebe24078e.png)

Icone 3 (with support wires) at z17: 
![hawaii-telescopes-3](https://user-images.githubusercontent.com/42757252/47257097-46204a80-d4c4-11e8-9a54-622fccc55e7e.png)

**Comment by jeisenbe** [comment] 2018-10-20 16:01
According to Overpass Turbo, there are 79 nodes and 4 closed ways / areas tagged with man_made=telescope and tower:construction=dish, and the ones that I checked all seem to be tagged telescope:type=radio as well.

Meanwhile, man_made=telescope with telescope:type=radio has over 400 uses in North America alone, and over 1000 overall

So, do we need to make a code to render telescope with tower:construction=dish, or is telescope:type=radio enough?

**Comment by jeisenbe** [comment] 2018-10-21 06:14
Should we go with icon 2 or 3?

Two radio telescopes in Poland, nodes
https://www.openstreetmap.org/node/4807613101
https://www.openstreetmap.org/#map=18/53.0955128/18.5610400

z17 Icon 2
![radio-italy-1](https://user-images.githubusercontent.com/42757252/47263716-0e57e800-d542-11e8-8497-a29fc43d4621.png)

z17 Icon 3
![italy-radio-3](https://user-images.githubusercontent.com/42757252/47263752-b968a180-d542-11e8-80a0-8aa0369e0718.png)

Radio telescopes in Cambridge, England; closed ways (polygons):
https://www.openstreetmap.org/way/32733809
https://www.openstreetmap.org/#map=18/52.1645763/0.0309299
z17 Icon 2
![cambridge-radio-1](https://user-images.githubusercontent.com/42757252/47263771-e87f1300-d542-11e8-99e5-a058aca15aa0.png)

z17 Icon 3
![cambridge-radio-3](https://user-images.githubusercontent.com/42757252/47263773-eb7a0380-d542-11e8-8349-6a210c142a18.png)

LOFAR Radio telescopes in Germany, closed ways
https://www.openstreetmap.org/way/132557743
https://www.openstreetmap.org/#map=18/50.8976057/6.4233260
z17 Icon 2
![lofar-radio-1](https://user-images.githubusercontent.com/42757252/47263800-8672dd80-d543-11e8-9006-3b4569499a04.png)

z17 Icon 3
![lofar-radio-3](https://user-images.githubusercontent.com/42757252/47263802-87a40a80-d543-11e8-8b15-99ab98c74870.png)

I notice that many radio telescopes have telescope:diameter=* in meters. Some are 30 or 40 meters! Should we consider using this to determine initial rendering zoom level, as is done with man_made=tower and height?

We could use waypixels for those that are drawn as closed ways, but because some radio telescopes are mobile (the dish moves to point at a specific place in the sky), it may be impossible to draw a correct geometry based on satellite imagery. And most are currently mapped as nodes.

I may need some help with the code. I'm not sure how to select only man_made=telescope with telescope:type=radio in the project.mml file; to get these images I just selected all man_made=telescope, but that puts name labels on optical telescopes as well. When I tried to imitate the code used for types of towers I got an error that the column "telescope:type=radio" did not exist.

**Comment by kocio-pl** [comment] 2018-10-21 06:51
I like icon 3.

For non-standard columns, we use hstore, which requires special syntax. Look for example at #3136.

**Comment by jeisenbe** [comment] 2018-10-22 12:40
I figured out the problem. I had not yet added telescope:type to the sections of the project file relating to name label rendering. Now it works, that is, radio telescopes are shown with the icon and name label, but optical (or other) types of telescopes are not shown. Note in this image the Keck and Subaru telescope name labels are coming from the name of the building, hence the light gray.

![radio-not-optical-telescope](https://user-images.githubusercontent.com/42757252/47292455-fb2c4180-d641-11e8-9c92-e6668f86bb0e.png)

I can make  PR for just radio telescopes now, if that's easier.

(I actually think it would be good to render optical telescopes with a dome + telescope icon. There are 366 tagged and they are rare features in the real world: https://wiki.openstreetmap.org/wiki/Tag:telescope:type%3Doptical)

**Comment by Tomasz-W** [comment] 2018-10-26 11:29
@jeisenbe Optical telescope icon proposal:

![telescope type optical](https://user-images.githubusercontent.com/25656654/47563760-21443100-d923-11e8-8c8e-4ffeaf57692f.png)

**Comment by jeisenbe** [comment] 2018-10-26 15:32
Thanks! Is there a link to download?

**Comment by Tomasz-W** [comment] 2018-10-27 12:29
I've changed it a little bit:

![telescope type optical](https://user-images.githubusercontent.com/25656654/47604001-2a510300-d9f4-11e8-8634-034214c48a48.png)

Gist link: https://gist.github.com/Tomasz-W/f8b8e3b06d6e6ec2867b50269fbe427c

**Comment by jeisenbe** [comment] 2018-10-27 12:37
Initial tests with PNG (the color is black, not man_made gray color which we will get with the svg).

I've again used the telescope:diameter to set the initial zoom level. Usually a the dome around a telescope is 5 to 10 times greater than the diameter of the instrument. The telescopes on Mauna Kea range in size from 0.6 to 10 meters; the smallest are in a dome 6 meters diameter, and the biggest domes are 40 or 50 meters.s

So z14 is for >=8m (only the top dozen telescopes in the world, at this moment, but more are being built), z15 for >=4m (a few dozen), z16 for >=2m, and z17 for smaller or untagged telescopes.

I'm assuming that all telescopes are optical telescopes unless they are specifically tagged otherwise (eg Radio, Radar, Gamma). Near-visible spectrum telescopes, eg Infrared, are probably similar enough to optical to use the same icon. 

Mauna Kea is one of two places in the world with this many huge optical telescopes in one place (the other is in Chile):

z15
![maunakea-z15](https://user-images.githubusercontent.com/42757252/47603458-28546780-da27-11e8-8d1b-03b692861d91.png)

z16
![maunakea-z16](https://user-images.githubusercontent.com/42757252/47603461-2b4f5800-da27-11e8-878b-ad350fa8551e.png)

z17
![maunakea-z17](https://user-images.githubusercontent.com/42757252/47603463-2e4a4880-da27-11e8-8228-236a9527111b.png)


_This institute southwest of Berlin has several telescopes of less than 2 meters in size, drawn as closed ways._ 
z16 (not yet visible)
![berlin-leibniz-z16](https://user-images.githubusercontent.com/42757252/47603464-330efc80-da27-11e8-9e5a-bd7d14b9ce3b.png)

z17
![berlin-leibniz-z17](https://user-images.githubusercontent.com/42757252/47603465-34402980-da27-11e8-8ff7-cac013410fad.png)

z18
![berlin-leibniz-z18](https://user-images.githubusercontent.com/42757252/47603467-386c4700-da27-11e8-8b20-f103c3be482c.png)


_Hampstead Observatory in London_
z16
![hampstead-z16](https://user-images.githubusercontent.com/42757252/47604058-66ee2000-da2f-11e8-9e52-ee1536f42154.png)

z17
![hampstead-z17](https://user-images.githubusercontent.com/42757252/47604060-68b7e380-da2f-11e8-9f9d-b4fe8d258b57.png)

z18
![hampstead-z18](https://user-images.githubusercontent.com/42757252/47604061-6ce40100-da2f-11e8-99d8-b9da4ded7fcb.png)

I have not been able to find any telescopes larger than 2 meters in towns or cities; they all appear to be built on mountains (this usually provides better atmospheric conditions).

**Comment by matkoniecz** [comment] 2018-10-27 13:31
> I have not been able to find any telescopes larger than 2 meters in towns or cities; they all appear to be built on mountains (this usually provides better atmospheric conditions).

Yes, due to light pollution it is unlikely that there is an expensive telescope will be located in a city.

And 2+ m telescopes that are museum pieces are fairly rare (nonexistent?).

**Comment by matkoniecz** [comment] 2018-10-27 13:34
one think that should be checked: is OSM wiki definition of diameter is capable of handling also telescopes built from separate mirror pieces with a small diameter that are equivalent to large diameter one - see https://commons.wikimedia.org/wiki/File:Comparison_optical_telescope_primary_mirrors.svg

**Comment by jragusa** [comment] 2018-10-29 08:53
why not using the `@man-made-icon` color instead of black ?

**Closed** 2018-11-09 16:02 UTC
Labels: amenity-points
