### ISSUE TITLE
Ottawa city hall name blotted out by cafes inside

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4876] opened 2023-09-27 09:04 UTC
### Expected behavior
See which building is the city hall
### Actual behavior
Name blotted out by shops within.
https://mc.bbbike.org/mc/?lon=-75.68973&lat=45.42055&zoom=17&num=3&mt0=mapnik-german&mt1=esri&mt2=google-map&marker=city%20hall

There needs to be more priority given to the building's name.

### Screenshots with links illustrating the problem
![20230927T035948](https://github.com/gravitystorm/openstreetmap-carto/assets/1230959/fb3439b7-2aa7-44a2-91b4-1c47d0286a10)

**Comment by imagico** [comment] 2023-09-27 10:48
Once again: Duplicate of #3880 (and #234 to some extent).

After already mentioning it in #4859:  Please don't report symptoms of problems we have already identified over and over again.  You have reported so many of these meanwhile that you should be able to recognize that.

**Closed by imagico** 2023-09-27 10:48 UTC

**Comment by jidanni** [comment] 2023-09-27 20:17
Yes. The problem is that it is nearly impossible with a keyword search to find if I have reported the exact same problem already.
