### ISSUE TITLE
Rendering of natural=spring

### ISSUE THREAD

**Issue by MaestroGlanz** [gravitystorm/openstreetmap-carto#2649] opened 2017-05-31 05:40 UTC
I'm too less experienced to this via fork and pull, so I do this via an issue.

The rendering of natural=spring is an "S":
https://wiki.openstreetmap.org/wiki/File:Spring-7.svg

But in my opinion there shouldn't be letters or numbers in the standard rendering. Except for things like McDonalds (M), which are the same worldwide, but is rendered as fast food anyway. 

So I created this Icon:
https://wiki.openstreetmap.org/wiki/File:Natural-spring-14.svg

**Comment by imagico** [comment] 2017-05-31 06:44
Thanks for the suggestion - this is a duplicate of #325.

**Closed by imagico** 2017-05-31 06:44 UTC
