### ISSUE TITLE
Underground platforms are rendered over buildings

### ISSUE THREAD

**Issue by AndrewHain** [gravitystorm/openstreetmap-carto#2130] opened 2016-05-22 12:10 UTC
Underground railway platforms are rendered over buildings and pedestrian routes even though a deep layer has been set. For instance: Green Park (London), Chatelet Les Halles (Paris).

**Comment by gorn** [comment] 2016-05-22 13:43
This is all realted to recent decision to render highways on top of everything no matter what. This decision went clearly too far. **Please start to respect layer=*** unless there is absolutely no way to map aby underground platforms (highway=pedestrian/platform, layer=-1), shopping malls, metro stations etc etc. Sure it is not good to map for renderer, but there is even no way to map for renderer no matter what. Or tell us how you imagine it.

**Comment by math1985** [comment] 2016-05-22 17:30
Unlike you state, this is not a recent change: http://bl.ocks.org/tyrasd/raw/6164696/#18.00/51.50636/-0.14116

Unfortunately layering issues tend to be hard to solve. If you have ideas on how to solve this, I would love o see a pull request.

**Comment by matkoniecz** [comment] 2016-05-26 18:59
Alternative - hiding underground platforms seems to be even worse.

**Comment by matkoniecz** [comment] 2016-05-26 18:59
And anyway duplicate of #2037

**Closed by matkoniecz** 2016-05-26 18:59 UTC
