### ISSUE TITLE
Further clean-up mid zoom levels

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#3331] opened 2018-08-05 21:18 UTC
Some ideas to further clean up the mid zoom levels:

Current:

<img width="500" alt="screen shot 2018-08-05 at 23 11 50" src="https://user-images.githubusercontent.com/5251909/43690118-0096c0fc-9905-11e8-980f-dae928c5862c.png">

Dropping buildings from z13:
<img width="502" alt="screen shot 2018-08-05 at 23 11 28" src="https://user-images.githubusercontent.com/5251909/43690210-87a5a9fe-9906-11e8-910b-690898eec119.png">

Dropping footways from z13:
<img width="499" alt="screen shot 2018-08-05 at 23 18 02" src="https://user-images.githubusercontent.com/5251909/43690170-d497fb50-9905-11e8-8dc2-d0ad69c44adf.png">

Dropping buildings and footways from z13:
<img width="501" alt="screen shot 2018-08-05 at 23 15 10" src="https://user-images.githubusercontent.com/5251909/43690152-7b268d66-9905-11e8-86dc-e9f1b4eb9aea.png">

**Comment by matthijsmelissen** [comment] 2018-08-05 22:01
Some more ideas for changes to z13:
* Drop service roads
* Drop pedestrian roads
* Different rendering of pedestrian
* Drop playground outlines
* Different rendering of cycleways
* Lighten up the color of trams

<img width="499" alt="screen shot 2018-08-06 at 00 01 40" src="https://user-images.githubusercontent.com/5251909/43690541-edcdddc8-990b-11e8-8091-579ed84690af.png">

**Comment by kocio-pl** [comment] 2018-08-05 23:34
I like these ideas. I also don't see big difference between images, which is good, because I feel this is just tuning proposition, not a big redesign. It's a hack to make #2896 less severe.

Buildings are not too big on z13, they only make the view brownish, so they might be shown later.

Footways can be annoying on z13, especially on cemeteries or allotments.

I'm interested how would you like to show pedestrian or cycleways.

Could you give the link to the code so I could make more testing? It would be also good to test it in more places you know, so the testing would be independent.

**Comment by matthijsmelissen** [comment] 2018-08-06 05:25
Code is at https://github.com/matthijsmelissen/openstreetmap-carto/commits/z13-cleanup - but note this is still very early phase.

**Comment by Tomasz-W** [comment] 2018-08-06 06:16
My remarks:
* trams could be even more lighten up
* cycleways with changed rendering looks like water

Please add test renderings from other places, because just one is not enough for such a big change.

**Comment by matkoniecz** [comment] 2018-08-06 10:15
> Dropping footways from z13:

Current footway zoom level is a balance between urban and rural/remote areas with both sides about equally badly rendered. This will improve styling a bit in cities and make it noticeably worse in the countryside. Note #211 and comments like https://github.com/gravitystorm/openstreetmap-carto/pull/747#issuecomment-50230004

**Comment by matkoniecz** [comment] 2018-08-06 10:18
> Drop pedestrian roads

Before seriously considering that #1964 "highway=pedestrian not shown at z12" should be closed as rejected. Personally I would reject both rendering highway=pedestrian at z12 and not rendering it at z13 (well, I already did it once, that is why I decided to leave potential closing #1964 for others)

**Comment by matthijsmelissen** [comment] 2018-08-06 13:18
> Please add test renderings from other places, because just one is not enough for such a big change.

I'm in favour of sharing work in progress early and often. That has as a consequence that early presentations of ideas are necessarily basic :). We'll definitely study how this works on multiple places before merging this. You probably didn't mean it like that, but please be careful of not sounding too demanding :).

**Comment by dieterdreist** [comment] 2018-08-07 07:55
sent from a phone

> On 6. Aug 2018, at 00:01, Matthijs Melissen <notifications@github.com> wrote:
> 
> Drop pedestrian roads


from this list, dropping the display of pedestrian roads on z13 seems the most problematic. It will lead to gaps in the road structure in some places.

**Comment by kocio-pl** [comment] 2018-08-07 13:04
I'm happy to test it more when the idea will be more or less settled. Let me know then.

**Comment by Nakaner** [comment] 2018-08-08 08:01
If you drop buildings from zoom level 13, you should have a look at cities which have all buildings mapped but no `landuse=residential`. This is an issue most mappers are not aware of because the tiny buildings on z13 combined with many residential streets give a similar impression than the grey polygon fill colour of `landuse=residential`. On the other hand, dropping buildings on z13 might drive mappers to fill the gaps in the residential landuse to make the map look nice.

Countries with lots of manual mapping (in contrast to the imported Netherlands) are worth to be looked at. I would recommend to look at Munich, Hamburg, Dortmund and Rome.

**Comment by dieterdreist** [comment] 2018-08-08 16:39
sent from a phone

> On 8. Aug 2018, at 10:01, Michael Reichert <notifications@github.com> wrote:
> 
> If you drop buildings from zoom level 13, you should have a look at cities which have all buildings mapped but no landuse=residential.


+1, I also suggest to look at huge buildings, for which z13 is already too late and creates a strange change when zooming from z12 to 13, e.g. the former Tempelhof airport, industrial buildings and so on.

**Comment by kocio-pl** [comment] 2018-08-09 01:40
As requested - [former Tempelhof airport at z13](https://www.openstreetmap.org/#map=13/52.4739/13.4135) with current cleanup code (which BTW shows buildings on z15+, not z14+):

Before
![86g9cmdp](https://user-images.githubusercontent.com/5439713/43873180-c85d6e6a-9b85-11e8-9699-5267d1b3e019.png)

After
![qpo49vco](https://user-images.githubusercontent.com/5439713/43873178-c59bac64-9b85-11e8-8cae-28422974c65a.png)

**Comment by kocio-pl** [comment] 2018-08-09 01:58
Center of Rome at z13:

Before
![dbh_9q s](https://user-images.githubusercontent.com/5439713/43873788-64ca6508-9b88-11e8-8550-ed6b64c53f1f.png)


After
![wmpbob2a](https://user-images.githubusercontent.com/5439713/43873772-4add8896-9b88-11e8-8458-e8c8dc6ad8c6.png)

**Comment by kocio-pl** [comment] 2018-08-09 02:12
Warsaw at z13

Before
![xwpsbtoe](https://user-images.githubusercontent.com/5439713/43874111-33c6358e-9b8a-11e8-8e52-3fb827d8fcbe.png)

After
![fnunkktk](https://user-images.githubusercontent.com/5439713/43874122-43c0fd8e-9b8a-11e8-90b6-613e14a72982.png)

**Comment by kocio-pl** [comment] 2018-08-09 02:25
Dortmund at z13

Before
![f5rusdt6](https://user-images.githubusercontent.com/5439713/43874436-321402aa-9b8c-11e8-9238-74d71c6ec3cc.png)


After
![jwduetpx](https://user-images.githubusercontent.com/5439713/43874425-253e7ae2-9b8c-11e8-85de-bb0c5954d2e5.png)

**Comment by kocio-pl** [comment] 2018-08-09 02:33
Hamburg at z13

Before
![dgpjq_kz](https://user-images.githubusercontent.com/5439713/43874640-39fc1bfa-9b8d-11e8-9e51-d2872fd09d69.png)


After
![w7tc1 ha](https://user-images.githubusercontent.com/5439713/43874647-44f560e8-9b8d-11e8-858b-b3dd6730d1d5.png)

**Comment by kocio-pl** [comment] 2018-08-09 02:42
London at z13

Before
![yk65ib8l](https://user-images.githubusercontent.com/5439713/43874895-8a49239a-9b8e-11e8-8db0-f098ff0da34d.png)


After
![vgn0aqt1](https://user-images.githubusercontent.com/5439713/43874874-644e2f0a-9b8e-11e8-8b2f-c62283467c0d.png)

**Comment by mboeringa** [comment] 2018-08-09 07:17
To be honest, I think that the removal of the buildings at these zoomlevels is going to be **_highly_** controversial in the community. Showing buildings at a relatively early stage is one of the key benefits and differences with many other (vector) map styles of this style. I think you should announce this in some more open way than just in this repository if you desire to have real input on this idea.

**Comment by kocio-pl** [comment] 2018-08-09 10:42
On z13 there are only single examples of buildings really visible, the rest is just making brown noise and is not really useful.

**Comment by mboeringa** [comment] 2018-08-09 13:52
I agree Z13 is a kind of "breaking point" for displaying buildings. Still, there are many large structures that will disappear too. Hence I do think it wise to announce this wider if you truly wish to have more input on this major change.

**Comment by kocio-pl** [comment] 2018-08-09 13:57
I guess it'll be mostly some industrial buildings, but I like showing industrial landuse instead more (south Hamburg looks better IMO) and this is still not that big change for me. But that's not my issue and you can do what you consider to be good.

**Comment by dieterdreist** [comment] 2018-08-09 14:29
sent from a phone

> On 9. Aug 2018, at 12:42, kocio-pl <notifications@github.com> wrote:
> 
> On z13 there are only single examples of buildings really visible, the rest is just making brown noise and is not really useful
> 


There are both, a few individual buildings that are recognizable and patterns of urban structure that are very useful for reading the city.

In some areas, the map would become extremely worse than it is now, for example: https://www.openstreetmap.org/#map=13/45.4815/-73.7089

I partly agree that the buildings are not very readable at z13 currently, but from my point of view this originates from the poor contrast with typical urban landuses and could be fixed with a darker building fill (also depends on latitude and building sizes and urban structure (detached/attached)).

**Comment by kocio-pl** [comment] 2018-08-09 14:45
For me it's the same as Hamburg case - looks better when I see the industrial area instead of all the industrial buildings:

Before
![nhod1eqk](https://user-images.githubusercontent.com/5439713/43906444-93c96b22-9bf3-11e8-8aa1-8cca705e3a23.png)


After
![tjpo9hea](https://user-images.githubusercontent.com/5439713/43906454-9700fe86-9bf3-11e8-9b37-06b003abb459.png)

**Comment by dieterdreist** [comment] 2018-08-09 15:59
sent from a phone

> On 9. Aug 2018, at 16:45, kocio-pl <notifications@github.com> wrote:
> 
> For me it's the same as Hamburg case - looks better when I see the industrial area instead of all the industrial buildings:
> 
> Before
> 
> 
> After
> 
> 


I see the industrial area in both, but for me removing the buildings reduces the information content significantly, e.g. for orienteering. It depends what you want from the map of course. Less content is usually cleaner, agreed.

**Comment by kocio-pl** [comment] 2018-08-13 17:17
I'm not convinced by orienteering at all - first, there are multiple outdoor maps which might be better for this task, second - with proper landuse you should know that there is a industrial area around. 

z13 would be the only zoom level where you can recognize different landuses without building clutter (z12 has general gray for builtup areas, z14 would have all the buildings) and I like this idea.

**Comment by kocio-pl** [comment] 2018-08-14 03:37
Another example - Moscow:

Before
![ovt7clmm](https://user-images.githubusercontent.com/5439713/44070420-07734ffa-9f84-11e8-85f8-6ed04beb5c3e.png)

After
![y0mcakjn](https://user-images.githubusercontent.com/5439713/44070425-14184e9a-9f84-11e8-856b-558b25629e87.png)

**Comment by ximex** [comment] 2018-08-22 19:11
If you drop the footways wouldn't it bad to have a good overview of the hiking ways in the wild?

**Comment by SomeoneElseOSM** [comment] 2018-08-22 20:07
@ximex That ship has already sailed, I think.  Since https://github.com/gravitystorm/openstreetmap-carto/pull/747 back in 2014 it's been impossible to use this style for a hiking map to visualise e.g. a 20km walk.

For good or ill the focus of the developers of this style is on central European cities (just look at the screenshots in the thread so far).  People tend to scratch their own itch; that's understandable.  It's not possible to have one map style that works well for every use case since some are contradictary (in fact, some of the goals of https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md are too to some extent).

**Comment by imagico** [comment] 2018-08-22 22:38
> It's not possible to have one map style that works well for every use case since some are contradictary (in fact, some of the goals of https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md are too to some extent).

You are right if you say _it is not possible to have one map style that works well for every use case_ but i think you can also clearly say that it would be possible to do much better than this style does right now.  The documented goals could be pretty helpful for that but practically it turned out to be unrealistic in most cases that they would actually help.

I should however mention that the goals were written when development here was still based on consensus so the spectrum of perceptions and priorities at least to some extent ensured some balance between the goals and some counterweight to special interests and narrow priorities.

**Comment by kocio-pl** [comment] 2018-08-23 00:17
I believe the main obstacle for better coexistence of big cities and outdoor rendering is #1957 "equalizing" ticket being unresolved.

I think about "WMAs" (well-mapped areas), which are located in the big cities where mappers were active, that they make the biggest difference. They start to be very rich, because this is the reality, which was not well covered by mappers just a few years ago. We could rely on this incompleteness up to some point and render whatever was available without critically rethinking the whole system for years. But this is no longer true and the WMAs begin to be drastically more dense than outdoor areas. This is nobody's fault, it's just the unexpected consequence of the success of OSM in gathering all kind of data. Of course, we might stay with what we were showing before, but it's just closing eyes to avoid noticing the constant change of OSM data. Something like taking the snapshot of some past moment and refusing to take more current ones, just because it's more familiar for cartographers than trying to face these new challenges.

I like the outdoor rendering and when it doesn't hurt, I'm happy to make it also rich. There are places where we outperform typical (if not all) outdoor maps with details, like for example here:

https://www.openstreetmap.org/#map=17/47.35137/8.49157

But without some kind of equalizer (making rendering aware of a place context), it's absolutely not possible to find a visual balance between rural/urban environments. And when this inevitable moment of clash comes, I tend to care more about proper depicting WMAs than the outdoor. 

Why? 

1. There are already many outdoor maps in the wild, including some based on OSM data (Hike&Bike, OpenTopoMap, cycling maps etc.), which are better suited for such tasks as hiking, precisely because they are very limited by design. General, rich map is just not a competitor for them. And I don't even mention primary solution for such activities, which are Garmin-like devices packed with vector maps and geolocalization included.

2. Choosing the outdoor advantage is not just trying to play the wrong game, it also means clutter for WMAs with no hope for being readable. And these are the places where a lot of people might be interested in looking at the map. Rendering problem in the middle of Andes is still a problem, but for example [visual mess in London](http://bl.ocks.org/matthijsmelissen/raw/7d2b0538a8b64b9d31e2/#10.00/51.4598/-0.1256) is just much worse.

3. The last argument is that there are no special maps of WMAs. There might be hand-crafted maps of specific places, but no other general map style to reflect data richness. I believe they deserve to be shown as good as it's possible.

**Comment by imagico** [comment] 2018-08-23 07:37
@kocio-pl - if that is the dominant opinion among currently active developers you should change the cartographic guidelines because what you write is fundamentally and ostentatiously in conflict with them.

**Comment by kocio-pl** [comment] 2018-08-23 07:52
Could you point out these conflicts, at least the main ones?

I'm not sure whose opinion might it be beside myself, and this is kind of very fresh vision I got just recently as a result of experience with developing this style. As you probably remember, I'm OK with the goals that got into the guidelines and also I was quite sure they are still valid for me lately, I just have different interpretation of them and my goals were mainly related to the teamwork, not to the code or cartography. That's why I was not able to draft my view until now.

**Comment by imagico** [comment] 2018-08-23 08:17
No, i won't discuss the goals yet again just to have you cherry pick the ones you like on a per-case basis and interpret them to support your interests while dismissing the rest.  The guidelines are very clear in describing how they are meant to be used and my suggestion is that if you don't use them this way you should remove or change them.  Saying you are OK with the goals if there is no need or even incentive to actually work towards the goals in substance is kind of cheap.

As said above already it is clear to me now that it was unrealistic that the guidelines would do any good with the current development model.

**Comment by kocio-pl** [comment] 2018-08-23 13:01
OK. I just thought that if you see conflicts, you can show them, because I don't see them:
- "There is no fixed order of priorities" - maybe I could argue with this sentence, because "rich map" is more important to me than the rest, but "not fixed" means that prioritizing them myself is allowed, so I guess no conflict here.
- You have interpretation of "rich map" (more or less "the map is already rich, don't add more things") which is as good as mine ("the goal of a rich map is still ahead of us and it's just not possible to render thousand keys") - both are not violating "very clear" rules, so maybe they're not as clear as you'd like to, but there's no conflict for me with what is written.
- "These rules are not set in stone, they can change and they may not be followed in all cases" - so even written guidelines are not so strict after all and no need to change them.

You gave a written set of "dots", but no higher level idea than them (even if you have some in your head, I don't know that). I just connect these dots in some pattern and I have wrote about my higher level idea here, which explains how I see the dots. This is not contradicting in my view and I still prefer to do the team job than rephrase guidelines. However I think about writing some diary entries about how do I see this project now and what I've learned while developing it.

**Comment by imagico** [comment] 2018-08-23 13:28
I think you just perfectly made my point.

**Comment by kocio-pl** [comment] 2018-08-23 13:31
Well, now I really don't know what do you mean, because I have just shown it's not contradicting, as you claim.

**Comment by dieterdreist** [comment] 2018-08-24 13:13
2018-08-23 15:01 GMT+02:00 kocio-pl <notifications@github.com>:

>
>    - "These rules are not set in stone, they can change and they may not
>    be followed in all cases" - so even written guidelines are not so strict
>    after all and no need to change them.
>
>


if we hold up this way of reading, I agree with Christoph it would be more
honest to abolish all rules all together, because if you reserve the right
to not act according to them in some cases, you end up in the same
situation as not having them and being frank about this seems more
transparent.

**Comment by kocio-pl** [comment] 2018-08-24 13:35
OK, it sounds reasonable to me. I don't think abolishing is the right way, rather rearranging.

Anyway I need some time to gather all my experiences and write about them. Another thing is if other people will agree with my visions and goals. But discussion about such things should go to #1975, not in this thread, so let's continue this thread there.

**Comment by Adamant36** [comment] 2018-09-13 01:35
Any chance of getting rid of streams at Z13? They are way to prominent at that level in places where there are a lot of them. Plus, %99 of the time they aren't major features like roads or landuse. Otherwise, they would be tagged as rivers.

**Comment by matkoniecz** [comment] 2018-09-13 03:07
> A lot of them are pretty tiny and don't have water most of the time.

Note that it strongly depends on a region. 

> don't have water most of the time

Are such waterways already tagged with intermittent=yes?

**Comment by Adamant36** [comment] 2018-09-13 03:34
@matkoniecz, of course it does. As does everything though. Although if they aren't small features, they can/should still be tagged as rivers. Your the one that told me as much in the first place. According the wiki, a stream is something a healthy person can jump across. From the research I have found, the world record for jumping distance is 29 feet 4 inches (the width of a residential street btw). That was a long jump expert. So what could a normal person jump? Like 10 feet? Id hardly call anything 10 feet or less then that a major feature. Personally, I think its a dumb way to classify something, as a 12 foot wide waterway that can't be jumped over shouldn't be classified as a river, but any complaints I have about it clearly don't matter and I don't have a better idea anyway. 

Either way, making them not view able on z13 would at least fit with @kocio-pl's "mapping things based on size" thing. Plus, know one is going to be concerned with a 5 foot wide dry creek at that zoom level. Especially since it gets in the way of seeing track/residential roads. Really, Id put them in the same category as driveways/parking isles/general service roads/power lines etc in importance and size. None of which are shown yet at z13. 

And yes they are tagged as intermittent. It doesn't make a difference and probably makes it worse in some places if anything.

**Comment by Adamant36** [comment] 2018-09-13 04:27
@jeisenbe, I could go with that. My main issue is with intermittent ones.

**Comment by jeisenbe** [comment] 2018-09-13 05:03
Great. Do you have a link to a place where too many intermittent are
displayed, currently?
I wonder it they might be due to bad data imports in some places.
I recall that the hills in Southern Oregon show too many streams, but they
are all from automated imports.
It looks like every low spot was shown as a stream, though many of these
only flow with the biggest winter storms:
https://www.openstreetmap.org/#map=14/42.2655/-122.9990

**Comment by Adamant36** [comment] 2018-09-13 05:30
@jeisenbe, Sure. There's this gem of an area in northern California that's a lot like the example you gave. Its probably from the same bad import you linked to. The NHD data that it is based on used LIDAR to map stream and its still considered an experimental technique. So it probably never should have been imported. https://www.openstreetmap.org/#map=13/40.0469/-122.6407

Although I agree that was from a bad import and most of those probably aren't streams, I was advised by people on the forum not to delete them unfortunately. So I just have to live with it. Therefore, I am more talking about places like here https://www.openstreetmap.org/#map=13/40.4339/-122.3867, here https://www.openstreetmap.org/#map=13/40.5482/-122.4785, 
here https://www.openstreetmap.org/#map=13/40.5298/-122.1973 etc. 

It would also be useful further up north in areas like above the lake here https://www.openstreetmap.org/#map=13/40.9137/-122.1505, most of those places do actually have streams as mapped. Although they hardly count as geographical features and are dry 99% of the time. They still can't be deleted though and cause problems with viewing things like track roads that intersect them at that zoom level. Although a case could be made that southern Oregon/northern California is an exception due to the overall denseness, I still think there would be merit to not displaying intermittent streams at z13 in areas where they are not as thick/is deserts/etc. As they still aren't major features or high priority in most cases. If they have water year round fine though. I can see merit in that.

**Comment by mboeringa** [comment] 2018-09-13 06:09
> Although I agree that was from a bad import and most of those probably aren't streams, **I was advised by people on the forum not to delete them unfortunately**.

Nobody can tell you to "not delete them". This is OSM, nobody is really in charge. 

If this data is from

- a poorly/undocumented or poorly executed import
- the data license is unclear
- the data entered is disputable or simply bad geometrically or otherwise

then please do remove or enhance the data by editing it. Leaving rubbish just because the data appears "detailed" or extents over large areas / involves many features, is ultimately of help to nobody (and certainly not to any data consumer or cartographer wishing to use the data)

**Comment by Adamant36** [comment] 2018-09-13 06:33
@mboeringa, Thanks. Although I completely agree with you, according to Frederik Ramm the number one rule of OSM is not to do anything that upsets people and more then likely its not worth the judgmental messages I'll probably receive afterwords from people like him or @matkoniecz, who disagree with us, for doing something I was told not to. Bad imports aside, I still think there is merit in not showing intermittent streams at z13.

**Comment by dieterdreist** [comment] 2018-09-13 07:49
sent from a phone

> On 13. Sep 2018, at 03:35, Adamant36 <notifications@github.com> wrote:
> 
> Plus, %99 of the time they aren't major features like roads or landuse.


they are significant features for reading the landscape as they tell the elevation / structure

**Comment by jeisenbe** [comment] 2018-09-13 08:06
If you verify every stream on good aerial imagery, I don't see an objection
to removing features that clearly do not exist. However, it is pretty
difficult to disprove the exitence of an intermittent stream from aerial
imagery alone, so caution is reasonable.

I believe marking the imported streams as "intermittent", when they cannot
be verified on satellite imagery, would be acceptable. I'll probably be
more inclinded to do it myself, if it means they won't render on z13, so
good call on that.

**Comment by andrzej-r** [comment] 2018-09-27 21:18
1. Buildings - I don't see them as a problem. IMHO all above examples look better with them, but that may be just me. With vector tiles we could remove buildings for rendering efficiency reasons but that's not an issue with raster tiles. We could perhaps use transparency instead of contrast to reveal more of the underlying landuse color (that could also be helpful with tunnels under buildings etc) but I don't think building are currently too prominent.
2. Paths - I am not a fan of red and blue rendering. It is indeed a bit too prominent at lower zoom levels but that could be avoided by rendering paths in white - less prominent, more consistent with roads, more consistent with other maps.

One more thing: removing information (here: buildings) with an intention of forcing mappers to add alternative information (landuse) is _bad_. We are an open data project so even a hint of coercion can be very damaging.

**Comment by matthijsmelissen** [comment] 2018-10-07 18:15
Thanks for all feedback.

I don't think I'm able to come up with a good idea for cycleways now, so I'm leaving these outside scope for now.

**Closed** 2018-11-03 23:55 UTC
Labels: cartography
