### ISSUE TITLE
Add icon for leisure=hackerspace

### ISSUE THREAD

**Issue by miniwark** [gravitystorm/openstreetmap-carto#1693] opened 2015-07-28 11:29 UTC
[leisure=hackerspace](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dhackerspace) is used to map hackerspaces, makerspaces (and sometime fablabs). There is actually no icon to render them in Mapnik. Actually there are [365 tagged points](https://taginfo.openstreetmap.org/tags/leisure=hackerspace).

As, almost all this leisures are for DIY stuff, a simple render solution is to use the [shop_diy](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop_diy.16.svg) logo.

The other easy alternate solution is to use the [computer]([https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/computer-14.svg) logo.

If not accepted i would think of a gear like or lab logo (because this symbol is popular in hacker spaces logos around the world), but i think it is not necessary to create a new special logo, when is possible to use an already existing one.

**Comment by HolgerJeromin** [comment] 2015-07-28 12:28
duplicate of #451

**Comment by dieterdreist** [comment] 2015-07-28 12:41
> Am 28.07.2015 um 13:29 schrieb Bertrand Lecervoisier <notifications@github.com>:
> 
> i think it is not necessary to create a new special logo, when is possible to use an already existing one


using the same icon for different stuff reduces the usefulness of the icon for all these things. It does only make sense if the tags are synonyms or very close and should not be differentiated in rendering

**Closed by dieterdreist** 2015-07-28 12:41 UTC

**Comment by kocio-pl** [comment] 2015-09-19 09:40
Is it close to the community centre or not?

**Comment by HolgerJeromin** [comment] 2015-09-19 11:36
I think the target audience of a community_centre and a hackerspace have no or a really small intersection. :)

**Comment by kocio-pl** [comment] 2015-09-19 11:50
Thanks. :smile: I was wondering what is community centre really, cause I'm not familiar with such things.

**Comment by math1985** [comment] 2015-09-20 10:39
> I was wondering what is community centre really, cause I'm not familiar with such things.

I think the Polish equivalent is dom kultury / dom ludowy. After Google'ing, I found http://www.sdk.pl, which I would call a community centre, not an arts centre: they offer various art courses and performances, but also things like computer courses for the elderly.

**Comment by kocio-pl** [comment] 2015-09-20 12:37
Yet some of the "dom kultury" ("house of culture") POIs should be rather tagged as arts centre (6k+ uses), so it looks like we have a few of similar, but not identical type of objects, and the name is not the ultimate hint:
- amenity=community_centre
- amenity=arts_centre
- club=art (and the likes)

with social facility, hackerspace and squat being around too. Tagging and rendering them is not quite clear for me as of now.

**Comment by miniwark** [comment] 2015-09-20 13:25
@kocio-pl hackerspace are [amenity=community_centre](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcommunity_centre) in the sense of "Community centres are public locations where members of a community tend to gather for group activities". In this case, mainly computer hacking and DIY activities. But they are more a sort of "computer club" or "hobby club" a mix of club =computer ; club=doityourself ; club=linux ; club=electronic ... Also as stated in the [wiki](http://wiki.openstreetmap.org/wiki/Key:club) amenity=community_centre is preferred over club=* for generic public facility and hackerspaces are not "generic".

Also, i personally think than amenity=community_centre must be better defined, because his definition vary a lot from country to country. For example in France, it is recommended by the OSM wiki to use it for "salle des fêtes"  ([Function hall](https://en.wikipedia.org/wiki/Function_hall)) but Wikipedia translate it as "Centre social" witch are more like the (Settlement movement)[https://en.wikipedia.org/wiki/Settlement_movement]. Both definitions are not hackerspaces... 

Hackerspaces are not amenity=arts_centre to, even if they may be art oriented. In this case, arts done in hackerspaces are almost only computer arts.
