### ISSUE TITLE
Treat segments with the same street name as one line

### ISSUE THREAD

**Issue by Debeet** [gravitystorm/openstreetmap-carto#1535] opened 2015-05-06 19:48 UTC
I don't know about the others but the way names are rendered always annoyed me. Here's what I mean:

![untitled-1](https://cloud.githubusercontent.com/assets/3075576/7502046/62a837fe-f439-11e4-9ea1-d311ac181832.png)

Road segments are highlighted by pink lines. Notice how names are rendered? It really tries to put name on every segment.

Couldn't these segments with **the same street name** be treated by the renderer as one long line? It would result in something like this:

![untitled-2](https://cloud.githubusercontent.com/assets/3075576/7501998/f4a4da3c-f438-11e4-8a0f-2a8ffbd56369.png)

**Comment by matkoniecz** [comment] 2015-05-06 19:51
Duplicate of #497 and #673

**Closed by matkoniecz** 2015-05-06 19:51 UTC
