### ISSUE TITLE
boundary=administrative, admin_level=4 labels obscures place=city labels

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1391] opened 2015-03-15 12:59 UTC
(This is more general problem already described in https://github.com/gravitystorm/openstreetmap-carto/issues/1386 ):

Sometimes admin_centre name is obscured by admin_level name, which I consider a serious bug for a general map. For example Warsaw is not visible up to z=7 (I think there are some other bugs at low zoom levels, but 6 and 7 seem like obvious cases of above).

IMO admin_level should always try hard to allow admin_centre name to appear where it really is, because the area is probably huge and we have more flexibility in choosing the place to render its name. I would use the rule of thumb that admin_level name should always stay entirely in its boundaries - and only obscure the admin_centre name if it's not really possible.

**Comment by pnorman** [comment] 2015-03-16 19:05
What do you mean by admin_centre name? I do not find that text anywhere in the style.

**Comment by kocio-pl** [comment] 2015-03-16 19:55
I may be wrong what really causes problem, because we have relations, places, labels - so here is the visible province relation:

http://www.openstreetmap.org/relation/130935

and here is the obscured city relation:

http://www.openstreetmap.org/relation/336074

**Comment by math1985** [comment] 2015-03-16 20:01
The problem is that boundary=administrative, admin_level=4 labels obscures place=city labels.

I'm not sure if it's always a bad thing. What is more important to label, Northern Ireland or Belfast? Baden-Wurtenberg or Stuttgart? Massachussets or Boston?

**Comment by kocio-pl** [comment] 2015-03-17 01:19
1. We don't always have to decide what's more important - that's why I want moving state's name away from the city's name, not just getting rid of them.

2. See how it works in practice - for Poland it's much stranger than only Warsaw case:

z3 - blank area, not even country name (?)

z4 - only WP and MA voivodeships (quasi-states) are visible (clear USA-based influence, since nobody in Poland uses such abbreviations for voivodeships!), and no country name

z5 - only "województwo wielkopolskie" (that was WP at z4) and country name in the middle

z6 - now it's getting funny =} :
- we have all 16 voivodeships visible, but font style is weak
- no single (voivodeship's or country's) capital is visible at all
- country's name is visible on the Baltic Sea
- the most visible thing (solid black font) are the second-grade "in-between" cities

z7 - almost the same level of fun, now just the minority of capitals are visible, but country's capital is still not (!)

***

For now I want to focus on z6-7 (at least in this ticket probably), because it's clear space for improvement here and it's local. z4-5 would be interesting for sure too, because we have many countries to check:
- big countries like Canada and USA have states/provinces visible, but Canada have just dropped its name (only Vancouver and Toronto is visible at z4, but at z5 there's only Ottawa), and in USA we see Washington, NY, but also Miami, Houston, LA, all on the edge - and Atlanta and Denver in the mainland, as if they were more important or something. =}
- in Europe London is healthy as hell =} even from z3 (just because it's not in the center of UK or even England) - but the other capitals are only Stockholm, Amsterdam, Paris, Geneva, Rome, Vienna and Kiev, on the other hand we have "Deutschland" here (but no Berlin, which was visible at z3) or Romania (and no Bucharest)

And I haven't even look at the rest of the world! There are probably much more things to consider, but I think admin_level area names shifting away from cities could also help here to some extent.

**Comment by emmexx** [comment] 2015-05-21 13:15
Probably it is an already known issue but it is weird to view mapnik without finding immediately some obvious info.
One case in northeastern USA:
http://www.openstreetmap.org/#map=8/39.988/-75.333

I expected to see New York City, Philadelphia and Washington DC. Instead I see Yonkers, Camden and Arlington. At zoom 8!
New York appears at zoom 7, Washington and Philadelphia at 12.

In Italy at zoom 5 there are the labels for many of the larger cities but not for Rome (almost 3 million inhabitants) and Turin. But there are Compobasso (50000) and Catanzaro (91000).
At zoom 6 Milan disappears substituted by many small cities around it. Rome is still missing. Campobasso is still there.
At zoom 7 Milan comes back, Rome is missing, Campobasso gone.
At zoom 8 Romes makes its debut, Campobasso is back. Bologna is hidden by the region name.

**Comment by dieterdreist** [comment] 2015-05-21 19:31
> Am 21.05.2015 um 15:15 schrieb emmexx <notifications@github.com>:
> 
> At zoom 7 Milan comes back, Rome is missing, Campobasso gone.
> At zoom 8 Romes makes its debut, Campobasso is back. Bologna is hidden by the region name.


the Rome case is rather particular because there is a country label competing with it (vatican, not any more at the moment) as well as the region label (lazio, z6+7)
Rome's debut is in z3 btw (from natural earth), it's also there in z4 and then disappears for a long time until z8.

**Comment by daganzdaanda** [comment] 2015-05-22 15:53
> debut is in z3 btw (from natural earth)

I did not know that, how does it work? do those names come pre-selected in the dataset?

Also: Berlin is weird, too. 
Most importantly it is a city, even a capital. But it is also a "state" of Germany, and in our style, that seems to win sometimes. But then, it's a tiny state, and an enclave of Brandenburg. 
So in z3 it's "Berlin", the city (probably from natural earth). 
z4: "BB" for Brandenburg renders first, so neither Berlin the state nor the city is seen (also, these abbreviations are rarely used in Germany, too). 
z5: Brandenburg wins again, same at z6. 
z7: Finally, "Berlin" the city (label could be larger or stronger imho, for capital and relative size). 
z8: the label turns pink and italic, because it's Berlin the state this time... (same happens at Hamburg, but not with Bremen). 
z9: Berlin still tiny and pink (same with Hamburg *and* Bremen this time) 
z10: same as 9 (Bremen now gets a city label in addition to the state label)
z11: Berlin takes nearly the whole browser window, and now has a city label and a state label (Hamburg stil has only the state)
z12,13,14: all three city-states have doubled labels.
z15-19: no city label anymore, but the state label still remains. 

What I take from this exercise: 
- City labels for big cities and capitals should come before some minor admin labels. Maybe they should be priorized even before country labels: countries are bigger, so a country label could fit in another place, while a city label can't move much. In practice, I guess Mapnik's label placement is not very smart yet. 
- City labels should come before road labels at z11. (I'm guessing that's what keeps Hamburg from showing up at z11)
- It may make sense to drop admin labels starting from z11 or 12.

**Comment by matkoniecz** [comment] 2015-05-22 18:41
> so a country label could fit in another place

see #1069

> It may make sense to drop admin labels starting from z11 or 12. 

Not all of them (lower divisions)

**Comment by pnorman** [comment] 2015-05-22 18:57
as there is no thing such as an admin_center name and people are pointing out various separate issues, I'm looking closing this ticket. If people want to make more focused tickets about clearer issues, that's fine, but this ticket isn't clear.

**Comment by daganzdaanda** [comment] 2015-05-22 20:02
> but this ticket isn't clear.

I think @math1985 phrased it better:
*The problem is that boundary=administrative, admin_level=4 labels obscures place=city labels.*
Should we open a new issue with that title, or can an admin rephrase this one?

**Comment by dieterdreist** [comment] 2015-05-23 12:09
> Am 22.05.2015 um 17:53 schrieb daganzdaanda <notifications@github.com>:
> 
> City labels for big cities and capitals should come before some minor admin labels. Maybe they should be priorized even before country labels: countries are bigger, so a country label could fit in another place, while a city label can't move much. In practice, I guess Mapnik's label placement is not very smart yet.


Berlin is admin level 4, this is not "minor", it has the same significance as Bavaria or a state of the US, to make these new rules work we'd have to render (some?) cities before all admin names below the country level. Not bad IMHO, but will likely have quite some impact on certain levels, so this is a decision we should be well aware of and take it consciously.

**Comment by kocio-pl** [comment] 2016-06-19 18:30
> but I see no example of anybody doing this in CartoCSS.

Isn't [French style](https://github.com/cquest/osmfr-cartocss) a fork of osm-carto? IIRC @cquest managed to do it somehow.

**Comment by matkoniecz** [comment] 2016-06-19 18:54
They use `text-label-position-tolerance:` for placenames but as documented in https://github.com/mapbox/carto/blob/master/docs/latest.md it works only for lines. I also tested it and it gives no difference in rendering.

**Comment by kocio-pl** [comment] 2016-06-19 19:21
I did the testing too with the same results. Yet it looks something works in FR, so I will try to look at it it closer.

**Comment by kocio-pl** [comment] 2016-09-30 02:54
Please reopen this issue, it was incidentally closed by #2314 ("Tries to partly fix" contains "fix" keyword).

**Comment by cquest** [comment] 2016-09-30 13:08
My last work on this uses text-placement to allow the state labels to move around if needed.

**Comment by kocio-pl** [comment] 2016-09-30 13:59
I've been already trying to debug your fork, because it works better than this style for many months, but it has diverged too much and I was not focused enough. I still plan to test it and find out the difference - thanks for the hint!

**Comment by cquest** [comment] 2016-09-30 15:25
I forked the style at its early days... and learned carto-css at the same time.
I know that it is not clean at all but some pieces may be interesting ;)

I've also use some ugly tricks using the _rels / _ways tables to get some details not available in the geometry tables produces by osm2pgsql (for example to get the operator on bus stops when this tag in only available in the relation).
I did something a bit similar for the boundaries...

**Comment by kocio-pl** [comment] 2018-01-10 13:48
This should be probably resolved by using `grid` placement once it's available in the Mapnik - see https://github.com/mapnik/mapnik/pull/3780#issuecomment-356583060 and #2962.

**Comment by kocio-pl** [comment] 2018-03-04 22:14
The code [is in the Mapnik repo](https://github.com/mapnik/mapnik/pull/3858), now I wait for v3.0.19 release to test it.

**Comment by kocio-pl** [comment] 2018-03-07 15:05
Mapnik 3.0.19 has been released and is even [available as a Debian package](https://tracker.debian.org/pkg/mapnik), so I was able to not wait for official Ubuntu package, npm Mapnik bindings and Kosmtik update and forge it myself:
- rebuild it for Ubuntu (`git clone https://anonscm.debian.org/git/pkg-grass/mapnik.git && cd mapnik && git co experimental && dpkg-buildpackage -B`) 
- install the resulting packages in my system (`sudo dpkg -i *.deb`)
- build a node-mapnik bindings for it (`git clone https://github.com/mapnik/node-mapnik.git && cd node-mapnik && git co v3.0.x && make release_base`) 
- make a hack to run it in a testing instance of Kosmtik (I want to be still able to have stable Kosmtik version with proper npm installed node-mapnik, which still uses old Mapnik like v3.0.15) - it means linking this `node-mapnik` directory into `kosmtik-devel/node_modules` (`cd kosmtik-devel/node_modules && rm mapnik && ln -s /path/to/node-mapnik mapnik`)

Mapnik 3.0.19 has new `interior` algorithm, so you could see some changes in **all** area label placements, including admin areas, but it is just different, not better in general (some labels start being visible, some are hidden now):

Poland, z6
Mapnik 3.0.15
![3dajsilj](https://user-images.githubusercontent.com/5439713/37099097-db2f92be-221f-11e8-96c5-beda04f91630.png)
Mapnik 3.0.19
![6lrtqo9b](https://user-images.githubusercontent.com/5439713/37099115-e609ccc2-221f-11e8-811a-a9cc3f257eb3.png)

Poland, z7  (click to see the full size images)
Mapnik 3.0.15
![tf1fzhli](https://user-images.githubusercontent.com/5439713/37099104-dfb97444-221f-11e8-838e-f7d0219093ad.png)

Mapnik 3.0.19
![thu3jbza](https://user-images.githubusercontent.com/5439713/37099130-eb0463fe-221f-11e8-801b-dd1690f845c5.png)

The real change will be when we make a v5.0.0 code branch (since it means "[upgrading software dependecies](https://github.com/gravitystorm/openstreetmap-carto#versioning)") and test the `grid` algorithm, which is finally also available in Mapnik 3.0.19.

**Comment by kocio-pl** [comment] 2018-08-09 13:25
Looks like 3.0.20 (for Ubuntu Bionic 18.04 LTS) is finally deployed on OSMF servers, since Lake Victoria has label in the center now:

![Victoria label correct on OSMF](https://user-images.githubusercontent.com/5439713/43896895-a9e66a5e-9bda-11e8-8668-2340c3168696.png)

also all the other label placing problems I was aware of are gone. 

Now that we have proper Mapnik version on OSMF servers, we can try using `grid` algorithm for some area labels, especially admin level 4, and fix this issue.

**Comment by emmexx** [comment] 2018-08-09 14:14
In Italy I see still problems in admin level priority labels.
z=5 is ok, I see the main cities (by population o some other criteria, I don't know).
z=6 is not ok, some of the bigger cities disappear behind minor cities or region labels (Milan, Torino, Naples). Similar problem in Spain, Madrid is hidden by the España Label.
z=7 is not ok, Milan and Naples are ok but Torino and Bologna are still missing.
z=8 Bologna still missing

**Comment by kocio-pl** [comment] 2018-08-09 14:20
Change of internal algorithm does not solve such problems, but it may accidentally (just like any change, at the same time it can make some other things worse). It was introduced only to fix the problems like #1465. 

New algorithm is now ready to be tested instead and this should really help by moving labels to a free space.

**Comment by kocio-pl** [comment] 2018-08-09 15:31
@nebulon42 said that `grid` does not need changes in CartoCSS - https://github.com/gravitystorm/openstreetmap-carto/issues/2962#issuecomment-348288764 - but it looks like CartoCSS 0.18.2 (and 1.0.1 too) does not like it and produce 0-length `project.xml`:

```
Error: placenames.mss:56:4 Invalid value for text-placement, the type keyword (options: point, line, vertex, interior) is expected. grid (of type keyword) was given.
    at Object.env.error (/media/hdd/home/kocio/devel/kosmtik/node_modules/carto/lib/carto/parser.js:249:55)
    at Rule.tree.Rule.toXML (/media/hdd/home/kocio/devel/kosmtik/node_modules/carto/lib/carto/tree/rule.js:86:28)
    at Definition.tree.Definition.symbolizersToXML (/media/hdd/home/kocio/devel/kosmtik/node_modules/carto/lib/carto/tree/definition.js:145:39)
    at Definition.tree.Definition.toXML (/media/hdd/home/kocio/devel/kosmtik/node_modules/carto/lib/carto/tree/definition.js:218:33)
    at /media/hdd/home/kocio/devel/kosmtik/node_modules/carto/lib/carto/tree/style.js:40:27
    at Array.map (<anonymous>)
    at Object.tree.StyleXML (/media/hdd/home/kocio/devel/kosmtik/node_modules/carto/lib/carto/tree/style.js:39:29)
    at Renderer.render (/media/hdd/home/kocio/devel/kosmtik/node_modules/carto/lib/carto/renderer.js:180:43)
    at compile (/media/hdd/home/kocio/devel/kosmtik/node_modules/carto/bin/carto:100:31)
    at MML.load (/media/hdd/home/kocio/devel/kosmtik/node_modules/carto/lib/carto/mml.js:68:20)
```

**Comment by kocio-pl** [comment] 2018-08-17 11:05
OK, it works now, an early test of this concept and new toolchain is here: https://github.com/gravitystorm/openstreetmap-carto/issues/2962#issuecomment-413758796.

**Comment by jeisenbe** [comment] 2019-09-10 01:50
So this currently needs to v5.0 since it requires Mapnik/CartoCSS update, right?

**Comment by imagico** [comment] 2022-11-15 20:40
Closing in favor of #3034.

**Closed by imagico** 2022-11-15 20:40 UTC
Labels: placenames
