### ISSUE TITLE
Rendering support for natural=valley, natural=ridge for the name=* key

### ISSUE THREAD

**Issue by aaronstar** [gravitystorm/openstreetmap-carto#2774] opened 2017-08-24 06:00 UTC
Hi,
I would like to see rendering support for natural=valley and natural=ridge (only for the name=* key).
It would be useful to label the names of these features. (A text label)
Other lesser used natural=* tags in my opinion probably are not yet at the stage where they should be rendered in any capacity, however as natural=valley and natural=ridge form the basis of some pretty significant topographical features it may be useful to render their name.

Currently, the only similar kind of features are natural=water and or waterway=river, which there may not always be a river, and the river or water-body may have a different alignment to the valley. The valley name may also extend only for a certain portion of the river section if this was the case. Similarly, natual=cliff or natural=peak is a currently rendered similar tag for natural=ridge, but a ridge may not always have a cliff, a cliff may have a different name, and it may not be a peak either.

A potential issue is where users mistakenly tag natural=valley or natural=ridge with other features like waterway=river. Hopefully this should not happen very frequently, as the name tags would overlap.

Let me know your thoughts,

Regards,
Aaron

**Comment by Ircama** [comment] 2017-09-06 06:27
I also wish to see the rendering of [valleys](https://taginfo.openstreetmap.org/tags/natural=valley) and other major natural features.

Some aspects have already been discussed in this repository, like at [Rendering of natural=ridge](https://github.com/gravitystorm/openstreetmap-carto/issues/1148) and at [Rendering of valleys, ridges and other mountain elements](https://github.com/gravitystorm/openstreetmap-carto/pull/2138), with a reviewed and unmerged PR.

In summary, even if JOSM already incudes a preset for valleys based on the current definition in the [wiki](http://wiki.openstreetmap.org/wiki/Tag:natural%3Dvalley) and this feature is increasingly used as *way* (check also with http://taghistory.raifer.tech), there is an open discussion at the [wiki talk tab for natural=valley](http://wiki.openstreetmap.org/wiki/Talk:Tag:natural%3Dvalley) on the most appropriate data model to be adopted, which still needs some time to be resumed and addressed.

Meanwhile, [OpenTopoMap](https://opentopomap.org/#map=14/45.89986/10.00125) already renders names of valleys, riges, aretes, symbols of peaks with cross.

**Comment by Tomasz-W** [comment] 2018-07-15 10:41
@kocio-pl Please close this ticket as a duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/788 meta ticket. Move further discussion there.

**Closed** 2018-07-15 11:18 UTC
Labels: amenity-points, text

**Comment by jeisenbe** [comment] 2018-10-05 00:56
@Ircama, would you be willing to do a new PR for just natural=arete and natural=ridge? I believe there was wide agreement that the name should be shown for these features. In particular, everyone agreed that natural=arete should be rendered with a linear symbol and name, when tagged on a way. There was some disagreement about if there should be a rendering for unnamed ridges tagged on ways, but everyone agreed to rendering named ridges.

**Comment by Ircama** [comment] 2018-10-05 06:46
@jeisenbe, thanks for the recap, these features have been pretty largely discussed. Anyway I'm afraid I cannot take care of them within a short time; it is something I would have liked to do, but unfortunately at the moment my free time is too limited.
The main code is already in https://github.com/gravitystorm/openstreetmap-carto/pull/2138 and I think that what would still be needed is to agree on the most appropriate symbol for arete and ridge. Examples are already in that PR, but some additional research should be done.
[OpenTopoMap](https://github.com/der-stefan/OpenTopoMap/blob/master/mapnik/styles-otm/text-natural-line.xml) renders labels of ridges [without a symbol](https://opentopomap.org/#map=15/45.91724/9.99550).
[Osmand](https://github.com/osmandapp/OsmAnd-resources/pull/470) renders them with a smooth line.
