### ISSUE TITLE
Wrong rendering of hedge and wall areas

### ISSUE THREAD

**Issue by dafadllyn** [gravitystorm/openstreetmap-carto#4374] opened 2021-04-15 20:06 UTC
Please fill walls and hedges that are mapped as an area (i.e. with area=yes). They are currently displayed with a line around the area, which not only looks unpleasent, but also gives the wrong impression that the wall or hedge surrounds the area.

Examples:

* barrier=wall + area=yes: https://www.openstreetmap.org/way/112257290
* barrier=hedge + area=yes: https://www.openstreetmap.org/way/922159692

Thanks in advance for fixing this!

**Comment by pnorman** [comment] 2021-04-15 21:03
For walls this is a duplicate of issue #3453, which you might not have seen because it was closed.

We intentionally chose not to do this. See the issue above, and also see pull requests #3834 and #3844 about barrier=hedge with area=yes, and issue #4111 for hedges.

**Closed by pnorman** 2021-04-15 21:03 UTC
Labels: declined, duplicate
