### ISSUE TITLE
Don't render parking lots with forest pattern

### ISSUE THREAD

**Issue by ppete2** [gravitystorm/openstreetmap-carto#4206] opened 2020-09-23 12:18 UTC
I think it would be a good idea not to render parking lot areas `amenity=parking` within surrounding forest areas `landuse=forest` with the typical forest pattern onto it.
A parking lot area (like highway - ways) is usually never covered with (dense) trees like the surrounding forest. Maybe with some single trees between the parking lanes - but these single trees are not part of a forest.  

Please render parking areas above the forest area. Right now we would have to cut out each parking lot of the forest's Multipolygon, which in my opinion is unnecessary and not logical.

An example is the following parking lot:
https://www.openstreetmap.org/#map=19/47.93165/14.12401

**Comment by imagico** [comment] 2020-09-23 12:44
Duplicate of #1754, #1796, #1821.

This is intentional.  We render landuse=forest as meaning _here trees grow_ - just like natural=wood.  If a polygon tagged amenity=parking overlaps landuse=forest that is intentionally rendered with tree symbols indicating that this is a parking within the forest and the parking does not interrupt the tree cover.  See also https://github.com/gravitystorm/openstreetmap-carto/issues/1754#issuecomment-132121551.

**Closed by imagico** 2020-09-23 12:44 UTC

**Comment by aceman444** [comment] 2020-10-01 06:20
There indeed exist parkings in dense forest (e.g. https://www.openstreetmap.org/way/146414430). Of course, you can freely drive a car in such a forest, but the tree tops create a continuous canopy. It should be OK to render that with the tree pattern on top of the parking lot.
If there are no trees in the parking lot, it should be cut out of the forest using an inner member of a multipolygon.
