### ISSUE TITLE
waterway=ditch in a forest, colored over the forest

### ISSUE THREAD

**Issue by AllroadsNL** [gravitystorm/openstreetmap-carto#2629] opened 2017-05-10 07:02 UTC
In a forest, when drawn in the ditches.
On level 13 you already see the ditches in the forest.
This give a blue look, not seeing the forest anymore.

Example:
Here is a mountain bike route, through several ditches.
The reason to draw in the ditches.

Ditches are 50 cm deep. 1- 1,30 wide, most of the time dry and flows in to the 70-100 deep ditch.

For me showing at level 17 would be fine.
Two plots where drawn in yet, but the whole forest have ditches.

https://www.openstreetmap.org/#map=13/52.6587/5.9629

level 13
![ditch 13](https://cloud.githubusercontent.com/assets/8817345/25886365/9697cb62-355d-11e7-9a85-a1e94e2acb8f.PNG)

level 14
![ditch 14](https://cloud.githubusercontent.com/assets/8817345/25886376/9eec5fe4-355d-11e7-9add-e2a005adb443.PNG)

level 15
![ditch 15](https://cloud.githubusercontent.com/assets/8817345/25886395/ac257114-355d-11e7-82ff-762d4d1ba834.PNG)
 
level 16
![ditch 16](https://cloud.githubusercontent.com/assets/8817345/25886408/b5aca11c-355d-11e7-8c51-f2d59e1476e9.PNG)

level 17
![ditch 17](https://cloud.githubusercontent.com/assets/8817345/25886418/be22a4d6-355d-11e7-9775-10f13e2140d7.PNG)

**Comment by imagico** [comment] 2017-05-10 09:03
So the issue is about `waterway=ditch` being rendered too early at z13 in your opinion?

This is more or less the same as #1101 suggests for `waterway=drain`.  The minor waterways at the lowest zoom level (z13) could be slightly reduced in width and casing strength probably though there were increased in width for a reason (#967).  Note we do not want to start ditches later than streams due to #2346.

If these are dry most of the time you should tag them `intermittent=yes` by the way - no matter if that looks good on the map or not at the moment.

**Comment by AllroadsNL** [comment] 2017-05-10 12:58
Yes, rendered too earlier on z13.
I would say, z16 z17

Forget, to search for a earlier issue.!

Intermittent=yes, I know,
Now intermittent, the right side of the example, compare.

z13
![int ditch 13](https://cloud.githubusercontent.com/assets/8817345/25899579/a9be8ebe-3590-11e7-88f6-a59666d2cc2a.PNG)

 z14
![int ditch 14](https://cloud.githubusercontent.com/assets/8817345/25899586/b0973f24-3590-11e7-81b2-f6e78bff8075.PNG)

z15
![int ditch 15](https://cloud.githubusercontent.com/assets/8817345/25899602/bcb73494-3590-11e7-90a8-5ee01eb2f187.PNG)

z16
![int ditch 16](https://cloud.githubusercontent.com/assets/8817345/25899610/c2fbab46-3590-11e7-929a-da55411d2d0f.PNG)

z17
![int ditch 17](https://cloud.githubusercontent.com/assets/8817345/25899618/cb25a4e8-3590-11e7-9646-56b390a052de.PNG)

**Comment by AllroadsNL** [comment] 2017-05-21 17:35
Not the solution, I think.
right side.
intermittent=yes
waterway=ditch
Zoomlevel 15
![int ditch 15 black](https://cloud.githubusercontent.com/assets/8817345/26286029/c7a17da0-3e5b-11e7-86e2-93a4425e7d2c.PNG)
Zoomlevel 17
![int ditch 17 black](https://cloud.githubusercontent.com/assets/8817345/26286070/3a973f52-3e5c-11e7-866f-3038a4a49ed1.PNG)

**Comment by nebulon42** [comment] 2017-05-21 17:47
Yes, this is a regression. See #2636.

**Comment by kocio-pl** [comment] 2017-07-31 02:29
With merging https://github.com/gravitystorm/openstreetmap-carto/pull/2654 (and resolving https://github.com/gravitystorm/openstreetmap-carto/issues/1781 of course) this problem is now even more visible:

z13
Before (took from the original report)
![ditch 13](https://cloud.githubusercontent.com/assets/8817345/25886365/9697cb62-355d-11e7-9a85-a1e94e2acb8f.PNG)
After
![yqp7tiqx](https://user-images.githubusercontent.com/5439713/28760586-8546330e-75a8-11e7-96f2-ae1802038f24.png)

**Comment by AllroadsNL** [comment] 2017-07-31 08:20
In the right field of waterways, the lower 7 waterways are waterway=drain and intermittent=yes.

**Comment by wmyrda** [comment] 2017-08-31 05:59
It is not that steams/ditches/drains are displayed to early. They simply have this unnecessary white outline around them which makes them appear twice as wide as they actually are which is especially visible in the forest http://www.openstreetmap.org/#map=14/50.1657/22.0304 Now that the water color have changed that white line surrounding them could be removed.

**Comment by kocio-pl** [comment] 2017-09-23 02:59
I'm afraid this could lead to a problem like #2098.

**Comment by kocio-pl** [comment] 2018-12-01 05:08
This case seems to be OK, with ditched from z14 and intermittent ditches from z15, effectively resolved by #3467, so I will close it now. If there will be some other cases which are still troublesome, we can reopen ticket and discuss it further.

**Closed by kocio-pl** 2018-12-01 05:08 UTC
Labels: enhancement, water-features
