### ISSUE TITLE
Coinciding scrub and campsite doesn't seem to work

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4624] opened 2022-07-26 19:30 UTC
What I wanted was a campsite coinciding with scrub.

I have seen that working -in variations- by which the scrub gets a lighter green colour, and retains its pattern.

But in reality I did not get it working.
- My preferred method, with 2 coinciding multipolygons sharing a line boundary, only showed the scrub.
- Experimenting with a new triangular campsite in a corner, with 2 of its sides coinciding with the multipolygon boundaries, did work.
- I turned the original campsite into an area by a lot of work. But to my surprise that still did not work.
- Experimenting with a small triangular campsite, overlaying the multipolygons within them, did work.

I don't get the problem, and how to resolve it.
- Is it boundaries coinciding too much that causes it?
- How to get the desired result? Preferably close to my preferred method.
- Is it a bug?

**Comment by imagico** [comment] 2022-07-29 11:28
I don't really understand this issue.  It seems to be concerned with what the right tagging is for a certain real world feature and as such would not belong on this issue tracker.  Suitable places to discuss such questions would be your local community channels or the tagging mailing list.

If this impression is wrong and this issue is concerned with a certain mapping being incorrectly rendered in this style please link to a specific example on the map and explain in what way you think the rendering is not right.

**Comment by BertMule** [comment] 2022-07-29 14:16
In other words: I want an area to be BOTH displayed as scrub AND marked (lighter) as a campsite.
Structurally modelled as above.

I HAVE seen that partially working, but it doesn't for the area as a whole..
With the questions above.

**Comment by imagico** [comment] 2022-07-29 16:10
Closing this as this is apparently not related to how a certain way things are mapped in OSM is rendered but seems related to the question how certain things should be mapped.

For clarification on how OpenStreetMap works in general:  Mappers map the geography of the world in the OSM database using tagging and mapping conventions developed through deliberation among themselves.  This process is completely outside the scope of this issue tracker.

We look at how mappers map things by studying the OSM database and decide on how we render things based on these observations.  Any discussion we have regarding how to render things and if we should change how we render things necessarily starts with a certain way things are mapped (in terms of tags and geometry).

If you can point to a certain way you map coinciding scrub and campsite (preferably in the form of a link to a place where this is done in OSM) and explain why you think the way we render that is wrong then we can reopen this issue.  If that is not the case and you would like advice how to best map coinciding scrub and campsite then as said this would be a question for a different venue.

**Closed by imagico** 2022-07-29 16:10 UTC

**Comment by BertMule** [comment] 2022-07-29 16:33
Phew, that's pretty harsh, and misunderstood.

I would think the question is clear. 
It IS about how rendering turns out, and whether it is a bug (as it seems).

Currently it is about this [region](https://www.openstreetmap.org/#map=18/53.39898/5.25848). 
With currently scrub as a polygon, and a campsite a bit tucked away.
Most of it following the green reserve line.

**Comment by imagico** [comment] 2022-07-29 16:54
Ok, thanks for the link, that makes the matter much clearer.  This seems to be about the (relatively common) misunderstanding about the drawing order of the polygon fills.

The two features in question:

https://www.openstreetmap.org/relation/14389245
https://www.openstreetmap.org/way/1081570863

are drawn in the order of their size with the smaller one on top.  We do this because we want for example micromapping of small scrub patches within a campsite to be visible while we also want a small campsite within a large scrub area to be visible.

The campsite is in addition shown with a symbol at z16/z17.

So there is no bug here, it renders as intended based on how things are mapped.  If you think it should be rendered differently please explain how you think it should be shown.

**Comment by BertMule** [comment] 2022-07-30 15:52
I started with the scrub and campsite SHARING the same outline. 
I would expect the ADDED information of the campsite's different colour to be visible in addition to the pattern of the scrub. Effectively taking priority.
It did not work either.
That might imply a small suggested change to let it have priority if it is **<=** than the scrub, instead of **<**.

As a workaround, it seems I should make the campsite 'smaller' than the scrub.
But how much?
Before I start experimenting (there is no preview, as far as I know).

I assume that would also work when making the campsite a polygon again?

**Comment by imagico** [comment] 2022-07-30 17:59
> That might imply a small suggested change to let it have priority if it is <= than the scrub, instead of <

Secondary to way_area we order by `feature` in the landcover layer (since  #3441) - and `natural_scrub` comes after `leisure_campsite`.  I would not be in favor of trying to micromanage the drawing order of roughly a hundred different landcover tags for the special case of identical geometries.
