### ISSUE TITLE
Island not rendered at z10

### ISSUE THREAD

**Issue by andrzej-r** [gravitystorm/openstreetmap-carto#3743] opened 2019-04-11 20:11 UTC
Island is not rendered at z10 (lower and higher zoom levels work fine), as in the following [screenshot](https://www.openstreetmap.org/#map=10/59.0420/-2.9423):

![Island_z10](https://user-images.githubusercontent.com/587630/55989835-282aea00-5c9e-11e9-8dc6-7c682ce50426.png)

**Comment by imagico** [comment] 2019-04-11 20:41
Cant't reproduce the problem.  If it is exclusively on z10 it is very unlikely to be a style issue.

If you continue to see this make sure to check

https://a.tile.openstreetmap.org/10/503/303.png
https://a.tile.openstreetmap.org/10/503/303.png/status

**Comment by matkoniecz** [comment] 2019-04-11 22:44
Seems to be fixed now. I suspect that somebody accidentally deleted the island and that it was reverted.

**Comment by matkoniecz** [comment] 2019-04-11 22:44
Please comment if issue continues to exist.

**Closed by matkoniecz** 2019-04-11 22:44 UTC
