### ISSUE TITLE
Current public_transport stop tags are not rendered

### ISSUE THREAD

**Issue by SelfishSeahorse** [gravitystorm/openstreetmap-carto#2724] opened 2017-08-02 20:26 UTC
Neither an icon nor the name of a stop appears on the map if it is tagged with the current public_transport keys `public_transport=stop_position` and `public_transport=platform` as described [here](https://wiki.openstreetmap.org/wiki/Key:public_transport).

**Comment by pnorman** [comment] 2017-08-03 20:25
Duplicate of #311

**Closed by pnorman** 2017-08-03 20:25 UTC
