### ISSUE TITLE
man_made=mast renders but not man_made=tower + tower:type=communication

### ISSUE THREAD

**Issue by Skippern** [gravitystorm/openstreetmap-carto#2299] opened 2016-08-21 13:08 UTC
As JOSM presets doesn't include `man_made=mast`, but have an external preset giving preferences `man_made=tower`+`tower:type=communication`, I think both tagging options should be rendered on the standard layer.

**Comment by kocio-pl** [comment] 2016-11-15 21:42
Closing as a duplicate of https://github.com/gravitystorm/openstreetmap-carto/issues/339.

**Closed by kocio-pl** 2016-11-15 21:42 UTC
