### ISSUE TITLE
render service roads in zoom 13

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#4252] opened 2020-11-20 10:24 UTC
### Expected behavior
See a consistent network in z13 in the country side (tracks and service ways)

### Actual behavior
tracks are shown at zoom13, services (without service=* qualifiers) at zoom 14, leading to gaps. 
IMHO if these aren't appearing at the same zoomlevel, it should rather be the services being longer visible. 

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=14/42.0194/12.2999
![Screenshot 2020-11-20 at 11 22 47](https://user-images.githubusercontent.com/581288/99789508-fc7f0f80-2b22-11eb-8af2-add092305285.png)
![Screenshot 2020-11-20 at 11 22 55](https://user-images.githubusercontent.com/581288/99789514-fee16980-2b22-11eb-9d45-309a75f86917.png)

**Comment by imagico** [comment] 2020-11-20 15:12
Duplicate of #3798.

**Closed** 2020-11-20 19:57 UTC
Labels: duplicate
