### ISSUE TITLE
certain tags create areas from route relations

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#2808] opened 2017-09-04 14:36 UTC
We had today a case in Italy where a route relation with the tag highway=path (and circular way members) lead to an highway area polygon rendering. Not sure if this is the right repo or if this is an osm2pgsql bug, but a route relation should never create polygons in the rendering db, regardless of tags.

**Comment by SomeoneElseOSM** [comment] 2017-09-04 15:01
Linking to https://github.com/openstreetmap/osm2pgsql/issues/304 , which might be the osm2pgsql issue you're thinking of.  I'm not  convinced that that's still an issue though - osm2pgsql versions have moved on considerably since 2015 when that issue was created.  I haven't seen a recent example in OSM data.

**Comment by dieterdreist** [comment] 2017-09-04 15:08
I'm not sure if this is the same bug, because it is about closed ways with
tags, while here there was a route relation which had additionally a
highway=path tag and several members with different highway tags. For
reference: https://www.openstreetmap.org/relation/3328050/history
(corrected in version 8).

**Comment by math1985** [comment] 2017-09-11 08:48
I don't think route relations should do anything with polygon handling. @pnorman is that correct?

**Comment by pnorman** [comment] 2017-09-15 08:23
> We had today a case in Italy where a route relation with the tag highway=path (and circular way members) lead to an highway area polygon rendering. Not sure if this is the right repo or if this is an osm2pgsql bug, but a route relation should never create polygons in the rendering db, regardless of tags.

Can you provide a minimized XML testcase?

> I don't think route relations should do anything with polygon handling. @pnorman is that correct?

They're all part of `filter_tags_relation_member`, I can look into it with a testcase. I'm not confident the problem is what's described here.

**Comment by dieterdreist** [comment] 2017-10-02 10:31
2017-09-15 10:23 GMT+02:00 Paul Norman <notifications@github.com>:

> We had today a case in Italy where a route relation with the tag
> highway=path (and circular way members) lead to an highway area polygon
> rendering. Not sure if this is the right repo or if this is an osm2pgsql
> bug, but a route relation should never create polygons in the rendering db,
> regardless of tags.
>
> Can you provide a minimized XML testcase?
>

I'm not sure I understood you right. I have produced a reduced testcase
which I believe might behave similarly than the relation I had linked, but
I don't have the means to test if it creates the same problem.

<?xml version='1.0' encoding='UTF-8'?>
<osm version='0.6' generator='Martin'>
  <node id='1234567890' version='1' lat='-22.90006927021'
lon='-43.12630757442' />
  <node id='1234567891' version='1' lat='-22.9011114933'
lon='-43.12594252431' />
  <node id='1234567895' version='1' lat='-22.9010892008'
lon='-43.12723094315' />
  <way id='1234567892' version='1'>
    <nd ref='1234567890' />
    <nd ref='1234567891' />
    <tag k='highway' v='footway' />
  </way>
  <way id='1234567893' version='1'>
    <nd ref='1234567891' />
    <nd ref='1234567895' />
    <tag k='highway' v='service' />
  </way>
  <way id='1234567894' version='1'>
    <nd ref='1234567895' />
    <nd ref='1234567890' />
    <tag k='highway' v='cycleway' />
  </way>
  <relation id='1234567896' version='1'>
    <member type='way' ref='1234567892' role='' />
    <member type='way' ref='1234567893' role='' />
    <member type='way' ref='1234567894' role='' />
    <tag k='bicycle' v='yes' />
    <tag k='highway' v='path' />
    <tag k='name' v='testcase route relation with highway tag' />
    <tag k='network' v='lwn' />
    <tag k='note' v='this is a testcase, not actual OSM data' />
    <tag k='operator' v='Mad Max' />
    <tag k='ref' v='23' />
    <tag k='roundtrip' v='yes' />
    <tag k='route' v='foot' />
    <tag k='type' v='route' />
  </relation>
</osm>

**Comment by majkaz** [comment] 2019-01-09 15:16
The same case was [here](https://www.openstreetmap.org/relation/7789722/history). It was corrected, but the highway=track did "overwrite" the pond.

**Comment by jeisenbe** [comment] 2020-03-16 11:24
According to the history, these were the tags at the time of the bug [above](https://github.com/gravitystorm/openstreetmap-carto/issues/2808#issuecomment-452732217):

complete	no
destinations	Blažejský rybník
highway	track
kct:green	learning
name	NS Svatého Blažeje
network	lwn
operator	Cesta z města, o.s.
osmc:symbol	green:white:green_backslash
route	hiking
source	gps;uhul:ortofoto;cuzk:km;strava
type	route

It had 3 members which formed a complete loop: 
 Way 251039054
 Way 545199868
 Way 545199900

The rendering changed in the 2nd version of the relation, which just dropped "highway=track"

There's nothing in this style which would cause a type=route relation to be imported as a polygon, so perhaps it was a bug like https://github.com/openstreetmap/osm2pgsql/issues/304 - but that was over a year ago, so perhaps the servers were using an older version of osm2pgsql at the time? 

I'm going to close this, since it does not seem to be a bug in this stylesheet.

**Comment by jeisenbe** [comment] 2020-03-16 11:25
Closed

**Closed** 2020-03-16 11:25 UTC
Labels: roads
