### ISSUE TITLE
Render icon for packstation (parcel lockers)

### ISSUE THREAD

**Issue by ttomasz** [gravitystorm/openstreetmap-carto#4372] opened 2021-04-14 18:17 UTC
### Proposal

I think carto should render icons for packstations (parcel lockers).

Tags:
- amenity=vending_machine

and one of: 
- vending=parcel_pickup;parcel_mail_in
- vending=parcel_pickup
- vending=parcel_mail_in

### History

This was previously discussed in: https://github.com/gravitystorm/openstreetmap-carto/issues/3558 and https://github.com/gravitystorm/openstreetmap-carto/issues/1561 . It was also mentioned in https://github.com/gravitystorm/openstreetmap-carto/issues/3617 .

Seems that development was halted due to proposal that would change tagging of these objects: https://wiki.openstreetmap.org/wiki/Proposed_features/Parcel_lockers_and_parcel_postbox
As of 2021-04-14 this proposal looks dead so I don't believe any changes to tagging will take place anytime soon.

### Why

Rendering these features would be highly valuable. There are about 11 000 - 14 000 of these points in Poland. They are very popular alternative to post offices which means it's something that people would like to see on the map so they know where these points are located. Right now we have only a few thousands mapped but efforts to map these features could increase significantly if people saw their work visible in the map.

### Icon

I think it would be best to use the same icon that is used by iD editor.

Example:
![image](https://user-images.githubusercontent.com/31594210/114759148-17665080-9d5e-11eb-8a0a-98bfb83672e2.png)

I was not able to find it in their repo so maybe someone smarter than me can find the file and establish if we could use the icon (legally).

**Comment by imagico** [comment] 2021-04-14 18:33
Duplicate of #3558 - reopened that instead.  We always prefer going with existing issues rather than opening new ones to retain connection to past discussions.

**Closed by imagico** 2021-04-14 18:33 UTC
