### ISSUE TITLE
Error generating MBTiles file

### ISSUE THREAD

**Issue by RandyHBH** [gravitystorm/openstreetmap-carto#2838] opened 2017-09-15 20:14 UTC
Hi, I dont know if this is the right place to ask this but i am Running OpenStreetMap Carto with Docker and when trying to export mbtiles give me this error, if anyone could help me with this.

```
/usr/lib/node_modules/kosmtik/src/Config.js:73
        if (err.code !== 'EEXIST') throw err;
                                   ^
Error: EACCES: permission denied, mkdir '/.config'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:924:18)
    at Config.ensureDefaultUserConfigPath (/usr/lib/node_modules/kosmtik/src/Config.js:71:12)
    at new Config (/usr/lib/node_modules/kosmtik/src/Config.js:24:32)
    at Object.<anonymous> (/usr/lib/node_modules/kosmtik/index.js:8:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by matkoniecz** [comment] 2017-10-16 13:47
It looks like a https://github.com/kosmtik/kosmtik bug (or at least poor error reporting) have you tried reporting this problem there (after checking whatever issue is already reported)?

**Comment by kocio-pl** [comment] 2017-10-16 20:57
It might be also permissions problem inside the container.

**Comment by matkoniecz** [comment] 2017-11-02 17:58
How one may export MBTiles from docker that we provide?

**Comment by kocio-pl** [comment] 2017-11-02 18:02
As this is osm-carto related image, not a general Kosmtik one, this plugin could be just removed IMO.

However it's also possible to mount a Docker volume and run the command inside running container if we want too.

**Comment by matkoniecz** [comment] 2018-01-05 09:47
How one may export MBTiles from docker container that we provide?

Original report is not mentioning how it can be reproduced.

**Comment by matkoniecz** [comment] 2018-01-14 13:55
Closing as I am unable to reproduce.

**Closed by matkoniecz** 2018-01-14 13:55 UTC
Labels: docker
