### ISSUE TITLE
highway=service + living_street=yes paint over as highway=living_street

### ISSUE THREAD

**Issue by zlant** [gravitystorm/openstreetmap-carto#3514] opened 2018-11-15 20:08 UTC
### Expected behavior
`highway=service` + `living_street=yes` paint over as `highway=living_street`

Added: change only the color, but not the width

### Actual behavior
`highway=service` + `living_street=yes` paint over as `highway=residential`

### Links and screenshots illustrating the problem
https://taginfo.openstreetmap.org/tags/living_street=yes#combinations

**Comment by kocio-pl** [comment] 2018-11-15 21:43
Thanks for reporting. Could you show the location (link) where the problem is visible and possibly post an image showing it?

**Comment by jeisenbe** [comment] 2018-11-15 22:58
I would think that highway=living_street or highway=service alone would be
the correct tagging?

https://wiki.openstreetmap.org/wiki/Tag:highway%3Dservice says
highway=service is for streets or roads that access one property or
building, and https://wiki.openstreetmap.org/wiki/Key:service does no
mention service=living_street

**Comment by kocio-pl** [comment] 2018-11-15 23:07
I have never heard of that. Looks like it was proposed long time ago and this proposition is described here:

https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:living_street%3Dyes

However it is being really used since then:

https://wiki.openstreetmap.org/wiki/Key:living_street

![taghistory 27](https://user-images.githubusercontent.com/5439713/48587428-63193380-e933-11e8-838d-64270ced9329.png)

**Comment by Adamant36** [comment] 2018-11-16 08:01
![taghistory 3](https://user-images.githubusercontent.com/30259065/48605842-c2c30f00-e932-11e8-9014-2e49a78a7980.png)

**Comment by Adamant36** [comment] 2018-11-16 08:02
![taghistory 4](https://user-images.githubusercontent.com/30259065/48605924-f43bda80-e932-11e8-9d61-b9242a9405f2.png)

**Comment by HolgerJeromin** [comment] 2018-11-16 11:50
I think this should be discussed in Tagging ML.
Indeed this small driveway would look nicer in gray:
https://www.openstreetmap.org/way/464614013

I would "allow" it only for lower class (than living street) highways like service.

**Comment by dieterdreist** [comment] 2018-11-16 12:15
Am Fr., 16. Nov. 2018 um 12:50 Uhr schrieb Holger Jeromin <
notifications@github.com>:

> I think this should be discussed in Tagging ML.
> Indeed this small driveway would look nicer in gray:
> https://www.openstreetmap.org/way/464614013
>
> I would "allow" it only for lower class (than living street) highways like
> service.
>


from a German point of view, a living street is a public road, while a
driveway is not, so it doesn't seem to make sense to put a living street
property on a private driveway. I agree that the rendering of living
streets is not the most beautiful possible solution, but extending the
living street on private ways doesn't  seem correct either.

**Comment by polarbearing** [comment] 2018-11-16 14:45
> Indeed this small driveway would look nicer in gray

Why would we determine the colour of a driveway depending on the adjacent road?

**Comment by zlant** [comment] 2018-11-16 16:22
I will add that I propose to change only the color, but not the width.

Place example: http://overpass-turbo.eu/s/DK9

**Comment by polarbearing** [comment] 2018-11-16 18:18
Could you upload a picture how the roads look in reality and how they are signposted?

**Comment by mboeringa** [comment] 2018-11-16 18:55
> I agree that the rendering of living streets is not the most beautiful possible solution, but extending the living street on private ways doesn't seem correct either.

I don't understand the point, there is **highway=service, service=driveway** for that case, with clearly described Wiki pages:
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dservice
https://wiki.openstreetmap.org/wiki/Tag:service%3Ddriveway

> from a German point of view, a living street is a public road

The same in the Netherlands, and I would never tag a private driveway to a property as highway=living_street, instead use the above tagging.

I do not like the concept of **living_street=yes** as described by that old Wiki page. I think this is a poor tagging scheme. If we follow the instructions on that page, even a **highway=motorway** could get the additional **living_street=yes**, which is ridiculous (_"Extend the concept of highway=living_street to any highway=* tag."_: https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:living_street%3Dyes)

I have the feeling this page was introduced before **landuse=residential** came into being, so as to have some way to describe a road that runs through a residential area. The proposal is from 2009 after all.

**Comment by zlant** [comment] 2018-11-16 19:11
@polarbearing 
[![image](https://user-images.githubusercontent.com/8606466/48641130-d2e9f580-e9e9-11e8-8874-d76ccb6063e7.png)](https://www.google.ru/maps/@55.7506865,49.2460115,3a,75y,4.81h,83.52t/data=!3m6!1e1!3m4!1s7oG7Wy5Ru6N9E4QJ-J0sHQ!2e0!7i13312!8i6656)
[![image](https://user-images.githubusercontent.com/8606466/48641925-6c1a0b80-e9ec-11e8-9d26-33a46817ef72.png)](https://www.google.ru/maps/@55.7670468,49.2251909,3a,51.3y,207.32h,92.59t/data=!3m6!1e1!3m4!1s1YuuMaG6p6lV-QlcQRLh_w!2e0!7i13312!8i6656)

**Comment by polarbearing** [comment] 2018-11-16 19:23
There is unambiguous signposting that cars and peds share the road, so it's ```highway=living_street```. 
<img width="82" alt="lstr" src="https://user-images.githubusercontent.com/8266355/48642524-5fda8200-e9dd-11e8-968e-e1c3a8832395.png">

**Comment by HolgerJeromin** [comment] 2018-11-16 20:44
> from a German point of view, a living street is a public road

Living Street in Germany defines an area (signed only at the beginning), not street itself. So every (non foot/cycle only) road has the same legal restrictions.

**Comment by polarbearing** [comment] 2018-11-16 20:56
I think he meant, independent from the shape, that the living street is a public entity, while the driveway is a private one, to which the Ruled of the Road do not apply. Therefore tagging the private driveway as living_street=yes is pointless.

**Comment by geozeisig** [comment] 2018-11-17 06:57
Timmendorfer Strand is a good example that a whole village can be a living street area. At the entrance there is only one sign.
![timmendorfer strand](https://user-images.githubusercontent.com/17127509/48658158-2f2a3500-ea3d-11e8-9503-6d0ce68ba434.jpg)
The service roads that are now white should also be gray. This is only possible if you additionally add the tag `living_street=yes`. The same traffic rules apply to service roads, which also apply to parking rules.

**Comment by jeisenbe** [comment] 2018-11-17 07:35
What makes those streets in Timmendorfer Strand service roads rather than
highway=residential or =living_street?

Are they maintained by the owners of nearby houses / apartments rather than
by the local government?

Are they alleys, or driveways, or something different?

I think of service roads as being private roads, maintained by individuals
or companies, rather than public highways. But this may be an American idea.

**Comment by dieterdreist** [comment] 2018-11-17 08:46
sent from a phone

> On 16. Nov 2018, at 21:44, Holger Jeromin <notifications@github.com> wrote:
> 
> from a German point of view, a living street is a public road
> 
> Living Street in Germany defines an area (signed only at the beginning), not street itself. So every (non foot/cycle only) road has the same legal restrictions.
> 


exactly: road, a private driveway isn’t a road. All the roads within that zone are highway=living_street in osm.

**Comment by polarbearing** [comment] 2018-11-19 12:46
I propose to close this issue as rejected, i.e. not rendering ```living_street=yes```

**Comment by jragusa** [comment] 2018-11-19 13:16
The proposal is marked as _abandonned_ on the [wiki page](https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:living_street%3Dyes) so agree to close this issue

**Comment by Adamant36** [comment] 2018-11-19 13:20
It doesn't seem like the numbers on it are increasing either. Plus, highway=living_street is a more proper tag. We shouldn't encourage bad/abandoned tagging.

**Comment by matkoniecz** [comment] 2018-11-19 13:34
From wiki edits it seems that `living_street=yes` is at best disputed by some. Is anybody planning to start discussion about this tag on OSM wiki or tagging mailing list?

**Comment by Adamant36** [comment] 2018-11-19 13:42
Going by the wiki it seems its an add-on to other roads to designate that they are mixed use of whatever+living_street. So, IMO there wouldn't be a practical way to render it anyway. Since rendering something like a liner residential road a completely different way because it is tagged with living_street=yes just doesn't seem doable or worth it. Especially considering the same idea got shot down for showing if a road is lit or not.

**Comment by polarbearing** [comment] 2018-11-19 19:48
It was discussed on talk-de and unanimously disagreed with. 
So far I have not seen a valid example where it would be needed. The only examples were private driveways, to which the road rules about living street don't apply, with the reason given that a unique colour would be nicer.
I'm in favour of the map being correct.

**Comment by matkoniecz** [comment] 2018-11-19 20:11
In that case I will close it for now. It may be reopened in case of evidence that this tagging is considered as a good one.

**Closed by matkoniecz** 2018-11-19 20:11 UTC
Labels: roads

**Comment by matkoniecz** [comment] 2018-11-19 20:12
And please do not discuss here whatever it is a good idea or not. Do it on OSM wiki/tagging mailing list and leave here at most a link.

**Comment by tjur0** [comment] 2023-07-19 07:23
Could this be reopened? I think that living_street=yes + highway=service has many valid use cases, one of which is parking aisles inside of living street areas:
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/52704747/1a695044-f12c-4c00-8a71-991a9213ba70)
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/52704747/c2483fbe-9ee4-4517-8f37-793bd5aed237)

**Comment by imagico** [comment] 2023-08-01 08:34
This continues to be a field without consensus on tagging among mappers.  Specifically here: There is no consensus that what you would like to tag `highway=service` + `living_street=yes` is not to be tagged `highway=living_street`. We do not want to influence consensus building by endorsing a specific, contested tagging scheme.  But please: No discussion of this here, do that in a different venue.

What we are considering is not rendering `highway=living_street` in a unique color any more - unifying it either with `highway=pedestrian` or  `highway=residential`.  See #3891 and #3961.  Given that a substantial number of mappers seems to consider _living street_ frequently to be a secondary attribute of roads rather than a primary highway class this might be a good idea.

We also have an open issue #214 on better differentiation of roads according to access restrictions secondary to the main road types, in other words: We definitely would like to provide better feedback on differentiation of roads according to access restrictions (based on well established tags with consensus support and clear meaning - where `living_street=yes` currently does not fit in though).
