### ISSUE TITLE
Highway under construction in tunnel does not render at all under pedestrian areas

### ISSUE THREAD

**Issue by jarikirma** [gravitystorm/openstreetmap-carto#3266] opened 2018-06-16 14:19 UTC
### Expected behavior

Duplicated separate issue from https://github.com/gravitystorm/openstreetmap-carto/issues/3265#issuecomment-397813893

highway=construction
construction=secondary
tunnel=building_passage (or plain yes)

should render (albeit not on top of everything) when it is running under a pedestrian area.

### Actual behavior

Seen on openstreetmap.org: such a highway is not rendered at all.

### Links and screenshots illustrating the problem

![image](https://user-images.githubusercontent.com/1022328/41499458-233b72ae-7189-11e8-9a1e-f9986594855d.png)

Seen at https://www.openstreetmap.org/#map=19/60.17524/24.80590

**Comment by jarikirma** [comment] 2018-06-16 18:34
Apparently this problem also applies to subways, even completed ones. This can be seen in the same screenshot above.

**Comment by polarbearing** [comment] 2018-06-16 22:29
Duplicate of #529

**Closed** 2018-06-17 00:38 UTC
Labels: duplicate
