### ISSUE TITLE
bridge multipolygon rendering below road

### ISSUE THREAD

**Issue by boothym** [gravitystorm/openstreetmap-carto#2509] opened 2016-12-13 18:41 UTC
Saw this note recently where the bridge is rendered below the road: http://www.openstreetmap.org/note/550736#map=18/51.52508/-0.03436&layers=N

Perhaps someone could shed some light on why it's not rendering as intended, and if it can be tagged in a better way?

**Comment by HolgerJeromin** [comment] 2016-12-13 19:26
Every group of features (buildings, landcover, streets) build separate layers. Apparently bridges are always below streets. This is in most cases desired to have the bridge as base of the street lines.

Here we have probably a data issue:
I just added covered=yes to all streets under the bridge which should results in a better rendering.

**Comment by dieterdreist** [comment] 2016-12-13 20:31
sent from a phone

> On 13 Dec 2016, at 20:26, Holger Jeromin <notifications@github.com> wrote:
> 
> Here we have probably a data issue:
> I just added covered=yes to all streets under the bridge which should results in a better rendering.


it should not be necessary to add covered=yes to the lower objects, as the order of all objects is already there (in the layer tags).


cheers, Martin

**Comment by jojo4u** [comment] 2016-12-13 20:37
>Here we have probably a data issue:
>I just added covered=yes to all streets under the bridge which should results in a better rendering.

Since the bridge has layer=1 the covered=yes should not be used. Do not use: _For objects in tunnels or passing under bridges where vertical ordering is established by layer=* in combination with a suitable tag such as bridge=* or tunnel=*._ ([wiki](http://wiki.openstreetmap.org/wiki/Key:covered)).

The real data issue: Usage of multipolygons in this situation is horrible. Construction of such simple areas via multipolygons (using only outer ways) is frowned upon (german "Multiploygonwahn" = multipolygon mania)

**Comment by jojo4u** [comment] 2016-12-13 20:41
I removed the unnecessary tags area=yes and bridge=yes.

**Comment by mboeringa** [comment] 2016-12-13 21:43
> Perhaps someone could shed some light on why it's not rendering as intended, and if it can be tagged in a better way?

**Man_made=bridge** features do not adhere to layered rendering like highways or railways. The **layer=x** tag is ignored in Carto for anything except highways and railway. It is the one big myth of OSM that it is otherwise...

My ArcGIS Renderer in development will have wider support for rendering other objects layered, but for the main style I develop, even there the vast majority of _thematic_ layers (there are 300 of them...) won't consider **layer=x**. This is all mainly because of technical reasons: each thematic layer that needs to be rendered according to the **layer=x** tag, significantly adds to the total pool of data layers to render (think about it: the layer tag has **11** valid values from -5 to +5), thus making the rendering completely unwieldy.

Don't confuse a **_thematic layer_** symbolizing e.g. all **landuse=forest** objects in OSM with data adhering to OSM's **layer=x** tag. The word **"layer"** has totally different meaning here.

My ArcGIS Renderer will, however, render **man_made=bridge** layered, and thus resolve this issue properly. See the images below for an example, including @jojo4u's "Multipolygonwahn" taken to the extreme on a monumental disused railway bridge in the Netherlands...

> Every group of features (buildings, landcover, streets) build separate layers. Apparently bridges are always below streets.

As @HolgerJeromin correctly states, the man_made=bridge are in one layer below all roads. Thematic layers are just stacked in what a style maintainer considers a sound cartographic solution / order (and that is of course to a large extent an arbitrary subjective choice). This is true for about any webmap out there, whether that one is OSM based like Carto, or others like Google, Bing or Here.

Carto:
![rotterdam_dehef_openstreetmap_carto](https://cloud.githubusercontent.com/assets/7635726/21159625/392c28c8-c182-11e6-8a14-060318cfc70a.jpg)

ArcGIS Renderer for OpenStreetMap:
![rotterdam_dehef_openstreetmap_arcgis_renderer_for_openstreetmap](https://cloud.githubusercontent.com/assets/7635726/21159641/40c575a8-c182-11e6-9c35-4eb1f35b0d2d.jpg)

**Comment by rKsanu2MMYvypWePtQWM** [comment] 2018-02-12 11:37
More than a year has passed. Will this be fixed?

**Comment by kocio-pl** [comment] 2018-02-12 11:45
I guess not, unless somebody come with the code for changing how osm-carto deals with layers, which might be quite serious job. It's just the current convention of showing bridges and roads, so I close it until then.

**Closed by kocio-pl** 2018-02-12 11:45 UTC
Labels: roads

**Comment by dieterdreist** [comment] 2018-02-12 11:55
2018-02-12 12:45 GMT+01:00 kocio-pl <notifications@github.com>:

> I guess not, unless somebody come with the code for changing how osm-carto
> deals with layers, which might be quite serious job. It's just the current
> convention of showing bridges and roads, so I close it until then.
>


you mean you will be reopening this ticket later, after someone has changed
how osm-carto deals with layers? Wouldn't it make more sense to keep the
ticket open unless the situation is resolved? A complete redesign of the
whole layer code is not the only way to solve this, the bridge areas could
be included in the road bridges code / query where their layer could be
taken into account.

**Comment by rKsanu2MMYvypWePtQWM** [comment] 2018-02-12 11:59
Agree. Sweeping problems under a rug doesn't fix them.

**Comment by kocio-pl** [comment] 2018-02-12 12:07
I see the ticket system as a tool to focus on probable solutions. Just keeping the ticket open doesn't fix anything in a magic way too. 

If there is a chance to fix it, it can be reopened to show that the solution is on the way. Currently it doesn't look like, because any of the solutions mentioned are quite big in my opinion, but discussion is not locked and reopening is always possible.

**Comment by matthijsmelissen** [comment] 2018-02-12 12:12
I think @kocio-pl doesn't formulate it exactly right. The main problem is that any solution we can think off has a strong negative impact on performance and code complexity, and therefore we choose not to implement a solution to this issue.

**Comment by imagico** [comment] 2018-02-12 12:56
I think some more explanation is in order here:

Originally this issue tracker was used in the sense of the word issue tracker - to keep track of problems with the style that were considered desirable to be fixed by consensus of the style maintainers.  That means issues were closed only in one of these cases:

* they were fixed
* they were duplicates of other issues
* they were not considered desirable to be fixed by consensus of the maintainers

After the consensus principle has been dropped this changed and this issue tracker now represents more a personal todo list of the active maintainers.  In particular issues are now closed also if:

* they are considered too hard to fix by one of the maintainers
* they are considered unimportant to fix or low priority by one of the maintainers

This means if you - as a contributor here - are looking to fix issues that lie outside the scope of work of the current maintainers you need to also consider the closed issues and then of course have the problem to separate all the fixed/invalid/duplicate issues from the valid but closed ones.

The problem with that apart from the mentioned difficulty of searching the closed issues is that map users are demotivated from reporting issues they know will likely be closed because they are considered too hard to fix or unimportant.  This means the issue tracker - even including the closed issues - does not actually contain all of the noteworthy problems people have with the style.

Note this is a general comment without any prejudice regarding if this is an issue that would be desirable to fix - i have not looked at the problem in enough detail to form an opinion on that.

**Comment by kocio-pl** [comment] 2018-02-12 13:17
That sounds to me like a proper description of a current situation with tickets. I can just add that "TODO style" helps focusing on solving problems instead of reporting more of them, which I'm in favor of. Sometimes the act of closing reignites interest in solving the issue ("deadline syndrome", I would say), and I'm happy to open it then or someone else explains what I got wrong. Nobody is closing all the old issues just because of long inactivity and lack of solution, so it gives a chance to look again after some time and test one by one if this is really important enough (or maybe fixed already and nobody noticed that).

Maybe we can improve it and for example close such issues with a special tag to help searching - I can do it if anybody needs it.

**Comment by sommerluk** [comment] 2018-04-27 19:10
Duplicate of #1799 and #3203
